// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using LeaveServices.Infrastructure.Data;

#nullable disable

namespace LeaveServices.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LeaveDbContext))]
    [Migration("20260311000001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Leave Master
            modelBuilder.Entity("LeaveServices.Domain.Entities.LeaveMaster", b =>
            {
                b.Property<long>("LeaveId").HasColumnName("LEAVE_ID").HasColumnType("bigint");
                b.Property<char>("LeaveApplicableForAll").HasColumnName("LEAVE_APPLICABLEFORALL").HasColumnType("CHAR(1)");
                b.Property<char>("LeaveCarryForward").HasColumnName("LEAVE_CARRYFORWARD").HasColumnType("CHAR(1)");
                b.Property<string>("LeaveDescription").IsRequired().HasMaxLength(255).HasColumnName("LEAVE_DESCRIPTION").HasColumnType("varchar(255)");
                b.Property<char>("LeaveEncashable").HasColumnName("LEAVE_ENCASHABLE").HasColumnType("CHAR(1)");
                b.Property<char>("LeaveGenderSpecific").HasColumnName("LEAVE_GENDERSPECIFIC").HasColumnType("CHAR(1)");
                b.Property<long>("LeaveLastModifiedBy").HasColumnName("LEAVE_LASTMODIFIEDBY").HasColumnType("bigint");
                b.Property<DateTime>("LeaveLastModifiedOn").HasColumnName("LEAVE_LASTMODIFIEDON").HasColumnType("DATETIME2(3)");
                b.Property<int>("LeaveMaxDaysPL").HasColumnName("LEAVE_MAXDAYSPL").HasColumnType("int");
                b.HasKey("LeaveId");
                b.HasIndex("LeaveDescription").IsUnique().HasDatabaseName("UQ_LEAVE_DESC");
                b.ToTable("LEAVE_MASTER");
            });
#pragma warning restore 612, 618
        }
    }
}
