-- UserSecurity Module - Tables
USE [HRDB];
GO

-- Table: USER_APPSMAP
CREATE TABLE [USER_APPSMAP] (
    [USER_EMPSYSID] DECIMAL(38) NOT NULL  -- Employee Pin No,
    [USER_APPS] VARCHAR(20) NOT NULL,
    [USER_EFFDATE] DATETIME2(3) NOT NULL  -- Effective Date,
    [USER_CLSDATE] DATETIME2(3) NULL  -- Close Date,
    [USER_MODIFIEDBY] DECIMAL(38) NOT NULL  -- Last Modified By,
    [USER_MODIFIEDON] DATETIME2(3) NOT NULL  -- Last Modified On,
    [USER_HRROLEID] DECIMAL(38) NOT NULL,
    [USER_CREATEDBY] DECIMAL(38) NULL,
    [USER_CREATEDON] DATETIME2(3) NULL,
    [USER_REMARKS] VARCHAR(200) NULL,
    CONSTRAINT [PK_USER_APPSMAP] PRIMARY KEY ([USER_EMPSYSID])
);



-- Table: USER_CALENDERMAP
CREATE TABLE [USER_CALENDERMAP] (
    [USER_ROLEID] DECIMAL(38) NOT NULL,
    [CALENDAR_ID] DECIMAL(38) NOT NULL,
    [MODIFIEDBY] DECIMAL(38) NOT NULL,
    [MODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_USER_CALENDERMAP] PRIMARY KEY ([USER_ROLEID])
);



-- Table: USER_MENUMAP
CREATE TABLE [USER_MENUMAP] (
    [USER_ROLEID] DECIMAL(38) NOT NULL,
    [USER_MENUID] DECIMAL(38) NOT NULL,
    [USER_MODIFIEDBY] DECIMAL(38) NOT NULL,
    [USER_MODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_USER_MENUMAP] PRIMARY KEY ([USER_ROLEID])
);



-- Table: USER_UNITMAP
CREATE TABLE [USER_UNITMAP] (
    [ROLE_ID] DECIMAL(38) NOT NULL,
    [ROLE_APPS] VARCHAR(10) NOT NULL,
    [ROLE_EMPSYSID] DECIMAL(38) NOT NULL,
    [ROLE_ORGID] DECIMAL(38) NOT NULL,
    [ROLE_UNITALL] CHAR(1) NOT NULL,
    [ROLE_UNITID] DECIMAL(38) NULL,
    [ROLE_MENUGROUPID] DECIMAL(38) NULL,
    [ROLE_TYPE] VARCHAR(3) NOT NULL,
    [ROLE_EFFDATE] DATETIME2(3) NOT NULL,
    [ROLE_CLSDATE] DATETIME2(3) NULL,
    [ROLE_MODIFIEDBY] DECIMAL(38) NOT NULL,
    [ROLE_MODIFIEDON] DATETIME2(3) NOT NULL,
    [ROLE_REMARKS] VARCHAR(200) NULL,
    [ROLE_VTCENTRY] CHAR(1) NULL
);



-- Table: USER_UNITMAPLOG
CREATE TABLE [USER_UNITMAPLOG] (
    [ROLE_ID] DECIMAL(38) NOT NULL,
    [ROLE_APPS] VARCHAR(10) NOT NULL,
    [ROLE_EMPSYSID] DECIMAL(38) NOT NULL,
    [ROLE_ORGID] DECIMAL(38) NOT NULL,
    [ROLE_UNITALL] CHAR(1) NOT NULL,
    [ROLE_UNITID] DECIMAL(38) NULL,
    [ROLE_MENUGROUPID] DECIMAL(38) NULL,
    [ROLE_TYPE] VARCHAR(3) NOT NULL,
    [ROLE_EFFDATE] DATETIME2(3) NOT NULL,
    [ROLE_CLSDATE] DATETIME2(3) NULL,
    [ROLE_MODIFIEDBY] DECIMAL(38) NOT NULL,
    [ROLE_MODIFIEDON] DATETIME2(3) NOT NULL,
    [ROLE_REMARKS] VARCHAR(200) NULL,
    [ROLE_VTCENTRY] CHAR(1) NULL,
    [LOG_CREATEDBY] DECIMAL(22,0) NOT NULL,
    [LOG_CREATEDON] DATETIME2(3) NOT NULL
);



-- Table: USER_PROFILE_PFS
CREATE TABLE [USER_PROFILE_PFS] (
    [EM_USR_ID] VARCHAR(25) NOT NULL,
    [EM_EMP_NUM] DECIMAL(38) NOT NULL,
    [EM_UNT_COD] VARCHAR(3) NOT NULL,
    [EM_NICK_NAM] VARCHAR(65) NOT NULL,
    [EM_USR_TYP] VARCHAR(1) NOT NULL,
    [EM_EML_FLG] VARCHAR(1) NOT NULL,
    [EM_OEML_ID] VARCHAR(65) NULL,
    [EM_PEML_ID] VARCHAR(65) NULL,
    [EM_EFF_DAT] DATETIME2(3) NOT NULL,
    [EM_CLS_DAT] DATETIME2(3) NULL,
    [EM_USR_PASS] VARCHAR(50) NOT NULL,
    [EM_EMP_NAM] VARCHAR(65) NULL,
    [EM_DOB_DAT] DATETIME2(3) NULL,
    [EM_PHT_PTH] VARCHAR(200) NULL,
    [EM_DIV_NAM] VARCHAR(200) NULL,
    [EM_JOB_COD] BIGINT NULL,
    [EM_PIN_NUM] DECIMAL(20,0) NULL,
    [EM_OLD_NUM] VARCHAR(20) NULL,
    [EM_EMP_DSG] VARCHAR(100) NULL,
    [EM_FRS_NAM] VARCHAR(65) NULL,
    [EM_MID_NAM] VARCHAR(65) NULL,
    [EM_LST_NAM] VARCHAR(65) NULL,
    [EM_CUR_BUS] CHAR(9) NULL,
    [EM_REP_UNT] CHAR(3) NULL,
    [EM_CUR_GRD] VARCHAR(10) NULL,
    [EM_PRO_DAT] DATETIME2(3) NULL,
    [EM_CUR_LOC] VARCHAR(65) NULL,
    [EM_TIM_UNT] CHAR(3) NULL,
    [EM_CTC_AMT] DECIMAL(19,0) NULL,
    [EM_EMP_SEX] CHAR(1) NULL,
    [EM_APP_USR] DECIMAL(38) NULL,
    [EM_WRK_FLG] VARCHAR(1) NULL,
    [EM_SIG_PTH] VARCHAR(200) NULL,
    [EM_OUTLOOK] CHAR(1) NULL,
    [EM_REGSTATUS] CHAR(1) NOT NULL
);



-- Table: EMP_PASSWORDCHANGE
CREATE TABLE [EMP_PASSWORDCHANGE] (
    [EPWD_ID] DECIMAL(38) NOT NULL,
    [EPWD_EMPSYSID] DECIMAL(38) NOT NULL,
    [EPWD_CREATEDBY] DECIMAL(38) NOT NULL,
    [EPWD_CREATEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_EMP_PASSWORDCHANGE] PRIMARY KEY ([EPWD_ID])
);



-- Table: USER_CALENDERMAP_LOG
CREATE TABLE [USER_CALENDERMAP_LOG] (
    [USER_ROLEID] DECIMAL(38) NOT NULL,
    [CALENDAR_ID] DECIMAL(38) NOT NULL,
    [CLSDATE] DATETIME2(3) NULL,
    [MODIFIEDBY] DECIMAL(38) NOT NULL,
    [MODIFIEDON] DATETIME2(3) NOT NULL,
    [LOGCREATED_BY] DECIMAL(38) NOT NULL,
    [LOGCREATED_ON] DATETIME2(3) NOT NULL
);



-- Table: USER_MENUMAP_LOG
CREATE TABLE [USER_MENUMAP_LOG] (
    [USER_ROLEID] DECIMAL(38) NOT NULL,
    [USER_MENUID] DECIMAL(38) NOT NULL,
    [USER_MODIFIEDBY] DECIMAL(38) NOT NULL,
    [USER_MODIFIEDON] DATETIME2(3) NOT NULL,
    [LOG_CREATEDBY] DECIMAL(38) NOT NULL,
    [LOG_CREATEDON] DATETIME2(3) NOT NULL
);

