// <auto-generated />
using System;
using LookupService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LookupService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LookupDbContext))]
    partial class LookupDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LookupService.Domain.Entities.LovMaster", b =>
                {
                    b.Property<long>("LovId")
                        .HasColumnType("bigint")
                        .HasColumnName("LOV_ID");

                    b.Property<string>("LovName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LOV_NAME");

                    b.Property<string>("LovType")
                        .HasColumnType("char(3)")
                        .HasColumnName("LOV_TYPE");

                    b.HasKey("LovId");

                    b.HasIndex("LovType");

                    b.ToTable("LOV_MASTER", (string)null);
                });

            modelBuilder.Entity("LookupService.Domain.Entities.LovPanelMap", b =>
                {
                    b.Property<long>("LpLovId")
                        .HasColumnType("bigint")
                        .HasColumnName("LP_LOVID");

                    b.Property<decimal>("LpPanelId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("LP_PANELID");

                    b.Property<string>("LpFlag")
                        .HasColumnType("char(1)")
                        .HasColumnName("LP_FLAG");

                    b.HasKey("LpLovId", "LpPanelId");

                    b.HasIndex("LpPanelId");

                    b.ToTable("LOV_PANELMAP", (string)null);
                });

            modelBuilder.Entity("LookupService.Domain.Entities.LovTypeMaster", b =>
                {
                    b.Property<string>("LovTypeCode")
                        .HasColumnType("char(3)")
                        .HasColumnName("LOV_TYPECODE");

                    b.Property<string>("LovTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LOV_TYPENAME");

                    b.HasKey("LovTypeCode");

                    b.ToTable("LOV_TYPEMASTER", (string)null);
                });

            modelBuilder.Entity("LookupService.Domain.Entities.LovUnitMap", b =>
                {
                    b.Property<decimal>("LuMapId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("LU_MAPID");

                    b.Property<string>("LuFlag")
                        .HasColumnType("char(1)")
                        .HasColumnName("LU_FLAG");

                    b.Property<long?>("LuLovId")
                        .HasColumnType("bigint")
                        .HasColumnName("LU_LOVID");

                    b.Property<string>("LuUnitCode")
                        .HasColumnType("char(3)")
                        .HasColumnName("LU_UNITCODE");

                    b.HasKey("LuMapId");

                    b.HasIndex("LuLovId");

                    b.ToTable("LOV_UNITMAP", (string)null);
                });

            modelBuilder.Entity("LookupService.Domain.Entities.PanelMaster", b =>
                {
                    b.Property<decimal>("PanelId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("PANEL_ID");

                    b.Property<string>("PanelName")
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)")
                        .HasColumnName("PANEL_NAME");

                    b.HasKey("PanelId");

                    b.ToTable("PANEL_MAST", (string)null);
                });

            modelBuilder.Entity("LookupService.Domain.Entities.ProcessMaster", b =>
                {
                    b.Property<decimal>("ProcessId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("PROCESS_ID");

                    b.Property<string>("ProcessLivFlag")
                        .HasColumnType("char(1)")
                        .HasColumnName("PROCESS_LIVFLAG");

                    b.Property<string>("ProcessName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PROCESS_NAME");

                    b.HasKey("ProcessId");

                    b.ToTable("PROCESS_MASTER", (string)null);
                });

            modelBuilder.Entity("LookupService.Domain.Entities.UnitLovAccessDetail", b =>
                {
                    b.Property<decimal>("UdAccessDetId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("UD_ACCESSDETID");

                    b.Property<decimal?>("UdAccessMastId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("UD_ACCESSMASTID");

                    b.Property<string>("UdAccessType")
                        .HasColumnType("char(2)")
                        .HasColumnName("UD_ACCESSTYPE");

                    b.Property<string>("UdClsDat")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("UD_CLS_DAT");

                    b.Property<string>("UdEffDat")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("UD_EFF_DAT");

                    b.Property<string>("UdEmpSysId")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("UD_EMPSYSID");

                    b.Property<decimal?>("UdEscDays")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("UD_ESCDAYS");

                    b.Property<decimal?>("UdUpdatedBy")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("UD_UPDATEDBY");

                    b.Property<DateTime?>("UdUpdatedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("UD_UPDATEDON");

                    b.HasKey("UdAccessDetId");

                    b.HasIndex("UdAccessMastId");

                    b.ToTable("UNITLOV_ACCESSDET", (string)null);
                });

            modelBuilder.Entity("LookupService.Domain.Entities.UnitLovAccessMaster", b =>
                {
                    b.Property<decimal>("UaAccessMastId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("UA_ACCESSMASTID");

                    b.Property<decimal?>("UaDepartmentId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("UA_DEPARTMENTID");

                    b.Property<decimal?>("UaProcessId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("UA_PROCESSID");

                    b.Property<decimal?>("UaUnitLovMapId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("UA_UNITLOVMAPID");

                    b.HasKey("UaAccessMastId");

                    b.HasIndex("UaProcessId");

                    b.HasIndex("UaUnitLovMapId");

                    b.ToTable("UNITLOV_ACCESSMAST", (string)null);
                });

            modelBuilder.Entity("LookupService.Domain.Entities.UnitProcessMap", b =>
                {
                    b.Property<decimal>("UpMapId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("UP_MAPID");

                    b.Property<decimal?>("UpProcessId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("UP_PROCESS_ID");

                    b.Property<string>("UpUnitCode")
                        .HasColumnType("char(3)")
                        .HasColumnName("UP_UNIT_CODE");

                    b.HasKey("UpMapId");

                    b.HasIndex("UpProcessId");

                    b.ToTable("UNIT_PROCESS_MAP", (string)null);
                });

            modelBuilder.Entity("LookupService.Domain.Entities.LovMaster", b =>
                {
                    b.HasOne("LookupService.Domain.Entities.LovTypeMaster", "LovTypeMasterNavigation")
                        .WithMany("LovMasters")
                        .HasForeignKey("LovType");

                    b.Navigation("LovTypeMasterNavigation");
                });

            modelBuilder.Entity("LookupService.Domain.Entities.LovPanelMap", b =>
                {
                    b.HasOne("LookupService.Domain.Entities.LovMaster", "LovMaster")
                        .WithMany("PanelMappings")
                        .HasForeignKey("LpLovId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LookupService.Domain.Entities.PanelMaster", "PanelMaster")
                        .WithMany("PanelMappings")
                        .HasForeignKey("LpPanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LovMaster");

                    b.Navigation("PanelMaster");
                });

            modelBuilder.Entity("LookupService.Domain.Entities.LovUnitMap", b =>
                {
                    b.HasOne("LookupService.Domain.Entities.LovMaster", "LovMaster")
                        .WithMany("UnitMappings")
                        .HasForeignKey("LuLovId");

                    b.Navigation("LovMaster");
                });

            modelBuilder.Entity("LookupService.Domain.Entities.UnitLovAccessDetail", b =>
                {
                    b.HasOne("LookupService.Domain.Entities.UnitLovAccessMaster", "AccessMaster")
                        .WithMany("AccessDetails")
                        .HasForeignKey("UdAccessMastId");

                    b.Navigation("AccessMaster");
                });

            modelBuilder.Entity("LookupService.Domain.Entities.UnitLovAccessMaster", b =>
                {
                    b.HasOne("LookupService.Domain.Entities.ProcessMaster", "ProcessMaster")
                        .WithMany("AccessMasters")
                        .HasForeignKey("UaProcessId");

                    b.HasOne("LookupService.Domain.Entities.LovUnitMap", "UnitLovMap")
                        .WithMany()
                        .HasForeignKey("UaUnitLovMapId");

                    b.Navigation("ProcessMaster");

                    b.Navigation("UnitLovMap");
                });

            modelBuilder.Entity("LookupService.Domain.Entities.UnitProcessMap", b =>
                {
                    b.HasOne("LookupService.Domain.Entities.ProcessMaster", "ProcessMaster")
                        .WithMany("UnitProcessMaps")
                        .HasForeignKey("UpProcessId");

                    b.Navigation("ProcessMaster");
                });

            modelBuilder.Entity("LookupService.Domain.Entities.LovMaster", b =>
                {
                    b.Navigation("PanelMappings");

                    b.Navigation("UnitMappings");
                });

            modelBuilder.Entity("LookupService.Domain.Entities.LovTypeMaster", b =>
                {
                    b.Navigation("LovMasters");
                });

            modelBuilder.Entity("LookupService.Domain.Entities.PanelMaster", b =>
                {
                    b.Navigation("PanelMappings");
                });

            modelBuilder.Entity("LookupService.Domain.Entities.ProcessMaster", b =>
                {
                    b.Navigation("AccessMasters");

                    b.Navigation("UnitProcessMaps");
                });

            modelBuilder.Entity("LookupService.Domain.Entities.UnitLovAccessMaster", b =>
                {
                    b.Navigation("AccessDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
