apiVersion: v1
kind: ConfigMap
metadata:
  name: srfsparsh-config
  namespace: srfsparsh
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  SQL_SERVER_HOST: "sqlserver"
  SQL_SERVER_DB: "SRFSPARSHDB"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
