apiVersion: v1
kind: Secret
metadata:
  name: srfsparsh-secrets
  namespace: srfsparsh
type: Opaque
stringData:
  sql-sa-password: "SRFSparsh@2026!Secure"
  rabbitmq-password: "SRFSparsh@RMQ2026"
  redis-password: "SRFSparsh@Redis2026"
  jwt-secret-key: "SRFSparshMicroservices_JWT_SuperSecret_Key_2026!@#MinLength32"
  azure-blob-connection: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1"
