// <auto-generated />
using System;
using BookingService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingService.Infrastructure.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260315032042_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingService.Domain.Entities.BookAttendee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ATTENDEE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("REGISTERED")
                        .HasColumnName("ATTENDANCE_STATUS");

                    b.Property<int>("AttendeeSerial")
                        .HasColumnType("int")
                        .HasColumnName("ATTENDEE_SERIAL");

                    b.Property<long>("AttendeeSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("ATTENDEE_SYSID");

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("BOOKING_ID");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_ON");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_ON");

                    b.HasKey("Id");

                    b.HasIndex("AttendeeSysId");

                    b.HasIndex("BookingId");

                    b.HasIndex("BookingId", "AttendeeSysId")
                        .IsUnique();

                    b.ToTable("BOOK_ATTENDEES", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.BookMain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("BOOKING_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BookingAppNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BOOKING_APPNO");

                    b.Property<DateTime?>("BookingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("BOOKING_DATE");

                    b.Property<string>("BookingTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("BOOKING_TITLE");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_ON");

                    b.Property<string>("LocationCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LOCATION_CODE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("BOOKING_STATUS");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_ON");

                    b.HasKey("Id");

                    b.HasIndex("BookingAppNo")
                        .IsUnique();

                    b.ToTable("BOOK_MAIN", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.BookRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("BOOK_REC_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("BOOKING_ID");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_ON");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LOCATION_CODE");

                    b.Property<string>("RecDetails")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("REC_DETAILS");

                    b.Property<string>("RecStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("REC_STATUS");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_ON");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("LocationCode");

                    b.ToTable("BOOK_REC", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.BookAttendee", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.BookMain", null)
                        .WithMany("Attendees")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingService.Domain.Entities.BookRecord", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.BookMain", null)
                        .WithMany("Records")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingService.Domain.Entities.BookMain", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
