-- ==========================================
-- AUDIT Module - Table Scripts
-- Database: MYWORKDB
-- Module: AUDIT
-- Description: Audit Management and Good Practices Module
-- Created: March 9, 2026
-- ==========================================

USE MYWORKDB;
GO

-- =====================================================
-- AUDIT Core Tables
-- =====================================================

-- Table: AUDIT_GOODPRACTICE - AUDIT PRACTICE
CREATE TABLE [AUDIT_GOODPRACTICE] (
    [PRACTICE_ID] BIGINT NOT NULL  -- Good Practice ID,
    [PRACTICE_TITLE] VARCHAR(200) NOT NULL  -- Title,
    [PRACTICE_DESCRIPTION] NVARCHAR(MAX) NOT NULL  -- Description,
    [PRACTICE_BENEFITS] VARCHAR(200) NOT NULL  -- Benefits,
    [PRACTICE_REMARKS] NVARCHAR(MAX) NOT NULL  -- Remarks,
    [PRACTICE_PROCESS] BIGINT NOT NULL  -- Process ID,
    [PRACTICE_EMPSYSID] BIGINT NOT NULL  -- Employee System ID,
    [PRACTICE_UNIT] BIGINT NOT NULL  -- Unit,
    [PRACTICE_LASTMODIFIEDBY] BIGINT NOT NULL  -- Last modified By,
    [PRACTICE_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last modified On,
    [PRACTICE_ATTACHMENT1] VARCHAR(200) NULL  -- Attachment - 1,
    [PRACTICE_ATTACHMENT2] VARCHAR(200) NULL  -- Attachment - 2,
    CONSTRAINT [PK_AUDIT_GOODPRACTICE] PRIMARY KEY ([PRACTICE_ID])
);

-- Table: AUDIT_GOODPRACTICERATING - AUDIT RATING
CREATE TABLE [AUDIT_GOODPRACTICERATING] (
    [PRACTICE_RATINGID] BIGINT NOT NULL  -- Practice RatingID,
    [PRACTICE_ID] BIGINT NOT NULL  -- Practice ID,
    [PRACTICE_RATINGBY] BIGINT NOT NULL  -- Rating By,
    [PRACTICE_RATING] INT NOT NULL  -- Rating On,
    [PRACTICE_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last Modifeid on,
    CONSTRAINT [PK_AUDIT_GOODPRACTICERATING] PRIMARY KEY ([PRACTICE_RATINGID])
);

-- Table: AUDIT_MASTER - audit master
CREATE TABLE [AUDIT_MASTER] (
    [AUDIT_ID] BIGINT NOT NULL  -- Audit ID,
    [AUDIT_NAME] VARCHAR(50) NOT NULL  -- Audit Name,
    [AUDIT_UNIT] BIGINT NOT NULL  -- Reporting Unit ID,
    [AUDIT_FROM] DATETIME2(3) NOT NULL,
    [AUDIT_TO] DATETIME2(3) NOT NULL  -- Audit From,
    [AUDIT_DEFLOCATION] VARCHAR(50) NOT NULL  -- Audit To,
    [AUDIT_STATUS] CHAR(1) NOT NULL  -- Default Location,
    [AUDIT_CREATEDBY] DECIMAL(38) NOT NULL  -- Created by,
    [AUDIT_CREATEDON] DATETIME2(3) NOT NULL  -- Created on,
    [AUDIT_UPDATEDBY] DECIMAL(38) NULL  -- UPDATED BY,
    [AUDIT_UPDATEDON] DATETIME2(3) NULL  -- UPDATED ON,
    [AUDIT_PLANYEAR] DECIMAL(38) NULL  -- planned year,
    [AUDIT_FILE1] VARCHAR(500) NULL  -- Audit File1,
    [AUDIT_FILE2] VARCHAR(500) NULL  -- Audit  File1,
    [AUDIT_FILE3] VARCHAR(500) NULL  -- Audit  File2,
    [AUDIT_PLANFROM] DATETIME2(3) NOT NULL  -- audit plan from,
    [AUDIT_PLANTO] DATETIME2(3) NOT NULL  -- audit plan to,
    [AUDIT_COMPLETED] CHAR(1) NULL  -- complteed,
    [AUDIT_FIRMNAME] VARCHAR(100) NULL  -- name firm,
    [AUDIT_FIELDFROM] DATETIME2(3) NULL  -- field from,
    [AUDIT_FIELDTO] DATETIME2(3) NULL  -- filed to,
    [AUDIT_CORDID] DECIMAL(38) NULL  -- AUDIT_CORDINATOR ID,
    [AUDIT_PROCESS] BIGINT NULL  -- Process ID,
    CONSTRAINT [PK_AUDIT_MASTER] PRIMARY KEY ([AUDIT_ID])
);

-- Table: AUDIT_OBSERVATION - audit observations
CREATE TABLE [AUDIT_OBSERVATION] (
    [OBV_ID] BIGINT NOT NULL  -- Observation ID,
    [OBV_AUDITID] BIGINT NOT NULL  -- Audit ID,
    [OBV_TITLE] VARCHAR(200) NOT NULL  -- Observation Title,
    [OBV_DESCRIPTION] VARCHAR(2000) NOT NULL  -- Observation description,
    [OBV_RISK] CHAR(1) NOT NULL  -- Risk Rating (A-D) (1-4),
    [OBV_AUDITEE] BIGINT NOT NULL  -- Auditee Employee System ID,
    [OBV_ESC1] BIGINT NOT NULL  -- Escalator - 1 Employee System ID,
    [OBV_ESC2] BIGINT NOT NULL  -- Escalator - 2 Employee System ID,
    [OBV_MANCOMMENTS] VARCHAR(2000) NOT NULL  -- Management Comments,
    [OBV_IMPLICATION] VARCHAR(2000) NULL  -- Implication,
    [OBV_STATUS] CHAR(1) NOT NULL  -- P - Pending , R - Revised , C - Completed,
    [OBV_ORGDUEDATE] DATETIME2(3) NOT NULL  -- Original Due Date,
    [OBV_ORGREV1DATE] DATETIME2(3) NULL  -- Original Revised Date1,
    [OBV_ORGREV2DATE] DATETIME2(3) NULL  -- Original Revised Date2,
    [OBV_DELAY1REMARKS] VARCHAR(2000) NULL  -- Delay Remarks - for 1st revision,
    [OBV_DELAY2REMARKS] VARCHAR(2000) NULL  -- Delay Remarks - for 2nd revision,
    [OBV_CREATEDBY] BIGINT NOT NULL  -- Created by,
    [OBV_CREATEDON] DATETIME2(3) NOT NULL  -- Created on,
    [OBV_MODIFIEDBY] BIGINT NOT NULL  -- Modified by,
    [OBV_MODIFIEDON] DATETIME2(3) NOT NULL  -- Modified on,
    [OBV_COMPLETEDON] DATETIME2(3) NOT NULL  -- Completed On,
    [OBV_LOCATION] VARCHAR(200) NOT NULL  -- Location,
    [OBV_AUDITORNAME] VARCHAR(200) NOT NULL  -- Auditor Name,
    [OBV_REMARKS] VARCHAR(200) NOT NULL  -- Remarks if any,
    [OBV_APPSTATUS] CHAR(1) NULL  -- Approval Status,
    [OBV_ENTRYSTATUS] CHAR(1) NULL  -- Escalator/ Auditee  Edit Status,
    [OBV_REPEATFLAG] CHAR(1) NULL,
    [OBV_DUPFLAG] CHAR(1) NULL,
    [OBV_PROCESS] DECIMAL(38) NULL,
    CONSTRAINT [PK_AUDIT_OBSERVATION] PRIMARY KEY ([OBV_ID])
);

-- Table: AUDIT_OBSERVATIONAPP - audit observartion app
CREATE TABLE [AUDIT_OBSERVATIONAPP] (
    [APP_ID] DECIMAL(38) NOT NULL,
    [APP_OBVID] DECIMAL(38) NOT NULL,
    [APP_ESCSYSID] DECIMAL(38) NOT NULL,
    [APP_STATUS] CHAR(1) NOT NULL,
    [APP_ON] DATETIME2(3) NOT NULL,
    [APP_REMARKS] VARCHAR(200) NULL,
    [APP_OBVSTATUS] CHAR(1) NOT NULL,
    [APP_DUEDATE] DATETIME2(3) NOT NULL,
    [APP_REVDUEDATE] DATETIME2(3) NOT NULL
);

-- Table: AUDIT_PROCESS_MASTER - audit process master
CREATE TABLE [AUDIT_PROCESS_MASTER] (
    [AUDITPROCESS_ID] DECIMAL(38) NULL,
    [AUDITPROCESS_NAME] VARCHAR(50) NULL,
    [AUDITPROCESS_CREATEDBY] BIGINT NULL,
    [AUDIT_PROCESS_CREATEDON] DATETIME2(3) NULL
);

-- Table: AUDIT_USERACCESS - audit user access
CREATE TABLE [AUDIT_USERACCESS] (
    [AUC_ID] DECIMAL(38) NOT NULL,
    [AUC_EMPSYSID] DECIMAL(38) NOT NULL,
    [AUC_BUSINESSID] DECIMAL(38) NULL,
    [AUC_UNITID] DECIMAL(38) NULL,
    [AUC_CREATEDBY] DECIMAL(38) NULL,
    [AUC_CREATEDON] DATETIME2(3) NULL,
    [AUC_MODIFIEDBY] DECIMAL(38) NULL,
    [AUC_MODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_AUDIT_USERACCESS] PRIMARY KEY ([AUC_ID])
);

-- Table: AUDIT_USERMASTER - audit user master
CREATE TABLE [AUDIT_USERMASTER] (
    [AUM_EMPSYSID] DECIMAL(38) NULL,
    [AUM_LIVESTATUS] CHAR(1) NULL,
    [AUM_LASTMODIFIEDBY] DECIMAL(38) NULL,
    [AUM_LASTMODIFIEDON] DATETIME2(3) NULL,
    [AUM_MAILSTATUS] CHAR(1) NULL,
    [AUM_USERTYPE] CHAR(1) NULL,
    [AUM_HRMSOPTED] CHAR(1) NULL
);

-- Table: AUDIT_YEARMASTER - AUDIT YEAR MASTER
CREATE TABLE [AUDIT_YEARMASTER] (
    [AYM_YEARID] DECIMAL(38) NOT NULL,
    [AYM_FROM] DATETIME2(3) NOT NULL,
    [AYM_TO] DATETIME2(3) NOT NULL,
    [AYM_LASTMODIFIEDBY] DECIMAL(38) NOT NULL,
    [AYM_LASTMODIFIEDON] DATETIME2(3) NOT NULL
);

-- Table: IA_HTML_EMAIL - HTML EMAIL
CREATE TABLE [IA_HTML_EMAIL] (
    [OBV_ID] VARCHAR(100) NULL,
    [MFROM] VARCHAR(100) NULL,
    [MTO] VARCHAR(100) NULL,
    [MCC] VARCHAR(100) NULL,
    [MBCC] VARCHAR(100) NULL,
    [SUBJECT] VARCHAR(200) NULL,
    [MESSAGE] NVARCHAR(MAX) NULL,
    [MSERVER] VARCHAR(20) NULL,
    [MPORT] VARCHAR(5) NULL,
    [ONDATE] VARCHAR(100) NULL
);

-- Table: IAESCALATION_MAILS - ESCALATION MAILS
CREATE TABLE [IAESCALATION_MAILS] (
    [MAIL_ID] DECIMAL(100,0) NOT NULL,
    [MAIL_OBSERVATIONAUDITID] DECIMAL(100,0) NOT NULL,
    [MAIL_AUDITEESYSID] DECIMAL(100,0) NOT NULL,
    [MAIL_ESCALATOSYSID] DECIMAL(100,0) NOT NULL,
    [MAIL_SUBJECT] VARCHAR(1000) NOT NULL,
    [MAIL_CONTENT] NVARCHAR(MAX) NOT NULL,
    [MAIL_TO] VARCHAR(500) NOT NULL,
    [MAIL_CC] VARCHAR(500) NOT NULL,
    [MAIL_SENTBY] DECIMAL(38) NOT NULL,
    [MAIL_SENTON] DATETIME2(3) NOT NULL
);

PRINT 'AUDIT Module - Tables created successfully.';
GO
