apiVersion: v1
kind: ConfigMap
metadata:
  name: dd-erp-config
  namespace: dd-erp
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  SQL_SERVER_HOST: "sqlserver-service"
  SQL_SERVER_PORT: "1433"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  AZURITE_BLOB_ENDPOINT: "http://azurite-service:10000/devstoreaccount1"
