apiVersion: v1
kind: Secret
metadata:
  name: dd-erp-secrets
  namespace: dd-erp
type: Opaque
stringData:
  db-password: "YourStrong@Passw0rd"
  rabbitmq-user: "admin"
  rabbitmq-pass: "admin123"
  jwt-secret-key: "your-very-long-secret-key-change-this-in-production-at-least-32-characters"
