apiVersion: v1
kind: Namespace
metadata:
  name: canteen-unit-service
  labels:
    name: canteen-unit-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: canteen-unit-service-config
  namespace: canteen-unit-service
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:5190"
  Jwt__Issuer: "CanteenUnitAPI"
  Jwt__Audience: "CanteenUnitClients"
  Jwt__ExpiresInMinutes: "60"
  RabbitMQ__Host: "rabbitmq.canteen-unit-service.svc.cluster.local"
  RabbitMQ__Port: "5672"
  RabbitMQ__Username: "guest"
  RabbitMQ__VHost: "/"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft: "Warning"
