apiVersion: v1
kind: Secret
metadata:
  name: canteen-unit-service-secrets
  namespace: canteen-unit-service
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=sql-server.default.svc.cluster.local;Database=CanteenUnitDb;User Id=sa;Password=YourPassword123!;TrustServerCertificate=True;"
  Jwt__Key: "CanteenUnit-SuperSecretKey-ChangeInProduction-Min32Characters!"
  RabbitMQ__Password: "guest"
---
apiVersion: v1
kind: Secret
metadata:
  name: canteen-unit-service-docker-registry
  namespace: canteen-unit-service
type: kubernetes.io/dockercfg
data:
  .dockercfg: e30=
