-- OrganizationStructure Module - Tables
USE [HRDB];
GO

-- Table: BUSINESS_MASTER
CREATE TABLE [BUSINESS_MASTER] (
    [BUSINESS_ID] DECIMAL(38) NOT NULL  -- Business ID,
    [BUSINESS_NAME] VARCHAR(50) NOT NULL  -- Business Name,
    [BUSINESS_SHTNAME] VARCHAR(10) NOT NULL  -- Business Short Name,
    [BUSINESS_CODE] CHAR(9) NOT NULL  -- Business Code for Backward compability,
    [BUSINESS_COMPID] DECIMAL(38) NOT NULL  -- Company ID / Organization ID,
    [BUSINESS_COMP_CODE] CHAR(3) NOT NULL  -- Company Code for Backward compability,
    [BUSINESS_LIVFLAG] CHAR(1) NOT NULL  -- Business Live Flag,
    [BUSINESS_UPDATEDON] DATETIME2(3) NULL,
    [BUSINESS_UPDATEDBY] DECIMAL(22,0) NULL,
    CONSTRAINT [PK_BUSINESS_MASTER] PRIMARY KEY ([BUSINESS_ID])
);



-- Table: BUSINESS_DEPTMAP
CREATE TABLE [BUSINESS_DEPTMAP] (
    [BUSDEPT_BUSINESSID] DECIMAL(38) NOT NULL,
    [BUSDEPT_PROCESSID] DECIMAL(38) NOT NULL,
    [BUSDEPT_DEPTID] DECIMAL(38) NOT NULL,
    [BUSDEPT_UPDATEDBY] DECIMAL(38) NOT NULL,
    [BUSDEPT_UPDATEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_BUSINESS_DEPTMAP] PRIMARY KEY ([BUSDEPT_BUSINESSID])
);



-- Table: BUSINESS_DEPTMAP_LOG
CREATE TABLE [BUSINESS_DEPTMAP_LOG] (
    [BUSDEPT_BUSINESSID] DECIMAL(38) NOT NULL,
    [BUSDEPT_PROCESSID] DECIMAL(38) NOT NULL,
    [BUSDEPT_DEPTID] DECIMAL(38) NOT NULL,
    [BUSDEPT_UPDATEDBY] DECIMAL(38) NOT NULL,
    [BUSDEPT_UPDATEDON] DATETIME2(3) NOT NULL,
    [BUSDEPT_LOGCREATEDBY] DECIMAL(38) NOT NULL,
    [BUSDEPT_LOGCREATEDON] DATETIME2(3) NOT NULL
);



-- Table: BUSINESS_PROCESSMAP
CREATE TABLE [BUSINESS_PROCESSMAP] (
    [BUSPROC_BUSINESSID] DECIMAL(38) NOT NULL,
    [BUSPROC_PROCESSID] DECIMAL(38) NOT NULL,
    [BUSPROC_PROCESSCATEGORYID] DECIMAL(38) NOT NULL,
    [BUSPROC_UPDATEDBY] DECIMAL(38) NOT NULL,
    [BUSPROC_UPDATEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_BUSINESS_PROCESSMAP] PRIMARY KEY ([BUSPROC_BUSINESSID])
);



-- Table: BUSINESS_PROCESSMAP_LOG
CREATE TABLE [BUSINESS_PROCESSMAP_LOG] (
    [BUSPROC_BUSINESSID] DECIMAL(38) NOT NULL,
    [BUSPROC_PROCESSID] DECIMAL(38) NOT NULL,
    [BUSPROC_PROCESSCATEGORYID] DECIMAL(38) NOT NULL,
    [BUSPROC_UPDATEDBY] DECIMAL(38) NOT NULL,
    [BUSPROC_UPDATEDON] DATETIME2(3) NOT NULL,
    [BUSPROC_LOGCREATEDBY] DECIMAL(38) NOT NULL,
    [BUSPROC_LOGCREATEDON] DATETIME2(3) NOT NULL
);



-- Table: UNIT_MASTER
CREATE TABLE [UNIT_MASTER] (
    [UNIT_ID] DECIMAL(38) NOT NULL  -- Unit ID,
    [UNIT_NAME] VARCHAR(50) NOT NULL  -- Unit Name,
    [UNIT_SHTNAME] VARCHAR(20) NOT NULL  -- Unit Short Name,
    [UNIT_CODE] CHAR(3) NOT NULL  -- Unit code for Backward compatibility,
    [UNIT_BUSINESSID] DECIMAL(38) NOT NULL  -- Unit Business ID,
    [UNIT_BUSINESS_CODE] CHAR(9) NOT NULL  -- Unit Business Code for Backward compatibility,
    [UNIT_LIVFLAG] CHAR(1) NOT NULL  -- Unit Live Flag,
    [UNIT_UPDATEDON] DATETIME2(3) NULL,
    [UNIT_UPDATEDBY] DECIMAL(22,0) NULL,
    [UNIT_PAYFLAG] CHAR(1) NULL,
    [UNIT_PAYLIVEFLAG] CHAR(1) NULL,
    [UNIT_ORGID] DECIMAL(22,0) NOT NULL,
    [UNIT_RPTFLAG] CHAR(1) NOT NULL,
    [UNIT_REGLANGFLAG] CHAR(1) NULL,
    [UNIT_REGLANGCODE] VARCHAR(3) NULL,
    [UNIT_PFFLG] CHAR(1) NULL,
    CONSTRAINT [PK_UNIT_MASTER] PRIMARY KEY ([UNIT_ID])
);



-- Table: UNIT_COST_MAP
CREATE TABLE [UNIT_COST_MAP] (
    [UNIT_CODE] CHAR(3) NOT NULL  -- Unit Code,
    [COST_ID] DECIMAL(38) NOT NULL  -- Cost ID,
    CONSTRAINT [PK_UNIT_COST_MAP] PRIMARY KEY ([UNIT_CODE])
);



-- Table: UNIT_DEPARTMENT_MAP
CREATE TABLE [UNIT_DEPARTMENT_MAP] (
    [UNIT_CODE] CHAR(3) NULL  -- Unit code,
    [UNIT_DEPARTMENT_ID] DECIMAL(38) NOT NULL  -- Department ID,
    [UNIT_ID] DECIMAL(38) NOT NULL,
    [UNIT_UPDATEDON] DATETIME2(3) NULL,
    [UNIT_UPDATEDBY] DECIMAL(22,0) NULL
);



-- Table: UNIT_DEPARTMENT_MAP_LOG
CREATE TABLE [UNIT_DEPARTMENT_MAP_LOG] (
    [UNIT_CODE] CHAR(3) NULL,
    [UNIT_DEPARTMENT_ID] DECIMAL(38) NOT NULL,
    [UNIT_ID] DECIMAL(38) NOT NULL,
    [UNIT_UPDATEDON] DATETIME2(3) NULL,
    [UNIT_UPDATEDBY] DECIMAL(22,0) NULL,
    [UNIT_DELETEDBY] DECIMAL(22,0) NOT NULL,
    [UNIT_DELETEDON] DATETIME2(3) NOT NULL
);



-- Table: UNIT_DIVISION_MAP
CREATE TABLE [UNIT_DIVISION_MAP] (
    [UNIT_CODE] CHAR(3) NULL  -- Unit code,
    [UNIT_DIVISION_ID] DECIMAL(38) NOT NULL  -- Division ID,
    [UNIT_ID] DECIMAL(38) NOT NULL,
    [UNIT_UPDATEDON] DATETIME2(3) NULL,
    [UNIT_UPDATEDBY] DECIMAL(22,0) NULL
);



-- Table: UNIT_DIVISION_MAP_LOG
CREATE TABLE [UNIT_DIVISION_MAP_LOG] (
    [UNIT_CODE] CHAR(3) NULL,
    [UNIT_DIVISION_ID] DECIMAL(38) NOT NULL,
    [UNIT_ID] DECIMAL(38) NOT NULL,
    [UNIT_UPDATEDON] DATETIME2(3) NULL,
    [UNIT_UPDATEDBY] DECIMAL(22,0) NULL,
    [UNIT_DELETEDBY] DECIMAL(22,0) NOT NULL,
    [UNIT_DELETEDON] DATETIME2(3) NOT NULL
);



-- Table: UNIT_GRADE_MAP
CREATE TABLE [UNIT_GRADE_MAP] (
    [UNIT_CODE] CHAR(3) NULL  -- Unit Code,
    [GRADE_ID] DECIMAL(38) NULL  -- Grade ID,
    [GRADE_DISPLAY] VARCHAR(50) NULL,
    [UNIT_ID] DECIMAL(38) NOT NULL,
    [UNIT_UPDATEDON] DATETIME2(3) NULL,
    [UNIT_UPDATEDBY] DECIMAL(22,0) NULL,
    [UNIT_MAPLIVESTATUS] CHAR(1) NULL,
    [GRADE_DESIGNATION] VARCHAR(50) NULL
);



-- Table: UNIT_GRADE_MAP_LOG
CREATE TABLE [UNIT_GRADE_MAP_LOG] (
    [UNIT_CODE] CHAR(3) NULL,
    [GRADE_ID] DECIMAL(38) NOT NULL,
    [GRADE_DISPLAY] VARCHAR(50) NULL,
    [UNIT_ID] DECIMAL(38) NOT NULL,
    [UNIT_UPDATEDON] DATETIME2(3) NULL,
    [UNIT_UPDATEDBY] DECIMAL(22,0) NULL,
    [UNIT_MAPLIVESTATUS] CHAR(1) NULL,
    [GRADE_DESIGNATION] VARCHAR(50) NULL,
    [UNIT_DELETEDBY] DECIMAL(22,0) NOT NULL,
    [UNIT_DELETEDON] DATETIME2(3) NOT NULL
);



-- Table: UNIT_LEADERSHIP_MAP
CREATE TABLE [UNIT_LEADERSHIP_MAP] (
    [UNITLT_EMPSYSID] DECIMAL(22,0) NOT NULL  -- Employee sysId,
    [UNITLT_UNITID] DECIMAL(22,0) NOT NULL  -- Unit Id,
    [UNITLT_LEADERTYPE] VARCHAR(3) NOT NULL  -- ULT,BLT,
    [UNITLT_EFFDATE] DATETIME2(3) NOT NULL  -- Effective Date,
    [UNITLT_CLOSEDATE] DATETIME2(3) NULL  -- Close Date,
    [UNITLT_CREATEDBY] DECIMAL(22,0) NOT NULL  -- Created By,
    [UNITLT_CREATEDON] DATETIME2(3) NOT NULL  -- Created On,
    [UNITLT_MODIFIEDBY] DECIMAL(22,0) NULL  -- Modified By,
    [UNITLT_MODIFIEDON] DATETIME2(3) NULL  -- Modified On
);



-- Table: UNIT_PROCESS_MAP
CREATE TABLE [UNIT_PROCESS_MAP] (
    [UNIT_CODE] CHAR(3) NULL  -- Unit code,
    [PROCESS_ID] DECIMAL(38) NOT NULL  -- Process ID,
    [UNIT_ID] DECIMAL(38) NOT NULL,
    [UNIT_UPDATEDON] DATETIME2(3) NULL,
    [UNIT_UPDATEDBY] DECIMAL(22,0) NULL
);



-- Table: UNIT_PROCESS_MAP_LOG
CREATE TABLE [UNIT_PROCESS_MAP_LOG] (
    [UNIT_CODE] CHAR(3) NULL,
    [PROCESS_ID] DECIMAL(38) NOT NULL,
    [UNIT_ID] DECIMAL(38) NOT NULL,
    [UNIT_UPDATEDON] DATETIME2(3) NULL,
    [UNIT_UPDATEDBY] DECIMAL(22,0) NULL,
    [UNIT_DELETEDBY] DECIMAL(22,0) NOT NULL,
    [UNIT_DELETEDON] DATETIME2(3) NOT NULL
);



-- Table: UNIT_SITE_MAP
CREATE TABLE [UNIT_SITE_MAP] (
    [UNIT_CODE] CHAR(3) NOT NULL  -- Unit Code,
    [SITE_ID] DECIMAL(38) NOT NULL  -- Site ID,
    [UNIT_ID] DECIMAL(38) NOT NULL,
    [UNIT_UPDATEDON] DATETIME2(3) NULL,
    [UNIT_UPDATEDBY] DECIMAL(22,0) NULL,
    CONSTRAINT [PK_UNIT_SITE_MAP] PRIMARY KEY ([UNIT_CODE])
);



-- Table: UNIT_SITE_MAP_LOG
CREATE TABLE [UNIT_SITE_MAP_LOG] (
    [UNIT_CODE] CHAR(3) NOT NULL,
    [SITE_ID] DECIMAL(38) NOT NULL,
    [UNIT_ID] DECIMAL(38) NOT NULL,
    [UNIT_UPDATEDON] DATETIME2(3) NULL,
    [UNIT_UPDATEDBY] DECIMAL(22,0) NULL,
    [UNIT_DELETEDBY] DECIMAL(22,0) NOT NULL,
    [UNIT_DELETEDON] DATETIME2(3) NOT NULL
);



-- Table: UNIT_GRADECAT_EXCEPTION
CREATE TABLE [UNIT_GRADECAT_EXCEPTION] (
    [UNIT_ID] DECIMAL(38) NULL  -- Unit Code,
    [GRADECAT_COD] CHAR(3) NULL  -- Grade Category,
    [GRADE_DISPLAY] VARCHAR(50) NULL  -- Grade Category Display Name,
    [UNIT_UPDATEDON] DATETIME2(3) NULL,
    [UNIT_UPDATEDBY] DECIMAL(22,0) NULL
);



-- Table: UNIT_PAYMAP
CREATE TABLE [UNIT_PAYMAP] (
    [REP_UNITID] DECIMAL(38) NOT NULL,
    [PAY_UNITID] DECIMAL(38) NOT NULL,
    [LIVE_FLG] CHAR(1) NOT NULL
);



-- Table: UNIT_ERPPRODUCTMAP
CREATE TABLE [UNIT_ERPPRODUCTMAP] (
    [UNIT_ERPID] DECIMAL(38) NOT NULL  -- Sequence ID,
    [UNIT_ERPBUSID] DECIMAL(38) NOT NULL  -- Business ID,
    [UNIT_ERPUNITID] DECIMAL(38) NOT NULL  -- (for all Unit we need to have 0 value)  UnitID,
    [UNIT_ERPPRODUCTID] VARCHAR(25) NOT NULL  -- Product Code,
    [UNIT_ERPMODIFIEDBY] DECIMAL(38) NOT NULL  -- Modified By,
    [UNIT_ERPMODIFIEDON] DATETIME2(3) NOT NULL  -- Modified On,
    CONSTRAINT [PK_UNIT_ERPPRODUCTMAP] PRIMARY KEY ([UNIT_ERPID])
);



-- Table: DEPARTMENT_MASTER
CREATE TABLE [DEPARTMENT_MASTER] (
    [DEPARTMENT_ID] DECIMAL(38) NOT NULL  -- Department ID,
    [DEPARTMENT_NAME] VARCHAR(50) NULL  -- Department Name,
    [DEPARTMENT_LIVFLAG] CHAR(1) NULL  -- Department Live Flag,
    [DEPARTMENT_UPDATEDON] DATETIME2(3) NULL,
    [DEPARTMENT_UPDATEDBY] DECIMAL(22,0) NULL,
    [DEPARTMENT_CODE] VARCHAR(50) NULL,
    CONSTRAINT [PK_DEPARTMENT_MASTER] PRIMARY KEY ([DEPARTMENT_ID])
);



-- Table: DIVISION_MASTER
CREATE TABLE [DIVISION_MASTER] (
    [DIVISION_ID] DECIMAL(38) NOT NULL  -- Division ID,
    [DIVISION_CODE] VARCHAR(3) NULL  -- Division Code,
    [DIVISION_NAME] VARCHAR(50) NULL  -- Division Name,
    [DIVISION_LIVEFLAG] CHAR(1) NULL  -- Division Live Flag,
    [DIVISION_UPDATEDON] DATETIME2(3) NULL,
    [DIVISION_UPDATEDBY] DECIMAL(22,0) NULL,
    CONSTRAINT [PK_DIVISION_MASTER] PRIMARY KEY ([DIVISION_ID])
);



-- Table: GRADE_MASTER
CREATE TABLE [GRADE_MASTER] (
    [GRADE_ID] DECIMAL(38) NOT NULL  -- Grade ID,
    [GRADE_CODE] CHAR(3) NULL  -- Grade Code,
    [GRADE_NAME] VARCHAR(50) NULL  -- Grade Name,
    [GRADE_DESIGNATION] VARCHAR(50) NULL  -- Grade Designation,
    [GRADE_CATEGORYCODE] CHAR(3) NULL  -- Grade Category,
    [GRADE_LIVFLAG] CHAR(1) NULL  -- Live Status (Y/N),
    [GRADE_MAN_COD] CHAR(3) NULL  -- Management Category (JM/MM/SM),
    [GRADE_PRIORITY] DECIMAL(38) NULL  -- Priority,
    [GRADE_SUBCAT] CHAR(3) NULL  -- Sub Category (Not Used),
    [GRADE_DEFRATING] VARCHAR(25) NULL  -- Default Rating for New Joinees,
    [GRADE_PROMSCORE] DECIMAL(38) NULL  -- Score for Promotion to Next Level,
    [GRADE_LEVELNOS] DECIMAL(38) NULL  -- Total levels in the band,
    [GRADE_CADREID] DECIMAL(38) NULL,
    CONSTRAINT [PK_GRADE_MASTER] PRIMARY KEY ([GRADE_ID])
);



-- Table: POSITION_MASTER
CREATE TABLE [POSITION_MASTER] (
    [POSITION_ID] DECIMAL(38) NOT NULL  -- Primary key for table,
    [POS_UNIT_CODE] CHAR(3) NOT NULL  -- Unit code,
    [POS_GRADE_ID] DECIMAL(38) NOT NULL  -- Grade ID,
    [POSITION_NAME] VARCHAR(100) NULL  -- Position Name,
    [POSITION_DESIGNATION] VARCHAR(100) NOT NULL  -- Position Designation,
    [POS_EFFECTIVE_DATE] DATETIME2(3) NOT NULL  -- Position Effectvie from Date,
    [POS_CLOSED_DATE] DATETIME2(3) NULL  -- Position Closure on date,
    [REFERENCE_CODE] VARCHAR(3) NOT NULL  -- Reference Transaction Code - (DIR -Direct/ MRF –From Manpower Requisition Form),
    [DELETED_FLAG] CHAR(1) NOT NULL  -- Deleted Flag  (Y/N),
    [POSITION_JD_ID] DECIMAL(38) NULL  -- JD Attachement File name,
    [ENTERED_DATE] DATETIME2(3) NOT NULL  -- Entered Date,
    [ENTERED_PIN_NO] DECIMAL(38) NOT NULL  -- Entered PIN No,
    [CTC] DECIMAL(38) NULL  -- CTC in lacs,
    [PROCESS_ID] DECIMAL(38) NULL,
    [REASON_ID] DECIMAL(38) NULL,
    [REPLACE_POSID] DECIMAL(38) NULL,
    [POS_MODIFIED_BY] DECIMAL(38) NULL,
    [POS_MODIFIED_ON] DATETIME2(3) NULL,
    [POS_UNIT_ID] DECIMAL(38) NULL,
    [POS_REFNO] BIGINT NULL,
    [POS_EVEGRADE_ID] BIGINT NOT NULL  -- Orginal Evaluated Grade ID,
    [POSITION_EVEDESIGNATION] VARCHAR(100) NOT NULL  -- Orginal Evaluated Designation,
    CONSTRAINT [PK_POSITION_MASTER] PRIMARY KEY ([POSITION_ID])
);



-- Table: SITE_MASTER
CREATE TABLE [SITE_MASTER] (
    [SITE_ID] DECIMAL(38) NOT NULL  -- Site ID,
    [SITE_NAME] VARCHAR(200) NULL  -- Site Name,
    [SITE_SHORT_NAME] VARCHAR(200) NULL  -- Site Short Name,
    [SITE_ADDRESS_LINE_1] VARCHAR(200) NULL  -- Site Address Line 1,
    [SITE_ADDRESS_LINE_2] VARCHAR(200) NULL  -- Site Address Line 2,
    [SITE_ADDRESS_LINE_3] VARCHAR(200) NULL  -- Site Address Line 3,
    [SITE_ADDRESS_LINE_4] VARCHAR(200) NULL  -- Site Address Line 4,
    [SITE_ADDRESS_PIN] VARCHAR(50) NULL  -- Site Pin Code,
    [SITE_CITY_CODE] DECIMAL(38) NOT NULL  -- Site City Code,
    [SITE_CATEGORY_CODE] DECIMAL(38) NOT NULL  -- Site Category,
    [SITE_PHONE_1] VARCHAR(200) NULL  -- Phone No 1,
    [SITE_PHONE_2] VARCHAR(200) NULL  -- Phone No 2,
    [SITE_FAXNO] VARCHAR(200) NULL  -- Fax No,
    [SITE_LANDMARK_1] VARCHAR(200) NULL  -- Landmark 1,
    [SITE_LANDMARK_2] VARCHAR(200) NULL  -- Landmark 2,
    [SITE_IMAGEPATH] VARCHAR(200) NULL  -- Image Path,
    [SITE_VISITORPOLICYPATH] VARCHAR(200) NULL  -- Visitor Policy Path,
    [SITE_NEARESTAIRPORT] VARCHAR(200) NULL  -- Nearest Airport,
    [SITE_DISTANCEAIRPORT] VARCHAR(200) NULL  -- Distance to Nearest Airport,
    [SITE_NEARESTRAIL] VARCHAR(200) NULL  -- Nearest Station,
    [SITE_DISTANCERAIL] VARCHAR(200) NULL  -- Distance to Nearest Station,
    [SITE_REMARKS] VARCHAR(200) NULL  -- Remarks,
    [SITE_LOCATION_CODE] DECIMAL(38) NULL  -- Location Code,
    [SITE_ATTACHEDEMPLOYEE] CHAR(1) NOT NULL  -- Attached to Employee,
    [SITE_CONTACT_NAME1] VARCHAR(200) NULL  -- Contact Person Name -1,
    [SITE_CONTACT_PHONE1] VARCHAR(200) NULL  -- Contact Phone - 1,
    [SITE_CONTACT_NAME2] VARCHAR(200) NULL  -- Contact Person Name -2,
    [SITE_CONTACT_PHONE2] VARCHAR(200) NULL  -- Contact Phone - 1,
    [SITE_LIVFLAG] CHAR(1) NULL  -- Site Live Flag,
    [SITE_TRAVELLOCID] BIGINT NULL,
    CONSTRAINT [PK_SITE_MASTER] PRIMARY KEY ([SITE_ID])
);



-- Table: LOCATION_MASTER
CREATE TABLE [LOCATION_MASTER] (
    [LOCATION_CODE] DECIMAL(38) NOT NULL  -- Location Code,
    [LOCATION_NAME] VARCHAR(200) NULL  -- Location Name,
    [LOCATION_REGION_CODE] DECIMAL(38) NOT NULL  -- Location Region Code,
    [LOCATION_UPDATEDON] DATETIME2(3) NULL,
    [LOCATION_UPDATEDBY] DECIMAL(22,0) NULL,
    CONSTRAINT [PK_LOCATION_MASTER] PRIMARY KEY ([LOCATION_CODE])
);



-- Table: REGION_MASTER
CREATE TABLE [REGION_MASTER] (
    [REGION_CODE] DECIMAL(38) NOT NULL  -- Region Code,
    [REGION_NAME] VARCHAR(200) NULL  -- Region Name,
    [REGION_COUNTRY_CODE] DECIMAL(38) NOT NULL  -- Region Country Code,
    [REGION_UPDATEDON] DATETIME2(3) NULL,
    [REGION_UPDATEDBY] DECIMAL(22,0) NULL,
    CONSTRAINT [PK_REGION_MASTER] PRIMARY KEY ([REGION_CODE])
);



-- Table: STATE_MASTER
CREATE TABLE [STATE_MASTER] (
    [STATE_CODE] DECIMAL(38) NOT NULL  -- State Code,
    [STATE_NAME] VARCHAR(200) NULL  -- State Name,
    [STATE_COUNTRY_CODE] DECIMAL(38) NULL  -- State Country Code,
    [STATE_UPDATEDON] DATETIME2(3) NULL,
    [STATE_UPDATEDBY] DECIMAL(22,0) NULL
);



-- Table: SITECATEGORY_MAST
CREATE TABLE [SITECATEGORY_MAST] (
    [CATEGORY_CODE] DECIMAL(38) NOT NULL  -- Category Code,
    [CATEGORY_NAME] VARCHAR(200) NULL  -- Category Name,
    [CATEGORY_UPDATEDON] DATETIME2(3) NULL,
    [CATEGORY_UPDATEDBY] DECIMAL(22,0) NULL,
    CONSTRAINT [PK_SITECATEGORY_MAST] PRIMARY KEY ([CATEGORY_CODE])
);



-- Table: LOV_MASTER
CREATE TABLE [LOV_MASTER] (
    [LOV_TYPE] CHAR(3) NULL  -- LOV Type,
    [LOV_ID] DECIMAL(38) NOT NULL  -- LOV Code,
    [LOV_NAME] VARCHAR(200) NULL  -- LOV Name,
    [LOV_UPDATEDBY] DECIMAL(38) NULL,
    [LOV_UPDATEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_LOV_MASTER] PRIMARY KEY ([LOV_ID])
);



-- Table: LOV_TYPEMASTER
CREATE TABLE [LOV_TYPEMASTER] (
    [LOV_TYPECODE] CHAR(3) NOT NULL  -- LOV Type Code,
    [LOV_TYPENAME] VARCHAR(50) NULL  -- LOV Type Name,
    [LOV_REGFLAG] CHAR(1) NOT NULL,
    CONSTRAINT [PK_LOV_TYPEMASTER] PRIMARY KEY ([LOV_TYPECODE])
);



-- Table: LOV_UNITMAP
CREATE TABLE [LOV_UNITMAP] (
    [LOV_ID] DECIMAL(38) NOT NULL  -- LOV ID,
    [LOV_UNIT] CHAR(3) NOT NULL  -- Unit Code,
    CONSTRAINT [PK_LOV_UNITMAP] PRIMARY KEY ([LOV_ID])
);



-- Table: HRROLE_MASTER
CREATE TABLE [HRROLE_MASTER] (
    [HRROLE_ID] DECIMAL(38) NOT NULL,
    [HRROLE_CODE] VARCHAR(3) NOT NULL,
    [HRROLE_NAME] VARCHAR(20) NOT NULL,
    CONSTRAINT [PK_HRROLE_MASTER] PRIMARY KEY ([HRROLE_ID])
);



-- Table: LEVEL_MASTER
CREATE TABLE [LEVEL_MASTER] (
    [LEVEL_ID] DECIMAL(38) NOT NULL  -- Level ID,
    [LEVEL_NAME] VARCHAR(50) NULL  -- Level Name,
    [LEVEL_DESIGNATION] VARCHAR(50) NULL  -- Designation,
    [LEVEL_GRADEID] DECIMAL(38) NULL  -- Grade ID,
    [LEVEL_LIVEFLAG] CHAR(1) NULL  -- Live Status,
    [LEVEL_PRIORITY] DECIMAL(38) NULL  -- Priority within the Grade (1,2,3),
    [LEVEL_LASTUPDATEDBY] DECIMAL(38) NULL  -- Last Updated By,
    [LEVEL_LASTUPDATEDON] DATETIME2(3) NULL  -- Last Updated On,
    CONSTRAINT [PK_LEVEL_MASTER] PRIMARY KEY ([LEVEL_ID])
);



-- Table: LEVEL_GRADEMAP
CREATE TABLE [LEVEL_GRADEMAP] (
    [LEVEL_ID] DECIMAL(38) NOT NULL,
    [GRADE_ID] DECIMAL(38) NOT NULL,
    CONSTRAINT [PK_LEVEL_GRADEMAP] PRIMARY KEY ([LEVEL_ID])
);

