-- ==========================================
-- ORDER SCHEDULING MODULE - Table Definitions
-- Database: SCIDB
-- Module: Order Management & Scheduling
-- Created: March 9, 2026
-- ==========================================

USE SCIDB;
GO

-- Table: OS_ACTUAL_ORDER
CREATE TABLE [OS_ACTUAL_ORDER] (
    [LINE_ID] DECIMAL(38) NOT NULL,
    [HEADER_ID] DECIMAL(38) NOT NULL,
    [ORDERED_ITEM] VARCHAR(2000) NULL,
    [ORDERED_ITEM_ID] DECIMAL(38) NULL,
    [REQUEST_DATE] DATETIME2(3) NULL,
    [SCHEDULE_SHIP_DATE] DATETIME2(3) NULL,
    [ORDERED_QUANTITY] DECIMAL(38) NULL,
    [ORDER_QUANTITY_UOM] VARCHAR(3) NULL,
    [CANCELLED_QUANTITY] DECIMAL(38) NULL,
    [FULFILLED_QUANTITY] DECIMAL(38) NULL,
    [SHIPPING_QUANTITY] DECIMAL(38) NULL,
    [SHIPPING_QUANTITY_UOM] VARCHAR(3) NULL,
    [INVOICED_QUANTITY] DECIMAL(38) NULL,
    [SHIP_FROM_ORG_ID] DECIMAL(38) NULL,
    [SOLD_FROM_ORG_ID] DECIMAL(38) NULL,
    [ACTUAL_SHIPMENT_DATE] DATETIME2(3) NULL,
    [ORDERED_DATE] DATETIME2(3) NULL,
    [ORDER_SOURCE_ID] DECIMAL(38) NULL,
    [ORDER_NUMBER] DECIMAL(38) NOT NULL,
    [CUST_PO_NUMBER] VARCHAR(50) NULL,
    [SOLD_TO_ORG_ID] DECIMAL(38) NULL,
    [CUSTOMER_NAME] VARCHAR(50) NULL,
    [SHIP_TO_ORG_ID] DECIMAL(38) NULL,
    [CONSIGNEE_NAME] VARCHAR(50) NULL,
    CONSTRAINT [PK_OS_ACTUAL_ORDER] PRIMARY KEY ([ORDER_NUMBER], [LINE_ID])
);

-- Table: OS_ACTUAL_ORDER_TIED
CREATE TABLE [OS_ACTUAL_ORDER_TIED] (
    [LINE_ID] DECIMAL(38) NOT NULL,
    [HEADER_ID] DECIMAL(38) NOT NULL,
    [ORDERED_ITEM] VARCHAR(2000) NULL,
    [ORDERED_ITEM_ID] DECIMAL(38) NULL,
    [REQUEST_DATE] DATETIME2(3) NULL,
    [SCHEDULE_SHIP_DATE] DATETIME2(3) NULL,
    [ORDERED_QUANTITY] DECIMAL(38) NULL,
    [ORDER_QUANTITY_UOM] VARCHAR(3) NULL,
    [CANCELLED_QUANTITY] DECIMAL(38) NULL,
    [FULFILLED_QUANTITY] DECIMAL(38) NULL,
    [SHIPPING_QUANTITY] DECIMAL(38) NULL,
    [SHIPPING_QUANTITY_UOM] VARCHAR(3) NULL,
    [INVOICED_QUANTITY] DECIMAL(38) NULL,
    [SHIP_FROM_ORG_ID] DECIMAL(38) NULL,
    [SOLD_FROM_ORG_ID] DECIMAL(38) NULL,
    [ACTUAL_SHIPMENT_DATE] DATETIME2(3) NULL,
    [ORDERED_DATE] DATETIME2(3) NULL,
    [ORDER_SOURCE_ID] DECIMAL(38) NULL,
    [ORDER_NUMBER] DECIMAL(38) NOT NULL,
    [CUST_PO_NUMBER] VARCHAR(50) NULL,
    [SOLD_TO_ORG_ID] DECIMAL(38) NULL,
    [CUSTOMER_NAME] VARCHAR(50) NULL,
    [SHIP_TO_ORG_ID] DECIMAL(38) NULL,
    [CONSIGNEE_NAME] VARCHAR(50) NULL
);

-- Table: OS_ACTUAL_ORDER_UNIT
CREATE TABLE [OS_ACTUAL_ORDER_UNIT] (
    [LINE_ID] DECIMAL(38) NOT NULL,
    [HEADER_ID] DECIMAL(38) NOT NULL,
    [ORDERED_ITEM] VARCHAR(2000) NULL,
    [ORDERED_ITEM_ID] DECIMAL(38) NULL,
    [REQUEST_DATE] DATETIME2(3) NULL,
    [SCHEDULE_SHIP_DATE] DATETIME2(3) NULL,
    [ORDERED_QUANTITY] DECIMAL(38) NULL,
    [ORDER_QUANTITY_UOM] VARCHAR(3) NULL,
    [CANCELLED_QUANTITY] DECIMAL(38) NULL,
    [FULFILLED_QUANTITY] DECIMAL(38) NULL,
    [SHIPPING_QUANTITY] DECIMAL(38) NULL,
    [SHIPPING_QUANTITY_UOM] VARCHAR(3) NULL,
    [INVOICED_QUANTITY] DECIMAL(38) NULL,
    [SHIP_FROM_ORG_ID] DECIMAL(38) NULL,
    [SOLD_FROM_ORG_ID] DECIMAL(38) NULL,
    [ACTUAL_SHIPMENT_DATE] DATETIME2(3) NULL,
    [ORDERED_DATE] DATETIME2(3) NULL,
    [ORDER_SOURCE_ID] DECIMAL(38) NULL,
    [ORDER_NUMBER] DECIMAL(38) NOT NULL,
    [CUST_PO_NUMBER] VARCHAR(50) NULL,
    [SOLD_TO_ORG_ID] DECIMAL(38) NULL,
    [CUSTOMER_NAME] VARCHAR(50) NULL,
    [SHIP_TO_ORG_ID] DECIMAL(38) NULL,
    [CONSIGNEE_NAME] VARCHAR(50) NULL
);

-- Table: OS_ACTUAL_ORDER_PROCESS
CREATE TABLE [OS_ACTUAL_ORDER_PROCESS] (
    [LINE_ID] DECIMAL(38) NOT NULL,
    [HEADER_ID] DECIMAL(38) NOT NULL,
    [ORDERED_ITEM] VARCHAR(255) NULL,
    [ORDERED_ITEM_ID] INT NULL,
    [REQUEST_DATE] CHAR(8) NULL,
    [SCHEDULE_SHIP_DATE] DATETIME2(3) NULL,
    [ORDERED_QUANTITY] CHAR(1) NULL,
    [ORDER_QUANTITY_UOM] VARCHAR(3) NULL,
    [CANCELLED_QUANTITY] CHAR(1) NULL,
    [FULFILLED_QUANTITY] CHAR(1) NULL,
    [SHIPPING_QUANTITY] CHAR(1) NULL,
    [SHIPPING_QUANTITY_UOM] VARCHAR(3) NULL,
    [INVOICED_QUANTITY] CHAR(1) NULL,
    [ACTUAL_SHIPMENT_DATE] DATETIME2(3) NULL,
    [ORDERED_DATE] CHAR(1) NULL,
    [ORDER_SOURCE_ID] DECIMAL(38) NULL,
    [ORDER_NUMBER] DECIMAL(38) NOT NULL,
    [CUST_PO_NUMBER] VARCHAR(50) NULL,
    [CUSTOMER_NAME] DECIMAL(38) NOT NULL,
    [SHIP_TO_ORG_ID] DECIMAL(38) NOT NULL
);

-- Table: OS_ACTUAL_ORDER_SCHEDULE
CREATE TABLE [OS_ACTUAL_ORDER_SCHEDULE] (
    [CTORDER_ID] DECIMAL(38) NOT NULL,
    [LINE_ID] DECIMAL(38) NOT NULL,
    [ORDERED_ITEM_ID] DECIMAL(38) NULL,
    [NEW_SCHEDULE_DATE] DATETIME2(3) NULL,
    [NEW_FILL_QTY] INT NULL,
    [FILLING_ALLOTED] INT NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_OS_ACTUAL_ORDER_SCHEDULE] PRIMARY KEY ([CTORDER_ID], [LINE_ID])
);

-- Table: OS_TIED_ORDER_HEADER
CREATE TABLE [OS_TIED_ORDER_HEADER] (
    [TIED_ORDER_ID] DECIMAL(38) NOT NULL,
    [CUSTOMER_CODE] VARCHAR(100) NULL,
    [ORDERED_DATE] DATETIME2(3) NULL,
    [COMPANY_UNIT_ID] DECIMAL(38) NOT NULL,
    [RECORD_STATUS] CHAR(1) NULL,
    [MODIFIED_SCI_USER_ID] VARCHAR(255) NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL,
    [ORDNUMBER_CODE] VARCHAR(10) NULL,
    [LCNUMBER] VARCHAR(255) NULL,
    CONSTRAINT [PK_OS_TIED_ORDER_HEADER] PRIMARY KEY ([TIED_ORDER_ID])
);

-- Table: OS_TIED_ORDER_DETAILS
CREATE TABLE [OS_TIED_ORDER_DETAILS] (
    [TIED_ORDER_DETAIL_ID] BIGINT NOT NULL,
    [TIED_ORDER_ID] DECIMAL(38) NOT NULL,
    [SCI_ITEM_ID] DECIMAL(38) NOT NULL,
    [ORDER_QTY] BIGINT NOT NULL,
    [DISPATCH_DATE] DATETIME2(3) NULL,
    [QTY_FROM_CUR_STOCK] BIGINT NULL,
    [FILLING_ALLOTED] BIGINT NULL,
    [CANCEL_FLAG] VARCHAR(255) NULL,
    [CANCEL_DATE] DATETIME2(3) NULL,
    [CANCEL_SCI_USER_ID] INT NULL,
    [MODIFIED_SCI_USER_ID] INT NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL,
    [PRICE] DECIMAL(38) NULL,
    [SCHEDULE_FLAG] VARCHAR(255) NULL,
    [IGNORE_EMPTIES_CHECK] VARCHAR(255) NULL,
    [IGNORE_CURSTOCK] VARCHAR(255) NULL,
    CONSTRAINT [PK_OS_TIED_ORDER_DETAILS] PRIMARY KEY ([TIED_ORDER_DETAIL_ID])
);

-- Table: ACTUAL_ORDER_MAP
CREATE TABLE [ACTUAL_ORDER_MAP] (
    [TIED_ORDER_DETAIL_ID] DECIMAL(38) NULL,
    [ACTUAL_LINE_ID] DECIMAL(38) NULL,
    [MAPPING_QUANTITY] INT NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL
);

-- Table: OS_SCHEDULE_MASTER
CREATE TABLE [OS_SCHEDULE_MASTER] (
    [OS_SCHEDULE_ID] INT NOT NULL,
    [FILLING_POINT_GROUP_ID] DECIMAL(38) NOT NULL,
    [SCI_ITEM_ID] DECIMAL(38) NOT NULL,
    [ORDER_TYPE] VARCHAR(1) NULL,
    [ORDER_ID] DECIMAL(38) NULL,
    [ORDER_LINE_ID] DECIMAL(38) NULL,
    [REQUIRED_DATE] DATETIME2(3) NULL,
    [ORDER_QTY] DECIMAL(38) NULL,
    [SHIFT_CAPACITY] DECIMAL(38) NULL,
    [TOTAL_ALOTTED_QTY] DECIMAL(38) NULL,
    CONSTRAINT [PK_OS_SCHEDULE_MASTER] PRIMARY KEY ([OS_SCHEDULE_ID])
);

-- Table: OS_SCHEDULE_DETAILS
CREATE TABLE [OS_SCHEDULE_DETAILS] (
    [OS_SCHEDULE_ID] DECIMAL(38) NOT NULL,
    [FILLING_DATE] DATETIME2(3) NULL,
    [FILLING_SHIFT] CHAR(1) NULL,
    [START_TIME] VARCHAR(5) NULL,
    [END_TIME] VARCHAR(5) NULL,
    [FILL_QTY] DECIMAL(38) NULL,
    [FILLING_POINT_GROUP_ID] DECIMAL(38) NULL,
    [REF_OS_SCHEDULE_ID] DECIMAL(38) NULL
);

-- Table: OS_SP_SCHEDULE_MASTER (Special Schedule Master)
CREATE TABLE [OS_SP_SCHEDULE_MASTER] (
    [OS_SCHEDULE_ID] INT NOT NULL,
    [FILLING_POINT_GROUP_ID] DECIMAL(38) NOT NULL,
    [SCI_ITEM_ID] DECIMAL(38) NOT NULL,
    [ORDER_TYPE] VARCHAR(1) NULL,
    [ORDER_ID] DECIMAL(38) NULL,
    [ORDER_LINE_ID] DECIMAL(38) NULL,
    [REQUIRED_DATE] DATETIME2(3) NULL,
    [ORDER_QTY] DECIMAL(38) NULL,
    [SHIFT_CAPACITY] DECIMAL(38) NULL,
    [TOTAL_ALOTTED_QTY] DECIMAL(38) NULL
);

-- Table: OS_SP_SCHEDULE_DETAILS (Special Schedule Details)
CREATE TABLE [OS_SP_SCHEDULE_DETAILS] (
    [OS_SCHEDULE_ID] DECIMAL(38) NOT NULL,
    [FILLING_DATE] DATETIME2(3) NULL,
    [FILLING_SHIFT] CHAR(1) NULL,
    [START_TIME] VARCHAR(5) NULL,
    [END_TIME] VARCHAR(5) NULL,
    [FILL_QTY] DECIMAL(38) NULL,
    [FILLING_POINT_GROUP_ID] DECIMAL(38) NULL
);

-- Table: OS_SHIFT_MASTER (Shift Master)
CREATE TABLE [OS_SHIFT_MASTER] (
    [SHIFT_CODE] CHAR(1) NOT NULL,
    [SHIFT_DESC] VARCHAR(20) NOT NULL,
    [COMPANY_UNIT_ID] DECIMAL(38) NOT NULL,
    [START_TIME] VARCHAR(5) NOT NULL,
    [START_DAY] INT NOT NULL,
    [END_TIME] VARCHAR(5) NOT NULL,
    [END_DAY] INT NOT NULL,
    CONSTRAINT [PK_OS_SHIFT_MASTER] PRIMARY KEY ([SHIFT_CODE], [COMPANY_UNIT_ID])
);

-- Table: OS_CAPACITY_CHANGES (Capacity Changes)
CREATE TABLE [OS_CAPACITY_CHANGES] (
    [FILLING_LINE_ID] INT NULL,
    [FILLING_GROUP_ID] INT NULL,
    [CHANGE_DATE] DATETIME2(3) NOT NULL,
    [RERUN_STATUS] VARCHAR(1) NOT NULL,
    [RERUN_DATE] DATETIME2(3) NULL
);

-- Table: OS_EMPTIES_ORDER (Empties Order)
CREATE TABLE [OS_EMPTIES_ORDER] (
    [SCI_ITEM_ID] DECIMAL(38) NULL,
    [ITEM_ID] DECIMAL(38) NULL,
    [ORDER_QTY] DECIMAL(38) NULL,
    [NEED_DATE] DATETIME2(3) NULL,
    [ORDER_DATE] DATETIME2(3) NULL,
    [ENTRY_DATE] DATETIME2(3) NULL
);

-- Table: OS_SCHEDULE_CONFIRM (Schedule Confirm)
CREATE TABLE [OS_SCHEDULE_CONFIRM] (
    [SCH_DATE] DATETIME2(3) NOT NULL,
    [SCH_STATUS] VARCHAR(1) NOT NULL,
    [MODIFIED_DATE] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_OS_SCHEDULE_CONFIRM] PRIMARY KEY ([SCH_DATE])
);

PRINT 'ORDER_SCHEDULING_MODULE Tables created successfully.';
GO
