-- =========================================================================
-- TRUST MODULE - Database Tables
-- Database: PFDB
-- Module: Trust Management
-- Description: Manages trust configuration and user-trust mappings
-- Created: March 9, 2026
-- =========================================================================

USE PFDB;
GO

-- Trust Master
CREATE TABLE [TRUST_MASTER] (
    [TRUST_CODE] CHAR(3) NOT NULL PRIMARY KEY,
    [TRUST_SHORT_NAME] VARCHAR(65) NOT NULL,
    [TRUST_TYPE] CHAR(3) NOT NULL,
    [TRUST_START_DATE] DATETIME2(3) NOT NULL,
    [TRUST_CLOSURE_DATE] DATETIME2(3) NULL,
    [TRUST_ID] VARCHAR(65) NULL,
    [ADDRESS_LINE1] VARCHAR(200) NOT NULL,
    [ADDRESS_LINE2] VARCHAR(200) NULL,
    [ADDRESS_LINE3] VARCHAR(200) NULL,
    [CITY] VARCHAR(50) NULL,
    [STATE] VARCHAR(50) NULL,
    [PIN_CODE] VARCHAR(10) NULL,
    [COUNTRY] VARCHAR(50) NULL,
    [PHONE_NO] VARCHAR(20) NULL,
    [FAX_NO] VARCHAR(20) NULL,
    [EMAIL] VARCHAR(100) NULL,
    [TRUST_STATUS] CHAR(1) DEFAULT 'A',
    [CREATED_DATE] DATETIME2(3) NOT NULL,
    [UPDATED_DATE] DATETIME2(3) NULL,
    [REGISTRAR_NAME] VARCHAR(65) NULL,
    [REGISTRAR_PHONE] VARCHAR(20) NULL
);
GO

-- Trust Fund Type
CREATE TABLE [TRUST_FUND_TYPE] (
    [FUND_TRUST_CODE] CHAR(3) NOT NULL,
    [FUND_TYPE] CHAR(3) NOT NULL,
    [FUND_NAME] VARCHAR(65) NOT NULL,
    [FUND_PREFIX] VARCHAR(65) NOT NULL,
    [FUND_STATUS] CHAR(1) DEFAULT 'A',
    CONSTRAINT [PK_TRUST_FUND_TYPE] PRIMARY KEY ([FUND_TRUST_CODE], [FUND_TYPE]),
    CONSTRAINT [FK_TRUST_FUND_TRUST] FOREIGN KEY ([FUND_TRUST_CODE]) REFERENCES [TRUST_MASTER]([TRUST_CODE])
);
GO

-- Trust Role
CREATE TABLE [TRUST_ROLE] (
    [TR_TRUST_CODE] CHAR(3) NOT NULL,
    [TR_ROLE_ID] INT NOT NULL,
    [TR_ROLE_CODE] CHAR(3) NOT NULL,
    [TR_USER_ID] VARCHAR(25) NOT NULL,
    [TR_USER_NO] BIGINT NOT NULL,
    [TR_EFF_DATE] DATETIME2(3) NOT NULL,
    [TR_CLS_DATE] DATETIME2(3) NULL,
    [TR_STATUS] CHAR(1) DEFAULT 'A',
    CONSTRAINT [PK_TRUST_ROLE] PRIMARY KEY ([TR_TRUST_CODE], [TR_ROLE_ID], [TR_USER_ID]),
    CONSTRAINT [FK_TRUST_ROLE_TRUST] FOREIGN KEY ([TR_TRUST_CODE]) REFERENCES [TRUST_MASTER]([TRUST_CODE])
);
GO

-- Trust Approvers
CREATE TABLE [TRUST_APPROVERS] (
    [APPROVER_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [TRUST_CODE] CHAR(3) NOT NULL,
    [APPROVER_SYSID] BIGINT NOT NULL,
    [APPROVER_LEVEL] INT NOT NULL,
    [APPROVER_TYPE] VARCHAR(50) NOT NULL,
    [EFF_DATE] DATETIME2(3) NOT NULL,
    [CLS_DATE] DATETIME2(3) NULL,
    [APPROVER_STATUS] CHAR(1) DEFAULT 'A',
    CONSTRAINT [FK_TRUST_APPROVERS_TRUST] FOREIGN KEY ([TRUST_CODE]) REFERENCES [TRUST_MASTER]([TRUST_CODE])
);
GO

-- Trust Configuration
CREATE TABLE [TRUST_CONFIGURATION] (
    [CONFIG_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [TRUST_CODE] CHAR(3) NOT NULL,
    [CONFIG_NAME] VARCHAR(100) NOT NULL,
    [CONFIG_VALUE] VARCHAR(500) NOT NULL,
    [CONFIG_CATEGORY] VARCHAR(50) NOT NULL,
    [EFF_DATE] DATETIME2(3) NOT NULL,
    [CLS_DATE] DATETIME2(3) NULL,
    CONSTRAINT [FK_TRUST_CONFIG_TRUST] FOREIGN KEY ([TRUST_CODE]) REFERENCES [TRUST_MASTER]([TRUST_CODE])
);
GO

-- Trust Audit Log
CREATE TABLE [TRUST_AUDIT_LOG] (
    [AUDIT_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [TRUST_CODE] CHAR(3) NOT NULL,
    [AUDIT_ACTION] VARCHAR(50) NOT NULL,
    [AUDIT_TABLE] VARCHAR(100) NOT NULL,
    [AUDIT_TIMESTAMP] DATETIME2(3) NOT NULL,
    [AUDIT_USER_ID] BIGINT NOT NULL,
    [OLD_VALUES] VARCHAR(MAX) NULL,
    [NEW_VALUES] VARCHAR(MAX) NULL,
    CONSTRAINT [FK_TRUST_AUDIT_TRUST] FOREIGN KEY ([TRUST_CODE]) REFERENCES [TRUST_MASTER]([TRUST_CODE])
);
GO

-- Trust Units/Branches
CREATE TABLE [TRUST_UNITS] (
    [UNIT_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [TRUST_CODE] CHAR(3) NOT NULL,
    [UNIT_CODE] CHAR(3) NOT NULL UNIQUE,
    [UNIT_NAME] VARCHAR(100) NOT NULL,
    [UNIT_TYPE] VARCHAR(50) NOT NULL,
    [ADDRESS_LINE1] VARCHAR(200) NOT NULL,
    [ADDRESS_LINE2] VARCHAR(200) NULL,
    [CITY] VARCHAR(50) NOT NULL,
    [STATE] VARCHAR(50) NOT NULL,
    [UNIT_HEAD_SYSID] BIGINT NULL,
    [EFF_DATE] DATETIME2(3) NOT NULL,
    [CLS_DATE] DATETIME2(3) NULL,
    [UNIT_STATUS] CHAR(1) DEFAULT 'A',
    CONSTRAINT [FK_TRUST_UNITS_TRUST] FOREIGN KEY ([TRUST_CODE]) REFERENCES [TRUST_MASTER]([TRUST_CODE])
);
GO

CREATE NONCLUSTERED INDEX [IDX_TRUST_MASTER_STATUS] ON [TRUST_MASTER] ([TRUST_STATUS]);
CREATE NONCLUSTERED INDEX [IDX_TRUST_FUND_TYPE_TRUST] ON [TRUST_FUND_TYPE] ([FUND_TRUST_CODE], [FUND_STATUS]);
CREATE NONCLUSTERED INDEX [IDX_TRUST_ROLE_USER] ON [TRUST_ROLE] ([TR_TRUST_CODE], [TR_USER_ID], [TR_STATUS]);
CREATE NONCLUSTERED INDEX [IDX_TRUST_APPROVERS_LEVEL] ON [TRUST_APPROVERS] ([TRUST_CODE], [APPROVER_LEVEL], [APPROVER_STATUS]);
CREATE NONCLUSTERED INDEX [IDX_TRUST_UNITS_CODE] ON [TRUST_UNITS] ([TRUST_CODE], [UNIT_CODE], [UNIT_STATUS]);

PRINT 'Trust Module Tables created successfully!';
GO
