apiVersion: v1
kind: Namespace
metadata:
  name: scholarship-service
  labels:
    name: scholarship-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scholarship-service-config
  namespace: scholarship-service
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:5166"
  Jwt__Issuer: "ScholarshipService"
  Jwt__Audience: "ScholarshipServiceClient"
  Jwt__ExpiresInMinutes: "60"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft: "Warning"
