// <auto-generated />
using System;
using CanteenUnit.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CanteenUnit.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CanteenUnit.Domain.Entities.CanteenMaster", b =>
                {
                    b.Property<decimal>("CnComCod")
                        .HasColumnType("DECIMAL(38,0)")
                        .HasColumnName("CN_COM_COD");

                    b.Property<DateTime?>("CnCanFro")
                        .HasColumnType("datetime2")
                        .HasColumnName("CN_CAN_FRO");

                    b.Property<long>("CnCanNum")
                        .HasColumnType("bigint")
                        .HasColumnName("CN_CAN_NUM");

                    b.Property<DateTime?>("CnCanTo")
                        .HasColumnType("datetime2")
                        .HasColumnName("CN_CAN_TO");

                    b.Property<DateTime?>("CnEntDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("CN_ENT_DAT");

                    b.Property<decimal?>("CnEntUsr")
                        .HasColumnType("DECIMAL(38,0)")
                        .HasColumnName("CN_ENT_USR");

                    b.Property<string>("CnLivFlg")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("CN_LIV_FLG");

                    b.Property<string>("CnRemMrk")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CN_REM_MRK");

                    b.HasKey("CnComCod");

                    b.HasIndex("CnCanNum")
                        .HasDatabaseName("IDX_CANTEEN_MASTER_CN_CAN_NUM");

                    b.ToTable("CANTEEN_MASTER", (string)null);
                });

            modelBuilder.Entity("CanteenUnit.Domain.Entities.CanteenMasterCat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CnCanNum")
                        .HasColumnType("bigint")
                        .HasColumnName("CN_CAN_NUM");

                    b.Property<long?>("CnComCod")
                        .HasColumnType("bigint")
                        .HasColumnName("CN_COM_COD");

                    b.Property<string>("CnGrdTyp")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("CN_GRD_TYP");

                    b.HasKey("Id");

                    b.ToTable("CANTEEN_MASTER_CAT", (string)null);
                });

            modelBuilder.Entity("CanteenUnit.Domain.Entities.CanteenMasterGradeCat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CnCanFro")
                        .HasColumnType("datetime2")
                        .HasColumnName("CN_CAN_FRO");

                    b.Property<long?>("CnCanNum")
                        .HasColumnType("bigint")
                        .HasColumnName("CN_CAN_NUM");

                    b.Property<long?>("CnCanSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("CN_CAN_SEQ");

                    b.Property<DateTime?>("CnCanTo")
                        .HasColumnType("datetime2")
                        .HasColumnName("CN_CAN_TO");

                    b.Property<decimal?>("CnComCod")
                        .HasColumnType("DECIMAL(38,0)")
                        .HasColumnName("CN_COM_COD");

                    b.Property<string>("CnGrdCat")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("CN_GRD_CAT");

                    b.Property<string>("CnLivFlg")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("CN_LIV_FLG");

                    b.HasKey("Id");

                    b.ToTable("CANTEEN_MASTER_GRADECAT", (string)null);
                });

            modelBuilder.Entity("CanteenUnit.Domain.Entities.CanteenUnitAccess", b =>
                {
                    b.Property<long>("UnUntAcc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("UN_UNT_ACC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UnUntAcc"));

                    b.Property<DateTime?>("UnClsDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("UN_CLS_DAT");

                    b.Property<long?>("UnComCod")
                        .HasColumnType("bigint")
                        .HasColumnName("UN_COM_COD");

                    b.Property<DateTime?>("UnEntOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("UN_ENT_ON");

                    b.Property<long?>("UnEntUsr")
                        .HasColumnType("bigint")
                        .HasColumnName("UN_ENT_USR");

                    b.Property<long?>("UnUsrId")
                        .HasColumnType("bigint")
                        .HasColumnName("UN_USR_ID");

                    b.HasKey("UnUntAcc");

                    b.ToTable("CANTEEN_UNIT_ACCESS", (string)null);
                });

            modelBuilder.Entity("CanteenUnit.Domain.Entities.CanteenUnitMaster", b =>
                {
                    b.Property<decimal>("UnComCod")
                        .HasColumnType("DECIMAL(38,0)")
                        .HasColumnName("UN_COM_COD");

                    b.Property<decimal?>("InMinVal")
                        .HasColumnType("DECIMAL(38,0)")
                        .HasColumnName("IN_MIN_VAL");

                    b.Property<long?>("UnHrmsId")
                        .HasColumnType("bigint")
                        .HasColumnName("UN_HRMS_ID");

                    b.Property<decimal?>("UnMaxVal")
                        .HasColumnType("DECIMAL(38,0)")
                        .HasColumnName("UN_MAX_VAL");

                    b.Property<long?>("UnSitId")
                        .HasColumnType("bigint")
                        .HasColumnName("UN_SIT_ID");

                    b.Property<string>("UnUntName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UN_UNT_NAME");

                    b.Property<string>("UntUntRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UNT_UNT_REF");

                    b.HasKey("UnComCod");

                    b.ToTable("CANTEEN_UNIT_MASTER", (string)null);
                });

            modelBuilder.Entity("CanteenUnit.Domain.Entities.GenCounter", b =>
                {
                    b.Property<string>("GnTrnTyp")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("GN_TRN_TYP");

                    b.Property<string>("GnTrnDes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("GN_TRN_DES");

                    b.Property<long?>("GnTrnNum")
                        .HasColumnType("bigint")
                        .HasColumnName("GN_TRN_NUM");

                    b.HasKey("GnTrnTyp");

                    b.ToTable("GEN_COUNTER", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
