// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionService.Infrastructure.Persistence;

#nullable disable

namespace TransactionService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    partial class TransactionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransactionService.Domain.Entities.ApprovalStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("STEP_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("ACTED_ON");

                    b.Property<long>("ApproverId")
                        .HasColumnType("bigint")
                        .HasColumnName("APPROVER_ID");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CREATED_ON");

                    b.Property<int>("StepLevel")
                        .HasColumnType("int")
                        .HasColumnName("STEP_LEVEL");

                    b.Property<string>("StepRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("STEP_REMARKS");

                    b.Property<string>("StepStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("STEP_STATUS");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("bigint")
                        .HasColumnName("WORKFLOW_ID");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId")
                        .HasDatabaseName("IX_APPROVAL_STEP_APPROVER");

                    b.HasIndex("StepStatus")
                        .HasDatabaseName("IX_APPROVAL_STEP_STATUS");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_APPROVAL_STEP_WORKFLOW");

                    b.ToTable("APPROVAL_STEP", (string)null);
                });

            modelBuilder.Entity("TransactionService.Domain.Entities.ApprovalWorkflow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("WORKFLOW_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CREATED_ON");

                    b.Property<int>("CurrentApprovalLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("CURRENT_APPROVAL_LEVEL");

                    b.Property<long>("CurrentApproverId")
                        .HasColumnType("bigint")
                        .HasColumnName("CURRENT_APPROVER_ID");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("ENTITY_ID");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ENTITY_TYPE");

                    b.Property<int>("MaxApprovalLevels")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("MAX_APPROVAL_LEVELS");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("REMARKS");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("UPDATED_ON");

                    b.Property<string>("WorkflowCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("WORKFLOW_CODE");

                    b.Property<string>("WorkflowStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("SUBMITTED")
                        .HasColumnName("WORKFLOW_STATUS");

                    b.HasKey("Id");

                    b.HasIndex("CurrentApproverId")
                        .HasDatabaseName("IX_APPROVAL_WORKFLOW_APPROVER");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_APPROVAL_WORKFLOW_EMPLOYEE");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("IX_APPROVAL_WORKFLOW_ENTITY_TYPE");

                    b.HasIndex("WorkflowCode")
                        .IsUnique()
                        .HasDatabaseName("UC_APPROVAL_WORKFLOW_CODE");

                    b.HasIndex("WorkflowStatus")
                        .HasDatabaseName("IX_APPROVAL_WORKFLOW_STATUS");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_APPROVAL_WORKFLOW_ENTITY");

                    b.ToTable("APPROVAL_WORKFLOW", (string)null);
                });

            modelBuilder.Entity("TransactionService.Domain.Entities.TransactionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LOG_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ACTION");

                    b.Property<long>("ActionBy")
                        .HasColumnType("bigint")
                        .HasColumnName("ACTION_BY");

                    b.Property<string>("ActionData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACTION_DATA");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CREATED_ON");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IP_ADDRESS");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NEW_STATUS");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PREVIOUS_STATUS");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("TRANSACTION_ID");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANSACTION_TYPE");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_TRANSACTION_LOG_ACTION");

                    b.HasIndex("ActionBy")
                        .HasDatabaseName("IX_TRANSACTION_LOG_ACTION_BY");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("IX_TRANSACTION_LOG_CREATED_ON");

                    b.HasIndex("TransactionType")
                        .HasDatabaseName("IX_TRANSACTION_LOG_TYPE");

                    b.HasIndex("TransactionType", "TransactionId")
                        .HasDatabaseName("IX_TRANSACTION_LOG_ENTITY");

                    b.ToTable("TRANSACTION_LOG", (string)null);
                });

            modelBuilder.Entity("TransactionService.Domain.Entities.ApprovalStep", b =>
                {
                    b.HasOne("TransactionService.Domain.Entities.ApprovalWorkflow", "Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_APPROVAL_STEP_WORKFLOW");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("TransactionService.Domain.Entities.ApprovalWorkflow", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
