-- Module: Recruitment
USE DDDB;
GO

-- Table: TEC_APPLICANT_DET
CREATE TABLE [TEC_APPLICANT_DET] (
    [AP_APPLN_NO] DECIMAL(38) NOT NULL  -- Aplplication Number,
    [AP_JOB_ID] DECIMAL(38) NULL  -- Job ID,
    [AP_SPARSH_ID] VARCHAR(25) NULL  -- Sparsh User ID,
    [AP_SPARSH_PIN] DECIMAL(38) NULL  -- Sparsh User PinNumber,
    [AP_CUR_JD] VARCHAR(200) NULL  -- Path for Current Job Description,
    [AP_ACIEVEMENTS] VARCHAR(4000) NULL  -- Job Achievements,
    [AP_RESN_JON] VARCHAR(4000) NULL  -- Reason For Joining,
    [AP_STRENGTH] VARCHAR(4000) NULL  -- Applicant Strength,
    [AP_AWARDS] VARCHAR(4000) NULL  -- Awards If any,
    [AP_CRT_MARKS] VARCHAR(200) NULL  -- CRT Marks,
    [AP_DMN_MARKS] VARCHAR(200) NULL  -- Domain Marks,
    [AP_CRT_PATH] VARCHAR(200) NULL  -- Path for CRT Mark,
    [AP_DMN_PATH] VARCHAR(200) NULL  -- Path for Domain Mark,
    [AP_APPLN_STS] DECIMAL(38) NULL  -- Applicant Status,
    CONSTRAINT [PK_TEC_APPLICANT_DET] PRIMARY KEY ([AP_APPLN_NO])
);



-- Table: TEC_APPLN_STS
CREATE TABLE [TEC_APPLN_STS] (
    [AS_APPLN_NO] DECIMAL(38) NOT NULL  -- Applicant  Number,
    [AP_SNO] DECIMAL(38) NOT NULL  -- Serial No,
    [AP_APPLN_STS] DECIMAL(38) NULL  -- Applicant Status,
    [AP_UPD_SPARSHID] VARCHAR(25) NULL  -- Sparsh ID,
    [AP_UPD_DATE] DATETIME2(3) NULL  -- Updation Date,
    [AP_REMARKS] VARCHAR(200) NULL  -- Remarks,
    CONSTRAINT [PK_TEC_APPLN_STS] PRIMARY KEY ([AS_APPLN_NO])
);



-- Table: TEC_COURSE_DETAILS
CREATE TABLE [TEC_COURSE_DETAILS] (
    [CD_APPLN_NO] DECIMAL(38) NULL  -- Applicant Number,
    [CD_SNO] DECIMAL(38) NULL  -- Sno,
    [CD_COURSE_TIT] VARCHAR(200) NULL  -- Course Tititle,
    [CD_DURATION] VARCHAR(200) NULL  -- Course Duration,
    [CD_INSTITUTE] VARCHAR(200) NULL  -- Course Institute
);



-- Table: TEC_JOB_DETAILS
CREATE TABLE [TEC_JOB_DETAILS] (
    [JD_JOB_ID] DECIMAL(38) NOT NULL  -- Primary key, Job ID,
    [JD_RECRUITMENTCYCLENO] DECIMAL(38) NULL  -- Link between this table and TEC_Vacancy REC_CYCLE_No,
    [JD_JOB_DESC] VARCHAR(200) NULL  -- Job Description,
    [JD_ROLE_DETAILS] VARCHAR(200) NULL  -- Role Details,
    [JD_CADRE_CODE] CHAR(3) NULL  -- Cadre Code,
    [JD_EFF_DATE] DATETIME2(3) NULL  -- Effective Date,
    [JD_PRINC_ACCOUNT] VARCHAR(500) NULL  -- Principle Account,
    [JD_JOB_TYPE] VARCHAR(200) NULL  -- Job Type,
    [JD_BUS_CODE] CHAR(9) NULL  -- Business Code,
    [JD_UNIT_CODE] VARCHAR(10) NULL  -- Unit Code
);



-- Table: TEC_JOB_DETAILS_DEL
CREATE TABLE [TEC_JOB_DETAILS_DEL] (
    [JD_JOB_ID] DECIMAL(38) NULL,
    [JD_RECRUITMENTCYCLENO] DECIMAL(38) NULL,
    [JD_JOB_DESC] VARCHAR(200) NULL,
    [JD_ROLE_DETAILS] VARCHAR(200) NULL,
    [JD_CADRE_CODE] CHAR(3) NULL,
    [JD_EFF_DATE] DATETIME2(3) NULL,
    [JD_PRINC_ACCOUNT] VARCHAR(500) NULL,
    [JD_JOB_TYPE] VARCHAR(200) NULL,
    [JD_BUS_CODE] CHAR(9) NULL,
    [JD_UNIT_CODE] VARCHAR(10) NULL
);



-- Table: TEC_STC_ASSESS
CREATE TABLE [TEC_STC_ASSESS] (
    [SA_APPLN_NO] DECIMAL(38) NULL  -- Applicant Number,
    [SA_PARAM_NO] DECIMAL(38) NULL  -- Parameter Number,
    [SA_PINNUM] DECIMAL(38) NULL  -- STEERING COMMITEE MEMBER PIN NUMBER,
    [SA_USERID] VARCHAR(100) NULL  -- STEERING COMMITEE MEMBER USER ID,
    [SA_PARAM_REMARKS] VARCHAR(500) NULL  -- PARAMETER REMARKS,
    [SA_OTHER_REMARKS] VARCHAR(2000) NULL  -- OTHER REMARKS,
    [SA_MARK] DECIMAL(38) NULL  -- Applicant Marks,
    CONSTRAINT [PK_TEC_STC_ASSESS] PRIMARY KEY ([SA_PARAM_NO])
);



-- Table: TEC_STC_PARAMS
CREATE TABLE [TEC_STC_PARAMS] (
    [SP_RECCYCLENO] DECIMAL(38) NULL  -- Recruitment Number,
    [SP_PARAMNO] DECIMAL(38) NULL  -- Parameter Number,
    [SP_PARAMETER] VARCHAR(200) NULL  -- Parameter Name
);



-- Table: TEC_VACANCY_MASTER
CREATE TABLE [TEC_VACANCY_MASTER] (
    [VM_RECRUITMENT_CYCLE_NO] DECIMAL(38) NOT NULL  -- sequence that says about the vacancy,
    [VM_EFFDATE] DATETIME2(3) NULL  -- Effective FROM Date for the vacancy,
    [VM_ENDDATE] DATETIME2(3) NULL  -- End Date for the vacancy,
    CONSTRAINT [PK_TEC_VACANCY_MASTER] PRIMARY KEY ([VM_RECRUITMENT_CYCLE_NO])
);

