-- Create ADMINDB database if it doesn't exist
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'ADMINDB')
BEGIN
    CREATE DATABASE ADMINDB;
END
GO

USE ADMINDB;
GO

-- Create FINYEAR_MASTER table
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'FINYEAR_MASTER')
BEGIN
    CREATE TABLE FINYEAR_MASTER (
        [FY_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [FY_NAME] NVARCHAR(27) NOT NULL,
        [FY_STARTDATE] DATETIME2(3) NOT NULL,
        [FY_CLOSEDATE] DATETIME2(3) NOT NULL,
        [FY_UPDATED_BY] BIGINT DEFAULT 1,
        [FY_UPDATED_ON] DATETIME2(3) DEFAULT GETDATE()
    );
    
    -- Create index on FY_NAME
    CREATE NONCLUSTERED INDEX [IX_FINYEAR_MASTER_NAME] ON [FINYEAR_MASTER] ([FY_NAME]);
    
    -- Insert sample data
    INSERT INTO FINYEAR_MASTER ([FY_NAME], [FY_STARTDATE], [FY_CLOSEDATE], [FY_UPDATED_BY], [FY_UPDATED_ON])
    VALUES 
        ('FY 2024-25', '2024-04-01', '2025-03-31', 1, GETDATE()),
        ('FY 2025-26', '2025-04-01', '2026-03-31', 1, GETDATE()),
        ('FY 2026-27', '2026-04-01', '2027-03-31', 1, GETDATE());
END
GO
