<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" Version="14.0.0" />
    <PackageReference Include="HotChocolate.Types" Version="14.0.0" />
    <PackageReference Include="HotChocolate.Subscriptions.InMemory" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../FinyearAPI.Application/FinyearAPI.Application.csproj" />
    <ProjectReference Include="../FinyearAPI.Domain/FinyearAPI.Domain.csproj" />
  </ItemGroup>

</Project>
