apiVersion: v1
kind: ConfigMap
metadata:
  name: loan-services-config
  namespace: loan-services
data:
  # SQL Server
  SQL_SERVER_HOST: "sqlserver"
  SQL_SERVER_PORT: "1433"
  SQL_DATABASE: "LOANDB"

  # RabbitMQ
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"

  # ASPNETCORE
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"

  # Service URLs (used by Gateway / inter-service calls)
  LOAN_TRANSACTION_URL: "http://loan-transaction:8080/"
  LOAN_APPLICATION_URL: "http://loan-application:8080/"
  LOAN_ACCOUNT_URL:     "http://loan-account:8080/"
  LOAN_DEFINITION_URL:  "http://loan-definition:8080/"
  DOCUMENT_SERVICE_URL: "http://document-service:8080/"
  LOV_SERVICE_URL:      "http://lov-service:8080/"
  UTILITY_SERVICE_URL:  "http://utility-service:8080/"
