loopback_users.guest = false
management.load_definitions = /etc/rabbitmq/definitions.json

listeners.tcp.default = 5672
management.tcp.port = 15672

vm_memory_high_watermark.relative = 0.7
disk_free_limit.absolute = 1GB

log.console = true
log.console.level = warning
log.file = false

consumer_timeout = 3600000
