-- ==========================================
-- SRF Sparsh Microservices - Initial Database Setup
-- Database: SRFSPARSHDB
-- Created: April 5, 2026
-- Description: Creates the database, login, and user
--   then runs all module schemas and stored procedures
-- ==========================================

-- Create the database if it doesn't exist
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'SRFSPARSHDB')
BEGIN
    CREATE DATABASE SRFSPARSHDB;
    PRINT 'Database SRFSPARSHDB created.';
END
ELSE
BEGIN
    PRINT 'Database SRFSPARSHDB already exists.';
END
GO

USE SRFSPARSHDB;
GO

-- Create application login and user (for Docker/Production)
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'srfsparsh_app')
BEGIN
    CREATE LOGIN srfsparsh_app WITH PASSWORD = 'SRFSparsh@2026!Secure';
    PRINT 'Login srfsparsh_app created.';
END
GO

IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'srfsparsh_app')
BEGIN
    CREATE USER srfsparsh_app FOR LOGIN srfsparsh_app;
    ALTER ROLE db_datareader ADD MEMBER srfsparsh_app;
    ALTER ROLE db_datawriter ADD MEMBER srfsparsh_app;
    GRANT EXECUTE TO srfsparsh_app;
    PRINT 'User srfsparsh_app created with read/write/execute permissions.';
END
GO

-- ==========================================
-- APPROVAL MODULE TABLES
-- ==========================================
IF OBJECT_ID('dbo.APPR_MAST', 'U') IS NULL
CREATE TABLE [APPR_MAST] (
    [APPR_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [APPR_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [APPR_NAME] VARCHAR(255) NOT NULL,
    [APPR_TYPE] VARCHAR(20) NOT NULL,
    [APPR_DESC] NVARCHAR(MAX),
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);
GO

IF OBJECT_ID('dbo.APPROVER_EMP', 'U') IS NULL
CREATE TABLE [APPROVER_EMP] (
    [APPROVER_EMP_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [APPR_ID] BIGINT NOT NULL REFERENCES [APPR_MAST]([APPR_ID]),
    [EMP_ID] BIGINT NOT NULL,
    [APPROVAL_LEVEL] INT NOT NULL DEFAULT 1,
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);
GO

IF OBJECT_ID('dbo.APPROVAL_WORKFLOW', 'U') IS NULL
CREATE TABLE [APPROVAL_WORKFLOW] (
    [WORKFLOW_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [WORKFLOW_CODE] VARCHAR(100) NOT NULL UNIQUE,
    [WORKFLOW_NAME] VARCHAR(255) NOT NULL,
    [MODULE_NAME] VARCHAR(100) NOT NULL,
    [WORKFLOW_STATUS] VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    [REQUESTED_BY] BIGINT NOT NULL,
    [REQUESTED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [COMPLETED_ON] DATETIME2(3),
    [REMARKS] NVARCHAR(MAX),
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);
GO

IF OBJECT_ID('dbo.APPROVAL_STEP', 'U') IS NULL
CREATE TABLE [APPROVAL_STEP] (
    [STEP_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [WORKFLOW_ID] BIGINT NOT NULL REFERENCES [APPROVAL_WORKFLOW]([WORKFLOW_ID]),
    [STEP_ORDER] INT NOT NULL,
    [APPROVER_ID] BIGINT NOT NULL,
    [STEP_STATUS] VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    [ACTION_DATE] DATETIME2(3),
    [COMMENTS] NVARCHAR(MAX),
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);
GO

-- ==========================================
-- USER MANAGEMENT MODULE TABLES
-- ==========================================
IF OBJECT_ID('dbo.USERS', 'U') IS NULL
CREATE TABLE [USERS] (
    [USER_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [USER_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [USER_NAME] VARCHAR(255) NOT NULL,
    [EMAIL] VARCHAR(255) NOT NULL UNIQUE,
    [PASSWORD_HASH] VARCHAR(500) NOT NULL,
    [PHONE_NUMBER] VARCHAR(20),
    [USER_TYPE] VARCHAR(50) NOT NULL,
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [LAST_LOGIN] DATETIME2(3),
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);
GO

IF OBJECT_ID('dbo.ROLES', 'U') IS NULL
CREATE TABLE [ROLES] (
    [ROLE_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [ROLE_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [ROLE_NAME] VARCHAR(255) NOT NULL,
    [ROLE_DESC] NVARCHAR(MAX),
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);
GO

IF OBJECT_ID('dbo.USER_ROLES', 'U') IS NULL
CREATE TABLE [USER_ROLES] (
    [USER_ROLE_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [USER_ID] BIGINT NOT NULL REFERENCES [USERS]([USER_ID]),
    [ROLE_ID] BIGINT NOT NULL REFERENCES [ROLES]([ROLE_ID]),
    [ASSIGNED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [ASSIGNED_BY] BIGINT,
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1
);
GO

-- ==========================================
-- BOOKING MODULE TABLES
-- ==========================================
IF OBJECT_ID('dbo.BOOKING_TYPES', 'U') IS NULL
CREATE TABLE [BOOKING_TYPES] (
    [BOOKING_TYPE_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [TYPE_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [TYPE_NAME] VARCHAR(255) NOT NULL,
    [DESCRIPTION] NVARCHAR(MAX),
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT
);
GO

IF OBJECT_ID('dbo.BOOKINGS', 'U') IS NULL
CREATE TABLE [BOOKINGS] (
    [BOOKING_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [BOOKING_CODE] VARCHAR(100) NOT NULL UNIQUE,
    [BOOKING_TYPE_ID] BIGINT NOT NULL REFERENCES [BOOKING_TYPES]([BOOKING_TYPE_ID]),
    [BOOKED_BY] BIGINT NOT NULL,
    [BOOKING_DATE] DATETIME2(3) NOT NULL,
    [START_DATE] DATETIME2(3) NOT NULL,
    [END_DATE] DATETIME2(3) NOT NULL,
    [STATUS] VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    [REMARKS] NVARCHAR(MAX),
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);
GO

-- ==========================================
-- COMMUNITY MODULE TABLES
-- ==========================================
IF OBJECT_ID('dbo.COMMUNITY_POSTS', 'U') IS NULL
CREATE TABLE [COMMUNITY_POSTS] (
    [POST_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [POST_CODE] VARCHAR(100) NOT NULL UNIQUE,
    [TITLE] VARCHAR(500) NOT NULL,
    [CONTENT] NVARCHAR(MAX) NOT NULL,
    [POST_TYPE] VARCHAR(50) NOT NULL,
    [AUTHOR_ID] BIGINT NOT NULL,
    [STATUS] VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    [PUBLISHED_DATE] DATETIME2(3),
    [VIEW_COUNT] INT NOT NULL DEFAULT 0,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);
GO

IF OBJECT_ID('dbo.COMMUNITY_COMMENTS', 'U') IS NULL
CREATE TABLE [COMMUNITY_COMMENTS] (
    [COMMENT_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [POST_ID] BIGINT NOT NULL REFERENCES [COMMUNITY_POSTS]([POST_ID]),
    [PARENT_COMMENT_ID] BIGINT,
    [COMMENT_TEXT] NVARCHAR(MAX) NOT NULL,
    [AUTHOR_ID] BIGINT NOT NULL,
    [STATUS] VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT
);
GO

-- ==========================================
-- COMPENSATION MODULE TABLES
-- ==========================================
IF OBJECT_ID('dbo.COMPENSATION_TYPES', 'U') IS NULL
CREATE TABLE [COMPENSATION_TYPES] (
    [COMP_TYPE_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [TYPE_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [TYPE_NAME] VARCHAR(255) NOT NULL,
    [DESCRIPTION] NVARCHAR(MAX),
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT
);
GO

IF OBJECT_ID('dbo.COMPENSATION_RECORDS', 'U') IS NULL
CREATE TABLE [COMPENSATION_RECORDS] (
    [RECORD_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [RECORD_CODE] VARCHAR(100) NOT NULL UNIQUE,
    [COMP_TYPE_ID] BIGINT NOT NULL REFERENCES [COMPENSATION_TYPES]([COMP_TYPE_ID]),
    [EMPLOYEE_ID] BIGINT NOT NULL,
    [AMOUNT] DECIMAL(18,2) NOT NULL,
    [EFFECTIVE_DATE] DATETIME2(3) NOT NULL,
    [STATUS] VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    [APPROVED_BY] BIGINT,
    [APPROVED_DATE] DATETIME2(3),
    [REMARKS] NVARCHAR(MAX),
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);
GO

-- ==========================================
-- GROUP MANAGEMENT MODULE TABLES
-- ==========================================
IF OBJECT_ID('dbo.GROUPS', 'U') IS NULL
CREATE TABLE [GROUPS] (
    [GROUP_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [GROUP_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [GROUP_NAME] VARCHAR(255) NOT NULL,
    [GROUP_TYPE] VARCHAR(50) NOT NULL,
    [DESCRIPTION] NVARCHAR(MAX),
    [MAX_MEMBERS] INT,
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);
GO

IF OBJECT_ID('dbo.GROUP_MEMBERS', 'U') IS NULL
CREATE TABLE [GROUP_MEMBERS] (
    [MEMBER_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [GROUP_ID] BIGINT NOT NULL REFERENCES [GROUPS]([GROUP_ID]),
    [USER_ID] BIGINT NOT NULL,
    [ROLE] VARCHAR(50) NOT NULL DEFAULT 'MEMBER',
    [JOINED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT
);
GO

-- ==========================================
-- LOCATION MODULE TABLES
-- ==========================================
IF OBJECT_ID('dbo.LOCATIONS', 'U') IS NULL
CREATE TABLE [LOCATIONS] (
    [LOCATION_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [LOCATION_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [LOCATION_NAME] VARCHAR(255) NOT NULL,
    [LOCATION_TYPE] VARCHAR(50) NOT NULL,
    [ADDRESS] NVARCHAR(500),
    [CITY] VARCHAR(100),
    [STATE] VARCHAR(100),
    [COUNTRY] VARCHAR(100),
    [PIN_CODE] VARCHAR(20),
    [LATITUDE] DECIMAL(10,8),
    [LONGITUDE] DECIMAL(11,8),
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);
GO

-- ==========================================
-- MEETING MODULE TABLES
-- ==========================================
IF OBJECT_ID('dbo.MEETINGS', 'U') IS NULL
CREATE TABLE [MEETINGS] (
    [MEETING_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [MEETING_CODE] VARCHAR(100) NOT NULL UNIQUE,
    [TITLE] VARCHAR(500) NOT NULL,
    [DESCRIPTION] NVARCHAR(MAX),
    [MEETING_TYPE] VARCHAR(50) NOT NULL,
    [ORGANIZER_ID] BIGINT NOT NULL,
    [LOCATION_ID] BIGINT,
    [START_TIME] DATETIME2(3) NOT NULL,
    [END_TIME] DATETIME2(3) NOT NULL,
    [STATUS] VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    [MEETING_LINK] VARCHAR(500),
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);
GO

IF OBJECT_ID('dbo.MEETING_PARTICIPANTS', 'U') IS NULL
CREATE TABLE [MEETING_PARTICIPANTS] (
    [PARTICIPANT_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [MEETING_ID] BIGINT NOT NULL REFERENCES [MEETINGS]([MEETING_ID]),
    [USER_ID] BIGINT NOT NULL,
    [RSVP_STATUS] VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    [ATTENDED] BIT NOT NULL DEFAULT 0,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE()
);
GO

-- ==========================================
-- PROXY MODULE TABLES
-- ==========================================
IF OBJECT_ID('dbo.PROXY_ASSIGNMENTS', 'U') IS NULL
CREATE TABLE [PROXY_ASSIGNMENTS] (
    [PROXY_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [PROXY_CODE] VARCHAR(100) NOT NULL UNIQUE,
    [ASSIGNOR_ID] BIGINT NOT NULL,
    [PROXY_USER_ID] BIGINT NOT NULL,
    [START_DATE] DATETIME2(3) NOT NULL,
    [END_DATE] DATETIME2(3) NOT NULL,
    [REASON] NVARCHAR(MAX),
    [STATUS] VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    [APPROVED_BY] BIGINT,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);
GO

-- ==========================================
-- REIMBURSEMENT MODULE TABLES
-- ==========================================
IF OBJECT_ID('dbo.REIMBURSEMENT_TYPES', 'U') IS NULL
CREATE TABLE [REIMBURSEMENT_TYPES] (
    [REIMB_TYPE_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [TYPE_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [TYPE_NAME] VARCHAR(255) NOT NULL,
    [MAX_AMOUNT] DECIMAL(18,2),
    [DESCRIPTION] NVARCHAR(MAX),
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT
);
GO

IF OBJECT_ID('dbo.REIMBURSEMENT_CLAIMS', 'U') IS NULL
CREATE TABLE [REIMBURSEMENT_CLAIMS] (
    [CLAIM_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [CLAIM_CODE] VARCHAR(100) NOT NULL UNIQUE,
    [REIMB_TYPE_ID] BIGINT NOT NULL REFERENCES [REIMBURSEMENT_TYPES]([REIMB_TYPE_ID]),
    [CLAIMANT_ID] BIGINT NOT NULL,
    [AMOUNT] DECIMAL(18,2) NOT NULL,
    [CLAIM_DATE] DATETIME2(3) NOT NULL,
    [RECEIPT_PATH] VARCHAR(500),
    [STATUS] VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED',
    [APPROVED_AMOUNT] DECIMAL(18,2),
    [REMARKS] NVARCHAR(MAX),
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);
GO

-- ==========================================
-- STIPEND MODULE TABLES
-- ==========================================
IF OBJECT_ID('dbo.STIPEND_DEFINITIONS', 'U') IS NULL
CREATE TABLE [STIPEND_DEFINITIONS] (
    [STIPEND_DEF_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [STIPEND_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [STIPEND_NAME] VARCHAR(255) NOT NULL,
    [AMOUNT] DECIMAL(18,2) NOT NULL,
    [FREQUENCY] VARCHAR(20) NOT NULL,
    [DESCRIPTION] NVARCHAR(MAX),
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);
GO

IF OBJECT_ID('dbo.STIPEND_DISBURSEMENTS', 'U') IS NULL
CREATE TABLE [STIPEND_DISBURSEMENTS] (
    [DISBURSEMENT_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [DISBURSEMENT_CODE] VARCHAR(100) NOT NULL UNIQUE,
    [STIPEND_DEF_ID] BIGINT NOT NULL REFERENCES [STIPEND_DEFINITIONS]([STIPEND_DEF_ID]),
    [BENEFICIARY_ID] BIGINT NOT NULL,
    [AMOUNT] DECIMAL(18,2) NOT NULL,
    [DISBURSEMENT_DATE] DATETIME2(3) NOT NULL,
    [PERIOD_FROM] DATETIME2(3) NOT NULL,
    [PERIOD_TO] DATETIME2(3) NOT NULL,
    [STATUS] VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    [REMARKS] NVARCHAR(MAX),
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);
GO

-- ==========================================
-- TIMESHEET MODULE TABLES
-- ==========================================
IF OBJECT_ID('dbo.TIMESHEETS', 'U') IS NULL
CREATE TABLE [TIMESHEETS] (
    [TIMESHEET_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [TIMESHEET_CODE] VARCHAR(100) NOT NULL UNIQUE,
    [EMPLOYEE_ID] BIGINT NOT NULL,
    [PERIOD_START] DATETIME2(3) NOT NULL,
    [PERIOD_END] DATETIME2(3) NOT NULL,
    [TOTAL_HOURS] DECIMAL(8,2) NOT NULL DEFAULT 0,
    [STATUS] VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    [SUBMITTED_ON] DATETIME2(3),
    [APPROVED_BY] BIGINT,
    [APPROVED_ON] DATETIME2(3),
    [REMARKS] NVARCHAR(MAX),
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);
GO

IF OBJECT_ID('dbo.TIMESHEET_ENTRIES', 'U') IS NULL
CREATE TABLE [TIMESHEET_ENTRIES] (
    [ENTRY_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [TIMESHEET_ID] BIGINT NOT NULL REFERENCES [TIMESHEETS]([TIMESHEET_ID]),
    [WORK_DATE] DATE NOT NULL,
    [HOURS_WORKED] DECIMAL(5,2) NOT NULL,
    [TASK_DESCRIPTION] NVARCHAR(500),
    [PROJECT_CODE] VARCHAR(50),
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT
);
GO

-- ==========================================
-- TRANSACTION MODULE TABLES
-- ==========================================
IF OBJECT_ID('dbo.TRANSACTION_LOGS', 'U') IS NULL
CREATE TABLE [TRANSACTION_LOGS] (
    [LOG_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [LOG_CODE] VARCHAR(100) NOT NULL UNIQUE,
    [TRANSACTION_TYPE] VARCHAR(50) NOT NULL,
    [MODULE_NAME] VARCHAR(100) NOT NULL,
    [REFERENCE_ID] BIGINT,
    [REFERENCE_CODE] VARCHAR(100),
    [ACTION] VARCHAR(50) NOT NULL,
    [PERFORMED_BY] BIGINT NOT NULL,
    [PERFORMED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [DETAILS] NVARCHAR(MAX),
    [IP_ADDRESS] VARCHAR(50),
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE()
);
GO

IF OBJECT_ID('dbo.TRANSACTION_STATUS_LOGS', 'U') IS NULL
CREATE TABLE [TRANSACTION_STATUS_LOGS] (
    [STATUS_LOG_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [WORKFLOW_ID] BIGINT NOT NULL REFERENCES [APPROVAL_WORKFLOW]([WORKFLOW_ID]),
    [STATUS_CODE] VARCHAR(50) NOT NULL,
    [STATUS_MESSAGE] VARCHAR(500),
    [CHANGED_BY] VARCHAR(100) NOT NULL,
    [CHANGED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE()
);
GO

-- ==========================================
-- WEBSITE CONTENT MODULE TABLES
-- ==========================================
IF OBJECT_ID('dbo.WEBSITE_PAGES', 'U') IS NULL
CREATE TABLE [WEBSITE_PAGES] (
    [PAGE_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [PAGE_CODE] VARCHAR(100) NOT NULL UNIQUE,
    [PAGE_TITLE] VARCHAR(255) NOT NULL,
    [PAGE_CONTENT] NVARCHAR(MAX),
    [META_DESCRIPTION] VARCHAR(500),
    [META_KEYWORDS] VARCHAR(500),
    [PAGE_ORDER] INT,
    [PARENT_PAGE_ID] BIGINT,
    [IS_PUBLISHED] CHAR(1) DEFAULT 'N',
    [PUBLISHED_DATE] DATETIME2(3),
    [PAGE_STATUS] VARCHAR(20) DEFAULT 'ACTIVE',
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [UPDATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3)
);
GO

IF OBJECT_ID('dbo.WEBSITE_NEWS', 'U') IS NULL
CREATE TABLE [WEBSITE_NEWS] (
    [NEWS_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [NEWS_TITLE] VARCHAR(500) NOT NULL,
    [NEWS_CONTENT] NVARCHAR(MAX) NOT NULL,
    [NEWS_SUMMARY] VARCHAR(500),
    [NEWS_CATEGORY] VARCHAR(100),
    [FEATURED_IMAGE] VARCHAR(500),
    [IS_PUBLISHED] CHAR(1) DEFAULT 'N',
    [PUBLISHED_DATE] DATETIME2(3),
    [NEWS_STATUS] VARCHAR(20) DEFAULT 'ACTIVE',
    [VIEW_COUNT] INT DEFAULT 0,
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [UPDATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3)
);
GO

-- ==========================================
-- INDEXES
-- ==========================================
CREATE NONCLUSTERED INDEX IX_USERS_EMAIL ON [USERS]([EMAIL]) WHERE [IS_ACTIVE] = 1;
GO
CREATE NONCLUSTERED INDEX IX_USERS_USER_CODE ON [USERS]([USER_CODE]);
GO
CREATE NONCLUSTERED INDEX IX_APPROVAL_WORKFLOW_STATUS ON [APPROVAL_WORKFLOW]([WORKFLOW_STATUS]);
GO
CREATE NONCLUSTERED INDEX IX_BOOKINGS_STATUS ON [BOOKINGS]([STATUS]);
GO
CREATE NONCLUSTERED INDEX IX_BOOKINGS_BOOKED_BY ON [BOOKINGS]([BOOKED_BY]);
GO
CREATE NONCLUSTERED INDEX IX_TRANSACTION_LOGS_MODULE ON [TRANSACTION_LOGS]([MODULE_NAME], [PERFORMED_ON]);
GO
CREATE NONCLUSTERED INDEX IX_TIMESHEETS_EMPLOYEE ON [TIMESHEETS]([EMPLOYEE_ID], [PERIOD_START]);
GO
CREATE NONCLUSTERED INDEX IX_REIMBURSEMENT_CLAIMS_STATUS ON [REIMBURSEMENT_CLAIMS]([STATUS]);
GO
CREATE NONCLUSTERED INDEX IX_MEETINGS_ORGANIZER ON [MEETINGS]([ORGANIZER_ID], [START_TIME]);
GO

PRINT '==========================================';
PRINT 'SRFSPARSHDB initial schema setup complete.';
PRINT '==========================================';
GO
