-- ==========================================
-- DEVELOPMENT MODULE - Schema
-- Database: LETDB
-- Purpose: Learning & Development Plan Management
-- Created: March 9, 2026
-- ==========================================

USE LETDB;
GO

-- ==========================================
-- DEVELOPMENT MODULE - Core Tables
-- ==========================================

-- Table: DD_LETPLAN
CREATE TABLE [DD_LETPLAN] (
    [DD_REQNUM] BIGINT NOT NULL PRIMARY KEY,
    [DD_SNO] BIGINT NULL,
    [DD_USERID] VARCHAR(255) NULL,
    [DD_PINNUM] BIGINT NULL,
    [DD_DEVSOURCE] VARCHAR(255) NULL,
    [DD_DEVNEED] VARCHAR(255) NULL,
    [DD_DEVINDICATOR] VARCHAR(255) NULL,
    [DD_DEVMODE] BIGINT NULL,
    [DD_RECPROG] VARCHAR(255) NULL,
    [DD_TRAININGPROGRAM] VARCHAR(255) NULL,
    [DD_INTERNALTRAINING] BIGINT NULL,
    [DD_REVDATE] VARCHAR(255) NULL,
    [DD_PRIORITY] BIGINT NULL,
    [DD_ENTDATE] DATETIME2(3) NULL,
    [DD_APPSTATUS] CHAR(1) NULL,
    [DD_BHRSTATUS] CHAR(1) NULL
);

-- Table: DD_LETPLAN_PROB
CREATE TABLE [DD_LETPLAN_PROB] (
    [DD_REQNUM] BIGINT NULL,
    [DD_SNO] BIGINT NULL,
    [DD_USERID] VARCHAR(255) NULL,
    [DD_PINNUM] BIGINT NULL,
    [DD_DEVSOURCE] VARCHAR(255) NULL,
    [DD_DEVNEED] VARCHAR(255) NULL,
    [DD_DEVINDICATOR] VARCHAR(255) NULL,
    [DD_DEVMODE] BIGINT NULL,
    [DD_RECPROG] VARCHAR(255) NULL,
    [DD_TRAININGPROGRAM] VARCHAR(255) NULL,
    [DD_INTERNALTRAINING] BIGINT NULL,
    [DD_REVDATE] VARCHAR(255) NULL,
    [DD_PRIORITY] BIGINT NULL,
    [DD_ENTDATE] DATETIME2(3) NULL,
    [DD_APPSTATUS] CHAR(1) NULL,
    [DD_BHRSTATUS] CHAR(1) NULL,
    [DD_STRDATE] DATETIME2(3) NULL,
    [DD_ENDATE] DATETIME2(3) NULL
);

-- Table: DD_LETBHRPLAN
CREATE TABLE [DD_LETBHRPLAN] (
    [DD_REQNUM] BIGINT NOT NULL PRIMARY KEY,
    [DD_SNO] BIGINT NULL,
    [DD_USERID] VARCHAR(255) NULL,
    [DD_TRAININGPROGRAM] VARCHAR(255) NULL,
    [DD_TRAININGCODE] DECIMAL(38) NULL,
    [DD_PRIORITY] DECIMAL(38) NULL,
    [DD_PINUM] BIGINT NULL,
    [DD_FINALACCEPT] VARCHAR(255) NULL,
    [DD_BHRACCEPT] CHAR(1) NULL
);

-- Table: DD_REQNUM_COMPE_IND
CREATE TABLE [DD_REQNUM_COMPE_IND] (
    [REQNUM] BIGINT NULL,
    [COMPNUM] DECIMAL(38) NULL,
    [INDNUM] DECIMAL(38) NULL,
    [FLAG] CHAR(1) NULL,
    [PINNUM] DECIMAL(38) NULL
);

-- Table: DD_COMPETENCY_IND
CREATE TABLE [DD_COMPETENCY_IND] (
    [SRL_NO] DECIMAL(38) NULL,
    [BAND] VARCHAR(50) NULL,
    [COMP_NUM] BIGINT NULL,
    [IND_FLAG] CHAR(1) NULL,
    [IND_DEFN] VARCHAR(4000) NULL
);

-- ==========================================
-- INDEXES FOR DEVELOPMENT MODULE
-- ==========================================

CREATE INDEX [IDX_DD_LETPLAN_USERID] ON [DD_LETPLAN]([DD_USERID]);
CREATE INDEX [IDX_DD_LETPLAN_PRIORITY] ON [DD_LETPLAN]([DD_PRIORITY]);
CREATE INDEX [IDX_DD_LETPLAN_STATUS] ON [DD_LETPLAN]([DD_APPSTATUS]);
CREATE INDEX [IDX_DD_COMPETENCY_COMPNUM] ON [DD_COMPETENCY_IND]([COMP_NUM]);

PRINT 'Development Module Schema created successfully.';
GO
