-- ==========================================
-- Module: FINANCE & ACCOUNTS PAYABLE
-- Description: Financial transactions and AP management
-- Tables: Invoice, payments, JV posting, tax configurations
-- ==========================================

USE [TRAVELDB];
GO

-- Table: AP_INVOICES_INTERFACE - Invoice interface
CREATE TABLE [AP_INVOICES_INTERFACE] (
    [INVOICE_ID] BIGINT NOT NULL,
    [INVOICE_NUM] VARCHAR(50) NULL,
    [INVOICE_TYPE_LOOKUP_CODE] VARCHAR(25) NULL,
    [INVOICE_DATE] VARCHAR(255) NULL,
    [VENDOR_ID] BIGINT NULL,
    [VENDOR_SITE_ID] BIGINT NULL,
    [INVOICE_AMOUNT] VARCHAR(255) NULL,
    [INVOICE_CURRENCY_CODE] VARCHAR(255) NULL,
    [EXCHANGE_RATE] VARCHAR(255) NULL,
    [EXCHANGE_RATE_TYPE] VARCHAR(30) NULL,
    [TERMS_ID] BIGINT NULL,
    [PAYMENT_METHOD_LOOKUP_CODE] VARCHAR(25) NULL,
    [DESCRIPTION] VARCHAR(240) NULL,
    [LAST_UPDATE_DATE] VARCHAR(255) NULL,
    [LAST_UPDATED_BY] BIGINT NULL,
    [CREATION_DATE] VARCHAR(255) NULL,
    [CREATED_BY] BIGINT NULL,
    [ORG_ID] DECIMAL(80,0) NULL,
    [STATUS] CHAR(1) NULL,
    [AGENCY_ID] BIGINT NULL,
    CONSTRAINT [PK_AP_INVOICES_INTERFACE] PRIMARY KEY ([INVOICE_ID])
);

-- Table: AP_INVOICE_LINES_INTERFACE - Invoice line interface
CREATE TABLE [AP_INVOICE_LINES_INTERFACE] (
    [INVOICE_ID] BIGINT NOT NULL,
    [INVOICE_LINE_ID] BIGINT NULL,
    [LINE_NUMBER] BIGINT NOT NULL,
    [LINE_TYPE_LOOKUP_CODE] VARCHAR(25) NULL,
    [AMOUNT] DECIMAL(38) NULL,
    [ACCOUNTING_DATE] DATETIME2(3) NULL,
    [DESCRIPTION] VARCHAR(240) NULL,
    [LAST_UPDATED_BY] BIGINT NULL,
    [LAST_UPDATE_DATE] DATETIME2(3) NULL,
    [CREATED_BY] BIGINT NULL,
    [CREATION_DATE] DATETIME2(3) NULL,
    [ORG_ID] BIGINT NULL,
    [ACCOUNT_CODE] VARCHAR(25) NULL,
    [PROJECT_CODE] VARCHAR(25) NULL,
    [SGSTAMT] DECIMAL(19,0) NULL,
    [CGSTAMT] DECIMAL(19,0) NULL,
    [IGSTAMT] DECIMAL(19,0) NULL
);

-- Table: AP_TERMS_TL - Payment terms
CREATE TABLE [AP_TERMS_TL] (
    [TERM_ID] BIGINT NOT NULL,
    [LAST_UPDATE_DATE] DATETIME2(3) NOT NULL,
    [LAST_UPDATED_BY] BIGINT NOT NULL,
    [CREATION_DATE] DATETIME2(3) NOT NULL,
    [CREATED_BY] BIGINT NOT NULL,
    [NAME] VARCHAR(50) NOT NULL,
    [ENABLED_FLAG] VARCHAR(1) NOT NULL,
    [DUE_CUTOFF_DAY] DECIMAL(38) NULL,
    [DESCRIPTION] VARCHAR(240) NULL
);

-- Table: PAYMENT_DETAILS - Payment  details
CREATE TABLE [PAYMENT_DETAILS] (
    [SNO] BIGINT NULL,
    [BOOK_NO] BIGINT NULL,
    [VENDOR] VARCHAR(200) NULL,
    [TS_TKT_CST] DECIMAL(19,0) NULL,
    [TS_TKT_ADJ] DECIMAL(19,0) NULL,
    [TS_BASE_STAX] DECIMAL(19,0) NULL,
    [TS_APPROVE_AMT] DECIMAL(19,0) NULL,
    [TS_STATUS] VARCHAR(65) NULL,
    [TM_INV_NUM] VARCHAR(65) NULL,
    [TM_INV_DAT] VARCHAR(255) NULL,
    [TM_INV_AMT] DECIMAL(19,0) NULL,
    [TM_TOTAPPRAMT] DECIMAL(19,0) NULL,
    [TM_TOTAL] DECIMAL(19,0) NULL,
    [TM_JVNO] BIGINT NULL,
    [TM_PAYMENTTERMS] VARCHAR(20) NULL,
    [SERVICETAX] DECIMAL(19,0) NULL
);

-- Table: TRAVEL_BATCH_MAIN - Batch main records
CREATE TABLE [TRAVEL_BATCH_MAIN] (
    [TM_UNT_COD] CHAR(3) NOT NULL  -- UNIT CODE,
    [TM_BAT_NUM] DECIMAL(38) NOT NULL  -- BATCH NUMBER,
    [TM_BAT_DAT] DATETIME2(3) NULL  -- BATCH GENERATION DATE,
    [TM_INV_NUM] VARCHAR(25) NULL  -- INVOICE NO,
    [TM_INV_DAT] DATETIME2(3) NULL  -- INVOICE DATE,
    [TM_BAT_STS] CHAR(1) NULL  -- Status,
    [TM_ADM_REM] VARCHAR(200) NULL  -- BATCH ADMIN REMARKS,
    [TM_FIN_REM] VARCHAR(200) NULL  -- BATCH FINANCE REMARKS,
    [TM_AGN_COD] DECIMAL(38) NULL  -- AGENCY CODE,
    [TM_TOTAPPRAMT] DECIMAL(19,0) NULL,
    [TM_TOTAL] DECIMAL(19,0) NULL,
    [TM_JVNO] BIGINT NULL,
    [TM_CGSTAMT] DECIMAL(19,0) NULL,
    [TM_SGSTAMT] DECIMAL(19,0) NULL,
    [TM_IGSTAMT] DECIMAL(19,0) NULL,
    CONSTRAINT [PK_TRAVEL_BATCH_MAIN] PRIMARY KEY ([TM_UNT_COD], [TM_BAT_NUM])
);

-- Table: TRAVEL_BATCH_SUB - Batch sub records
CREATE TABLE [TRAVEL_BATCH_SUB] (
    [TS_UNT_COD] CHAR(3) NOT NULL  -- UNIT CODE,
    [TS_BAT_NUM] DECIMAL(38) NOT NULL  -- BATCH NUMBER,
    [TS_SRL_NUM] DECIMAL(38) NOT NULL  -- AUTO SERIAL NUMBER,
    [TS_BOK_NUM] DECIMAL(38) NULL  -- BOOKING CONFORMATION NO,
    [TS_TKT_CST] DECIMAL(19,0) NULL  -- TICKET COST,
    [TS_TKT_ADJ] DECIMAL(19,0) NULL  -- TICKET COST ADJUSTMENT,
    [TS_APPROVE_AMT] DECIMAL(19,0) NULL,
    [TS_REASON] VARCHAR(255) NULL,
    [TS_STATUS] VARCHAR(255) NULL,
    [TS_CGSTAMT] VARCHAR(255) NULL,
    [TS_SGSTAMT] VARCHAR(255) NULL,
    [TS_IGSTAMT] VARCHAR(255) NULL
);

-- Table: JVPOSTDET - JV posting detail
CREATE TABLE [JVPOSTDET] (
    [JVINTCODE] BIGINT NOT NULL  -- JV internal Code,
    [JVDOCNUM] INT NOT NULL  -- JV number,
    [JV_COM_COD] CHAR(3) NOT NULL  -- Company Code,
    [JV_GRD_TYP] VARCHAR(3) NOT NULL  -- Grade type,
    [JV_ST_DAT] DATETIME2(3) NOT NULL  -- Start Date,
    [JV_ED_DAT] DATETIME2(3) NOT NULL  -- End Date,
    [JV_COMMENT] VARCHAR(50) NULL  -- Remakrs,
    [JV_STATUS] DATETIME2(3) NULL  -- Status flag,
    [JV_PAY_NUM] BIGINT NULL  -- Pay number,
    [JV_DATE] DATETIME2(3) NULL
);

-- Table: PAY_JV - Payment JV
CREATE TABLE [PAY_JV] (
    [AC_ENT_COD] CHAR(3) NOT NULL  -- Company Code,
    [AC_FIN_YER] DATETIME2(3) NOT NULL  -- Financial Year,
    [AC_DOC_NUM] BIGINT NOT NULL  -- Document No,
    [AC_SRL_NUM] BIGINT NOT NULL  -- Serial No,
    [AC_PAY_NUM] BIGINT NULL  -- Pay Batch No,
    [AC_PAY_DAT] DATETIME2(3) NULL  -- Pay Date,
    [AC_ACC_COD] CHAR(6) NULL  -- Account Code,
    [AC_TRN_AMT] DECIMAL(19,0) NULL  -- Transaction Amount,
    [AC_NAR_TON] VARCHAR(200) NULL  -- Narration,
    [AC_PST_TYP] CHAR(1) NULL  -- Posting Flag,
    [AC_ENT_DAT] DATETIME2(3) NULL  -- Entered On,
    [AC_CAN_DAT] DATETIME2(3) NULL  -- Cancelled On,
    [AC_ENT_USR] VARCHAR(25) NULL  -- Entered By,
    CONSTRAINT [PK_PAY_JV] PRIMARY KEY ([AC_SRL_NUM], [AC_FIN_YER], [AC_DOC_NUM], [AC_ENT_COD])
);

-- Table: PAY_OTHDET - Payment other details
CREATE TABLE [PAY_OTHDET] (
    [PY_COM_COD] BIGINT NOT NULL  -- Company Code,
    [PY_TRN_NUM] BIGINT NOT NULL  -- Transaction No,
    [PY_PAY_NUM] BIGINT NULL  -- Pay Batch No,
    [PY_VND_COD] BIGINT NULL  -- Vendor No,
    [PY_TRN_DAT] DATETIME2(3) NULL  -- Transaction Date,
    [PY_PAY_MOD] CHAR(3) NULL  -- Pay Mode,
    [PY_PAY_AMT] DECIMAL(19,0) NULL  -- Pay Amount,
    [PY_CHQ_DAT] DATETIME2(3) NULL  -- Cheque Date,
    [PY_CHQ_NUM] BIGINT NULL  -- Cheque No,
    [PY_PAY_DAT] DATETIME2(3) NULL  -- Pay Date,
    [PY_REM_MRK] VARCHAR(4000) NULL  -- Remarks,
    [PY_STS_COD] CHAR(1) NULL,
    CONSTRAINT [PK_PAY_OTHDET] PRIMARY KEY ([PY_COM_COD])
);

-- Table: TRAVEL_ACCOUNT - Travel account entry
CREATE TABLE [TRAVEL_ACCOUNT] (
    [AC_TRN_NUM] BIGINT NOT NULL  -- Transaction No,
    [AC_UNT_COD] CHAR(3) NOT NULL  -- Unit Code,
    [AC_USR_COD] VARCHAR(20) NULL  -- User Code,
    [AC_USR_NUM] BIGINT NULL  -- User Number,
    [AC_DC_FLG] CHAR(1) NULL  -- Debit/Credit Flag (D/C),
    [AC_TRN_AMT] DECIMAL(19,0) NULL  -- Transaction Amount,
    [AC_ACC_COD] CHAR(3) NULL  -- Travel Account Code,
    [AC_REM_MRK] VARCHAR(200) NULL  -- Description,
    [AC_ACC_TYP] CHAR(3) NULL  -- ADV/PLN/SET,
    [AC_JV_STS] CHAR(1) NULL  -- JV Posting Status (Y/N)
);

GO
