-- ===========================================================
-- Migration Script: InitialCreate
-- Database: HRDB (LocalDB)
-- Service:  CompensationBenefitsService
-- ===========================================================
USE [HRDB];
GO

-- SALARY_MAIN
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='SALARY_MAIN')
BEGIN
    CREATE TABLE [SALARY_MAIN] (
        [SALARY_ID]          DECIMAL(38) NOT NULL,
        [SALARY_TYPE]        CHAR(1) NOT NULL,
        [SALARY_CTC]         DECIMAL(38) NOT NULL,
        [SALARY_STRUCTUREID] DECIMAL(38) NOT NULL,
        [SALARY_FOOTERID]    DECIMAL(38) NOT NULL,
        [SALARY_COPYEMPSYSID] DECIMAL(38) NULL,
        [SALARY_CREATEDBY]   DECIMAL(38) NOT NULL,
        [SALARY_CREATEDON]   DATETIME2(3) NOT NULL,
        [SALARY_CANCELLEDBY] DECIMAL(38) NULL,
        [SALARY_CANCELLEDON] DATETIME2(3) NULL,
        CONSTRAINT [PK_SALARY_MAIN] PRIMARY KEY ([SALARY_ID])
    );
END
GO

-- SALARY_DET
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='SALARY_DET')
BEGIN
    CREATE TABLE [SALARY_DET] (
        [SALDET_ID]         DECIMAL(38) NOT NULL,
        [SALDET_SALARYID]   DECIMAL(38) NOT NULL,
        [SALDET_SRL]        DECIMAL(38) NOT NULL,
        [SALDET_ANNGROUP]   VARCHAR(50) NULL,
        [SALDET_EDID]       DECIMAL(38) NOT NULL,
        [SALDET_CATEGORY]   CHAR(1) NOT NULL,
        [SALDET_EDNAME]     VARCHAR(50) NOT NULL,
        [SALDET_EDAMT]      DECIMAL(38) NOT NULL,
        [SALDET_FREQUENCY]  CHAR(1) NOT NULL,
        [SALDET_SUPERCHAR]  VARCHAR(25) NULL,
        [SALDET_SUPERDESC]  VARCHAR(1000) NULL,
        [SALDET_YEARTYPE]   CHAR(1) NULL,
        [SALDET_GLOBALUNITID] DECIMAL(38) NULL,
        [SALDET_FORMULA]    CHAR(1) NOT NULL,
        [SALDET_SHOWMONTHLY] CHAR(1) NOT NULL,
        [SALDET_ANNEXONLY]  CHAR(1) NOT NULL,
        CONSTRAINT [PK_SALARY_DET] PRIMARY KEY ([SALDET_ID]),
        CONSTRAINT [FK_SALARY_DET_MAIN] FOREIGN KEY ([SALDET_SALARYID]) REFERENCES [SALARY_MAIN]([SALARY_ID])
    );
END
GO

-- SALSTRUCTURE_MAIN
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='SALSTRUCTURE_MAIN')
BEGIN
    CREATE TABLE [SALSTRUCTURE_MAIN] (
        [STRUCTURE_ID]             DECIMAL(38) NOT NULL,
        [STRUCTURE_UNITID]         DECIMAL(38) NOT NULL,
        [STRUCTURE_NAME]           VARCHAR(200) NOT NULL,
        [STRUCTURE_GRADECATEGORY]  CHAR(3) NOT NULL,
        [STRUCTURE_APPLYTOALL]     DECIMAL(38) NOT NULL,
        [STRUCTURE_GRADEID]        DECIMAL(38) NOT NULL,
        [STRUCTURE_TYPE]           CHAR(1) NOT NULL,
        [STRUCTURE_CTCMIN]         DECIMAL(38) NOT NULL,
        [STRUCTURE_CTCMAX]         DECIMAL(38) NOT NULL,
        [STRUCTURE_FOOTERID]       DECIMAL(38) NOT NULL,
        [STRUCTURE_CLSDATE]        DATETIME2(3) NULL,
        [STRUCTURE_CREATEDBY]      DECIMAL(38) NOT NULL,
        [STRUCTURE_CREATEDON]      DATETIME2(3) NOT NULL,
        [STRUCTURE_LASTMODIFIEDBY] DECIMAL(38) NOT NULL,
        [STRUCTURE_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
        [STRUCTURET_APPLYTOALLUNIT] DECIMAL(38) NULL,
        [STRUCTURE_OFFERFOOTERID]  DECIMAL(38) NULL,
        CONSTRAINT [PK_SALSTRUCTURE_MAIN] PRIMARY KEY ([STRUCTURE_ID])
    );
END
GO

-- SALSTRUCTURE_DET
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='SALSTRUCTURE_DET')
BEGIN
    CREATE TABLE [SALSTRUCTURE_DET] (
        [STRUCTDET_ID]             DECIMAL(38) NOT NULL,
        [STRUCTDET_STRUCTUREID]    DECIMAL(38) NOT NULL,
        [STRUCTDET_EDID]           DECIMAL(38) NOT NULL,
        [STRUCTDET_AMTTYPE]        CHAR(1) NOT NULL,
        [STRUCTDET_CALTYPE]        DECIMAL(38) NOT NULL,
        [STRUCTDET_CATEGORY]       CHAR(1) NOT NULL,
        [STRUCTDET_FREQUENCY]      CHAR(1) NOT NULL,
        [STRUCTDET_EDAMT]          DECIMAL(38) NOT NULL,
        [STRUCTDET_MINVALUE]       DECIMAL(38) NOT NULL,
        [STRUCTDET_MAXVALUE]       DECIMAL(38) NULL,
        [STRUCTDET_GLOBALUNITID]   DECIMAL(38) NULL,
        [STRUCTDET_SUPERCHAR]      VARCHAR(25) NULL,
        [STRUCTDET_SUPERDESC]      VARCHAR(1000) NULL,
        [STRUCTDET_MODIFY]         CHAR(1) NOT NULL,
        [STRUCTDET_FORMULA]        CHAR(1) NOT NULL,
        [STRUCTDET_CREATEDBY]      DECIMAL(38) NOT NULL,
        [STRUCTDET_CREATEDON]      DATETIME2(3) NOT NULL,
        [STRUCTDET_LASTMODIFIEDBY] DECIMAL(38) NOT NULL,
        [STRUCTDET_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
        [STRUCTURE_SHOWMONTHLY]    CHAR(1) NOT NULL,
        [STRUCTURE_ANNEXONLY]      CHAR(1) NOT NULL,
        CONSTRAINT [PK_SALSTRUCTURE_DET] PRIMARY KEY ([STRUCTDET_ID]),
        CONSTRAINT [FK_STRUCTDET_MAIN] FOREIGN KEY ([STRUCTDET_STRUCTUREID]) REFERENCES [SALSTRUCTURE_MAIN]([STRUCTURE_ID])
    );
END
GO

-- MEDICLAIM_MASTER
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='MEDICLAIM_MASTER')
BEGIN
    CREATE TABLE [MEDICLAIM_MASTER] (
        [MEDICLAIM_ID]            DECIMAL(38) NOT NULL,
        [MEDICLAIM_REFNAME]       VARCHAR(200) NULL,
        [MEDICLAIM_PROVIDERID]    DECIMAL(38) NULL,
        [MEDICLAIM_TPPID]         DECIMAL(38) NULL,
        [MEDICLAIM_STARTDATE]     DATETIME2(3) NULL,
        [MEDICLAIM_CLOSEDATE]     DATETIME2(3) NULL,
        [MEDICLAIM_MAXENTRYDATE]  DATETIME2(3) NULL,
        [MEDICLAIM_INSREFNO]      VARCHAR(100) NULL,
        [MEDICLAIM_TYPE]          VARCHAR(1) NULL,
        [MEDICLAIM_PAIDBY]        CHAR(1) NULL,
        [MEICLAIM_SERVICETAXPER]  BIGINT NULL,
        [MEDICLAIM_COMPPAYLIMIT]  DECIMAL(38) NULL,
        [MEDICLAIM_LOADINGPER]    BIGINT NULL,
        [MEDICLAIM_NONCLAIMPER]   BIGINT NULL,
        CONSTRAINT [PK_MEDICLAIM_MASTER] PRIMARY KEY ([MEDICLAIM_ID])
    );
END
GO

-- MEDICLAIM_YEARLYPREM
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='MEDICLAIM_YEARLYPREM')
BEGIN
    CREATE TABLE [MEDICLAIM_YEARLYPREM] (
        [MEDYP_YEARLYPREMID]  DECIMAL(38) NOT NULL,
        [MEDYP_MEDICLAIMID]   DECIMAL(38) NOT NULL,
        [MEDYP_SUMASSURED]    DECIMAL(38) NOT NULL,
        [MEDYP_PREMIUMAMNT]   DECIMAL(38) NOT NULL,
        [MEDYP_MODIFIEDBY]    DECIMAL(38) NOT NULL,
        [MEDYP_MODIFIEDON]    DATETIME2(3) NOT NULL,
        [MEDYP_TYPE]          CHAR(1) NOT NULL,
        CONSTRAINT [PK_MEDICLAIM_YEARLYPREM] PRIMARY KEY ([MEDYP_YEARLYPREMID]),
        CONSTRAINT [FK_MEDYP_MASTER] FOREIGN KEY ([MEDYP_MEDICLAIMID]) REFERENCES [MEDICLAIM_MASTER]([MEDICLAIM_ID])
    );
END
GO

-- MEDICLAIM_DET
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='MEDICLAIM_DET')
BEGIN
    CREATE TABLE [MEDICLAIM_DET] (
        [MED_NOMINATIONRUNID]    DECIMAL(38) NOT NULL,
        [MED_NOMINATIONID]       DECIMAL(38) NOT NULL,
        [MED_RELATIONSHIP]       DECIMAL(38) NOT NULL,
        [MED_NOMINEENAME]        VARCHAR(200) NOT NULL,
        [MED_NOMINEEDOB]         DATETIME2(3) NULL,
        [MED_NOMINEEAGE]         DECIMAL(38) NULL,
        [MED_NOMINEEGENDER]      CHAR(1) NOT NULL,
        [MED_PREMIUM]            DECIMAL(38) NULL,
        [MED_TAXSTATUS]          CHAR(1) NOT NULL,
        [MED_NETPREMIUM]         DECIMAL(19,0) NULL,
        [MED_PREMIUMSERVICETAX]  DECIMAL(19,0) NULL,
        [MED_GROSSPREMIUM]       DECIMAL(19,0) NULL,
        CONSTRAINT [PK_MEDICLAIM_DET] PRIMARY KEY ([MED_NOMINATIONRUNID])
    );
END
GO

-- MEDICLAIM_EXCEPTION
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='MEDICLAIM_EXCEPTION')
BEGIN
    CREATE TABLE [MEDICLAIM_EXCEPTION] (
        [MEDICLAIM_EMPSYSID] DECIMAL(38) NOT NULL,
        [MEDICLAIM_ID]       DECIMAL(38) NOT NULL
    );
END
GO

-- MEDICLAIM_PREMPERCENTAGE
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='MEDICLAIM_PREMPERCENTAGE')
BEGIN
    CREATE TABLE [MEDICLAIM_PREMPERCENTAGE] (
        [MED_PPID]          DECIMAL(38) NOT NULL,
        [MED_RELATIONSHIPID] DECIMAL(38) NOT NULL,
        [MED_PERCENTAGE]    DECIMAL(38) NOT NULL,
        CONSTRAINT [PK_MEDICLAIM_PREMPERCENTAGE] PRIMARY KEY ([MED_PPID])
    );
END
GO

-- MOBILE_CONNECTION
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='MOBILE_CONNECTION')
BEGIN
    CREATE TABLE [MOBILE_CONNECTION] (
        [CONN_ID]           BIGINT NOT NULL,
        [CONN_EMPSYSID]     BIGINT NOT NULL,
        [CONN_EFFDATE]      DATETIME2(3) NOT NULL,
        [CONN_CLSDATE]      DATETIME2(3) NULL,
        [CONN_TYPE]         CHAR(1) NOT NULL,
        [CONN_PHONENO]      BIGINT NOT NULL,
        [CONN_REMARKS]      VARCHAR(500) NULL,
        [CONN_OPENREQUESTNO]  BIGINT NULL,
        [CONN_CLOSEREQUESTNO] BIGINT NULL,
        [CONN_CALENDARID]   BIGINT NOT NULL,
        [CONN_CREATEDBY]    BIGINT NOT NULL,
        [CONN_CREATEDON]    DATETIME2(3) NOT NULL,
        [CONN_MODIFIEDBY]   BIGINT NULL,
        [CONN_MODIFIEDON]   DATETIME2(3) NULL,
        CONSTRAINT [PK_MOBILE_CONNECTION] PRIMARY KEY ([CONN_ID])
    );
END
GO

-- MOBILE_LIMITMAST
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='MOBILE_LIMITMAST')
BEGIN
    CREATE TABLE [MOBILE_LIMITMAST] (
        [LIMIT_ID]         BIGINT NOT NULL,
        [LIMIT_ORG]        BIGINT NOT NULL,
        [LIMIT_UNITID]     BIGINT NOT NULL,
        [LIMIT_GRADECATID] CHAR(3) NOT NULL,
        [LIMIT_GRADEID]    BIGINT NOT NULL,
        [LIMIT_ELGAMT]     BIGINT NOT NULL,
        [LIMIT_EFFDATE]    DATETIME2(3) NOT NULL,
        [LIMIT_CLSDATE]    DATETIME2(3) NULL,
        [LIMIT_CREATEDBY]  BIGINT NOT NULL,
        [LIMIT_CREATEDON]  DATETIME2(3) NOT NULL,
        [LIMIT_MODIFIEDBY] BIGINT NULL,
        [LIMIT_MODIFIEDON] DATETIME2(3) NULL,
        CONSTRAINT [PK_MOBILE_LIMITMAST] PRIMARY KEY ([LIMIT_ID])
    );
END
GO

-- MOBILE_ADDLIMIT
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='MOBILE_ADDLIMIT')
BEGIN
    CREATE TABLE [MOBILE_ADDLIMIT] (
        [ADD_ID]        BIGINT NOT NULL,
        [ADD_EMPSYSID]  BIGINT NOT NULL,
        [ADD_EFFDATE]   DATETIME2(3) NOT NULL,
        [ADD_CLSDATE]   DATETIME2(3) NULL,
        [ADD_REMARKS]   VARCHAR(500) NULL,
        [ADD_AMT]       BIGINT NOT NULL,
        [ADD_CALENDARID] BIGINT NOT NULL,
        [ADD_CREATEDBY] BIGINT NOT NULL,
        [ADD_CREATEDON] DATETIME2(3) NOT NULL,
        [ADD_MODIFIEDBY] DECIMAL(38) NULL,
        [ADD_MODIFIEDON] DATETIME2(3) NULL,
        CONSTRAINT [PK_MOBILE_ADDLIMIT] PRIMARY KEY ([ADD_ID])
    );
END
GO

-- EMP_RETIRALS_EMPSPECIFIC
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='EMP_RETIRALS_EMPSPECIFIC')
BEGIN
    CREATE TABLE [EMP_RETIRALS_EMPSPECIFIC] (
        [EMPRET_ID]         BIGINT NOT NULL,
        [EMPRET_EMPSYSID]   BIGINT NOT NULL,
        [EMPRET_PAYTYPE]    VARCHAR(3) NOT NULL,
        [EMPRET_EDID]       BIGINT NOT NULL,
        [EMPRET_EFFDATE]    DATETIME2(3) NOT NULL,
        [EMPRET_CLSDATE]    DATETIME2(3) NULL,
        [EMPRET_PERCENTAGE] BIGINT NOT NULL,
        [EMPRET_CREATEDBY]  BIGINT NOT NULL,
        [EMPRET_CREATEDON]  DATETIME2(3) NOT NULL,
        [EMPRET_MODIFIEDBY] BIGINT NULL,
        [EMPRET_MODIFIEDON] DATETIME2(3) NULL,
        CONSTRAINT [PK_EMP_RETIRALS_EMPSPECIFIC] PRIMARY KEY ([EMPRET_ID])
    );
END
GO

-- EMP_RETIRALSDET
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='EMP_RETIRALSDET')
BEGIN
    CREATE TABLE [EMP_RETIRALSDET] (
        [ERDET_ID]        DECIMAL(38) NOT NULL,
        [ERDET_EMPSYSID]  DECIMAL(38) NOT NULL,
        [ERDET_PFCLSDATE] DATETIME2(3) NOT NULL,
        [ERDET_REMARKS]   VARCHAR(200) NOT NULL,
        [ERDET_MODIFIEDBY] DECIMAL(38) NOT NULL,
        [ERDET_MODIFIEDON] DATETIME2(3) NOT NULL,
        CONSTRAINT [PK_EMP_RETIRALSDET] PRIMARY KEY ([ERDET_ID])
    );
END
GO

-- RETRIALS_RANGEMAST
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='RETRIALS_RANGEMAST')
BEGIN
    CREATE TABLE [RETRIALS_RANGEMAST] (
        [RRMAST_ID]         DECIMAL(38) NOT NULL,
        [RRMAST_UNITID]     DECIMAL(38) NOT NULL,
        [RRMAST_FROMYEAR]   DECIMAL(38) NOT NULL,
        [RRMAST_TOYEAR]     DECIMAL(38) NOT NULL,
        [RRMAST_PERCENTAGE] DECIMAL(38) NOT NULL,
        [RRMAST_MODIFIEDBY] DECIMAL(38) NOT NULL,
        [RRMAST_MODIFIEDON] DATETIME2(3) NOT NULL,
        CONSTRAINT [PK_RETRIALS_RANGEMAST] PRIMARY KEY ([RRMAST_ID])
    );
END
GO

-- BASIC_SLABINC
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='BASIC_SLABINC')
BEGIN
    CREATE TABLE [BASIC_SLABINC] (
        [SLAB_INCID]        BIGINT NOT NULL,
        [SLAB_GRADEID]      BIGINT NOT NULL,
        [SLAB_UNITID]       BIGINT NOT NULL,
        [SLAB_INCSTRTDATE]  DATETIME2(3) NOT NULL,
        [SLAB_INCCLSDATE]   DATETIME2(3) NULL,
        [SLAB_INCMODIFIEDBY] BIGINT NOT NULL,
        [SLAB_INCMODIFIEDON] DATETIME2(3) NOT NULL,
        CONSTRAINT [PK_BASIC_SLABINC] PRIMARY KEY ([SLAB_INCID])
    );
END
GO

-- COMP_PARAMS
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='COMP_PARAMS')
BEGIN
    CREATE TABLE [COMP_PARAMS] (
        [CP_ID]          DECIMAL(38) NOT NULL,
        [CP_COUNTRYCODE] VARCHAR(3) NOT NULL,
        [CP_EDGROUP]     VARCHAR(3) NOT NULL,
        [CP_TYPE]        VARCHAR(3) NOT NULL,
        [CP_EDID]        DECIMAL(38) NOT NULL,
        [CP_MODIFIEDBY]  DECIMAL(38) NOT NULL,
        [CP_MODIFIEDON]  DATETIME2(3) NOT NULL,
        CONSTRAINT [PK_COMP_PARAMS] PRIMARY KEY ([CP_ID])
    );
END
GO

-- DILIGENCE_RATEMAST
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='DILIGENCE_RATEMAST')
BEGIN
    CREATE TABLE [DILIGENCE_RATEMAST] (
        [DILIGENCE_ID]              BIGINT NOT NULL,
        [DILIGENCE_PAYUNITID]       BIGINT NOT NULL,
        [DILIGENCE_GRADECATEGORY]   CHAR(3) NOT NULL,
        [DILIGENCE_EDID]            BIGINT NOT NULL,
        [DILIGENCE_YEARID]          INT NOT NULL,
        [DILIGENCE_AMOUNT]          DECIMAL(19,0) NOT NULL,
        [DILIGENCE_EFFDATE]         DATETIME2(3) NOT NULL,
        [DILIGENCE_CLSDATE]         DATETIME2(3) NULL,
        [DILIGENCE_LASTMODIFIEDBY]  BIGINT NOT NULL,
        [DILIGENCE_LASTMODIFIEDON]  DATETIME2(3) NOT NULL,
        [DILIGENCE_BENLOGID]        BIGINT NULL,
        CONSTRAINT [PK_DILIGENCE_RATEMAST] PRIMARY KEY ([DILIGENCE_ID])
    );
END
GO

-- PMS_CASHPAY
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='PMS_CASHPAY')
BEGIN
    CREATE TABLE [PMS_CASHPAY] (
        [CASHPAY_ID]          DECIMAL(38) NOT NULL,
        [CASHPAY_UNITID]      DECIMAL(38) NOT NULL,
        [CASHPAY_GRADECAT]    VARCHAR(5) NOT NULL,
        [CASHPAY_PAYTYPE]     CHAR(1) NOT NULL,
        [CASHPAY_EFFDATE]     DATETIME2(3) NOT NULL,
        [CASHPAY_CLSDATE]     DATETIME2(3) NULL,
        [CASHPAY_MODIFIEDBY]  DECIMAL(38) NOT NULL,
        [CASHPAY_MODIFIEDON]  DATETIME2(3) NOT NULL,
        CONSTRAINT [PK_PMS_CASHPAY] PRIMARY KEY ([CASHPAY_ID])
    );
END
GO

-- PMS_CASHPAYDET
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='PMS_CASHPAYDET')
BEGIN
    CREATE TABLE [PMS_CASHPAYDET] (
        [CASHPAY_DETID]  DECIMAL(38) NOT NULL,
        [CASHPAY_ID]     DECIMAL(38) NOT NULL,
        [CASHPAY_PER]    DECIMAL(38) NOT NULL,
        [CASHPAY_PAYDATE] VARCHAR(20) NOT NULL,
        CONSTRAINT [PK_PMS_CASHPAYDET] PRIMARY KEY ([CASHPAY_DETID]),
        CONSTRAINT [FK_CASHPAYDET_PAY] FOREIGN KEY ([CASHPAY_ID]) REFERENCES [PMS_CASHPAY]([CASHPAY_ID])
    );
END
GO

-- EMPLOYEE_CTCREMARKS
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='EMPLOYEE_CTCREMARKS')
BEGIN
    CREATE TABLE [EMPLOYEE_CTCREMARKS] (
        [CTCREM_EMP_SYSID] DECIMAL(38) NOT NULL,
        [CTCREM_ID]        DECIMAL(38) NOT NULL,
        [CTCREM_LINE1]     VARCHAR(200) NULL,
        [CTCREM_LINE2]     VARCHAR(200) NULL,
        [CTCREM_LINE3]     VARCHAR(200) NULL,
        [CTCREM_UPDATEDBY] DECIMAL(38) NULL,
        [CTCREM_UPDATEDON] DATETIME2(3) NULL,
        CONSTRAINT [PK_EMPLOYEE_CTCREMARKS] PRIMARY KEY ([CTCREM_EMP_SYSID])
    );
END
GO

-- TEVCTC (no PK - transactional view table)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='TEVCTC')
BEGIN
    CREATE TABLE [TEVCTC] (
        [CTC_EMP_SYSID]   DECIMAL(38) NOT NULL,
        [CTC_ID]          DECIMAL(38) NOT NULL,
        [CTC_EFF_DAT]     DATETIME2(3) NOT NULL,
        [CTC_CLS_DAT]     DATETIME2(3) NULL,
        [CTC_ED_ID]       DECIMAL(38) NOT NULL,
        [CTC_ED_FREQ]     CHAR(1) NOT NULL,
        [CTC_ED_AMTPA]    DECIMAL(38) NOT NULL,
        [CTC_TRANNO]      DECIMAL(38) NOT NULL,
        [CTC_SOURCE]      CHAR(3) NOT NULL,
        [CTC_STRUCTUREID] DECIMAL(38) NOT NULL,
        [CTC_UPDATEDBY]   DECIMAL(38) NOT NULL,
        [CTC_UPDATEDON]   DATETIME2(3) NOT NULL,
        [CTC_FORMULA]     CHAR(1) NOT NULL,
        [CTC_LOGNO]       DECIMAL(22,0) NULL
    );
END
GO

PRINT 'InitialCreate migration script completed successfully.';
GO
