-- TimeAttendance Module - Tables
USE [HRDB];
GO

-- Table: ABSENTEEISM_DET
CREATE TABLE [ABSENTEEISM_DET] (
    [ABS_ID] BIGINT NOT NULL  -- Absenteeism ID (Sequence),
    [ABS_UNITID] BIGINT NOT NULL  -- Unit ID,
    [ABS_YEAR] BIGINT NOT NULL  -- Year,
    [ABS_MONTH] BIGINT NOT NULL  -- Month,
    [ABS_TOTMANDAYS] BIGINT NOT NULL  -- Total Man Days,
    [ABS_ABSMANDAYS] BIGINT NOT NULL  -- Absent Days,
    [ABS_GRADECAT] CHAR(3) NOT NULL  -- Grade Category,
    [ABS_FUNCTIONID] BIGINT NOT NULL  -- Function,
    [ABS_AGEID] BIGINT NOT NULL  -- Age ID,
    [ABS_EXPERIENCEID] BIGINT NOT NULL  -- Experience ID,
    [ABS_GENDER] CHAR(1) NOT NULL  -- Gender,
    [ABS_INTEXPID] BIGINT NOT NULL  -- Internal Experience ID,
    [ABS_TOTEXPID] BIGINT NOT NULL  -- Total Experience ID,
    CONSTRAINT [PK_ABSENTEEISM_DET] PRIMARY KEY ([ABS_ID])
);



-- Table: ABSMIS
CREATE TABLE [ABSMIS] (
    [ABSID] BIGINT NOT NULL,
    [UNTID] INT NULL,
    [CID] INT NULL,
    [DID] BIGINT NULL,
    [SYSID] BIGINT NULL,
    [GRD] CHAR(3) NULL,
    [PLD] DECIMAL(38) NULL,
    [PDS] DECIMAL(38) NULL,
    [WOFF] DECIMAL(38) NULL,
    [LWOP] DECIMAL(38) NULL,
    [NPH] DECIMAL(38) NULL,
    [COF] DECIMAL(38) NULL,
    [BKL] DECIMAL(38) NULL,
    [APL] DECIMAL(38) NULL,
    [PNL] DECIMAL(38) NULL,
    [SWP] DECIMAL(38) NULL,
    [OND] DECIMAL(38) NULL,
    [MNTH] VARCHAR(6) NULL,
    [LOGSYSID] DECIMAL(38) NULL,
    [LWOPP] DECIMAL(38) NULL,
    CONSTRAINT [PK_ABSMIS] PRIMARY KEY ([ABSID])
);

