-- Module: Employee
USE DDDB;
GO

-- Table: BASIC_CHANGE
CREATE TABLE [BASIC_CHANGE] (
    [PINNO] DECIMAL(38) NULL,
    [CURBASIC] DECIMAL(38) NULL,
    [NEWBASIC] DECIMAL(38) NULL,
    [FINYEAR] DECIMAL(38) NULL,
    [EMPSYSID] DECIMAL(38) NULL
);



-- Table: DDEMPLIST2018
CREATE TABLE [DDEMPLIST2018] (
    [SYSID] DECIMAL(38) NOT NULL,
    [EMPNO] DECIMAL(38) NULL,
    [USERID] VARCHAR(25) NOT NULL,
    [USERID2] VARCHAR(25) NULL,
    [EM_TRM_FLG] CHAR(1) NULL,
    [EM_SAL_TYPE] VARCHAR(3) NULL,
    [DD_YEARID] DECIMAL(38) NULL,
    [UNIT_BUSINESSID] DECIMAL(38) NOT NULL,
    [PINNO] DECIMAL(38) NOT NULL,
    [UNIT] VARCHAR(20) NOT NULL,
    [HRROLEID] CHAR(3) NOT NULL,
    [EM_NICK_NAM] VARCHAR(65) NOT NULL,
    [EMPNAME] VARCHAR(4000) NULL,
    [EMP_FRS_NAME] VARCHAR(65) NOT NULL,
    [EMP_MID_NAME] VARCHAR(65) NULL,
    [EMP_LST_NAME] VARCHAR(65) NULL,
    [GRADE_CODE] CHAR(3) NULL,
    [GRADE_NAME] VARCHAR(50) NULL,
    [GRADE_ID] DECIMAL(38) NOT NULL,
    [CADRE_NAME] VARCHAR(20) NOT NULL,
    [EM_EFF_DAT] DATETIME2(3) NOT NULL,
    [EMP_JOINDATE] DATETIME2(3) NOT NULL,
    [GROUP_DOJ] DATETIME2(3) NULL,
    [EMP_CONFDATE] DATETIME2(3) NULL,
    [LASTVERTIPROMDATE] VARCHAR(4000) NULL,
    [UNIT_CODE] CHAR(3) NULL,
    [DDSTATUS] VARCHAR(11) NULL,
    [DDREQNO] DECIMAL(38) NULL,
    [DD_FORMCAT] VARCHAR(5) NULL,
    [EXIT] VARCHAR(3) NULL,
    [PROCESS_TYPE] VARCHAR(19) NULL,
    [EXPMONTHS] DECIMAL(38) NULL,
    [MYPROM] VARCHAR(4000) NULL,
    [INCSTATUS] VARCHAR(40) NULL,
    [EMP_CUR_LEVELID] DECIMAL(38) NULL,
    [EMP_GENDER] CHAR(1) NOT NULL,
    [HRSALUTE] VARCHAR(200) NULL,
    [DOB] DATETIME2(3) NOT NULL,
    [EMP_DESIGNATION] VARCHAR(100) NULL,
    [UNIT_ORGID] DECIMAL(38) NOT NULL
);



-- Table: DDGRADE2017
CREATE TABLE [DDGRADE2017] (
    [SYSID] DECIMAL(38) NULL,
    [PINNO] DECIMAL(38) NULL,
    [RULEGRADE] VARCHAR(10) NULL,
    [GRADE2] VARCHAR(10) NULL,
    [FINALGRADE] VARCHAR(10) NULL,
    [FINALGRADEID] DECIMAL(38) NULL
);



-- Table: DDTT
CREATE TABLE [DDTT] (
    [SRLNO] DECIMAL(38) NULL,
    [TEST] VARCHAR(4000) NULL,
    [TEST1] VARCHAR(9) NULL,
    [TEST2] VARCHAR(4000) NULL,
    [TEST3] VARCHAR(9) NULL,
    [SRLNO1] DECIMAL(38) NULL
);



-- Table: DDTT1
CREATE TABLE [DDTT1] (
    [SRLNO] DECIMAL(38) NULL,
    [TEST] VARCHAR(4000) NULL,
    [TEST1] VARCHAR(9) NULL,
    [TEST2] VARCHAR(4000) NULL,
    [TEST3] VARCHAR(9) NULL,
    [SRLNO1] DECIMAL(38) NULL
);



-- Table: DD_ACCOUNTABILITY
CREATE TABLE [DD_ACCOUNTABILITY] (
    [DD_ACCID] DECIMAL(38) NOT NULL,
    [DD_ACCDESC] VARCHAR(2000) NOT NULL,
    [DD_POSITIONID] DECIMAL(38) NOT NULL,
    [DD_ACCCLOSED] CHAR(1) NOT NULL,
    [DD_MODIFIEDBY] DECIMAL(38) NULL,
    [DD_MODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_DD_ACCOUNTABILITY] PRIMARY KEY ([DD_ACCID])
);



-- Table: DD_ACCOUNTABILITY_LOG
CREATE TABLE [DD_ACCOUNTABILITY_LOG] (
    [DD_ACCID] DECIMAL(38) NULL,
    [DD_ACCDESC] VARCHAR(2000) NOT NULL,
    [DD_POSITIONID] DECIMAL(38) NOT NULL,
    [DD_ACCCLOSED] CHAR(1) NOT NULL,
    [DD_MODIFIEDBY] DECIMAL(38) NULL,
    [DD_MODIFIEDON] DATETIME2(3) NULL,
    [LOG_CREATEDBY] DECIMAL(38) NULL,
    [LOG_CREATEDON] DATETIME2(3) NULL
);



-- Table: DD_APPFORCEDET
CREATE TABLE [DD_APPFORCEDET] (
    [DD_FORCEDETID] DECIMAL(38) NOT NULL,
    [DD_FORCEID] DECIMAL(38) NOT NULL,
    [DD_EMPSYSID] DECIMAL(38) NOT NULL,
    [DD_NOOFSKIP] DECIMAL(38) NOT NULL,
    CONSTRAINT [PK_DD_APPFORCEDET] PRIMARY KEY ([DD_FORCEDETID])
);



-- Table: DD_APPFORCEMAIN
CREATE TABLE [DD_APPFORCEMAIN] (
    [DD_FORCEID] DECIMAL(38) NOT NULL,
    [DD_TYPE] VARCHAR(5) NOT NULL,
    [DD_YEARID] DECIMAL(38) NOT NULL,
    [DD_TOTALSKIP] DECIMAL(38) NOT NULL,
    CONSTRAINT [PK_DD_APPFORCEMAIN] PRIMARY KEY ([DD_FORCEID])
);



-- Table: DD_APPMEETING_REQUEST
CREATE TABLE [DD_APPMEETING_REQUEST] (
    [DD_YEARID] DECIMAL(38) NULL,
    [DD_APPSYSID] DECIMAL(38) NULL,
    [DD_REQUESTEDON] DATETIME2(3) NULL,
    [DD_COMPLETEDON] DATETIME2(3) NULL
);



-- Table: DD_APP_SELFDEVELOP
CREATE TABLE [DD_APP_SELFDEVELOP] (
    [SD_REQ_NUM] DECIMAL(38) NULL,
    [SD_QTN_NUM] DECIMAL(38) NULL,
    [SD_SRL_NUM] DECIMAL(38) NULL,
    [SD_EFFORTS] VARCHAR(200) NULL,
    [SD_BENEFITS] VARCHAR(200) NULL,
    [SD_APP_ID] VARCHAR(30) NULL,
    [SD_APP_NUM] DECIMAL(38) NULL,
    [SD_DATE] DATETIME2(3) NULL
);



-- Table: DD_APP_STARTSTOP
CREATE TABLE [DD_APP_STARTSTOP] (
    [AP_REQ_NUM] DECIMAL(38) NOT NULL,
    [AP_QTN_NUM] DECIMAL(38) NOT NULL,
    [AP_SRL_NUM] DECIMAL(38) NOT NULL,
    [AP_START] VARCHAR(4000) NULL,
    [AP_STOP] VARCHAR(4000) NULL,
    [AP_CONTINUE] VARCHAR(4000) NULL,
    [AP_MODIFIEDBY] DECIMAL(38) NULL,
    [AP_MODIFIEDON] DATETIME2(3) NULL
);



-- Table: DD_APP_STARTSTOP_LOG
CREATE TABLE [DD_APP_STARTSTOP_LOG] (
    [AP_REQ_NUM] DECIMAL(38) NOT NULL,
    [AP_QTN_NUM] DECIMAL(38) NOT NULL,
    [AP_SRL_NUM] DECIMAL(38) NOT NULL,
    [AP_START] VARCHAR(4000) NULL,
    [AP_STOP] VARCHAR(4000) NULL,
    [AP_CONTINUE] VARCHAR(4000) NULL,
    [AP_MODIFIEDBY] DECIMAL(38) NOT NULL,
    [AP_MODIFIEDON] DATETIME2(3) NOT NULL,
    [AP_LOGCREATEDBY] DECIMAL(38) NOT NULL,
    [AP_LOGCREATEDON] DATETIME2(3) NOT NULL
);



-- Table: DD_APP_SUBEFFORTS
CREATE TABLE [DD_APP_SUBEFFORTS] (
    [DL_REQ_NUM] DECIMAL(38) NULL,
    [DL_QTN_NUM] DECIMAL(38) NULL,
    [DL_SRL_NUM] DECIMAL(38) NULL,
    [DL_SUBOR_NAME] VARCHAR(200) NULL,
    [DL_EFFORTS] VARCHAR(200) NULL,
    [DL_BENEFITS] VARCHAR(200) NULL,
    [DL_APP_ID] VARCHAR(30) NULL,
    [DL_APP_NUM] DECIMAL(38) NULL,
    [DL_DATE] DATETIME2(3) NULL
);



-- Table: DD_APP_SUCCESSOR
CREATE TABLE [DD_APP_SUCCESSOR] (
    [DL_REQ_NUM] DECIMAL(38) NULL,
    [DL_QTN_NUM] DECIMAL(38) NULL,
    [DL_SRL_NUM] DECIMAL(38) NULL,
    [DL_SUCCR_NAME] VARCHAR(200) NULL,
    [DL_DESIG] VARCHAR(200) NULL,
    [DL_PERIOD] VARCHAR(200) NULL,
    [DL_APP_ID] VARCHAR(30) NULL,
    [DL_APP_NUM] DECIMAL(38) NULL,
    [DL_DATE] DATETIME2(3) NULL
);



-- Table: DD_ASPIRATIONVALUES
CREATE TABLE [DD_ASPIRATIONVALUES] (
    [DD_VALUEID] DECIMAL(38) NOT NULL,
    [DD_VALUEDESC] VARCHAR(250) NOT NULL,
    CONSTRAINT [PK_DD_ASPIRATIONVALUES] PRIMARY KEY ([DD_VALUEID])
);



-- Table: DD_BELLEXCLUDE
CREATE TABLE [DD_BELLEXCLUDE] (
    [DDEX_ID] DECIMAL(38) NOT NULL,
    [DDEX_EMPSYSID] DECIMAL(38) NOT NULL,
    [DDEX_YEARID] DECIMAL(38) NOT NULL,
    [DDEX_UPDATEDBY] DECIMAL(38) NOT NULL,
    [DDEX_UPDATEDON] DATETIME2(3) NOT NULL
);



-- Table: DD_BENMAST
CREATE TABLE [DD_BENMAST] (
    [DD_USR_ID] VARCHAR(25) NOT NULL  -- User Id,
    [DD_USR_NUM] DECIMAL(38) NOT NULL  -- User Number,
    [DD_UNT_COD] CHAR(3) NULL  -- Unit Code,
    [DD_EMP_NUM] DECIMAL(38) NULL  -- Employee Number,
    [DD_FIN_YER] DATETIME2(3) NOT NULL  -- Financial Year,
    [DD_EDT_COD] CHAR(6) NOT NULL  -- Edit Code,
    [DD_BEN_AMT] DECIMAL(38) NULL  -- Benefit Amount
);



-- Table: DD_BENMASTNEW
CREATE TABLE [DD_BENMASTNEW] (
    [DD_USR_ID] VARCHAR(25) NOT NULL  -- User Id,
    [DD_USR_NUM] DECIMAL(38) NOT NULL  -- User Number,
    [DD_UNT_COD] CHAR(3) NULL  -- Unit Code,
    [DD_EMP_NUM] DECIMAL(38) NULL  -- Employee Number,
    [DD_FIN_YER] DATETIME2(3) NOT NULL  -- Financial Year,
    [DD_EDT_COD] CHAR(6) NOT NULL  -- Edit Code,
    [DD_BEN_AMT] DECIMAL(38) NULL  -- Benefit Amount
);



-- Table: DD_CAREERPLAN
CREATE TABLE [DD_CAREERPLAN] (
    [DD_PIN_NUM] DECIMAL(38) NULL,
    [DD_USR_ID] VARCHAR(25) NULL,
    [DD_VER_NUM] DECIMAL(38) NULL,
    [DD_APP_PIN] DECIMAL(38) NULL,
    [DD_APP_ID] VARCHAR(25) NULL,
    [DD_CAR_PRM] VARCHAR(20) NULL,
    [DD_CAR_POS] CHAR(1) NULL,
    [DD_COM_DV1] DECIMAL(38) NULL,
    [DD_COM_DV2] DECIMAL(38) NULL,
    [DD_COM_DV3] DECIMAL(38) NULL,
    [DD_CAR_FUN] DECIMAL(38) NULL,
    [DD_CAR_PRD] DECIMAL(38) NULL,
    [DD_CAR_BND] DECIMAL(38) NULL,
    [DD_PRP_SUC] VARCHAR(200) NULL,
    [DD_PRP_PRD] DECIMAL(38) NULL,
    [DD_CAR_STS] CHAR(1) NULL,
    [DD_CHR_PIN] DECIMAL(38) NULL,
    [DD_CHR_UID] VARCHAR(25) NULL,
    [DD_SRF_PIN] DECIMAL(38) NULL,
    [DD_SRF_UID] VARCHAR(25) NULL,
    [DD_CAR_ML1] VARCHAR(200) NULL,
    [DD_CAR_ML2] VARCHAR(200) NULL,
    [DD_CAR_ML3] VARCHAR(200) NULL,
    [DD_CAR_ML4] VARCHAR(200) NULL,
    [DD_CAR_ML5] VARCHAR(200) NULL,
    [DD_CAR_ML6] VARCHAR(200) NULL,
    [DD_OWN_ASP] CHAR(1) NULL,
    [DD_BND_REM] VARCHAR(500) NULL,
    [DD_PRO_REM] VARCHAR(500) NULL,
    [DD_SUS_NAM] VARCHAR(60) NULL,
    [DD_SUS_PRD] DECIMAL(38) NULL,
    [DD_CAR_FN1] DECIMAL(38) NULL,
    [DD_CRT_DAT] DATETIME2(3) NULL
);



-- Table: DD_CAREERREP
CREATE TABLE [DD_CAREERREP] (
    [DD_CRT_ID] DECIMAL(38) NULL,
    [DD_USR_ID] VARCHAR(25) NULL,
    [DD_PIN_NUM] DECIMAL(38) NULL,
    [EMP_NAM] VARCHAR(200) NULL,
    [DD_BND_DSC] CHAR(3) NULL,
    [GR_GRP_NAM] VARCHAR(100) NULL,
    [SC_COM_NAM] VARCHAR(65) NULL,
    [DD_CRP_STS] CHAR(1) NULL,
    [DD_STS_DSC] VARCHAR(100) NULL,
    [DD_RVR_GRP] VARCHAR(10) NULL,
    [DD_COM_COD] VARCHAR(3) NULL,
    [DD_GRD_COD] VARCHAR(3) NULL
);



-- Table: DD_CMPARNET
CREATE TABLE [DD_CMPARNET] (
    [DD_OLD] VARCHAR(20) NULL,
    [PARENTCOMP] VARCHAR(100) NULL,
    [OLDNAME] VARCHAR(100) NULL,
    [OLDID] DECIMAL(38) NULL,
    [NEWID] DECIMAL(38) NULL
);



-- Table: DD_COMPARENTMAST
CREATE TABLE [DD_COMPARENTMAST] (
    [CM_PARENTID] DECIMAL(38) NOT NULL,
    [CM_PARENTNAME] VARCHAR(100) NOT NULL
);



-- Table: DD_COMPGROUP
CREATE TABLE [DD_COMPGROUP] (
    [CM_GROUPID] DECIMAL(38) NOT NULL,
    [CM_GROUPNAME] VARCHAR(4000) NOT NULL
);



-- Table: DD_COMWEIGHTAGE
CREATE TABLE [DD_COMWEIGHTAGE] (
    [COMP_GRADEID] DECIMAL(38) NOT NULL,
    [COMP_TYPE] VARCHAR(10) NOT NULL,
    [COMP_WEIGHTAGE] DECIMAL(38) NOT NULL
);



-- Table: DD_CPAPPR_REM
CREATE TABLE [DD_CPAPPR_REM] (
    [GL_REQ_NO] DECIMAL(38) NULL,
    [GL_SNO] DECIMAL(38) NULL,
    [GL_USR_COD] VARCHAR(200) NULL,
    [GL_PIN_NUM] DECIMAL(38) NULL,
    [GL_REM] VARCHAR(4000) NULL,
    [GL_APPRAISEE_DISCUSSION] VARCHAR(4000) NULL,
    [GL_APPRAISEE_CONCERN] VARCHAR(4000) NULL,
    [GL_WHATWENTWELL] VARCHAR(4000) NULL
);



-- Table: DD_CPRESEND_REM
CREATE TABLE [DD_CPRESEND_REM] (
    [GL_REQ_NO] DECIMAL(38) NULL,
    [GL_APPR_PIN_NUM] DECIMAL(38) NULL,
    [GL_SUPAPPR_PIN_NUM] DECIMAL(38) NULL,
    [GL_RESEND_REM] VARCHAR(4000) NULL,
    [RESEND_DATE] DATETIME2(3) NULL
);



-- Table: DD_CPWEIGHTAGE
CREATE TABLE [DD_CPWEIGHTAGE] (
    [CP_CATEGORY] VARCHAR(50) NOT NULL,
    [CP_GRADEID] DECIMAL(38) NOT NULL,
    [CP_WEIGHTAGE] DECIMAL(38) NOT NULL,
    [CP_APPLICABLE] CHAR(1) NULL
);



-- Table: DD_DEADLINEEXTEND
CREATE TABLE [DD_DEADLINEEXTEND] (
    [DD_YEARID] DECIMAL(38) NOT NULL,
    [DD_APPSYSID] DECIMAL(38) NOT NULL,
    [DD_EXTTYPE] CHAR(1) NOT NULL  -- R- Resend ;  E - Extend Form,
    [DD_MODULE] VARCHAR(2) NOT NULL,
    [DD_APRSYSID] DECIMAL(38) NULL,
    [DD_CLS_DAT] DATETIME2(3) NULL,
    [DD_RESENDREMARKS] VARCHAR(500) NULL,
    [DD_CREATEDON] DATETIME2(3) NULL
);



-- Table: DD_DEADLINEUSERS
CREATE TABLE [DD_DEADLINEUSERS] (
    [DL_USER_ID] VARCHAR(25) NULL,
    [DL_PIN_NUM] DECIMAL(38) NULL,
    [DL_CLS_DAT] DATETIME2(3) NULL
);



-- Table: DD_DISTRIBUTION_BUDGET
CREATE TABLE [DD_DISTRIBUTION_BUDGET] (
    [BUD_FINYEARID] DECIMAL(38) NOT NULL,
    [BUD_RATINGGROUP] CHAR(7) NOT NULL,
    [BUD_VTC_DISTRBPERCENT] DECIMAL(38) NOT NULL
);



-- Table: DD_EMAIL_LIST
CREATE TABLE [DD_EMAIL_LIST] (
    [DD_TRN_NUM] DECIMAL(38) NULL  -- REFERENCE ID,
    [DD_APP_ID] VARCHAR(65) NULL  -- APPRAISEE ID,
    [DD_APR_ID] VARCHAR(65) NULL  -- APPRAISER ID,
    [DD_TRN_DAT] DATETIME2(3) NULL  -- SYSDATE(CURRENT DATE),
    [DD_STS_FLG] VARCHAR(10) NULL  -- FLAG
);



-- Table: DD_EMPGRADE
CREATE TABLE [DD_EMPGRADE] (
    [EM_COM_COD] CHAR(3) NOT NULL  -- Company Code,
    [EM_GRD_COD] CHAR(3) NOT NULL  -- Grade Code,
    [EM_GRD_NAM] CHAR(25) NULL  -- Grade Name,
    [EM_GRD_TYP] CHAR(3) NULL  -- Grade Type,
    [EM_MAN_COD] VARCHAR(3) NULL  -- Manager Code,
    [EM_BUS_COD] CHAR(9) NULL  -- Business Code
);



-- Table: DD_EMPMAST
CREATE TABLE [DD_EMPMAST] (
    [EM_PIN_NUM] DECIMAL(38) NULL  -- Pin Number,
    [EM_USR_ID] VARCHAR(65) NULL  -- Sparsh Id,
    [EM_TRM_FLG] CHAR(1) NULL  -- BLT / CLT,
    [EM_CEO_ID] DECIMAL(38) NULL  -- CEO Id,
    [EM_EFF_DAT] DATETIME2(3) NULL  -- Effective Date,
    [EM_CLS_DAT] DATETIME2(3) NULL  -- Closure Date,
    [EM_SAL_TYPE] VARCHAR(3) NULL,
    [EM_MODI_BY] DECIMAL(38) NULL,
    [EM_MODI_ON] DATETIME2(3) NULL,
    [EM_FIN_YEAR] DECIMAL(38) NULL,
    [EM_CEO_ID2] DECIMAL(38) NULL,
    [EM_CEO_IDAPPON] DATETIME2(3) NULL  -- CEO 1 Approved On,
    [EM_CEO_IDAPPSTATUS] CHAR(1) NULL  -- CEO 1 Approved Status -- Y Approved,
    [EM_CEO_ID2APPON] DATETIME2(3) NULL  -- CEO 2 Approved On,
    [EM_CEO_ID2APPSTATUS] CHAR(1) NULL  -- CEO 2 Approved Status -- Y Approved
);



-- Table: DD_FINYEAR
CREATE TABLE [DD_FINYEAR] (
    [AC_SRL_NUM] DECIMAL(38) NOT NULL  -- Serial Number,
    [AC_STR_DAT] DATETIME2(3) NOT NULL  -- Start Date,
    [AC_END_DAT] DATETIME2(3) NOT NULL  -- End Date,
    [AC_ACT_FLG] VARCHAR(1) NOT NULL  -- ACTIVE FLAG FOR THE FINANCIAL YEAR,
    [AC_YEAR] VARCHAR(7) NOT NULL,
    [AC_INCYEAR] DECIMAL(38) NULL,
    [AC_PROCESS_FLG] VARCHAR(1) NULL  -- N - Pending  
R - Rating Parameter Changed / Revised 
A - Approved Increment processed data                
P - Revision changes processed 
C - Confirmed to Payroll,
    [AC_PROCESSED_BY] DECIMAL(38) NULL,
    [AC_PROCESSED_ON] DATETIME2(3) NULL,
    [AC_APPROVED_BY] DECIMAL(38) NULL,
    [AC_APPROVED_ON] DATETIME2(3) NULL,
    [AC_OPENDATE] DATETIME2(3) NULL  -- DD Form open date,
    [AC_BHRVTCDATE] DATETIME2(3) NULL,
    [AC_CP_FLG] CHAR(1) NULL
);



-- Table: DD_FINYEAR_DUE
CREATE TABLE [DD_FINYEAR_DUE] (
    [YEAR_ID] DECIMAL(38) NOT NULL,
    [BUSINESS_ID] DECIMAL(38) NOT NULL,
    [APP_LASTDATE] DATETIME2(3) NULL,
    [APR_LASTDATE] DATETIME2(3) NULL,
    [BHR_LASTDATE] DATETIME2(3) NULL
);



-- Table: DD_FUNCTIONALGROUP
CREATE TABLE [DD_FUNCTIONALGROUP] (
    [DD_FUN_ID] DECIMAL(38) NULL  -- Functional Id,
    [DD_FUN_DSC] VARCHAR(65) NULL  -- Functional Description
);



-- Table: DD_HPISSUE
CREATE TABLE [DD_HPISSUE] (
    [LOGINSYSID] DECIMAL(38) NULL,
    [DDREQUESTNO] DECIMAL(38) NULL,
    [APRTYPE] VARCHAR(5) NULL,
    [EMPSYSID] DECIMAL(38) NULL,
    [CREATEDON] DATETIME2(3) NULL
);



-- Table: DD_INPUTSMAST
CREATE TABLE [DD_INPUTSMAST] (
    [DD_INS_NUM] DECIMAL(38) NOT NULL  -- SERIAL NUMBER,
    [DD_INS_NAM] VARCHAR(500) NOT NULL  -- INPUTS FROM SOURCE  (NAME OF INPUTS),
    [DD_EFF_DAT] DATETIME2(3) NOT NULL  -- EFFECTIVE DATE,
    [DD_CLS_DAT] DATETIME2(3) NULL  -- CLOSURE DATE,
    [DD_REM_MRK] VARCHAR(200) NULL  -- REMARKS
);



-- Table: DD_JOBROTATION
CREATE TABLE [DD_JOBROTATION] (
    [JR_REQ_NUM] DECIMAL(38) NOT NULL  -- Request Number,
    [JR_SRL_NUM] DECIMAL(38) NOT NULL  -- Serial Number,
    [JR_USR_COD] VARCHAR(50) NULL  -- User Code,
    [JR_JOB_POS] VARCHAR(100) NULL  -- Job Position,
    [JR_JOB_FUN] VARCHAR(100) NULL  -- Job Functionality,
    [JR_FRM_TIM] VARCHAR(50) NULL  -- From Time,
    [JR_TO_TIM] VARCHAR(50) NULL  -- To Time,
    [JR_JOB_LOC] VARCHAR(50) NULL  -- Job Location,
    [JR_EMP_PIN] DECIMAL(38) NULL  -- Employee Pin Number,
    [JR_FLX_COL1] DECIMAL(38) NULL  -- Flexi Column 1,
    [JR_CAN_REM] VARCHAR(4000) NULL  -- Cancel Remark,
    [JR_CAN_STS] CHAR(1) NULL  -- Cancel Status,
    [JR_FLX_COL4] DATETIME2(3) NULL  -- Flexi Column 2,
    CONSTRAINT [PK_DD_JOBROTATION] PRIMARY KEY ([JR_REQ_NUM])
);



-- Table: DD_MIDREMINDER
CREATE TABLE [DD_MIDREMINDER] (
    [DD_USR_ID] VARCHAR(65) NULL,
    [DD_USR_NAM] VARCHAR(200) NULL,
    [DD_USR_EML] VARCHAR(100) NULL,
    [DD_APP_ID] VARCHAR(65) NULL,
    [DD_APP_NAM] VARCHAR(200) NULL,
    [DD_REQ_DAT] DATETIME2(3) NULL,
    [DD_APP_STS] CHAR(1) NULL,
    [DD_REF_ID] DECIMAL(38) NULL,
    [DD_REQ_NUM] DECIMAL(38) NULL,
    [DD_APR_EML] VARCHAR(100) NULL,
    [DD_LST_REM] DATETIME2(3) NULL,
    [DD_MAL_FLG] VARCHAR(6) NULL,
    [EMP_ID] VARCHAR(200) NULL  -- User ID,
    [EMP_PINO] DECIMAL(38) NULL  -- Userno
);



-- Table: DD_MIDREVIEWAPR
CREATE TABLE [DD_MIDREVIEWAPR] (
    [MIDCOM_APRID] DECIMAL(38) NOT NULL  -- Mid Year Appraiser ID,
    [MIDCOM_REVIEWID] DECIMAL(38) NOT NULL  -- Mid Year Review ID,
    [MIDCOM_REVTYPE] CHAR(3) NOT NULL  -- Type (SLF/APR/REV),
    [MIDCOM_REVON] DATETIME2(3) NOT NULL  -- Review On,
    [MIDCOM_REVBY] DECIMAL(38) NOT NULL  -- Review By,
    [MIDCOM_STATUS] CHAR(1) NOT NULL  -- F - Pending for Feedback Acceptance; Y - Completed ; V - Resend by Reviewer ; R - Resend by Appraiser,
    [MIDCOM_RESENDREM] VARCHAR(2000) NULL  -- Resend Remarks
);



-- Table: DD_MIDREVIEWCOMP
CREATE TABLE [DD_MIDREVIEWCOMP] (
    [MIDCOMP_ID] DECIMAL(38) NOT NULL  -- Mid Year Review Detail ID,
    [MIDCOMP_REVIEWID] DECIMAL(38) NOT NULL  -- Mid Year Review ID,
    [MIDCOMP_REVTYPE] CHAR(3) NOT NULL  -- Type (SLF/APR/REV ) SLF - Self Appraisal,
    [MIDCOMP_REVBY] DECIMAL(38) NOT NULL  -- Feedback By,
    [MIDCOMP_COMPNO] DECIMAL(38) NOT NULL  -- Competency No,
    [MIDCOMP_REMARKS] VARCHAR(2000) NULL  -- Competency Remarks,
    [MIDCOMP_RATING] DECIMAL(38) NULL  -- Competency Rating,
    [MIDCOMP_DEVNEED] VARCHAR(2000) NULL  -- Developmental Need,
    [MIDCOMP_POSIND] VARCHAR(2000) NULL  -- Competency Positive Indicators,
    [MIDCOMP_NEGIND] VARCHAR(2000) NULL  -- Competency Negative Indicators,
    [MIDCOMP_AGREEFLAG] CHAR(1) NULL
);



-- Table: DD_MIDREVIEWCOMPBAK
CREATE TABLE [DD_MIDREVIEWCOMPBAK] (
    [MIDCOMP_ID] DECIMAL(38) NOT NULL,
    [MIDCOMP_REVIEWID] DECIMAL(38) NOT NULL,
    [MIDCOMP_REVTYPE] CHAR(3) NOT NULL,
    [MIDCOMP_REVBY] DECIMAL(38) NOT NULL,
    [MIDCOMP_COMPNO] DECIMAL(38) NOT NULL,
    [MIDCOMP_REMARKS] VARCHAR(2000) NULL,
    [MIDCOMP_RATING] DECIMAL(38) NULL,
    [MIDCOMP_DEVNEED] VARCHAR(2000) NULL,
    [MIDCOMP_POSIND] VARCHAR(2000) NULL,
    [MIDCOMP_NEGIND] VARCHAR(2000) NULL,
    [MIDCOMP_AGREEFLAG] CHAR(1) NULL
);



-- Table: DD_MIDREVIEWCOMPLOG
CREATE TABLE [DD_MIDREVIEWCOMPLOG] (
    [MIDCOMP_ID] DECIMAL(38) NOT NULL,
    [MIDCOMP_REVIEWID] DECIMAL(38) NOT NULL,
    [MIDCOMP_REVTYPE] CHAR(3) NOT NULL,
    [MIDCOMP_REVBY] DECIMAL(38) NOT NULL,
    [MIDCOMP_COMPNO] DECIMAL(38) NOT NULL,
    [MIDCOMP_REMARKS] VARCHAR(2000) NULL,
    [MIDCOMP_RATING] DECIMAL(38) NULL,
    [MIDCOMP_DEVNEED] VARCHAR(2000) NULL,
    [MIDCOMP_POSIND] VARCHAR(2000) NULL,
    [MIDCOMP_NEGIND] VARCHAR(2000) NULL,
    [MIDCOMP_AGREEFLAG] CHAR(1) NULL,
    [LOG_CREATEDBY] DECIMAL(38) NOT NULL,
    [LOG_CREATEDON] DATETIME2(3) NOT NULL
);



-- Table: DD_MIDREVIEWCOMPREV
CREATE TABLE [DD_MIDREVIEWCOMPREV] (
    [MIDCOMP_REVID] DECIMAL(38) NOT NULL,
    [MIDCOMP_ID] DECIMAL(38) NOT NULL  -- Mid Year Review Detail ID,
    [MIDCOMP_REVBY] DECIMAL(38) NOT NULL  -- Feedback By,
    [MIDCOMP_REMARKS] VARCHAR(2000) NULL  -- Competency Remarks,
    [MIDCOMP_RATING] DECIMAL(38) NULL  -- Competency Rating,
    [MIDCOMP_DEVNEED] VARCHAR(2000) NULL  -- Developmental Need,
    [MIDCOMP_AGREEFLAG] CHAR(1) NULL
);



-- Table: DD_MIDREVIEWCOMPREVLOG
CREATE TABLE [DD_MIDREVIEWCOMPREVLOG] (
    [MIDCOMP_REVID] DECIMAL(38) NOT NULL,
    [MIDCOMP_ID] DECIMAL(38) NOT NULL,
    [MIDCOMP_REVBY] DECIMAL(38) NOT NULL,
    [MIDCOMP_REMARKS] VARCHAR(2000) NULL,
    [MIDCOMP_RATING] DECIMAL(38) NULL,
    [MIDCOMP_DEVNEED] VARCHAR(2000) NULL,
    [MIDCOMP_AGREEFLAG] CHAR(1) NULL,
    [LOG_CREATEDBY] DECIMAL(38) NULL,
    [LOG_CREATEDON] DATETIME2(3) NULL
);



-- Table: DD_MIDREVIEWCP
CREATE TABLE [DD_MIDREVIEWCP] (
    [MIDCP_ID] DECIMAL(38) NOT NULL  -- Mid Year Review Detail ID,
    [MIDCP_REVIEWID] DECIMAL(38) NOT NULL  -- Mid Year Review ID,
    [MIDCP_DESC] VARCHAR(4000) NOT NULL  -- Description,
    [MIDCP_TYPE] VARCHAR(100) NOT NULL,
    [MIDCP_UOM] VARCHAR(65) NOT NULL  -- Unit of Measurement,
    [MIDCP_FRO] VARCHAR(50) NOT NULL  -- From,
    [MIDCP_TO] VARCHAR(50) NOT NULL  -- To,
    [MIDCP_STATUS] CHAR(1) NOT NULL  -- Control Point  Status Active , Dropped, Modified, New Addition,
    [MIDCP_ACHSTATUS] VARCHAR(1000) NULL  -- Achievement Status,
    [MIDCP_MILESTONE] VARCHAR(4000) NULL  -- Milestone,
    [MIDCP_JUSTIFICATION] VARCHAR(4000) NULL  -- Justification,
    [MIDCP_ASSWEIGHTAGE] DECIMAL(38) NULL,
    [MIDCP_MODIFIEDON] DATETIME2(3) NULL,
    [MIDCP_SOURCE] VARCHAR(9) NULL,
    [MIDCP_REFID] DECIMAL(38) NULL,
    CONSTRAINT [PK_DD_MIDREVIEWCP] PRIMARY KEY ([MIDCP_ID])
);



-- Table: DD_MIDREVIEWCPAPR
CREATE TABLE [DD_MIDREVIEWCPAPR] (
    [MIDCP_APRID] DECIMAL(38) NOT NULL  -- Mid Year Review Appraiser Comments ID,
    [MIDCP_ID] DECIMAL(38) NOT NULL  -- Mid Year Review ID,
    [MIDCP_APREMPSYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [MIDCP_COMMENTS] VARCHAR(4000) NULL  -- Comments by Appraiser or Reviewer,
    [MIDCP_AGREEFLAG] CHAR(1) NULL
);



-- Table: DD_MIDREVIEWCPAPRLOG
CREATE TABLE [DD_MIDREVIEWCPAPRLOG] (
    [MIDCP_APRID] DECIMAL(38) NOT NULL,
    [MIDCP_ID] DECIMAL(38) NOT NULL,
    [MIDCP_APREMPSYSID] DECIMAL(38) NOT NULL,
    [MIDCP_COMMENTS] VARCHAR(4000) NULL,
    [MIDCP_AGREEFLAG] CHAR(1) NULL,
    [LOG_CREATEDBY] DECIMAL(38) NOT NULL,
    [LOG_CREATEDON] DATETIME2(3) NOT NULL
);



-- Table: DD_MIDREVIEWCPBK
CREATE TABLE [DD_MIDREVIEWCPBK] (
    [MIDCP_ID] DECIMAL(38) NOT NULL,
    [MIDCP_REVIEWID] DECIMAL(38) NOT NULL,
    [MIDCP_DESC] VARCHAR(4000) NOT NULL,
    [MIDCP_TYPE] VARCHAR(100) NOT NULL,
    [MIDCP_UOM] VARCHAR(65) NOT NULL,
    [MIDCP_FRO] VARCHAR(50) NOT NULL,
    [MIDCP_TO] VARCHAR(50) NOT NULL,
    [MIDCP_STATUS] CHAR(1) NOT NULL,
    [MIDCP_ACHSTATUS] VARCHAR(1000) NULL,
    [MIDCP_MILESTONE] VARCHAR(4000) NULL,
    [MIDCP_JUSTIFICATION] VARCHAR(4000) NULL,
    [MIDCP_ASSWEIGHTAGE] DECIMAL(38) NULL,
    [MIDCP_MODIFIEDON] DATETIME2(3) NULL,
    [MIDCP_SOURCE] VARCHAR(5) NULL,
    [MIDCP_REFID] DECIMAL(38) NULL
);



-- Table: DD_MIDREVIEWCPLOG
CREATE TABLE [DD_MIDREVIEWCPLOG] (
    [MIDCP_ID] DECIMAL(38) NOT NULL,
    [MIDCP_REVIEWID] DECIMAL(38) NOT NULL,
    [MIDCP_DESC] VARCHAR(4000) NOT NULL,
    [MIDCP_TYPE] VARCHAR(100) NOT NULL,
    [MIDCP_UOM] VARCHAR(65) NOT NULL,
    [MIDCP_FRO] VARCHAR(50) NOT NULL,
    [MIDCP_TO] VARCHAR(50) NOT NULL,
    [MIDCP_STATUS] CHAR(1) NOT NULL,
    [MIDCP_ACHSTATUS] VARCHAR(1000) NULL,
    [MIDCP_MILESTONE] VARCHAR(4000) NULL,
    [MIDCP_JUSTIFICATION] VARCHAR(4000) NULL,
    [MIDCP_ASSWEIGHTAGE] DECIMAL(38) NULL,
    [MIDCP_MODIFIEDON] DATETIME2(3) NULL,
    [MIDCP_SOURCE] VARCHAR(9) NULL,
    [MIDCP_REFID] DECIMAL(38) NULL,
    [LOG_CREATEDON] DATETIME2(3) NOT NULL,
    [LOG_CREATEDBY] DECIMAL(38) NOT NULL
);



-- Table: DD_MIDREVIEWCPREV
CREATE TABLE [DD_MIDREVIEWCPREV] (
    [MIDCP_REVID] DECIMAL(38) NOT NULL,
    [MIDCP_APRID] DECIMAL(38) NOT NULL  -- Mid Year Review ID,
    [MIDCP_REVEMPSYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [MIDCP_COMMENTS] VARCHAR(4000) NULL  -- Comments by Reviewer,
    [MIDCP_AGREEFLAG] CHAR(1) NULL
);



-- Table: DD_MIDREVIEWCPREVLOG
CREATE TABLE [DD_MIDREVIEWCPREVLOG] (
    [MIDCP_REVID] DECIMAL(38) NOT NULL,
    [MIDCP_APRID] DECIMAL(38) NOT NULL  -- Mid Year Review ID,
    [MIDCP_REVEMPSYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [MIDCP_COMMENTS] VARCHAR(4000) NULL  -- Comments by Reviewer,
    [MIDCP_AGREEFLAG] CHAR(1) NULL,
    [LOG_CREATEDBY] DECIMAL(38) NULL,
    [LOG_CREATEDON] DATETIME2(3) NULL
);



-- Table: DD_MIDREVIEWMAIN
CREATE TABLE [DD_MIDREVIEWMAIN] (
    [MID_REVIEWID] DECIMAL(38) NOT NULL  -- Mid Year Review ID,
    [MID_EMPSYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [MID_DDYEAR] DECIMAL(38) NOT NULL  -- DD Year,
    [MID_STATUS] CHAR(1) NOT NULL  -- P - Pending with Appraisee; A - Pending with Appraiser ; R - Pending with Reviewer; Y - Completed,
    [MID_RESENDBY] DECIMAL(38) NULL  -- Last Resent By,
    [MID_RESENDREM] VARCHAR(500) NULL  -- Last Resent Remarks,
    [MID_SOURCE] CHAR(3) NOT NULL  -- Source - PRB/DD/,
    [MID_SOURCEREFNO] DECIMAL(38) NULL  -- DD Request No,
    [MID_LASTMODBY] DECIMAL(38) NOT NULL  -- Last Modified By,
    [MID_LASTMODON] DATETIME2(3) NOT NULL  -- Last Modified On,
    [MID_FORMTYPE] CHAR(3) NULL,
    [MID_SUBORDINATE] CHAR(1) NULL,
    [MID_APPCOMMENTS] VARCHAR(500) NULL,
    CONSTRAINT [PK_DD_MIDREVIEWMAIN] PRIMARY KEY ([MID_REVIEWID])
);



-- Table: DD_MIDREVQTN10
CREATE TABLE [DD_MIDREVQTN10] (
    [MR_REQ_NUM] DECIMAL(38) NOT NULL  -- REQUEST NUMBER,
    [MR_QTN_NUM] DECIMAL(38) NOT NULL  -- QUESTION NUMBER,
    [MR_SRL_NUM] DECIMAL(38) NOT NULL  -- ANSWER SERIAL NUMBER,
    [MR_SUBSRL_NUM] DECIMAL(38) NOT NULL  -- ANSWER SUB SERIAL NUMBER,
    [MR_ANS_NAM] VARCHAR(4000) NULL  -- ANSWER FOR THE QUESTION,
    [MR_MOD_DAT] DATETIME2(3) NULL  -- MODIFIED DATE
);



-- Table: DD_MODULE
CREATE TABLE [DD_MODULE] (
    [DD_MOD_COD] DECIMAL(38) NOT NULL  -- Module Code,
    [DD_MOD_DSC] VARCHAR(30) NULL  -- Module Description,
    CONSTRAINT [PK_DD_MODULE] PRIMARY KEY ([DD_MOD_COD])
);



-- Table: DD_PERK
CREATE TABLE [DD_PERK] (
    [DD_BND_ID] DECIMAL(38) NOT NULL  -- Band Id,
    [DD_EFF_DAT] DATETIME2(3) NOT NULL  -- Effective Date,
    [DD_CLS_DAT] DATETIME2(3) NULL  -- Closure Date,
    [DD_ED_COD] CHAR(9) NOT NULL  -- Earnings Deduction Code,
    [DD_PAY_TYP] CHAR(1) NULL  -- Pay Type,
    [DD_PAY_AMT] DECIMAL(38) NULL  -- Pay Amount,
    [DD_ED_NAM] VARCHAR(65) NULL  -- Earnings Deduction Description,
    [DD_BNDNAME] VARCHAR(10) NULL,
    CONSTRAINT [PK_DD_PERK] PRIMARY KEY ([DD_BND_ID])
);



-- Table: DD_PERKMAST
CREATE TABLE [DD_PERKMAST] (
    [PK_ED_COD] CHAR(9) NULL  -- Earnings Deduction Code,
    [PK_ED_NAM] VARCHAR(65) NULL  -- Earnings Deduction Description,
    [PK_SRT_NUM] DECIMAL(38) NULL  -- Sort Number
);



-- Table: DD_PREVCASHAWARD
CREATE TABLE [DD_PREVCASHAWARD] (
    [CS_USR_ID] VARCHAR(25) NOT NULL  -- User Id,
    [CS_USR_NUM] DECIMAL(38) NOT NULL  -- User Number,
    [CS_FIN_FRO] DATETIME2(3) NULL  -- Financial Year From,
    [CS_FIN_TO] DATETIME2(3) NOT NULL  -- Financial Year To,
    [CS_LVL_TYP] VARCHAR(25) NULL  -- Level Type,
    [CS_CSH_AMT] DECIMAL(38) NULL  -- Cash Amount
);



-- Table: DD_PROBAPPR08
CREATE TABLE [DD_PROBAPPR08] (
    [AP_REQ_NUM] DECIMAL(38) NULL,
    [AP_QTN_NUM] DECIMAL(38) NULL,
    [AP_ANS_NAM] VARCHAR(4000) NULL,
    [AP_MOD_DAT] DATETIME2(3) NULL,
    [AP_USR_COD] VARCHAR(200) NULL,
    [AP_PIN_NUM] DECIMAL(38) NULL,
    [AP_REM] VARCHAR(10) NULL
);



-- Table: DD_PROBFEEDBACK
CREATE TABLE [DD_PROBFEEDBACK] (
    [PR_USR_ID] VARCHAR(50) NULL  -- Probationers userid,
    [PR_PIN_NUM] DECIMAL(38) NULL  -- Probationers  pinnum,
    [PR_QTN_NUM] DECIMAL(38) NULL  -- question number,
    [PR_ANS_NAM] VARCHAR(4000) NULL  -- Answer,
    [PR_APP_ID] VARCHAR(50) NULL  -- Approvers userid,
    [PR_APP_NUM] DECIMAL(38) NULL  -- Approvers pinnum,
    [PR_STS_FLG] CHAR(1) NULL  -- Status flag,
    [PR_APP_DAT] DATETIME2(3) NULL  -- Filled in date,
    [PR_MOD_DAT] DATETIME2(3) NULL  -- Modified date
);



-- Table: DD_PROBFEEDBACK08
CREATE TABLE [DD_PROBFEEDBACK08] (
    [PR_USR_ID] VARCHAR(50) NULL  -- Probationers userid,
    [PR_PIN_NUM] DECIMAL(38) NULL  -- Probationers  pinnum,
    [PR_QTN_NUM] DECIMAL(38) NULL  -- question number,
    [PR_ANS_NAM] VARCHAR(4000) NULL  -- Answer,
    [PR_APP_ID] VARCHAR(50) NULL  -- Approvers userid,
    [PR_APP_NUM] DECIMAL(38) NULL  -- Approvers pinnum,
    [PR_STS_FLG] CHAR(1) NULL  -- Status flag,
    [PR_APP_DAT] DATETIME2(3) NULL  -- Filled in date,
    [PR_MOD_DAT] DATETIME2(3) NULL  -- Modified date
);



-- Table: DD_PROBMAIN
CREATE TABLE [DD_PROBMAIN] (
    [AP_REQ_NUM] DECIMAL(38) NOT NULL  -- REQUEST NUMBER GENERATED FROM SRFSPARSH. REQUEST_MAIN,
    [AP_USR_COD] VARCHAR(25) NULL  -- USER CODE OF THE EMPLOYEE,
    [AP_PIN_NUM] DECIMAL(38) NULL  -- USER NO OF THE EMPLOYEE,
    [AP_ENT_DAT] DATETIME2(3) NULL  -- DD ENTRY DATE,
    [AP_REM_MRK] VARCHAR(200) NULL  -- REMARKS,
    [AP_MOD_DAT] DATETIME2(3) NULL  -- MODIFIED ON,
    [AP_MOD_REM] VARCHAR(200) NULL  -- MODIFICATION  REMARKS,
    [AP_CAN_REM] VARCHAR(200) NULL  -- SELF APPRAISAL CANCELLATION REMARKS,
    [AP_STS_COD] VARCHAR(1) NULL  -- I - INCOMPLETE; N - SUBMITTED BY PROBATIONER; A - PENDING WITH APPRAISER; S - SUBMITTED BY APPRAISER;,
    [AP_GOL_NO] DECIMAL(38) NULL  -- Goal Sheet No,
    [AP_STR_DAT] DATETIME2(3) NULL,
    [AP_END_DAT] DATETIME2(3) NULL,
    CONSTRAINT [PK_DD_PROBMAIN] PRIMARY KEY ([AP_REQ_NUM])
);



-- Table: DD_PROBMAIN08
CREATE TABLE [DD_PROBMAIN08] (
    [AP_REQ_NUM] DECIMAL(38) NULL  -- REQUEST NUMBER GENERATED FROM SRFSPARSH. REQUEST_MAIN,
    [AP_USR_COD] VARCHAR(25) NULL  -- USER CODE OF THE EMPLOYEE,
    [AP_PIN_NUM] DECIMAL(38) NULL  -- USER NO OF THE EMPLOYEE,
    [AP_ENT_DAT] DATETIME2(3) NULL  -- DD ENTRY DATE,
    [AP_REM_MRK] VARCHAR(200) NULL  -- REMARKS,
    [AP_MOD_DAT] DATETIME2(3) NULL  -- MODIFIED ON,
    [AP_MOD_REM] VARCHAR(200) NULL  -- MODIFICATION  REMARKS,
    [AP_CAN_REM] VARCHAR(200) NULL  -- SELF APPRAISAL CANCELLATION REMARKS,
    [AP_STS_COD] VARCHAR(1) NULL  -- I - INCOMPLETE; N - SUBMITTED BY PROBATIONER; A - PENDING WITH APPRAISER; S - SUBMITTED BY APPRAISER;,
    [AP_GOL_NO] DECIMAL(38) NULL  -- Goal Sheet No,
    [AP_STR_DAT] DATETIME2(3) NULL,
    [AP_END_DAT] DATETIME2(3) NULL
);



-- Table: DD_PROBMAIN08LOG
CREATE TABLE [DD_PROBMAIN08LOG] (
    [AP_REQ_NUM] DECIMAL(38) NULL,
    [AP_USR_COD] VARCHAR(25) NULL,
    [AP_PIN_NUM] DECIMAL(38) NULL,
    [AP_ENT_DAT] DATETIME2(3) NULL,
    [AP_REM_MRK] VARCHAR(200) NULL,
    [AP_MOD_DAT] DATETIME2(3) NULL,
    [AP_MOD_REM] VARCHAR(200) NULL,
    [AP_CAN_REM] VARCHAR(200) NULL,
    [AP_STS_COD] VARCHAR(1) NULL,
    [AP_GOL_NO] DECIMAL(38) NULL,
    [AP_STR_DAT] DATETIME2(3) NULL,
    [AP_END_DAT] DATETIME2(3) NULL
);



-- Table: DD_PROBREV08
CREATE TABLE [DD_PROBREV08] (
    [RV_REQ_NUM] DECIMAL(38) NULL,
    [RV_QTN_NUM] DECIMAL(38) NULL,
    [RV_ANS_NAM] VARCHAR(4000) NULL,
    [RV_MOD_DAT] DATETIME2(3) NULL,
    [RV_USR_COD] VARCHAR(200) NULL,
    [RV_PIN_NUM] DECIMAL(38) NULL,
    [RV_REM] VARCHAR(4000) NULL,
    [RV_EXTEND] VARCHAR(10) NULL
);



-- Table: DD_PROBVOICE
CREATE TABLE [DD_PROBVOICE] (
    [AV_REQ_NUM] DECIMAL(38) NOT NULL  -- REQUEST NUMBER,
    [AV_QTN_NUM] DECIMAL(38) NOT NULL  -- QUESTION NUMBER,
    [AV_ANS_SRL] DECIMAL(38) NOT NULL  -- ANSWER SERIAL NUMBER,
    [AV_ANS_NAM] VARCHAR(4000) NULL  -- ANSWER FOR THE QUESTION,
    [AV_MOD_DAT] DATETIME2(3) NULL  -- Modified  date
);



-- Table: DD_PROBVOICE08
CREATE TABLE [DD_PROBVOICE08] (
    [AV_REQ_NUM] DECIMAL(38) NOT NULL  -- REQUEST NUMBER,
    [AV_QTN_NUM] DECIMAL(38) NOT NULL  -- QUESTION NUMBER,
    [AV_ANS_NAM] VARCHAR(4000) NULL  -- ANSWER FOR THE QUESTION,
    [AV_MOD_DAT] DATETIME2(3) NULL  -- Modified  date
);



-- Table: DD_PROCESSENTRY
CREATE TABLE [DD_PROCESSENTRY] (
    [PR_ASS_SRL] DECIMAL(38) NOT NULL  -- SERIAL NO,
    [PR_QTN_NUM] DECIMAL(38) NOT NULL  -- QUESTION NO,
    [PR_ANS_SRL] DECIMAL(38) NOT NULL  -- ANSWER SERIAL NO,
    [PR_ANS_NAM] VARCHAR(4000) NULL  -- DESCRIPTION,
    [PR_CHO_QTN] VARCHAR(4000) NULL  -- CHOICE QUESTION,
    [PR_CHO_ANS1] VARCHAR(4000) NULL  -- CHOICE ANSWER 1,
    [PR_USR_COD] VARCHAR(25) NOT NULL  -- USER ID,
    [PR_REQ_NUM] DECIMAL(38) NULL  -- REQUEST NO,
    [PR_CHO_ANS2] VARCHAR(4000) NULL  -- CHOICE ANSWER 2,
    [PR_CHO_ANS3] VARCHAR(4000) NULL  -- CHOICE ANSWER3,
    [PR_CHO_ANS4] VARCHAR(4000) NULL  -- CHOICE ANSWER 4,
    [PR_CHO_ANS5] VARCHAR(4000) NULL  -- CHOICE ANSWER 5,
    [PR_MOD_DAT] DATETIME2(3) NULL  -- MODIFIED ON,
    [PR_CHO_ANS6] VARCHAR(4000) NULL  -- CHOICE ANSWER 6,
    [PR_CHO_ANS7] VARCHAR(4000) NULL  -- CHOICE ANSWER 7,
    [PR_CHO_ANS8] VARCHAR(4000) NULL  -- CHOICE ANSWER 8,
    [PR_PIN_NUM] DECIMAL(38) NULL,
    CONSTRAINT [PK_DD_PROCESSENTRY] PRIMARY KEY ([PR_ASS_SRL])
);



-- Table: DD_PROCESSENTRY_LOG
CREATE TABLE [DD_PROCESSENTRY_LOG] (
    [PR_LOG_NUM] DECIMAL(38) NOT NULL  -- LOG NO,
    [PR_LOG_DAT] DATETIME2(3) NOT NULL  -- LOG DATE,
    [PR_ANS_NAM] VARCHAR(4000) NULL  -- DESCRIPTION,
    [PR_CHO_QTN] VARCHAR(4000) NULL  -- CHOICE QUESTION1,
    [PR_CHO_ANS1] VARCHAR(4000) NULL  -- CHOICE ANSWER,
    [PR_CHO_ANS2] VARCHAR(4000) NULL  -- CHOICE ANSWER 2,
    [PR_CHO_ANS3] VARCHAR(4000) NULL  -- CHOICE ANSWER3,
    [PR_CHO_ANS4] VARCHAR(4000) NULL  -- CHOICE ANSWER 4,
    [PR_CHO_ANS5] VARCHAR(4000) NULL  -- CHOICE ANSWER 5,
    [PR_CHO_ANS6] VARCHAR(4000) NULL  -- CHOICE ANSWER 6,
    [PR_CHO_ANS7] VARCHAR(4000) NULL  -- CHOICE ANSWER 7,
    [PR_CHO_ANS8] VARCHAR(4000) NULL  -- CHOICE ANSWER 8,
    [PR_APP_SRL] DECIMAL(38) NULL  -- ANSWER SERIAL,
    [PR_REQ_NUM] DECIMAL(38) NULL,
    [PR_PIN_NUM] DECIMAL(38) NULL,
    CONSTRAINT [PK_DD_PROCESSENTRY_LOG] PRIMARY KEY ([PR_LOG_NUM])
);



-- Table: DD_PROCESSENTRY_TEMP
CREATE TABLE [DD_PROCESSENTRY_TEMP] (
    [PR_ASS_SRL] DECIMAL(38) NOT NULL,
    [PR_QTN_NUM] DECIMAL(38) NOT NULL,
    [PR_ANS_SRL] DECIMAL(38) NOT NULL,
    [PR_ANS_NAM] VARCHAR(4000) NULL,
    [PR_CHO_QTN] VARCHAR(4000) NULL,
    [PR_CHO_ANS1] VARCHAR(4000) NULL,
    [PR_USR_COD] VARCHAR(25) NOT NULL,
    [PR_REQ_NUM] DECIMAL(38) NULL,
    [PR_CHO_ANS2] VARCHAR(4000) NULL,
    [PR_CHO_ANS3] VARCHAR(4000) NULL,
    [PR_CHO_ANS4] VARCHAR(4000) NULL,
    [PR_CHO_ANS5] VARCHAR(4000) NULL,
    [PR_MOD_DAT] DATETIME2(3) NULL,
    [PR_CHO_ANS6] VARCHAR(4000) NULL,
    [PR_CHO_ANS7] VARCHAR(4000) NULL,
    [PR_CHO_ANS8] VARCHAR(4000) NULL,
    [PR_PIN_NUM] DECIMAL(38) NULL
);



-- Table: DD_PROFILEREP
CREATE TABLE [DD_PROFILEREP] (
    [DD_PRF_CRT] DECIMAL(38) NULL,
    [DD_PRF_PIN] DECIMAL(38) NULL  -- Pin Number,
    [DD_PRF_NUM] DECIMAL(38) NULL  -- Profile Number,
    [DD_PRF_NAM] VARCHAR(200) NULL  -- Profile Name,
    [DD_PRF_BUS] CHAR(9) NULL  -- Profile Business Name,
    [DD_PRF_UNT] CHAR(3) NULL  -- Profile Unit Code,
    [DD_PRF_REP] CHAR(3) NULL  -- Profile Represent Code,
    [DD_PRF_GRD] VARCHAR(25) NULL  -- Profile Code,
    [DD_PRF_CIT] VARCHAR(50) NULL  -- Profile City,
    [DD_PRF_AGE] VARCHAR(25) NULL  -- Profile Age,
    [DD_PRF_EXP] VARCHAR(25) NULL  -- Profile Experience,
    [DD_BUS_NAM] VARCHAR(50) NULL  -- Business Name,
    [DD_UNT_NAM] VARCHAR(50) NULL  -- Unit Name,
    [DD_PRF_DSG] VARCHAR(100) NULL  -- Profile Designatino,
    [DD_PRF_CON] VARCHAR(4000) NULL,
    [DD_PRF_SKL] VARCHAR(4000) NULL  -- Profile Skill Set,
    [DD_PRF_TRF] VARCHAR(4000) NULL,
    [DD_PRF_OFN] VARCHAR(4000) NULL,
    [DD_PRF_ISS] VARCHAR(4000) NULL,
    [DD_PRF_HLP] VARCHAR(4000) NULL,
    [DD_PRF_JON] VARCHAR(12) NULL,
    [DD_PRF_BAN] VARCHAR(3) NULL,
    [DD_PRF_CTC] DECIMAL(38) NULL  -- Profile CTC,
    [DD_PRF_TEX] DECIMAL(38) NULL,
    [DD_PRF_QLF] VARCHAR(70) NULL  -- Profile Qualification
);



-- Table: DD_QTNMAST
CREATE TABLE [DD_QTNMAST] (
    [DD_QTN_NUM] DECIMAL(38) NOT NULL  -- QUESTION NUMBER,
    [DD_QTN_NAM] VARCHAR(4000) NOT NULL  -- QUESTION NAME,
    [DD_QTN_RMK] VARCHAR(4000) NULL  -- QUESTION REMARKS(AUX QUESTIONS CAN BE ADDED),
    [DD_QTN_CMT] VARCHAR(4000) NULL  -- QUESTION COMMENTS,
    [DD_QTN_GRP] VARCHAR(25) NULL  -- QUESTION GROUP,
    [DD_QTN_ROW] DECIMAL(38) NULL  -- NUMBER OF ANSWER ROWS,
    [DD_QTN_TYP] VARCHAR(3) NULL  -- ANSWER TYP LIKE T- TEXT C- COMBO, RADIO -R,
    [DD_TOOL_TIP] VARCHAR(50) NULL,
    CONSTRAINT [PK_DD_QTNMAST] PRIMARY KEY ([DD_QTN_NUM])
);



-- Table: DD_QTNOPTIONAL
CREATE TABLE [DD_QTNOPTIONAL] (
    [DD_OPT_QTNNUM] DECIMAL(38) NOT NULL,
    [DD_OPT_TYPE] VARCHAR(10) NOT NULL,
    [DD_OPT_PAGENUM] DECIMAL(38) NOT NULL,
    [DD_OPT_PAGEURL] VARCHAR(200) NOT NULL,
    [DD_OPT_SORTNO] DECIMAL(38) NOT NULL,
    CONSTRAINT [PK_DD_QTNOPTIONAL] PRIMARY KEY ([DD_OPT_QTNNUM])
);



-- Table: DD_QTNOPTIONALLOG_SUB
CREATE TABLE [DD_QTNOPTIONALLOG_SUB] (
    [DD_OPT_SRLNUM] DECIMAL(38) NOT NULL,
    [DD_OPT_REQNUM] DECIMAL(38) NOT NULL,
    [DD_OPT_QTNNUM] DECIMAL(38) NOT NULL,
    [DD_OPT_MODIFIEDBY] DECIMAL(38) NOT NULL,
    [DD_OPT_MODIFIEDON] DATETIME2(3) NOT NULL,
    [LOG_CREATEDBY] DECIMAL(38) NOT NULL,
    [LOG_CREATEDON] DATETIME2(3) NOT NULL
);



-- Table: DD_QTNOPTIONAL_SUB
CREATE TABLE [DD_QTNOPTIONAL_SUB] (
    [DD_OPT_SRLNUM] DECIMAL(38) NOT NULL,
    [DD_OPT_REQNUM] DECIMAL(38) NOT NULL,
    [DD_OPT_QTNNUM] DECIMAL(38) NOT NULL,
    [DD_OPT_MODIFIEDBY] DECIMAL(38) NOT NULL,
    [DD_OPT_MODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_DD_QTNOPTIONAL_SUB] PRIMARY KEY ([DD_OPT_SRLNUM])
);



-- Table: DD_QTN_MAP
CREATE TABLE [DD_QTN_MAP] (
    [DDTYPE] VARCHAR(10) NOT NULL,
    [APRTYPE] VARCHAR(3) NOT NULL,
    [QTN_NUM] DECIMAL(38) NOT NULL,
    [ANS_SAVETYPE] VARCHAR(1) NOT NULL,
    [START_DATE] DATETIME2(3) NOT NULL,
    [END_DATE] DATETIME2(3) NULL,
    [MODIFIED_BY] DECIMAL(38) NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL
);



-- Table: DD_REQNUM_COMPE_IND
CREATE TABLE [DD_REQNUM_COMPE_IND] (
    [REQNUM] DECIMAL(38) NULL  -- Request Number,
    [COMPNUM] DECIMAL(38) NULL  -- Competency Number,
    [INDNUM] DECIMAL(38) NULL  -- Indicator Number,
    [FLAG] CHAR(1) NULL  -- Flag,
    [PINNUM] DECIMAL(38) NULL  -- Pin Number
);



-- Table: DD_REQNUM_COMPE_IND_LOG
CREATE TABLE [DD_REQNUM_COMPE_IND_LOG] (
    [REQNUM] DECIMAL(38) NULL  -- Request Number,
    [COMPNUM] DECIMAL(38) NULL  -- Competency Number,
    [INDNUM] DECIMAL(38) NULL  -- Indicator Number,
    [FLAG] CHAR(1) NULL  -- Flag,
    [PINNUM] DECIMAL(38) NULL  -- Pin Number
);



-- Table: DD_RESEND
CREATE TABLE [DD_RESEND] (
    [RESEND_REQUESTNO] DECIMAL(38) NOT NULL,
    [RESEND_APRTYPE] VARCHAR(3) NULL,
    [RESEND_BY] DECIMAL(38) NULL,
    [RESEND_TO_WHOM] DECIMAL(38) NULL,
    [RESEND_REMARKS] VARCHAR(4000) NULL,
    [RESEND_ON] DATETIME2(3) NULL,
    CONSTRAINT [PK_DD_RESEND] PRIMARY KEY ([RESEND_REQUESTNO])
);



-- Table: DD_REVIEWERGRP
CREATE TABLE [DD_REVIEWERGRP] (
    [EM_RVR_COD] CHAR(1) NULL  -- Reviewer Code,
    [EM_RVR_NAM] VARCHAR(10) NULL  -- Reviewer Group
);



-- Table: DD_REVISION
CREATE TABLE [DD_REVISION] (
    [DD_PIN_NUM] DECIMAL(38) NULL  -- Pin Number,
    [DD_CRT_PIN] DECIMAL(38) NULL  -- Apprasier Pin,
    [DD_APR_NAM] VARCHAR(150) NULL  -- Appraiser Name,
    [DD_SIG_NAM] VARCHAR(150) NULL  -- Signatory Name,
    [DD_SIG_DSG] VARCHAR(100) NULL  -- Signatory Designation,
    [DD_APR_BUS] VARCHAR(100) NULL  -- Business,
    [DD_APR_PR1] VARCHAR(600) NULL  -- Para 1,
    [DD_APR_PR2] VARCHAR(500) NULL  -- Para 2,
    [DD_APR_PR3] VARCHAR(500) NULL  -- Para 3,
    [DD_APR_PR4] VARCHAR(500) NULL  -- Para 4,
    [DD_APR_PR5] VARCHAR(500) NULL  -- Para 5,
    [DD_PRN_DAT] DATETIME2(3) NULL  -- Print Date,
    [DD_APR_SIN] VARCHAR(150) NULL,
    [DD_APR_DSG] VARCHAR(100) NULL  -- Appraised Desgination,
    [DD_APR_BND] VARCHAR(10) NULL  -- Appraised Band
);



-- Table: DD_REV_STRENGTHWEEK
CREATE TABLE [DD_REV_STRENGTHWEEK] (
    [AP_REQ_NUM] DECIMAL(38) NOT NULL,
    [AP_QTN_NUM] DECIMAL(38) NOT NULL,
    [AP_SRL_NUM] DECIMAL(38) NOT NULL,
    [AP_PIN_NUM] DECIMAL(38) NOT NULL,
    [AP_USR_COD] VARCHAR(25) NOT NULL,
    [AP_STRENGTH] VARCHAR(4000) NULL,
    [AP_IMPROVEMENT] VARCHAR(4000) NULL,
    [AP_CREATEDON] DATETIME2(3) NULL,
    [AP_MODIFIEDON] DATETIME2(3) NULL
);



-- Table: DD_SRFVALUES
CREATE TABLE [DD_SRFVALUES] (
    [DD_SRFVALUEID] DECIMAL(38) NOT NULL,
    [DD_SRFVALUEDESC] VARCHAR(250) NOT NULL,
    CONSTRAINT [PK_DD_SRFVALUES] PRIMARY KEY ([DD_SRFVALUEID])
);



-- Table: DD_SUMMARYREP
CREATE TABLE [DD_SUMMARYREP] (
    [DD_SUM_CRT] VARCHAR(25) NULL,
    [DD_SUM_PIN] DECIMAL(38) NULL,
    [DD_SUM_NUM] DECIMAL(38) NULL,
    [DD_SUM_NAM] VARCHAR(200) NULL,
    [DD_SUM_BUS] CHAR(9) NULL,
    [DD_SUM_UNT] CHAR(3) NULL,
    [DD_SUM_REP] CHAR(3) NULL,
    [DD_SUM_GRD] VARCHAR(25) NULL,
    [DD_SUM_CIT] VARCHAR(50) NULL,
    [DD_SUM_FRT] VARCHAR(2000) NULL,
    [DD_SUM_VTC] VARCHAR(5) NULL,
    [DD_SUM_PRE] VARCHAR(2000) NULL,
    [DD_SUM_CRE] VARCHAR(2000) NULL,
    [DD_SUM_AGE] VARCHAR(25) NULL,
    [DD_SUM_EXP] VARCHAR(25) NULL,
    [DD_BUS_NAM] VARCHAR(50) NULL,
    [DD_UNT_NAM] VARCHAR(50) NULL,
    [DD_SUM_DSG] VARCHAR(100) NULL,
    [DD_SUM_EML] VARCHAR(65) NULL,
    [DD_SUM_REQ] VARCHAR(20) NULL,
    [DD_SUM_DAT] VARCHAR(11) NULL,
    [DD_SUM_BAN] VARCHAR(10) NULL,
    [DD_SUM_CTC] DECIMAL(38) NULL,
    [DD_SUM_BAS] DECIMAL(38) NULL,
    [DD_SUM_QUL] VARCHAR(65) NULL,
    [DD_SUM_TEX] VARCHAR(10) NULL,
    [DD_SUM_HVA] VARCHAR(5) NULL,
    [DD_SUM_LPR] VARCHAR(11) NULL,
    [DD_SUM_LCR] VARCHAR(11) NULL,
    [DD_REQ_NUM] DECIMAL(38) NULL
);



-- Table: DD_TEMP
CREATE TABLE [DD_TEMP] (
    [D] NVARCHAR(MAX) NULL
);



-- Table: DD_VTOCOMP
CREATE TABLE [DD_VTOCOMP] (
    [VC_USR_ID] VARCHAR(25) NULL  -- User Id,
    [VC_USR_PIN] DECIMAL(38) NULL  -- User Pin Number,
    [VC_REQ_NUM] DECIMAL(38) NULL  -- Request Number,
    [VC_REQ_USR] VARCHAR(25) NULL  -- Requested User,
    [VC_REQ_PIN] DECIMAL(38) NULL  -- Requested User Pin,
    [VC_REQ_NAM] VARCHAR(150) NULL  -- Request Name,
    [VC_REQ_GRD] VARCHAR(25) NULL  -- Request Grade,
    [VC_SUG_RAT] VARCHAR(200) NULL  -- Suggested Rating,
    [VC_COM_COD] VARCHAR(4) NULL  -- Company Code,
    [VC_FIN_RAT] CHAR(4) NULL  -- Final Rating,
    [VC_FIN_PRM] CHAR(1) NULL  -- Final Promotion Flag,
    [VC_UNT_COD] CHAR(3) NULL  -- Unit Code,
    [VC_UNT_REP] CHAR(3) NULL  -- Unit Representing,
    [VC_BUS_COD] VARCHAR(50) NULL  -- Business Code,
    [VC_RAT_CHR] CHAR(4) NULL  -- CHR rating,
    [VC_RAT_BND] CHAR(20) NULL  -- Band Rating,
    [VC_BND_ID] DECIMAL(38) NULL  -- Band ID,
    [VC_EMP_NUM] DECIMAL(38) NULL  -- Employee Number,
    [VC_FIN_YER] DATETIME2(3) NULL  -- Financial Year Date,
    [VC_PRV_RAT] CHAR(4) NULL  -- Previous DD Rating,
    [NEW_PROMO_FLAG] CHAR(1) NULL  -- New Promotion Flag,
    [NEW_CASH_FLAG] CHAR(1) NULL  -- New Cash Award Flag,
    [LEV_TYP] CHAR(25) NULL  -- Level Type,
    [CASH_AMT] DECIMAL(38) NULL  -- Cash Award Amount,
    [DD_PROMO_FLAG] CHAR(1) NULL  -- DD Promotion Flag,
    [DD_CASH_FLAG] CHAR(1) NULL  -- DD Cash Flag,
    [PROMO_USER] VARCHAR(75) NULL  -- Promotion Reccommended By User Id,
    [DD_FINAL_CTC] DECIMAL(38) NULL  -- Final CTC,
    [DD_CASH_LEVEL] VARCHAR(50) NULL  -- DD Cash Level,
    [DD_CASH_REASON1] VARCHAR(4000) NULL  -- Key Achievement-Reason1,
    [DD_CASH_REASON2] VARCHAR(4000) NULL  -- Results of improvement/changes-Reason2,
    [DD_CASH_REASON3] VARCHAR(4000) NULL  -- Year/time perid-Reason3,
    [CASH_USER] VARCHAR(80) NULL  -- Cash Recommended by user id,
    [DD_EXPECT] VARCHAR(200) NULL  -- DD Expectation,
    [REV_PINUM] DECIMAL(38) NULL,
    [VC_REV_RAT] VARCHAR(200) NULL,
    [VC_APR_PROM] CHAR(1) NULL
);



-- Table: DD_VTOCOMP09
CREATE TABLE [DD_VTOCOMP09] (
    [VC_USR_ID] VARCHAR(25) NULL,
    [VC_USR_PIN] DECIMAL(38) NULL,
    [VC_REQ_NUM] DECIMAL(38) NULL,
    [VC_REQ_USR] VARCHAR(25) NULL,
    [VC_REQ_PIN] DECIMAL(38) NULL,
    [VC_REQ_NAM] VARCHAR(150) NULL,
    [VC_REQ_GRD] VARCHAR(25) NULL,
    [VC_COM_COD] VARCHAR(4) NULL,
    [VC_FIN_PRM] CHAR(1) NULL,
    [VC_UNT_COD] CHAR(3) NULL,
    [VC_UNT_REP] CHAR(3) NULL,
    [VC_BUS_COD] VARCHAR(50) NULL,
    [VC_RAT_BND] CHAR(20) NULL,
    [VC_BND_ID] DECIMAL(38) NULL,
    [VC_EMP_NUM] DECIMAL(38) NULL,
    [VC_FIN_YER] DATETIME2(3) NULL,
    [VC_PRV_RAT] CHAR(4) NULL,
    [NEW_PROMO_FLAG] CHAR(1) NULL,
    [NEW_CASH_FLAG] CHAR(1) NULL,
    [LEV_TYP] CHAR(25) NULL,
    [CASH_AMT] DECIMAL(38) NULL,
    [DD_PROMO_FLAG] CHAR(1) NULL,
    [DD_CASH_FLAG] CHAR(1) NULL,
    [PROMO_USER] VARCHAR(75) NULL,
    [VC_PER_DD] VARCHAR(200) NULL,
    [VC_COMP_DD] VARCHAR(200) NULL,
    [VC_VTC_DD] VARCHAR(200) NULL,
    [VC_PER_APPR] VARCHAR(200) NULL,
    [VC_COMP_APPR] VARCHAR(200) NULL,
    [VC_VTC_APPR] VARCHAR(200) NULL,
    [VC_PER_BLT] VARCHAR(200) NULL,
    [VC_COMP_BLT] VARCHAR(200) NULL,
    [VC_VTC_BLT] VARCHAR(200) NULL,
    [VC_PER_CLT] VARCHAR(200) NULL,
    [VC_COMP_CLT] VARCHAR(200) NULL,
    [VC_VTC_CLT] VARCHAR(200) NULL,
    [DD_FINAL_CTC] DECIMAL(38) NULL  -- DD Final CTC,
    [DD_PROM_FLG] VARCHAR(10) NULL,
    [DD_PROM_ID] DECIMAL(38) NULL,
    [REV_PINUM] DECIMAL(38) NULL,
    [CASH_AMOUNT] DECIMAL(38) NULL,
    [CASH_LEVEL] DECIMAL(38) NULL,
    [DD_CASHLEVEL] VARCHAR(100) NULL,
    [DD_REASON1] VARCHAR(4000) NULL,
    [DD_REASON2] VARCHAR(4000) NULL,
    [DD_REASON3] VARCHAR(4000) NULL,
    [DD_CASHAPPR] VARCHAR(100) NULL,
    [DD_TYPE] VARCHAR(10) NULL,
    [DD_REASON4] VARCHAR(4000) NULL,
    [VC_VTC_REVDD] VARCHAR(200) NULL,
    [VC_PROMLEVELID] DECIMAL(38) NULL,
    [VC_PROMSUBLEVELID] DECIMAL(38) NULL,
    [VC_VTC_APPR_RAT] VARCHAR(200) NULL
);



-- Table: DD_VTOCOMP09_APR
CREATE TABLE [DD_VTOCOMP09_APR] (
    [VC_USR_ID] VARCHAR(25) NULL,
    [VC_USR_PIN] DECIMAL(38) NULL,
    [VC_REQ_NUM] DECIMAL(38) NULL,
    [VC_REQ_USR] VARCHAR(25) NULL,
    [VC_REQ_PIN] DECIMAL(38) NULL,
    [VC_REQ_NAM] VARCHAR(150) NULL,
    [VC_REQ_GRD] VARCHAR(25) NULL,
    [VC_COM_COD] VARCHAR(4) NULL,
    [VC_FIN_PRM] CHAR(1) NULL,
    [VC_UNT_COD] CHAR(3) NULL,
    [VC_UNT_REP] CHAR(3) NULL,
    [VC_BUS_COD] VARCHAR(50) NULL,
    [VC_RAT_BND] CHAR(20) NULL,
    [VC_BND_ID] DECIMAL(38) NULL,
    [VC_EMP_NUM] DECIMAL(38) NULL,
    [VC_FIN_YER] DATETIME2(3) NULL,
    [NEW_PROMO_FLAG] CHAR(1) NULL,
    [DD_PROMO_FLAG] CHAR(1) NULL,
    [PROMO_USER] VARCHAR(75) NULL,
    [VC_PER_DD] VARCHAR(200) NULL,
    [VC_COMP_DD] VARCHAR(200) NULL,
    [VC_VTC_DD] VARCHAR(200) NULL,
    [VC_PER_APPR] VARCHAR(200) NULL,
    [VC_COMP_APPR] VARCHAR(200) NULL,
    [VC_VTC_APPR] VARCHAR(200) NULL,
    [DD_PROM_FLG] VARCHAR(10) NULL,
    [DD_REASON1] VARCHAR(4000) NULL,
    [DD_REASON2] VARCHAR(4000) NULL,
    [DD_REASON3] VARCHAR(4000) NULL,
    [DD_TYPE] VARCHAR(10) NULL,
    [VC_PROMLEVELID] DECIMAL(38) NULL,
    [VC_PROMSUBLEVELID] DECIMAL(38) NULL,
    [APPR_PINUM] DECIMAL(38) NULL
);



-- Table: DD_VTOCOMP_BLT
CREATE TABLE [DD_VTOCOMP_BLT] (
    [VC_USR_ID] VARCHAR(25) NULL  -- User Id,
    [VC_USR_PIN] DECIMAL(38) NULL  -- User Pin Number,
    [VC_REQ_NUM] DECIMAL(38) NULL  -- Request Number,
    [VC_REQ_USR] VARCHAR(25) NULL  -- Requested User,
    [VC_REQ_PIN] DECIMAL(38) NULL  -- Requested User Pin,
    [VC_REQ_NAM] VARCHAR(150) NULL  -- Request Name,
    [VC_REQ_GRD] VARCHAR(25) NULL  -- Request Grade,
    [VC_SUG_RAT] VARCHAR(15) NULL  -- Suggested Rating,
    [VC_COM_COD] VARCHAR(4) NULL  -- Company Code,
    [VC_FIN_RAT] CHAR(4) NULL  -- Final Rating,
    [VC_FIN_PRM] CHAR(1) NULL  -- Final Promotion Flag,
    [VC_UNT_COD] CHAR(3) NULL  -- Unit Code,
    [VC_UNT_REP] CHAR(3) NULL  -- Unit Representing,
    [VC_BUS_COD] VARCHAR(50) NULL  -- Business Code,
    [VC_RAT_CHR] CHAR(4) NULL  -- CHR rating,
    [VC_RAT_BND] CHAR(1) NULL  -- Band Rating,
    [VC_BND_ID] DECIMAL(38) NULL  -- Band ID,
    [VC_EMP_NUM] DECIMAL(38) NULL  -- Employee Number,
    [VC_FIN_YER] DATETIME2(3) NULL  -- Financial Year Date,
    [VC_PRV_RAT] CHAR(4) NULL  -- Previous DDDB.DD Rating
);



-- Table: DD_VTOCOMP_CLT
CREATE TABLE [DD_VTOCOMP_CLT] (
    [VC_USR_ID] VARCHAR(25) NULL  -- User Id,
    [VC_USR_PIN] DECIMAL(38) NULL  -- User Pin Number,
    [VC_REQ_NUM] DECIMAL(38) NULL  -- Request Number,
    [VC_REQ_USR] VARCHAR(25) NULL  -- Requested User,
    [VC_REQ_PIN] DECIMAL(38) NULL  -- Requested User Pin,
    [VC_REQ_NAM] VARCHAR(150) NULL  -- Request Name,
    [VC_REQ_GRD] VARCHAR(25) NULL  -- Request Grade,
    [VC_SUG_RAT] VARCHAR(15) NULL  -- Suggested Rating,
    [VC_COM_COD] VARCHAR(4) NULL  -- Company Code,
    [VC_FIN_RAT] CHAR(4) NULL  -- Final Rating,
    [VC_FIN_PRM] CHAR(1) NULL  -- Final Promotion Flag,
    [VC_UNT_COD] CHAR(3) NULL  -- Unit Code,
    [VC_UNT_REP] CHAR(3) NULL  -- Unit Representing,
    [VC_BUS_COD] VARCHAR(50) NULL  -- Business Code,
    [VC_RAT_CHR] CHAR(4) NULL  -- CHR rating,
    [VC_RAT_BND] CHAR(1) NULL  -- Band Rating,
    [VC_BND_ID] DECIMAL(38) NULL  -- Band ID,
    [VC_EMP_NUM] DECIMAL(38) NULL  -- Employee Number,
    [VC_FIN_YER] DATETIME2(3) NULL  -- Financial Year Date,
    [VC_PRV_RAT] CHAR(4) NULL  -- Previous DDDB.DD Rating
);



-- Table: PRODUCTIG
CREATE TABLE [PRODUCTIG] (
    [PINNO] DECIMAL(38) NOT NULL,
    [NAME] VARCHAR(60) NULL,
    [GRADE] VARCHAR(10) NULL,
    [NEWGRADE] VARCHAR(10) NULL,
    [ROLE] VARCHAR(150) NULL,
    [DESIGNATION] VARCHAR(150) NULL,
    [SYSID] DECIMAL(38) NULL,
    [POSID] DECIMAL(38) NULL,
    CONSTRAINT [PK_PRODUCTIG] PRIMARY KEY ([PINNO])
);



-- Table: CTG
CREATE TABLE [CTG] (
    [SYSID] DECIMAL(38) NULL,
    [OFFICER] VARCHAR(100) NULL,
    [APPSYSID] DECIMAL(38) NULL,
    [APPNAME] VARCHAR(100) NULL
);



-- Table: CTGDESIG
CREATE TABLE [CTGDESIG] (
    [SYSID] DECIMAL(38) NULL,
    [DESIG] VARCHAR(100) NULL,
    [LEVEL2] VARCHAR(10) NULL,
    [GRADECODE] VARCHAR(5) NULL,
    [NEWDESIG] VARCHAR(100) NULL,
    [NEWBAND] VARCHAR(10) NULL
);

-- ------------------------------------------------------------
-- Foreign Key Constraints
-- ------------------------------------------------------------
ALTER TABLE [DD_APPRAISALBREAK] ADD CONSTRAINT [FK_DD_APPRAISALBREAK_DD_USR_ID] FOREIGN KEY ([DD_USR_ID]) REFERENCES [DD_USR] ([ID]);

-- ------------------------------------------------------------
-- Indexes on Foreign Key Columns
-- ------------------------------------------------------------
CREATE INDEX [IDX_DD_APPRAISALBREAK_DD_USR_ID] ON [DD_APPRAISALBREAK]([DD_USR_ID]);
CREATE INDEX [IDX_DD_APPRAISALBREAK_DD_ED_COD] ON [DD_APPRAISALBREAK]([DD_ED_COD]);
CREATE INDEX [IDX_DD_APPRAISALBREAK_DD_APR_END] ON [DD_APPRAISALBREAK]([DD_APR_END]);
CREATE INDEX [IDX_DD_APPRAISESLFPER_AP_PER_SRL] ON [DD_APPRAISESLFPER]([AP_PER_SRL]);
CREATE INDEX [IDX_DD_APR_STRENGTHWEEK_AP_QTN_NUM] ON [DD_APR_STRENGTHWEEK]([AP_QTN_NUM]);
CREATE INDEX [IDX_DD_APR_STRENGTHWEEK_AP_SRL_NUM] ON [DD_APR_STRENGTHWEEK]([AP_SRL_NUM]);
CREATE INDEX [IDX_DD_APR_STRENGTHWEEK_AP_PIN_NUM] ON [DD_APR_STRENGTHWEEK]([AP_PIN_NUM]);
CREATE INDEX [IDX_DD_ASPIRATIONVALUES_DD_VALUEDESC] ON [DD_ASPIRATIONVALUES]([DD_VALUEDESC]);
CREATE INDEX [IDX_DD_PERK_DD_EFF_DAT] ON [DD_PERK]([DD_EFF_DAT]);
CREATE INDEX [IDX_DD_PERK_DD_ED_COD] ON [DD_PERK]([DD_ED_COD]);
CREATE INDEX [IDX_DD_QTNOPTIONAL_DD_OPT_TYPE] ON [DD_QTNOPTIONAL]([DD_OPT_TYPE]);
CREATE INDEX [IDX_DD_SRFVALUES_DD_SRFVALUEDESC] ON [DD_SRFVALUES]([DD_SRFVALUEDESC]);
CREATE INDEX [IDX_SPL_RATING_SP_SRL_NUM] ON [SPL_RATING]([SP_SRL_NUM]);
CREATE INDEX [IDX_SPL_RATING_SP_FIN_STR] ON [SPL_RATING]([SP_FIN_STR]);
CREATE INDEX [IDX_SPL_RATING_SP_FIN_END] ON [SPL_RATING]([SP_FIN_END]);
CREATE INDEX [IDX_TEC_APPLN_STS_AP_SNO] ON [TEC_APPLN_STS]([AP_SNO]);
CREATE INDEX [IDX_TEC_STC_ASSESS_SA_APPLN_NO] ON [TEC_STC_ASSESS]([SA_APPLN_NO]);
