-- ==========================================
-- Module: APPROVAL GROUP MODULE
-- Description: AP group management and approval workflows
-- Created: March 9, 2026
-- Database: SSCDB
-- ==========================================

USE SSCDB;
GO

-- ==========================================
-- APGROUP_MAST - AP Group Master
-- ==========================================
IF OBJECT_ID('[APGROUP_MAST]', 'U') IS NOT NULL DROP TABLE [APGROUP_MAST];
GO
CREATE TABLE [APGROUP_MAST] (
    [GROUP_ID] BIGINT NOT NULL,
    [GROUP_NAME] VARCHAR(50) NOT NULL,
    [GROUP_CREATEDBY] BIGINT NOT NULL,
    [GROUP_CREATEDON] DATETIME2(3) NOT NULL,
    [GROUP_MODIFIEDBY] BIGINT NULL,
    [GROUP_MODIFIEDON] DATETIME2(3) NULL,
    [GROUP_PRIORITYID] BIGINT NULL,
    CONSTRAINT [PK_APGROUP_MAST] PRIMARY KEY ([GROUP_ID])
);
GO

-- ==========================================
-- APGROUP_MAP - AP Group Mapping
-- ==========================================
IF OBJECT_ID('[APGROUP_MAP]', 'U') IS NOT NULL DROP TABLE [APGROUP_MAP];
GO
CREATE TABLE [APGROUP_MAP] (
    [MAP_ID] BIGINT NOT NULL,
    [MAP_GROUPID] BIGINT NOT NULL,
    [MAP_PAYBYSPECIFIC] INT NOT NULL,
    [MAP_BUSPECIFIC] INT NOT NULL,
    [MAP_MAINCAT] BIGINT NOT NULL,
    [MAP_SUBCAT] BIGINT NOT NULL,
    [MAP_CURRENCY] CHAR(1) NULL,
    [MAP_CREATEDBY] BIGINT NOT NULL,
    [MAP_CREATEDON] DATETIME2(3) NOT NULL,
    [MAP_MODIFIEDBY] BIGINT NULL,
    [MAP_MODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_APGROUP_MAP] PRIMARY KEY ([MAP_ID])
);
GO

-- ==========================================
-- APGROUP_UNITMAP - AP Group Unit Mapping
-- ==========================================
IF OBJECT_ID('[APGROUP_UNITMAP]', 'U') IS NOT NULL DROP TABLE [APGROUP_UNITMAP];
GO
CREATE TABLE [APGROUP_UNITMAP] (
    [MAP_ID] BIGINT NOT NULL,
    [MAP_GROUMAPID] BIGINT NOT NULL,
    [MAP_BUID] VARCHAR(25) NOT NULL,
    CONSTRAINT [PK_APGROUP_UNITMAP] PRIMARY KEY ([MAP_ID])
);
GO

-- ==========================================
-- APGROUP_PAYBY - AP Group Pay By
-- ==========================================
IF OBJECT_ID('[APGROUP_PAYBY]', 'U') IS NOT NULL DROP TABLE [APGROUP_PAYBY];
GO
CREATE TABLE [APGROUP_PAYBY] (
    [MAP_ID] BIGINT NOT NULL,
    [MAP_GROUPMAPID] BIGINT NOT NULL,
    [MAP_PAYBY] INT NOT NULL,
    CONSTRAINT [PK_APGROUP_PAYBY] PRIMARY KEY ([MAP_ID])
);
GO

-- ==========================================
-- APGROUP_MAINCATMAP - AP Group Main Category Mapping
-- ==========================================
IF OBJECT_ID('[APGROUP_MAINCATMAP]', 'U') IS NOT NULL DROP TABLE [APGROUP_MAINCATMAP];
GO
CREATE TABLE [APGROUP_MAINCATMAP] (
    [MAP_ID] BIGINT NOT NULL,
    [MAP_GROUPMAPID] BIGINT NOT NULL,
    [MAP_MAINCAT] BIGINT NOT NULL,
    CONSTRAINT [PK_APGROUP_MAINCATMAP] PRIMARY KEY ([MAP_ID])
);
GO

-- ==========================================
-- APGROUP_USERMAP - AP Group User Mapping
-- ==========================================
IF OBJECT_ID('[APGROUP_USERMAP]', 'U') IS NOT NULL DROP TABLE [APGROUP_USERMAP];
GO
CREATE TABLE [APGROUP_USERMAP] (
    [MAP_ID] BIGINT NOT NULL,
    [MAP_GROUPID] BIGINT NOT NULL,
    [MAP_USERID] BIGINT NOT NULL,
    [MAP_EFFECTIVEDATE] DATETIME2(3) NOT NULL,
    [MAP_CLOSUREDATE] DATETIME2(3) NULL,
    [MAP_CREATEDBY] BIGINT NOT NULL,
    [MAP_CREATEDON] DATETIME2(3) NOT NULL,
    [MAP_MODIFIEDBY] BIGINT NULL,
    [MAP_MODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_APGROUP_USERMAP] PRIMARY KEY ([MAP_ID]),
    CONSTRAINT [UK_APGROUP_USERMAP_MAP_GROUPID] UNIQUE ([MAP_GROUPID]),
    CONSTRAINT [UK_APGROUP_USERMAP_MAP_USERID] UNIQUE ([MAP_USERID])
);
GO

-- ==========================================
-- PULLMATRIX_DET - Pull Matrix Details
-- ==========================================
IF OBJECT_ID('[PULLMATRIX_DET]', 'U') IS NOT NULL DROP TABLE [PULLMATRIX_DET];
GO
CREATE TABLE [PULLMATRIX_DET] (
    [MAT_ID] BIGINT NOT NULL,
    [MAT_UNITID] BIGINT NOT NULL,
    [MAT_PAYBY] CHAR(2) NOT NULL,
    [MAT_FLAG] CHAR(1) NOT NULL,
    [MAT_MAINCAT] BIGINT NOT NULL,
    [MAT_EMPSYSID] BIGINT NOT NULL,
    [MAT_MAXNOS] BIGINT NOT NULL,
    [MAT_CREATEDBY] BIGINT NOT NULL,
    [MAT_CREATEDON] DATETIME2(3) NOT NULL,
    [MAT_MODIFIEDBY] BIGINT NOT NULL,
    [MAT_MODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_PULLMATRIX_DET] PRIMARY KEY ([MAT_ID])
);
GO

PRINT 'APPROVAL_GROUP_MODULE Schema created successfully.';
GO
