-- ==========================================
-- CommunityModule
-- Database: SRFSPARSHDB
-- Module Purpose: Community and User Community Management
-- Created: March 09, 2026
-- ==========================================

USE SRFSPARSHDB;
GO

-- Drop tables if they exist (reverse order for dependencies)
IF OBJECT_ID('[COMMUNITY_MEMBERS]', 'U') IS NOT NULL DROP TABLE [COMMUNITY_MEMBERS];
GO
IF OBJECT_ID('[COMMUNITY_MAST]', 'U') IS NOT NULL DROP TABLE [COMMUNITY_MAST];
GO

-- ==========================================
-- Table: COMMUNITY_MAST - Community Master
-- Description: Master table for communities/forums/groups
-- ==========================================
CREATE TABLE [COMMUNITY_MAST] (
    [COMMUNITY_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [COMMUNITY_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [COMMUNITY_NAME] VARCHAR(255) NOT NULL,
    [COMMUNITY_DESC] NVARCHAR(MAX),
    [COMMUNITY_TYPE] VARCHAR(50), -- FORUM, INTEREST_GROUP, TEAM, DEPARTMENT, etc.
    [COMMUNITY_ICON] VARCHAR(500),
    [COMMUNITY_BANNER] VARCHAR(500),
    [PRIVACY_LEVEL] VARCHAR(20) DEFAULT 'PUBLIC', -- PUBLIC, PRIVATE, RESTRICTED
    [OWNER_ID] BIGINT NOT NULL,
    [APPROVER_ID] BIGINT,
    [COMMUNITY_STATUS] VARCHAR(20) DEFAULT 'ACTIVE', -- ACTIVE, INACTIVE, ARCHIVED
    [MEMBER_COUNT] INT DEFAULT 0,
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [UPDATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3)
);
GO

-- ==========================================
-- Table: COMMUNITY_MEMBERS - Community Membership
-- Description: Tracks community member relationships and roles
-- Relationship: References COMMUNITY_MAST
-- ==========================================
CREATE TABLE [COMMUNITY_MEMBERS] (
    [MEMBER_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [COMMUNITY_ID] BIGINT NOT NULL,
    [USER_SYSID] BIGINT NOT NULL,
    [MEMBER_ROLE] VARCHAR(50) DEFAULT 'MEMBER', -- ADMIN, MODERATOR, MEMBER, GUEST
    [JOIN_DATE] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [LEAVE_DATE] DATETIME2(3),
    [MEMBER_STATUS] VARCHAR(20) DEFAULT 'ACTIVE', -- ACTIVE, INACTIVE, SUSPENDED, REMOVED
    [CONTRIBUTION_COUNT] INT DEFAULT 0,
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [UPDATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    CONSTRAINT [FK_COMMUNITY_MEMBERS_COMM] FOREIGN KEY ([COMMUNITY_ID]) REFERENCES [COMMUNITY_MAST]([COMMUNITY_ID]),
    CONSTRAINT [UC_COMMUNITY_USER] UNIQUE ([COMMUNITY_ID], [USER_SYSID])
);
GO

-- Create Indexes
CREATE INDEX [IX_COMMUNITY_MAST_CODE] ON [COMMUNITY_MAST]([COMMUNITY_CODE]);
CREATE INDEX [IX_COMMUNITY_MAST_TYPE] ON [COMMUNITY_MAST]([COMMUNITY_TYPE]);
CREATE INDEX [IX_COMMUNITY_MAST_STATUS] ON [COMMUNITY_MAST]([COMMUNITY_STATUS]);
CREATE INDEX [IX_COMMUNITY_MAST_OWNER] ON [COMMUNITY_MAST]([OWNER_ID]);
CREATE INDEX [IX_COMMUNITY_MAST_PRIVACY] ON [COMMUNITY_MAST]([PRIVACY_LEVEL]);
CREATE INDEX [IX_COMMUNITY_MEMBERS_COMMUNITY_ID] ON [COMMUNITY_MEMBERS]([COMMUNITY_ID]);
CREATE INDEX [IX_COMMUNITY_MEMBERS_USER_SYSID] ON [COMMUNITY_MEMBERS]([USER_SYSID]);
CREATE INDEX [IX_COMMUNITY_MEMBERS_ROLE] ON [COMMUNITY_MEMBERS]([MEMBER_ROLE]);
CREATE INDEX [IX_COMMUNITY_MEMBERS_STATUS] ON [COMMUNITY_MEMBERS]([MEMBER_STATUS]);
GO

PRINT 'CommunityModule_Schema created successfully.';
GO
