-- ==========================================
-- Community Module - Seed Data
-- ==========================================

USE SRFSPARSHDB;
GO

-- Seed Communities
INSERT INTO [COMMUNITY_MAST] 
([COMMUNITY_CODE], [COMMUNITY_NAME], [COMMUNITY_DESC], [COMMUNITY_TYPE], [PRIVACY_LEVEL], [OWNER_ID], [COMMUNITY_STATUS], [CREATED_BY], [CREATED_ON])
VALUES 
('COM-DEV-001', 'Developers Community', 'A community for all developers', 'INTEREST_GROUP', 'PUBLIC', 1, 'ACTIVE', 1, GETDATE()),
('COM-DES-001', 'Designers Forum', 'Share design ideas and tips', 'FORUM', 'PUBLIC', 2, 'ACTIVE', 1, GETDATE()),
('COM-QA-001', 'Quality Assurance Team', 'QA team for project coordination', 'TEAM', 'RESTRICTED', 3, 'ACTIVE', 1, GETDATE()),
('COM-HR-001', 'Human Resources', 'HR department community', 'DEPARTMENT', 'PRIVATE', 4, 'ACTIVE', 1, GETDATE()),
('COM-SALES-001', 'Sales Discussion', 'Sales team forum', 'FORUM', 'RESTRICTED', 5, 'ACTIVE', 1, GETDATE());
GO

-- Seed Community Members
INSERT INTO [COMMUNITY_MEMBERS] 
([COMMUNITY_ID], [USER_SYSID], [MEMBER_ROLE], [MEMBER_STATUS], [CREATED_BY], [CREATED_ON])
SELECT 1, 1, 'ADMIN', 'ACTIVE', 1, GETDATE()
WHERE NOT EXISTS (SELECT 1 FROM COMMUNITY_MEMBERS WHERE COMMUNITY_ID = 1 AND USER_SYSID = 1);

INSERT INTO [COMMUNITY_MEMBERS] 
([COMMUNITY_ID], [USER_SYSID], [MEMBER_ROLE], [MEMBER_STATUS], [CREATED_BY], [CREATED_ON])
SELECT 1, 2, 'MODERATOR', 'ACTIVE', 1, GETDATE()
WHERE NOT EXISTS (SELECT 1 FROM COMMUNITY_MEMBERS WHERE COMMUNITY_ID = 1 AND USER_SYSID = 2);

INSERT INTO [COMMUNITY_MEMBERS] 
([COMMUNITY_ID], [USER_SYSID], [MEMBER_ROLE], [MEMBER_STATUS], [CREATED_BY], [CREATED_ON])
SELECT 1, 3, 'MEMBER', 'ACTIVE', 1, GETDATE()
WHERE NOT EXISTS (SELECT 1 FROM COMMUNITY_MEMBERS WHERE COMMUNITY_ID = 1 AND USER_SYSID = 3);

INSERT INTO [COMMUNITY_MEMBERS] 
([COMMUNITY_ID], [USER_SYSID], [MEMBER_ROLE], [MEMBER_STATUS], [CREATED_BY], [CREATED_ON])
SELECT 2, 2, 'ADMIN', 'ACTIVE', 1, GETDATE()
WHERE NOT EXISTS (SELECT 1 FROM COMMUNITY_MEMBERS WHERE COMMUNITY_ID = 2 AND USER_SYSID = 2);

INSERT INTO [COMMUNITY_MEMBERS] 
([COMMUNITY_ID], [USER_SYSID], [MEMBER_ROLE], [MEMBER_STATUS], [CREATED_BY], [CREATED_ON])
SELECT 3, 3, 'ADMIN', 'ACTIVE', 1, GETDATE()
WHERE NOT EXISTS (SELECT 1 FROM COMMUNITY_MEMBERS WHERE COMMUNITY_ID = 3 AND USER_SYSID = 3);

INSERT INTO [COMMUNITY_MEMBERS] 
([COMMUNITY_ID], [USER_SYSID], [MEMBER_ROLE], [MEMBER_STATUS], [CREATED_BY], [CREATED_ON])
SELECT 3, 4, 'MODERATOR', 'ACTIVE', 1, GETDATE()
WHERE NOT EXISTS (SELECT 1 FROM COMMUNITY_MEMBERS WHERE COMMUNITY_ID = 3 AND USER_SYSID = 4);

GO

-- Update member counts
UPDATE c
SET c.MEMBER_COUNT = (SELECT COUNT(*) FROM COMMUNITY_MEMBERS WHERE COMMUNITY_ID = c.COMMUNITY_ID AND MEMBER_STATUS != 'REMOVED')
FROM COMMUNITY_MAST c;

GO

PRINT 'Seed data inserted successfully.';
GO

-- Verify data
SELECT 'Communities' as EntityType, COUNT(*) as Count FROM COMMUNITY_MAST
UNION ALL
SELECT 'Members', COUNT(*) FROM COMMUNITY_MEMBERS;
GO
