-- PROFILE MODULE - Schema Definition
-- Employee personal information, address, family, language proficiency

USE [Careers]
GO

/****** PERSONAL_DETAILS ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PERSONAL_DETAILS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOGIN_ID] [bigint] NULL,
	[INITIAL] [varchar](10) NULL,
	[FIRST_NAME] [varchar](50) NULL,
	[MIDDLE_NAME] [varchar](50) NULL,
	[LAST_NAM] [varchar](50) NULL,
	[DATE_OF_BIRTH] [datetime] NULL,
	[PLACE_OF_BIRTH] [varchar](50) NULL,
	[COUNTY_OF_BIRTH] [varchar](50) NULL,
	[RELIGION] [varchar](50) NULL,
	[BLOOG_GROUP] [varchar](10) NULL,
	[MARITAL_STATUS] [varchar](10) NULL,
	[DATE_OF_MARRIAGE] [datetime] NULL,
	[NO_OF_CHILDREN] [int] NULL,
	[PHONE_LANDLINE] [varchar](20) NULL,
	[PAN_NO] [varchar](20) NULL,
	[PASSPORT_NO] [varchar](20) NULL,
	[DRIVING_LICENCE_NO] [varchar](20) NULL,
	[PHOTO] [varchar](30) NULL,
	[RESUME] [varchar](30) NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** ADDRESS_TABLE ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ADDRESS_TABLE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOGIN_ID] [bigint] NULL,
	[PER_CO] [varchar](100) NULL,
	[PER_STR_HOUSE_NO] [varchar](100) NULL,
	[PER_2ND_ADDRESS_LINE] [varchar](100) NULL,
	[PER_CITY] [varchar](100) NULL,
	[PER_STATE] [varchar](50) NULL,
	[PER_PINCODE] [varchar](50) NULL,
	[TEMP_CO] [varchar](100) NULL,
	[TEMP_STR_HOUSE_NO] [varchar](100) NULL,
	[TEMP_2ND_ADDRESS_LINE] [varchar](100) NULL,
	[TEMP_CITY] [varchar](100) NULL,
	[TEMP_STATE] [varchar](50) NULL,
	[TEMP_PINCODE] [varchar](50) NULL,
	[EMERGENCY_CONTACT_NO] [varchar](20) NULL,
	[IS_SAME_AS_PERMANENT] [bit] NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** FAMILY_BACKGROUND ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FAMILY_BACKGROUND](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[SL_NO] [int] NULL,
	[RELATIONSHIP] [varchar](30) NULL,
	[NAME] [varchar](50) NULL,
	[DATE_OF_BIRTH] [datetime] NULL,
	[EDUCATION] [varchar](30) NULL,
	[EMPLOYMENT_DETAILS] [varchar](50) NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
	[ISVALID] [bit] NULL,
	[LOGIN_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** LANGUAGES_KNOWN ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LANGUAGES_KNOWN](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOGIN_ID] [bigint] NULL,
	[LANGUAGE_NO] [int] NULL,
	[LANGUAGE] [varchar](30) NULL,
	[READABLE] [bit] NULL,
	[WRITE] [bit] NULL,
	[SPEAK] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
	[ISVALID] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** PREVIOUS_ORGANISATION ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PREVIOUS_ORGANISATION](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOGIN_ID] [bigint] NULL,
	[ORGANISATION_NAME] [varchar](30) NULL,
	[PAY_SLIP] [varchar](30) NULL,
	[LAST_REVISED_CTC] [varchar](30) NULL,
	[EXPECTED_SALARY] [money] NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
	[ISFRESHER] [bit] NULL,
	[ACCEPT] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** REFERENCE_TABLE ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[REFERENCE_TABLE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOGIN_ID] [bigint] NULL,
	[REFERENCE_NO] [int] NULL,
	[NAME_ADD_DESIGNATION] [varchar](150) NULL,
	[PHONE_NO] [varchar](20) NULL,
	[EMAILID] [varchar](50) NULL,
	[RELATIONSHIP] [varchar](30) NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
