-- ==========================================
-- Module: CONFIG
-- Description: Master Data & Configuration Module
-- Database: TOURDB
-- Created: March 9, 2026
-- ==========================================

USE TOURDB;
GO

-- Table: CURRENCY_MASTER - Currency Master
CREATE TABLE [CURRENCY_MASTER] (
    [CURRENCY_ID] BIGINT NOT NULL  -- Currency ID,
    [CURRENCY_CODE] CHAR(3) NOT NULL  -- Currency Code,
    [CURRENCY_NAME] VARCHAR(65) NULL  -- CURRENCY NAME,
    [CURRENCY_SYMBOL] VARCHAR(10) NULL  -- CURRENCY SYMBOL
);

-- Table: EXPCUR_MAST - Expense Currency Master
CREATE TABLE [EXPCUR_MAST] (
    [CUR_CODE] CHAR(3) NOT NULL  -- Currency Code,
    [CUR_NAME] VARCHAR(65) NOT NULL  -- Currency Name,
    [CUR_SHTNAME] VARCHAR(5) NOT NULL  -- Currency Short Name,
    [CUR_SYMBOL] VARCHAR(5) NOT NULL  -- Currency Symbol,
    CONSTRAINT [PK_EXPCUR_MAST] PRIMARY KEY ([CUR_CODE])
);

-- Table: EXPENSEGROUP_MAST - Expense Group Master
CREATE TABLE [EXPENSEGROUP_MAST] (
    [EXPGROUP_ID] VARCHAR(255) NOT NULL  -- Expense Group ID,
    [EXPGROUP_NAME] VARCHAR(255) NOT NULL  -- Expense Group Name,
    [EXPGROUP_TRAVELTYPE] VARCHAR(255) NOT NULL  -- Expense Group Travel Type,
    [EXPGROUP_BREAKFLAG] VARCHAR(255) NOT NULL  -- Expense Group Break details required,
    CONSTRAINT [PK_EXPENSEGROUP_MAST] PRIMARY KEY ([EXPGROUP_ID])
);

-- Table: EXPENSEGROUP_MAP - Expense Group Mapping
CREATE TABLE [EXPENSEGROUP_MAP] (
    [EXPGROUPMAP_ID] VARCHAR(255) NOT NULL  -- Expense Group Map ID,
    [EXPGROUPMAP_GROUPID] VARCHAR(255) NOT NULL  -- Expense Group ID,
    [EXPGROUPMAP_EXPENSEID] VARCHAR(255) NOT NULL  -- Expense Group Expense ID,
    CONSTRAINT [PK_EXPENSEGROUP_MAP] PRIMARY KEY ([EXPGROUPMAP_ID])
);

-- Table: EXPENSETYPE_MAST - Expense type master
CREATE TABLE [EXPENSETYPE_MAST] (
    [EXPENSE_ID] BIGINT NOT NULL  -- Expense ID,
    [EXPENSE_NAME] VARCHAR(75) NOT NULL  -- Expense Name,
    [EXPENSE_CATID] INT NOT NULL  -- Expense Category ID,
    [EXPENSE_TRAVELTYPE] CHAR(3) NOT NULL  -- Expense Travel Type,
    [EXPENSE_SORTNO] BIGINT NOT NULL  -- Expense Sorting No,
    CONSTRAINT [PK_EXPENSETYPE_MAST] PRIMARY KEY ([EXPENSE_ID])
);

-- Table: GLOBALPAY_PARAMS - Global Pay Params
CREATE TABLE [GLOBALPAY_PARAMS] (
    [PARAM_ID] VARCHAR(255) NOT NULL  -- Param ID,
    [PARAM_CODE] VARCHAR(255) NOT NULL  -- Param Code,
    [PARAM_DESC] VARCHAR(255) NOT NULL  -- Param Description,
    [PARAM_VALUE] VARCHAR(255) NOT NULL  -- Param Value,
    CONSTRAINT [PK_GLOBALPAY_PARAMS] PRIMARY KEY ([PARAM_ID])
);

-- Table: GRADECAT_EXPRULE - Grade category wise Expense Rules
CREATE TABLE [GRADECAT_EXPRULE] (
    [EXPRULE_ID] VARCHAR(255) NOT NULL  -- Expense Rule ID,
    [EXPRULE_GRADECAT] VARCHAR(255) NOT NULL  -- Grade Category,
    [EXPRULE_APPLYTOUNIT] VARCHAR(255) NOT NULL  -- Apply to unit,
    [EXPRULE_UNITID] VARCHAR(255) NOT NULL  -- Unit,
    [EXPRULE_APPLYTOGRADE] VARCHAR(255) NOT NULL  -- Apply to all Grades,
    [EXPRULE_GRADEID] VARCHAR(255) NOT NULL  -- Grade ID,
    [EXPRULE_EXPTYPE] VARCHAR(255) NOT NULL  -- Expense Rule Type,
    [EXPRULE_LIMIT] VARCHAR(255) NOT NULL  -- Expense Limit,
    [EXPRULE_DAYLIMIT] VARCHAR(255) NOT NULL  -- Day Expense Limit,
    [EXPRULE_BROKENFLAG] VARCHAR(255) NOT NULL  -- Y/N,
    [EXPRULE_YPE] VARCHAR(3) NULL,
    CONSTRAINT [PK_GRADECAT_EXPRULE] PRIMARY KEY ([EXPRULE_ID])
);

-- Table: GRADECAT_EXPRULEBRK - Grade category wise Expense Rules Breakup
CREATE TABLE [GRADECAT_EXPRULEBRK] (
    [EXPRULE_BRKID] VARCHAR(255) NOT NULL  -- Expense Rule Break ID,
    [EXPRULE_ID] VARCHAR(255) NOT NULL  -- Expense Rule ID,
    [EXPRULE_FROMHRS] VARCHAR(255) NOT NULL  -- From Hours,
    [EXPRULE_TOHRS] VARCHAR(255) NOT NULL  -- To Hours,
    [EXPRULE_AMT] VARCHAR(255) NOT NULL  -- Amount,
    CONSTRAINT [PK_GRADECAT_EXPRULEBRK] PRIMARY KEY ([EXPRULE_BRKID])
);

-- Table: GRADECAT_MODEMAP - Grade category wise mode map
CREATE TABLE [GRADECAT_MODEMAP] (
    [MODEMAP_ID] VARCHAR(255) NOT NULL  -- Map ID,
    [MODEMAP_GRADECAT] VARCHAR(255) NOT NULL  -- Grade Category,
    [MODEMAP_APPLYTOUNIT] VARCHAR(255) NOT NULL  -- Apply to all Units,
    [MODEMAP_UNITID] VARCHAR(255) NOT NULL  -- Unit,
    [MODEMAP_APPLYTOGRADE] VARCHAR(255) NOT NULL  -- Apply to all Grades,
    [MODEMAP_GRADEID] VARCHAR(255) NOT NULL  -- Grade ID,
    [MODEMAP_MODEID] VARCHAR(255) NOT NULL  -- Mode ID,
    [MODEMAP_CLASSID] VARCHAR(255) NOT NULL  -- Class Type ID,
    [MODEMAP_SPECIALSTATUS] VARCHAR(255) NOT NULL  -- On Special Sanction Only
);

-- Table: GRADECAT_STAYRULE - Grade category wise Stay Rules
CREATE TABLE [GRADECAT_STAYRULE] (
    [STAYRULE_ID] VARCHAR(255) NOT NULL  -- Stay Rule ID,
    [STAYRULE_GRADECAT] VARCHAR(255) NOT NULL  -- Grade Category,
    [STAYRULE_APPLYTOUNIT] VARCHAR(255) NOT NULL  -- Apply to all Units,
    [STAYRULE_UNITID] VARCHAR(255) NOT NULL  -- Unit,
    [STAYRULE_APPLYTOGRADE] VARCHAR(255) NOT NULL  -- Apply to all Grades,
    [STAYRULE_GRADEID] VARCHAR(255) NOT NULL  -- Grade ID,
    [STAYRULE_TRAVELTYPE] VARCHAR(255) NOT NULL  -- DOM/INT,
    [STAYRULE_TYPE] VARCHAR(255) NOT NULL  -- OWN/ACT / FLT/ACT,
    [STAYRULE_CITYCLASSID] VARCHAR(255) NOT NULL  -- City Class ID / Sector ID,
    [STAYRULE_LIMIT] VARCHAR(255) NOT NULL  -- Entitlement Amount,
    [STAYRULE_BOOKCHARGES] VARCHAR(255) NOT NULL  -- Booking Charges,
    [STAYRULE_NIGHTSTAYVAL] VARCHAR(255) NOT NULL  -- Night stay charges,
    [STAYRULE_INCEXP] VARCHAR(255) NOT NULL  -- Incidental expenses,
    CONSTRAINT [PK_GRADECAT_STAYRULE] PRIMARY KEY ([STAYRULE_ID])
);

-- Table: GRADECATEXP_MAP - Expense Grade Category Mapping
CREATE TABLE [GRADECATEXP_MAP] (
    [EXPMAP_ID] VARCHAR(255) NOT NULL  -- Expense Map ID,
    [EXPMAP_GRADECAT] VARCHAR(255) NOT NULL  -- Grade Category,
    [EXPMAP_APPLYTOUNIT] VARCHAR(255) NOT NULL  -- Apply to all units,
    [EXPMAP_UNITID] VARCHAR(255) NOT NULL  -- Reporting Unit ID,
    [EXPMAP_APPLYTOGRADE] VARCHAR(255) NOT NULL  -- Apply to all Grades,
    [EXPMAP_GRADEID] VARCHAR(255) NOT NULL  -- Grade ID,
    [EXPMAP_EXPID] VARCHAR(255) NOT NULL  -- Expense ID,
    CONSTRAINT [PK_GRADECATEXP_MAP] PRIMARY KEY ([EXPMAP_ID])
);

-- Table: GRADETYPETRAVEL_PARAMS - Grade Type Travel Params
CREATE TABLE [GRADETYPETRAVEL_PARAMS] (
    [PARAM_ID] VARCHAR(255) NOT NULL  -- Param ID,
    [PARAM_GRADECAT] VARCHAR(255) NOT NULL  -- Grade Category,
    [PARAM_APPLYTOUNIT] VARCHAR(255) NOT NULL  -- Apply to all Units,
    [PARAM_UNITID] VARCHAR(255) NOT NULL  -- Reporting Unit,
    [PARAM_ADVANCEELG] VARCHAR(255) NOT NULL  -- Advance Eligible,
    [PARAM_ADVANCELIMIT] VARCHAR(255) NOT NULL  -- Advance Limit Per Day,
    [PARAM_ADVANCEDAYS] VARCHAR(255) NOT NULL  -- Advance Limits Days,
    [PARAM_ADVANCENOS] VARCHAR(255) NOT NULL  -- No of Advances,
    [PARAM_ADVANCEOUT] VARCHAR(255) NOT NULL  -- Allow to claim advance,
    [PARAM_TPAPPROVAL] VARCHAR(255) NOT NULL  -- Approval Required for Tour Plan,
    [PARAM_SETTIMELIMIT] VARCHAR(255) NOT NULL  -- Time period to submit,
    CONSTRAINT [PK_GRADETYPETRAVEL_PARAMS] PRIMARY KEY ([PARAM_ID])
);

-- Table: CALENDAR_GSTBUMAP - CALENDAR MAP
CREATE TABLE [CALENDAR_GSTBUMAP] (
    [CALENDAR_ID] INT NOT NULL,
    [CALENDAR_NAME] VARCHAR(100) NOT NULL,
    [CALENDAR_R12BU] VARCHAR(25) NULL
);

-- Table: TRAVEL_CITYMASTER - Travel City Master
CREATE TABLE [TRAVEL_CITYMASTER] (
    [CITY_ID] VARCHAR(255) NOT NULL  -- City ID,
    [CITY_COUNTRYID] VARCHAR(255) NOT NULL  -- Country ID,
    [CITY_NAME] VARCHAR(255) NOT NULL  -- City Name,
    [CITY_CODE] VARCHAR(255) NOT NULL  -- City Code,
    [CITY_LASTMODIFIEDBY] VARCHAR(255) NOT NULL  -- Last modified by,
    [CITY_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last modified on,
    CONSTRAINT [PK_TRAVEL_CITYMASTER] PRIMARY KEY ([CITY_ID])
);

-- Table: TRAVEL_CITYMODEMAP - Travel City Mode Map
CREATE TABLE [TRAVEL_CITYMODEMAP] (
    [CITYMODE_MAPID] VARCHAR(255) NOT NULL  -- City Mode Map ID,
    [CITYMODE_CITYID] VARCHAR(255) NOT NULL  -- City ID,
    [CITYMODE_MODEID] VARCHAR(255) NOT NULL  -- Mode ID,
    [CITYMODE_LASTMODIFIEDBY] VARCHAR(255) NOT NULL  -- Last modified by,
    [CITYMODE_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last modified on,
    CONSTRAINT [PK_TRAVEL_CITYMODEMAP] PRIMARY KEY ([CITYMODE_MAPID])
);

-- Table: TRAVEL_CITYSECMAP - Travel City Sector Map
CREATE TABLE [TRAVEL_CITYSECMAP] (
    [CITYSEC_MAPID] VARCHAR(255) NOT NULL  -- Sector Map ID,
    [CITYSEC_CITYID] VARCHAR(255) NOT NULL  -- Sector City ID,
    [CITYSEC_CLASSID] VARCHAR(255) NOT NULL  -- Sector Name,
    [CITYSEC_LASTMODIFIEDBY] VARCHAR(255) NOT NULL  -- Last modified by,
    [CITYSEC_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last modified on,
    [CITYSEC_GRADEFCAT] VARCHAR(255) NOT NULL  -- Grade Cat Specific,
    CONSTRAINT [PK_TRAVEL_CITYSECMAP] PRIMARY KEY ([CITYSEC_MAPID])
);

-- Table: TRAVEL_CLASS - Travel Class
CREATE TABLE [TRAVEL_CLASS] (
    [CLASS_ID] VARCHAR(255) NOT NULL  -- Class Type ID,
    [CLASS_MODEID] VARCHAR(255) NOT NULL  -- Mode ID,
    [CLASS_NAME] VARCHAR(255) NOT NULL  -- Class Type Name,
    [CLASS_ORDER] VARCHAR(255) NOT NULL  -- Class Order,
    CONSTRAINT [PK_TRAVEL_CLASS] PRIMARY KEY ([CLASS_ID])
);

-- Table: TRAVEL_CONTACT - Travel Contact
CREATE TABLE [TRAVEL_CONTACT] (
    [CONTACT_ID] VARCHAR(255) NULL  -- Contact ID,
    [CONTACT_TYPE] VARCHAR(255) NULL  -- Travel Type,
    [CONTACT_ADMINID] VARCHAR(255) NULL  -- Admin ID,
    [CONTACT_ADMNAME] VARCHAR(255) NULL  -- Name,
    [CONTACT_EMPSYSID] VARCHAR(255) NULL  -- Employee System ID,
    [CONTACT_PHONENOS] VARCHAR(255) NULL  -- Contact No,
    [CONTACT_EMAILID] VARCHAR(255) NULL  -- Email ID,
    [CONTACT_LASTMODIFIEDBY] VARCHAR(255) NULL  -- Last modified by,
    [CONTACT_LASTMODIFIEDON] DATETIME2(3) NULL  -- Last modified on,
    CONSTRAINT [PK_TRAVEL_CONTACT] PRIMARY KEY ([CONTACT_ID])
);

-- Table: TRAVEL_COUNTRYMASTER - Travel Country Master
CREATE TABLE [TRAVEL_COUNTRYMASTER] (
    [COUNTRY_ID] VARCHAR(255) NOT NULL  -- Country ID,
    [COUNTRY_NAME] VARCHAR(255) NOT NULL  -- Country Name,
    [COUNTRY_AIRID] VARCHAR(255) NOT NULL  -- Country Air Code,
    [COUNTRY_LASTMODIFIEDBY] VARCHAR(255) NOT NULL  -- Last modified by,
    [COUNTRY_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last modified on,
    [COUTRY_GHAVAILABLE] CHAR(1) NULL,
    [COUNTRY_GHRATE] VARCHAR(255) NULL,
    [COUNTRY_NMSGHRATE] VARCHAR(255) NULL,
    CONSTRAINT [PK_TRAVEL_COUNTRYMASTER] PRIMARY KEY ([COUNTRY_ID])
);

-- Table: TRAVEL_COUNTRYMODEMAP - Travel Country Mode Map
CREATE TABLE [TRAVEL_COUNTRYMODEMAP] (
    [MODE_MAPID] VARCHAR(255) NOT NULL  -- Country Mode Map ID,
    [MODE_ID] VARCHAR(255) NOT NULL  -- Mode ID,
    [MODE_COUNTRYID] VARCHAR(255) NOT NULL  -- Country ID,
    [MODE_LASTMODIFIEDBY] VARCHAR(255) NOT NULL  -- Last modified by,
    [MODE_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last modified on,
    CONSTRAINT [PK_TRAVEL_COUNTRYMODEMAP] PRIMARY KEY ([MODE_MAPID])
);

-- Table: TRAVEL_COUNTRYSECMAP - Travel Country Sector Map
CREATE TABLE [TRAVEL_COUNTRYSECMAP] (
    [SECTOR_MAPID] VARCHAR(255) NOT NULL  -- Sector Map ID,
    [SECTOR_COUNTRYID] VARCHAR(255) NOT NULL  -- Sector Country ID,
    [SECTOR_CLASSID] VARCHAR(255) NOT NULL  -- Sector ID,
    [SECTOR_LASTMODIFIEDBY] VARCHAR(255) NOT NULL  -- Last modified by,
    [SECTOR_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last modified on,
    CONSTRAINT [PK_TRAVEL_COUNTRYSECMAP] PRIMARY KEY ([SECTOR_MAPID])
);

-- Table: TRAVEL_COUNTRYCURMAP - Travel Country Currency Map
CREATE TABLE [TRAVEL_COUNTRYCURMAP] (
    [CURMAP_ID] VARCHAR(255) NOT NULL  -- Currency Map ID,
    [CURMAP_CURRENCYID] VARCHAR(255) NOT NULL  -- Currency ID,
    [CURMAP_COUNTRYID] VARCHAR(255) NOT NULL  -- Currenct Map Country ID,
    [CURMAP_LASTMODIFIEDBY] VARCHAR(255) NOT NULL  -- Last modified by,
    [CURMAP_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last modified on,
    CONSTRAINT [PK_TRAVEL_COUNTRYCURMAP] PRIMARY KEY ([CURMAP_ID])
);

-- Table: TRAVEL_BUSCITYSECMAP - Travel City Sector Business Map
CREATE TABLE [TRAVEL_BUSCITYSECMAP] (
    [CITYBUS_MAPID] VARCHAR(255) NOT NULL  -- Business Map ID,
    [CITYBUS_CITYID] VARCHAR(255) NOT NULL  -- City ID,
    [CITYBUS_CLASSID] VARCHAR(255) NOT NULL  -- Class ID,
    [CITYBUS_BUSID] VARCHAR(255) NOT NULL  -- Business ID,
    CONSTRAINT [PK_TRAVEL_BUSCITYSECMAP] PRIMARY KEY ([CITYBUS_MAPID])
);

-- Table: TRAVEL_BUEXCLUDE - TRAVEL EXCLUDE
CREATE TABLE [TRAVEL_BUEXCLUDE] (
    [BU_EXID] VARCHAR(255) NOT NULL,
    [BU_EMPSYSID] VARCHAR(255) NULL,
    [BU_UNITID] VARCHAR(255) NULL,
    CONSTRAINT [PK_TRAVEL_BUEXCLUDE] PRIMARY KEY ([BU_EXID])
);

-- Table: VENDOR_MASTER - Vendor Master
CREATE TABLE [VENDOR_MASTER] (
    [VENDOR_ID] VARCHAR(255) NOT NULL  -- Vendor ID,
    [VENDOR_NAME] VARCHAR(255) NOT NULL  -- Vendor Name,
    [VENDOR_ACTIVE] VARCHAR(255) NOT NULL  -- Active Status (Active/Inactive),
    [VENDOR_CODE] VARCHAR(255) NOT NULL  -- Vendor Code,
    [VENDOR_CONTACTPERSON] VARCHAR(255) NOT NULL  -- Contact Person,
    [VENDOR_ADDRESS1] VARCHAR(255) NOT NULL  -- Address 1,
    [VENDOR_ADDRESS2] VARCHAR(255) NOT NULL  -- Address 2,
    [VENDOR_ADDRESS3] VARCHAR(255) NOT NULL  -- Address 3,
    [VENDOR_ADDRESS4] VARCHAR(255) NOT NULL  -- Address 4,
    [VENDOR_PINCODE] VARCHAR(255) NOT NULL  -- Pin Code,
    [VENDOR_EMAILID] VARCHAR(255) NOT NULL  -- Email Id,
    [VENDOR_CCEMAILID] VARCHAR(255) NOT NULL  -- CC Email Id,
    [VENDOR_SRFTRIGGERID] VARCHAR(255) NOT NULL  -- SRF Mail Trigger ID,
    [VENDOR_MOBILENO] VARCHAR(255) NOT NULL  -- Mobile No,
    [VENDOR_PHONENOS] VARCHAR(255) NOT NULL  -- Additional Phone Nos,
    [VENDOR_TYPE] VARCHAR(255) NOT NULL  -- Type of Booking,
    [VENDOR_SUBTYPE] VARCHAR(255) NOT NULL  -- L/N,
    [VENDOR_DIRECTMAIL] VARCHAR(255) NULL  -- Direct Mail to Vendor,
    [VENDOR_USERID] VARCHAR(255) NULL  -- Allow to change User ID,
    [VENDOR_PASSWORD] VARCHAR(255) NULL  -- Password,
    [VENDOR_GSTNO] VARCHAR(255) NULL  -- Vendor GST No,
    CONSTRAINT [PK_VENDOR_MASTER] PRIMARY KEY ([VENDOR_ID])
);

-- Table: VENDOR_TAXRATE - Vendor Tax Rate
CREATE TABLE [VENDOR_TAXRATE] (
    [VENDOR_TAXID] VARCHAR(255) NOT NULL  -- Tax rate sequence ID,
    [VENDOR_ID] VARCHAR(255) NULL  -- Vendor ID,
    [VENDOR_TAXNATURE] VARCHAR(255) NOT NULL  -- Service Tax/Cess,
    [VENDOR_TAXRATE] VARCHAR(255) NOT NULL  -- Tax Rate,
    [VENDOR_TAXEFFDATE] DATETIME2(3) NOT NULL  -- Effective From,
    [VENDOR_TAXCLSDATE] DATETIME2(3) NOT NULL  -- Closure Date,
    [VENDOR_ENTBY] VARCHAR(255) NOT NULL  -- Entered By,
    [VENDOR_ENTON] DATETIME2(3) NOT NULL  -- Entered On,
    CONSTRAINT [PK_VENDOR_TAXRATE] PRIMARY KEY ([VENDOR_TAXID])
);

-- Table: VENDOR_UNITMAP - Vendor Unit Map
CREATE TABLE [VENDOR_UNITMAP] (
    [VENDOR_UNITMAPID] VARCHAR(255) NOT NULL  -- Vendor Unit Map ID,
    [VENDOR_ID] VARCHAR(255) NOT NULL  -- Vendor ID,
    [VENDOR_PAYUNITID] VARCHAR(255) NOT NULL  -- Payroll Unit ID,
    [VENDOR_ORASITEID] VARCHAR(255) NOT NULL  -- Oracle Site ID,
    [VENDOR_TERMID] VARCHAR(255) NOT NULL  -- Payment Term ID,
    CONSTRAINT [PK_VENDOR_UNITMAP] PRIMARY KEY ([VENDOR_UNITMAPID])
);

-- Table: VENDOR_CHARGES - Vendor Charges
CREATE TABLE [VENDOR_CHARGES] (
    [VENDOR_CHARGESID] VARCHAR(255) NULL  -- VENDORCHARGESID ID,
    [VENDOR_ID] VARCHAR(255) NULL  -- Vendor ID,
    [VENDOR_RATE] VARCHAR(255) NULL  -- Rate to be charged,
    [VENDOR_TAXEFFDATE] DATETIME2(3) NULL  -- Effective From,
    [VENDOR_TAXCLSDATE] DATETIME2(3) NULL  -- Closure Date,
    [VENDOR_ENTBY] VARCHAR(255) NULL  -- Entered By,
    [VENDOR_ENTON] DATETIME2(3) NULL  -- Entered On,
    CONSTRAINT [PK_VENDOR_CHARGES] PRIMARY KEY ([VENDOR_CHARGESID])
);

PRINT 'CONFIG Module - Tables created successfully.';
GO
