// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganizationStructureService.Infrastructure.Persistence;

#nullable disable

namespace OrganizationStructureService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrganizationDbContext))]
    [Migration("20260314062255_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrganizationStructureService.Domain.Entities.Business", b =>
                {
                    b.Property<decimal>("BusinessId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("BUSINESS_ID");

                    b.Property<string>("BusinessCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nchar(9)")
                        .HasColumnName("BUSINESS_CODE")
                        .IsFixedLength();

                    b.Property<string>("BusinessCompanyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("BUSINESS_COMP_CODE")
                        .IsFixedLength();

                    b.Property<decimal>("BusinessCompanyId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("BUSINESS_COMPID");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BUSINESS_NAME");

                    b.Property<string>("BusinessShortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("BUSINESS_SHTNAME");

                    b.Property<string>("LiveFlag")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("BUSINESS_LIVFLAG")
                        .IsFixedLength();

                    b.Property<decimal?>("UpdatedBy")
                        .HasColumnType("decimal(22,0)")
                        .HasColumnName("BUSINESS_UPDATEDBY");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("BUSINESS_UPDATEDON");

                    b.HasKey("BusinessId");

                    b.ToTable("BUSINESS_MASTER", (string)null);
                });

            modelBuilder.Entity("OrganizationStructureService.Domain.Entities.Department", b =>
                {
                    b.Property<decimal>("DepartmentId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("DEPARTMENT_ID");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DEPARTMENT_CODE");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DEPARTMENT_NAME");

                    b.Property<string>("LiveFlag")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("DEPARTMENT_LIVFLAG")
                        .IsFixedLength();

                    b.Property<decimal?>("UpdatedBy")
                        .HasColumnType("decimal(22,0)")
                        .HasColumnName("DEPARTMENT_UPDATEDBY");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("DEPARTMENT_UPDATEDON");

                    b.HasKey("DepartmentId");

                    b.ToTable("DEPARTMENT_MASTER", (string)null);
                });

            modelBuilder.Entity("OrganizationStructureService.Domain.Entities.Division", b =>
                {
                    b.Property<decimal>("DivisionId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("DIVISION_ID");

                    b.Property<string>("DivisionCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("DIVISION_CODE");

                    b.Property<string>("DivisionName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DIVISION_NAME");

                    b.Property<string>("LiveFlag")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("DIVISION_LIVEFLAG")
                        .IsFixedLength();

                    b.Property<decimal?>("UpdatedBy")
                        .HasColumnType("decimal(22,0)")
                        .HasColumnName("DIVISION_UPDATEDBY");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("DIVISION_UPDATEDON");

                    b.HasKey("DivisionId");

                    b.ToTable("DIVISION_MASTER", (string)null);
                });

            modelBuilder.Entity("OrganizationStructureService.Domain.Entities.Grade", b =>
                {
                    b.Property<decimal>("GradeId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("GRADE_ID");

                    b.Property<decimal?>("CadreId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("GRADE_CADREID");

                    b.Property<string>("DefaultRating")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("GRADE_DEFRATING");

                    b.Property<string>("GradeCategoryCode")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("GRADE_CATEGORYCODE")
                        .IsFixedLength();

                    b.Property<string>("GradeCode")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("GRADE_CODE")
                        .IsFixedLength();

                    b.Property<string>("GradeDesignation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("GRADE_DESIGNATION");

                    b.Property<string>("GradeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("GRADE_NAME");

                    b.Property<decimal?>("LevelCount")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("GRADE_LEVELNOS");

                    b.Property<string>("LiveFlag")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("GRADE_LIVFLAG")
                        .IsFixedLength();

                    b.Property<string>("ManagementCategoryCode")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("GRADE_MAN_COD")
                        .IsFixedLength();

                    b.Property<decimal?>("Priority")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("GRADE_PRIORITY");

                    b.Property<decimal?>("PromotionScore")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("GRADE_PROMSCORE");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("GRADE_SUBCAT")
                        .IsFixedLength();

                    b.HasKey("GradeId");

                    b.ToTable("GRADE_MASTER", (string)null);
                });

            modelBuilder.Entity("OrganizationStructureService.Domain.Entities.HrRole", b =>
                {
                    b.Property<decimal>("HrRoleId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("HRROLE_ID");

                    b.Property<string>("HrRoleCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("HRROLE_CODE");

                    b.Property<string>("HrRoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("HRROLE_NAME");

                    b.HasKey("HrRoleId");

                    b.ToTable("HRROLE_MASTER", (string)null);
                });

            modelBuilder.Entity("OrganizationStructureService.Domain.Entities.Level", b =>
                {
                    b.Property<decimal>("LevelId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("LEVEL_ID");

                    b.Property<decimal?>("LastUpdatedBy")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("LEVEL_LASTUPDATEDBY");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("LEVEL_LASTUPDATEDON");

                    b.Property<string>("LevelDesignation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LEVEL_DESIGNATION");

                    b.Property<decimal?>("LevelGradeId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("LEVEL_GRADEID");

                    b.Property<string>("LevelLiveFlag")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("LEVEL_LIVEFLAG")
                        .IsFixedLength();

                    b.Property<string>("LevelName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LEVEL_NAME");

                    b.Property<decimal?>("LevelPriority")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("LEVEL_PRIORITY");

                    b.HasKey("LevelId");

                    b.ToTable("LEVEL_MASTER", (string)null);
                });

            modelBuilder.Entity("OrganizationStructureService.Domain.Entities.Location", b =>
                {
                    b.Property<decimal>("LocationCode")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("LOCATION_CODE");

                    b.Property<string>("LocationName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LOCATION_NAME");

                    b.Property<decimal>("LocationRegionCode")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("LOCATION_REGION_CODE");

                    b.Property<decimal?>("UpdatedBy")
                        .HasColumnType("decimal(22,0)")
                        .HasColumnName("LOCATION_UPDATEDBY");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("LOCATION_UPDATEDON");

                    b.HasKey("LocationCode");

                    b.ToTable("LOCATION_MASTER", (string)null);
                });

            modelBuilder.Entity("OrganizationStructureService.Domain.Entities.LovMaster", b =>
                {
                    b.Property<decimal>("LovId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("LOV_ID");

                    b.Property<string>("LovName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LOV_NAME");

                    b.Property<string>("LovType")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("LOV_TYPE")
                        .IsFixedLength();

                    b.Property<decimal?>("LovUpdatedBy")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("LOV_UPDATEDBY");

                    b.Property<DateTime?>("LovUpdatedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("LOV_UPDATEDON");

                    b.HasKey("LovId");

                    b.ToTable("LOV_MASTER", (string)null);
                });

            modelBuilder.Entity("OrganizationStructureService.Domain.Entities.Position", b =>
                {
                    b.Property<decimal>("PositionId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("POSITION_ID");

                    b.Property<decimal?>("Ctc")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CTC");

                    b.Property<string>("DeletedFlag")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("DELETED_FLAG")
                        .IsFixedLength();

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("ENTERED_DATE");

                    b.Property<decimal>("EnteredPinNo")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("ENTERED_PIN_NO");

                    b.Property<DateTime?>("PosClosedDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("POS_CLOSED_DATE");

                    b.Property<DateTime>("PosEffectiveDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("POS_EFFECTIVE_DATE");

                    b.Property<long>("PosEvaluatedGradeId")
                        .HasColumnType("bigint")
                        .HasColumnName("POS_EVEGRADE_ID");

                    b.Property<decimal>("PosGradeId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("POS_GRADE_ID");

                    b.Property<decimal?>("PosModifiedBy")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("POS_MODIFIED_BY");

                    b.Property<DateTime?>("PosModifiedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("POS_MODIFIED_ON");

                    b.Property<long?>("PosRefNo")
                        .HasColumnType("bigint")
                        .HasColumnName("POS_REFNO");

                    b.Property<string>("PosUnitCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("POS_UNIT_CODE")
                        .IsFixedLength();

                    b.Property<decimal?>("PosUnitId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("POS_UNIT_ID");

                    b.Property<string>("PositionDesignation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("POSITION_DESIGNATION");

                    b.Property<string>("PositionEvaluatedDesignation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("POSITION_EVEDESIGNATION");

                    b.Property<decimal?>("PositionJdId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("POSITION_JD_ID");

                    b.Property<string>("PositionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("POSITION_NAME");

                    b.Property<decimal?>("ProcessId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("PROCESS_ID");

                    b.Property<decimal?>("ReasonId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("REASON_ID");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("REFERENCE_CODE")
                        .IsFixedLength();

                    b.Property<decimal?>("ReplacePositionId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("REPLACE_POSID");

                    b.HasKey("PositionId");

                    b.ToTable("POSITION_MASTER", (string)null);
                });

            modelBuilder.Entity("OrganizationStructureService.Domain.Entities.Region", b =>
                {
                    b.Property<decimal>("RegionCode")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("REGION_CODE");

                    b.Property<decimal>("RegionCountryCode")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("REGION_COUNTRY_CODE");

                    b.Property<string>("RegionName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("REGION_NAME");

                    b.Property<decimal?>("UpdatedBy")
                        .HasColumnType("decimal(22,0)")
                        .HasColumnName("REGION_UPDATEDBY");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("REGION_UPDATEDON");

                    b.HasKey("RegionCode");

                    b.ToTable("REGION_MASTER", (string)null);
                });

            modelBuilder.Entity("OrganizationStructureService.Domain.Entities.Site", b =>
                {
                    b.Property<decimal>("SiteId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("SITE_ID");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_ADDRESS_LINE_1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_ADDRESS_LINE_2");

                    b.Property<string>("AddressLine3")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_ADDRESS_LINE_3");

                    b.Property<string>("AddressLine4")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_ADDRESS_LINE_4");

                    b.Property<string>("AddressPin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SITE_ADDRESS_PIN");

                    b.Property<string>("AttachedEmployee")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("SITE_ATTACHEDEMPLOYEE")
                        .IsFixedLength();

                    b.Property<string>("ContactName1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_CONTACT_NAME1");

                    b.Property<string>("ContactName2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_CONTACT_NAME2");

                    b.Property<string>("ContactPhone1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_CONTACT_PHONE1");

                    b.Property<string>("ContactPhone2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_CONTACT_PHONE2");

                    b.Property<string>("DistanceAirport")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_DISTANCEAIRPORT");

                    b.Property<string>("DistanceRail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_DISTANCERAIL");

                    b.Property<string>("FaxNo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_FAXNO");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_IMAGEPATH");

                    b.Property<string>("Landmark1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_LANDMARK_1");

                    b.Property<string>("Landmark2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_LANDMARK_2");

                    b.Property<string>("LiveFlag")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("SITE_LIVFLAG")
                        .IsFixedLength();

                    b.Property<decimal?>("LocationCode")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("SITE_LOCATION_CODE");

                    b.Property<string>("NearestAirport")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_NEARESTAIRPORT");

                    b.Property<string>("NearestRail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_NEARESTRAIL");

                    b.Property<string>("Phone1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_PHONE_1");

                    b.Property<string>("Phone2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_PHONE_2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_REMARKS");

                    b.Property<decimal>("SiteCategoryCode")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("SITE_CATEGORY_CODE");

                    b.Property<decimal>("SiteCityCode")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("SITE_CITY_CODE");

                    b.Property<string>("SiteName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_NAME");

                    b.Property<string>("SiteShortName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_SHORT_NAME");

                    b.Property<long?>("TravelLocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("SITE_TRAVELLOCID");

                    b.Property<string>("VisitorPolicyPath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SITE_VISITORPOLICYPATH");

                    b.HasKey("SiteId");

                    b.ToTable("SITE_MASTER", (string)null);
                });

            modelBuilder.Entity("OrganizationStructureService.Domain.Entities.Unit", b =>
                {
                    b.Property<decimal>("UnitId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("UNIT_ID");

                    b.Property<string>("LiveFlag")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("UNIT_LIVFLAG")
                        .IsFixedLength();

                    b.Property<decimal>("OrgId")
                        .HasColumnType("decimal(22,0)")
                        .HasColumnName("UNIT_ORGID");

                    b.Property<string>("PayFlag")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("UNIT_PAYFLAG")
                        .IsFixedLength();

                    b.Property<string>("PayLiveFlag")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("UNIT_PAYLIVEFLAG")
                        .IsFixedLength();

                    b.Property<string>("PfFlag")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("UNIT_PFFLG")
                        .IsFixedLength();

                    b.Property<string>("RegionalLanguageCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("UNIT_REGLANGCODE");

                    b.Property<string>("RegionalLanguageFlag")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("UNIT_REGLANGFLAG")
                        .IsFixedLength();

                    b.Property<string>("ReportFlag")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("UNIT_RPTFLAG")
                        .IsFixedLength();

                    b.Property<string>("UnitBusinessCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nchar(9)")
                        .HasColumnName("UNIT_BUSINESS_CODE")
                        .IsFixedLength();

                    b.Property<decimal>("UnitBusinessId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("UNIT_BUSINESSID");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("UNIT_CODE")
                        .IsFixedLength();

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UNIT_NAME");

                    b.Property<string>("UnitShortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("UNIT_SHTNAME");

                    b.Property<decimal?>("UpdatedBy")
                        .HasColumnType("decimal(22,0)")
                        .HasColumnName("UNIT_UPDATEDBY");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("UNIT_UPDATEDON");

                    b.HasKey("UnitId");

                    b.ToTable("UNIT_MASTER", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
