-- Seed Data Script: OrganizationStructure Service
-- Run after InitialCreate migration

USE [HRDB];
GO

-- Seed HRROLE_MASTER
IF NOT EXISTS (SELECT 1 FROM HRROLE_MASTER WHERE HRROLE_ID = 1)
BEGIN
    INSERT INTO HRROLE_MASTER (HRROLE_ID, HRROLE_CODE, HRROLE_NAME) VALUES (1, 'ADM', 'Admin');
    INSERT INTO HRROLE_MASTER (HRROLE_ID, HRROLE_CODE, HRROLE_NAME) VALUES (2, 'MGR', 'Manager');
    INSERT INTO HRROLE_MASTER (HRROLE_ID, HRROLE_CODE, HRROLE_NAME) VALUES (3, 'EMP', 'Employee');
END

-- Seed LOV_MASTER (reference LOV types)
IF NOT EXISTS (SELECT 1 FROM LOV_MASTER WHERE LOV_ID = 1)
BEGIN
    INSERT INTO LOV_MASTER (LOV_ID, LOV_TYPE, LOV_NAME) VALUES (1, 'GEN', 'General');
    INSERT INTO LOV_MASTER (LOV_ID, LOV_TYPE, LOV_NAME) VALUES (2, 'REF', 'Reference');
    INSERT INTO LOV_MASTER (LOV_ID, LOV_TYPE, LOV_NAME) VALUES (3, 'CTG', 'Category');
END

-- Seed REGION_MASTER
IF NOT EXISTS (SELECT 1 FROM REGION_MASTER WHERE REGION_CODE = 1)
BEGIN
    INSERT INTO REGION_MASTER (REGION_CODE, REGION_NAME, REGION_COUNTRY_CODE) VALUES (1, 'North Region', 1);
    INSERT INTO REGION_MASTER (REGION_CODE, REGION_NAME, REGION_COUNTRY_CODE) VALUES (2, 'South Region', 1);
    INSERT INTO REGION_MASTER (REGION_CODE, REGION_NAME, REGION_COUNTRY_CODE) VALUES (3, 'East Region', 1);
    INSERT INTO REGION_MASTER (REGION_CODE, REGION_NAME, REGION_COUNTRY_CODE) VALUES (4, 'West Region', 1);
END

-- Seed SITECATEGORY_MAST
IF NOT EXISTS (SELECT 1 FROM SITECATEGORY_MAST WHERE CATEGORY_CODE = 1)
BEGIN
    INSERT INTO SITECATEGORY_MAST (CATEGORY_CODE, CATEGORY_NAME) VALUES (1, 'Head Office');
    INSERT INTO SITECATEGORY_MAST (CATEGORY_CODE, CATEGORY_NAME) VALUES (2, 'Regional Office');
    INSERT INTO SITECATEGORY_MAST (CATEGORY_CODE, CATEGORY_NAME) VALUES (3, 'Branch Office');
    INSERT INTO SITECATEGORY_MAST (CATEGORY_CODE, CATEGORY_NAME) VALUES (4, 'Factory');
END

-- Seed DIVISION_MASTER
IF NOT EXISTS (SELECT 1 FROM DIVISION_MASTER WHERE DIVISION_ID = 1)
BEGIN
    INSERT INTO DIVISION_MASTER (DIVISION_ID, DIVISION_CODE, DIVISION_NAME, DIVISION_LIVEFLAG) VALUES (1, 'FIN', 'Finance', 'Y');
    INSERT INTO DIVISION_MASTER (DIVISION_ID, DIVISION_CODE, DIVISION_NAME, DIVISION_LIVEFLAG) VALUES (2, 'OPS', 'Operations', 'Y');
    INSERT INTO DIVISION_MASTER (DIVISION_ID, DIVISION_CODE, DIVISION_NAME, DIVISION_LIVEFLAG) VALUES (3, 'HRD', 'Human Resources', 'Y');
    INSERT INTO DIVISION_MASTER (DIVISION_ID, DIVISION_CODE, DIVISION_NAME, DIVISION_LIVEFLAG) VALUES (4, 'ITD', 'Information Technology', 'Y');
END

-- Seed DEPARTMENT_MASTER
IF NOT EXISTS (SELECT 1 FROM DEPARTMENT_MASTER WHERE DEPARTMENT_ID = 1)
BEGIN
    INSERT INTO DEPARTMENT_MASTER (DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_CODE, DEPARTMENT_LIVFLAG) VALUES (1, 'Accounts', 'ACC', 'Y');
    INSERT INTO DEPARTMENT_MASTER (DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_CODE, DEPARTMENT_LIVFLAG) VALUES (2, 'HR Department', 'HRD', 'Y');
    INSERT INTO DEPARTMENT_MASTER (DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_CODE, DEPARTMENT_LIVFLAG) VALUES (3, 'IT Department', 'ITD', 'Y');
    INSERT INTO DEPARTMENT_MASTER (DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_CODE, DEPARTMENT_LIVFLAG) VALUES (4, 'Production', 'PRD', 'Y');
END

-- Seed GRADE_MASTER
IF NOT EXISTS (SELECT 1 FROM GRADE_MASTER WHERE GRADE_ID = 1)
BEGIN
    INSERT INTO GRADE_MASTER (GRADE_ID, GRADE_CODE, GRADE_NAME, GRADE_DESIGNATION, GRADE_CATEGORYCODE, GRADE_LIVFLAG, GRADE_MAN_COD, GRADE_PRIORITY)
    VALUES (1, 'E01', 'Executive Grade 1', 'Junior Executive', 'EXC', 'Y', 'JM', 1);
    INSERT INTO GRADE_MASTER (GRADE_ID, GRADE_CODE, GRADE_NAME, GRADE_DESIGNATION, GRADE_CATEGORYCODE, GRADE_LIVFLAG, GRADE_MAN_COD, GRADE_PRIORITY)
    VALUES (2, 'M01', 'Manager Grade 1', 'Manager', 'MGT', 'Y', 'MM', 2);
    INSERT INTO GRADE_MASTER (GRADE_ID, GRADE_CODE, GRADE_NAME, GRADE_DESIGNATION, GRADE_CATEGORYCODE, GRADE_LIVFLAG, GRADE_MAN_COD, GRADE_PRIORITY)
    VALUES (3, 'S01', 'Senior Grade 1', 'Senior Manager', 'SEN', 'Y', 'SM', 3);
END

GO
PRINT 'Seed data applied successfully.';
