-- =========================================================================
-- BANK MODULE - Database Tables
-- Database: PFDB
-- Module: Bank and Cheque Management
-- Description: Manages bank accounts, cheques, and payments
-- Created: March 9, 2026
-- =========================================================================

USE PFDB;
GO

-- Bank Master
CREATE TABLE [BANK_MASTER] (
    [BANK_TRUST_CODE] CHAR(3) NOT NULL,
    [BANK_CODE] CHAR(6) NOT NULL,
    [BANK_NAME] CHAR(65) NOT NULL,
    [MICR_CODE] CHAR(9) NOT NULL,
    [BRANCH_NAME] VARCHAR(65) NOT NULL,
    [BRANCH_ADDRESS_LINE_1] VARCHAR(200) NOT NULL,
    [BRANCH_ADDRESS_LINE_2] VARCHAR(200) NULL,
    [BRANCH_ADDRESS_LINE_3] VARCHAR(200) NULL,
    [BRANCH_ADDRESS_LINE_4] VARCHAR(200) NULL,
    [BRANCH_PHONE_NO] VARCHAR(200) NULL,
    [BRANCH_FAX_NO] VARCHAR(200) NULL,
    [BRANCH_EFF_DATE] DATETIME2(3) NOT NULL,
    [BRANCH_CLS_DATE] DATETIME2(3) NULL,
    [BRANCH_STATUS] CHAR(1) DEFAULT 'A',
    CONSTRAINT [PK_BANK_MASTER] PRIMARY KEY ([BANK_TRUST_CODE], [BANK_CODE])
);
GO

-- Cheque Details
CREATE TABLE [CHEQUE_DET] (
    [CHEQUE_ACTRAN_NO] BIGINT NULL,
    [CHEQUE_ID] BIGINT NOT NULL PRIMARY KEY,
    [CHEQUE_BRANCH] VARCHAR(200) NULL,
    [CHEQUE_NO] DECIMAL(20,0) NULL,
    [CHEQUE_DATE] DATETIME2(3) NULL,
    [CHEQUE_BANK] BIGINT NULL,
    [CHEQUE_REMARKS] VARCHAR(200) NULL,
    [CHEQUE_AMOUNT] DECIMAL(19,0) NULL,
    [CHEQUE_STATUS] CHAR(1) DEFAULT 'I',
    [CHEQUE_PAYEE] VARCHAR(100) NULL,
    [CHEQUE_CLEARED_DATE] DATETIME2(3) NULL
);
GO

-- Bank Account
CREATE TABLE [BANK_ACCOUNT] (
    [ACCOUNT_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [ACCOUNT_NUMBER] VARCHAR(30) NOT NULL UNIQUE,
    [ACCOUNT_TITLE] VARCHAR(100) NOT NULL,
    [BANK_CODE] CHAR(6) NOT NULL,
    [TRUST_CODE] CHAR(3) NOT NULL,
    [ACCOUNT_TYPE] VARCHAR(20) NOT NULL,
    [ACCOUNT_BALANCE] DECIMAL(19,0) DEFAULT 0,
    [ACCOUNT_STATUS] CHAR(1) DEFAULT 'A',
    [OPENING_DATE] DATETIME2(3) NOT NULL,
    [CLOSING_DATE] DATETIME2(3) NULL
);
GO

-- Cheque Register
CREATE TABLE [CHEQUE_REGISTER] (
    [REGISTER_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [CHEQUE_NO_FROM] DECIMAL(20,0) NOT NULL,
    [CHEQUE_NO_TO] DECIMAL(20,0) NOT NULL,
    [CHEQUE_BOOK_ID] VARCHAR(50) NOT NULL,
    [ACCOUNT_ID] BIGINT NOT NULL,
    [ISSUED_DATE] DATETIME2(3) NOT NULL,
    [REGISTER_STATUS] CHAR(1) DEFAULT 'A',
    CONSTRAINT [FK_CHEQUE_REGISTER_ACCOUNT] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [BANK_ACCOUNT]([ACCOUNT_ID])
);
GO

-- Payment Reconciliation
CREATE TABLE [PAYMENT_RECONCILIATION] (
    [RECON_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [CHEQUE_ID] BIGINT NOT NULL,
    [RECON_REFERENCE] VARCHAR(100) NOT NULL,
    [RECON_AMOUNT] DECIMAL(19,0) NOT NULL,
    [RECON_DATE] DATETIME2(3) NOT NULL,
    [RECON_STATUS] CHAR(1) DEFAULT 'O',
    CONSTRAINT [FK_PAYMENT_RECON_CHEQUE] FOREIGN KEY ([CHEQUE_ID]) REFERENCES [CHEQUE_DET]([CHEQUE_ID])
);
GO

CREATE NONCLUSTERED INDEX [IDX_BANK_MASTER_TRUST] ON [BANK_MASTER] ([BANK_TRUST_CODE], [BRANCH_STATUS]);
CREATE NONCLUSTERED INDEX [IDX_CHEQUE_DET_STATUS] ON [CHEQUE_DET] ([CHEQUE_STATUS], [CHEQUE_DATE]);
CREATE NONCLUSTERED INDEX [IDX_BANK_ACCOUNT_TRUST] ON [BANK_ACCOUNT] ([TRUST_CODE], [ACCOUNT_STATUS]);
CREATE NONCLUSTERED INDEX [IDX_CHEQUE_REGISTER_ACCOUNT] ON [CHEQUE_REGISTER] ([ACCOUNT_ID], [REGISTER_STATUS]);

PRINT 'Bank Module Tables created successfully!';
GO
