# RabbitMQ Configuration
# Loaded on startup to set default management features

management.load_definitions = /etc/rabbitmq/definitions.json

# Logging
log.console = true
log.console.level = warning
log.file.level = warning

# Memory and Disk Limits
vm_memory_high_watermark.relative = 0.7
disk_free_limit.absolute = 1GB

# Connection limits
channel_max = 128
heartbeat = 60

# Queue limits
queue_master_locator = min-masters
