-- EDUCATION MODULE - SCHEMA DEFINITION
-- Academic records, qualifications, and specializations

USE [Careers]
GO

/****** ACADEMICS ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ACADEMICS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOGIN_ID] [bigint] NULL,
	[ACADEMIC_NO] [int] NULL,
	[EXAM_PASSED] [varchar](50) NULL,
	[INSTITUTION] [varchar](50) NULL,
	[FROM_DATE] [datetime] NULL,
	[TO_DATE] [datetime] NULL,
	[SPECIFICATION] [varchar](50) NULL,
	[CLASS] [varchar](20) NULL,
	[PERCENTAGE] [varchar](20) NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
	[ISVALID] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** ACADEMIC_ACTIVITIES ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ACADEMIC_ACTIVITIES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOGIN_ID] [bigint] NULL,
	[SUMMARY_OF_ACHIEVEMENTS] [varchar](300) NULL,
	[TRAINING_COURCES] [varchar](300) NULL,
	[PAPER_PRESENTAION] [varchar](300) NULL,
	[PREOFESSIONAL_MEMBERSHIP] [varchar](300) NULL,
	[HIBBIES_EXT_CURRICUL] [varchar](300) NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** EXAMS_MASTER ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[EXAMS_MASTER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[EXAMS] [varchar](70) NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** SPECIALISATION_MASTER ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SPECIALISATION_MASTER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[SPECIALISATION] [varchar](50) NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
