-- ==========================================
-- MASTER MODULE - Schema
-- Database: LETDB
-- Purpose: Master & Reference Data Tables
-- Created: March 9, 2026
-- ==========================================

USE LETDB;
GO

-- ==========================================
-- MASTER MODULE - Master Tables
-- ==========================================

-- Table: BENEFIT_MAST
CREATE TABLE [BENEFIT_MAST] (
    [BE_BEN_COD] CHAR(3) NOT NULL PRIMARY KEY,
    [BE_BEN_DES] VARCHAR(200) NOT NULL
);

-- Table: CAT_MAST - Category Master
CREATE TABLE [CAT_MAST] (
    [CT_CAT_COD] CHAR(3) NOT NULL PRIMARY KEY,
    [CT_CAT_NAM] VARCHAR(65) NOT NULL,
    [CT_SRL_NUM] BIGINT NULL
);

-- Table: COST_MAST - Cost Master
CREATE TABLE [COST_MAST] (
    [CS_CST_COD] BIGINT NOT NULL PRIMARY KEY,
    [CS_CST_NAM] VARCHAR(65) NOT NULL
);

-- Table: COMP_FINYEAR - Company Financial Year
CREATE TABLE [COMP_FINYEAR] (
    [AC_SRL_NUM] BIGINT NOT NULL PRIMARY KEY,
    [AC_STR_DAT] DATETIME2(3) NOT NULL,
    [AC_END_DAT] DATETIME2(3) NOT NULL,
    [AC_CLS_FLG] CHAR(1) NOT NULL
);

-- Table: FUNCTION_MAST - Function Master
CREATE TABLE [FUNCTION_MAST] (
    [FN_FNC_COD] CHAR(3) NOT NULL PRIMARY KEY,
    [FN_FNC_NAM] VARCHAR(65) NOT NULL,
    [FN_GRP_COD] CHAR(3) NOT NULL,
    [FN_UNT_COD] CHAR(9) NOT NULL,
    [FN_SRL_NUM] BIGINT NULL
);

-- Table: FUNCTION_GROUP - Function Group Master
CREATE TABLE [FUNCTION_GROUP] (
    [GR_GRP_COD] CHAR(3) NOT NULL PRIMARY KEY,
    [GR_GRP_NAM] VARCHAR(65) NOT NULL,
    [GR_SRL_NUM] BIGINT NULL
);

-- Table: GOAL_MAST - Goal Master
CREATE TABLE [GOAL_MAST] (
    [GL_GOL_COD] CHAR(3) NOT NULL PRIMARY KEY,
    [GL_GOL_NAM] VARCHAR(65) NOT NULL
);

-- Table: JOB_MAST - Job Master
CREATE TABLE [JOB_MAST] (
    [JB_JOB_COD] BIGINT NOT NULL PRIMARY KEY,
    [JB_JOB_NAM] VARCHAR(65) NOT NULL,
    [JB_CAT_COD] CHAR(3) NOT NULL,
    [JB_SRL_NUM] BIGINT NULL
);

-- Table: INSTRUCTION_MAST - Instruction Master
CREATE TABLE [INSTRUCTION_MAST] (
    [IN_TR_COD] VARCHAR(1) NULL,
    [IN_TR_NAM] VARCHAR(65) NULL
);

-- Table: LOC_MAST - Location Master
CREATE TABLE [LOC_MAST] (
    [LC_LOC_COD] CHAR(3) NULL,
    [LC_LOC_NAM] VARCHAR(65) NULL
);

-- Table: LOCATION_MAST - Location Master Extended
CREATE TABLE [LOCATION_MAST] (
    [LN_LOC_COD] BIGINT NULL,
    [LN_LOC_NAM] VARCHAR(65) NULL
);

-- Table: MODE_MAST - Mode Master
CREATE TABLE [MODE_MAST] (
    [MD_MOD_COD] CHAR(3) NOT NULL PRIMARY KEY,
    [MD_MOD_DES] VARCHAR(65) NOT NULL
);

-- Table: SKILL_MAST - Skill Master
CREATE TABLE [SKILL_MAST] (
    [SK_SKL_COD] BIGINT NOT NULL PRIMARY KEY,
    [SK_SKL_NAM] VARCHAR(255) NOT NULL,
    [SK_SKL_TYP] CHAR(1) NOT NULL,
    [SK_WGT_NUM] DECIMAL(19,0) NULL,
    [SK_SKL_REM] VARCHAR(4000) NULL,
    [SK_EFF_DAT] DATETIME2(3) NULL,
    [SK_CLS_DAT] DATETIME2(3) NULL
);

-- Table: SKILL_GROUP - Skill Group Master
CREATE TABLE [SKILL_GROUP] (
    [SK_GRP_COD] CHAR(3) NOT NULL PRIMARY KEY,
    [SK_GRP_NAM] VARCHAR(25) NOT NULL
);

-- Table: SOURCE_MAST - Source Master
CREATE TABLE [SOURCE_MAST] (
    [SR_SRC_COD] CHAR(3) NOT NULL PRIMARY KEY,
    [SR_SRC_NAM] VARCHAR(65) NOT NULL
);

-- Table: TRAIN_MAST - Training Master
CREATE TABLE [TRAIN_MAST] (
    [TR_TRN_COD] BIGINT NOT NULL PRIMARY KEY,
    [TR_TRN_NAM] VARCHAR(255) NOT NULL,
    [TR_TRN_ADD1] VARCHAR(255) NULL,
    [TR_TRN_ADD2] VARCHAR(255) NULL,
    [TR_TRN_ADD3] VARCHAR(255) NULL,
    [TR_TRN_ADD4] VARCHAR(255) NULL,
    [TR_CNT_NAM1] VARCHAR(255) NULL,
    [TR_CNT_NAM2] VARCHAR(255) NULL,
    [TR_REM_MRK] VARCHAR(255) NULL,
    [TR_PHN_NUM1] VARCHAR(255) NULL,
    [TR_PHN_NUM2] VARCHAR(255) NULL,
    [TR_FAX_NUM1] VARCHAR(255) NULL,
    [TR_FAX_NUM2] VARCHAR(255) NULL,
    [TR_EML_ADD1] VARCHAR(255) NULL,
    [TR_EML_ADD2] VARCHAR(255) NULL,
    [TR_GRP_COD] BIGINT NULL,
    [TR_VND_RAT] DECIMAL(38) NULL,
    [TR_EFF_DAT] DATETIME2(3) NULL,
    [TR_CAN_DAT] DATETIME2(3) NULL,
    [TR_CAN_REM] VARCHAR(255) NULL,
    [TR_BRC_FIL] VARCHAR(255) NULL,
    [TR_VND_EXP] VARCHAR(255) NULL
);

-- Table: TRAIN_GROUP - Training Group Master
CREATE TABLE [TRAIN_GROUP] (
    [TR_GRP_COD] BIGINT NOT NULL PRIMARY KEY,
    [TR_GRP_NAM] VARCHAR(65) NULL
);

-- Table: VTOCOMP - VTO Competency Reference
CREATE TABLE [VTOCOMP] (
    [VC_USR_ID] VARCHAR(25) NULL,
    [VC_USR_PIN] DECIMAL(20,0) NULL,
    [VC_REQ_NUM] BIGINT NULL,
    [VC_REQ_USR] VARCHAR(25) NULL,
    [VC_REQ_PIN] DECIMAL(20,0) NULL,
    [VC_REQ_NAM] VARCHAR(150) NULL,
    [VC_REQ_GRD] VARCHAR(25) NULL,
    [VC_COM_COD] VARCHAR(4) NULL,
    [VC_UNT_COD] CHAR(3) NULL,
    [VC_UNT_REP] CHAR(3) NULL,
    [VC_BUS_COD] VARCHAR(50) NULL,
    [VC_EMP_NUM] BIGINT NULL,
    [VC_FIN_YER] DATETIME2(3) NULL
);

-- ==========================================
-- TEST/MISCELLANEOUS TABLE
-- ==========================================

-- Table: DDTT - Test Table
CREATE TABLE [DDTT] (
    [SRLNO] DECIMAL(38) NULL,
    [TEST] VARCHAR(4000) NULL,
    [TEST1] VARCHAR(9) NULL,
    [TEST2] VARCHAR(4000) NULL,
    [TEST3] VARCHAR(9) NULL,
    [SRLNO1] DECIMAL(38) NULL
);

-- ==========================================
-- INDEXES FOR MASTER MODULE
-- ==========================================

CREATE INDEX [IDX_SKILL_MAST_SKL_TYP] ON [SKILL_MAST]([SK_SKL_TYP]);
CREATE INDEX [IDX_TRAIN_MAST_GRP_COD] ON [TRAIN_MAST]([TR_GRP_COD]);
CREATE INDEX [IDX_FUNCTION_MAST_GRP_COD] ON [FUNCTION_MAST]([FN_GRP_COD]);
CREATE INDEX [IDX_JOB_MAST_CAT_COD] ON [JOB_MAST]([JB_CAT_COD]);
CREATE INDEX [IDX_COMP_FINYEAR_STR_DAT] ON [COMP_FINYEAR]([AC_STR_DAT]);

PRINT 'Master Module Schema created successfully.';
GO
