// <auto-generated />
using System;
using EmployeeService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeService.Infrastructure.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20260316081830_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeService.Domain.Entities.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CTCEffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CostCenterId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("EmployeeSystemId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastCTCModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("Email");

                    b.HasIndex("EmployeeCode");

                    b.HasIndex("EmployeeSystemId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeService.Domain.Entities.SalaryIncrementLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApprovalComments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("ApprovedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ApprovedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("EmployeeSystemId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Approved");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveDate");

                    b.HasIndex("EmployeeSystemId");

                    b.HasIndex("Status");

                    b.HasIndex("EmployeeSystemId", "EffectiveDate");

                    b.ToTable("SalaryIncrementLogs");
                });

            modelBuilder.Entity("EmployeeService.Domain.Entities.Employee", b =>
                {
                    b.OwnsOne("EmployeeService.Domain.ValueObjects.Money", "BasicSalary", b1 =>
                        {
                            b1.Property<long>("EmployeeId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 2)
                                .HasColumnType("decimal(19,2)")
                                .HasColumnName("BasicSalary");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasDefaultValue("INR");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("EmployeeService.Domain.ValueObjects.Money", "GrossCTC", b1 =>
                        {
                            b1.Property<long>("EmployeeId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 2)
                                .HasColumnType("decimal(19,2)")
                                .HasColumnName("GrossCTC");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasDefaultValue("INR");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("BasicSalary")
                        .IsRequired();

                    b.Navigation("GrossCTC")
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeService.Domain.Entities.SalaryIncrementLog", b =>
                {
                    b.OwnsOne("EmployeeService.Domain.ValueObjects.Money", "NewCTC", b1 =>
                        {
                            b1.Property<long>("SalaryIncrementLogId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 2)
                                .HasColumnType("decimal(19,2)")
                                .HasColumnName("NewCTC");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasDefaultValue("INR");

                            b1.HasKey("SalaryIncrementLogId");

                            b1.ToTable("SalaryIncrementLogs");

                            b1.WithOwner()
                                .HasForeignKey("SalaryIncrementLogId");
                        });

                    b.OwnsOne("EmployeeService.Domain.ValueObjects.Money", "OldCTC", b1 =>
                        {
                            b1.Property<long>("SalaryIncrementLogId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 2)
                                .HasColumnType("decimal(19,2)")
                                .HasColumnName("OldCTC");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasDefaultValue("INR");

                            b1.HasKey("SalaryIncrementLogId");

                            b1.ToTable("SalaryIncrementLogs");

                            b1.WithOwner()
                                .HasForeignKey("SalaryIncrementLogId");
                        });

                    b.OwnsOne("EmployeeService.Domain.ValueObjects.Percentage", "IncrementPercentage", b1 =>
                        {
                            b1.Property<long>("SalaryIncrementLogId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Value")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("IncrementPercentage");

                            b1.HasKey("SalaryIncrementLogId");

                            b1.ToTable("SalaryIncrementLogs");

                            b1.WithOwner()
                                .HasForeignKey("SalaryIncrementLogId");
                        });

                    b.Navigation("IncrementPercentage")
                        .IsRequired();

                    b.Navigation("NewCTC")
                        .IsRequired();

                    b.Navigation("OldCTC")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
