-- ==========================================
-- Database: CALENDARDB
-- Module: Calendar and Shift Management System
-- Generated Module Script
-- ==========================================

USE master;
GO

-- ==========================================
-- PHASE 1: Database Creation
-- ==========================================
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'CALENDARDB')
BEGIN
    CREATE DATABASE [CALENDARDB];
    PRINT '+ CALENDARDB created';
END
ELSE
    PRINT '= CALENDARDB already exists';
GO

ALTER DATABASE [CALENDARDB] SET READ_COMMITTED_SNAPSHOT ON;
GO

PRINT '=== PHASE 1 COMPLETE: Database Created ===';
GO

-- ==========================================
-- PHASE 2: Table Definitions
-- ==========================================
USE CALENDARDB;
GO

-- Table: CALENDAR_MASTER - Calendar Master Information
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CALENDAR_MASTER]') AND type = 'U')
BEGIN
CREATE TABLE [CALENDAR_MASTER] (
    [CALENDAR_ID] INT NOT NULL,
    [CALENDAR_NAME] VARCHAR(255) NOT NULL,
    [CALENDAR_UNITID] INT NOT NULL,
    [CALENDAR_EFFDATE] DATETIME2(3) NOT NULL,
    [CALENDAR_CLSDATE] DATETIME2(3) NULL,
    [CALENDAR_STATUS] CHAR(1) NOT NULL,
    [CALENDAR_LASTMODIFIEDBY] BIGINT NOT NULL,
    [CALENDAR_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_CALENDAR_MASTER] PRIMARY KEY ([CALENDAR_ID]),
    CONSTRAINT [UQ_CALENDAR_NAME] UNIQUE ([CALENDAR_NAME])
);
    PRINT '+ CALENDAR_MASTER created';
END
ELSE
    PRINT '= CALENDAR_MASTER already exists';
GO

-- Table: CALENDAR_UNITMAP - Calendar Unit Mapping
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CALENDAR_UNITMAP]') AND type = 'U')
BEGIN
CREATE TABLE [CALENDAR_UNITMAP] (
    [CALUNIT_ID] INT NOT NULL,
    [CALUNIT_CALENID] INT NOT NULL,
    [CALUNIT_UNITID] INT NOT NULL,
    [CALUNIT_EFFDATE] DATETIME2(3) NOT NULL,
    [CALUNIT_CLSDATE] DATETIME2(3) NULL,
    [CALUNIT_LASTMODIFIEDBY] BIGINT NOT NULL,
    [CALUNIT_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_CALENDAR_UNITMAP] PRIMARY KEY ([CALUNIT_ID]),
    CONSTRAINT [FK_CALUNIT_CALENID] FOREIGN KEY ([CALUNIT_CALENID]) REFERENCES [CALENDAR_MASTER]([CALENDAR_ID])
);
    PRINT '+ CALENDAR_UNITMAP created';
END
ELSE
    PRINT '= CALENDAR_UNITMAP already exists';
GO

-- Table: CALENDAR_ROUNDRANGE - Calendar Round Range
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CALENDAR_ROUNDRANGE]') AND type = 'U')
BEGIN
CREATE TABLE [CALENDAR_ROUNDRANGE] (
    [CALROUND_ID] INT NOT NULL,
    [CALROUND_CALENID] INT NOT NULL,
    [CALROUND_ROUNDNO] INT NOT NULL,
    [CALROUND_ROUNDFROM] INT NOT NULL,
    [CALROUND_ROUNDTO] INT NOT NULL,
    [CALROUND_WORKING] INT NOT NULL,
    [CALROUND_LASTMODIFIEDBY] BIGINT NOT NULL,
    [CALROUND_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_CALENDAR_ROUNDRANGE] PRIMARY KEY ([CALROUND_ID]),
    CONSTRAINT [FK_CALROUND_CALENID] FOREIGN KEY ([CALROUND_CALENID]) REFERENCES [CALENDAR_MASTER]([CALENDAR_ID])
);
    PRINT '+ CALENDAR_ROUNDRANGE created';
END
ELSE
    PRINT '= CALENDAR_ROUNDRANGE already exists';
GO

-- Table: CALENDAR_GRACERANGE - Calendar Grace Range
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CALENDAR_GRACERANGE]') AND type = 'U')
BEGIN
CREATE TABLE [CALENDAR_GRACERANGE] (
    [CALGRACE_ID] INT NOT NULL,
    [CALGRACE_CALENID] INT NOT NULL,
    [CALGRACE_GRACEID] INT NOT NULL,
    [CALGRACE_GRACETIME] INT NOT NULL,
    [CALGRACE_LASTMODIFIEDBY] BIGINT NOT NULL,
    [CALGRACE_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_CALENDAR_GRACERANGE] PRIMARY KEY ([CALGRACE_ID]),
    CONSTRAINT [FK_CALGRACE_CALENID] FOREIGN KEY ([CALGRACE_CALENID]) REFERENCES [CALENDAR_MASTER]([CALENDAR_ID])
);
    PRINT '+ CALENDAR_GRACERANGE created';
END
ELSE
    PRINT '= CALENDAR_GRACERANGE already exists';
GO

-- Table: HOLIDAY_MASTER - Holiday Master Information
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HOLIDAY_MASTER]') AND type = 'U')
BEGIN
CREATE TABLE [HOLIDAY_MASTER] (
    [HOLIDAY_ID] INT NOT NULL,
    [HOLIDAY_DATE] DATETIME2(3) NOT NULL,
    [HOLIDAY_DESCRIPTION] VARCHAR(255) NOT NULL,
    [HOLIDAY_TYPE] CHAR(1) NOT NULL,
    [HOLIDAY_UNIT] INT NULL,
    [HOLIDAY_LASTMODIFIEDBY] BIGINT NOT NULL,
    [HOLIDAY_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_HOLIDAY_MASTER] PRIMARY KEY ([HOLIDAY_ID])
);
    PRINT '+ HOLIDAY_MASTER created';
END
ELSE
    PRINT '= HOLIDAY_MASTER already exists';
GO

-- Table: SHIFT_MASTER - Shift Master Information
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SHIFT_MASTER]') AND type = 'U')
BEGIN
CREATE TABLE [SHIFT_MASTER] (
    [SHIFT_ID] INT NOT NULL,
    [SHIFT_CODE] VARCHAR(20) NOT NULL,
    [SHIFT_NAME] VARCHAR(255) NOT NULL,
    [SHIFT_INTIME] TIME NOT NULL,
    [SHIFT_OUTTIME] TIME NOT NULL,
    [SHIFT_DURATION] DECIMAL(5,2) NOT NULL,
    [SHIFT_LASTMODIFIEDBY] BIGINT NOT NULL,
    [SHIFT_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_SHIFT_MASTER] PRIMARY KEY ([SHIFT_ID]),
    CONSTRAINT [UQ_SHIFT_CODE] UNIQUE ([SHIFT_CODE])
);
    PRINT '+ SHIFT_MASTER created';
END
ELSE
    PRINT '= SHIFT_MASTER already exists';
GO

-- Table: SHIFT_TIMEMASTER - Shift Time Details
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SHIFT_TIMEMASTER]') AND type = 'U')
BEGIN
CREATE TABLE [SHIFT_TIMEMASTER] (
    [SHIFTTIME_ID] INT NOT NULL,
    [SHIFTTIME_SHIFTID] INT NOT NULL,
    [SHIFTTIME_INTIME] TIME NOT NULL,
    [SHIFTTIME_OUTTIME] TIME NOT NULL,
    [SHIFTTIME_LASTMODIFIEDBY] BIGINT NOT NULL,
    [SHIFTTIME_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_SHIFT_TIMEMASTER] PRIMARY KEY ([SHIFTTIME_ID]),
    CONSTRAINT [FK_SHIFTTIME_SHIFTID] FOREIGN KEY ([SHIFTTIME_SHIFTID]) REFERENCES [SHIFT_MASTER]([SHIFT_ID])
);
    PRINT '+ SHIFT_TIMEMASTER created';
END
ELSE
    PRINT '= SHIFT_TIMEMASTER already exists';
GO

-- Table: SHIFT_EXCEPTION - Shift Exception Master
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SHIFT_EXCEPTION]') AND type = 'U')
BEGIN
CREATE TABLE [SHIFT_EXCEPTION] (
    [SHIFTEXC_ID] INT NOT NULL,
    [SHIFTEXC_SHIFTID] INT NOT NULL,
    [SHIFTEXC_EFFDATE] DATETIME2(3) NOT NULL,
    [SHIFTEXC_CLSDATE] DATETIME2(3) NULL,
    [SHIFTEXC_NEWSHIFTID] INT NOT NULL,
    [SHIFTEXC_LASTMODIFIEDBY] BIGINT NOT NULL,
    [SHIFTEXC_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_SHIFT_EXCEPTION] PRIMARY KEY ([SHIFTEXC_ID]),
    CONSTRAINT [FK_SHIFTEXC_SHIFTID] FOREIGN KEY ([SHIFTEXC_SHIFTID]) REFERENCES [SHIFT_MASTER]([SHIFT_ID]),
    CONSTRAINT [FK_SHIFTEXC_NEWSHIFTID] FOREIGN KEY ([SHIFTEXC_NEWSHIFTID]) REFERENCES [SHIFT_MASTER]([SHIFT_ID])
);
    PRINT '+ SHIFT_EXCEPTION created';
END
ELSE
    PRINT '= SHIFT_EXCEPTION already exists';
GO

-- Table: PATTERN_MASTER - Attendance Pattern Master
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PATTERN_MASTER]') AND type = 'U')
BEGIN
CREATE TABLE [PATTERN_MASTER] (
    [PATTERN_ID] INT NOT NULL,
    [PATTERN_NAME] VARCHAR(100) NOT NULL,
    [PATTERN_DESCRIPTION] VARCHAR(255) NULL,
    [PATTERN_CYCLEID] INT NOT NULL,
    [PATTERN_LASTMODIFIEDBY] BIGINT NOT NULL,
    [PATTERN_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_PATTERN_MASTER] PRIMARY KEY ([PATTERN_ID]),
    CONSTRAINT [UQ_PATTERN_NAME] UNIQUE ([PATTERN_NAME])
);
    PRINT '+ PATTERN_MASTER created';
END
ELSE
    PRINT '= PATTERN_MASTER already exists';
GO

-- Table: PATTERN_DETAIL - Attendance Pattern Details
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PATTERN_DETAIL]') AND type = 'U')
BEGIN
CREATE TABLE [PATTERN_DETAIL] (
    [PATDET_ID] INT NOT NULL,
    [PATDET_PATTERNID] INT NOT NULL,
    [PATDET_DAYNO] INT NOT NULL,
    [PATDET_SHIFTID] INT NOT NULL,
    [PATDET_LASTMODIFIEDBY] BIGINT NOT NULL,
    [PATDET_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_PATTERN_DETAIL] PRIMARY KEY ([PATDET_ID]),
    CONSTRAINT [FK_PATDET_PATTERNID] FOREIGN KEY ([PATDET_PATTERNID]) REFERENCES [PATTERN_MASTER]([PATTERN_ID]),
    CONSTRAINT [FK_PATDET_SHIFTID] FOREIGN KEY ([PATDET_SHIFTID]) REFERENCES [SHIFT_MASTER]([SHIFT_ID])
);
    PRINT '+ PATTERN_DETAIL created';
END
ELSE
    PRINT '= PATTERN_DETAIL already exists';
GO

-- Create Indexes (idempotent)
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CALENDAR_MASTER_STATUS' AND object_id = OBJECT_ID('CALENDAR_MASTER'))
    CREATE INDEX [IX_CALENDAR_MASTER_STATUS] ON [CALENDAR_MASTER] ([CALENDAR_STATUS]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_HOLIDAY_MASTER_DATE' AND object_id = OBJECT_ID('HOLIDAY_MASTER'))
    CREATE INDEX [IX_HOLIDAY_MASTER_DATE] ON [HOLIDAY_MASTER] ([HOLIDAY_DATE]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_SHIFT_MASTER_CODE' AND object_id = OBJECT_ID('SHIFT_MASTER'))
    CREATE INDEX [IX_SHIFT_MASTER_CODE] ON [SHIFT_MASTER] ([SHIFT_CODE]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PATTERN_MASTER_NAME' AND object_id = OBJECT_ID('PATTERN_MASTER'))
    CREATE INDEX [IX_PATTERN_MASTER_NAME] ON [PATTERN_MASTER] ([PATTERN_NAME]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_SHIFTEXC_SHIFTID' AND object_id = OBJECT_ID('SHIFT_EXCEPTION'))
    CREATE INDEX [IX_SHIFTEXC_SHIFTID] ON [SHIFT_EXCEPTION] ([SHIFTEXC_SHIFTID]);
GO

PRINT '=== PHASE 2 COMPLETE: Tables Created ===';
GO

-- ==========================================
-- PHASE 3: Stored Procedures
-- ==========================================

-- Procedure: usp_CreateShift
CREATE OR ALTER PROCEDURE dbo.usp_CreateShift
(
    @p_Code VARCHAR(20),
    @p_Name VARCHAR(255),
    @p_InTime TIME,
    @p_OutTime TIME,
    @p_CreatedBy BIGINT,
    @p_ShiftID INT OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;
        
        IF EXISTS (SELECT 1 FROM SHIFT_MASTER WHERE SHIFT_CODE = @p_Code)
            THROW 50001, 'Shift code already exists', 1;
        
        DECLARE @Duration DECIMAL(5,2);
        SET @Duration = CAST(DATEDIFF(MINUTE, @p_InTime, @p_OutTime) AS DECIMAL(5,2)) / 60;
        
        SELECT @p_ShiftID = ISNULL(MAX(SHIFT_ID), 0) + 1 FROM SHIFT_MASTER;
        
        INSERT INTO SHIFT_MASTER
        (SHIFT_ID, SHIFT_CODE, SHIFT_NAME, SHIFT_INTIME, SHIFT_OUTTIME, SHIFT_DURATION, SHIFT_LASTMODIFIEDBY, SHIFT_LASTMODIFIEDON)
        VALUES (@p_ShiftID, @p_Code, @p_Name, @p_InTime, @p_OutTime, @Duration, @p_CreatedBy, GETDATE());
        
        COMMIT TRANSACTION;
        PRINT 'Shift created: ID = ' + CAST(@p_ShiftID AS VARCHAR);
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        RAISERROR('Shift creation failed: %s', 16, 1, ERROR_MESSAGE());
    END CATCH
END;
GO

-- Procedure: usp_CreateHoliday
CREATE OR ALTER PROCEDURE dbo.usp_CreateHoliday
(
    @p_HolidayDate DATETIME2(3),
    @p_Description VARCHAR(255),
    @p_Type CHAR(1),
    @p_CreatedBy BIGINT,
    @p_HolidayID INT OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;
        
        IF @p_Type NOT IN ('N', 'O')
            THROW 50002, 'Holiday type must be N (National) or O (Optional)', 1;
        
        SELECT @p_HolidayID = ISNULL(MAX(HOLIDAY_ID), 0) + 1 FROM HOLIDAY_MASTER;
        
        INSERT INTO HOLIDAY_MASTER
        (HOLIDAY_ID, HOLIDAY_DATE, HOLIDAY_DESCRIPTION, HOLIDAY_TYPE, HOLIDAY_LASTMODIFIEDBY, HOLIDAY_LASTMODIFIEDON)
        VALUES (@p_HolidayID, @p_HolidayDate, @p_Description, @p_Type, @p_CreatedBy, GETDATE());
        
        COMMIT TRANSACTION;
        PRINT 'Holiday created: ID = ' + CAST(@p_HolidayID AS VARCHAR);
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        RAISERROR('Holiday creation failed: %s', 16, 1, ERROR_MESSAGE());
    END CATCH
END;
GO

PRINT '=== PHASE 3 COMPLETE: Procedures Created ===';
GO

-- ==========================================
-- PHASE 4: Verification Views
-- ==========================================
IF EXISTS (SELECT 1 FROM sys.views WHERE name = 'vw_CalendarDB_Status')
    DROP VIEW vw_CalendarDB_Status;
GO

CREATE VIEW vw_CalendarDB_Status AS
SELECT 
    'CALENDARDB' AS DatabaseName,
    'Calendar and Shift Management Module' AS ModuleDescription,
    (SELECT COUNT(*) FROM CALENDAR_MASTER) AS Calendars,
    (SELECT COUNT(*) FROM HOLIDAY_MASTER) AS Holidays,
    (SELECT COUNT(*) FROM SHIFT_MASTER) AS Shifts,
    (SELECT COUNT(*) FROM PATTERN_MASTER) AS Patterns,
    GETDATE() AS LastChecked;
GO

PRINT '=== PHASE 4 COMPLETE: Views Created ===';
GO

-- ==========================================
-- PHASE 5: Final Verification
-- ==========================================
PRINT '=== PHASE 5: FINAL VERIFICATION ===';
SELECT 'System Tables' AS Object_Type, COUNT(*) AS Count FROM sys.tables;
SELECT 'Indexes' AS Object_Type, COUNT(*) AS Count FROM sys.indexes WHERE object_id > 0;
SELECT 'Procedures' AS Object_Type, COUNT(*) AS Count FROM sys.objects WHERE type = 'P';
SELECT 'Views' AS Object_Type, COUNT(*) AS Count FROM sys.views;

PRINT '======================================';
PRINT 'CALENDARDB DEPLOYMENT COMPLETE';
PRINT '======================================';
PRINT 'Database: CALENDARDB';
PRINT 'Tables: 10';
PRINT 'Indexes: 5';
PRINT 'Procedures: 2';
PRINT 'Views: 1';
PRINT 'Status: READY FOR DEPLOYMENT';
PRINT '======================================';
GO
