apiVersion: v1
kind: Secret
metadata:
  name: sci-erp-secrets
  namespace: sci-erp
type: Opaque
stringData:
  db-connection-string: "Server=sqlserver-service;Database=SCIDB;User Id=sa;Password=SciDb@Str0ngP@ss!;TrustServerCertificate=true;Encrypt=true"
  jwt-secret: "YourSuperSecretKeyThatIsAtLeast32Characters!"
  rabbitmq-user: "sci_admin"
  rabbitmq-password: "SciRabbit@2026!"
  sa-password: "SciDb@Str0ngP@ss!"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sci-erp-config
  namespace: sci-erp
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  RABBITMQ_HOSTNAME: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: "sci_vhost"
  JWT_ISSUER: "ERPMicroservice"
  JWT_AUDIENCE: "ERPMicroservice"
