<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-StipendService.Functions-51aa4a65-9d9a-4b0f-aaee-d7bae7d762a6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StipendService.Application\StipendService.Application.csproj" />
    <ProjectReference Include="..\StipendService.Infrastructure\StipendService.Infrastructure.csproj" />
  </ItemGroup>
</Project>
