-- Module: Reporting
USE DDDB;
GO

-- Table: TEMP_APPRAISEEGOAL_CUR
CREATE TABLE [TEMP_APPRAISEEGOAL_CUR] (
    [AG_REQ_NUM] DECIMAL(38) NULL,
    [AG_SRL_NUM] DECIMAL(38) NULL,
    [AG_PER_DES] VARCHAR(4000) NULL,
    [AG_UNT_FRM] VARCHAR(20) NULL,
    [AG_UNT_TO] VARCHAR(20) NULL,
    [AG_APP_RMK] VARCHAR(4000) NULL,
    [AG_CAN_RMK] VARCHAR(4000) NULL,
    [AG_USR_ID] VARCHAR(50) NULL,
    [AG_WEIGHTAGE] DECIMAL(38) NULL,
    [AG_FIN_STR] DATETIME2(3) NULL,
    [AG_FIN_END] DATETIME2(3) NULL,
    [AG_PIN_NUM] DECIMAL(38) NULL,
    [AG_APS_STS] CHAR(1) NULL,
    [AG_ACH] VARCHAR(4000) NULL,
    [AG_DIFF] VARCHAR(4000) NULL,
    [AG_CATEGORY] VARCHAR(100) NULL,
    [AG_UOM] VARCHAR(65) NULL,
    [AG_MOD_SRLNO] DECIMAL(38) NULL,
    [AG_EXPCOD] VARCHAR(3) NULL,
    [AG_GOL_FLG] VARCHAR(3) NULL,
    [AG_ACCOUNTABILITYID] DECIMAL(38) NULL
);



-- Table: TEMP_APPRAISESLFPER
CREATE TABLE [TEMP_APPRAISESLFPER] (
    [AP_REQ_NUM] DECIMAL(38) NOT NULL,
    [AP_PER_SRL] DECIMAL(38) NOT NULL,
    [AP_PER_DES] VARCHAR(4000) NULL,
    [AP_PER_RAT] VARCHAR(50) NULL,
    [AP_UNT_FRO] VARCHAR(50) NULL,
    [AP_UNT_TO] VARCHAR(50) NULL,
    [AP_UNT_ACT] VARCHAR(50) NULL,
    [AP_PER_RMK] VARCHAR(4000) NULL,
    [AP_ASS_WEIGHTAGE] DECIMAL(38) NULL,
    [AP_CAN_DAT] DATETIME2(3) NULL,
    [AP_APP_ID] VARCHAR(30) NULL,
    [AP_APP_NUM] DECIMAL(38) NULL,
    [AP_CAN_REM] VARCHAR(4000) NULL,
    [AP_UNT_MSR] VARCHAR(65) NULL,
    [AP_PER_RAT1] VARCHAR(50) NULL,
    [AP_PER_RMK1] VARCHAR(4000) NULL,
    [AP_PER_CAT] VARCHAR(50) NULL,
    [AP_PER_RATING] DECIMAL(38) NULL,
    [AP_PERF_RATING] DECIMAL(38) NULL,
    [AP_MEAN_RATING] DECIMAL(38) NULL,
    [AP_APPPERF_RATING] DECIMAL(38) NULL,
    [AP_APPMEAN_RATING] DECIMAL(38) NULL,
    [AP_MEAN_REMARKS] VARCHAR(4000) NULL,
    [AP_APPMEAN_REMARKS] VARCHAR(4000) NULL
);



-- Table: TEMP_CONSPER
CREATE TABLE [TEMP_CONSPER] (
    [COL1] VARCHAR(4000) NULL,
    [COL2] VARCHAR(4000) NULL,
    [COL3] VARCHAR(4000) NULL,
    [COL4] VARCHAR(4000) NULL,
    [COL5] VARCHAR(4000) NULL,
    [COL6] VARCHAR(4000) NULL,
    [COL7] VARCHAR(4000) NULL,
    [COL8] VARCHAR(4000) NULL,
    [COL9] VARCHAR(4000) NULL,
    [COL10] VARCHAR(4000) NULL,
    [COL11] VARCHAR(4000) NULL,
    [COL12] VARCHAR(4000) NULL,
    [COL13] VARCHAR(4000) NULL,
    [COL14] DECIMAL(38) NULL,
    [COL15] VARCHAR(4000) NULL,
    [COL16] VARCHAR(4000) NULL
);



-- Table: TEMP_DDRATING
CREATE TABLE [TEMP_DDRATING] (
    [USER_ID] VARCHAR(100) NULL,
    [USER_PINUM] DECIMAL(38) NULL,
    [BUS_COD] VARCHAR(100) NULL,
    [BUS_NAM] VARCHAR(100) NULL,
    [UNIT_COD] VARCHAR(100) NULL,
    [UNIT_NAM] VARCHAR(100) NULL,
    [VTC_RATING1] DECIMAL(38) NULL,
    [VTC_RATING2] DECIMAL(38) NULL,
    [VTC_RATING3] DECIMAL(38) NULL,
    [VTC_RATING4] DECIMAL(38) NULL,
    [VTC_RATING5] DECIMAL(38) NULL,
    [VTC_TOT] DECIMAL(38) NULL,
    [VTC_RAT1PER] DECIMAL(38) NULL,
    [VTC_RAT2PER] DECIMAL(38) NULL,
    [VTC_RAT4PER] DECIMAL(38) NULL,
    [VTC_RAT3PER] DECIMAL(38) NULL,
    [VTC_RAT5PER] DECIMAL(38) NULL,
    [UNI_COD] VARCHAR(100) NULL,
    [BUSI_COD] VARCHAR(100) NULL,
    [VTC_TOTPER] DECIMAL(38) NULL
);



-- Table: TEMP_GETAPPRAISEFORPROCESS
CREATE TABLE [TEMP_GETAPPRAISEFORPROCESS] (
    [TM_REQ_NUM] DECIMAL(38) NULL  -- Request Number,
    [TM_STS_DES] VARCHAR(30) NULL  -- Status Desc,
    [TM_USR_NAM] VARCHAR(25) NULL  -- User Name,
    [TM_SUP_NAM] VARCHAR(25) NULL  -- Supervisor Name,
    [TM_GRP_COD] VARCHAR(7) NULL  -- Group Code
);



-- Table: TEMP_GETAPPRAISELIST
CREATE TABLE [TEMP_GETAPPRAISELIST] (
    [TM_REQ_NUM] DECIMAL(38) NULL,
    [TM_USR_NAM] VARCHAR(70) NULL,
    [TM_STS_DES] VARCHAR(100) NULL,
    [TM_NUM_DAT] VARCHAR(16) NULL,
    [TM_FIN_PRD] VARCHAR(22) NULL,
    [TM_USR_ID] VARCHAR(30) NULL,
    [TM_ST_FYR] DATETIME2(3) NULL,
    [TM_ED_FYR] DATETIME2(3) NULL,
    [TM_EMP_NUM] DECIMAL(38) NULL,
    [TM_UNT_COD] VARCHAR(3) NULL,
    [TM_GRD_COD] VARCHAR(10) NULL,
    [TM_AC_YEAR] VARCHAR(7) NULL,
    [TM_DD_TYPE] VARCHAR(10) NULL,
    [TM_COMPFLG] VARCHAR(1) NULL
);



-- Table: TEMP_GETAPPRAISELIST1
CREATE TABLE [TEMP_GETAPPRAISELIST1] (
    [TM_REQ_NUM] DECIMAL(38) NULL,
    [TM_USR_NAM] VARCHAR(70) NULL,
    [TM_STS_DES] VARCHAR(100) NULL,
    [TM_FIN_PRD] VARCHAR(22) NULL,
    [TM_USR_ID] VARCHAR(30) NULL,
    [TM_EMP_NUM] DECIMAL(38) NULL,
    [TM_UNT_COD] VARCHAR(3) NULL,
    [TM_STS_CODE] CHAR(2) NULL,
    [TM_PIN_NUM] DECIMAL(38) NULL
);



-- Table: TEMP_GETAPPRAISELIST11
CREATE TABLE [TEMP_GETAPPRAISELIST11] (
    [TM_REQ_NUM] DECIMAL(38) NULL,
    [TM_USR_NAM] VARCHAR(70) NULL,
    [TM_STS_DES] VARCHAR(100) NULL,
    [TM_NUM_DAT] VARCHAR(16) NULL,
    [TM_FIN_PRD] VARCHAR(22) NULL,
    [TM_USR_ID] VARCHAR(30) NULL,
    [TM_ST_FYR] DATETIME2(3) NULL,
    [TM_ED_FYR] DATETIME2(3) NULL,
    [TM_EMP_NUM] DECIMAL(38) NULL,
    [TM_UNT_COD] VARCHAR(3) NULL,
    [TM_GRD_COD] VARCHAR(10) NULL,
    [TM_AC_YEAR] VARCHAR(7) NULL,
    [TM_DD_TYPE] VARCHAR(10) NULL
);



-- Table: TEMP_GETAPPRAISELIST_BK
CREATE TABLE [TEMP_GETAPPRAISELIST_BK] (
    [TM_REQ_NUM] DECIMAL(38) NULL,
    [TM_USR_NAM] VARCHAR(70) NULL,
    [TM_STS_DES] VARCHAR(100) NULL,
    [TM_NUM_DAT] VARCHAR(16) NULL,
    [TM_FIN_PRD] VARCHAR(22) NULL,
    [TM_USR_ID] VARCHAR(30) NULL,
    [TM_ST_FYR] DATETIME2(3) NULL,
    [TM_ED_FYR] DATETIME2(3) NULL,
    [TM_EMP_NUM] DECIMAL(38) NULL,
    [TM_UNT_COD] VARCHAR(3) NULL,
    [TM_GRD_COD] VARCHAR(10) NULL,
    [TM_AC_YEAR] VARCHAR(7) NULL,
    [TM_DD_TYPE] VARCHAR(10) NULL,
    [TM_COMPFLG] VARCHAR(1) NULL
);



-- Table: TEMP_LET
CREATE TABLE [TEMP_LET] (
    [EMPNAME] VARCHAR(4000) NULL,
    [OFFNAME] VARCHAR(65) NULL,
    [BUSINESS_SHTNAME] VARCHAR(200) NULL,
    [UNIT_SHTNAME] VARCHAR(200) NULL,
    [GRADE_NAME] VARCHAR(50) NULL,
    [REQNUM] DECIMAL(38) NULL,
    [EM_REP_UNT] CHAR(3) NULL,
    [LET_ID] DECIMAL(38) NULL,
    [TRAININGID] DECIMAL(38) NULL,
    [COURSE_NAME] VARCHAR(65) NULL,
    [LET_SUBID] DECIMAL(38) NULL,
    [EM_PIN_NUM] DECIMAL(38) NULL,
    [LET_DEV_AREA] VARCHAR(2000) NULL,
    [LET_SPECIFIC_NEED] VARCHAR(2000) NULL,
    [TYPE] VARCHAR(8) NULL,
    [LOCATION_NAME] VARCHAR(200) NULL,
    [STRDATE] VARCHAR(213) NULL,
    [USR_PINUM] DECIMAL(38) NULL,
    [LET_REMARKS] VARCHAR(200) NULL
);



-- Table: TEMP_LET09
CREATE TABLE [TEMP_LET09] (
    [EMPNAME] VARCHAR(4000) NULL,
    [OFFNAME] VARCHAR(65) NULL,
    [BUSINESS_SHTNAME] VARCHAR(200) NULL,
    [UNIT_SHTNAME] VARCHAR(200) NULL,
    [GRADE_NAME] VARCHAR(50) NULL,
    [REQNUM] DECIMAL(38) NULL,
    [EM_REP_UNT] CHAR(3) NULL,
    [LET_ID] DECIMAL(38) NULL,
    [TRAININGID] DECIMAL(38) NULL,
    [COURSE_NAME] VARCHAR(65) NULL,
    [LET_SUBID] DECIMAL(38) NULL,
    [EM_PIN_NUM] DECIMAL(38) NULL,
    [LET_DEV_AREA] VARCHAR(2000) NULL,
    [LET_SPECIFIC_NEED] VARCHAR(2000) NULL,
    [TYPE] VARCHAR(8) NULL,
    [LOCATION_NAME] VARCHAR(200) NULL,
    [STRDATE] VARCHAR(213) NULL,
    [USR_PINUM] DECIMAL(38) NULL
);



-- Table: TEMP_PROBDATA
CREATE TABLE [TEMP_PROBDATA] (
    [USR_ID] VARCHAR(4000) NULL,
    [PIN_NUM] VARCHAR(4000) NULL,
    [APP_ID] VARCHAR(4000) NULL,
    [APP_NUM] VARCHAR(4000) NULL,
    [QTN_NUM] VARCHAR(4000) NULL,
    [QTN_NAM] VARCHAR(4000) NULL,
    [ANS_NAM] VARCHAR(4000) NULL,
    [STATUS] VARCHAR(4000) NULL,
    [REQ_NUM] DECIMAL(38) NULL
);



-- Table: TEMP_PROBTRACKER
CREATE TABLE [TEMP_PROBTRACKER] (
    [EMP_ID] DECIMAL(38) NULL,
    [EMP_NAME] VARCHAR(200) NULL,
    [DOJ] VARCHAR(100) NULL,
    [CONFIR_DUEDATE] VARCHAR(100) NULL,
    [REVIEWER_NAME] VARCHAR(100) NULL,
    [PROB_STATUS] VARCHAR(200) NULL,
    [APPRAISER_NAM] VARCHAR(200) NULL,
    [REQ_NUM] DECIMAL(38) NULL,
    [GOAL_NUM] DECIMAL(38) NULL,
    [USER_ID] DECIMAL(38) NULL,
    [EMP_NUM] DECIMAL(38) NULL,
    [UNT_COD] VARCHAR(10) NULL,
    [BUS_COD] VARCHAR(20) NULL  -- Business Code
);



-- Table: TEMP_QUES_ROLE
CREATE TABLE [TEMP_QUES_ROLE] (
    [RQ_QUS_NUM] DECIMAL(38) NULL  -- Question No,
    [RQ_ROL_NUM] DECIMAL(38) NULL  -- Role No
);



-- Table: TEMP_RETRIVECANCELCOMMENTS
CREATE TABLE [TEMP_RETRIVECANCELCOMMENTS] (
    [TM_QTN_NUM] DECIMAL(38) NULL,
    [TM_APP_ID] VARCHAR(25) NULL,
    [TM_CAN_REM] VARCHAR(4000) NULL,
    [TM_APP_SRL] DECIMAL(38) NULL
);



-- Table: TEMP_RETRIVECANCELQTNS
CREATE TABLE [TEMP_RETRIVECANCELQTNS] (
    [TM_REQ_NUM] DECIMAL(38) NULL,
    [TM_QTN_NUM] DECIMAL(38) NULL
);



-- Table: TEMP_RETRIVEDATA
CREATE TABLE [TEMP_RETRIVEDATA] (
    [COL1] VARCHAR(4000) NULL  -- USED TO STORE THE OUTPUTS,
    [COL2] VARCHAR(4000) NULL  -- USED TO STORE THE OUTPUTS,
    [COL3] VARCHAR(4000) NULL  -- USED TO STORE THE OUTPUTS,
    [COL4] VARCHAR(4000) NULL  -- USED TO STORE THE OUTPUTS,
    [COL5] VARCHAR(4000) NULL  -- USED TO STORE THE OUTPUTS,
    [COL6] VARCHAR(4000) NULL  -- USED TO STORE THE OUTPUTS,
    [COL7] VARCHAR(4000) NULL  -- USED TO STORE THE OUTPUTS,
    [COL8] VARCHAR(4000) NULL  -- USED TO STORE THE OUTPUTS,
    [COL9] VARCHAR(4000) NULL,
    [COL10] VARCHAR(4000) NULL,
    [COL11] VARCHAR(4000) NULL,
    [COL12] VARCHAR(4000) NULL,
    [COL13] VARCHAR(4000) NULL,
    [COL14] VARCHAR(4000) NULL,
    [COL15] VARCHAR(4000) NULL,
    [COL16] VARCHAR(4000) NULL,
    [COL17] VARCHAR(4000) NULL,
    [COL18] VARCHAR(4000) NULL,
    [COL19] VARCHAR(4000) NULL
);



-- Table: TEMP_RETRIVEDATANEW
CREATE TABLE [TEMP_RETRIVEDATANEW] (
    [COL1] DECIMAL(38) NULL,
    [COL2] VARCHAR(4000) NULL,
    [COL3] VARCHAR(4000) NULL,
    [COL4] VARCHAR(4000) NULL,
    [COL5] VARCHAR(4000) NULL,
    [COL6] VARCHAR(4000) NULL,
    [COL7] VARCHAR(4000) NULL,
    [COL8] VARCHAR(4000) NULL,
    [COL9] VARCHAR(4000) NULL,
    [COL10] VARCHAR(4000) NULL,
    [COL11] VARCHAR(4000) NULL,
    [COL12] VARCHAR(4000) NULL,
    [COL13] VARCHAR(4000) NULL
);



-- Table: TEMP_RETRIVEDATANEW09
CREATE TABLE [TEMP_RETRIVEDATANEW09] (
    [COL1] DECIMAL(38) NULL,
    [COL2] VARCHAR(4000) NULL,
    [COL3] VARCHAR(4000) NULL,
    [COL4] VARCHAR(4000) NULL,
    [COL5] VARCHAR(4000) NULL,
    [COL6] VARCHAR(4000) NULL,
    [COL7] VARCHAR(4000) NULL,
    [COL8] VARCHAR(4000) NULL,
    [COL9] VARCHAR(4000) NULL,
    [COL10] VARCHAR(4000) NULL,
    [COL11] VARCHAR(4000) NULL,
    [COL12] VARCHAR(4000) NULL,
    [COL13] VARCHAR(4000) NULL,
    [ROLE] DECIMAL(38) NULL
);



-- Table: TEMP_RETRIVEDATANEW0934
CREATE TABLE [TEMP_RETRIVEDATANEW0934] (
    [COL1] DECIMAL(38) NULL,
    [COL2] VARCHAR(4000) NULL,
    [COL3] VARCHAR(4000) NULL,
    [COL4] VARCHAR(4000) NULL,
    [COL5] VARCHAR(4000) NULL,
    [COL6] VARCHAR(4000) NULL,
    [COL7] VARCHAR(4000) NULL,
    [COL8] VARCHAR(4000) NULL,
    [COL9] VARCHAR(4000) NULL,
    [COL10] VARCHAR(4000) NULL,
    [COL11] VARCHAR(4000) NULL,
    [COL12] VARCHAR(4000) NULL,
    [COL13] VARCHAR(4000) NULL,
    [ROLE] DECIMAL(38) NULL
);



-- Table: TEMP_RETRIVEDATANEW2018
CREATE TABLE [TEMP_RETRIVEDATANEW2018] (
    [COL1] DECIMAL(38) NULL,
    [COL2] VARCHAR(4000) NULL,
    [COL3] VARCHAR(4000) NULL,
    [COL4] VARCHAR(4000) NULL,
    [COL5] VARCHAR(4000) NULL,
    [COL6] VARCHAR(4000) NULL,
    [COL7] VARCHAR(4000) NULL,
    [COL8] VARCHAR(4000) NULL,
    [COL9] VARCHAR(4000) NULL,
    [COL10] VARCHAR(4000) NULL,
    [COL11] VARCHAR(4000) NULL,
    [COL12] VARCHAR(4000) NULL,
    [COL13] VARCHAR(4000) NULL,
    [ROLE] DECIMAL(38) NULL
);



-- Table: TEMP_RETRIVEDATA_DD
CREATE TABLE [TEMP_RETRIVEDATA_DD] (
    [COL1] VARCHAR(4000) NULL,
    [COL2] VARCHAR(4000) NULL,
    [COL3] VARCHAR(4000) NULL,
    [COL4] VARCHAR(4000) NULL,
    [COL5] VARCHAR(4000) NULL,
    [COL6] VARCHAR(4000) NULL,
    [COL7] VARCHAR(4000) NULL,
    [COL8] VARCHAR(4000) NULL,
    [COL9] VARCHAR(4000) NULL,
    [COL10] VARCHAR(4000) NULL,
    [COL11] VARCHAR(4000) NULL,
    [COL12] VARCHAR(4000) NULL,
    [COL13] VARCHAR(4000) NULL,
    [SNO] DECIMAL(38) NULL,
    [COL14] VARCHAR(4000) NULL
);



-- Table: TEMP_RETRIVEDATA_TEST
CREATE TABLE [TEMP_RETRIVEDATA_TEST] (
    [COL1] DECIMAL(38) NULL,
    [COL2] VARCHAR(4000) NULL,
    [COL3] VARCHAR(4000) NULL,
    [COL4] VARCHAR(4000) NULL,
    [COL5] VARCHAR(4000) NULL,
    [COL6] VARCHAR(4000) NULL,
    [COL7] VARCHAR(4000) NULL,
    [COL8] VARCHAR(4000) NULL,
    [COL9] VARCHAR(4000) NULL,
    [COL10] VARCHAR(4000) NULL,
    [COL11] VARCHAR(4000) NULL,
    [COL12] VARCHAR(4000) NULL,
    [COL13] VARCHAR(4000) NULL
);



-- Table: TEMP_RETRIVEDELIVERY
CREATE TABLE [TEMP_RETRIVEDELIVERY] (
    [TM_QTN_NUM] DECIMAL(38) NULL,
    [TM_APP_ID] VARCHAR(25) NULL,
    [TM_DEV_REM] VARCHAR(4000) NULL,
    [TM_DEV_STS] VARCHAR(50) NULL
);



-- Table: TEM_RETRIEVEDAT1
CREATE TABLE [TEM_RETRIEVEDAT1] (
    [COL1] DECIMAL(38) NULL,
    [COL2] VARCHAR(4000) NULL,
    [COL3] VARCHAR(4000) NULL,
    [COL4] VARCHAR(4000) NULL,
    [COL5] VARCHAR(4000) NULL,
    [COL6] VARCHAR(4000) NULL,
    [COL7] VARCHAR(4000) NULL,
    [COL8] VARCHAR(4000) NULL,
    [COL9] VARCHAR(4000) NULL,
    [COL10] VARCHAR(4000) NULL,
    [COL11] VARCHAR(4000) NULL,
    [COL12] VARCHAR(4000) NULL,
    [COL13] VARCHAR(4000) NULL,
    [MODCOL] DECIMAL(38) NULL
);



-- Table: TMP_BLT
CREATE TABLE [TMP_BLT] (
    [USR_ID] VARCHAR(20) NULL,
    [EMP_NAM] VARCHAR(200) NULL,
    [PIN_NUM] DECIMAL(38) NULL
);



-- Table: TMP_CPAPPRAISERDET
CREATE TABLE [TMP_CPAPPRAISERDET] (
    [GL_GOL_NUM] DECIMAL(38) NULL,
    [STATUS_DESC] VARCHAR(100) NULL,
    [GL_STS_FLG] VARCHAR(1) NULL,
    [EMP_SYSID] DECIMAL(38) NOT NULL,
    [REPORTING_SYSID] DECIMAL(38) NOT NULL,
    [APPRAISEE_NAME] VARCHAR(65) NULL,
    [APPRAISER_NAME] VARCHAR(65) NULL,
    [APPRAISEE_EMPNUM] DECIMAL(38) NOT NULL,
    [APPRAISER_EMPNUM] DECIMAL(38) NOT NULL,
    [APPRAISEE_MAILID] VARCHAR(65) NULL,
    [APPRAISER_MAILID] VARCHAR(65) NULL,
    [APPRAISEE_UNIT] VARCHAR(3) NOT NULL,
    [REPORT_TYPE] CHAR(1) NOT NULL,
    [DDREQNUM] DECIMAL(38) NOT NULL,
    [REQ_STATUS] VARCHAR(20) NULL
);



-- Table: TMP_CPAPPRDET
CREATE TABLE [TMP_CPAPPRDET] (
    [GL_GOL_NUM] DECIMAL(38) NOT NULL,
    [STATUS_DESC] VARCHAR(50) NULL,
    [GL_STS_FLG] CHAR(1) NULL,
    [GL_PIN_NUM] DECIMAL(38) NULL,
    [APPR_USRID] VARCHAR(65) NULL,
    [APPR_EMPNUM] DECIMAL(38) NULL,
    [APPR_EMPNAM] VARCHAR(65) NULL,
    [APPR_UNT] CHAR(3) NULL,
    [REQ_STATUS] VARCHAR(20) NULL,
    [APPR_MAILID] VARCHAR(200) NULL
);



-- Table: TMP_CPBHRDET
CREATE TABLE [TMP_CPBHRDET] (
    [GL_GOL_NUM] DECIMAL(38) NULL,
    [STATUS_DESC] VARCHAR(100) NULL,
    [GL_STS_FLG] VARCHAR(1) NULL,
    [EMP_SYSID] DECIMAL(38) NOT NULL,
    [REPORTING_SYSID] DECIMAL(38) NOT NULL,
    [APPRAISEE_NAME] VARCHAR(65) NULL,
    [APPRAISER_NAME] VARCHAR(65) NULL,
    [APPRAISEE_EMPNUM] DECIMAL(38) NOT NULL,
    [APPRAISER_EMPNUM] DECIMAL(38) NOT NULL,
    [APPRAISEE_MAILID] VARCHAR(200) NULL,
    [APPRAISER_MAILID] VARCHAR(200) NULL,
    [APPRAISEE_UNIT] VARCHAR(3) NOT NULL,
    [REPORT_TYPE] CHAR(1) NOT NULL,
    [DDREQNUM] DECIMAL(38) NOT NULL,
    [BHR_BUSCOD] CHAR(9) NULL,
    [BHR_UNTCOD] CHAR(3) NULL,
    [BHR_PIN] DECIMAL(38) NULL,
    [APPRAISEE_BUS] VARCHAR(9) NULL
);



-- Table: TMP_CPDETAILS
CREATE TABLE [TMP_CPDETAILS] (
    [GL_GOL_NO] DECIMAL(38) NULL,
    [GL_SRL_NO] DECIMAL(38) NULL,
    [GL_GOL_DES] VARCHAR(4000) NULL,
    [GL_GOL_FRM] VARCHAR(20) NULL,
    [GL_GOL_TO] VARCHAR(20) NULL,
    [GL_GOL_ACH] VARCHAR(4000) NULL,
    [GL_GOL_DIFF] VARCHAR(4000) NULL,
    [GL_EXP_COD] VARCHAR(50) NULL,
    [GL_MOD_SRLNO] DECIMAL(38) NULL,
    [GL_UOM] VARCHAR(65) NULL,
    [GL_CATEGORY] VARCHAR(100) NULL,
    [GL_REMARKS] VARCHAR(4000) NULL,
    [GL_GOL_FLG] VARCHAR(3) NULL
);



-- Table: TMP_CPDETAILS4BHR
CREATE TABLE [TMP_CPDETAILS4BHR] (
    [GL_GOL_NO] DECIMAL(38) NULL,
    [GL_SRL_NO] DECIMAL(38) NULL,
    [GL_GOL_DES] VARCHAR(4000) NULL,
    [GL_GOL_FRM] VARCHAR(20) NULL,
    [GL_GOL_TO] VARCHAR(20) NULL,
    [GL_GOL_ACH] VARCHAR(4000) NULL,
    [GL_GOL_DIFF] VARCHAR(4000) NULL,
    [GL_EXP_COD] VARCHAR(50) NULL,
    [GL_MOD_SRLNO] DECIMAL(38) NULL,
    [GL_UOM] VARCHAR(65) NULL,
    [GL_CATEGORY] VARCHAR(100) NULL,
    [GL_REMARKS] VARCHAR(4000) NULL,
    [GL_GOL_FLG] VARCHAR(3) NULL,
    [GL_REM] VARCHAR(4000) NULL,
    [GL_APPRAISEE_DISCUSSION] VARCHAR(4000) NULL
);



-- Table: TMP_CPREVIEWERDET
CREATE TABLE [TMP_CPREVIEWERDET] (
    [GL_GOL_NUM] DECIMAL(38) NULL,
    [STATUS_DESC] VARCHAR(50) NULL,
    [GL_STS_FLG] VARCHAR(1) NULL,
    [EMP_SYSID] DECIMAL(38) NOT NULL,
    [REPORTING_SYSID] DECIMAL(38) NOT NULL,
    [APPRAISEE_NAME] VARCHAR(65) NULL,
    [APPRAISER_NAME] VARCHAR(65) NULL,
    [APPRAISEE_EMPNUM] DECIMAL(38) NOT NULL,
    [APPRAISER_EMPNUM] DECIMAL(38) NOT NULL,
    [APPRAISEE_MAILID] VARCHAR(200) NULL,
    [APPRAISER_MAILID] VARCHAR(200) NULL,
    [APPRAISEE_UNIT] VARCHAR(3) NOT NULL,
    [REPORT_TYPE] CHAR(1) NOT NULL,
    [DDREQNUM] DECIMAL(38) NOT NULL,
    [REQ_STATUS] VARCHAR(20) NULL
);



-- Table: TMP_DD
CREATE TABLE [TMP_DD] (
    [COMP_NUM] DECIMAL(38) NULL,
    [SRL_NUM] DECIMAL(38) NULL,
    [STR_VAL] VARCHAR(4000) NULL,
    [IND_FLG] CHAR(1) NULL
);



-- Table: TMP_DD2
CREATE TABLE [TMP_DD2] (
    [COMP_NUM] DECIMAL(38) NULL,
    [SRL_NUM] DECIMAL(38) NULL,
    [STR_VAL] VARCHAR(4000) NULL,
    [IND_FLG] CHAR(1) NULL,
    [PIN_NUM] DECIMAL(38) NULL
);



-- Table: TMP_INCLDD
CREATE TABLE [TMP_INCLDD] (
    [USR_ID] VARCHAR(20) NULL,
    [EMP_NAM] VARCHAR(200) NULL,
    [PIN_NUM] DECIMAL(38) NULL
);



-- Table: TMP_PROBMAIN
CREATE TABLE [TMP_PROBMAIN] (
    [TM_APP_ID] VARCHAR(50) NULL,
    [TM_APP_NAM] VARCHAR(100) NULL,
    [TM_PROB_STS] CHAR(1) NULL,
    [TR_REQ_NUM] DECIMAL(38) NULL,
    [TR_REQ_USR] VARCHAR(50) NULL,
    [TR_REQ_PIN] DECIMAL(38) NULL,
    [TM_STS_DEF] VARCHAR(200) NULL,
    [TM_UNTCOD] VARCHAR(200) NULL,
    [TM_EMPNO] DECIMAL(38) NULL
);



-- Table: TT
CREATE TABLE [TT] (
    [D] VARCHAR(4000) NULL
);



-- Table: TT1
CREATE TABLE [TT1] (
    [D] VARCHAR(4000) NULL
);



-- Table: TT11
CREATE TABLE [TT11] (
    [TM_REQ_NUM] DECIMAL(38) NULL,
    [TM_USR_NAM] VARCHAR(70) NULL,
    [TM_STS_DES] VARCHAR(100) NULL,
    [TM_NUM_DAT] VARCHAR(16) NULL,
    [TM_FIN_PRD] VARCHAR(22) NULL,
    [TM_USR_ID] VARCHAR(30) NULL,
    [TM_ST_FYR] VARCHAR(11) NULL,
    [TM_ED_FYR] VARCHAR(11) NULL,
    [TM_AC_YEAR] VARCHAR(7) NULL,
    [TM_EMP_NUM] DECIMAL(38) NULL,
    [TM_UNT_COD] VARCHAR(3) NULL,
    [TM_GRD_COD] VARCHAR(10) NULL,
    [TM_DD_TYPE] VARCHAR(10) NULL,
    [Status_flag] VARCHAR(4000) NULL,
    [ViewStatus_flag] VARCHAR(4000) NULL,
    [StatusCod] CHAR(1) NULL
);



-- Table: TT_APPR_BUS
CREATE TABLE [TT_APPR_BUS] (
    [TT_BUS_COD] VARCHAR(10) NULL,
    [TT_USR_COD] VARCHAR(50) NULL,
    [TT_PIN_NUM] DECIMAL(38) NULL,
    [TT_TYP_NAM] CHAR(1) NULL
);



-- Table: TT_BANDCTC
CREATE TABLE [TT_BANDCTC] (
    [BANDID] DECIMAL(38) NULL,
    [BAND_NAME] VARCHAR(20) NULL,
    [MAXCTC] DECIMAL(38) NULL,
    [MINCTC] DECIMAL(38) NULL,
    [MEDIANCTC] DECIMAL(38) NULL,
    [NOS] DECIMAL(38) NULL,
    [RND_NUM] VARCHAR(20) NULL
);



-- Table: TT_CLOB
CREATE TABLE [TT_CLOB] (
    [D] NVARCHAR(MAX) NULL
);



-- Table: TT_DATACHECK
CREATE TABLE [TT_DATACHECK] (
    [EMP_TYP] VARCHAR(20) NULL,
    [EMP_NUM] DECIMAL(38) NULL,
    [EMP_NAM] VARCHAR(65) NULL,
    [DOB_DAT] DATETIME2(3) NULL,
    [DOJ_DAT] DATETIME2(3) NULL,
    [DOC_DAT] DATETIME2(3) NULL,
    [BND_NAM] VARCHAR(50) NULL,
    [UNT_NAM] VARCHAR(50) NULL,
    [EMP_DSG] VARCHAR(200) NULL,
    [BAS_AMT] DECIMAL(38) NULL,
    [FLX_PAY] DECIMAL(38) NULL,
    [EXG_AMT] DECIMAL(38) NULL,
    [RET_AMT] DECIMAL(38) NULL,
    [CTC_AMT] DECIMAL(38) NULL,
    [USR_ID] VARCHAR(25) NULL,
    [PIN_NUM] DECIMAL(38) NULL,
    [UNT_COD] CHAR(3) NULL,
    [CIT_AMT] DECIMAL(38) NULL,
    [MIT_AMT] DECIMAL(38) NULL,
    [LEAVE_AMT] DECIMAL(38) NULL
);



-- Table: TT_DD
CREATE TABLE [TT_DD] (
    [COMP_NUM] DECIMAL(38) NULL,
    [POS_IND] VARCHAR(4000) NULL,
    [NEG_IND] VARCHAR(4000) NULL
);



-- Table: TT_DD2
CREATE TABLE [TT_DD2] (
    [COMP_NUM] DECIMAL(38) NULL,
    [POS_IND] VARCHAR(4000) NULL,
    [NEG_IND] VARCHAR(4000) NULL,
    [PIN_NUM] DECIMAL(38) NULL
);



-- Table: TT_DDRAT
CREATE TABLE [TT_DDRAT] (
    [REFNO] DECIMAL(38) NULL,
    [PROMFLG] VARCHAR(1) NULL,
    [EMP_SYSID] DECIMAL(38) NULL,
    [EMP_PIN_NO] DECIMAL(38) NULL,
    [DDENDDATE] CHAR(11) NULL,
    [DD_NEW_FLX] DECIMAL(38) NULL,
    [GRADE_ID] DECIMAL(38) NOT NULL,
    [DOJ] VARCHAR(10) NULL,
    [OLD_CTC] DECIMAL(38) NULL,
    [NEW_CTC] DECIMAL(38) NULL,
    [OLD_BASIC] DECIMAL(38) NULL,
    [NEW_BASIC] DECIMAL(38) NULL,
    [INCAMNT_DD] DECIMAL(38) NULL,
    [INCPERCENTAGE] VARCHAR(40) NULL,
    [INC_AMOUNT] DECIMAL(38) NULL,
    [USER_SYID] DECIMAL(38) NULL
);



-- Table: TT_DD_COMPENDMAST
CREATE TABLE [TT_DD_COMPENDMAST] (
    [GRADEID] VARCHAR(100) NULL,
    [CM_CPD_NUM] DECIMAL(38) NOT NULL,
    [CM_CPD_NAM] VARCHAR(4000) NOT NULL,
    [CM_CPD_REM] VARCHAR(4000) NULL,
    [CM_JOB_COD] DECIMAL(38) NULL,
    [CM_POS_IND] VARCHAR(4000) NULL,
    [CM_NEG_IND] VARCHAR(4000) NULL,
    [CM_CPD_SLF] VARCHAR(4000) NULL,
    [CM_CPD_TYPE] VARCHAR(10) NULL
);



-- Table: TT_DD_COMPETENCY_IND
CREATE TABLE [TT_DD_COMPETENCY_IND] (
    [SRL_NO] DECIMAL(38) NULL,
    [BAND] VARCHAR(50) NULL,
    [COMP_NUM] DECIMAL(38) NULL,
    [IND_FLAG] CHAR(1) NULL,
    [IND_DEFN] VARCHAR(4000) NULL
);



-- Table: TT_GOALAPPRAISER
CREATE TABLE [TT_GOALAPPRAISER] (
    [GL_GOL_NUM] DECIMAL(38) NULL,
    [AP_PIN_NUM] DECIMAL(38) NULL,
    [EM_EMP_NAM] VARCHAR(65) NULL,
    [AP_SRL_NUM] DECIMAL(38) NULL,
    [APPR_CNT] DECIMAL(38) NULL
);



-- Table: TT_HORIZ
CREATE TABLE [TT_HORIZ] (
    [RUNEMPSYSID] DECIMAL(38) NULL,
    [EMPSYSID] DECIMAL(38) NULL,
    [PINNO] DECIMAL(38) NULL,
    [BAND] VARCHAR(50) NULL,
    [BANDLEVEL] VARCHAR(50) NULL,
    [EMPNAME] VARCHAR(200) NULL,
    [UNIT] VARCHAR(50) NULL,
    [BUSINESS] VARCHAR(50) NULL,
    [LASTPROMOTED1] DATETIME2(3) NULL,
    [LASTPROMOTED2] DATETIME2(3) NULL,
    [SRFEXP] DECIMAL(38) NULL,
    [PRVEXP] DECIMAL(38) NULL,
    [POINTSDD] DECIMAL(38) NULL,
    [CDATE] DATETIME2(3) NULL,
    [DOJ] DATETIME2(3) NULL,
    [RATINGOLD] VARCHAR(200) NULL,
    [GRADEID] DECIMAL(38) NULL,
    [POINTSOLD] DECIMAL(38) NULL,
    [DDLAST] DATETIME2(3) NULL,
    [POINTSNEW] DECIMAL(38) NULL,
    [DDRATING] VARCHAR(5) NULL,
    [PROMSCORE] DECIMAL(38) NULL,
    [PROMSTATUS] CHAR(1) NULL,
    [PROMLEVEL] DECIMAL(38) NULL,
    [PROMLEVELNAME] VARCHAR(50) NULL,
    [LEVELID] DECIMAL(38) NULL,
    [DDRATINGCHR] VARCHAR(5) NULL,
    [LASTHORIZDATE] DATETIME2(3) NULL
);



-- Table: TT_HORIZONTAL
CREATE TABLE [TT_HORIZONTAL] (
    [RUNEMPSYSID] DECIMAL(38) NULL,
    [EMPSYSID] DECIMAL(38) NULL,
    [PINNO] DECIMAL(38) NULL,
    [BAND] VARCHAR(50) NULL,
    [BANDLEVEL] VARCHAR(50) NULL,
    [EMPNAME] VARCHAR(200) NULL,
    [UNIT] VARCHAR(50) NULL,
    [BUSINESS] VARCHAR(50) NULL,
    [LASTPROMOTED1] DATETIME2(3) NULL,
    [LASTPROMOTED2] DATETIME2(3) NULL,
    [SRFEXP] DECIMAL(38) NULL,
    [PRVEXP] DECIMAL(38) NULL,
    [POINTSDD] DECIMAL(38) NULL,
    [CDATE] DATETIME2(3) NULL,
    [DOJ] DATETIME2(3) NULL,
    [RATINGOLD] VARCHAR(200) NULL,
    [GRADEID] DECIMAL(38) NULL,
    [POINTSOLD] DECIMAL(38) NULL,
    [DDLAST] DATETIME2(3) NULL,
    [POINTSNEW] DECIMAL(38) NULL,
    [DDRATING] VARCHAR(5) NULL,
    [PROMSCORE] DECIMAL(38) NULL,
    [PROMSTATUS] CHAR(1) NULL,
    [PROMLEVEL] DECIMAL(38) NULL,
    [PROMLEVELNAME] VARCHAR(50) NULL,
    [LEVELID] DECIMAL(38) NULL,
    [DDRATINGCHR] VARCHAR(5) NULL,
    [LASTHORIZDATE] DATETIME2(3) NULL,
    [MAXLEVEL] CHAR(1) NULL,
    [REQNUM] DECIMAL(38) NULL,
    [REV_CONCERN] CHAR(1) NULL,
    [MINLEVEL] DECIMAL(38) NULL,
    [FIRSTYEARDD] VARCHAR(20) NULL
);



-- Table: TT_RATINGDET
CREATE TABLE [TT_RATINGDET] (
    [RATING] VARCHAR(30) NULL,
    [COUNT] DECIMAL(38) NULL,
    [SORTORDER] DECIMAL(38) NULL
);



-- Table: TT_SRL_NUM
CREATE TABLE [TT_SRL_NUM] (
    [REQ_NUM] DECIMAL(38) NULL,
    [NEW_SRL] DECIMAL(38) NULL,
    [OLD_SRL] DECIMAL(38) NULL
);

