-- PFTransactionalService Migration Script
-- Creates the 5 new tables required by PFTransactionalService in PFDB
-- COMP_FINYEAR and TRANSACTION_MASTER already exist in PFDB

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'PF_ACCUMULATION')
BEGIN
    CREATE TABLE [PF_ACCUMULATION] (
        [PF_ACC_ID]           BIGINT          IDENTITY(1,1) NOT NULL,
        [EMP_SYS_ID]          BIGINT          NOT NULL,
        [MEMBER_NO]           BIGINT          NOT NULL,
        [TRUST_CODE]          NCHAR(3)        NOT NULL,
        [PF_ACC_BAL]          DECIMAL(19,0)   NOT NULL DEFAULT 0,
        [PF_EMP_CONT_TOTAL]   DECIMAL(19,0)   NOT NULL DEFAULT 0,
        [PF_ER_CONT_TOTAL]    DECIMAL(19,0)   NOT NULL DEFAULT 0,
        [PF_VOL_CONT_TOTAL]   DECIMAL(19,0)   NOT NULL DEFAULT 0,
        [PF_ACC_STATUS]       NVARCHAR(1)     NOT NULL DEFAULT 'A',
        [CREATED_BY]          BIGINT          NOT NULL,
        [CREATED_ON]          DATETIME2(3)    NOT NULL DEFAULT SYSUTCDATETIME(),
        [UPDATED_BY]          BIGINT          NULL,
        [UPDATED_ON]          DATETIME2(3)    NULL,
        CONSTRAINT [PK_PF_ACCUMULATION] PRIMARY KEY ([PF_ACC_ID])
    );
    CREATE UNIQUE INDEX [IDX_PF_ACCUMULATION_EMPSYSID] ON [PF_ACCUMULATION] ([EMP_SYS_ID]);
    CREATE INDEX [IDX_PF_ACCUMULATION_MEMBERNO] ON [PF_ACCUMULATION] ([MEMBER_NO]);
    PRINT 'Created table PF_ACCUMULATION';
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'PF_CONTRIBUTION_TXN')
BEGIN
    CREATE TABLE [PF_CONTRIBUTION_TXN] (
        [PF_TXN_ID]            BIGINT          IDENTITY(1,1) NOT NULL,
        [EMP_SYS_ID]           BIGINT          NOT NULL,
        [PF_EMP_CONTRIBUTION]  DECIMAL(19,0)   NOT NULL DEFAULT 0,
        [PF_ER_CONTRIBUTION]   DECIMAL(19,0)   NOT NULL DEFAULT 0,
        [PF_VOL_CONTRIBUTION]  DECIMAL(19,0)   NOT NULL DEFAULT 0,
        [PF_TXN_DATE]          DATETIME2(3)    NOT NULL DEFAULT SYSUTCDATETIME(),
        [PF_TXN_MONTH]         DATETIME2(3)    NOT NULL,
        [PF_TXN_STATUS]        NVARCHAR(1)     NOT NULL DEFAULT 'P',
        [CREATED_BY]           BIGINT          NOT NULL,
        [CREATED_ON]           DATETIME2(3)    NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT [PK_PF_CONTRIBUTION_TXN] PRIMARY KEY ([PF_TXN_ID])
    );
    CREATE INDEX [IDX_PF_CONTRIBUTION_TXN_EMPSYSID] ON [PF_CONTRIBUTION_TXN] ([EMP_SYS_ID]);
    CREATE INDEX [IDX_PF_CONTRIBUTION_TXN_MONTH] ON [PF_CONTRIBUTION_TXN] ([PF_TXN_MONTH]);
    PRINT 'Created table PF_CONTRIBUTION_TXN';
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'PF_SETTLEMENT')
BEGIN
    CREATE TABLE [PF_SETTLEMENT] (
        [PF_SETTLEMENT_ID]       BIGINT          IDENTITY(1,1) NOT NULL,
        [EMP_SYS_ID]             BIGINT          NOT NULL,
        [PF_SETTLEMENT_AMOUNT]   DECIMAL(19,0)   NOT NULL DEFAULT 0,
        [PF_SETTLEMENT_TYPE]     NVARCHAR(10)    NULL,
        [PF_SETTLEMENT_DATE]     DATETIME2(3)    NOT NULL DEFAULT SYSUTCDATETIME(),
        [PF_SETTLEMENT_STATUS]   NVARCHAR(1)     NOT NULL DEFAULT 'P',
        [APPROVED_BY]            BIGINT          NULL,
        [CREATED_BY]             BIGINT          NOT NULL,
        [CREATED_ON]             DATETIME2(3)    NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT [PK_PF_SETTLEMENT] PRIMARY KEY ([PF_SETTLEMENT_ID])
    );
    CREATE INDEX [IDX_PF_SETTLEMENT_EMPSYSID] ON [PF_SETTLEMENT] ([EMP_SYS_ID]);
    PRINT 'Created table PF_SETTLEMENT';
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'PF_SETTLEMENT_TXN')
BEGIN
    CREATE TABLE [PF_SETTLEMENT_TXN] (
        [PF_SETTLEMENT_TXN_ID]      BIGINT          IDENTITY(1,1) NOT NULL,
        [PF_SETTLEMENT_ID]          BIGINT          NOT NULL,
        [EMP_SYS_ID]                BIGINT          NOT NULL,
        [PF_SETTLEMENT_TXN_AMOUNT]  DECIMAL(19,0)   NOT NULL DEFAULT 0,
        [PF_SETTLEMENT_TXN_DATE]    DATETIME2(3)    NOT NULL DEFAULT SYSUTCDATETIME(),
        [PF_SETTLEMENT_TXN_STATUS]  NVARCHAR(1)     NOT NULL DEFAULT 'P',
        [CREATED_BY]                BIGINT          NOT NULL,
        [CREATED_ON]                DATETIME2(3)    NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT [PK_PF_SETTLEMENT_TXN] PRIMARY KEY ([PF_SETTLEMENT_TXN_ID])
    );
    PRINT 'Created table PF_SETTLEMENT_TXN';
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'PF_WITHDRAWAL_CERTIFICATE')
BEGIN
    CREATE TABLE [PF_WITHDRAWAL_CERTIFICATE] (
        [CERTIFICATE_ID]       BIGINT          IDENTITY(1,1) NOT NULL,
        [PF_SETTLEMENT_ID]     BIGINT          NOT NULL,
        [EMP_SYS_ID]           BIGINT          NOT NULL,
        [CERTIFICATE_AMOUNT]   DECIMAL(19,0)   NOT NULL DEFAULT 0,
        [CERTIFICATE_DATE]     DATETIME2(3)    NOT NULL DEFAULT SYSUTCDATETIME(),
        [CERTIFICATE_STATUS]   NVARCHAR(1)     NOT NULL DEFAULT 'G',
        [CREATED_BY]           BIGINT          NOT NULL,
        [CREATED_ON]           DATETIME2(3)    NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT [PK_PF_WITHDRAWAL_CERTIFICATE] PRIMARY KEY ([CERTIFICATE_ID])
    );
    PRINT 'Created table PF_WITHDRAWAL_CERTIFICATE';
END
GO
