-- Module: Promotion
USE DDDB;
GO

-- Table: DD_APPRAISALAMOUNT
CREATE TABLE [DD_APPRAISALAMOUNT] (
    [DD_SRL_NO] DECIMAL(38) NOT NULL  -- Serial No,
    [DD_BND_ID] DECIMAL(38) NULL  -- Band ID,
    [DD_BND_APR] VARCHAR(5) NULL  -- VTC Rating,
    [DD_BND_AMT] DECIMAL(38) NULL  -- Amount,
    [DD_BND_MAX] DECIMAL(38) NULL  -- Band Maximum Amount,
    [DD_BND_EFF] DATETIME2(3) NULL  -- Appraisal Period From,
    [DD_BND_END] DATETIME2(3) NULL  -- Appraisal Period To,
    [DD_BND_PER] DECIMAL(38) NULL  -- Band Percentage,
    [DD_MIN_CTC] DECIMAL(38) NULL,
    [DD_MIN_PER] DECIMAL(38) NULL,
    [DD_GRADECODE] CHAR(3) NULL,
    [DD_GRADEID] DECIMAL(38) NULL,
    [DD_MODIFIEDBY] DECIMAL(38) NULL,
    [DD_MODIFIEDON] DATETIME2(3) NULL,
    [DD_BND_MIN] DECIMAL(38) NULL,
    CONSTRAINT [PK_DD_APPRAISALAMOUNT] PRIMARY KEY ([DD_SRL_NO])
);



-- Table: DD_APPRAISALAMOUNT_LOG
CREATE TABLE [DD_APPRAISALAMOUNT_LOG] (
    [DD_SRL_NO] DECIMAL(38) NULL,
    [DD_BND_ID] DECIMAL(38) NULL,
    [DD_BND_APR] CHAR(5) NULL,
    [DD_BND_AMT] DECIMAL(38) NULL,
    [DD_BND_MAX] DECIMAL(38) NULL,
    [DD_BND_EFF] DATETIME2(3) NULL,
    [DD_BND_END] DATETIME2(3) NULL,
    [DD_BND_PER] DECIMAL(38) NULL,
    [DD_MIN_CTC] DECIMAL(38) NULL,
    [DD_MIN_PER] DECIMAL(38) NULL,
    [DD_GRADECODE] CHAR(3) NULL,
    [DD_GRADEID] DECIMAL(38) NULL,
    [DD_MODIFIEDBY] DECIMAL(38) NULL,
    [DD_MODIFIEDON] DATETIME2(3) NULL,
    [DD_BND_MIN] DECIMAL(38) NULL,
    [DD_LOGCREATEDBY] DECIMAL(38) NULL,
    [DD_LOGCREATEDON] DATETIME2(3) NULL
);



-- Table: DD_CTGPROMOTION
CREATE TABLE [DD_CTGPROMOTION] (
    [DD_REQ_NUM] DECIMAL(38) NOT NULL,
    [DD_APPRSYSID] DECIMAL(38) NULL,
    [DD_QTNNO] DECIMAL(38) NULL,
    [DD_APPTYPE] CHAR(3) NULL,
    [DD_ANS1] VARCHAR(100) NULL,
    [DD_ANS2] VARCHAR(100) NULL,
    [DD_LEVELID] DECIMAL(38) NULL,
    [DD_NEWGRADEID] DECIMAL(38) NULL,
    [DD_LASTUPDATEDBY] DECIMAL(38) NULL,
    [DD_LASTUPDATEDON] DATETIME2(3) NULL,
    [DD_PROMO_REMARKS] VARCHAR(1000) NULL
);



-- Table: DD_GRADE_INCTYPE
CREATE TABLE [DD_GRADE_INCTYPE] (
    [DD_GRADEID] DECIMAL(38) NULL,
    [DD_FORMCAT] VARCHAR(5) NULL,
    [DD_YEARID] DECIMAL(38) NULL,
    [DD_INCTYPE] VARCHAR(5) NULL,
    [DD_GRADECODE] CHAR(3) NULL,
    [DD_PROBRATING] VARCHAR(5) NULL,
    [DD_VPPER] DECIMAL(38) NULL,
    [DD_HPPER] DECIMAL(38) NULL
);



-- Table: DD_HORIZONTAL
CREATE TABLE [DD_HORIZONTAL] (
    [PROMOTION_TRANID] DECIMAL(38) NOT NULL  -- Transaction ID,
    [PROMOTION_EMPSYSID] DECIMAL(38) NULL  -- Employee System ID,
    [PROMOTION_SCORE] DECIMAL(38) NULL  -- Promotion Score,
    [PROMOTION_GRADE] DECIMAL(38) NULL  -- Grade ID,
    [PROMOTION_CURLEVELID] DECIMAL(38) NULL  -- Current Level ID,
    [PROMOTION_NEWLEVELID] DECIMAL(38) NULL  -- New Level ID,
    [PROMOTION_EFFFROM] DATETIME2(3) NULL  -- Effective From,
    [PROMOTION_UPDATEDBY] DECIMAL(38) NULL  -- Last Updated By,
    [PROMOTION_UPDATEDON] DATETIME2(3) NULL  -- Last Updated On,
    [PROMOTION_POSITIONID] DECIMAL(38) NULL,
    [PROMOTION_OLDPOSNAME] VARCHAR(100) NULL,
    [PROMOTION_OLDPOSDESG] VARCHAR(100) NULL,
    [PROMOTION_NEWPOSNAME] VARCHAR(100) NULL,
    [PROMOTION_NEWPOSDESG] VARCHAR(100) NULL,
    [PROMOTION_POSUPDATEBY] DECIMAL(38) NULL,
    [PROMOTION_POSUPDATEDON] DATETIME2(3) NULL,
    [PROMOTION_CONFIRM_HRMS] CHAR(1) NULL,
    CONSTRAINT [PK_DD_HORIZONTAL] PRIMARY KEY ([PROMOTION_TRANID])
);



-- Table: DD_HORIZONTALLOG
CREATE TABLE [DD_HORIZONTALLOG] (
    [PROMOTION_TRANID] DECIMAL(38) NULL,
    [PROMOTION_EMPSYSID] DECIMAL(38) NULL,
    [PROMOTION_SCORE] DECIMAL(38) NULL,
    [PROMOTION_GRADE] DECIMAL(38) NULL,
    [PROMOTION_CURLEVELID] DECIMAL(38) NULL,
    [PROMOTION_NEWLEVELID] DECIMAL(38) NULL,
    [PROMOTION_EFFFROM] DATETIME2(3) NULL,
    [PROMOTION_UPDATEDBY] DECIMAL(38) NULL,
    [PROMOTION_UPDATEDON] DATETIME2(3) NULL,
    [PROMOTION_POSITIONID] DECIMAL(38) NULL,
    [PROMOTION_OLDPOSNAME] VARCHAR(100) NULL,
    [PROMOTION_OLDPOSDESG] VARCHAR(100) NULL,
    [PROMOTION_NEWPOSNAME] VARCHAR(100) NULL,
    [PROMOTION_NEWPOSDESG] VARCHAR(100) NULL,
    [PROMOTION_POSUPDATEBY] DECIMAL(38) NULL,
    [PROMOTION_POSUPDATEDON] DATETIME2(3) NULL,
    [PROMOTION_CONFIRM_HRMS] CHAR(1) NULL,
    [LOG_CREATEDBY] DECIMAL(38) NULL,
    [LOG_CREATEDON] DATETIME2(3) NULL
);



-- Table: DD_HORIZONTAL_POSITION
CREATE TABLE [DD_HORIZONTAL_POSITION] (
    [PROMOTION_EMPSYSID] DECIMAL(38) NOT NULL,
    [PROMOTION_DDYEARID] DECIMAL(38) NOT NULL,
    [PROMOTION_POSITIONID] DECIMAL(38) NOT NULL,
    [PROMOTION_OLDPOSNAME] VARCHAR(100) NOT NULL,
    [PROMOTION_OLDPOSDESG] VARCHAR(100) NOT NULL,
    [PROMOTION_NEWPOSNAME] VARCHAR(100) NOT NULL,
    [PROMOTION_NEWPOSDESG] VARCHAR(100) NOT NULL,
    [PROMOTION_POSUPDATEBY] DECIMAL(38) NOT NULL,
    [PROMOTION_POSUPDATEDON] DATETIME2(3) NOT NULL,
    [PROMOTION_CONFIRM_HRMS] CHAR(1) NOT NULL
);



-- Table: DD_INCDIRECT
CREATE TABLE [DD_INCDIRECT] (
    [DDINC_ID] DECIMAL(38) NOT NULL,
    [DDINC_EMPSYSID] DECIMAL(38) NOT NULL,
    [DDINC_YEARID] DECIMAL(38) NOT NULL,
    [DDINC_AMOUNT] DECIMAL(38) NOT NULL,
    [DDINC_SALTYPE] VARCHAR(3) NOT NULL,
    [DDINC_UPDATEDBY] DECIMAL(38) NOT NULL,
    [DDINC_UPDATEDON] DATETIME2(3) NOT NULL,
    [DDINC_RATAMT] DECIMAL(38) NULL,
    [DDINC_PROMAMNT] DECIMAL(38) NULL,
    [DDINC_PER] DECIMAL(38) NULL
);



-- Table: DD_INCDIRECT_LOG
CREATE TABLE [DD_INCDIRECT_LOG] (
    [DDINC_ID] DECIMAL(38) NOT NULL,
    [DDINC_EMPSYSID] DECIMAL(38) NOT NULL,
    [DDINC_YEARID] DECIMAL(38) NOT NULL,
    [DDINC_AMOUNT] DECIMAL(38) NOT NULL,
    [DDINC_SALTYPE] VARCHAR(3) NOT NULL,
    [DDINC_UPDATEDBY] DECIMAL(38) NOT NULL,
    [DDINC_UPDATEDON] DATETIME2(3) NOT NULL,
    [DDINC_RATAMT] DECIMAL(38) NULL,
    [DDINC_PROMAMNT] DECIMAL(38) NULL,
    [DDINC_PER] DECIMAL(38) NULL,
    [DDINC_LOGCREATEDBY] DECIMAL(38) NOT NULL,
    [DDINC_LOGCREATEDON] DATETIME2(3) NOT NULL
);



-- Table: DD_PERFORMANCERATING
CREATE TABLE [DD_PERFORMANCERATING] (
    [PER_REQNUM] DECIMAL(38) NULL  -- Request number,
    [PER_RATING] DECIMAL(38) NULL  -- Average Rating,
    [PER_PIN_NUM] DECIMAL(38) NULL  -- Pinnnumber,
    [PER_COMMENTS] VARCHAR(4000) NULL  -- appraiser comment,
    [PER_RATING1] VARCHAR(50) NULL  -- Performance Rating,
    [PER_USERID] VARCHAR(100) NULL  -- User id,
    [PER_SRLNO] DECIMAL(38) NULL,
    [PER_MEAN_RATING] DECIMAL(38) NULL  -- appraiser Mean Rating,
    [PER_MEAN_REMARKS] VARCHAR(4000) NULL  -- appraiser Mean Remarks,
    [PER_ACH_RATING] DECIMAL(38) NULL  -- Overall Performance Rating,
    [PER_RESULT_AVG] DECIMAL(38) NULL,
    [PER_APPROACH_AVG] DECIMAL(38) NULL
);



-- Table: DD_PROMOTIONLETTER
CREATE TABLE [DD_PROMOTIONLETTER] (
    [DD_PIN_NUM] DECIMAL(38) NULL  -- Pin Number,
    [DD_CRT_PIN] DECIMAL(38) NULL,
    [DD_APR_NAM] VARCHAR(150) NULL  -- Appraiser Number,
    [DD_SIG_NAM] VARCHAR(150) NULL  -- Signatory Name,
    [DD_SIG_DSG] VARCHAR(100) NULL  -- Signatory Designation,
    [DD_APR_BUS] VARCHAR(100) NULL  -- Appraisee Business,
    [DD_APR_PR1] VARCHAR(1000) NULL  -- Para 1,
    [DD_APR_PR2] VARCHAR(1000) NULL  -- Para 2,
    [DD_APR_PR3] VARCHAR(1000) NULL  -- Para 3,
    [DD_APR_PR4] VARCHAR(1000) NULL  -- Para 4,
    [DD_APR_PR5] VARCHAR(1000) NULL  -- Para 5,
    [DD_PRN_DAT] DATETIME2(3) NULL  -- Print Date,
    [DD_APR_SIN] VARCHAR(150) NULL  -- Appriaser Sign,
    [DD_APR_DSG] VARCHAR(100) NULL  -- Appraiser Designation,
    [DD_APR_BND] VARCHAR(50) NULL  -- Appraiser Band,
    [DD_APR_INC] DECIMAL(38) NULL,
    [DD_APR_PAY] DECIMAL(38) NULL,
    [DD_APR_FLX] DECIMAL(38) NULL,
    [DD_EFF_DAT] DATETIME2(3) NULL  -- Effective Date,
    [DD_APR_PR6] VARCHAR(1000) NULL
);



-- Table: DD_PROMOTIONPERIOD
CREATE TABLE [DD_PROMOTIONPERIOD] (
    [DD_PRM_ID] DECIMAL(38) NULL  -- Promotion Id,
    [DD_PRD_DSC] VARCHAR(25) NULL  -- Promotion Description (Period)
);



-- Table: DD_RATING
CREATE TABLE [DD_RATING] (
    [DD_RAT_FROM] DATETIME2(3) NULL  -- Appraisal Period From,
    [DD_RAT_TO] DATETIME2(3) NULL  -- Appraisal Period To,
    [DD_RAT_PIN] DECIMAL(38) NULL  -- PIN No,
    [DD_RAT_USR] VARCHAR(25) NULL  -- User ID,
    [DD_RAT_FIN] VARCHAR(4) NULL  -- Suggested Rating by HR,
    [DD_RAT_PRO] CHAR(1) NULL  -- Promotion Flag,
    [DD_RAT_REQ] DECIMAL(38) NULL,
    [DD_RAT_CHR] VARCHAR(4) NULL  -- CHR Rating,
    [DD_BND_ID] DECIMAL(38) NULL  -- Band Id,
    [DD_BAS_AMT] DECIMAL(38) NULL  -- Basic Pay,
    [DD_CTC_AMT] DECIMAL(38) NULL  -- CTC Amount,
    [DD_PRM_FLG] DECIMAL(38) NULL  -- Promotion Flag,
    [DD_SPL_SKL] DECIMAL(38) NULL  -- Special Skill,
    [DD_PRM_BND] DECIMAL(38) NULL  -- Final Promotion Band,
    [NEW_PROMO_FLAG] CHAR(1) NULL  -- New Promotion Flag (Y/N),
    [CASH_LEVEL] VARCHAR(1) NULL  -- Cash Level,
    [CASH_AMOUNT] DECIMAL(38) NULL  -- Cash Amount,
    [CASH_REASON] VARCHAR(400) NULL  -- Cash Reason,
    [CSH_OUTCOME] VARCHAR(400) NULL  -- Outcome Expected by this cash award,
    [DD_BLT_PER] VARCHAR(50) NULL  -- Performance Rating of BLT,
    [DD_BLT_COMP] VARCHAR(50) NULL  -- Competency Rating of BLT,
    [DD_CLT_PER] VARCHAR(50) NULL  -- Performance Rating of CLT,
    [DD_CLT_COMP] VARCHAR(50) NULL  -- Competency Rating of CLT,
    [DD_RAT_FLAG] CHAR(1) NULL  -- Rationalization Required Flag,
    [NEW_CASH_FLAG] CHAR(1) NULL,
    [DD_POSITIONID] DECIMAL(38) NULL,
    [DD_PRMHORLEVELID] DECIMAL(38) NULL,
    [DD_PAYROLL] VARCHAR(1) NULL,
    [DD_UPDATEDBY] DECIMAL(38) NULL,
    [DD_UPDATEDON] DATETIME2(3) NULL
);



-- Table: DD_RATING_LOG
CREATE TABLE [DD_RATING_LOG] (
    [DD_RAT_FROM] DATETIME2(3) NULL,
    [DD_RAT_TO] DATETIME2(3) NULL,
    [DD_RAT_PIN] DECIMAL(38) NULL,
    [DD_RAT_USR] VARCHAR(25) NULL,
    [DD_RAT_FIN] VARCHAR(4) NULL,
    [DD_RAT_PRO] CHAR(1) NULL,
    [DD_RAT_REQ] DECIMAL(38) NULL,
    [DD_RAT_CHR] VARCHAR(4) NULL,
    [DD_BND_ID] DECIMAL(38) NULL,
    [DD_BAS_AMT] DECIMAL(38) NULL,
    [DD_CTC_AMT] DECIMAL(38) NULL,
    [DD_PRM_FLG] DECIMAL(38) NULL,
    [DD_SPL_SKL] DECIMAL(38) NULL,
    [DD_PRM_BND] DECIMAL(38) NULL,
    [NEW_PROMO_FLAG] CHAR(1) NULL,
    [CASH_LEVEL] VARCHAR(1) NULL,
    [CASH_AMOUNT] DECIMAL(38) NULL,
    [CASH_REASON] VARCHAR(400) NULL,
    [CSH_OUTCOME] VARCHAR(400) NULL,
    [DD_BLT_PER] VARCHAR(50) NULL,
    [DD_BLT_COMP] VARCHAR(50) NULL,
    [DD_CLT_PER] VARCHAR(50) NULL,
    [DD_CLT_COMP] VARCHAR(50) NULL,
    [DD_RAT_FLAG] CHAR(1) NULL,
    [NEW_CASH_FLAG] CHAR(1) NULL,
    [DD_POSITIONID] DECIMAL(38) NULL,
    [DD_PRMHORLEVELID] DECIMAL(38) NULL,
    [DD_PAYROLL] VARCHAR(1) NULL,
    [DD_UPDATEDBY] DECIMAL(38) NULL,
    [DD_UPDATEDON] DATETIME2(3) NULL,
    [DD_LOGCREATEDBY] DECIMAL(38) NULL,
    [DD_LOGCREATEDON] DATETIME2(3) NULL
);



-- Table: DD_REQNUM_COMPE_INDPROM
CREATE TABLE [DD_REQNUM_COMPE_INDPROM] (
    [REQNUM] DECIMAL(38) NULL  -- Request Number,
    [COMPNUM] DECIMAL(38) NULL  -- Competency Number,
    [INDNUM] DECIMAL(38) NULL  -- Indicator Number,
    [FLAG] CHAR(1) NULL  -- Flag,
    [PINNUM] DECIMAL(38) NULL  -- Pin Number
);



-- Table: DD_REQNUM_COMPE_INDPROMLOG
CREATE TABLE [DD_REQNUM_COMPE_INDPROMLOG] (
    [REQNUM] DECIMAL(38) NULL,
    [COMPNUM] DECIMAL(38) NULL,
    [INDNUM] DECIMAL(38) NULL,
    [FLAG] CHAR(1) NULL,
    [PINNUM] DECIMAL(38) NULL
);



-- Table: DD_SUBLEVEL_INC
CREATE TABLE [DD_SUBLEVEL_INC] (
    [SLINC_ID] DECIMAL(38) NULL,
    [SLINC_YEARID] DECIMAL(38) NOT NULL,
    [SLINC_ENDDATE] DATETIME2(3) NOT NULL,
    [SLINC_GRADEID] DECIMAL(38) NOT NULL,
    [SLINC_LEVELID] DECIMAL(38) NOT NULL,
    [SLINC_RATING] CHAR(5) NOT NULL,
    [SLINC_RATEAMT] DECIMAL(38) NULL,
    [SLINC_MODIFIEDBY] DECIMAL(38) NOT NULL,
    [SLINC_MODIFIEDON] DATETIME2(3) NOT NULL,
    [SLINC_MINAMT] DECIMAL(38) NULL,
    [SLINC_MAXAMT] DECIMAL(38) NULL
);



-- Table: DD_SUBLEVEL_INC_LOG
CREATE TABLE [DD_SUBLEVEL_INC_LOG] (
    [SLINC_ID] DECIMAL(38) NULL,
    [SLINC_YEARID] DECIMAL(38) NOT NULL,
    [SLINC_ENDDATE] DATETIME2(3) NOT NULL,
    [SLINC_GRADEID] DECIMAL(38) NOT NULL,
    [SLINC_LEVELID] DECIMAL(38) NOT NULL,
    [SLINC_RATING] CHAR(5) NOT NULL,
    [SLINC_RATEAMT] DECIMAL(38) NULL,
    [SLINC_MODIFIEDBY] DECIMAL(38) NOT NULL,
    [SLINC_MODIFIEDON] DATETIME2(3) NOT NULL,
    [SLINC_MINAMT] DECIMAL(38) NULL,
    [SLINC_MAXAMT] DECIMAL(38) NULL,
    [SLINC_LOGCREATEDBY] DECIMAL(38) NULL,
    [SLINC_LOGCREATEDON] DATETIME2(3) NULL
);



-- Table: DD_VTCCORRECTION
CREATE TABLE [DD_VTCCORRECTION] (
    [VTC_RATEID] DECIMAL(38) NOT NULL,
    [VTC_EMPSYSID] DECIMAL(38) NOT NULL,
    [VTC_FINYEARID] DECIMAL(38) NOT NULL,
    [VTC_STATUS] CHAR(1) NOT NULL,
    [VTC_GRADEID] DECIMAL(38) NOT NULL,
    [VTC_OLDRATING] VARCHAR(20) NOT NULL,
    [VTC_NEWRATING] VARCHAR(20) NOT NULL,
    [VTC_OLDCASH] VARCHAR(3) NULL,
    [VTC_NEWCASH] VARCHAR(3) NULL,
    [VTC_OLDPROMO] VARCHAR(3) NOT NULL,
    [VTC_NEWPROMO] VARCHAR(3) NOT NULL,
    [VTC_OLDRATIONAL] VARCHAR(3) NOT NULL,
    [VTC_NEWRATIONAL] VARCHAR(3) NOT NULL,
    [VTC_REASON] VARCHAR(200) NOT NULL,
    [VTC_CREATEDBY] DECIMAL(38) NOT NULL,
    [VTC_CREATEDON] DATETIME2(3) NOT NULL,
    [VTC_MODIFIEDBY] DECIMAL(38) NULL,
    [VTC_MODIFIEDON] DATETIME2(3) NULL,
    [VTC_APPROVEDBY] DECIMAL(38) NULL,
    [VTC_APPROVEDON] DATETIME2(3) NULL
);



-- Table: DD_VTCCORRECTION_LOG
CREATE TABLE [DD_VTCCORRECTION_LOG] (
    [VTC_RATEID] DECIMAL(38) NOT NULL,
    [VTC_EMPSYSID] DECIMAL(38) NOT NULL,
    [VTC_FINYEARID] DECIMAL(38) NOT NULL,
    [VTC_STATUS] CHAR(1) NOT NULL,
    [VTC_GRADEID] DECIMAL(38) NOT NULL,
    [VTC_OLDRATING] VARCHAR(20) NOT NULL,
    [VTC_NEWRATING] VARCHAR(20) NOT NULL,
    [VTC_OLDCASH] VARCHAR(3) NULL,
    [VTC_NEWCASH] VARCHAR(3) NULL,
    [VTC_OLDPROMO] VARCHAR(3) NOT NULL,
    [VTC_NEWPROMO] VARCHAR(3) NOT NULL,
    [VTC_OLDRATIONAL] VARCHAR(3) NOT NULL,
    [VTC_NEWRATIONAL] VARCHAR(3) NOT NULL,
    [VTC_REASON] VARCHAR(200) NOT NULL,
    [VTC_CREATEDBY] DECIMAL(38) NOT NULL,
    [VTC_CREATEDON] DATETIME2(3) NOT NULL,
    [VTC_MODIFIEDBY] DECIMAL(38) NULL,
    [VTC_MODIFIEDON] DATETIME2(3) NULL,
    [VTC_APPROVEDBY] DECIMAL(38) NULL,
    [VTC_APPROVEDON] DATETIME2(3) NULL,
    [LOG_CREATEDBY] DECIMAL(38) NULL,
    [LOG_CREATEDON] DATETIME2(3) NULL
);



-- Table: DD_VTCDETERREM
CREATE TABLE [DD_VTCDETERREM] (
    [DE_BND_NAM] VARCHAR(20) NULL  -- Band Name,
    [DE_VAL_NAM] VARCHAR(3) NULL  -- Value Name (H1,H2A,H3..),
    [DD_VAL_DSC] VARCHAR(1000) NULL  -- Value Description,
    [DD_FIN_YEAR] DATETIME2(3) NULL  -- Financial Year Date
);



-- Table: DD_VTCINCLIST
CREATE TABLE [DD_VTCINCLIST] (
    [VTC_DDYEARID] DECIMAL(38) NULL,
    [VTC_REQ_NUM] DECIMAL(38) NULL,
    [VTC_DDTYPE] VARCHAR(10) NULL,
    [VTC_SALTYPE] VARCHAR(10) NULL,
    [VTC_REQ_USERID] VARCHAR(25) NULL,
    [VTC_REQ_EMPSYSID] DECIMAL(38) NULL,
    [VTC_REQ_NAM] VARCHAR(150) NULL,
    [VTC_REQ_UNITID] DECIMAL(38) NULL,
    [VTC_REQ_BUSID] DECIMAL(38) NULL,
    [VTC_REQ_GRADEID] DECIMAL(38) NULL,
    [VTC_REQ_GRADE] VARCHAR(25) NULL,
    [VTC_REQ_BANDLEVEL] VARCHAR(50) NULL,
    [VTC_REQ_LEVELID] DECIMAL(38) NULL,
    [VTC_REQ_GROUPDOJ] DATETIME2(3) NULL,
    [VTC_REQ_CONFDATE] DATETIME2(3) NULL,
    [VTC_PROMSCORE] DECIMAL(38) NULL,
    [VTC_CURR_CTC] DECIMAL(38) NULL,
    [VTC_RAT_REVDD] VARCHAR(200) NULL,
    [VTC_RAT_BLT] VARCHAR(5) NULL,
    [VTC_RAT_CLT] VARCHAR(5) NULL,
    [VTC_BND_ID] DECIMAL(38) NULL,
    [VTC_RAT_BND] CHAR(20) NULL,
    [VTC_INC_AMT] DECIMAL(38) NULL,
    [VTC_PRE_HORIPOINTS] DECIMAL(38) NULL,
    [VTC_RATING_POINTS] DECIMAL(38) NULL,
    [VTC_NEW_HORIPOINTS] DECIMAL(38) NULL,
    [VTC_HORIPRM_ELIGIBLE] CHAR(1) NULL,
    [VTC_HORIPRM_BLT] CHAR(1) NULL,
    [VTC_VERTIPRM_BLT] CHAR(1) NULL,
    [VTC_PRM_BND] DECIMAL(38) NULL,
    [VTC_PRM_INCAMT] DECIMAL(38) NULL,
    [VTC_RATIFY_FLAG] CHAR(1) NULL,
    [VTC_RATIFY_AMT] DECIMAL(38) NULL,
    [VTC_REQ_EMPNUM] DECIMAL(38) NULL,
    [VTC_REQ_PINNO] DECIMAL(38) NULL,
    [VTC_REQ_UNIT] VARCHAR(50) NULL,
    [VTC_REQ_BUS] VARCHAR(50) NULL,
    [VTC_REV_CTC] DECIMAL(38) NULL,
    [VTC_PER_INCREASE] DECIMAL(38) NULL,
    [VTC_OLD_PER] DECIMAL(38) NULL,
    [VTC_OLD_RAT] VARCHAR(5) NULL,
    [VTC_EXPMONTHS] DECIMAL(38) NULL,
    [VTC_MYPROM] VARCHAR(20) NULL,
    [VTC_PROB_FLAG] CHAR(1) NULL,
    [VTC_LASTVERTIPROMDATE] DATETIME2(3) NULL,
    [VTC_INC_TYPE] VARCHAR(5) NULL,
    [VTC_SAMEAPR_REV] CHAR(1) NULL,
    [VTC_PROMO_FLAG] CHAR(1) NULL,
    [VTC_PROMO_REVDD] VARCHAR(100) NULL,
    [VTC_PROMLEVELTYPE] CHAR(1) NULL,
    [VTC_PROMLEVELID] DECIMAL(38) NULL,
    [VTC_PROMGRADEID] DECIMAL(38) NULL,
    [VTC_PROMLEVELTYPE_BLT] CHAR(1) NULL,
    [VTC_PROMLEVELID_BLT] DECIMAL(38) NULL,
    [VTC_PROMSUBLEVELID_BLT] DECIMAL(38) NULL,
    [VTC_DDPAYROLL] CHAR(1) NULL,
    [VTC_LOG_EMPSYSID] DECIMAL(38) NULL,
    [VTC_LOG_USERID] VARCHAR(25) NULL,
    [VTC_LOG_RUNON] DATETIME2(3) NULL,
    [VTC_NEWGRADE2017] VARCHAR(50) NULL,
    [VTC_NEWGRADE] DECIMAL(38) NULL,
    [VTC_INCPER] DECIMAL(38) NULL,
    [VTC_CONFPAY_FLAG] CHAR(1) NULL,
    [VTC_CONFPAY_AMT] DECIMAL(38) NULL,
    [VTC_DD_VERPER] DECIMAL(38) NULL,
    [VTC_DD_HPPER] DECIMAL(38) NULL,
    [VTC_ORGID] DECIMAL(38) NULL,
    [VTC_BUSID] DECIMAL(38) NULL
);



-- Table: DD_VTCRATING
CREATE TABLE [DD_VTCRATING] (
    [DD_REQ_NUM] DECIMAL(38) NULL  -- Request Number,
    [APPR_PERRAT] DECIMAL(38) NULL  -- Appraiser Performance Rating,
    [APPR_COMPRAT] DECIMAL(38) NULL  -- Appraiser Competency Rating,
    [APPR_VTCRAT] DECIMAL(38) NULL  -- Appraiser  VTC Rating,
    [APPR_USERID] VARCHAR(100) NULL  -- Appraiser User ID,
    [APPR_PIN_NUM] DECIMAL(38) NULL  -- Appraiser Pinum,
    [EN_DATE] DATETIME2(3) NULL  -- Enter Date,
    [REV_PERRAT] DECIMAL(38) NULL  -- Reviewer Performance Rating,
    [REV_COMPRAT] DECIMAL(38) NULL  -- Reviewer Competency Rating,
    [REV_VTCRAT] DECIMAL(38) NULL  -- Reviewer VTC Rating,
    [REV_USRID] VARCHAR(100) NULL  -- Reviewer Userid,
    [REV_PIN_NUM] DECIMAL(38) NULL  -- Reviewer Pinum,
    [REV_PER_REMARKS] VARCHAR(4000) NULL  -- Performance Remarks,
    [REV_COMPE_REMARKS] VARCHAR(4000) NULL  -- Competency Remarks,
    [APPR_VTCRAT_REC] DECIMAL(38) NULL
);



-- Table: DD_VTCRATING_REV
CREATE TABLE [DD_VTCRATING_REV] (
    [REV_REQ_NUM] DECIMAL(38) NULL  -- Request Number,
    [REV_PERRAT] DECIMAL(38) NULL  -- Reviewer Performance Rating,
    [REV_COMPRAT] DECIMAL(38) NULL  -- Reviewer Competency Rating,
    [REV_VTCRAT] DECIMAL(38) NULL  -- Reviewer VTC Rating,
    [REV_USRID] VARCHAR(100) NULL  -- Reviewer Userid,
    [REV_PIN_NUM] DECIMAL(38) NULL  -- Reviewer Pinum,
    [REV_PER_REMARKS] VARCHAR(4000) NULL  -- Performance Remarks,
    [REV_COMPE_REMARKS] VARCHAR(4000) NULL,
    [REV_UPDATEDON] DATETIME2(3) NULL,
    [REV_VTCRAT_REC] DECIMAL(38) NULL
);



-- Table: DD_VTCSCORE
CREATE TABLE [DD_VTCSCORE] (
    [VTC_SCOREID] DECIMAL(38) NOT NULL  -- Score ID,
    [VTC_GRADEID] DECIMAL(38) NULL  -- Grate ID,
    [VTC_RATING] VARCHAR(5) NULL  -- VTC Rating,
    [VTC_SCORE] DECIMAL(38) NULL  -- VTC Score,
    [VTC_DDTYPE] CHAR(3) NULL  -- DD Type,
    CONSTRAINT [PK_DD_VTCSCORE] PRIMARY KEY ([VTC_SCOREID])
);



-- Table: DD_VTCSUGGRATING
CREATE TABLE [DD_VTCSUGGRATING] (
    [VT_RQ_NUM] DECIMAL(38) NOT NULL  -- Request No,
    [VT_QTN_NUM] DECIMAL(38) NULL  -- Competency No or Qusetion No,
    [VT_QTN_TYP] CHAR(1) NULL  -- C-Competency N-Normal Question,
    [VT_VTC_RAT] DECIMAL(38) NULL  -- Rating By BLT/CLT
);



-- Table: DD_VTC_COPYBLANKRAT
CREATE TABLE [DD_VTC_COPYBLANKRAT] (
    [VTC_DDYEARID] DECIMAL(38) NULL,
    [VTC_STRDATE] DATETIME2(3) NULL,
    [VTC_ENDDATE] DATETIME2(3) NULL,
    [VTC_REQ_NUM] DECIMAL(38) NULL,
    [VTC_DDTYPE] VARCHAR(10) NULL,
    [VTC_REQ_USERID] VARCHAR(25) NULL,
    [VTC_REQ_EMPSYSID] DECIMAL(38) NULL,
    [VTC_RAT_REVDD] VARCHAR(200) NULL,
    [VTC_RAT_BLT] VARCHAR(5) NULL,
    [VTC_LOG_EMPSYSID] DECIMAL(38) NULL,
    [VTC_LOG_USERID] VARCHAR(25) NULL,
    [VTC_LOG_RUNON] DATETIME2(3) NULL,
    [VTC_REVCOUNT] DECIMAL(38) NULL,
    [VTC_BND_ID] DECIMAL(38) NULL
);



-- Table: DD_YRRATING_MASTER
CREATE TABLE [DD_YRRATING_MASTER] (
    [YRRATING_ID] DECIMAL(38) NOT NULL,
    [YRRATING_FINYEAR_ID] DECIMAL(38) NOT NULL,
    [YRRATING_DESC] VARCHAR(5) NOT NULL,
    [YRRATING_ORDER] DECIMAL(38) NOT NULL,
    [YRRATING_SUBCAT] VARCHAR(5) NOT NULL,
    [YRRATING_GROUP] VARCHAR(7) NULL,
    [YRRATING_START] DECIMAL(38) NULL,
    [YRRATING_END] DECIMAL(38) NULL,
    [YRRATING_COLOR] VARCHAR(25) NULL,
    CONSTRAINT [PK_DD_YRRATING_MASTER] PRIMARY KEY ([YRRATING_ID])
);



-- Table: ELORATE
CREATE TABLE [ELORATE] (
    [PINNO] DECIMAL(38) NULL,
    [ELONAME] VARCHAR(200) NULL,
    [RATING] VARCHAR(2) NULL,
    [YEAR] DECIMAL(38) NULL,
    [EMPNO] DECIMAL(38) NULL,
    [PAYUNIT] VARCHAR(3) NULL,
    [REPUNIT] VARCHAR(3) NULL,
    [USERID] VARCHAR(100) NULL,
    [SYSID] DECIMAL(38) NULL,
    [STATUS] VARCHAR(1) NULL
);



-- Table: SPL_RATING
CREATE TABLE [SPL_RATING] (
    [SP_REQ_NUM] DECIMAL(38) NOT NULL  -- Request Number,
    [SP_SRL_NUM] DECIMAL(38) NOT NULL  -- Serial Number,
    [SP_CMP_SKL] VARCHAR(2000) NULL  -- components of skill,
    [SP_CMP_NUM] DECIMAL(38) NULL  -- component number,
    [SP_SPL_RMK] VARCHAR(2000) NULL  -- Remarks,
    [SP_SPL_RAT] VARCHAR(10) NULL  -- Specail rating,
    [SP_SUC_NAM] VARCHAR(50) NULL  -- Successor name,
    [SP_FIN_STR] DATETIME2(3) NOT NULL  -- Financial Year Start date,
    [SP_FIN_END] DATETIME2(3) NOT NULL  -- Financial Date End Date,
    CONSTRAINT [PK_SPL_RATING] PRIMARY KEY ([SP_REQ_NUM])
);

