// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurityService.Infrastructure.Data;

#nullable disable

namespace SecurityService.Infrastructure.Migrations
{
    [DbContext(typeof(SecurityDbContext))]
    [Migration("20260318085222_AddStoredProcedures")]
    partial class AddStoredProcedures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SecurityService.Domain.Entities.AccessRole", b =>
                {
                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("RA_END_DAT");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("RA_ROL_COD");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("RA_STR_DAT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("RA_UPD_DAT");

                    b.Property<string>("UpdatedByCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("RA_UPD_USR");

                    b.Property<long?>("UpdatedByNum")
                        .HasColumnType("bigint")
                        .HasColumnName("RA_UPD_NUM");

                    b.Property<string>("UserCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("RA_USR_COD");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("RA_USR_NUM");

                    b.ToTable("ACCESS_ROLE", (string)null);
                });

            modelBuilder.Entity("SecurityService.Domain.Entities.AccessRoleMaster", b =>
                {
                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("AR_ROL_COD");

                    b.Property<string>("RoleName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AR_ROL_NAM");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("AR_UPD_DAT");

                    b.Property<string>("UpdatedByCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("AR_UPD_USR");

                    b.Property<long?>("UpdatedByNum")
                        .HasColumnType("bigint")
                        .HasColumnName("AR_UPD_NUM");

                    b.ToTable("ACCESS_ROLE_MASTER", (string)null);
                });

            modelBuilder.Entity("SecurityService.Domain.Entities.AccessRoleMenu", b =>
                {
                    b.Property<long?>("MenuId")
                        .HasColumnType("bigint")
                        .HasColumnName("ARM_MEN_COD");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("ARM_ROL_COD");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("ARM_UPD_DAT");

                    b.Property<string>("UpdatedByCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("ARM_UPD_USR");

                    b.Property<long?>("UpdatedByNum")
                        .HasColumnType("bigint")
                        .HasColumnName("ARM_UPD_NUM");

                    b.ToTable("ACCESSROLE_MENU", (string)null);
                });

            modelBuilder.Entity("SecurityService.Domain.Entities.MenuMaster", b =>
                {
                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("DISPLAYORDER");

                    b.Property<long?>("MenuId")
                        .HasColumnType("bigint")
                        .HasColumnName("MENU_ID");

                    b.Property<string>("MenuName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MENU_NAME");

                    b.Property<long?>("ParentMenuId")
                        .HasColumnType("bigint")
                        .HasColumnName("PARENT_MENU_ID");

                    b.Property<string>("Url")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("URL");

                    b.ToTable("MENUMASTER", (string)null);
                });

            modelBuilder.Entity("SecurityService.Domain.Entities.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("RL_ROL_COD");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("RL_ROL_NAM");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("RL_UPD_DAT");

                    b.Property<string>("UpdatedByCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RL_UPD_USR");

                    b.Property<long?>("UpdatedByNum")
                        .HasColumnType("bigint")
                        .HasColumnName("RL_UPD_NUM");

                    b.HasKey("RoleId");

                    b.ToTable("ROLE_MAST", (string)null);
                });

            modelBuilder.Entity("SecurityService.Domain.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UM_USR_NUM");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("UM_END_DAT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("UM_STR_DAT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("UM_UPD_DAT");

                    b.Property<string>("UpdatedByCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("UM_UPD_USR");

                    b.Property<long?>("UpdatedByNum")
                        .HasColumnType("bigint")
                        .HasColumnName("UM_UPD_NUM");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UM_USR_NAM");

                    b.Property<string>("UserType")
                        .HasColumnType("char(1)")
                        .HasColumnName("UM_USR_TYP");

                    b.HasKey("UserId");

                    b.ToTable("USER_MASTER", (string)null);
                });

            modelBuilder.Entity("SecurityService.Domain.Entities.UserMasterMap", b =>
                {
                    b.Property<long>("MapId")
                        .HasColumnType("bigint")
                        .HasColumnName("UM_MAP_ID");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("UM_DEPT_COD");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("UM_END_DAT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("UM_STR_DAT");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UM_USR_NUM");

                    b.HasKey("MapId");

                    b.ToTable("USER_MASTER_MAP", (string)null);
                });

            modelBuilder.Entity("SecurityService.Domain.Entities.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UR_USR_NUM");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("UR_ROL_COD");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("UR_END_DAT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("UR_STR_DAT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("UR_UPD_DAT");

                    b.Property<string>("UpdatedByCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("UR_UPD_USR");

                    b.Property<long?>("UpdatedByNum")
                        .HasColumnType("bigint")
                        .HasColumnName("UR_UPD_NUM");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("USER_ROLE", (string)null);
                });

            modelBuilder.Entity("SecurityService.Domain.Entities.User", b =>
                {
                    b.OwnsOne("SecurityService.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("UM_USR_MAI");

                            b1.HasKey("UserId");

                            b1.ToTable("USER_MASTER");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("SecurityService.Domain.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("UM_USR_PHN");

                            b1.HasKey("UserId");

                            b1.ToTable("USER_MASTER");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("SecurityService.Domain.ValueObjects.UserCode", "UserCode", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(25)
                                .HasColumnType("nvarchar(25)")
                                .HasColumnName("UM_USR_COD");

                            b1.HasKey("UserId");

                            b1.ToTable("USER_MASTER");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email");

                    b.Navigation("Phone");

                    b.Navigation("UserCode")
                        .IsRequired();
                });

            modelBuilder.Entity("SecurityService.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("SecurityService.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SecurityService.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecurityService.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
