-- ==========================================
-- Module: TOURPLAN
-- Description: Tour Plan Management Module
-- Database: TOURDB
-- Created: March 9, 2026
-- ==========================================

USE TOURDB;
GO

-- Table: TOURPLAN_MAIN - Travel Main
CREATE TABLE [TOURPLAN_MAIN] (
    [TP_ID] VARCHAR(255) NOT NULL  -- TP ID,
    [TP_EMPSYSID] VARCHAR(255) NOT NULL  -- Employee System ID,
    [TP_STARTDATE] DATETIME2(3) NOT NULL  -- Start Date,
    [TP_ENDDATE] DATETIME2(3) NULL  -- End Date,
    [TP_PURPOSE] VARCHAR(255) NOT NULL  -- Purpose of Travel,
    [TP_REMARKS] VARCHAR(255) NOT NULL  -- Desired Outcome,
    [TP_STATUS] VARCHAR(255) NOT NULL  -- TP Status,
    [TP_CATEGORY] VARCHAR(255) NOT NULL  -- Travel Category (DOM/INT),
    [TP_BOOKINC] VARCHAR(255) NOT NULL  -- Include Booking Requests,
    [TP_TYPE] VARCHAR(255) NULL  -- Single City/Multiple City,
    [TP_CREATEDBY] VARCHAR(255) NOT NULL  -- Created by,
    [TP_CREATEDON] DATETIME2(3) NOT NULL  -- Created on,
    [TP_APPROVEDBY] VARCHAR(255) NULL  -- Approved by,
    [TP_APPROVEDON] DATETIME2(3) NULL  -- Approved on,
    [TP_LASTMODIFIEDBY] VARCHAR(255) NOT NULL  -- Last modified by,
    [TP_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last modified on,
    [TP_FROMCITYID] VARCHAR(255) NOT NULL  -- From City ID,
    [TP_FROMCITYNAME] VARCHAR(255) NOT NULL  -- From City Name,
    [TP_TOCITYID] VARCHAR(255) NOT NULL  -- To City ID,
    [TP_TOCITYNAME] VARCHAR(255) NOT NULL  -- To City Name,
    [TP_SUPREMARKS] VARCHAR(255) NOT NULL  -- Remarks to supervisor,
    [TP_CONTACTNO] VARCHAR(255) NULL  -- Contact mobile no,
    [TP_GRADETYPE] VARCHAR(255) NULL  -- Grade Category,
    [TP_HOMECOUNTRYID] VARCHAR(255) NULL  -- Home Country ID,
    [TP_TRAVELSECTORID] VARCHAR(255) NULL  -- Travel Sector ID,
    [TP_COSTEFFECTIVE] VARCHAR(255) NULL  -- Is it cost effective,
    [TP_COSTJUSTIFY] VARCHAR(255) NULL  -- Justification for cost,
    [TP_CLAIMTYPE] VARCHAR(255) NULL  -- Flat/Actuals,
    [TP_SPECIALREMARKS] VARCHAR(255) NULL  -- Special sanction remarks,
    [TP_APPREMARKS] VARCHAR(255) NULL  -- Approver Remarks,
    [TP_APPLEVEL] VARCHAR(255) NULL  -- Approver Max Level,
    [TP_BALPAYAMT] VARCHAR(255) NULL  -- Balance payable amount,
    [TP_CEOEMPSYSID] VARCHAR(255) NULL  -- CEO Approval EmpsysID,
    [TP_DAEFFDATE] DATETIME2(3) NULL  -- DA Start Date,
    [TP_DACLSDATE] DATETIME2(3) NULL  -- DA End Date,
    [TP_DAVALUE] VARCHAR(255) NULL  -- DA Value,
    [TP_DATOOLTIP] VARCHAR(255) NULL  -- DA Tooltip description,
    [TP_EXPSTATUS] VARCHAR(255) NULL  -- Expense Status,
    [TP_EXPAPPROVEDBY] VARCHAR(255) NULL  -- Expense Approved by,
    [TP_EXPAPPROVEDON] DATETIME2(3) NULL  -- Expense Approved on,
    [TP_RECOMMENDERSYSID] VARCHAR(255) NULL  -- Recommender Sysid,
    [TP_PAYUNITID] VARCHAR(255) NULL  -- Payroll Units ID,
    [TP_DADAYS] VARCHAR(255) NULL  -- DA Days,
    [TP_DARATE] VARCHAR(255) NULL  -- DA Rate,
    [TP_EXPPAYMODE] VARCHAR(255) NULL  -- Expense Settlement Pay Mode,
    [TP_EXPJVID] VARCHAR(255) NULL  -- Expense JV ID,
    [TP_EXPSUBMITEDON] DATETIME2(3) NULL  -- Expense Settlement Submited On,
    [TP_EXPSUBMITEDBY] VARCHAR(255) NULL  -- Expense Settlement Submited By,
    [TP_ESTIMATECONVRATE1] VARCHAR(255) NULL  -- Estimated Conversion Rate (USD),
    [TP_ESTIMATECONVRATE2] VARCHAR(255) NULL  -- Estimated Conversion Rate (EURO),
    [TP_ACTREMARKS] VARCHAR(255) NULL  -- Actual Outcome,
    [TP_ESTIMATECONVRATE3] VARCHAR(255) NULL  -- Estimated Conversion Rate (GBP),
    [TP_CLOSURESTATUS] CHAR(1) NULL  -- Closure Status,
    CONSTRAINT [PK_TOURPLAN_MAIN] PRIMARY KEY ([TP_ID])
);

-- Table: TOURPLAN_ADVANCE - Travel Advance
CREATE TABLE [TOURPLAN_ADVANCE] (
    [ADV_ID] VARCHAR(255) NOT NULL  -- Advance ID,
    [ADV_TPID] VARCHAR(255) NOT NULL  -- TP ID,
    [ADV_AMOUNT] VARCHAR(255) NOT NULL  -- Advance Amount,
    [ADV_JVID] VARCHAR(255) NOT NULL  -- Advance JV ID,
    [ADV_REMARKS] VARCHAR(255) NOT NULL  -- Advance Remarks,
    [ADV_APPSTATUS] VARCHAR(255) NOT NULL  -- Finance Approval Status,
    [ADV_APPBY] VARCHAR(255) NULL  -- Approved by,
    [ADV_APPON] DATETIME2(3) NULL  -- Approved on,
    [ADV_CURRENCY] VARCHAR(255) NOT NULL  -- Currency,
    [ADV_RATE] VARCHAR(255) NOT NULL  -- Foreign Currency Value,
    [ADV_TOTAL] VARCHAR(255) NOT NULL  -- INR Value,
    [ADV_MODIFIEDON] DATETIME2(3) NOT NULL  -- Last Modified on,
    [ADV_APPREMARKS] VARCHAR(200) NULL  -- Approver Remarks,
    [ADV_FINREMARKS] VARCHAR(200) NULL  -- Finance Remarks,
    [ADV_TYPE] CHAR(1) NULL  -- (N-Normal / A - Addtional),
    [ADV_PAYMODE] VARCHAR(255) NULL  -- Advance Payment Mode,
    CONSTRAINT [PK_TOURPLAN_ADVANCE] PRIMARY KEY ([ADV_ID])
);

-- Table: TOURPLAN_AGENDA - Travel Agenda
CREATE TABLE [TOURPLAN_AGENDA] (
    [AGENDA_ID] VARCHAR(255) NOT NULL  -- Agenda Detail ID,
    [AGENDA_TPID] VARCHAR(255) NOT NULL  -- TP ID,
    [AGENDA_CITY] VARCHAR(255) NOT NULL  -- City,
    [AGENDA_MEET] VARCHAR(255) NOT NULL  -- Party to meet,
    [AGENDA_OUTCOME] VARCHAR(255) NOT NULL  -- Desired outcome,
    [AGENDA_TYPE] DATETIME2(3) NULL
);

-- Table: TOURPLAN_COSTCENTRE - Travel Cost Allocation
CREATE TABLE [TOURPLAN_COSTCENTRE] (
    [TPCOST_ID] VARCHAR(255) NOT NULL  -- TP Cost ID,
    [TPCOST_TPID] VARCHAR(255) NOT NULL  -- TP ID,
    [TPCOST_BUCODE] VARCHAR(255) NOT NULL  -- Unit,
    [TPCOST_CCCODE] VARCHAR(255) NOT NULL  -- Cost Centre,
    [TPCOST_SUBACCCODE] VARCHAR(255) NOT NULL  -- Sub Account Code,
    [TPCOST_PRODUCTCODE] VARCHAR(255) NOT NULL  -- Product Code,
    [TPCOST_LOCSEGMENT] VARCHAR(255) NOT NULL  -- Location,
    [TPCOST_ALLLPER] VARCHAR(255) NOT NULL  -- Allocation Percentage,
    [TPCOST_DEFAULT] CHAR(1) NULL  -- Default CostCentre
);

-- Table: TOURPLAN_DABREAK - Tour Plan DA breakup
CREATE TABLE [TOURPLAN_DABREAK] (
    [TPDA_ID] VARCHAR(255) NOT NULL  -- DA ID,
    [TPDA_TPID] VARCHAR(255) NOT NULL  -- TP ID,
    [TPDA_COUNTRYID] VARCHAR(255) NOT NULL  -- Country ID,
    [TPDA_CURRENCY] VARCHAR(255) NOT NULL  -- Currency,
    [TPDA_DAYS] VARCHAR(255) NOT NULL  -- No of days,
    [TPDA_RATE] VARCHAR(255) NOT NULL  -- Rate,
    [TPDA_GHDAYS] VARCHAR(255) NULL  -- Guest House Days,
    [TPDA_GHRATE] VARCHAR(255) NULL  -- Guest House Rate,
    CONSTRAINT [PK_TOURPLAN_DABREAK] PRIMARY KEY ([TPDA_ID])
);

-- Table: TOURPLAN_EXPENSE - Travel Approximate Expense
CREATE TABLE [TOURPLAN_EXPENSE] (
    [TPEXP_ID] VARCHAR(255) NOT NULL  -- Expense Detail ID,
    [TPEXP_TPID] VARCHAR(255) NOT NULL  -- TP ID,
    [TPEXP_EXPID] VARCHAR(255) NOT NULL  -- Expense ID,
    [TPEXP_CUR] VARCHAR(255) NOT NULL  -- Currency,
    [TPEXP_EXPAMT] VARCHAR(255) NOT NULL  -- Expense Amount,
    [TPEXP_REMARKS] VARCHAR(255) NULL  -- Remarks,
    CONSTRAINT [PK_TOURPLAN_EXPENSE] PRIMARY KEY ([TPEXP_ID])
);

-- Table: TOURPLAN_INTSCH - International Travel Schedule
CREATE TABLE [TOURPLAN_INTSCH] (
    [INTSCH_ID] VARCHAR(255) NOT NULL  -- International Schedule ID,
    [INTSCH_TPID] VARCHAR(255) NOT NULL  -- TP ID,
    [INTSCH_FROMDATE] DATETIME2(3) NOT NULL  -- From Date,
    [INTSCH_FROMTIME] VARCHAR(255) NOT NULL  -- From Time,
    [INTSCH_FROMCITYID] VARCHAR(255) NOT NULL  -- From City ID,
    [INTSCH_FROMCITY] VARCHAR(255) NOT NULL  -- From City,
    [INTSCH_FROMCOUNTRY] VARCHAR(255) NOT NULL  -- From Country,
    [INTSCH_TODATE] DATETIME2(3) NOT NULL  -- To Date,
    [INTSCH_TOTIME] VARCHAR(255) NOT NULL  -- To Time,
    [INTSCH_TOCITYID] VARCHAR(255) NOT NULL  -- To City ID,
    [INTSCH_TOCITY] VARCHAR(255) NOT NULL  -- To City,
    [INTSCH_TOCOUNTRY] VARCHAR(255) NOT NULL  -- To Country,
    [INTSCH_APPROXCOST] VARCHAR(255) NOT NULL  -- Approximate Cost,
    CONSTRAINT [PK_TOURPLAN_INTSCH] PRIMARY KEY ([INTSCH_ID])
);

-- Table: TOURPLAN_LEAVE - Tour Plan Leave Details
CREATE TABLE [TOURPLAN_LEAVE] (
    [LEAVE_TPLEAVEID] VARCHAR(255) NOT NULL  -- TP Leave ID,
    [LEAVE_TPID] VARCHAR(255) NOT NULL  -- TP ID,
    [LEAVE_FROMDATE] DATETIME2(3) NOT NULL  -- From Date,
    [LEAVE_TODATE] DATETIME2(3) NOT NULL  -- To Date,
    [LEAVE_FROMSESSION] VARCHAR(255) NOT NULL  -- From Session,
    [LEAVE_TOSESSION] VARCHAR(255) NOT NULL  -- To Session,
    [LEAVE_TYPE] VARCHAR(255) NOT NULL  -- Type,
    [LEAVE_DAYS] VARCHAR(255) NOT NULL  -- Leave Days,
    [LEAVE_REMARKS] VARCHAR(255) NOT NULL  -- Remarks,
    [LEAVE_ID] VARCHAR(255) NOT NULL  -- Leave ID,
    CONSTRAINT [PK_TOURPLAN_LEAVE] PRIMARY KEY ([LEAVE_TPLEAVEID])
);

-- Table: TOURPLAN_NMSSCH - Travel NMS Schedule
CREATE TABLE [TOURPLAN_NMSSCH] (
    [NMSSCH_ID] VARCHAR(255) NOT NULL  -- Itenerary ID,
    [NMSSCH_TPID] VARCHAR(255) NOT NULL  -- TP ID,
    [NMSSCH_CITYID] VARCHAR(255) NOT NULL  -- City ID,
    [NMSSCH_CITYNAME] VARCHAR(255) NOT NULL  -- City Name,
    [NMSSCH_FROMDATE] DATETIME2(3) NOT NULL  -- From Date,
    [NMSSCH_FROMTIME] VARCHAR(255) NOT NULL  -- From Time,
    [NMSSCH_TODATE] DATETIME2(3) NOT NULL  -- To Date,
    [NMSSCH_TOTIME] VARCHAR(255) NOT NULL  -- To Time,
    [NMSSCH_NODAYS] VARCHAR(255) NOT NULL  -- No of Days,
    [NMSSCH_MODEID] VARCHAR(255) NOT NULL  -- Travel Mode ID,
    [NMSSCH_CLASSID] VARCHAR(255) NOT NULL  -- Travel Class ID,
    [NMSSCH_PURPOSE] VARCHAR(255) NOT NULL  -- Purpose of Travel,
    [NMSSCH_REMARKS] VARCHAR(255) NOT NULL  -- Desired Outcome,
    CONSTRAINT [PK_TOURPLAN_NMSSCH] PRIMARY KEY ([NMSSCH_ID])
);

-- Table: TOURPLAN_SLFEXP - Self Expense Ticket Details
CREATE TABLE [TOURPLAN_SLFEXP] (
    [EXP_TKTID] VARCHAR(255) NOT NULL  -- Ticket ID,
    [EXP_TPID] VARCHAR(255) NOT NULL  -- TP No,
    [EXP_EXPCAT] VARCHAR(255) NOT NULL  -- TKT/STY/CAB/MSC,
    [EXP_TRAVELMODE] VARCHAR(255) NOT NULL  -- Mode of Travel,
    [EXP_FROMDATE] DATETIME2(3) NOT NULL  -- Departure Date,
    [EXP_FROMCITY] VARCHAR(255) NOT NULL  -- Departure from,
    [EXP_FROMCITYNAME] VARCHAR(255) NOT NULL  -- From city name,
    [EXP_TODATE] DATETIME2(3) NOT NULL  -- Checkout date,
    [EXP_TOCITY] VARCHAR(255) NOT NULL  -- To City,
    [EXP_TOCITYNAME] VARCHAR(255) NOT NULL  -- To city name,
    [EXP_NOOFDAYS] VARCHAR(255) NOT NULL  -- Number of days,
    [EXP_ENTITLEVALUE] VARCHAR(255) NOT NULL  -- Entitlement amount,
    [EXP_VALUE] VARCHAR(255) NOT NULL  -- Expense value,
    [EXP_SERTAXVAL] VARCHAR(255) NOT NULL  -- Service Tax value,
    [EXP_ADLVALUE] VARCHAR(255) NOT NULL  -- Additional Charges,
    [EXP_TRAVELCLASS] VARCHAR(255) NOT NULL  -- Travel class,
    [EXP_REMARKS] VARCHAR(255) NOT NULL  -- Remarks,
    [EXP_APPROVEDAMT] VARCHAR(255) NOT NULL  -- Final approved amount,
    [EXP_FINREMARKS] VARCHAR(255) NULL  -- Finance Remarks,
    [EXP_EXPID] VARCHAR(255) NOT NULL  -- Expense ID,
    CONSTRAINT [PK_TOURPLAN_SLFEXP] PRIMARY KEY ([EXP_TKTID])
);

-- Table: TOURPLAN_FOREXMAIN - Travel Forex Requisition Main
CREATE TABLE [TOURPLAN_FOREXMAIN] (
    [FORREQ_ID] VARCHAR(255) NOT NULL  -- Forex Requisiton ID,
    [FORREQ_TPID] VARCHAR(255) NOT NULL  -- Tour Plan ID,
    [FORREQ_PASSNO] VARCHAR(255) NOT NULL  -- Passport No,
    [FORREQ_PASSNAME] VARCHAR(255) NOT NULL  -- Passport Name,
    [FORREQ_PASSLOCATION] VARCHAR(255) NOT NULL  -- Passport Location,
    [FORREQ_PASSEXPDATE] DATETIME2(3) NOT NULL  -- Passport Expiry Date,
    [FORREQ_DESTINATION] VARCHAR(255) NULL  -- Forex Destination,
    [FORREQ_STATUS] VARCHAR(255) NULL  -- Status,
    [FORREQ_DATE] VARCHAR(255) NULL  -- Requested on,
    [FORREQ_LASTMODIFIEDBY] VARCHAR(255) NOT NULL  -- Last modified by,
    [FORREQ_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last modified on,
    [FORREQ_RECEIVEDON] DATETIME2(3) NULL  -- Receipt On / Surrendered On,
    [FORREQ_REFNO] VARCHAR(255) NULL  -- Reference No,
    [FORREQ_TAX1] VARCHAR(255) NOT NULL  -- Charges,
    [FORREQ_TAX2] VARCHAR(255) NOT NULL  -- Service Tax,
    [FORREQ_TAX3] VARCHAR(255) NOT NULL  -- Edu Cess,
    [FORREQ_TAX4] VARCHAR(255) NOT NULL  -- H.E. Cess,
    [FORREQ_TAX5] VARCHAR(255) NOT NULL  -- Rounding Amount,
    [FORREQ_VENDORID] VARCHAR(255) NULL  -- Forex Vendor ID,
    [FORREQ_CURRENCY] VARCHAR(255) NULL  -- Currency,
    [FORREQ_TOTVALUE] VARCHAR(255) NULL  -- Value,
    [FORREQ_RECBY] VARCHAR(255) NULL  -- To be recommended by,
    [FORREQ_TYPE] VARCHAR(255) NOT NULL  -- R - Request ; S - Surrender,
    [FORREQ_ADLREMARKS] VARCHAR(255) NOT NULL  -- Additional forex reason,
    [FORREQ_ADVREFNO] VARCHAR(255) NOT NULL  -- Advance ID,
    [FORREQ_NETPAY] VARCHAR(255) NULL,
    [FORREQ_CURDENOADJ] VARCHAR(255) NULL,
    [FORREQ_ENCASHCERTDATE] DATETIME2(3) NULL,
    [FORREQ_BASAMT] VARCHAR(255) NULL,
    [FORREQ_CGSTAMT] VARCHAR(255) NULL,
    [FORREQ_SGSTAMT] VARCHAR(255) NULL,
    [FORREQ_IGSTAMT] VARCHAR(255) NULL,
    [FORREQ_CGSTCHARGES] VARCHAR(255) NULL,
    [FORREQ_SGSTCHARGES] VARCHAR(255) NULL,
    [FORREQ_IGSTCHARGES] VARCHAR(255) NULL,
    CONSTRAINT [PK_TOURPLAN_FOREXMAIN] PRIMARY KEY ([FORREQ_ID])
);

-- Table: TOURPLAN_FOREXDET - Travel Forex Currency breakup
CREATE TABLE [TOURPLAN_FOREXDET] (
    [FOREX_ID] VARCHAR(255) NOT NULL  -- Forex ID,
    [FOREX_REQID] VARCHAR(255) NOT NULL  -- Forex Requisiton ID,
    [FOREX_SRCVALUE] VARCHAR(255) NOT NULL  -- Source Currency Value,
    [FOREX_CURRENCY] VARCHAR(255) NOT NULL  -- Currency Code,
    [FOREX_VALUE] VARCHAR(255) NOT NULL  -- Forex Value,
    [FOREX_EXGRATE] VARCHAR(255) NULL  -- Exchange Rate,
    [FOREX_EXGVALUE] VARCHAR(255) NULL  -- Exchange Value,
    [FOREX_PAYMODE] VARCHAR(255) NULL  -- Forex Mode,
    [FOREX_REQCURVAL] VARCHAR(255) NULL,
    [FOREX_REQCURRECD] VARCHAR(255) NULL,
    CONSTRAINT [PK_TOURPLAN_FOREXDET] PRIMARY KEY ([FOREX_ID])
);

-- Table: TOURPLAN_FOREXCHQDET - tour exchange
CREATE TABLE [TOURPLAN_FOREXCHQDET] (
    [FOREX_CHQDETID] VARCHAR(255) NOT NULL,
    [FOREX_REQID] VARCHAR(255) NOT NULL,
    [FOREX_CHQNO] VARCHAR(255) NOT NULL,
    [FOREX_CHQDATE] DATETIME2(3) NULL,
    [FOREX_BANKNAME] VARCHAR(200) NOT NULL,
    CONSTRAINT [PK_TOURPLAN_FOREXCHQDET] PRIMARY KEY ([FOREX_CHQDETID])
);

-- Table: TRAVEL_DOMDABREAK - Travel Domestic DA Days Breakup
CREATE TABLE [TRAVEL_DOMDABREAK] (
    [DOMDA_ID] VARCHAR(255) NOT NULL  -- DA Break ID,
    [DOMDA_TPID] VARCHAR(255) NULL  -- Tour Plan ID,
    [DOMDA_FROMDATE] DATETIME2(3) NULL  -- Domestic DA From Date,
    [DOMDA_TODATE] DATETIME2(3) NULL  -- Domestic DA To Date,
    [DOMDA_DADAYS] VARCHAR(255) NULL  -- No of Total DA days,
    [DOMDA_DAEFFDATE] DATETIME2(3) NULL  -- Domestic DA Effective Date,
    [DOMDA_DACLSDATE] DATETIME2(3) NULL  -- Domestic DA Close Date,
    [DOMDA_DAACTUALDAYS] VARCHAR(255) NULL  -- No of Actual DA days,
    [DOMDA_DARATE] VARCHAR(255) NULL  -- DA Rate,
    [DOMDA_LEAVEDAYS] VARCHAR(255) NULL  -- Leave Days,
    [DOMDA_FOODEXPDAYS] VARCHAR(255) NULL  -- Food opted in DA Days,
    [DOMDA_OWNSTAYTDAYS] VARCHAR(255) NULL  -- Own Stay Days,
    [DOMDA_FINALDAYS] VARCHAR(255) NULL  -- Domestic DA Final Days,
    [DOMDA_FINALVALUE] VARCHAR(255) NULL  -- Domestic DA Final value,
    CONSTRAINT [PK_TRAVEL_DOMDABREAK] PRIMARY KEY ([DOMDA_ID])
);

-- Table: TRAVEL_EXPENSEINTMAIN - Travel Foreign Expense Main
CREATE TABLE [TRAVEL_EXPENSEINTMAIN] (
    [TPEXPMAIN_ID] VARCHAR(255) NOT NULL  -- Settlement ID,
    [TPEXPMAIN_TPID] VARCHAR(255) NOT NULL  -- TP ID,
    [TPEXPMAIN_CLAIMTYPE] VARCHAR(255) NULL  -- Flat/Actuals/Combination,
    [TPEXPMAIN_LOCCUR] VARCHAR(255) NULL  -- INR,
    [TPEXPMAIN_SETDATE] DATETIME2(3) NOT NULL  -- Settlement Date,
    [TPEXPMAIN_APPSETDATE] DATETIME2(3) NOT NULL  -- Approved Settlement Date,
    [TPEXPMAIN_INTCUR1] VARCHAR(255) NOT NULL  -- USD,
    [TPEXPMAIN_INTCUR2] VARCHAR(255) NOT NULL  -- EURO,
    [TPEXPMAIN_INTCNV1] VARCHAR(255) NOT NULL  -- Conversion Rate 1,
    [TPEXPMAIN_INTCNV2] VARCHAR(255) NOT NULL  -- Conversion Rate 2,
    [TPEXPMAIN_INTVAL1] VARCHAR(255) NOT NULL  -- Source Value - 1,
    [TPEXPMAIN_INTVAL2] VARCHAR(255) NOT NULL  -- Source Value - 2,
    [TPEXPMAIN_BALAMT] VARCHAR(255) NOT NULL  -- Balance Amount Payable,
    CONSTRAINT [PK_TRAVEL_EXPENSEINTMAIN] PRIMARY KEY ([TPEXPMAIN_ID])
);

-- Table: TRAVEL_EXPENSEINTDET - Travel Foreign Expense Detail
CREATE TABLE [TRAVEL_EXPENSEINTDET] (
    [TPEXPDET_ID] VARCHAR(255) NOT NULL  -- Detail ID,
    [TPEXPDET_TPID] VARCHAR(255) NOT NULL  -- Detail ID,
    [TPEXPDET_GROUPID] VARCHAR(255) NOT NULL  -- Group ID,
    [TPEXPDET_CURRENCY] VARCHAR(255) NOT NULL  -- Currency,
    [TPEXPDET_VALUE] VARCHAR(255) NOT NULL  -- Value,
    [TPEXPDET_ACTVALUE] VARCHAR(255) NOT NULL  -- Actual Value,
    [TPEXPDET_APPAMT] VARCHAR(255) NOT NULL  -- Approved Amount,
    [TPEXPDET_EXPFLAG] VARCHAR(255) NOT NULL  -- Expense Flag,
    CONSTRAINT [PK_TRAVEL_EXPENSEINTDET] PRIMARY KEY ([TPEXPDET_ID])
);

-- Table: TRAVEL_EXPENSEINTBRK - Travel Foreign Expense Breakup
CREATE TABLE [TRAVEL_EXPENSEINTBRK] (
    [TPEXPBRK_ID] VARCHAR(255) NOT NULL  -- Break ID,
    [TPEXPBRK_DETID] VARCHAR(255) NOT NULL  -- Detail ID,
    [TPEXPBRK_EXPID] VARCHAR(255) NOT NULL  -- Expense ID,
    [TPEXPBRK_DATE] DATETIME2(3) NULL  -- Date,
    [TPEXPBRK_REMARKS] VARCHAR(255) NOT NULL  -- Remarks,
    [TPEXPBRK_AMT] VARCHAR(255) NOT NULL  -- Amount,
    [TPEXPBRK_ACTAMT] VARCHAR(255) NOT NULL  -- Actual Value,
    [TPEXPBRK_APPAMT] VARCHAR(255) NOT NULL  -- Approved Amount,
    [TPEXPBRK_PAYMODE] VARCHAR(255) NULL  -- Payment Mode,
    CONSTRAINT [PK_TRAVEL_EXPENSEINTBRK] PRIMARY KEY ([TPEXPBRK_ID])
);

PRINT 'TOURPLAN Module - Tables created successfully.';
GO
