-- =============================================
-- 09-Transaction Tables
-- Travel Transaction Service
-- =============================================

-- VENDOR_MASTER
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VENDOR_MASTER]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[VENDOR_MASTER] (
    [VENDOR_ID]       NUMERIC(15,0) NOT NULL,
    [NAME]            VARCHAR(240)  NOT NULL,
    [ADDRESS_LINE1]   VARCHAR(240)  NULL,
    [ADDRESS_LINE2]   VARCHAR(240)  NULL,
    [ADDRESS_LINE3]   VARCHAR(240)  NULL,
    [CITY_CODE]       NUMERIC(15,0) NULL,
    [IT_PAN_NUMBER]   VARCHAR(20)   NULL,
    [PHONE_NUMBER]    VARCHAR(20)   NULL,
    [ACCOUNT_NUMBER]  VARCHAR(30)   NULL,
    [BANK_NAME]       VARCHAR(100)  NULL,
    [CATEGORY_TYPE]   VARCHAR(1)    NOT NULL DEFAULT 'V',
    CONSTRAINT [PK_VENDOR_MASTER] PRIMARY KEY CLUSTERED ([VENDOR_ID])
);
END
GO

-- ACC_MASTER (keyless)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ACC_MASTER]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[ACC_MASTER] (
    [COMPANY_CODE]        VARCHAR(10)  NULL,
    [ED_CODE]             VARCHAR(10)  NULL,
    [ACCOUNT_CODE]        VARCHAR(20)  NULL,
    [GRADE_TYPE]          VARCHAR(10)  NULL,
    [DEBIT_CREDIT_FLAG]   VARCHAR(1)   NULL,
    [SUB_CODE]            VARCHAR(10)  NULL,
    [ACCOUNT_DESCRIPTION] VARCHAR(240) NULL
);
END
GO

-- GL_CODE_COMBINATIONS_KFV
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GL_CODE_COMBINATIONS_KFV]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[GL_CODE_COMBINATIONS_KFV] (
    [ROWID]                  NUMERIC(15,0)  NOT NULL,
    [CODE_COMBINATION_ID]    NUMERIC(15,0)  NOT NULL,
    [CHART_OF_ACCOUNTS_ID]   NUMERIC(15,0)  NOT NULL,
    [CONCATENATED_SEGMENTS]  VARCHAR(200)   NULL,
    [GL_ACCOUNT_TYPE]        VARCHAR(25)    NOT NULL,
    [ENABLED_FLAG]           VARCHAR(1)     NOT NULL DEFAULT 'Y',
    [SEGMENT1]               VARCHAR(25)    NULL,
    [SEGMENT2]               VARCHAR(25)    NULL,
    [SEGMENT3]               VARCHAR(25)    NULL,
    [DESCRIPTION]            VARCHAR(240)   NULL,
    CONSTRAINT [PK_GL_CODE_COMB] PRIMARY KEY CLUSTERED ([ROWID])
);
END
GO

-- TAX_MASTER
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TAX_MASTER]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TAX_MASTER] (
    [TAX_VENDOR_ID]       NUMERIC(15,0) NOT NULL,
    [TAX_TYPE]            VARCHAR(10)   NOT NULL,
    [TAX_RATE]            NUMERIC(5,2)  NULL,
    [TAX_EFFECTIVE_DATE]  DATETIME      NOT NULL,
    [TAX_CLOSE_DATE]      DATETIME      NULL,
    [CREATED_BY]          NUMERIC(15,0) NULL,
    [CREATION_DATE]       DATETIME      NULL DEFAULT GETDATE(),
    [LAST_UPDATED_BY]     NUMERIC(15,0) NULL,
    [LAST_UPDATE_DATE]    DATETIME      NULL,
    CONSTRAINT [PK_TAX_MASTER] PRIMARY KEY CLUSTERED ([TAX_TYPE])
);
END
GO

-- TAX_COMPONENT (keyless)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TAX_COMPONENT]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TAX_COMPONENT] (
    [VENDOR_CODE] NUMERIC(15,0) NOT NULL,
    [COMPONENT]   VARCHAR(50)   NULL
);
END
GO

-- JV_INTERFACE (keyless)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[JV_INTERFACE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[JV_INTERFACE] (
    [CODE_COMBINATION] NUMERIC(15,0) NULL,
    [SEGMENT1]         VARCHAR(25)   NULL,
    [IO]               NUMERIC(15,0) NULL,
    [UNIT]             VARCHAR(10)   NULL
);
END
GO

-- JV_MISSING_COMBICODE (keyless)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[JV_MISSING_COMBICODE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[JV_MISSING_COMBICODE] (
    [AGENCY_NAME]             VARCHAR(240) NULL,
    [INVOICE_NUMBER]          VARCHAR(50)  NULL,
    [DESCRIPTION]             VARCHAR(240) NULL,
    [DIST_CODE_CONCATENATED]  VARCHAR(200) NULL,
    [JV_NUMBER]               NUMERIC(15,0) NULL,
    [LOG_SYSID]               NUMERIC(15,0) NULL
);
END
GO

-- JAI_INTERFACE_LINES_ALL (keyless)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[JAI_INTERFACE_LINES_ALL]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[JAI_INTERFACE_LINES_ALL] (
    [INTERFACE_LINE_ID]      NUMERIC(15,0) NULL,
    [ORG_ID]                 NUMERIC(15,0) NOT NULL,
    [PARTY_ID]               NUMERIC(15,0) NOT NULL,
    [PARTY_SITE_ID]          NUMERIC(15,0) NOT NULL,
    [IMPORT_MODULE]          VARCHAR(20)   NOT NULL,
    [TRANSACTION_NUM]        VARCHAR(50)   NOT NULL,
    [TRANSACTION_LINE_NUM]   NUMERIC(15,0) NOT NULL,
    [ERROR_FLAG]             VARCHAR(1)    NULL,
    [IMPORT_STATUS]          VARCHAR(20)   NULL,
    [BATCH_ID]               NUMERIC(15,0) NULL,
    [INVOICE_ID]             NUMERIC(15,0) NULL,
    [TYPE]                   VARCHAR(20)   NULL,
    [SGST_AMOUNT]            NUMERIC(15,2) NULL,
    [CGST_AMOUNT]            NUMERIC(15,2) NULL,
    [IGST_AMOUNT]            NUMERIC(15,2) NULL,
    [JV_NUMBER]              NUMERIC(15,0) NULL,
    [CREATED_BY]             NUMERIC(15,0) NULL,
    [CREATION_DATE]          DATETIME      NULL DEFAULT GETDATE(),
    [LAST_UPDATED_BY]        NUMERIC(15,0) NULL,
    [LAST_UPDATE_DATE]       DATETIME      NULL
);
END
GO

-- JAI_INTERFACE_TAX_LINES_ALL (keyless)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[JAI_INTERFACE_TAX_LINES_ALL]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[JAI_INTERFACE_TAX_LINES_ALL] (
    [INTERFACE_TAX_LINE_ID]  NUMERIC(15,0) NULL,
    [INTERFACE_LINE_ID]      NUMERIC(15,0) NULL,
    [TAX_LINE_NO]            NUMERIC(15,0) NOT NULL,
    [EXTERNAL_TAX_CODE]      VARCHAR(30)   NULL,
    [TAX_RATE]               NUMERIC(5,2)  NULL,
    [TAX_AMOUNT]             NUMERIC(15,2) NULL,
    [CODE_COMBINATION_ID]    NUMERIC(15,0) NULL
);
END
GO

-- TRAVEL_BATCH_SUB_BREAKUP (keyless)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRAVEL_BATCH_SUB_BREAKUP]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TRAVEL_BATCH_SUB_BREAKUP] (
    [SLNO]             NUMERIC(15,0) NOT NULL,
    [BOOKNO]           NUMERIC(15,0) NOT NULL,
    [COST_UNIT]        VARCHAR(10)   NOT NULL,
    [COST_CODE]        VARCHAR(10)   NOT NULL,
    [PRODUCT_CODE]     VARCHAR(10)   NULL,
    [SUBACCOUNT_CODE]  VARCHAR(10)   NULL
);
END
GO

-- TRAVEL_AP_PARAMS
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRAVEL_AP_PARAMS]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TRAVEL_AP_PARAMS] (
    [AP_UNIT_ID]       NUMERIC(15,0) NOT NULL,
    [ACCOUNT_STATUS]   VARCHAR(10)   NOT NULL,
    [ACCOUNT_CODE]     VARCHAR(30)   NOT NULL,
    [CONTROL_COMB_ID]  NUMERIC(15,0) NULL,
    CONSTRAINT [PK_TRAVEL_AP_PARAMS] PRIMARY KEY CLUSTERED ([AP_UNIT_ID])
);
END
GO

-- SOURCE_HIST (keyless)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SOURCE_HIST]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[SOURCE_HIST] (
    [CHANGE_DATE]  DATETIME     NULL,
    [NAME]         VARCHAR(100) NULL,
    [TYPE]         VARCHAR(50)  NULL,
    [LINE]         NUMERIC(15,0) NULL,
    [TEXT]         VARCHAR(4000) NULL
);
END
GO

-- Indexes
CREATE NONCLUSTERED INDEX [IX_VENDOR_MASTER_CATEGORY] ON [dbo].[VENDOR_MASTER] ([CATEGORY_TYPE]) WHERE [CATEGORY_TYPE] IS NOT NULL;
GO
CREATE NONCLUSTERED INDEX [IX_TAX_MASTER_VENDOR] ON [dbo].[TAX_MASTER] ([TAX_VENDOR_ID]);
GO
CREATE NONCLUSTERED INDEX [IX_JAI_LINES_BATCH] ON [dbo].[JAI_INTERFACE_LINES_ALL] ([BATCH_ID]) WHERE [BATCH_ID] IS NOT NULL;
GO
CREATE NONCLUSTERED INDEX [IX_JAI_TAX_LINES_LINE] ON [dbo].[JAI_INTERFACE_TAX_LINES_ALL] ([INTERFACE_LINE_ID]) WHERE [INTERFACE_LINE_ID] IS NOT NULL;
GO
