-- AUTH MODULE - Stored Procedures
-- User authentication and registration procedures

USE [Careers]
GO

/****** SP_LOGIN ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_LOGIN] 
(
@PERSONAL_MAIID varchar(50),
@Password varchar(30),
@Status varchar(40) output
)
AS
BEGIN

IF EXISTS (SELECT LOGIN_ID from REGISTRATION_TABLE where PERSONAL_MAIID=@PERSONAL_MAIID and ISVALID=1)
	begin
	
	if Exists (SELECT * from REGISTRATION_TABLE where PERSONAL_MAIID=@PERSONAL_MAIID and PASSWORD=@Password  and ISVALID=1)
		begin
		--SELECT * from spa_user where userid=@userid and password=@password--
		set @Status='Success'
		end
	else
		begin
		set @Status='Password does not match..'
		end
	
	end
else
	begin
	set @Status='Invalid User Id..'
	end
	
END
GO

/****** SP_CHANGE_PASSWORD ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_CHANGE_PASSWORD]
(
@PERSONAL_MAIID VARCHAR(30),
@OLDPASSWORD VARCHAR(30),
@NEWPASSWORD VARCHAR(30),
@STATUS VARCHAR(30) OUTPUT
)
AS
BEGIN

IF ((SELECT COUNT(*) FROM REGISTRATION_TABLE WHERE PERSONAL_MAIID=@PERSONAL_MAIID AND ISVALID=1)>0)
	BEGIN
	
	IF((SELECT COUNT(*) FROM REGISTRATION_TABLE WHERE PERSONAL_MAIID=@PERSONAL_MAIID AND ISVALID=1 AND PASSWORD=@OLDPASSWORD)>0)
		BEGIN
		UPDATE REGISTRATION_TABLE SET PASSWORD=@NEWPASSWORD WHERE PERSONAL_MAIID=@PERSONAL_MAIID
		SET @STATUS='SUCCESS'
		END
	ELSE
		BEGIN
		SET @STATUS='PASSWORD INCORECT'
		END	
	
	END
	
ELSE
	BEGIN
	SET @STATUS='INVALID'
	END	

END
GO

/****** SP_REGISTER ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_REGISTER]
(
	   @PASSWORD VARCHAR(30)
      ,@FIRST_NAME VARCHAR(50)
      ,@MIDDLE_NAME VARCHAR(50)
      ,@LAST_NAME VARCHAR(50)
      ,@INITIAL VARCHAR(5)
      ,@JOB_APPLIED_FOR varchar(50)
      ,@PERSONAL_MAIID VARCHAR(50)
      ,@OFFICEAL_MAILID VARCHAR(50)      
      ,@FUNCTIONS VARCHAR(50)
      ,@INDUSTRY_DOMAIN VARCHAR(50)
      ,@EXPERIENCE_IN_YEAR INT
      ,@CURRENT_LOCATION VARCHAR(50)
      ,@PREFERED_LOCATION VARCHAR(50)
      ,@MOBILE_NO VARCHAR(20)
      ,@ISVALID BIT
      ,@RESULT BIGINT  OUTPUT  
)
AS
BEGIN
IF((SELECT COUNT(*) FROM REGISTRATION_TABLE WHERE [PERSONAL_MAIID]=@PERSONAL_MAIID)=0)
BEGIN
INSERT INTO REGISTRATION_TABLE
	(
	   [PASSWORD]	
      ,[FIRST_NAME]
      ,[MIDDLE_NAME]
      ,[LAST_NAME]      
      ,[INITIAL]
      ,[PERSONAL_MAIID]
      ,[OFFICEAL_MAILID] 
      ,[USER_TYPE]     
      ,[ISVALID]
      ,[ENTERED_ON]
     
      
	)
	VALUES
	(
	   @PASSWORD	
      ,@FIRST_NAME
      ,@MIDDLE_NAME
      ,@LAST_NAME
      ,@INITIAL      
      ,@PERSONAL_MAIID
      ,@OFFICEAL_MAILID  
      ,'CANDIDATE'    
      ,@ISVALID
      ,GETDATE()
      
      
	)
	
	DECLARE @LOGIN_ID BIGINT
	SET @LOGIN_ID=(SELECT @@IDENTITY)
	
INSERT INTO REGISTERED_JOBS
	(
		[LOGIN_ID]
		,[JOB_APPLIED_FOR]
      ,[FUNCTIONS]
      ,[INDUSTRY_DOMAIN]
      ,[EXPERIENCE_IN_YEAR]
      ,[CURRENT_LOCATION]
      ,[PREFERED_LOCATION]
      ,[MOBILE_NO]
      ,[ISVALID]
      ,[ENTERED_ON]
	)
	VALUES
	(
		@LOGIN_ID
		,@JOB_APPLIED_FOR
      ,@FUNCTIONS
      ,@INDUSTRY_DOMAIN
      ,@EXPERIENCE_IN_YEAR
      ,@CURRENT_LOCATION
      ,@PREFERED_LOCATION
      ,@MOBILE_NO
      ,@ISVALID
      ,GETDATE()
	)	
	SET @RESULT=@LOGIN_ID
END
ELSE
BEGIN
SET @RESULT=0
END

END
GO

/****** SP_GET_LOGINID ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_GET_LOGINID]
(
@PERSONAL_MAIID VARCHAR(50)
)
AS
BEGIN
SELECT  [LOGIN_ID]
      ,[FIRST_NAME]
      ,[MIDDLE_NAME]
      ,[LAST_NAME]
      ,[PERSONAL_MAIID]
      ,[OFFICEAL_MAILID]
      ,[PASSWORD]
      ,[USER_TYPE]
      ,[ISVALID]
      ,[ENTERED_ON]
      ,[CHANGED_ON]
      ,[INITIAL]
      ,[UserDept]
  FROM [CAREERS].[dbo].[REGISTRATION_TABLE] WHERE [PERSONAL_MAIID]=@PERSONAL_MAIID AND ISVALID=1
  END
GO

/****** SP_GET_PASSWORD ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_GET_PASSWORD] 
(
@PERSONAL_MAIID varchar(50),
@DATE_OF_BIRTH DATETIME,
@STATUS varchar(40) output
)
AS
BEGIN

IF EXISTS (SELECT LOGIN_ID from REGISTRATION_TABLE where PERSONAL_MAIID=@PERSONAL_MAIID and ISVALID=1)
	begin
	
	if Exists (SELECT * from REGISTRATION_TABLE INNER JOIN PERSONAL_DETAILS on REGISTRATION_TABLE.LOGIN_ID=PERSONAL_DETAILS.LOGIN_ID where REGISTRATION_TABLE.PERSONAL_MAIID=@PERSONAL_MAIID and PERSONAL_DETAILS.DATE_OF_BIRTH=@DATE_OF_BIRTH  and REGISTRATION_TABLE.ISVALID=1)
		begin
		--SELECT * from spa_user where userid=@userid and password=@password--
		set @STATUS=(SELECT REGISTRATION_TABLE.PASSWORD from REGISTRATION_TABLE INNER JOIN PERSONAL_DETAILS on REGISTRATION_TABLE.LOGIN_ID=PERSONAL_DETAILS.LOGIN_ID where REGISTRATION_TABLE.PERSONAL_MAIID=@PERSONAL_MAIID and PERSONAL_DETAILS.DATE_OF_BIRTH=@DATE_OF_BIRTH  and REGISTRATION_TABLE.ISVALID=1)
		end
	else
		begin
		set @STATUS='Invalid Date of Birth..'
		end
	
	end
else
	begin
	set @STATUS='Invalid User Id..'
	end
	
END
GO

/****** SP_GET_SMTP ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_GET_SMTP]
AS
BEGIN
SELECT * FROM SMTP_DETAILS WHERE ISVALID=1
END
GO
