-- AUTH MODULE - Schema Definition
-- User authentication and registration management
-- Date: Migrated from monolithic careersall.sql

USE [Careers]
GO

/****** REGISTRATION_TABLE ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[REGISTRATION_TABLE](
	[LOGIN_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[FIRST_NAME] [varchar](50) NULL,
	[MIDDLE_NAME] [varchar](50) NULL,
	[LAST_NAME] [varchar](50) NULL,
	[PERSONAL_MAIID] [varchar](50) NULL,
	[OFFICEAL_MAILID] [varchar](50) NULL,
	[PASSWORD] [varchar](30) NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[CHANGED_ON] [datetime] NULL
) ON [PRIMARY]
SET ANSI_PADDING ON
ALTER TABLE [dbo].[REGISTRATION_TABLE] ADD [INITIAL] [varchar](5) NULL
ALTER TABLE [dbo].[REGISTRATION_TABLE] ADD [USER_TYPE] [varchar](10) NULL
ALTER TABLE [dbo].[REGISTRATION_TABLE] ADD [UserDept] [varchar](10) NULL
ALTER TABLE [dbo].[REGISTRATION_TABLE] ADD PRIMARY KEY CLUSTERED 
(
	[LOGIN_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** SMTP_DETAILS ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SMTP_DETAILS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SMTP_IP] [varchar](15) NULL,
	[PORTNO] [varchar](10) NULL,
	[ISVALID] [bit] NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
