// <auto-generated />
using System;
using IntegrationService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntegrationService.Infrastructure.Migrations
{
    [DbContext(typeof(IntegrationDbContext))]
    [Migration("20260319142708_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntegrationService.Domain.Entities.MaterialReceiptCertificate", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("MRC_SEQID");

                    b.Property<string>("MrcNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("MRC_NO");

                    b.Property<long>("PurchaseOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("MRC_POID");

                    b.Property<DateTime?>("ReceiveDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("MRC_RECDATE");

                    b.Property<long?>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("MRC_SEQNO");

                    b.Property<long?>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("MRC_VENDID");

                    b.Property<long?>("VendorSiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("MRC_VENSITEID");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("ORA_MRCMAST", (string)null);
                });

            modelBuilder.Entity("IntegrationService.Domain.Entities.OrganizationUnit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("OU_ID");

                    b.Property<string>("BuId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("OU_BUID");

                    b.Property<string>("OuName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("OU_NAME");

                    b.HasKey("Id");

                    b.ToTable("ORA_OUMAST", (string)null);
                });

            modelBuilder.Entity("IntegrationService.Domain.Entities.OuBuMapping", b =>
                {
                    b.Property<string>("BuId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("OU_BUID");

                    b.Property<long>("OuId")
                        .HasColumnType("bigint")
                        .HasColumnName("OU_ID");

                    b.ToTable("ORA_OU_BUMAP", (string)null);
                });

            modelBuilder.Entity("IntegrationService.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("PO_SEQID");

                    b.Property<long>("OracleOrgId")
                        .HasColumnType("bigint")
                        .HasColumnName("PO_OUID");

                    b.Property<long>("OraclePoId")
                        .HasColumnType("bigint")
                        .HasColumnName("PO_ID");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("PO_NO");

                    b.Property<long>("VendorSiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("PO_VENDORSITEID");

                    b.HasKey("Id");

                    b.HasIndex("OraclePoId")
                        .IsUnique();

                    b.ToTable("ORA_POMAST", (string)null);
                });

            modelBuilder.Entity("IntegrationService.Domain.Entities.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("VENDOR_ID");

                    b.Property<string>("VendorCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("VENDOR_CODE");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("VENDOR_NAME");

                    b.HasKey("Id");

                    b.ToTable("ORA_VENDORMAST", (string)null);
                });

            modelBuilder.Entity("IntegrationService.Domain.Entities.VendorSite", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("VENDOR_SITEID");

                    b.Property<string>("OracleOuId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("VENDOR_OUID");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("VENDOR_SITECODE");

                    b.Property<int>("VendorId")
                        .HasColumnType("int")
                        .HasColumnName("VENDOR_ID");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("ORA_VENDORSITEMAST", (string)null);
                });

            modelBuilder.Entity("IntegrationService.Domain.Entities.VendorSiteBuMapping", b =>
                {
                    b.Property<long>("VendorSiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("VENDOR_SITEID");

                    b.Property<long>("BuId")
                        .HasColumnType("bigint")
                        .HasColumnName("VENDOR_BUID");

                    b.HasKey("VendorSiteId");

                    b.ToTable("ORA_VENDORSITEBUMAP", (string)null);
                });

            modelBuilder.Entity("IntegrationService.Domain.Entities.MaterialReceiptCertificate", b =>
                {
                    b.HasOne("IntegrationService.Domain.Entities.PurchaseOrder", null)
                        .WithMany("MaterialReceipts")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrationService.Domain.Entities.PurchaseOrder", b =>
                {
                    b.OwnsOne("IntegrationService.Domain.ValueObjects.PaymentTerms", "PaymentTerms", b1 =>
                        {
                            b1.Property<long>("PurchaseOrderId")
                                .HasColumnType("bigint");

                            b1.Property<long>("DueDayMonthOffset")
                                .HasColumnType("bigint")
                                .HasColumnName("PO_DUE_DAY_MONTHOFF");

                            b1.Property<long>("DueDays")
                                .HasColumnType("bigint")
                                .HasColumnName("PO_DUEDAYS");

                            b1.Property<long>("MonthForward")
                                .HasColumnType("bigint")
                                .HasColumnName("PO_MONTHFORWARD");

                            b1.HasKey("PurchaseOrderId");

                            b1.ToTable("ORA_POMAST");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");
                        });

                    b.Navigation("PaymentTerms")
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrationService.Domain.Entities.VendorSite", b =>
                {
                    b.HasOne("IntegrationService.Domain.Entities.Vendor", null)
                        .WithMany("VendorSites")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrationService.Domain.Entities.VendorSiteBuMapping", b =>
                {
                    b.HasOne("IntegrationService.Domain.Entities.VendorSite", null)
                        .WithMany("BuMappings")
                        .HasForeignKey("VendorSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrationService.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("MaterialReceipts");
                });

            modelBuilder.Entity("IntegrationService.Domain.Entities.Vendor", b =>
                {
                    b.Navigation("VendorSites");
                });

            modelBuilder.Entity("IntegrationService.Domain.Entities.VendorSite", b =>
                {
                    b.Navigation("BuMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
