-- EmployeeManagement Module - Tables
USE [HRDB];
GO

-- Table: EMPLOYEE_ADDRESS
CREATE TABLE [EMPLOYEE_ADDRESS] (
    [ADDRESS_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [ADDRESS_FLAG] CHAR(1) NOT NULL  -- Address Flag - C/P,
    [ADDRESS_1] VARCHAR(65) NULL  -- Address - 1,
    [ADDRESS_2] VARCHAR(65) NULL  -- Address - 2,
    [ADDRESS_3] VARCHAR(65) NULL  -- Address - 3,
    [ADDRESS_4] VARCHAR(65) NULL  -- Address - 4,
    [ADDRESS_CITY] DECIMAL(38) NULL  -- City,
    [ADDRESS_PINCODE] DECIMAL(38) NULL  -- PIN Code,
    [ADDRESS_UPDATEDBY] DECIMAL(38) NULL  -- Last updated by,
    [ADDRESS_UPDATEDON] DATETIME2(3) NULL  -- Last updated on,
    [ADDRESS_STATE] DECIMAL(22,0) NULL,
    [ADDRESS_CITYOTHERS] VARCHAR(65) NULL,
    CONSTRAINT [PK_EMPLOYEE_ADDRESS] PRIMARY KEY ([ADDRESS_EMP_SYSID])
);



-- Table: EMPLOYEE_CAREER
CREATE TABLE [EMPLOYEE_CAREER] (
    [CAREER_ID] DECIMAL(38) NOT NULL,
    [CAREER_EMP_SYSID] DECIMAL(38) NOT NULL,
    [CAREER_BUSINESS] CHAR(9) NULL,
    [CAREER_UNIT] CHAR(3) NULL,
    [CAREER_FROM] DATETIME2(3) NULL,
    [CAREER_TO] DATETIME2(3) NULL,
    [CAREER_EMPNO] VARCHAR(20) NULL,
    [CAREER_GRADE] DECIMAL(38) NULL,
    [CAREER_GRADEOTH] VARCHAR(50) NULL,
    [CAREER_DESIGNATION] VARCHAR(50) NULL,
    [CAREER_DIVISION] DECIMAL(38) NULL,
    [CAREER_DIVISIONOTH] VARCHAR(50) NULL,
    [CAREER_PROCESS] DECIMAL(38) NULL,
    [CAREER_PROCESSOTH] VARCHAR(50) NULL,
    [CAREER_DEPARTMENT] DECIMAL(38) NULL,
    [CAREER_DEPARTMENTOTH] VARCHAR(50) NULL,
    [CAREER_REASON] VARCHAR(150) NULL,
    [CAREER_MODIFIEDBY] DECIMAL(38) NULL,
    [CAREER_MODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_EMPLOYEE_CAREER] PRIMARY KEY ([CAREER_ID])
);



-- Table: EMPLOYEE_CAREER_HIST
CREATE TABLE [EMPLOYEE_CAREER_HIST] (
    [CAREER_TRN_NO] DECIMAL(38) NULL,
    [CAREER_ID] DECIMAL(38) NULL,
    [CAREER_BUSINESS] CHAR(9) NULL,
    [CAREER_UNIT] CHAR(3) NULL,
    [CAREER_FROM] DATETIME2(3) NULL,
    [CAREER_TO] DATETIME2(3) NULL,
    [CAREER_EMPNO] VARCHAR(20) NULL,
    [CAREER_GRADE] DECIMAL(38) NULL,
    [CAREER_GRADEOTH] VARCHAR(50) NULL,
    [CAREER_DESIGNATION] VARCHAR(50) NULL,
    [CAREER_DIVISION] DECIMAL(38) NULL,
    [CAREER_DIVISIONOTH] VARCHAR(50) NULL,
    [CAREER_PROCESS] DECIMAL(38) NULL,
    [CAREER_PROCESSOTH] VARCHAR(50) NULL,
    [CAREER_DEPARTMENT] DECIMAL(38) NULL,
    [CAREER_DEPARTMENTOTH] VARCHAR(50) NULL,
    [CAREER_REASON] VARCHAR(150) NULL,
    [CAREER_NEW_OLD] DECIMAL(38) NULL
);



-- Table: EMPLOYEE_QUALIFICATION
CREATE TABLE [EMPLOYEE_QUALIFICATION] (
    [QUAL_ID] DECIMAL(38) NOT NULL  -- Qualification ID,
    [QUAL_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [QUAL_CODE] DECIMAL(38) NULL  -- Qualification Code,
    [QUAL_DESC] VARCHAR(65) NULL  -- Qualification Description,
    [QUAL_YEARFRO] CHAR(6) NULL  -- Year from (MMYYYY),
    [QUAL_YEARTO] CHAR(6) NULL  -- Year to (MMYYYY),
    [QUAL_INST_CODE] DECIMAL(22,0) NULL  -- Institution Code,
    [QUAL_INST_DESC] VARCHAR(65) NULL  -- Institution Description,
    [QUAL_EDU_TYPE] CHAR(1) NULL  -- F - Full Time ; P - Partime ; C - Correspondance,
    [QUAL_SPE_CODE] DECIMAL(38) NULL  -- Specialization Code,
    [QUAL_SPE_DESC] VARCHAR(65) NULL  -- Specialization Description,
    [QUAL_PERCENTAGE] VARCHAR(10) NULL  -- Percentage / Class,
    [QUAL_DEGREE_CODE] DECIMAL(38) NULL  -- Degree Code,
    [QUAL_DEGREE_DESC] VARCHAR(65) NULL  -- Degree Description,
    [QUAL_UPDATEDBY] DECIMAL(38) NULL  -- Last updated by,
    [QUAL_UPDATEDON] DATETIME2(3) NULL  -- Last updated on,
    CONSTRAINT [PK_EMPLOYEE_QUALIFICATION] PRIMARY KEY ([QUAL_ID])
);



-- Table: EMPLOYEE_QUALIFICATION_HIST
CREATE TABLE [EMPLOYEE_QUALIFICATION_HIST] (
    [QUAL_TRN_NO] DECIMAL(38) NOT NULL,
    [QUAL_ID] DECIMAL(38) NOT NULL,
    [QUAL_CODE] DECIMAL(38) NULL,
    [QUAL_DESC] VARCHAR(65) NULL,
    [QUAL_YEARFRO] CHAR(6) NULL,
    [QUAL_YEARTO] CHAR(6) NULL,
    [QUAL_INST_CODE] DECIMAL(22,0) NULL,
    [QUAL_INST_DESC] VARCHAR(65) NULL,
    [QUAL_EDU_TYPE] CHAR(1) NULL,
    [QUAL_SPE_CODE] DECIMAL(38) NULL,
    [QUAL_SPE_DESC] VARCHAR(65) NULL,
    [QUAL_PERCENTAGE] VARCHAR(10) NULL,
    [QUAL_DEGREE_CODE] DECIMAL(38) NULL,
    [QUAL_DEGREE_DESC] VARCHAR(65) NULL,
    [QUAL_NEW_OLD] DECIMAL(38) NULL
);



-- Table: EMPLOYEE_LANGUAGE
CREATE TABLE [EMPLOYEE_LANGUAGE] (
    [LANGUAGE_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [LANGUAGE_ID] DECIMAL(38) NOT NULL  -- Language ID,
    [LANGUAGE_TYPE] CHAR(3) NULL  -- Language Type (SRW) S- Speak; R-Read; W-Write,
    [LANGUAGE_UPDATEDBY] DECIMAL(38) NULL  -- Last updated by,
    [LANGUAGE_UPDATEDON] DATETIME2(3) NULL  -- Last updated on,
    CONSTRAINT [PK_EMPLOYEE_LANGUAGE] PRIMARY KEY ([LANGUAGE_EMP_SYSID])
);



-- Table: EMPLOYEE_DIARY
CREATE TABLE [EMPLOYEE_DIARY] (
    [DIARY_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [DIARY_ID] DECIMAL(38) NOT NULL  -- Diary ID,
    [DIARY_TYPE] CHAR(1) NOT NULL  -- A - Awards ; R - Recognition,
    [DIARY_SUBTYPE] DECIMAL(38) NOT NULL  -- Sub type - (Awards/Recognitions),
    [DIARY_DATE] CHAR(6) NULL  -- MMYYYY,
    [DIARY_REASON] VARCHAR(200) NULL  -- Remarks,
    [DIARY_UPDATED_BY] DECIMAL(38) NULL  -- Last updated by,
    [DIARY_UPDATED_ON] DATETIME2(3) NULL  -- Last updated on,
    CONSTRAINT [PK_EMPLOYEE_DIARY] PRIMARY KEY ([DIARY_EMP_SYSID])
);



-- Table: EMP_DEPARTMENT
CREATE TABLE [EMP_DEPARTMENT] (
    [DEPARTMENT_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [DEPARTMENT_TRANID] DECIMAL(38) NOT NULL  -- Transaction ID,
    [DEPARTMENT_ID] DECIMAL(38) NULL  -- Department ID,
    [DEPARTMENT_EFF_DATE] DATETIME2(3) NULL  -- Effective Date,
    [DEPARTMENT_CLS_DATE] DATETIME2(3) NULL  -- Closure Date,
    [DEPARTMENT_REMARKS] VARCHAR(65) NULL  -- Remarks,
    [DEPARTMENT_LIVFLAG] CHAR(1) NULL  -- Live Flag,
    [DEPARTMENT_BATCHNO] DECIMAL(38) NULL  -- Batch No,
    [DEPARTMENT_UPDATEDBY] DECIMAL(38) NULL  -- Last updated by,
    [DEPARTMENT_UPDATEDON] DATETIME2(3) NULL  -- Last updated on,
    [DEPARTMENT_UNITID] DECIMAL(38) NULL,
    CONSTRAINT [PK_EMP_DEPARTMENT] PRIMARY KEY ([DEPARTMENT_EMP_SYSID])
);



-- Table: EMP_DIVISION
CREATE TABLE [EMP_DIVISION] (
    [DIVISION_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [DIVISION_TRANID] DECIMAL(38) NOT NULL  -- Transaction ID,
    [DIVISION_ID] DECIMAL(38) NOT NULL  -- Division ID,
    [DIVISION_EFF_DATE] DATETIME2(3) NULL  -- Effective Date,
    [DIVISION_CLS_DATE] DATETIME2(3) NULL  -- Closure Date,
    [DIVISION_REMARKS] VARCHAR(65) NULL  -- Remarks,
    [DIVISION_LIVFLAG] CHAR(1) NULL  -- Live Flag,
    [DIVISION_BATCHNO] DECIMAL(38) NULL  -- Batch No,
    [DIVISION_UPDATEDBY] DECIMAL(38) NULL  -- Last updated by,
    [DIVISION_UPDATEDON] DATETIME2(3) NULL  -- Last updated on,
    CONSTRAINT [PK_EMP_DIVISION] PRIMARY KEY ([DIVISION_EMP_SYSID])
);



-- Table: EMP_GRADE
CREATE TABLE [EMP_GRADE] (
    [GRADE_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [GRADE_TRANID] DECIMAL(38) NOT NULL  -- Transaction ID,
    [GRADE_ID] DECIMAL(38) NOT NULL  -- Grade ID,
    [GRADE_EFF_DATE] DATETIME2(3) NULL  -- Effective Date,
    [GRADE_CLS_DATE] DATETIME2(3) NULL  -- Closure Date,
    [GRADE_REMARKS] VARCHAR(65) NULL  -- Remarks,
    [GRADE_LIVFLAG] CHAR(1) NULL  -- Live Flag,
    [GRADE_BATCHNO] DECIMAL(38) NULL  -- Batch No,
    [GRADE_UPDATEDBY] DECIMAL(38) NULL  -- Last updated by,
    [GRADE_UPDATEDON] DATETIME2(3) NULL  -- Last updated on,
    [GRADE_PROBATION] CHAR(1) NULL,
    CONSTRAINT [PK_EMP_GRADE] PRIMARY KEY ([GRADE_EMP_SYSID])
);



-- Table: EMP_HRROLE
CREATE TABLE [EMP_HRROLE] (
    [HRROLE_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [HRROLE_TRANID] DECIMAL(38) NOT NULL  -- Transaction ID,
    [HRROLE_ID] CHAR(3) NOT NULL  -- HR Role ID,
    [HRROLE_EFF_DATE] DATETIME2(3) NULL  -- Effective Date,
    [HRROLE_CLS_DATE] DATETIME2(3) NULL  -- Closure Date,
    [HRROLE_REMARKS] VARCHAR(65) NULL  -- Remarks,
    [HRROLE_LIVFLAG] CHAR(1) NULL  -- Live Flag,
    [HRROLE_BATCHNO] DECIMAL(38) NULL  -- Batch No,
    [HRROLE_UPDATEDBY] DECIMAL(38) NULL  -- Last updated by,
    [HRROLE_UPDATEDON] DATETIME2(3) NULL  -- Last updated on,
    CONSTRAINT [PK_EMP_HRROLE] PRIMARY KEY ([HRROLE_EMP_SYSID])
);



-- Table: EMP_PAYUNIT
CREATE TABLE [EMP_PAYUNIT] (
    [PAYUNIT_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [PAYUNIT_TRANID] DECIMAL(38) NOT NULL  -- Transaction ID,
    [PAYUNIT_CODE] CHAR(3) NOT NULL  -- Payroll Unit,
    [PAYUNIT_EMPNO] DECIMAL(38) NOT NULL  -- Payroll Employee No,
    [PAYUNIT_EFF_DATE] DATETIME2(3) NULL  -- Effective Date,
    [PAYUNIT_CLS_DATE] DATETIME2(3) NULL  -- Closure Date,
    [PAYUNIT_REMARKS] VARCHAR(65) NULL  -- Remarks,
    [PAYUNIT_LIVFLAG] CHAR(1) NULL  -- Live Flag,
    [PAYUNIT_BATCHNO] DECIMAL(38) NULL  -- Batch No,
    [PAYUNIT_UPDATEDBY] DECIMAL(38) NULL  -- Last updated by,
    [PAYUNIT_UPDATEDON] DATETIME2(3) NULL  -- Last updated on,
    [PAYUNIT_ID] DECIMAL(22,0) NOT NULL,
    CONSTRAINT [PK_EMP_PAYUNIT] PRIMARY KEY ([PAYUNIT_EMP_SYSID])
);



-- Table: EMP_POSITION
CREATE TABLE [EMP_POSITION] (
    [POSITION_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [POSITION_TRANID] DECIMAL(38) NOT NULL  -- Transaction ID,
    [POSITION_ID] DECIMAL(38) NOT NULL  -- Position ID,
    [POSITION_EFF_DATE] DATETIME2(3) NOT NULL  -- Effective Date,
    [POSITION_CLS_DATE] DATETIME2(3) NULL  -- Closure Date,
    [POSITION_REMARKS] VARCHAR(65) NULL  -- Remarks,
    [POSITION_LIVFLAG] CHAR(1) NULL  -- Live Flag,
    [POSITION_BATCHNO] DECIMAL(38) NULL  -- Batch No,
    [POSITION_UPDATEDBY] DECIMAL(38) NULL  -- Last updated by,
    [POSITION_UPDATEDON] DATETIME2(3) NULL  -- Last updated on,
    CONSTRAINT [PK_EMP_POSITION] PRIMARY KEY ([POSITION_EMP_SYSID])
);



-- Table: EMP_RETIRALS
CREATE TABLE [EMP_RETIRALS] (
    [RETIRAL_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [RETIRAL_TRANID] DECIMAL(38) NOT NULL  -- Transaction ID,
    [RETIRAL_PFAPPLICABLE] CHAR(1) NULL  -- PF Applicable (Y/N),
    [RETIRAL_PFTRUST] CHAR(3) NULL  -- PF Trust,
    [RETIRAL_PFNO] DECIMAL(38) NULL  -- PF No,
    [RETIRAL_ADDLPF] CHAR(1) NULL  -- Additional Contribution Available?,
    [RETIRAL_ADDLPFPER] DECIMAL(38) NULL  -- Additional PF % of Basic,
    [RETIRAL_GRATUITYAPP] CHAR(1) NULL  -- Gratuity Appilcable (Y/N),
    [RETIRAL_SUPERANNUATIONAPP] CHAR(1) NULL  -- Superannuation Applicable (Y/N),
    [RETIRAL_SUPERANNUATIONOPT] CHAR(1) NULL  -- Superannuation Option (Y/N),
    [RETIRAL_SUPERANNUATIONNO] DECIMAL(38) NULL  -- Superannuation No,
    [RETIRAL_ESIAPP] CHAR(1) NULL  -- ESI Applicable (Y/N),
    [RETIRAL_ESINO] DECIMAL(38) NULL  -- ESI No,
    [RETIRAL_EFF_DATE] DATETIME2(3) NULL  -- Effective Date,
    [RETIRAL_CLS_DATE] DATETIME2(3) NULL  -- Closure Date,
    [RETIRAL_REMARKS] VARCHAR(65) NULL  -- Remarks,
    [RETIRAL_BATCHNO] DECIMAL(38) NULL  -- Batch No,
    [RETIRAL_UPDATED_BY] DECIMAL(38) NULL  -- Last updated by,
    [RETIRAL_UPDATED_ON] DATETIME2(3) NULL  -- Last updated on,
    CONSTRAINT [PK_EMP_RETIRALS] PRIMARY KEY ([RETIRAL_EMP_SYSID])
);



-- Table: EMP_SITE
CREATE TABLE [EMP_SITE] (
    [SITE_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [SITE_TRANID] DECIMAL(38) NOT NULL  -- Transaction ID,
    [SITE_ID] DECIMAL(38) NOT NULL  -- Site ID,
    [SITE_EFF_DATE] DATETIME2(3) NULL  -- Effective Date,
    [SITE_CLS_DATE] DATETIME2(3) NULL  -- Closure Date,
    [SITE_REMARKS] VARCHAR(65) NULL  -- Remarks,
    [SITE_LIVFLAG] CHAR(1) NULL  -- Live Flag,
    [SITE_BATCHNO] DECIMAL(38) NULL  -- Batch No,
    [SITE_UPDATEDBY] DECIMAL(38) NULL  -- Last updated by,
    [SITE_UPDATEDON] DATETIME2(3) NULL  -- Last updated on,
    CONSTRAINT [PK_EMP_SITE] PRIMARY KEY ([SITE_EMP_SYSID])
);



-- Table: EMP_SPARSHID
CREATE TABLE [EMP_SPARSHID] (
    [SPARSH_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [SPARSH_TRANID] DECIMAL(38) NOT NULL  -- Transaction ID,
    [SPARSH_USERID] VARCHAR(25) NULL  -- Sparsh User ID,
    [SPARSH_EMLFLAG] CHAR(1) NULL  -- Windows ID Available (Y/N),
    [SPARSH_EMAILID] VARCHAR(200) NULL  -- Office Email ID,
    [SPARSH_EFF_DATE] DATETIME2(3) NULL  -- Effective Date,
    [SPARSH_CLS_DATE] DATETIME2(3) NULL  -- Closure Date,
    [SPARSH_REMARKS] VARCHAR(65) NULL  -- Remarks,
    [SPARSH_LIVFLAG] CHAR(1) NULL  -- Live Flag,
    [SPARSH_BATCHNO] DECIMAL(38) NULL  -- Batch No,
    [SPARSH_MODBY] DECIMAL(38) NULL  -- Modified By,
    [SPARSH_MODON] DATETIME2(3) NULL  -- Modified On,
    CONSTRAINT [PK_EMP_SPARSHID] PRIMARY KEY ([SPARSH_EMP_SYSID])
);



-- Table: EMP_TIMEUNIT
CREATE TABLE [EMP_TIMEUNIT] (
    [TIMEUNIT_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [TIMEUNIT_TRANID] DECIMAL(38) NOT NULL  -- Transaction ID,
    [TIMEUNIT_UNIT] CHAR(3) NULL  -- Time Office Unit,
    [TIMEUNIT_EMPNO] DECIMAL(38) NULL  -- Time Office Employee No,
    [TIMEUNIT_EFF_DATE] DATETIME2(3) NULL  -- Effective Date,
    [TIMEUNIT_CLS_DATE] DATETIME2(3) NULL  -- Closure Date,
    [TIMEUNIT_REMARKS] VARCHAR(65) NULL  -- Remarks,
    [TIMEUNIT_LIVFLAG] CHAR(1) NULL  -- Live Flag,
    [TIMEUNIT_BATCHNO] DECIMAL(38) NULL  -- Batch No,
    [TIMEUNIT_UPDATEDBY] DECIMAL(38) NULL  -- Last updated by,
    [TIMEUNIT_UPDATEDON] DATETIME2(3) NULL  -- Last updated on,
    CONSTRAINT [PK_EMP_TIMEUNIT] PRIMARY KEY ([TIMEUNIT_EMP_SYSID])
);



-- Table: EMP_UNIT
CREATE TABLE [EMP_UNIT] (
    [UNIT_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [UNIT_TRANID] DECIMAL(38) NOT NULL  -- Transaction ID,
    [UNIT_CODE] CHAR(3) NOT NULL  -- Unit Code,
    [UNIT_EFF_DATE] DATETIME2(3) NULL  -- Effective Date,
    [UNIT_CLS_DATE] DATETIME2(3) NULL  -- Closure Date,
    [UNIT_REMARKS] VARCHAR(200) NULL  -- Remarks,
    [UNIT_LIVFLAG] CHAR(1) NULL  -- Live Flag,
    [UNIT_BATCHNO] DECIMAL(38) NULL  -- Batch No,
    [UNIT_UPDATEDBY] DECIMAL(38) NULL  -- Last updated by,
    [UNIT_UPDATEDON] DATETIME2(3) NULL  -- Last updated on,
    [UNIT_ID] DECIMAL(38) NOT NULL,
    CONSTRAINT [PK_EMP_UNIT] PRIMARY KEY ([UNIT_EMP_SYSID])
);



-- Table: EMPLOYEE_INDUCTION
CREATE TABLE [EMPLOYEE_INDUCTION] (
    [INDUCTION_EMPSYSID] DECIMAL(38) NOT NULL,
    [INDUCTION_CHKLISTCODE] DECIMAL(38) NOT NULL,
    [INDUCTION_CHKLISTSTATUS] CHAR(1) NULL,
    [INDUCTION_CHKLISTBY] VARCHAR(200) NULL,
    [INDUCTION_CHKLISTON] DATETIME2(3) NULL,
    [INDUCTION_CHKLISTREMARKS] VARCHAR(200) NULL,
    [INDUCTION_MODBY] DECIMAL(38) NULL,
    [INDUCTION_MODON] DATETIME2(3) NULL,
    CONSTRAINT [PK_EMPLOYEE_INDUCTION] PRIMARY KEY ([INDUCTION_EMPSYSID])
);



-- Table: EMPLOYEE_PROMOTION
CREATE TABLE [EMPLOYEE_PROMOTION] (
    [PROM_NO] DECIMAL(38) NOT NULL  -- Promotion No,
    [PROM_SOURCE] CHAR(3) NOT NULL  -- Source (ADD/MYR/DIR/PRB),
    [PROM_REQUESTNO] DECIMAL(38) NOT NULL  -- Request No,
    [PROM_RECDATE] DATETIME2(3) NOT NULL  -- Recommendation Date,
    [PROM_EMPSYSID] DECIMAL(38) NOT NULL  -- Employee Sysid,
    [PROM_OLDGRADE] DECIMAL(38) NOT NULL  -- Old Grade,
    [PROM_NEWGRADE] DECIMAL(38) NOT NULL  -- New Grade,
    [PROM_STATUS] CHAR(1) NOT NULL,
    [PROM_OLDPOSITION] DECIMAL(38) NOT NULL  -- Old Position ID,
    [PROM_NEWPOSITION] DECIMAL(38) NOT NULL  -- New Position ID,
    [PROM_REASON] DECIMAL(38) NOT NULL  -- Reason for Promotion,
    [PROM_REMARKS] VARCHAR(400) NULL  -- Remarks if any,
    [PROM_CNFDATE] DATETIME2(3) NULL  -- Promotion Confirmation Date,
    [PROM_REVISIONSTATUS] CHAR(1) NOT NULL  -- Revision Status (Y - Yes; N - No),
    [PROM_INCREMENTNO] DECIMAL(38) NOT NULL  -- Increment No,
    [PROM_CIRCULARID] DECIMAL(38) NULL  -- Promotion Circular ID,
    [PROM_SIGNATORY] DECIMAL(38) NULL  -- Promotion SIgnatory ID,
    [PROM_DESIGNATION] VARCHAR(65) NULL  -- Promotion Designation,
    [PROM_CTCEXC] DECIMAL(22,0) NULL,
    [PROM_CURCTCDATE] DATETIME2(3) NULL,
    [PROM_DDAMT] DECIMAL(22,0) NULL  -- DD Amount,
    [PROM_BATCHID] DECIMAL(22,0) NULL  -- Batch Id,
    [PROM_RESENDREMARKS] VARCHAR(300) NULL  -- Resend Remarks,
    [PROM_CANCELLEDBY] DECIMAL(38) NULL  -- Cancelled By,
    [PROM_CANCELLEDON] DATETIME2(3) NULL  -- Cancelled On,
    [PROM_TEMPLATEID] DECIMAL(22,0) NULL  -- Template ID,
    [PROM_LETTERDATE] DATETIME2(3) NULL  -- Letter date,
    [PROM_VERNO] DECIMAL(22,0) NULL  -- Ver No,
    [PROM_APPROVEDON] DATETIME2(3) NULL,
    [PROM_APPROVEDBY] DECIMAL(22,0) NULL,
    [PROM_CREATEDON] DATETIME2(3) NOT NULL  -- Created On,
    [PROM_CREATEDBY] DECIMAL(22,0) NOT NULL  -- Created by,
    [PROM_UPDATEDON] DATETIME2(3) NULL  -- Updated On,
    [PROM_UPDATEDBY] DECIMAL(22,0) NULL  -- Updated By,
    [PROM_PROBDATE] DATETIME2(3) NULL,
    [PROM_NEWDOJ] DATETIME2(3) NULL,
    [PROM_ANNXSIGNATORY] DECIMAL(38) NULL,
    [PROM_TYPE] CHAR(1) NULL  -- 'P' --   'Promotion', 
'G' --   'Change to different cadre or band',
    [PROM_SIGNATORY2] DECIMAL(22,0) NULL,
    [PROM_ANNXSIGNATORY2] DECIMAL(22,0) NULL,
    CONSTRAINT [PK_EMPLOYEE_PROMOTION] PRIMARY KEY ([PROM_NO])
);



-- Table: EMPLOYEE_PROMOTIONLOG
CREATE TABLE [EMPLOYEE_PROMOTIONLOG] (
    [PROM_NO] DECIMAL(38) NOT NULL,
    [PROM_SOURCE] CHAR(3) NOT NULL,
    [PROM_REQUESTNO] DECIMAL(38) NOT NULL,
    [PROM_RECDATE] DATETIME2(3) NOT NULL,
    [PROM_EMPSYSID] DECIMAL(38) NOT NULL,
    [PROM_OLDGRADE] DECIMAL(38) NOT NULL,
    [PROM_NEWGRADE] DECIMAL(38) NOT NULL,
    [PROM_STATUS] CHAR(1) NOT NULL,
    [PROM_OLDPOSITION] DECIMAL(38) NOT NULL,
    [PROM_NEWPOSITION] DECIMAL(38) NOT NULL,
    [PROM_REASON] DECIMAL(38) NOT NULL,
    [PROM_REMARKS] VARCHAR(400) NULL,
    [PROM_CNFDATE] DATETIME2(3) NULL,
    [PROM_REVISIONSTATUS] CHAR(1) NOT NULL,
    [PROM_INCREMENTNO] DECIMAL(38) NOT NULL,
    [PROM_CIRCULARID] DECIMAL(38) NULL,
    [PROM_SIGNATORY] DECIMAL(38) NULL,
    [PROM_DESIGNATION] VARCHAR(65) NULL,
    [PROM_CTCEXC] DECIMAL(22,0) NULL,
    [PROM_CURCTCDATE] DATETIME2(3) NULL,
    [PROM_DDAMT] DECIMAL(22,0) NULL,
    [PROM_BATCHID] DECIMAL(22,0) NULL,
    [PROM_RESENDREMARKS] VARCHAR(300) NULL,
    [PROM_CANCELLEDBY] DECIMAL(38) NULL,
    [PROM_CANCELLEDON] DATETIME2(3) NULL,
    [PROM_TEMPLATEID] DECIMAL(22,0) NULL,
    [PROM_LETTERDATE] DATETIME2(3) NULL,
    [PROM_VERNO] DECIMAL(22,0) NULL,
    [PROM_APPROVEDON] DATETIME2(3) NULL,
    [PROM_APPROVEDBY] DECIMAL(22,0) NULL,
    [PROM_CREATEDON] DATETIME2(3) NOT NULL,
    [PROM_CREATEDBY] DECIMAL(22,0) NOT NULL,
    [PROM_UPDATEDON] DATETIME2(3) NULL,
    [PROM_UPDATEDBY] DECIMAL(22,0) NULL,
    [PROM_PROBDATE] DATETIME2(3) NULL,
    [PROM_NEWDOJ] DATETIME2(3) NULL,
    [PROM_ANNXSIGNATORY] DECIMAL(38) NULL,
    [PROM_TYPE] CHAR(1) NULL,
    [PROM_SIGNATORY2] DECIMAL(22,0) NULL,
    [PROM_ANNXSIGNATORY2] DECIMAL(22,0) NULL,
    [LOG_CREATEDBY] DECIMAL(22,0) NULL,
    [LOG_CREATEDON] DATETIME2(3) NULL
);



-- Table: EMPLOYEE_PROMTOIONPRB
CREATE TABLE [EMPLOYEE_PROMTOIONPRB] (
    [PROM_NO] DECIMAL(38) NOT NULL,
    [PROM_SOURCE] CHAR(3) NOT NULL,
    [PROM_REQUESTNO] DECIMAL(38) NOT NULL,
    [PROM_RECDATE] DATETIME2(3) NOT NULL,
    [PROM_EMPSYSID] DECIMAL(38) NOT NULL,
    [PROM_OLDGRADE] DECIMAL(38) NOT NULL,
    [PROM_NEWGRADE] DECIMAL(38) NOT NULL,
    [PROM_STATUS] CHAR(1) NOT NULL,
    [PROM_OLDPOSITION] DECIMAL(38) NOT NULL,
    [PROM_NEWPOSITION] DECIMAL(38) NOT NULL,
    [PROM_REASON] DECIMAL(38) NOT NULL,
    [PROM_REMARKS] VARCHAR(400) NULL,
    [PROM_CNFDATE] DATETIME2(3) NULL,
    [PROM_REVISIONSTATUS] CHAR(1) NOT NULL,
    [PROM_INCREMENTNO] DECIMAL(38) NOT NULL,
    [PROM_CIRCULARID] DECIMAL(38) NULL,
    [PROM_SIGNATORY] DECIMAL(38) NULL,
    [PROM_DESIGNATION] VARCHAR(65) NULL,
    [PROM_CTCEXC] DECIMAL(22,0) NULL,
    [PROM_CURCTCDATE] DATETIME2(3) NULL,
    [PROM_DDAMT] DECIMAL(22,0) NULL,
    [PROM_BATCHID] DECIMAL(22,0) NULL,
    [PROM_RESENDREMARKS] VARCHAR(300) NULL,
    [PROM_CANCELLEDBY] DECIMAL(38) NULL,
    [PROM_CANCELLEDON] DATETIME2(3) NULL,
    [PROM_TEMPLATEID] DECIMAL(22,0) NULL,
    [PROM_LETTERDATE] DATETIME2(3) NULL,
    [PROM_VERNO] DECIMAL(22,0) NULL,
    [PROM_APPROVEDON] DATETIME2(3) NULL,
    [PROM_APPROVEDBY] DECIMAL(22,0) NULL,
    [PROM_CREATEDON] DATETIME2(3) NOT NULL,
    [PROM_CREATEDBY] DECIMAL(22,0) NOT NULL,
    [PROM_UPDATEDON] DATETIME2(3) NULL,
    [PROM_UPDATEDBY] DECIMAL(22,0) NULL,
    [PROM_PROBDATE] DATETIME2(3) NULL,
    [PROM_NEWDOJ] DATETIME2(3) NULL,
    [PROM_ANNXSIGNATORY] DECIMAL(38) NULL,
    [PROM_TYPE] CHAR(1) NULL,
    [PROM_SIGNATORY2] DECIMAL(22,0) NULL,
    [PROM_ANNXSIGNATORY2] DECIMAL(22,0) NULL
);



-- Table: AA_EMP_PROBATION
CREATE TABLE [AA_EMP_PROBATION] (
    [PROB_ID] DECIMAL(38) NOT NULL  -- Probation ID,
    [PROB_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee SYS ID,
    [PROB_DUEDATE] DATETIME2(3) NULL  -- Probationary Due Date,
    [PROB_DDREQUESTNO] DECIMAL(38) NULL  -- DD Request No,
    [PROB_FINSTATUS] CHAR(1) NULL  -- Final Status-A-confirmed,B-Extended,C-Terminated,
    [PROB_REVIEWDATE] DATETIME2(3) NULL  -- Review Date,
    [PROB_NXTREVIEWDATE] DATETIME2(3) NULL  -- Next Review Date,
    [PROB_CONFDATE] DATETIME2(3) NULL  -- Confirmation Date,
    CONSTRAINT [PK_AA_EMP_PROBATION] PRIMARY KEY ([PROB_ID])
);



-- Table: EMP_PROBATIONKK
CREATE TABLE [EMP_PROBATIONKK] (
    [PROBATION_ID] BIGINT NOT NULL,
    [PROBATION_EMPSYSID] BIGINT NOT NULL,
    [PROBATION_UNITID] BIGINT NOT NULL,
    [PROBATION_GRADE] BIGINT NOT NULL,
    [PROBATION_DUEDATE] DATETIME2(3) NOT NULL,
    [PROBATION_PROBATIONSTATUS] CHAR(1) NOT NULL,
    [PROBATION_EXTENDED] CHAR(1) NOT NULL,
    [PROBATION_DATE] DATETIME2(3) NOT NULL,
    [PROBATION_SALARYCHANGE] CHAR(1) NULL,
    [PROBATION_GRADECHANGE] CHAR(1) NULL,
    [PROBATION_INCREMENTNO] BIGINT NULL,
    [PROBATION_PROMOTIONNO] BIGINT NULL,
    [PROBATION_CREATEDON] DATETIME2(3) NOT NULL,
    [PROBATION_CREATEDBY] DECIMAL(38) NOT NULL,
    [PROBATION_LASTMODIFIEDBY] DECIMAL(38) NULL,
    [PROBATION_LASTMODIFIEDON] DATETIME2(3) NULL,
    [PROBATION_RATING] VARCHAR(20) NULL,
    [PROBATION_PFOPT] CHAR(1) NULL
);



-- Table: EMP_PROBWORKFLOW_TT
CREATE TABLE [EMP_PROBWORKFLOW_TT] (
    [SESSIONID] BIGINT NOT NULL,
    [PROBATION_PROCESSEDBY] BIGINT NOT NULL,
    [PROBATION_PROCESSEDON] DATETIME2(3) NULL,
    [PROBATION_ID] BIGINT NOT NULL,
    [PROBATION_EMPSYSID] BIGINT NOT NULL,
    [PROBATION_UNITID] BIGINT NOT NULL,
    [PROBATION_GRADE] BIGINT NOT NULL,
    [PROBATION_GRADECAT] CHAR(3) NOT NULL,
    [DOJ_DATE] DATETIME2(3) NOT NULL,
    [PROB_DATE] DATETIME2(3) NOT NULL,
    [STATUS] CHAR(1) NULL,
    [PROB_EXTENDED] CHAR(1) NULL,
    [PROB_SELFAPPRAISAL] CHAR(1) NULL
);



-- Table: EMP_TQM_CATEGORY
CREATE TABLE [EMP_TQM_CATEGORY] (
    [TQM_CATEGORY] VARCHAR(10) NOT NULL,
    [GRADE_CATEGORY] VARCHAR(3) NOT NULL
);



-- Table: EMPVISA_STAMPDET
CREATE TABLE [EMPVISA_STAMPDET] (
    [EV_EMPSYSID] BIGINT NOT NULL  -- Expat Employee SysID,
    [EV_STAMPDATE] DATETIME2(3) NOT NULL  -- Stamping Date,
    [EV_STAMPTYPE] CHAR(1) NOT NULL  -- Stamp Type (Specific/Re-Entry),
    [EV_UPDATEDBY] DECIMAL(38) NOT NULL  -- Updated by,
    [EV_UPDATEDON] DATETIME2(3) NOT NULL  -- Updated on,
    CONSTRAINT [PK_EMPVISA_STAMPDET] PRIMARY KEY ([EV_STAMPDATE])
);



-- Table: EXP_BREAKDETAILS
CREATE TABLE [EXP_BREAKDETAILS] (
    [EXB_ID] DECIMAL(38) NOT NULL,
    [EXB_EMPSYSID] DECIMAL(38) NOT NULL,
    [EXB_FROMDATE] DATETIME2(3) NOT NULL,
    [EXB_TODATE] DATETIME2(3) NOT NULL,
    [EXB_REMARKS] VARCHAR(200) NULL,
    CONSTRAINT [PK_EXP_BREAKDETAILS] PRIMARY KEY ([EXB_ID])
);



-- Table: NDA_INFO
CREATE TABLE [NDA_INFO] (
    [NDA_ID] BIGINT NOT NULL,
    [NDA_SYSID] BIGINT NOT NULL,
    [NDA_AGREEMENTDATE] DATETIME2(3) NOT NULL,
    [NDA_RELATIONNAME] VARCHAR(60) NOT NULL,
    [NDA_RELATIONSHIP] VARCHAR(60) NOT NULL,
    [NDA_EMPLOYEENAME] VARCHAR(60) NOT NULL,
    [NDA_ADDRESS1] VARCHAR(100) NOT NULL,
    [NDA_ADDRESS2] VARCHAR(100) NULL,
    [NDA_ADDRESS3] VARCHAR(100) NULL,
    [NDA_ADDRESS4] VARCHAR(100) NULL,
    [NDA_DOJ] DATETIME2(3) NOT NULL,
    [NDA_DESIGNATION] VARCHAR(100) NULL,
    [NDA_REFNUM] DECIMAL(38) NOT NULL,
    [NDA_ENTDATE] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_NDA_INFO] PRIMARY KEY ([NDA_ID])
);



-- Table: NDA_DOJ
CREATE TABLE [NDA_DOJ] (
    [NDA_SYSID] BIGINT NOT NULL,
    [NDA_DOJ] DATETIME2(3) NOT NULL,
    [EMP_GROUPDOJ] DATETIME2(3) NULL,
    [NDA_ENTDATE] DATETIME2(3) NOT NULL
);



-- Table: TRANSFER_MAIN
CREATE TABLE [TRANSFER_MAIN] (
    [TRANSFER_ID] DECIMAL(38) NOT NULL  -- Transfer ID,
    [TRANSFER_EMPSYSID] DECIMAL(38) NOT NULL  -- Transfer EmpSysid,
    [TRANSFER_OLDUNIT] CHAR(3) NULL  -- Transfer From Unit,
    [TRANSFER_NEWUNIT] CHAR(3) NULL  -- Transfer To Unit,
    [TRANSFER_REASON] DECIMAL(38) NULL  -- Transfer Reason,
    [TRANSFER_DATE] DATETIME2(3) NOT NULL  -- Transfer Date,
    [TRANSFER_REMARKS] VARCHAR(200) NULL  -- Reason for Transfer - Remarks if any,
    [TRANSFER_PAYFLAG] CHAR(1) NOT NULL  -- Transfer Payroll Flag (Y/N),
    [TRANSFER_PAYUNIT] CHAR(3) NULL  -- Transfer Payroll Unit,
    [TRANSFER_PAYDATE] DATETIME2(3) NULL  -- Transfer Payroll Transfer Date,
    [TRANSFER_TIMEFLAG] CHAR(1) NULL  -- Transfer Timeoffice Flag,
    [TRANSFER_TIMEUNIT] CHAR(3) NULL  -- Transfer Timeoffice Unit,
    [TRANSFER_TIMEDATE] DATETIME2(3) NULL  -- Transfer Time unit Transfer Date,
    [TRANSFER_TYPE] CHAR(2) NOT NULL  -- --01-Business to Business ; 02 - Within Business 
 
'I'- with Incremnt 
'P-' Promoiton 
'N'- No Increment,
    [TRANSFER_CIRCULARFLAG] CHAR(1) NULL  -- Y/N (Yes/No),
    [TRANSFER_CIRCULARID] DECIMAL(38) NULL  -- Transfer Circular - ID,
    [TRANSFER_STATUS] CHAR(2) NOT NULL  -- Transfer Status (01-Transferred; 02 - Transfer Settlement; 03 - Employment Entry; 04 - Transfer Complete),
    [TRANSFER_UPDATEDBY] DECIMAL(38) NULL  -- Last updated by,
    [TRANSFER_UPDATEDON] DATETIME2(3) NULL  -- Last updated on,
    [TRANSFER_SIGNATORYID] DECIMAL(38) NULL  -- Signatory ID,
    [TRANSFER_NOTES] VARCHAR(2000) NULL,
    [TRANSFER_PROM_NO] DECIMAL(38) NULL,
    [TRANSFER_POSITIONCHANGE] CHAR(1) NULL,
    [TRANSFER_CHECKLIST] CHAR(1) NULL,
    [TRANSFER_OLDDESIGNATION] VARCHAR(65) NULL,
    [TRANSFER_NEWDESIGNATION] VARCHAR(65) NULL,
    [TRANSFER_PAYUNITID] DECIMAL(22,0) NULL,
    [TRANSFER_CALENDARID] DECIMAL(22,0) NULL,
    [TRANSFER_INCREMENTSTS] CHAR(1) NULL,
    [TRANSFER_INCREMENTNO] DECIMAL(22,0) NULL,
    [TRANSFER_APPRSTATUS] CHAR(1) NULL,
    [TRANSFER_APPROVEDBY] DECIMAL(22,0) NULL,
    [TRANSFER_CANCELLEDBY] DECIMAL(22,0) NULL,
    [TRANSFER_CANCELLEDON] DATETIME2(3) NULL,
    [TRANSFER_OLDUNITID] DECIMAL(22,0) NOT NULL,
    [TRANSFER_NEWUNITID] DECIMAL(22,0) NOT NULL,
    [TRANSFER_TEMPLATEID] DECIMAL(22,0) NULL,
    [TRANSFER_LETTERDATE] DATETIME2(3) NULL,
    [TRANSFER_TIMEUNITID] DECIMAL(22,0) NULL,
    [TRANSFER_RESENDREMARKS] VARCHAR(400) NULL,
    [TRANSFER_VERNO] DECIMAL(22,0) NULL,
    [TRANSFER_ANNXSIGNATORY] DECIMAL(38) NULL,
    [TRANSFER_SIGNATORYID2] DECIMAL(22,0) NULL,
    [TRANSFER_ANNXSIGNATORY2] DECIMAL(22,0) NULL,
    [TRANSFER_EXPATSTATUS] CHAR(1) NOT NULL,
    [TRANSFER_CREATEDBY] DECIMAL(38) NULL,
    [TRANSFER_CREATEDON] DATETIME2(3) NULL,
    [TRANSFER_APPROVEDON] DATETIME2(3) NULL,
    [TRANSFER_CONFIRMEDBY] DECIMAL(38) NULL,
    [TRANSFER_CONFIRMEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_TRANSFER_MAIN] PRIMARY KEY ([TRANSFER_ID])
);



-- Table: TRANSFER_MAINLOG
CREATE TABLE [TRANSFER_MAINLOG] (
    [TRANSFER_ID] DECIMAL(38) NOT NULL,
    [TRANSFER_EMPSYSID] DECIMAL(38) NOT NULL,
    [TRANSFER_OLDUNIT] CHAR(3) NULL,
    [TRANSFER_NEWUNIT] CHAR(3) NULL,
    [TRANSFER_REASON] DECIMAL(38) NULL,
    [TRANSFER_DATE] DATETIME2(3) NOT NULL,
    [TRANSFER_REMARKS] VARCHAR(200) NULL,
    [TRANSFER_PAYFLAG] CHAR(1) NOT NULL,
    [TRANSFER_PAYUNIT] CHAR(3) NULL,
    [TRANSFER_PAYDATE] DATETIME2(3) NULL,
    [TRANSFER_TIMEFLAG] CHAR(1) NULL,
    [TRANSFER_TIMEUNIT] CHAR(3) NULL,
    [TRANSFER_TIMEDATE] DATETIME2(3) NULL,
    [TRANSFER_TYPE] CHAR(2) NOT NULL,
    [TRANSFER_CIRCULARFLAG] CHAR(1) NULL,
    [TRANSFER_CIRCULARID] DECIMAL(38) NULL,
    [TRANSFER_STATUS] CHAR(2) NOT NULL,
    [TRANSFER_UPDATEDBY] DECIMAL(38) NULL,
    [TRANSFER_UPDATEDON] DATETIME2(3) NULL,
    [TRANSFER_SIGNATORYID] DECIMAL(38) NULL,
    [TRANSFER_NOTES] VARCHAR(2000) NULL,
    [TRANSFER_PROM_NO] DECIMAL(38) NULL,
    [TRANSFER_POSITIONCHANGE] CHAR(1) NULL,
    [TRANSFER_CHECKLIST] CHAR(1) NULL,
    [TRANSFER_OLDDESIGNATION] VARCHAR(65) NULL,
    [TRANSFER_NEWDESIGNATION] VARCHAR(65) NULL,
    [TRANSFER_PAYUNITID] DECIMAL(22,0) NULL,
    [TRANSFER_CALENDARID] DECIMAL(22,0) NULL,
    [TRANSFER_INCREMENTSTS] CHAR(1) NULL,
    [TRANSFER_INCREMENTNO] DECIMAL(22,0) NULL,
    [TRANSFER_APPRSTATUS] CHAR(1) NULL,
    [TRANSFER_APPROVEDBY] DECIMAL(22,0) NULL,
    [TRANSFER_CANCELLEDBY] DECIMAL(22,0) NULL,
    [TRANSFER_CANCELLEDON] DATETIME2(3) NULL,
    [TRANSFER_OLDUNITID] DECIMAL(22,0) NULL,
    [TRANSFER_NEWUNITID] DECIMAL(22,0) NULL,
    [TRANSFER_TEMPLATEID] DECIMAL(22,0) NULL,
    [TRANSFER_LETTERDATE] DATETIME2(3) NULL,
    [TRANSFER_TIMEUNITID] DECIMAL(22,0) NULL,
    [TRANSFER_RESENDREMARKS] VARCHAR(400) NULL,
    [TRANSFER_VERNO] DECIMAL(22,0) NULL,
    [TRANSFER_ANNXSIGNATORY] DECIMAL(38) NULL,
    [TRANSFER_SIGNATORYID2] DECIMAL(22,0) NULL,
    [TRANSFER_ANNXSIGNATORY2] DECIMAL(22,0) NULL,
    [TRANSFER_EXPATSTATUS] CHAR(1) NOT NULL,
    [TRANSFER_CREATEDBY] DECIMAL(38) NULL,
    [TRANSFER_CREATEDON] DATETIME2(3) NULL,
    [TRANSFER_APPROVEDON] DATETIME2(3) NULL,
    [TRANSFER_CONFIRMEDBY] DECIMAL(38) NULL,
    [TRANSFER_CONFIRMEDON] DATETIME2(3) NULL,
    [LOG_CREATEDBY] DECIMAL(22,0) NULL,
    [LOG_CREATEDON] DATETIME2(3) NULL
);



-- Table: TRANSFER_OUT
CREATE TABLE [TRANSFER_OUT] (
    [TRANSFER_ID] DECIMAL(38) NOT NULL  -- Transfer ID,
    [TRANSFER_EMPSYSID] DECIMAL(38) NOT NULL  -- Transfer EmpSysid,
    [TRANSFER_OLDUNITID] DECIMAL(22,0) NOT NULL,
    [TRANSFER_NEWUNITID] DECIMAL(22,0) NOT NULL,
    [TRANSFER_REASON] DECIMAL(38) NULL  -- Transfer Reason,
    [TRANSFER_DATE] DATETIME2(3) NOT NULL  -- Transfer Date,
    [TRANSFER_REMARKS] VARCHAR(200) NULL  -- Reason for Transfer - Remarks if any,
    [TRANSFER_UPDATEDBY] DECIMAL(38) NOT NULL  -- Last updated by,
    [TRANSFER_UPDATEDON] DATETIME2(3) NOT NULL  -- Last updated on,
    [TRANSFER_CHECKLIST] CHAR(1) NULL,
    [TRANSFER_APPRSTATUS] CHAR(1) NULL,
    [TRANSFER_APPROVEDBY] DECIMAL(22,0) NULL,
    [TRANSFER_APPROVEDON] DATETIME2(3) NULL,
    [TRANSFER_CANCELLEDBY] DECIMAL(22,0) NULL,
    [TRANSFER_CANCELLEDON] DATETIME2(3) NULL,
    [TRANSFER_RESENDREMARKS] VARCHAR(400) NULL,
    [TRANSFER_CREATEDBY] DECIMAL(38) NULL,
    [TRANSFER_CREATEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_TRANSFER_OUT] PRIMARY KEY ([TRANSFER_ID])
);



-- Table: TRANSFER_CHANGEDET
CREATE TABLE [TRANSFER_CHANGEDET] (
    [ORG_CHANGEID] DECIMAL(38) NOT NULL  -- Orgn. Structure Change ID,
    [ORG_STRUCTURE_TYPE] CHAR(3) NOT NULL  -- UNT - Unit/ COS - Cost Centre / DIV - Division / LOC - Location / DEP - Department / PRC - Process / SIT - Site / ROL - HR Role/ POS - Position/ PAY - Payroll Unit / TIM - Time Office Unit,
    [ORG_OLDCODE] VARCHAR(10) NULL  -- Change - Old Code,
    [ORG_NEWCODE] VARCHAR(10) NULL  -- Change - New Code,
    [ORG_SOURCE] CHAR(3) NULL  -- Transaction Source (TRN - Transfer ; ORG - Organisation Change),
    [ORG_TRANSACTIONNO] DECIMAL(38) NULL  -- Originating Transaction No (Transfer ID - Transfer; Change ID - Organizational Changes),
    [ORG_MODBY] DECIMAL(38) NULL  -- Modified by,
    [ORG_MODON] DATETIME2(3) NULL  -- Modified on,
    CONSTRAINT [PK_TRANSFER_CHANGEDET] PRIMARY KEY ([ORG_CHANGEID])
);



-- Table: TRANSFER_CHANGEDET_BAK
CREATE TABLE [TRANSFER_CHANGEDET_BAK] (
    [ORG_CHANGEID] DECIMAL(38) NOT NULL,
    [ORG_STRUCTURE_TYPE] CHAR(3) NOT NULL,
    [ORG_OLDCODE] VARCHAR(10) NULL,
    [ORG_NEWCODE] VARCHAR(10) NULL,
    [ORG_SOURCE] CHAR(3) NULL,
    [ORG_TRANSACTIONNO] DECIMAL(38) NULL,
    [ORG_MODBY] DECIMAL(38) NULL,
    [ORG_MODON] DATETIME2(3) NULL
);

