-- ==========================================
-- MODULE: SCHOLARSHIP
-- Component: Sample / Seed Data
-- Database: ADMINDB
-- ==========================================

-- Scholarship Amounts (grade configurations)
INSERT INTO SCHOLARSHIP_AMOUNT
    (SCH_AMTID, SCH_ORGID, SCH_GRADECAT, SCH_ELGIBLEEXAM, SCH_APPLICABLEALLGRADE,
     SCH_GRADEID, SCH_FROMYEAR, SCH_CLOSEYEAR, SCH_ELGIBLEAMOUNT, SCH_ELGIBLEYEAR,
     SCH_CUTOFFMARKS, SCH_CREATEDON, SCH_CREATEDBY, SCH_UPDATEDON, SCH_UPDATEDBY)
VALUES
    (1, 1, 'GRP', '10', '0', 0, 2020, NULL, 25000, 4, 70, GETDATE(), 1, NULL, NULL),
    (2, 1, 'GRP', '12', '0', 0, 2020, NULL, 30000, 4, 75, GETDATE(), 1, NULL, NULL),
    (3, 1, 'OFF', '10', '0', 0, 2020, NULL, 20000, 3, 65, GETDATE(), 1, NULL, NULL),
    (4, 1, 'OFF', '12', '0', 0, 2020, NULL, 25000, 3, 70, GETDATE(), 1, NULL, NULL);
GO

-- Sample Scholarship Main record
INSERT INTO SCHOLARSHIP_MAIN
    (SCH_ID, SCH_EMPSYSID, SCH_GRADEID, SCH_DEPENDID, SCH_CHILDNAME,
     SCH_LASTSCHOOL, SCH_LASTYEAROFSCHOOL, SCH_LASTEXAM, SCH_CGPAFLAG,
     SCH_MARKSPER, SCH_MARKSGPA, SCH_MARKSFILE, SCH_COURSENAME,
     SCH_COURSEJOINYEAR, SCH_COURSEJOINMONTH, SCH_COURSEDURATION,
     SCH_ADMRECPTFILE, SCH_PAYMODE, SCH_CHILDACCNO, SCH_CHILLDBANKIFSC,
     SCH_CHILLDBANKMICR, SCH_ENTRYSTATUS, SCH_SOURCE, SCH_DISBAMOUNT,
     SCH_DISBFREQ, SCH_LIVESTATUS, SCH_CREATEDON, SCH_CREATEDBY,
     SCH_UPDATEDON, SCH_UPDATEDBY, SCH_APPROVALBY, SCH_APPROVALON,
     SCH_APPREMARKS, SCH_STOPREASON, SCH_STOPDATE, SCH_STOPENTEREDON,
     SCH_STOPENTEREDBY, SCH_OFFLINE, SCH_OFFLINEYEAR)
VALUES
    (1, 1001, 101, 201, 'Rahul Kumar',
     'Delhi Public School', 2022, '12', 'N',
     85, 0, 'marks_cert_2022.pdf', 'B.Tech Computer Science',
     2022, 6, 4,
     'admission_receipt.pdf', 'NET', '12345678901234567890', 'HDFC0001234',
     '110001234', 'E', 'O', 30000,
     'Y', 'A', GETDATE(), 1001,
     GETDATE(), 1001, 0, GETDATE(),
     '', '', GETDATE(), GETDATE(),
     0, 'N', NULL);
GO

-- Sample Scholarship Detail record
INSERT INTO SCHOLARSHIP_DETAIL
    (SCHDET_ID, SCHDET_MAINID, SCHDET_YEAR, SCHDET_MARKSFILE,
     SCHDET_MARKSTATUS, SCHDET_PAYSTATUS, SCHDET_CREATEDON, SCHDET_CREATEDBY,
     SCHDET_UPDATEDON, SCHDET_UPDATEDBY, SCHDET_APPROVEDON, SCHDET_APPROVEDBY,
     SCHDET_PAYAPPROVEDON, SCHDET_PAYAPPROVEDBY, SCHDET_PAYDATE,
     SCHDET_PAYAMOUNT, SCHDET_PAYUPDATEDON, SCHDET_PAYUPDATEDBY)
VALUES
    (1, 1, 2022, 'marks_year1.pdf',
     'P', 'S', GETDATE(), 1001,
     GETDATE(), 1001, NULL, NULL,
     NULL, NULL, NULL,
     NULL, NULL, NULL);
GO
