-- ==========================================
-- MODULE: SCHOLARSHIP
-- Component: Stored Procedures (EF Migration Script)
-- Description: Run this after EF migrations to create SP and function
-- Database: ADMINDB
-- ==========================================

-- Function: fn_GetScholarshipEligibleAmount
CREATE OR ALTER FUNCTION dbo.fn_GetScholarshipEligibleAmount
(
    @p_GradeCat CHAR(3),
    @p_EligibleExam VARCHAR(2),
    @p_Year INT
)
RETURNS BIGINT
AS
BEGIN
    DECLARE @Amount BIGINT;
    SELECT TOP 1 @Amount = SCH_ELGIBLEAMOUNT
    FROM SCHOLARSHIP_AMOUNT
    WHERE SCH_GRADECAT = @p_GradeCat
      AND SCH_ELGIBLEEXAM = @p_EligibleExam
      AND @p_Year BETWEEN SCH_FROMYEAR AND ISNULL(SCH_CLOSEYEAR, @p_Year)
    ORDER BY SCH_FROMYEAR DESC;
    RETURN ISNULL(@Amount, 0);
END;
GO

-- Procedure: usp_ScholarshipApplication
CREATE OR ALTER PROCEDURE dbo.usp_ScholarshipApplication
(
    @p_SCH_EMPSYSID INT,
    @p_SCH_GRADEID INT,
    @p_SCH_DEPENDID INT,
    @p_SCH_CHILDNAME VARCHAR(100),
    @p_SCH_LASTSCHOOL VARCHAR(100),
    @p_SCH_LASTYEAROFSCHOOL DECIMAL(38,0),
    @p_SCH_LASTEXAM CHAR(2),
    @p_SCH_CGPAFLAG CHAR(1),
    @p_SCH_MARKSPER DECIMAL(19,0),
    @p_SCH_MARKSGPA DECIMAL(19,0),
    @p_SCH_MARKSFILE VARCHAR(100),
    @p_SCH_COURSENAME VARCHAR(100),
    @p_SCH_COURSEJOINYEAR INT,
    @p_SCH_COURSEJOINMONTH DECIMAL(20,0),
    @p_SCH_COURSEDURATION BIGINT,
    @p_SCH_ADMRECPTFILE VARCHAR(100) = NULL,
    @p_SCH_PAYMODE CHAR(3) = NULL,
    @p_SCH_CHILDACCNO VARCHAR(20) = NULL,
    @p_SCH_CHILLDBANKIFSC VARCHAR(12) = NULL,
    @p_SCH_CHILLDBANKMICR VARCHAR(12) = NULL,
    @p_SCH_ENTRYSTATUS CHAR(1) = 'E',
    @p_SCH_SOURCE CHAR(1),
    @p_SCH_DISBAMOUNT DECIMAL(19,0),
    @p_SCH_DISBFREQ CHAR(1),
    @p_SCH_LIVESTATUS CHAR(1) = 'A',
    @p_CreatedBy INT,
    @p_SCH_OFFLINE CHAR(1) = 'N',
    @p_SCH_OFFLINEYEAR INT = NULL,
    @p_NewSchID INT OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;
        SELECT @p_NewSchID = ISNULL(MAX(SCH_ID), 0) + 1 FROM SCHOLARSHIP_MAIN;
        INSERT INTO SCHOLARSHIP_MAIN
        (SCH_ID, SCH_EMPSYSID, SCH_GRADEID, SCH_DEPENDID, SCH_CHILDNAME,
         SCH_LASTSCHOOL, SCH_LASTYEAROFSCHOOL, SCH_LASTEXAM, SCH_CGPAFLAG,
         SCH_MARKSPER, SCH_MARKSGPA, SCH_MARKSFILE, SCH_COURSENAME,
         SCH_COURSEJOINYEAR, SCH_COURSEJOINMONTH, SCH_COURSEDURATION,
         SCH_ADMRECPTFILE, SCH_PAYMODE, SCH_CHILDACCNO, SCH_CHILLDBANKIFSC,
         SCH_CHILLDBANKMICR, SCH_ENTRYSTATUS, SCH_SOURCE, SCH_DISBAMOUNT,
         SCH_DISBFREQ, SCH_LIVESTATUS, SCH_CREATEDON, SCH_CREATEDBY,
         SCH_UPDATEDON, SCH_UPDATEDBY, SCH_APPROVALBY, SCH_APPROVALON,
         SCH_APPREMARKS, SCH_STOPREASON, SCH_STOPDATE, SCH_STOPENTEREDON,
         SCH_STOPENTEREDBY, SCH_OFFLINE, SCH_OFFLINEYEAR)
        VALUES
        (@p_NewSchID, @p_SCH_EMPSYSID, @p_SCH_GRADEID, @p_SCH_DEPENDID, @p_SCH_CHILDNAME,
         @p_SCH_LASTSCHOOL, @p_SCH_LASTYEAROFSCHOOL, @p_SCH_LASTEXAM, @p_SCH_CGPAFLAG,
         @p_SCH_MARKSPER, @p_SCH_MARKSGPA, @p_SCH_MARKSFILE, @p_SCH_COURSENAME,
         @p_SCH_COURSEJOINYEAR, @p_SCH_COURSEJOINMONTH, @p_SCH_COURSEDURATION,
         @p_SCH_ADMRECPTFILE, @p_SCH_PAYMODE, @p_SCH_CHILDACCNO, @p_SCH_CHILLDBANKIFSC,
         @p_SCH_CHILLDBANKMICR, @p_SCH_ENTRYSTATUS, @p_SCH_SOURCE, @p_SCH_DISBAMOUNT,
         @p_SCH_DISBFREQ, @p_SCH_LIVESTATUS, GETDATE(), @p_CreatedBy,
         GETDATE(), @p_CreatedBy, 0, GETDATE(), '', '', GETDATE(), GETDATE(), 0,
         @p_SCH_OFFLINE, @p_SCH_OFFLINEYEAR);

        DECLARE @NewDetID BIGINT;
        SELECT @NewDetID = ISNULL(MAX(SCHDET_ID), 0) + 1 FROM SCHOLARSHIP_DETAIL;
        INSERT INTO SCHOLARSHIP_DETAIL
        (SCHDET_ID, SCHDET_MAINID, SCHDET_YEAR, SCHDET_MARKSFILE,
         SCHDET_MARKSTATUS, SCHDET_PAYSTATUS, SCHDET_CREATEDON, SCHDET_CREATEDBY,
         SCHDET_UPDATEDON, SCHDET_UPDATEDBY, SCHDET_APPROVEDON, SCHDET_APPROVEDBY,
         SCHDET_PAYAPPROVEDON, SCHDET_PAYAPPROVEDBY, SCHDET_PAYDATE,
         SCHDET_PAYAMOUNT, SCHDET_PAYUPDATEDON, SCHDET_PAYUPDATEDBY)
        VALUES
        (@NewDetID, @p_NewSchID, @p_SCH_COURSEJOINYEAR, @p_SCH_MARKSFILE,
         'P', 'S', GETDATE(), @p_CreatedBy, GETDATE(), @p_CreatedBy,
         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

-- Procedure: usp_ScholarshipApprove
CREATE OR ALTER PROCEDURE dbo.usp_ScholarshipApprove
(
    @p_SCH_ID INT,
    @p_ApprovedBy INT,
    @p_AppRemarks VARCHAR(200) = NULL
)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;
        UPDATE SCHOLARSHIP_MAIN
        SET SCH_ENTRYSTATUS = 'A',
            SCH_APPROVALBY = @p_ApprovedBy,
            SCH_APPROVALON = GETDATE(),
            SCH_APPREMARKS = ISNULL(@p_AppRemarks, ''),
            SCH_UPDATEDON = GETDATE(),
            SCH_UPDATEDBY = @p_ApprovedBy
        WHERE SCH_ID = @p_SCH_ID;

        UPDATE SCHOLARSHIP_DETAIL
        SET SCHDET_MARKSTATUS = 'A',
            SCHDET_APPROVEDON = GETDATE(),
            SCHDET_APPROVEDBY = @p_ApprovedBy,
            SCHDET_UPDATEDON = GETDATE(),
            SCHDET_UPDATEDBY = @p_ApprovedBy
        WHERE SCHDET_MAINID = @p_SCH_ID
          AND SCHDET_MARKSTATUS = 'P';

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

-- Trigger: trg_ScholarshipDetail_UpdateAudit
CREATE OR ALTER TRIGGER dbo.trg_ScholarshipDetail_UpdateAudit
ON dbo.SCHOLARSHIP_DETAIL
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE SD
    SET SCHDET_UPDATEDON = GETDATE()
    FROM dbo.SCHOLARSHIP_DETAIL SD
    INNER JOIN inserted I ON SD.SCHDET_ID = I.SCHDET_ID;
END;
GO
