// <auto-generated />
using System;
using AuditLogService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuditLogService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuditLogDbContext))]
    partial class AuditLogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuditLogService.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("action");

                    b.Property<DateTime>("ChangeDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("change_date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("changed_by");

                    b.Property<int>("RecordId")
                        .HasColumnType("int")
                        .HasColumnName("record_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("table_name");

                    b.HasKey("Id");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("AuditLogService.Domain.Entities.AuditLogEntry", b =>
                {
                    b.OwnsOne("AuditLogService.Domain.ValueObjects.ChangeData", "ChangeData", b1 =>
                        {
                            b1.Property<long>("AuditLogEntryId")
                                .HasColumnType("bigint");

                            b1.Property<string>("NewValues")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("new_values");

                            b1.Property<string>("OldValues")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("old_values");

                            b1.HasKey("AuditLogEntryId");

                            b1.ToTable("AuditLog");

                            b1.WithOwner()
                                .HasForeignKey("AuditLogEntryId");
                        });

                    b.Navigation("ChangeData")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
