// <auto-generated />
using System;
using MemberService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MemberService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MemberDbContext))]
    [Migration("20260317132436_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MemberService.Domain.Aggregates.Member", b =>
                {
                    b.Property<long>("MemberNo")
                        .HasColumnType("bigint")
                        .HasColumnName("MEMBER_NO");

                    b.Property<DateTime?>("ClosureDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MEMBER_CLOSURE_DATE");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MEMBER_DOB");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MEMBER_DOJ");

                    b.Property<long>("EmployeeNo")
                        .HasColumnType("bigint")
                        .HasColumnName("MEMBER_EMP_NUM");

                    b.Property<long>("EmployeeSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("MEMBER_EMP_SYSID");

                    b.Property<string>("EmployeeType")
                        .IsRequired()
                        .HasColumnType("CHAR(2)")
                        .HasColumnName("MEMBER_EMPLOYEE_TYPE");

                    b.Property<DateTime>("EnrollDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MEMBER_ENROLL_DATE");

                    b.Property<long>("EnrollSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("MEMBER_ENROLL_SYSID");

                    b.Property<string>("EnrollUserId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("MEMBER_ENROLL_USER_ID");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MEMBER_ENR_DATE");

                    b.Property<string>("FatherName")
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)")
                        .HasColumnName("MEMBER_FATHERNAME");

                    b.Property<string>("FpsTrustCode")
                        .IsRequired()
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("MEMBER_FPSTRUST_CODE");

                    b.Property<DateTime?>("LeaveDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MEMBER_LEAVE_DATE");

                    b.Property<string>("LeaveReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MEMBER_LEAVE_REASON");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)")
                        .HasColumnName("MEMBER_NAME");

                    b.Property<int>("OpfNo")
                        .HasColumnType("int")
                        .HasColumnName("MEMBER_OPF_NO");

                    b.Property<int>("PensionNo")
                        .HasColumnType("int")
                        .HasColumnName("MEMBER_PENSION_NO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("MEMBER_STATUS");

                    b.Property<string>("TrustCode")
                        .IsRequired()
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("MEMBER_TRUST_CODE");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("MEMBER_UNIT_CODE");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("MEMBER_UPDATED_BY");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MEMBER_UPDATED_ON");

                    b.HasKey("MemberNo");

                    b.HasIndex("EmployeeSysId")
                        .HasDatabaseName("IDX_MEMBER_MASTER_EMP_SYSID");

                    b.HasIndex("TrustCode", "Status")
                        .HasDatabaseName("IDX_MEMBER_MASTER_TRUST_STATUS");

                    b.ToTable("MEMBER_MASTER", (string)null);
                });

            modelBuilder.Entity("MemberService.Domain.Entities.MemberAuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AUDIT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditId"));

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AUDIT_ACTION");

                    b.Property<DateTime>("AuditTimestamp")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("AUDIT_TIMESTAMP");

                    b.Property<long>("AuditUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("AUDIT_USER_ID");

                    b.Property<long>("MemberNo")
                        .HasColumnType("bigint")
                        .HasColumnName("MEMBER_NO");

                    b.Property<string>("NewValues")
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("AUDIT_NEW_VALUES");

                    b.Property<string>("OldValues")
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("AUDIT_OLD_VALUES");

                    b.HasKey("AuditId");

                    b.HasIndex("MemberNo", "AuditTimestamp")
                        .HasDatabaseName("IDX_MEMBER_AUDIT_LOG_MEMBER");

                    b.ToTable("MEMBER_AUDIT_LOG", (string)null);
                });

            modelBuilder.Entity("MemberService.Domain.Entities.MemberContact", b =>
                {
                    b.Property<long>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CONTACT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ContactId"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ADDRESS_LINE_1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ADDRESS_LINE_2");

                    b.Property<string>("AddressLine3")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ADDRESS_LINE_3");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CITY");

                    b.Property<DateTime?>("ClosureDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("CLS_DATE");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("CONTACT_TYPE");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("COUNTRY");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("EFF_DATE");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<long>("MemberNo")
                        .HasColumnType("bigint")
                        .HasColumnName("MEMBER_NO");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PHONE_NO");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PIN_CODE");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STATE");

                    b.HasKey("ContactId");

                    b.HasIndex("MemberNo", "ContactType")
                        .HasDatabaseName("IDX_MEMBER_CONTACT_MEMBER");

                    b.ToTable("MEMBER_CONTACT", (string)null);
                });

            modelBuilder.Entity("MemberService.Domain.Entities.MemberNominee", b =>
                {
                    b.Property<long>("MemberNo")
                        .HasColumnType("BIGINT")
                        .HasColumnName("NOMINEE_MEMBER_NO");

                    b.Property<int>("SerialNo")
                        .HasColumnType("int")
                        .HasColumnName("NOMINEE_SERIAL_NO");

                    b.Property<string>("FundType")
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("NOMINEE_FUND_TYPE");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOMINEE_ADDRESS_LINE_1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOMINEE_ADDRESS_LINE_2");

                    b.Property<string>("AddressLine3")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOMINEE_ADDRESS_LINE_3");

                    b.Property<DateTime?>("ClosureDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("NOMINEE_CLS_DATE");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("NOMINEE_DOB");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("NOMINEE_EFF_DATE");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOMINEE_EMAIL");

                    b.Property<string>("IsMinor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOMINEE_MINOR_FLAG");

                    b.Property<string>("NomineeName")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)")
                        .HasColumnName("NOMINEE_NAME");

                    b.Property<long>("Percentage")
                        .HasColumnType("bigint")
                        .HasColumnName("NOMINEE_PERCENTAGE");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NOMINEE_PHONE_NO");

                    b.Property<string>("RelationshipCode")
                        .IsRequired()
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("NOMINEE_RELATIONSHIP_CODE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("NOMINEE_STATUS");

                    b.Property<string>("TrustCode")
                        .IsRequired()
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("NOMINEE_TRUST_CODE");

                    b.HasKey("MemberNo", "SerialNo", "FundType");

                    b.HasIndex("MemberNo", "EffectiveDate", "Status")
                        .HasDatabaseName("IDX_MEMBER_NOMINEE_MEMBER");

                    b.ToTable("MEMBER_NOMINEE", (string)null);
                });

            modelBuilder.Entity("MemberService.Domain.Entities.MemberPayroll", b =>
                {
                    b.Property<long>("MemberNo")
                        .HasColumnType("bigint")
                        .HasColumnName("PAYROLL_MEMBER_NO");

                    b.Property<string>("UnitCode")
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("PAYROLL_UNT_COD");

                    b.Property<DateTime?>("ClosureDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("PAYROLL_CLS_DATE");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("PAYROLL_EFF_DATE");

                    b.Property<long>("EmployeeNo")
                        .HasColumnType("bigint")
                        .HasColumnName("PAYROLL_EMP_NUM");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("PAYROLL_STATUS");

                    b.HasKey("MemberNo", "UnitCode");

                    b.HasIndex("MemberNo", "Status")
                        .HasDatabaseName("IDX_MEMBER_PAYROLL_STATUS");

                    b.ToTable("MEMBER_PAYROLL", (string)null);
                });

            modelBuilder.Entity("MemberService.Domain.Entities.NomineeGuardian", b =>
                {
                    b.Property<string>("TrustCode")
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("GN_TRUST_CODE");

                    b.Property<long>("NomineeMemberNo")
                        .HasColumnType("bigint")
                        .HasColumnName("GN_NOMINEE_MEMBER_NO");

                    b.Property<long>("NomineeSerialNo")
                        .HasColumnType("bigint")
                        .HasColumnName("GN_NOMINEE_SERIAL_NO");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("GN_ADDRESS_LINE1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("GN_ADDRESS_LINE2");

                    b.Property<string>("AddressLine3")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("GN_ADDRESS_LINE3");

                    b.Property<string>("AddressLine4")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("GN_ADDRESS_LINE4");

                    b.Property<DateTime?>("ClosureDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("GN_CLS_DATE");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("GN_EFF_DATE");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("GN_EMAIL");

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)")
                        .HasColumnName("GAURDIAN_NAME");

                    b.Property<string>("GuardianRelationship")
                        .IsRequired()
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("GAURDIAN_RELATIONSHIP");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("GN_PHONE_NO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("GN_STATUS");

                    b.HasKey("TrustCode", "NomineeMemberNo", "NomineeSerialNo");

                    b.ToTable("NOMINEE_GAURDIAN", (string)null);
                });

            modelBuilder.Entity("MemberService.Domain.Entities.MemberContact", b =>
                {
                    b.HasOne("MemberService.Domain.Aggregates.Member", null)
                        .WithMany("Contacts")
                        .HasForeignKey("MemberNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MemberService.Domain.Entities.MemberNominee", b =>
                {
                    b.HasOne("MemberService.Domain.Aggregates.Member", null)
                        .WithMany("Nominees")
                        .HasForeignKey("MemberNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MemberService.Domain.Entities.MemberPayroll", b =>
                {
                    b.HasOne("MemberService.Domain.Aggregates.Member", null)
                        .WithMany("PayrollRecords")
                        .HasForeignKey("MemberNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MemberService.Domain.Aggregates.Member", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Nominees");

                    b.Navigation("PayrollRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
