-- Module: Appraisal
USE DDDB;
GO

-- Table: DD_APPRAISALBAND
CREATE TABLE [DD_APPRAISALBAND] (
    [DD_BND_ID] DECIMAL(38) NOT NULL  -- Band Id,
    [DD_BND_DSC] VARCHAR(20) NULL  -- Band Description,
    [DD_BND_DSG] VARCHAR(200) NULL  -- Band Designation,
    [DD_SIG_NAM] VARCHAR(200) NULL  -- Signatory Name,
    [DD_SIG_DSG] VARCHAR(200) NULL  -- Signatory Designation,
    [DD_BND_COD] CHAR(3) NULL,
    [DD_FORMFLAG] CHAR(1) NULL,
    [DD_GRADEID] DECIMAL(38) NULL,
    CONSTRAINT [PK_DD_APPRAISALBAND] PRIMARY KEY ([DD_BND_ID])
);



-- Table: DD_APPRAISALBREAK
CREATE TABLE [DD_APPRAISALBREAK] (
    [DD_PIN_NUM] DECIMAL(38) NOT NULL  -- Pin No,
    [DD_USR_ID] VARCHAR(25) NOT NULL  -- User Id,
    [DD_ED_DSC] VARCHAR(65) NULL,
    [DD_ED_COD] CHAR(9) NOT NULL,
    [DD_MNT_AMT] DECIMAL(38) NULL  -- Monthly Amount,
    [DD_ANN_AMT] DECIMAL(38) NULL  -- Annual Amount,
    [DD_APR_END] DATETIME2(3) NOT NULL  -- Appraisal End date,
    CONSTRAINT [PK_DD_APPRAISALBREAK] PRIMARY KEY ([DD_PIN_NUM])
);



-- Table: DD_APPRAISALDETAILS
CREATE TABLE [DD_APPRAISALDETAILS] (
    [DD_PIN_NUM] DECIMAL(38) NULL  -- PIN No,
    [DD_USR_ID] VARCHAR(25) NULL  -- User ID,
    [DD_USR_SLT] VARCHAR(4) NULL  -- User Salute,
    [DD_USR_FNM] VARCHAR(65) NULL  -- First Name,
    [DD_USR_MNM] VARCHAR(65) NULL  -- Middle Name,
    [DD_USR_LNM] VARCHAR(65) NULL  -- Last Name,
    [DD_USR_BND] DECIMAL(38) NULL  -- Band,
    [DD_CEO_NAM2] VARCHAR(150) NULL  -- Signatory Name,
    [DD_CEO_DSG2] VARCHAR(100) NULL  -- Signatory Designation,
    [DD_EFF_FROM] DATETIME2(3) NULL  -- Compensation Effective From,
    [DD_INC_AMT] DECIMAL(38) NULL  -- Increment Amount,
    [DD_BAS_OLD] DECIMAL(38) NULL  -- Old Basic,
    [DD_BAS_NEW] DECIMAL(38) NULL  -- New Basic,
    [DD_CTC_OLD] DECIMAL(38) NULL  -- CTC Old,
    [DD_CTC_NEW] DECIMAL(38) NULL  -- CTC New,
    [DD_GRT_AVL] CHAR(1) NULL  -- Gratuity Availability Flag,
    [DD_SUP_AVL] CHAR(1) NULL  -- Superannuation Availability Flag,
    [DD_PF_AVL] CHAR(1) NULL  -- PF Availability Flag,
    [DD_NEW_FLX] DECIMAL(38) NULL  -- New Flexipay,
    [DD_CEO_NAM] VARCHAR(150) NULL  -- CEO Name,
    [DD_CEO_DSG] VARCHAR(100) NULL  -- CEO Designation,
    [DD_APR_END] DATETIME2(3) NULL  -- Appraiser End Date,
    [DD_USR_DSG] VARCHAR(100) NULL  -- Employee Designation,
    [DD_VTC_RAT] VARCHAR(4) NULL  -- Final VTC Rating,
    [DD_REQ_NUM] DECIMAL(38) NOT NULL  -- DD Request No,
    [DD_PRM_BND] DECIMAL(38) NULL  -- Promotion Band,
    [DD_EMP_TYP] CHAR(3) NULL  -- Employee Type (Probationers - PRB, Regular - REG),
    [DD_INC_DD] DECIMAL(38) NULL,
    [DD_BLT_PERCENT] DECIMAL(38) NULL,
    [DD_PRMLEVEL] DECIMAL(38) NULL,
    [DD_REPUNIT] CHAR(3) NULL,
    [DD_PAYROLL] CHAR(1) NULL  -- N- Processing, A- Approved HR ,C- Approved by All CEO, S- Digitally Signed In Letter, R- Released Letter to Appraiser, E- Release to Employee, Y- Pushed to Payroll,
    [DD_EMPGRADEID] DECIMAL(38) NULL,
    [DD_EMPLEVELID] DECIMAL(38) NULL,
    [DD_EMPUNITID] DECIMAL(38) NULL,
    [DD_YEARID] DECIMAL(38) NULL,
    [DD_INCTEMPLATEID] DECIMAL(38) NULL,
    [DD_RATETEMPLATEID] DECIMAL(38) NULL,
    [DD_NEWGRADE] DECIMAL(38) NULL,
    [DD_LETFILE] VARCHAR(30) NULL,
    [DD_EXPMONTHS] DECIMAL(38) NULL
);



-- Table: DD_APPRAISAL_LETRELEASE
CREATE TABLE [DD_APPRAISAL_LETRELEASE] (
    [DD_YEARID] DECIMAL(38) NOT NULL,
    [DD_PIN_NUM] DECIMAL(38) NOT NULL,
    [APPROVER_SYSID] DECIMAL(38) NOT NULL,
    [APPROVER_MAILDATE] DATETIME2(3) NULL,
    [APPROVER_MAILBY] DECIMAL(38) NULL,
    [DD_RELEASE_DATE] DATETIME2(3) NULL,
    [DD_RELEASE_BY] DECIMAL(38) NULL
);



-- Table: DD_APPRAISECOMPASSESS
CREATE TABLE [DD_APPRAISECOMPASSESS] (
    [AS_ASS_SRL] DECIMAL(38) NOT NULL,
    [AS_REQ_NUM] DECIMAL(38) NOT NULL,
    [AS_CPD_NUM] DECIMAL(38) NOT NULL,
    [AS_SPECIFIC] VARCHAR(2000) NULL,
    [AS_DEV_NEED] VARCHAR(2000) NULL,
    [AS_USR_COD] VARCHAR(25) NOT NULL,
    [AS_PIN_NUM] DECIMAL(38) NOT NULL,
    [AS_CREATEDON] DATETIME2(3) NOT NULL,
    [AS_MODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_DD_APPRAISECOMPASSESS] PRIMARY KEY ([AS_ASS_SRL])
);



-- Table: DD_APPRAISECOMPASSESS_CTG
CREATE TABLE [DD_APPRAISECOMPASSESS_CTG] (
    [AS_ASS_SRL] DECIMAL(38) NOT NULL,
    [AS_REQ_NUM] DECIMAL(38) NOT NULL,
    [AS_CPD_NUM] DECIMAL(38) NOT NULL,
    [AS_SPECIFIC] VARCHAR(2000) NULL,
    [AS_DEV_NEED] VARCHAR(2000) NULL,
    [AS_USR_COD] VARCHAR(25) NOT NULL,
    [AS_PIN_NUM] DECIMAL(38) NOT NULL,
    [AS_CREATEDON] DATETIME2(3) NOT NULL,
    [AS_MODIFIEDON] DATETIME2(3) NOT NULL
);



-- Table: DD_APPRAISEEGOAL_CUR
CREATE TABLE [DD_APPRAISEEGOAL_CUR] (
    [AG_REQ_NUM] DECIMAL(38) NULL  -- Request Number,
    [AG_SRL_NUM] DECIMAL(38) NULL  -- Serial Number,
    [AG_PER_DES] VARCHAR(4000) NULL  -- Person Designation,
    [AG_UNT_FRM] VARCHAR(20) NULL  -- Unit From,
    [AG_UNT_TO] VARCHAR(20) NULL  -- Unit To,
    [AG_APP_RMK] VARCHAR(4000) NULL  -- Appraisee Remark,
    [AG_CAN_RMK] VARCHAR(4000) NULL  -- Remark,
    [AG_USR_ID] VARCHAR(50) NULL  -- User id,
    [AG_WEIGHTAGE] DECIMAL(38) NULL  -- Refernce Number,
    [AG_FIN_STR] DATETIME2(3) NULL  -- Financial Start Date,
    [AG_FIN_END] DATETIME2(3) NULL  -- Financial End Date,
    [AG_PIN_NUM] DECIMAL(38) NULL  -- Pin Number,
    [AG_APS_STS] CHAR(1) NULL  -- STATUS OF THE GOALSHEET N-with apraisee, Y-completed by apraisee n pending with one of the aprraisers ;C- completed by all appraisers and pending with appriasee for feedback acceptance; A- feedback(oral) accepted by appraisee(midyear review),
    [AG_ACH] VARCHAR(4000) NULL  -- Achievements(Midyear Review),
    [AG_DIFF] VARCHAR(4000) NULL  -- Difficulties Faced(Midyear Review),
    [AG_CATEGORY] VARCHAR(100) NULL  -- Category(added for 2007-08),
    [AG_UOM] VARCHAR(65) NULL  -- UOM(added for 2007-08),
    [AG_MOD_SRLNO] DECIMAL(38) NULL  -- New Serial number in case if goal is modified(for Midyear review),
    [AG_EXPCOD] VARCHAR(3) NULL  -- LI-live,DR-Drop,MD-Modified(Midyear Review),
    [AG_GOL_FLG] VARCHAR(3) NULL  -- V-to edit,N-cannot edit(Midyear Review),
    [AG_ACCOUNTABILITYID] DECIMAL(38) NULL
);



-- Table: DD_APPRAISEEGOAL_CUR_LOG
CREATE TABLE [DD_APPRAISEEGOAL_CUR_LOG] (
    [AG_REQ_NUM] DECIMAL(38) NULL,
    [AG_SRL_NUM] DECIMAL(38) NULL,
    [AG_PER_DES] VARCHAR(4000) NULL,
    [AG_UNT_FRM] VARCHAR(20) NULL,
    [AG_UNT_TO] VARCHAR(20) NULL,
    [AG_FIN_STR] DATETIME2(3) NULL,
    [AG_FIN_END] DATETIME2(3) NULL,
    [AG_PIN_NUM] DECIMAL(38) NULL,
    [AG_CATEGORY] VARCHAR(100) NULL,
    [AG_UOM] VARCHAR(65) NULL,
    [AG_ENTERDATE] DATETIME2(3) NULL  -- Enter Date,
    [AG_ACCOUNTABILITYID] DECIMAL(38) NULL,
    [AG_WEIGHTAGE] DECIMAL(38) NULL
);



-- Table: DD_APPRAISEESKILLS
CREATE TABLE [DD_APPRAISEESKILLS] (
    [AS_REQ_NUM] DECIMAL(38) NULL  -- Request Number,
    [AS_QTN_NUM] DECIMAL(38) NULL  -- Question Number,
    [AS_SRL_NUM] DECIMAL(38) NULL  -- Serial Number,
    [AS_SKL_TYP] VARCHAR(3) NULL  -- Skill Type,
    [AS_SKL_DES] VARCHAR(1000) NULL  -- Skill Description,
    [AS_SKL_ANS] VARCHAR(1) NULL  -- Skill Answer,
    [AS_SKL_DET] VARCHAR(1000) NULL  -- Skill Detail,
    [AS_EMP_PIN] DECIMAL(38) NULL  -- Employee Pin,
    [AS_APR_ID] VARCHAR(100) NULL  -- Appraiser Pin,
    [AS_STR_FIN] DATETIME2(3) NULL  -- Fin Start Date,
    [AS_END_FIN] DATETIME2(3) NULL  -- Fin End Date,
    [AS_FLX1] VARCHAR(100) NULL  -- Flexi Field 1,
    [AS_FLX2] VARCHAR(100) NULL  -- Flexi Field 2,
    [AS_FLX3] VARCHAR(100) NULL  -- Flexi Field 3
);



-- Table: DD_APPRAISELETPLAN_SUBMITTED
CREATE TABLE [DD_APPRAISELETPLAN_SUBMITTED] (
    [LP_ASS_SRL] DECIMAL(38) NOT NULL,
    [LP_INP_FRO] VARCHAR(5) NULL,
    [LP_BEN_FIT] VARCHAR(4000) NULL,
    [LP_CNT_PNT] VARCHAR(4000) NULL,
    [LP_MOD_TRG] VARCHAR(4000) NULL,
    [LP_REQ_NUM] DECIMAL(38) NOT NULL,
    [LP_REF_NUM] DECIMAL(38) NULL,
    [LP_CAP_DEV] VARCHAR(4000) NULL,
    [LP_CAN_DAT] DATETIME2(3) NULL,
    [LP_ANS_SRL] DECIMAL(38) NULL,
    [LP_LET_FLG] VARCHAR(1) NULL,
    [LP_STS_FLG] VARCHAR(100) NULL,
    [LP_APP_COD] VARCHAR(25) NULL,
    [LP_APP_NUM] DECIMAL(38) NULL,
    [LP_CAN_REM] VARCHAR(200) NULL,
    [LP_STS_REM] VARCHAR(4000) NULL,
    [LP_PIN_NUM] DECIMAL(38) NULL,
    [LP_FLX_FLD1] VARCHAR(100) NULL,
    [LP_FLX_FLD2] VARCHAR(100) NULL,
    [LP_FLX_FLD3] VARCHAR(100) NULL
);



-- Table: DD_APPRAISEMAIL
CREATE TABLE [DD_APPRAISEMAIL] (
    [DD_APP_ID] VARCHAR(65) NULL
);



-- Table: DD_APPRAISEMAIN
CREATE TABLE [DD_APPRAISEMAIN] (
    [AP_REQ_NUM] DECIMAL(38) NOT NULL  -- REQUEST NUMBER GENERATED FROM SRFSPARSH. REQUEST_MAIN,
    [AP_USR_COD] VARCHAR(25) NOT NULL  -- USER CODE OF THE EMPLOYEE,
    [AP_ENT_DAT] DATETIME2(3) NOT NULL  -- DD ENTRY DATE,
    [AP_GRADEID] DECIMAL(38) NULL  -- Appraisee Grade ID,
    [AP_UNITID] DECIMAL(38) NULL  -- Appraisee Unit ID,
    [AP_YEARID] DECIMAL(38) NULL  -- DD Year ID,
    [AP_CAN_REM] VARCHAR(4000) NULL  -- SELF APPRAISAL CANCELLATION REMARKS,
    [AP_STS_COD] VARCHAR(1) NULL  -- I - INCOMPLETE; N - SUBMITTED BY APPRAISEE; A - PENDING WITH APPRAISER; S - SUBMITTED BY APPRAISER;  C - AFTER ACKNOWLEDGE FROM APPRAISE,
    [AP_ST_FIN] DATETIME2(3) NULL  -- APPRAISIAL START DATE,
    [AP_ED_FIN] DATETIME2(3) NULL  -- APPRAISIAL END DATE,
    [AP_FIN_DAT] DATETIME2(3) NULL  -- DD COMPLETED ON,
    [AP_USR_NUM] DECIMAL(38) NULL  -- USER NO OF THE EMPLOYEE,
    [AP_PIN_NUM] DECIMAL(38) NULL,
    [AP_DD_TYPE] VARCHAR(10) NULL,
    [AP_CAN_APPRID] DECIMAL(38) NULL,
    [AP_CANCELDATE] DATETIME2(3) NULL,
    [AP_SUBORDINATE] CHAR(1) NULL,
    CONSTRAINT [PK_DD_APPRAISEMAIN] PRIMARY KEY ([AP_REQ_NUM])
);



-- Table: DD_APPRAISEMAIN_LOG
CREATE TABLE [DD_APPRAISEMAIN_LOG] (
    [AP_REQ_NUM] DECIMAL(38) NOT NULL,
    [AP_USR_COD] VARCHAR(25) NOT NULL,
    [AP_ENT_DAT] DATETIME2(3) NOT NULL,
    [AP_GRADEID] DECIMAL(38) NULL,
    [AP_UNITID] DECIMAL(38) NULL,
    [AP_YEARID] DECIMAL(38) NULL,
    [AP_CAN_REM] VARCHAR(4000) NULL,
    [AP_STS_COD] VARCHAR(1) NULL,
    [AP_ST_FIN] DATETIME2(3) NULL,
    [AP_ED_FIN] DATETIME2(3) NULL,
    [AP_FIN_DAT] DATETIME2(3) NULL,
    [AP_USR_NUM] DECIMAL(38) NULL,
    [AP_PIN_NUM] DECIMAL(38) NULL,
    [AP_DD_TYPE] VARCHAR(10) NULL,
    [AP_CAN_APPRID] DECIMAL(38) NULL,
    [AP_CANCELDATE] DATETIME2(3) NULL,
    [AP_SUBORDINATE] CHAR(1) NULL,
    [AP_LOGCREATEDBY] DECIMAL(38) NULL,
    [AP_LOGCREATEDON] DATETIME2(3) NULL
);



-- Table: DD_APPRAISERASSESS
CREATE TABLE [DD_APPRAISERASSESS] (
    [AP_REQ_NUM] DECIMAL(38) NOT NULL  -- REQUEST NO,
    [AP_CPD_NUM] DECIMAL(38) NOT NULL  -- COMPETENCY NO,
    [AP_REM_MRK] VARCHAR(1000) NULL  -- REMARKS,
    [AP_ASS_RAT] DECIMAL(38) NULL  -- ASSESSMENT RATING,
    [AP_SLF_DEV] VARCHAR(4000) NULL  -- SELF DEVELOPMENT,
    [AP_JOB_DEV] VARCHAR(4000) NULL  -- JOB DEVELOPMENT,
    [AP_TRG_DEV] VARCHAR(4000) NULL  -- TRAININNG DEVELOPMENT,
    [AP_USR_COD] VARCHAR(25) NOT NULL  -- APPRAISER USER CODE,
    [AP_ASS_SRL] DECIMAL(38) NOT NULL  -- SERIAL NO,
    [AP_REF_SRLNO] DECIMAL(38) NULL  -- APPRAISER USER NO,
    [AP_CAN_DAT] DATETIME2(3) NULL  -- CANCELLATION DATE,
    [AP_CAN_REM] VARCHAR(4000) NULL  -- CANCELLATION REMARKS,
    [AP_PIN_NUM] DECIMAL(38) NULL,
    [AP_COMP_RATING] DECIMAL(38) NULL  -- Competency Rating,
    [AP_ROLE] VARCHAR(20) NULL  -- Competency Specification,
    CONSTRAINT [PK_DD_APPRAISERASSESS] PRIMARY KEY ([AP_ASS_SRL])
);



-- Table: DD_APPRAISERASSESS_LOG
CREATE TABLE [DD_APPRAISERASSESS_LOG] (
    [AP_LOG_NUM] DECIMAL(38) NOT NULL  -- LOG NUMBER,
    [AP_LOG_DAT] DATETIME2(3) NOT NULL  -- LOG DATE,
    [AP_REM_MRK] VARCHAR(1000) NULL  -- REMARKS,
    [AP_ASS_RAT] DECIMAL(38) NULL  -- ASSESSMENT RATING,
    [AP_SLF_DEV] VARCHAR(4000) NULL  -- SELF DEVELOPMENT,
    [AP_JOB_DEV] VARCHAR(4000) NULL  -- JOB DEVELOPMENT,
    [AP_TRG_DEV] VARCHAR(4000) NULL  -- TRAININNG DEVELOPMENT,
    [AP_APP_SRL] DECIMAL(38) NULL  -- SERIAL NUMBER FROM TABLE DD_APPAISERASSESS FOR REF,
    [AP_APP_COD] VARCHAR(25) NULL  -- APPRAISER USER CODE,
    [AP_APP_NUM] DECIMAL(38) NULL  -- APPRAISER USER NO,
    [AP_CAN_DAT] DATETIME2(3) NULL  -- CANCELLATION DATE,
    [AP_CAN_REM] VARCHAR(4000) NULL  -- CANCELLATION REMARKS,
    [AP_REF_SRLNO] DECIMAL(38) NULL,
    CONSTRAINT [PK_DD_APPRAISERASSESS_LOG] PRIMARY KEY ([AP_LOG_NUM])
);



-- Table: DD_APPRAISERASSESS_PROM
CREATE TABLE [DD_APPRAISERASSESS_PROM] (
    [AP_REQ_NUM] DECIMAL(38) NOT NULL  -- REQUEST NO,
    [AP_CPD_NUM] DECIMAL(38) NOT NULL  -- COMPETENCY NO,
    [AP_REM_MRK] VARCHAR(1000) NULL  -- REMARKS,
    [AP_ASS_RAT] DECIMAL(38) NULL  -- ASSESSMENT RATING,
    [AP_SLF_DEV] VARCHAR(4000) NULL  -- SELF DEVELOPMENT,
    [AP_JOB_DEV] VARCHAR(4000) NULL  -- JOB DEVELOPMENT,
    [AP_TRG_DEV] VARCHAR(4000) NULL  -- TRAININNG DEVELOPMENT,
    [AP_USR_COD] VARCHAR(25) NOT NULL  -- APPRAISER USER CODE,
    [AP_ASS_SRL] DECIMAL(38) NOT NULL  -- SERIAL NO,
    [AP_USR_NUM] DECIMAL(38) NULL  -- APPRAISER USER NO,
    [AP_CAN_DAT] DATETIME2(3) NULL  -- CANCELLATION DATE,
    [AP_CAN_REM] VARCHAR(4000) NULL  -- CANCELLATION REMARKS,
    [AP_PIN_NUM] DECIMAL(38) NULL,
    [AP_COMP_RATING] DECIMAL(38) NULL  -- Competency Rating,
    [AP_ROLE] VARCHAR(20) NULL  -- Competency Specification
);



-- Table: DD_APPRAISEREMINDER
CREATE TABLE [DD_APPRAISEREMINDER] (
    [DD_USR_ID] VARCHAR(65) NULL,
    [DD_USR_NAM] VARCHAR(200) NULL,
    [DD_USR_EML] VARCHAR(100) NULL,
    [DD_APP_ID] VARCHAR(65) NULL,
    [DD_APP_NAM] VARCHAR(200) NULL,
    [DD_REQ_DAT] DATETIME2(3) NULL,
    [DD_APP_STS] CHAR(1) NULL,
    [DD_REF_ID] DECIMAL(38) NULL,
    [DD_REQ_NUM] DECIMAL(38) NULL,
    [DD_APR_EML] VARCHAR(100) NULL,
    [DD_LST_REM] DATETIME2(3) NULL,
    [DD_MAL_FLG] VARCHAR(6) NULL,
    [DDMIDCOM_REVIEWID] DECIMAL(38) NULL,
    [DD_STATUS] VARCHAR(200) NULL
);



-- Table: DD_APPRAISERENTRY
CREATE TABLE [DD_APPRAISERENTRY] (
    [AP_REQ_NUM] DECIMAL(38) NOT NULL  -- REQUEST NO,
    [AP_QTN_NUM] DECIMAL(38) NOT NULL  -- QUESTION NO,
    [AP_ANS_SRL] DECIMAL(38) NOT NULL  -- ANSWER SERIAL NO,
    [AP_ANS_NAM] VARCHAR(4000) NULL  -- DESCRIPTION,
    [AP_USR_COD] VARCHAR(25) NOT NULL  -- APPRAISER USER CODE,
    [AP_ASS_SRL] DECIMAL(38) NOT NULL  -- SERIAL NO,
    [AP_USR_NUM] DECIMAL(38) NULL  -- APPRAISER USER NO,
    [AP_ENT_DAT] DATETIME2(3) NULL  -- ENTERED ON,
    [AP_CAN_DAT] DATETIME2(3) NULL  -- CANCELLATION DATE,
    [AP_CAN_REM] VARCHAR(4000) NULL  -- CANCELLATION REMARKS,
    [AP_APP_ID] VARCHAR(25) NULL  -- CANCELLED BY APPRAISER ID,
    [AP_APP_NUM] DECIMAL(38) NULL  -- CANCELLED BY APPRAISER NO,
    [AP_PIN_NUM] DECIMAL(38) NULL,
    CONSTRAINT [PK_DD_APPRAISERENTRY] PRIMARY KEY ([AP_ASS_SRL])
);



-- Table: DD_APPRAISERENTRY_LOG
CREATE TABLE [DD_APPRAISERENTRY_LOG] (
    [AP_LOG_NUM] DECIMAL(38) NOT NULL  -- LOG NUMBER,
    [AP_LOG_DAT] DATETIME2(3) NOT NULL  -- LOG DATE,
    [AP_ANS_NAM] VARCHAR(4000) NULL  -- ANSWER CODE FOR THE QUESTIONS,
    [AP_APP_SRL] DECIMAL(38) NULL  -- DD-APPRAISERENTRY SERIAL FOR REFERENCE PURPOSE OF LOG,
    [AP_CAN_DAT] DATETIME2(3) NULL  -- CANCELLATION DATE,
    [AP_CAN_REM] VARCHAR(4000) NULL  -- CANCELLATION REMARKS,
    [AP_APP_ID] VARCHAR(25) NULL  -- CANCELLED BY APPRAISER ID,
    [AP_APP_NUM] DECIMAL(38) NULL  -- CANCELLED BY APPRAISER NO,
    [AP_REQ_NUM] DECIMAL(38) NULL,
    [AP_QTN_NUM] DECIMAL(38) NULL,
    [AP_PIN_NUM] DECIMAL(38) NULL,
    CONSTRAINT [PK_DD_APPRAISERENTRY_LOG] PRIMARY KEY ([AP_LOG_NUM])
);



-- Table: DD_APPRAISERLETPLAN
CREATE TABLE [DD_APPRAISERLETPLAN] (
    [LT_ASS_SRL] DECIMAL(38) NOT NULL  -- SERIAL NUMBER,
    [LT_INP_FRO] VARCHAR(5) NULL  -- INPUT FROM,
    [LT_BEN_FIT] VARCHAR(4000) NULL  -- BENEFITS,
    [LT_CNT_PNT] VARCHAR(4000) NULL  -- CONTROL POINTS,
    [LT_MOD_TRG] VARCHAR(4000) NULL  -- MODE OF TRAINING,
    [LT_REQ_NUM] DECIMAL(38) NOT NULL  -- REQUEST NUMBER,
    [LT_CAP_DEV] VARCHAR(4000) NULL  -- CAPABILITY TO BE DEVELOPED,
    [LT_CAN_DAT] DATETIME2(3) NULL  -- CANCEL DATE,
    [LT_ANS_SRL] DECIMAL(38) NULL  -- ANSWER SERIAL NO,
    [LT_LET_FLG] CHAR(1) NULL  -- P - PREVOIUS YEAR; C - CURRENT YEAR,
    [LT_STS_FLG] CHAR(1) NULL  -- C - COMPLETE; I - INCOMPLETE,
    [LT_APP_COD] VARCHAR(25) NULL  -- APPRASIER USER CODE,
    [LT_APP_NUM] DECIMAL(38) NULL  -- APPRASIER USER NO,
    [LT_CAN_REM] VARCHAR(200) NULL  -- CANCELLATION REMARKS,
    [LT_STS_REM] VARCHAR(4000) NULL  -- REMARKS IF INCOMPLETE,
    [LT_PIN_NUM] DECIMAL(38) NULL,
    CONSTRAINT [PK_DD_APPRAISERLETPLAN] PRIMARY KEY ([LT_ASS_SRL])
);



-- Table: DD_APPRAISERLETPLAN_LOG
CREATE TABLE [DD_APPRAISERLETPLAN_LOG] (
    [LT_LOG_NUM] DECIMAL(38) NOT NULL  -- LOG NUMBER,
    [LT_LOG_DAT] DATETIME2(3) NOT NULL  -- LOG DATE,
    [LT_BEN_FIT] VARCHAR(4000) NULL  -- BENEFITS,
    [LT_CNT_PNT] VARCHAR(4000) NULL  -- CONTROL POINTS,
    [LT_MOD_TRG] VARCHAR(4000) NULL  -- MODE OF TRAINING,
    [LT_CAP_DEV] VARCHAR(4000) NULL  -- CAPABILITY TO BE DEVELOPED,
    [LT_CAN_DAT] DATETIME2(3) NULL  -- CANCEL DATE,
    [LT_INP_FRO] VARCHAR(5) NULL  -- INPUT FROM,
    [LT_LET_FLG] CHAR(1) NULL  -- P - PREVIOUS YEAR; C - CURRENT YEAR,
    [LT_STS_FLG] CHAR(1) NULL  -- C - COMPLETE; I - INCOMPLETE,
    [LT_STS_REM] VARCHAR(4000) NULL  -- REMARKS IF INCOMPLETE,
    [LT_APP_COD] VARCHAR(25) NULL  -- APPRAISER USER CODE,
    [LT_APP_NUM] DECIMAL(38) NULL  -- APPRAISER USER NO,
    [LT_REQ_NUM] DECIMAL(38) NULL  -- REQUEST NUMBER,
    [LT_CAN_REM] VARCHAR(200) NULL  -- CANCELLATIAON REMARKS,
    [LT_ANS_SRL] DECIMAL(38) NULL  -- ANSWER SERIAL NO,
    [LT_SRL_NUM] DECIMAL(38) NULL  -- LET SERIAL NO,
    [LT_LET_SRL] DECIMAL(38) NULL  -- let serial number,
    CONSTRAINT [PK_DD_APPRAISERLETPLAN_LOG] PRIMARY KEY ([LT_LOG_NUM])
);



-- Table: DD_APPRAISESLFPER
CREATE TABLE [DD_APPRAISESLFPER] (
    [AP_REQ_NUM] DECIMAL(38) NOT NULL  -- REQUEST NUMBER FOR SELF PERFORMANCE FOR APPRAISE,
    [AP_PER_SRL] DECIMAL(38) NOT NULL  -- SELF PERFORMANCE REVIEW SERIAL NUMBER,
    [AP_PER_DES] VARCHAR(4000) NULL  -- PERFORMANCE DESCRIPTION,
    [AP_PER_RAT] VARCHAR(50) NULL  -- SELF PERFORMANCE RATING,
    [AP_UNT_FRO] VARCHAR(50) NULL  -- UNIT MAY BE IN DATE OR NUMERIC,
    [AP_UNT_TO] VARCHAR(50) NULL  -- UNIT MAY BE IN DATE OR NUMERIC,
    [AP_UNT_ACT] VARCHAR(50) NULL  -- UNIT MAY BE IN DATE OR NUMERIC,
    [AP_PER_RMK] VARCHAR(4000) NULL  -- REMARKS,
    [AP_ASS_WEIGHTAGE] DECIMAL(38) NULL  -- SERIAL NUMBER,
    [AP_CAN_DAT] DATETIME2(3) NULL  -- cancel date,
    [AP_APP_ID] VARCHAR(30) NULL  -- APPRAISER CODE,
    [AP_APP_NUM] DECIMAL(38) NULL  -- APPRAISER NO,
    [AP_CAN_REM] VARCHAR(4000) NULL  -- CANCELLATION REMARKS,
    [AP_UNT_MSR] VARCHAR(65) NULL  -- UNIT OF MEASUREMENT,
    [AP_PER_RAT1] VARCHAR(50) NULL  -- APPRAISER PERPORMANCE RATING,
    [AP_PER_RMK1] VARCHAR(4000) NULL  -- APPRAISER REMARKS,
    [AP_PER_CAT] VARCHAR(50) NULL  -- Category,
    [AP_PER_RATING] DECIMAL(38) NULL  -- Performance Rating,
    [AP_PERF_RATING] DECIMAL(38) NULL  -- Appraisee Results Rating,
    [AP_MEAN_RATING] DECIMAL(38) NULL  -- Appraisee Means Rating,
    [AP_APPPERF_RATING] DECIMAL(38) NULL  -- Appraiser Results Rating,
    [AP_APPMEAN_RATING] DECIMAL(38) NULL  -- Appraiser Means Rating,
    [AP_MEAN_REMARKS] VARCHAR(4000) NULL  -- Appraisee Means Remarks,
    [AP_APPMEAN_REMARKS] VARCHAR(4000) NULL  -- Appraiser Means Remarks,
    CONSTRAINT [PK_DD_APPRAISESLFPER] PRIMARY KEY ([AP_REQ_NUM])
);



-- Table: DD_APPRAISESLFPER_LOG
CREATE TABLE [DD_APPRAISESLFPER_LOG] (
    [AP_LOG_NUM] DECIMAL(38) NOT NULL  -- LOG NUMBER SELF PERFORMANCE FOR APPRAISE,
    [AP_LOG_DAT] DATETIME2(3) NOT NULL  -- LOG DATE,
    [AP_PER_RMK] VARCHAR(4000) NULL  -- REMARKS,
    [AP_PER_RAT] VARCHAR(50) NULL  -- SELF PERFORMANCE RATING,
    [AP_UNT_FRO] VARCHAR(50) NULL  -- UNIT MAY BE IN DATE OR NUMERIC,
    [AP_UNT_TO] VARCHAR(50) NULL  -- UNIT MAY BE IN DATE OR NUMERIC,
    [AP_UNT_ACT] VARCHAR(50) NULL  -- UNIT MAY BE IN DATE OR NUMERIC,
    [AP_APP_SRL] DECIMAL(38) NULL  -- DD_APPRAISESLFPER FOR REFEERNCE,
    [AP_CAN_DAT] DATETIME2(3) NULL  -- cancel date,
    [AP_APP_ID] VARCHAR(25) NULL  -- APPRAISER ID,
    [AP_APP_NUM] DECIMAL(38) NULL  -- APPRAISER NO,
    [AP_CAN_REM] VARCHAR(4000) NULL  -- CANCELLATION REMARKS,
    [AP_UNT_MSR] VARCHAR(65) NULL  -- unit of measurement,
    [AP_PER_RAT1] VARCHAR(50) NULL  -- APPRAISER PERPORMANCE RATING,
    [AP_PER_RMK1] VARCHAR(4000) NULL  -- APPRAISER REMARKS,
    [AP_PER_CAT] VARCHAR(50) NULL  -- Category,
    [AP_PER_RATING] DECIMAL(38) NULL  -- Performance Rating,
    [AP_PERF_RATING] DECIMAL(38) NULL  -- Appraisee Results Rating,
    [AP_MEAN_RATING] DECIMAL(38) NULL  -- Appraisee Means Rating,
    [AP_APPPERF_RATING] DECIMAL(38) NULL  -- Appraiser Results Rating,
    [AP_APPMEAN_RATING] DECIMAL(38) NULL  -- Appraiser Means Rating,
    [AP_MEAN_REMARKS] VARCHAR(4000) NULL  -- Appraisee Means Remarks,
    [AP_APPMEAN_REMARKS] VARCHAR(4000) NULL  -- Appraiser Means Remarks,
    CONSTRAINT [PK_DD_APPRAISESLFPER_LOG] PRIMARY KEY ([AP_LOG_NUM])
);



-- Table: DD_APPRAISESTATUS
CREATE TABLE [DD_APPRAISESTATUS] (
    [DD_USR_ID] VARCHAR(65) NULL  -- User ID,
    [DD_USR_PIN] DECIMAL(38) NULL  -- User Pin Number,
    [DD_BUS_COD] VARCHAR(9) NULL  -- Business Code,
    [DD_BUS_NAM] VARCHAR(65) NULL  -- Business Name,
    [DD_COM_COD] VARCHAR(3) NULL  -- Company Code,
    [DD_COM_NAM] VARCHAR(65) NULL  -- Company Name,
    [DD_TOT_APP] DECIMAL(38) NULL  -- Total Applicable,
    [DD_APP_COM] DECIMAL(38) NULL  -- Appraiser Comments,
    [DD_APP_PEN] DECIMAL(38) NULL,
    [DD_APR_REC] DECIMAL(38) NULL  -- Appraiser Recommendation,
    [DD_APR_COM] DECIMAL(38) NULL,
    [DD_APR_PEN] DECIMAL(38) NULL,
    [DD_REV_REC] DECIMAL(38) NULL  -- Reviewer Recommendation,
    [DD_REV_COM] DECIMAL(38) NULL  -- Reviewer Comment,
    [DD_REV_PEN] DECIMAL(38) NULL,
    [DD_STS_UPD] DATETIME2(3) NULL  -- Status Updated by,
    [DD_FDBCK_REC] DECIMAL(38) NULL  -- for capturing appraisee feedback acceptance,
    [DD_FDBCK_COM] DECIMAL(38) NULL,
    [DD_FDBCK_PEN] DECIMAL(38) NULL,
    [DD_APPR_NOTDEFINED] DECIMAL(38) NULL,
    [DD_DEFINENO] DECIMAL(38) NULL
);



-- Table: DD_APPRAISEVOICE
CREATE TABLE [DD_APPRAISEVOICE] (
    [AV_REQ_NUM] DECIMAL(38) NOT NULL  -- REQUEST NUMBER,
    [AV_QTN_NUM] DECIMAL(38) NOT NULL  -- QUESTION NUMBER,
    [AV_ANS_SRL] DECIMAL(38) NOT NULL  -- ANSWER SERIAL NUMBER,
    [AV_ANS_NAM] VARCHAR(4000) NULL  -- ANSWER FOR THE QUESTION,
    [AV_ASS_SRL] DECIMAL(38) NOT NULL  -- SERIAL NUMBER,
    [AV_PER_NAM] VARCHAR(4000) NULL  -- PERSONAL SKILLS,
    [AV_CAN_DAT] DATETIME2(3) NULL  -- cancellation date,
    [AV_APP_ID] VARCHAR(30) NULL  -- CANCELLED BY APPRAISER ID,
    [AV_APP_NUM] DECIMAL(38) NULL  -- CANCELLED BY APPRAISER NO,
    [AV_CAN_REM] VARCHAR(4000) NULL  -- CANCELLATION REMARKS,
    CONSTRAINT [PK_DD_APPRAISEVOICE] PRIMARY KEY ([AV_ASS_SRL])
);



-- Table: DD_APPRAISEVOICE_LOG
CREATE TABLE [DD_APPRAISEVOICE_LOG] (
    [AV_LOG_NUM] DECIMAL(38) NOT NULL  -- LOG NUMBER,
    [AV_LOG_DAT] DATETIME2(3) NOT NULL  -- LOG DATE,
    [AV_ANS_NAM] VARCHAR(4000) NULL  -- ANSWER FOR THE QUESTION,
    [AV_PER_NAM] VARCHAR(4000) NULL  -- PERSONAL SKILLS,
    [AV_APP_SRL] DECIMAL(38) NULL  -- DD_APPRAISEVOICE SERIAL  REFERENCE,
    [AV_CAN_DAT] DATETIME2(3) NULL  -- CANCELLATION DATE,
    [AV_APP_ID] VARCHAR(30) NULL  -- CANCELLED BY APPRAISER ID,
    [AV_CAN_REM] VARCHAR(4000) NULL  -- CANCELLATION REMARKS,
    [AV_APP_NUM] DECIMAL(38) NULL  -- CANCELLED BY APPRAISER NO,
    [AV_REQ_NUM] DECIMAL(38) NULL,
    [AV_QTN_NUM] DECIMAL(38) NULL,
    [AV_ASS_SRL] DECIMAL(38) NULL,
    CONSTRAINT [PK_DD_APPRAISEVOICE_LOG] PRIMARY KEY ([AV_LOG_NUM])
);



-- Table: DD_APR_STRENGTHWEEK
CREATE TABLE [DD_APR_STRENGTHWEEK] (
    [AP_REQ_NUM] DECIMAL(38) NOT NULL,
    [AP_QTN_NUM] DECIMAL(38) NOT NULL,
    [AP_SRL_NUM] DECIMAL(38) NOT NULL,
    [AP_PIN_NUM] DECIMAL(38) NOT NULL,
    [AP_USR_COD] VARCHAR(25) NOT NULL,
    [AP_STRENGTH] VARCHAR(4000) NULL,
    [AP_IMPROVEMENT] VARCHAR(4000) NULL,
    [AP_CREATEDON] DATETIME2(3) NULL,
    [AP_MODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_DD_APR_STRENGTHWEEK] PRIMARY KEY ([AP_REQ_NUM])
);



-- Table: DD_CAT_DEV_DETAIL_APPRAISEE
CREATE TABLE [DD_CAT_DEV_DETAIL_APPRAISEE] (
    [CT_REQ_NUM] DECIMAL(38) NULL  -- Request Number,
    [CT_QTN_NUM] DECIMAL(38) NULL  -- Question Number,
    [CT_ANS_SRL] DECIMAL(38) NULL  -- Answer Serial,
    [CT_APP_ID] VARCHAR(30) NOT NULL  -- Appraiser Id,
    [CT_APP_NUM] DECIMAL(38) NOT NULL  -- Appraiser Number,
    [CT_ENT_DAT] DATETIME2(3) NULL  -- Entered Date,
    [CT_DESC] VARCHAR(400) NULL  -- Description,
    [CT_NEED] VARCHAR(400) NULL  -- Need
);



-- Table: DD_GOALAPPRAISERSTS
CREATE TABLE [DD_GOALAPPRAISERSTS] (
    [GL_GOL_NUM] DECIMAL(38) NULL  -- Goal Number,
    [GL_STS_FLG] CHAR(1) NULL  -- Status Flag,
    [GL_APP_ID] VARCHAR(25) NULL  -- Appraiser Id,
    [GL_APP_PIN] DECIMAL(38) NULL  -- Appraiser Pin Number,
    [GL_LVL_NUM] DECIMAL(38) NULL  -- Level Number,
    [GL_REC_DAT] DATETIME2(3) NULL  -- Reccomendation Date,
    [GL_MOD_DAT] DATETIME2(3) NULL  -- Modified Date
);



-- Table: MIDYEAR_CATEGORY
CREATE TABLE [MIDYEAR_CATEGORY] (
    [MIDYEAR_DEADID] DECIMAL(38) NOT NULL,
    [MIDYEAR_BUSINESSID] DECIMAL(38) NOT NULL,
    [MIDYEAR_GRADECADREID] DECIMAL(38) NOT NULL
);



-- Table: MIDYEAR_DEADLINES
CREATE TABLE [MIDYEAR_DEADLINES] (
    [MIDYEAR_DEADID] DECIMAL(38) NOT NULL,
    [MIDYEAR_ID] DECIMAL(38) NOT NULL,
    [MIDYEAR_BUSINESSID] DECIMAL(38) NOT NULL,
    [MIDYEAR_CUTOFFDATE] DATETIME2(3) NOT NULL,
    [MIDYEAR_APPSTRDATE] DATETIME2(3) NULL,
    [MIDYEAR_APPFORCEDATE] DATETIME2(3) NULL,
    [MIDYEAR_ENDDATE] DATETIME2(3) NULL
);



-- Table: MYR_DEADLINEUSERS
CREATE TABLE [MYR_DEADLINEUSERS] (
    [DL_USER_ID] VARCHAR(25) NULL,
    [DL_PIN_NUM] DECIMAL(38) NULL,
    [DL_CLS_DAT] DATETIME2(3) NULL
);



-- Table: PROB_RESEND
CREATE TABLE [PROB_RESEND] (
    [USR_PINUM] DECIMAL(38) NOT NULL,
    [RESENT_REMARKS] VARCHAR(4000) NULL,
    [RESENT_ON] DATETIME2(3) NULL,
    [REQ_NUM] DECIMAL(38) NULL  -- for 3 months goalnum,for 6 months reqnum,
    [PROB_STS] CHAR(3) NULL  -- N-6 mon start,A-6 mon over,M-3 mon start,C-3 mon over
);



-- Table: REV_PER_DATA
CREATE TABLE [REV_PER_DATA] (
    [PINNUM] DECIMAL(38) NULL  -- Pin Number,
    [EMPNAME] VARCHAR(25) NULL  -- Employee Name,
    [REVBASIC] DECIMAL(38) NULL  -- Revised Basic,
    [REVCTC] DECIMAL(38) NULL  -- Revised CTC,
    [REVBAND] VARCHAR(3) NULL  -- Revised Band,
    [UPDUSER] VARCHAR(25) NULL  -- Updated User,
    [UPDDAT] DATETIME2(3) NULL  -- Updated Date,
    [CLSDAT] DATETIME2(3) NULL  -- Closure Date
);



-- Table: REV_PER_DATABAK
CREATE TABLE [REV_PER_DATABAK] (
    [PINNUM] DECIMAL(38) NULL,
    [EMPNAME] VARCHAR(25) NULL,
    [REVBASIC] DECIMAL(38) NULL,
    [REVCTC] DECIMAL(38) NULL,
    [REVBAND] VARCHAR(3) NULL,
    [UPDUSER] VARCHAR(25) NULL,
    [UPDDAT] DATETIME2(3) NULL,
    [CLSDAT] DATETIME2(3) NULL,
    [FINYER] DATETIME2(3) NULL
);

