-- ==========================================
-- Database: SRFSPARSHDB - Complete Schema
-- Senior Research Fellow (SRF) Scholarship Management System
-- Created: March 2, 2026
-- ==========================================

USE SRFSPARSHDB;
GO

-- ==========================================
-- USER MANAGEMENT TABLES
-- ==========================================

-- APPR_MAST - Approver Master (PER, DDP, LET)
IF OBJECT_ID('dbo.APPR_MAST', 'U') IS NULL
CREATE TABLE [APPR_MAST] (
    [APPR_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [APPR_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [APPR_NAME] VARCHAR(255) NOT NULL,
    [APPR_TYPE] VARCHAR(20) NOT NULL, -- PER, DDP, LET
    [APPR_DESC] NVARCHAR(MAX),
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);

-- APPROVER_EMP - Employee Approver Mapping
IF OBJECT_ID('dbo.APPROVER_EMP', 'U') IS NULL
CREATE TABLE [APPROVER_EMP] (
    [APPROVER_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [EMP_ID] BIGINT NOT NULL,
    [APPR_MAST_ID] BIGINT NOT NULL,
    [APPROVER_LEVEL] INT,
    [AUTHORITY_LIMIT] DECIMAL(19,2),
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT,
    FOREIGN KEY (APPR_MAST_ID) REFERENCES APPR_MAST(APPR_ID)
);

-- GROUP_MAST - User Group Master
IF OBJECT_ID('dbo.GROUP_MAST', 'U') IS NULL
CREATE TABLE [GROUP_MAST] (
    [GROUP_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [GROUP_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [GROUP_NAME] VARCHAR(255) NOT NULL,
    [GROUP_DESC] NVARCHAR(MAX),
    [ADMIN_ID] BIGINT,
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);

-- GROUP_MENUMAP - Group Menu Mapping
IF OBJECT_ID('dbo.GROUP_MENUMAP', 'U') IS NULL
CREATE TABLE [GROUP_MENUMAP] (
    [GROUPMENU_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [GROUP_ID] BIGINT NOT NULL,
    [MENU_ID] BIGINT NOT NULL,
    [PERMISSION_VIEW] BIT DEFAULT 0,
    [PERMISSION_ADD] BIT DEFAULT 0,
    [PERMISSION_EDIT] BIT DEFAULT 0,
    [PERMISSION_DELETE] BIT DEFAULT 0,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    FOREIGN KEY (GROUP_ID) REFERENCES GROUP_MAST(GROUP_ID)
);

-- USER_POLICY - User Policy Table
IF OBJECT_ID('dbo.USER_POLICY', 'U') IS NULL
CREATE TABLE [USER_POLICY] (
    [POLICY_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [USER_ID] BIGINT NOT NULL,
    [POLICY_CODE] VARCHAR(50) NOT NULL,
    [POLICY_DESC] NVARCHAR(MAX),
    [POLICY_VALUE] VARCHAR(MAX),
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);

-- USER_PROFILEHIST - User Profile History
IF OBJECT_ID('dbo.USER_PROFILEHIST', 'U') IS NULL
CREATE TABLE [USER_PROFILEHIST] (
    [PROFILEHIST_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [USER_ID] BIGINT NOT NULL,
    [PROFILE_CODE] VARCHAR(50),
    [PROFILE_NAME] VARCHAR(255),
    [PROFILE_DATA] NVARCHAR(MAX),
    [VALID_FROM] DATE,
    [VALID_TO] DATE,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT
);

-- PROXY_RIGHTS - Proxy User Rights
IF OBJECT_ID('dbo.PROXY_RIGHTS', 'U') IS NULL
CREATE TABLE [PROXY_RIGHTS] (
    [PROXY_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [PRIMARY_USER_ID] BIGINT NOT NULL,
    [PROXY_USER_ID] BIGINT NOT NULL,
    [PROXY_START_DATE] DATE NOT NULL,
    [PROXY_END_DATE] DATE NOT NULL,
    [PROXY_LEVEL] VARCHAR(50),
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);

-- ==========================================
-- BOOKING MANAGEMENT TABLES
-- ==========================================

-- MEETTYPE_MAST - Meeting Type Master
IF OBJECT_ID('dbo.MEETTYPE_MAST', 'U') IS NULL
CREATE TABLE [MEETTYPE_MAST] (
    [MEETTYPE_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [MEETTYPE_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [MEETTYPE_NAME] VARCHAR(255) NOT NULL,
    [MEETTYPE_DESC] NVARCHAR(MAX),
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);

-- LOCATION_CONTACT - Location Contact Details
IF OBJECT_ID('dbo.LOCATION_CONTACT', 'U') IS NULL
CREATE TABLE [LOCATION_CONTACT] (
    [LOCATION_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [LOCATION_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [LOCATION_NAME] VARCHAR(255) NOT NULL,
    [LOCATION_ADDRESS] NVARCHAR(MAX),
    [CONTACT_PERSON] VARCHAR(255),
    [CONTACT_PHONE] VARCHAR(20),
    [CONTACT_EMAIL] VARCHAR(255),
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);

-- ROOM_MAST - Room Master
IF OBJECT_ID('dbo.ROOM_MAST', 'U') IS NULL
CREATE TABLE [ROOM_MAST] (
    [ROOM_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [ROOM_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [ROOM_NAME] VARCHAR(255) NOT NULL,
    [LOCATION_ID] BIGINT NOT NULL,
    [ROOM_CAPACITY] INT,
    [ROOM_DESC] NVARCHAR(MAX),
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT,
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION_CONTACT(LOCATION_ID)
);

-- ROOM_RESOURCE - Room Resources
IF OBJECT_ID('dbo.ROOM_RESOURCE', 'U') IS NULL
CREATE TABLE [ROOM_RESOURCE] (
    [RESOURCE_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [ROOM_ID] BIGINT NOT NULL,
    [RESOURCE_NAME] VARCHAR(255) NOT NULL,
    [RESOURCE_DESC] NVARCHAR(MAX),
    [RESOURCE_QUANTITY] INT,
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT,
    FOREIGN KEY (ROOM_ID) REFERENCES ROOM_MAST(ROOM_ID)
);

-- BOOK_MAIN - Booking Master/Application
IF OBJECT_ID('dbo.BOOK_MAIN', 'U') IS NULL
CREATE TABLE [BOOK_MAIN] (
    [BOOK_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [BOOK_APP_NO] VARCHAR(50) NOT NULL UNIQUE,
    [ROOM_ID] BIGINT NOT NULL,
    [BOOKING_DATE] DATE NOT NULL,
    [BOOKING_TIME_FROM] TIME NOT NULL,
    [BOOKING_TIME_TO] TIME NOT NULL,
    [MEETTYPE_ID] BIGINT,
    [BOOKED_BY] BIGINT NOT NULL,
    [BOOKING_PURPOSE] NVARCHAR(MAX),
    [BOOKING_STATUS] VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE, CANCELLED, COMPLETED
    [APPROVED_BY] BIGINT,
    [APPROVAL_REMARKS] NVARCHAR(MAX),
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT,
    FOREIGN KEY (ROOM_ID) REFERENCES ROOM_MAST(ROOM_ID),
    FOREIGN KEY (MEETTYPE_ID) REFERENCES MEETTYPE_MAST(MEETTYPE_ID)
);

-- BOOK_ATTENDEES - Booking Attendees
IF OBJECT_ID('dbo.BOOK_ATTENDEES', 'U') IS NULL
CREATE TABLE [BOOK_ATTENDEES] (
    [ATTENDEE_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [BOOK_ID] BIGINT NOT NULL,
    [ATTENDEE_SN] BIGINT NOT NULL,
    [ATTENDEE_EMP_ID] BIGINT NOT NULL,
    [ATTENDEE_NAME] VARCHAR(255),
    [ATTENDEE_EMAIL] VARCHAR(255),
    [ATTENDANCE_STATUS] VARCHAR(20) DEFAULT 'INVITED', -- INVITED, ACCEPTED, DECLINED, ATTENDED
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK_MAIN(BOOK_ID)
);

-- BOOK_REC - Booking Recommendations/Records
IF OBJECT_ID('dbo.BOOK_REC', 'U') IS NULL
CREATE TABLE [BOOK_REC] (
    [BOOKREC_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [BOOK_ID] BIGINT NOT NULL,
    [LOCATION_CODE] VARCHAR(50),
    [REMARK] NVARCHAR(MAX),
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK_MAIN(BOOK_ID)
);

-- ==========================================
-- SRF MEETING TABLES
-- ==========================================

-- SRF_MEETINGSCH - SRF Meeting Schedule
IF OBJECT_ID('dbo.SRF_MEETINGSCH', 'U') IS NULL
CREATE TABLE [SRF_MEETINGSCH] (
    [MEETING_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [MEETING_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [MEETING_DATE] DATE NOT NULL,
    [MEETING_TIME] TIME NOT NULL,
    [MEETING_LOCATION] VARCHAR(255),
    [MEETING_TOPIC] VARCHAR(255),
    [MEETING_DESC] NVARCHAR(MAX),
    [ORGANIZED_BY] BIGINT,
    [MEETING_STATUS] VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED', -- SCHEDULED, ONGOING, COMPLETED, CANCELLED
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);

-- SRF_POLL_DETAIL - SRF Poll Details
IF OBJECT_ID('dbo.SRF_POLL_DETAIL', 'U') IS NULL
CREATE TABLE [SRF_POLL_DETAIL] (
    [POLL_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [MEETING_ID] BIGINT NOT NULL,
    [POLL_QUESTION] VARCHAR(MAX) NOT NULL,
    [POLL_OPTION_A] VARCHAR(255),
    [POLL_OPTION_B] VARCHAR(255),
    [POLL_OPTION_C] VARCHAR(255),
    [POLL_OPTION_D] VARCHAR(255),
    [VOTES_A] INT DEFAULT 0,
    [VOTES_B] INT DEFAULT 0,
    [VOTES_C] INT DEFAULT 0,
    [VOTES_D] INT DEFAULT 0,
    [POLL_STATUS] VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE, CLOSED
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    FOREIGN KEY (MEETING_ID) REFERENCES SRF_MEETINGSCH(MEETING_ID)
);

-- ==========================================
-- STIPEND & FINANCE TABLES
-- ==========================================

-- SRF_STIPEND_MASTER - Stipend Master
IF OBJECT_ID('dbo.SRF_STIPEND_MASTER', 'U') IS NULL
CREATE TABLE [SRF_STIPEND_MASTER] (
    [STIPEND_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [RESEARCH_CATEGORY_ID] BIGINT NOT NULL,
    [SRF_RANK_ID] BIGINT NOT NULL,
    [SRF_MONTHLY_STIPEND] DECIMAL(19,2) NOT NULL,
    [EFFECTIVE_FROM] DATE NOT NULL,
    [EFFECTIVE_TO] DATE,
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);

-- SRF_STIPEND_DISBURSEMENT - Stipend Disbursement
IF OBJECT_ID('dbo.SRF_STIPEND_DISBURSEMENT', 'U') IS NULL
CREATE TABLE [SRF_STIPEND_DISBURSEMENT] (
    [DISBURSE_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [SRF_ID] BIGINT NOT NULL,
    [STIPEND_ID] BIGINT NOT NULL,
    [DISBURSEMENT_DATE] DATE NOT NULL,
    [DISBURSEMENT_AMOUNT] DECIMAL(19,2) NOT NULL,
    [DISBURSEMENT_STATUS] VARCHAR(20) NOT NULL DEFAULT 'D', -- D=Draft, P=Processed, A=Approved, R=Rejected
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT,
    FOREIGN KEY (STIPEND_ID) REFERENCES SRF_STIPEND_MASTER(STIPEND_ID)
);

-- REIM_TRAN - Reimbursement Transactions
IF OBJECT_ID('dbo.REIM_TRAN', 'U') IS NULL
CREATE TABLE [REIM_TRAN] (
    [REIM_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [USER_ID] BIGINT NOT NULL,
    [REIM_DATE] DATE NOT NULL,
    [REIM_AMOUNT] DECIMAL(19,2) NOT NULL,
    [REIM_DESC] NVARCHAR(MAX),
    [REIM_CATEGORY] VARCHAR(50),
    [REIM_STATUS] VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED, PAID
    [APPROVED_BY] BIGINT,
    [APPROVAL_DATE] DATE,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);

-- TSE_TIMESHEET - Timesheet Entries
IF OBJECT_ID('dbo.TSE_TIMESHEET', 'U') IS NULL
CREATE TABLE [TSE_TIMESHEET] (
    [TIMESHEET_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [EMP_ID] BIGINT NOT NULL,
    [RECORDED_DATE] DATE NOT NULL,
    [WORK_HOURS] DECIMAL(5,2),
    [WORK_DESC] NVARCHAR(MAX),
    [PROJECT_ID] BIGINT,
    [TASK_ID] BIGINT,
    [TIMESHEET_STATUS] VARCHAR(20) NOT NULL DEFAULT 'DRAFT', -- DRAFT, SUBMITTED, APPROVED
    [APPROVED_BY] BIGINT,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);

-- ==========================================
-- COMMUNITY TABLES
-- ==========================================

-- COMMUNITY_MAST - Community Master
IF OBJECT_ID('dbo.COMMUNITY_MAST', 'U') IS NULL
CREATE TABLE [COMMUNITY_MAST] (
    [COMMUNITY_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [COMMUNITY_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [COMMUNITY_NAME] VARCHAR(255) NOT NULL,
    [COMMUNITY_DESC] NVARCHAR(MAX),
    [COMMUNITY_ADMIN_ID] BIGINT,
    [COMMUNITY_EMAIL] VARCHAR(255),
    [COMMUNITY_PHONE] VARCHAR(20),
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);

-- COMP_GRADE - Compensation Grade
IF OBJECT_ID('dbo.COMP_GRADE', 'U') IS NULL
CREATE TABLE [COMP_GRADE] (
    [GRADE_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [GRADE_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [GRADE_NAME] VARCHAR(255) NOT NULL,
    [GRADE_DESC] NVARCHAR(MAX),
    [SALARY_RANGE_MIN] DECIMAL(19,2),
    [SALARY_RANGE_MAX] DECIMAL(19,2),
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);

-- ==========================================
-- WEBSITE CONTACT TABLES
-- ==========================================

-- WEBSITE_CON_MAILID - Website Contact Mail IDs
IF OBJECT_ID('dbo.WEBSITE_CON_MAILID', 'U') IS NULL
CREATE TABLE [WEBSITE_CON_MAILID] (
    [WEBMAIL_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [EMAIL_TYPE] VARCHAR(50) NOT NULL,
    [EMAIL_ADDRESS] VARCHAR(255) NOT NULL,
    [RECIPIENT_NAME] VARCHAR(255),
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    [UPDATED_BY] BIGINT
);

-- ==========================================
-- INDEXES
-- ==========================================
CREATE INDEX IDX_APPROVER_EMP_EMPID ON APPROVER_EMP(EMP_ID);
CREATE INDEX IDX_APPROVER_EMP_APPRID ON APPROVER_EMP(APPR_MAST_ID);
CREATE INDEX IDX_BOOK_MAIN_ROOMID ON BOOK_MAIN(ROOM_ID);
CREATE INDEX IDX_BOOK_MAIN_STATUS ON BOOK_MAIN(BOOKING_STATUS);
CREATE INDEX IDX_BOOK_ATTENDEES_BOOKID ON BOOK_ATTENDEES(BOOK_ID);
CREATE INDEX IDX_SRF_MEETINGSCH_DATE ON SRF_MEETINGSCH(MEETING_DATE);
CREATE INDEX IDX_SRF_POLL_MEETINGID ON SRF_POLL_DETAIL(MEETING_ID);
CREATE INDEX IDX_REIM_TRAN_USERID ON REIM_TRAN(USER_ID);
CREATE INDEX IDX_REIM_TRAN_STATUS ON REIM_TRAN(REIM_STATUS);
CREATE INDEX IDX_TSE_TIMESHEET_EMPID ON TSE_TIMESHEET(EMP_ID);
CREATE INDEX IDX_TSE_TIMESHEET_DATE ON TSE_TIMESHEET(RECORDED_DATE);

GO

PRINT 'SRFSPARSHDB Complete schema created successfully.';
GO
