IF NOT EXISTS (SELECT 1 FROM EMPLOYEE_MAIN WHERE EMP_SYSID = 1)
BEGIN
    INSERT INTO EMPLOYEE_MAIN
    (
        EMP_SYSID, EMP_PIN_NO, EMP_APP_DATE, EMP_APP_UNIT, EMP_APP_GRADE, EMP_APP_POSITION,
        EMP_APP_POSITIONDESC, EMP_FRS_NAME, EMP_GENDER, EMP_DOB_RECORD, EMP_OFFERSTATUS,
        EMP_LEAD_ROLE, EMP_PROBDATE, EMP_PROB_FLAG, EMP_APPUNITID, EMP_CREATEDBY, EMP_CREATEDON,
        EMP_UPDATED_BY, EMP_UPDATED_ON
    )
    VALUES
    (
        1, 100001, SYSUTCDATETIME(), 'HQ1', 101, 9001,
        'Management Trainee', 'Seed', 'M', '1995-01-01', 'A',
        'GEN', DATEADD(MONTH, 6, SYSUTCDATETIME()), 'Y', 1, 1, SYSUTCDATETIME(),
        1, SYSUTCDATETIME()
    );
END;

IF NOT EXISTS (SELECT 1 FROM EMP_GRADE WHERE GRADE_EMP_SYSID = 1)
BEGIN
    INSERT INTO EMP_GRADE
    (
        GRADE_EMP_SYSID, GRADE_TRANID, GRADE_ID, GRADE_EFF_DATE, GRADE_REMARKS,
        GRADE_LIVFLAG, GRADE_UPDATEDBY, GRADE_UPDATEDON, GRADE_PROBATION
    )
    VALUES
    (
        1, 1, 101, SYSUTCDATETIME(), 'Seed grade',
        'Y', 1, SYSUTCDATETIME(), 'Y'
    );
END;