<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.1.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.RabbitMQ" Version="1.2.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="5.1.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.13.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.19.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs" Version="6.2.0" />
    <PackageReference Include="MediatR" Version="12.1.1" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommunityService.Domain\CommunityService.Domain.csproj" />
    <ProjectReference Include="..\CommunityService.Application\CommunityService.Application.csproj" />
    <ProjectReference Include="..\CommunityService.Infrastructure\CommunityService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
