-- ==========================================
-- Database: EMPLOYEEDB
-- Module: Employee Management System
-- Generated Module Script
-- ==========================================

USE master;
GO

-- ==========================================
-- PHASE 1: Database Creation
-- ==========================================
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'EMPLOYEEDB')
BEGIN
    CREATE DATABASE [EMPLOYEEDB];
    PRINT '+ EMPLOYEEDB created';
END
ELSE
    PRINT '= EMPLOYEEDB already exists';
GO

ALTER DATABASE [EMPLOYEEDB] SET READ_COMMITTED_SNAPSHOT ON;
GO

PRINT '=== PHASE 1 COMPLETE: Database Created ===';
GO

-- ==========================================
-- PHASE 2: Table Definitions
-- ==========================================
USE EMPLOYEEDB;
GO

-- Table: EMP_TIMEINFO - Employee Time Information
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMP_TIMEINFO]') AND type = 'U')
BEGIN
CREATE TABLE [EMP_TIMEINFO] (
    [TIME_INFOID] BIGINT NOT NULL,
    [TIME_EMPSYSID] BIGINT NOT NULL,
    [TIME_EMPATTFLAG] CHAR(1) NOT NULL,
    [TIME_LASTMODIFIEDBY] BIGINT NOT NULL,
    [TIME_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_EMP_TIMEINFO] PRIMARY KEY ([TIME_INFOID])
);
    PRINT '+ EMP_TIMEINFO created';
END
ELSE
    PRINT '= EMP_TIMEINFO already exists';
GO

-- Table: EMP_TIMEINFO_LOG - Employee Time Info Log
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMP_TIMEINFO_LOG]') AND type = 'U')
BEGIN
CREATE TABLE [EMP_TIMEINFO_LOG] (
    [TIME_INFOID] BIGINT NOT NULL,
    [TIME_EMPSYSID] BIGINT NOT NULL,
    [TIME_EMPATTFLAG] CHAR(1) NOT NULL,
    [TIME_LASTMODIFIEDBY] BIGINT NOT NULL,
    [TIME_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    [LOG_CREATEDON] DECIMAL(38) NULL,
    [LOG_CREATEBY] DATETIME2(3) NULL
);
    PRINT '+ EMP_TIMEINFO_LOG created';
END
ELSE
    PRINT '= EMP_TIMEINFO_LOG already exists';
GO

-- Table: EMPLOYEE_APPROVER - Employee Approver Details
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPLOYEE_APPROVER]') AND type = 'U')
BEGIN
CREATE TABLE [EMPLOYEE_APPROVER] (
    [APPROVER_ID] INT NOT NULL,
    [APPROVER_EMPSYSID] VARCHAR(255) NOT NULL,
    [APPROVER_LEVEL] INT NOT NULL,
    [APPROVER_SYSID] BIGINT NOT NULL,
    [APPROVER_EFFDATE] DATETIME2(3) NOT NULL,
    [APPROVER_MODIFIEDBY] BIGINT NOT NULL,
    [APPROVER_MODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_EMPLOYEE_APPROVER] PRIMARY KEY ([APPROVER_ID])
);
    PRINT '+ EMPLOYEE_APPROVER created';
END
ELSE
    PRINT '= EMPLOYEE_APPROVER already exists';
GO

-- Table: EMPLOYEE_APPROVER_LOG - Employee Approver Log
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPLOYEE_APPROVER_LOG]') AND type = 'U')
BEGIN
CREATE TABLE [EMPLOYEE_APPROVER_LOG] (
    [APPROVER_ID] INT NOT NULL,
    [APPROVER_EMPSYSID] BIGINT NOT NULL,
    [APPROVER_LEVEL] INT NOT NULL,
    [APPROVER_SYSID] BIGINT NOT NULL,
    [APPROVER_EFFDATE] DATETIME2(3) NOT NULL,
    [APPROVER_MODIFIEDBY] BIGINT NOT NULL,
    [APPROVER_MODIFIEDON] DATETIME2(3) NOT NULL,
    [LOGCREATED_BY] BIGINT NULL,
    [LOGCREATED_ON] DATETIME2(3) NULL,
    [APPROVER_CLSDATE] DATETIME2(3) NULL
);
    PRINT '+ EMPLOYEE_APPROVER_LOG created';
END
ELSE
    PRINT '= EMPLOYEE_APPROVER_LOG already exists';
GO

-- Table: EMPLOYEE_APPROVALMAIL - Employee Approver Mail Mapping
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPLOYEE_APPROVALMAIL]') AND type = 'U')
BEGIN
CREATE TABLE [EMPLOYEE_APPROVALMAIL] (
    [APPMAIL_ID] INT NOT NULL,
    [APPMAIL_EMPSYSID] VARCHAR(255) NOT NULL,
    [APPMAIL_SYSID] BIGINT NOT NULL,
    [APPMAIL_EFFDATE] DATETIME2(3) NOT NULL,
    [APPMAIL_MODIFIEDBY] BIGINT NULL,
    [APPMAIL_MODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_EMPLOYEE_APPROVALMAIL] PRIMARY KEY ([APPMAIL_ID])
);
    PRINT '+ EMPLOYEE_APPROVALMAIL created';
END
ELSE
    PRINT '= EMPLOYEE_APPROVALMAIL already exists';
GO

-- Table: EMPLOYEE_APPROVALMAIL_LOG - Employee Approver Mail Log
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPLOYEE_APPROVALMAIL_LOG]') AND type = 'U')
BEGIN
CREATE TABLE [EMPLOYEE_APPROVALMAIL_LOG] (
    [APPMAIL_ID] BIGINT NOT NULL,
    [APPMAIL_EMPSYSID] BIGINT NOT NULL,
    [APPMAIL_SYSID] BIGINT NOT NULL,
    [APPMAIL_EFFDATE] DATETIME2(3) NOT NULL,
    [APPMAIL_MODIFIEDBY] BIGINT NULL,
    [APPMAIL_MODIFIEDON] DATETIME2(3) NULL,
    [LOG_REASON] VARCHAR(255) NULL,
    [LOG_CREATEDBY] BIGINT NULL,
    [LOG_CREATEDON] DATETIME2(3) NULL
);
    PRINT '+ EMPLOYEE_APPROVALMAIL_LOG created';
END
ELSE
    PRINT '= EMPLOYEE_APPROVALMAIL_LOG already exists';
GO

-- Table: EMP_CALENDAR - Employee Calendar Mapping
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMP_CALENDAR]') AND type = 'U')
BEGIN
CREATE TABLE [EMP_CALENDAR] (
    [EMPCAL_ID] BIGINT NOT NULL,
    [EMPCAL_EMPSYSID] BIGINT NOT NULL,
    [EMPCAL_CALENDARID] INT NOT NULL,
    [EMPCAL_SWIPEID] BIGINT NULL,
    [EMPCAL_EFFDATE] DATETIME2(3) NOT NULL,
    [EMPCAL_CLSDATE] DATETIME2(3) NULL,
    [EMPCAL_LASTMODIFIEDBY] BIGINT NOT NULL,
    [EMPCAL_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    [EMPCAL_STATUS] CHAR(1) NULL,
    [EMPCAL_TRANSFER] INT NULL,
    [EMPCAL_SETTLEMENTNO] BIGINT NULL,
    CONSTRAINT [PK_EMP_CALENDAR] PRIMARY KEY ([EMPCAL_ID])
);
    PRINT '+ EMP_CALENDAR created';
END
ELSE
    PRINT '= EMP_CALENDAR already exists';
GO

-- Table: EMP_CALENDAR_LOG - Employee Calendar Log
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMP_CALENDAR_LOG]') AND type = 'U')
BEGIN
CREATE TABLE [EMP_CALENDAR_LOG] (
    [EMPCAL_ID] BIGINT NOT NULL,
    [EMPCAL_EMPSYSID] BIGINT NOT NULL,
    [EMPCAL_CALENDARID] INT NOT NULL,
    [EMPCAL_EFFDATE] DATETIME2(3) NOT NULL,
    [EMPCAL_CLSDATE] DATETIME2(3) NULL,
    [EMPCAL_LASTMODIFIEDBY] BIGINT NOT NULL,
    [EMPCAL_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    [LOG_CREATEDON] DECIMAL(38) NULL,
    [LOG_CREATEBY] DATETIME2(3) NULL
);
    PRINT '+ EMP_CALENDAR_LOG created';
END
ELSE
    PRINT '= EMP_CALENDAR_LOG already exists';
GO

-- Table: EMPLOYEE_PATTERN - Employee Pattern Assignment
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPLOYEE_PATTERN]') AND type = 'U')
BEGIN
CREATE TABLE [EMPLOYEE_PATTERN] (
    [EMPPATTERN_ID] BIGINT NOT NULL,
    [EMPPATTERN_EMPSYSID] BIGINT NOT NULL,
    [EMPPATTERN_MASTID] INT NOT NULL,
    [EMPPATTERN_EFFDATE] DATETIME2(3) NOT NULL,
    [EMPPATTERN_CLSDATE] DATETIME2(3) NULL,
    [EMPPATTERN_WEEKLYOFFDY] INT NOT NULL,
    [EMPPATTERN_SUBWEEKLYDY] INT NULL,
    [EMPPATTERN_SUBFRQ] VARCHAR(5) NULL,
    [EMPPATTERN_LASTMODIFIEDBY] BIGINT NULL,
    [EMPPATTERN_LASTMODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_EMPLOYEE_PATTERN] PRIMARY KEY ([EMPPATTERN_ID])
);
    PRINT '+ EMPLOYEE_PATTERN created';
END
ELSE
    PRINT '= EMPLOYEE_PATTERN already exists';
GO

-- Table: EMPLOYEE_PATTERNLOG - Employee Pattern Log
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPLOYEE_PATTERNLOG]') AND type = 'U')
BEGIN
CREATE TABLE [EMPLOYEE_PATTERNLOG] (
    [EMPPATTERN_ID] BIGINT NOT NULL,
    [EMPPATTERN_EMPSYSID] BIGINT NOT NULL,
    [EMPPATTERN_MASTID] INT NOT NULL,
    [EMPPATTERN_EFFDATE] DATETIME2(3) NOT NULL,
    [EMPPATTERN_CLSDATE] DATETIME2(3) NULL,
    [EMPPATTERN_WEEKLYOFFDY] INT NOT NULL,
    [EMPPATTERN_SUBWEEKLYDY] INT NULL,
    [EMPPATTERN_SUBFRQ] VARCHAR(255) NULL,
    [EMPPATTERN_LASTMODIFIEDBY] BIGINT NULL,
    [EMPPATTERN_LASTMODIFIEDON] DATETIME2(3) NULL,
    [LOG_CREATEDBY] BIGINT NULL,
    [LOG_CREATEDON] DATETIME2(3) NULL
);
    PRINT '+ EMPLOYEE_PATTERNLOG created';
END
ELSE
    PRINT '= EMPLOYEE_PATTERNLOG already exists';
GO

-- Table: EMPLOYEE_SHIFT - Employee Shift Schedule
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPLOYEE_SHIFT]') AND type = 'U')
BEGIN
CREATE TABLE [EMPLOYEE_SHIFT] (
    [EMPSHIFT_ID] BIGINT NOT NULL,
    [EMPSHIFT_EMPSYSID] BIGINT NOT NULL,
    [EMPSHIFT_TIMEUNITID] INT NOT NULL,
    [EMPSHIFT_CODE] CHAR(1) NOT NULL,
    [EMPSHIFT_YEARMONTH] INT NOT NULL,
    [EMPSHIFT_DAY] INT NOT NULL,
    [EMPSHIFT_DATE] DATETIME2(3) NOT NULL,
    [EMPSHIFT_UPDATEDBY] BIGINT NOT NULL,
    [EMPSHIFT_UPDATEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_EMPLOYEE_SHIFT] PRIMARY KEY ([EMPSHIFT_ID])
);
    PRINT '+ EMPLOYEE_SHIFT created';
END
ELSE
    PRINT '= EMPLOYEE_SHIFT already exists';
GO

-- Table: EMPLOYEE_SHIFTLOG - Employee Shift Log
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPLOYEE_SHIFTLOG]') AND type = 'U')
BEGIN
CREATE TABLE [EMPLOYEE_SHIFTLOG] (
    [EMPSHIFT_ID] INT NOT NULL,
    [EMPSHIFT_EMPSYSID] BIGINT NOT NULL,
    [EMPSHIFT_TIMEUNITID] INT NOT NULL,
    [EMPSHIFT_CODE] CHAR(1) NOT NULL,
    [EMPSHIFT_YEARMONTH] INT NOT NULL,
    [EMPSHIFT_DAY] INT NOT NULL,
    [EMPSHIFT_DATE] DATETIME2(3) NOT NULL,
    [EMPSHIFT_UPDATEDBY] BIGINT NOT NULL,
    [EMPSHIFT_UPDATEDON] DATETIME2(3) NOT NULL,
    [LOG_CREATED_ON] DATETIME2(3) NOT NULL,
    [LOG_CREATED_BY] DECIMAL(38) NOT NULL
);
    PRINT '+ EMPLOYEE_SHIFTLOG created';
END
ELSE
    PRINT '= EMPLOYEE_SHIFTLOG already exists';
GO

-- Table: EMPLOYEE_SHIFTPATTERN - Employee Shift Pattern
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPLOYEE_SHIFTPATTERN]') AND type = 'U')
BEGIN
CREATE TABLE [EMPLOYEE_SHIFTPATTERN] (
    [EMPSHIFT_ID] BIGINT NOT NULL,
    [EMPSHIFT_TIMEUNITID] BIGINT NULL,
    [EMPSHIFT_EMPSYSID] BIGINT NULL,
    [EMPSHIFT_YEARMONTH] INT NULL,
    [EMPSHIFT_ORGPATTERN] VARCHAR(31) NULL,
    [EMPSHIFT_NEWPATTERN] VARCHAR(31) NULL,
    [EMPSHIFT_LASTMODIFIEDBY] BIGINT NOT NULL,
    [EMPSHIFT_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_EMPLOYEE_SHIFTPATTERN] PRIMARY KEY ([EMPSHIFT_ID])
);
    PRINT '+ EMPLOYEE_SHIFTPATTERN created';
END
ELSE
    PRINT '= EMPLOYEE_SHIFTPATTERN already exists';
GO

-- Table: EMPLOYEE_SHIFTPATTERN_LOG - Employee Shift Pattern Log
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPLOYEE_SHIFTPATTERN_LOG]') AND type = 'U')
BEGIN
CREATE TABLE [EMPLOYEE_SHIFTPATTERN_LOG] (
    [EMPSHIFT_ID] BIGINT NULL,
    [EMPSHIFT_EMPSYSID] BIGINT NULL,
    [EMPSHIFT_TIMEUNITID] INT NULL,
    [EMPSHIFT_YEARMONTH] INT NULL,
    [EMPSHIFT_ORGPATTERN] VARCHAR(255) NULL,
    [EMPSHIFT_NEWPATTERN] VARCHAR(255) NULL,
    [EMPSHIFT_LASTMODIFIEDBY] DECIMAL(38) NULL,
    [EMPSHIFT_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    [LOG_CREATED_ON] DATETIME2(3) NOT NULL,
    [LOG_CREATED_BY] DECIMAL(38) NOT NULL
);
    PRINT '+ EMPLOYEE_SHIFTPATTERN_LOG created';
END
ELSE
    PRINT '= EMPLOYEE_SHIFTPATTERN_LOG already exists';
GO

-- Create Indexes (idempotent)
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_EMP_TIMEINFO_EMPSYSID' AND object_id = OBJECT_ID('EMP_TIMEINFO'))
    CREATE INDEX [IX_EMP_TIMEINFO_EMPSYSID] ON [EMP_TIMEINFO] ([TIME_EMPSYSID]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_EMPLOYEE_APPROVER_EMPSYSID' AND object_id = OBJECT_ID('EMPLOYEE_APPROVER'))
    CREATE INDEX [IX_EMPLOYEE_APPROVER_EMPSYSID] ON [EMPLOYEE_APPROVER] ([APPROVER_EMPSYSID]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_EMP_CALENDAR_EMPSYSID' AND object_id = OBJECT_ID('EMP_CALENDAR'))
    CREATE INDEX [IX_EMP_CALENDAR_EMPSYSID] ON [EMP_CALENDAR] ([EMPCAL_EMPSYSID]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_EMPLOYEE_PATTERN_EMPSYSID' AND object_id = OBJECT_ID('EMPLOYEE_PATTERN'))
    CREATE INDEX [IX_EMPLOYEE_PATTERN_EMPSYSID] ON [EMPLOYEE_PATTERN] ([EMPPATTERN_EMPSYSID]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_EMPLOYEE_SHIFT_EMPSYSID' AND object_id = OBJECT_ID('EMPLOYEE_SHIFT'))
    CREATE INDEX [IX_EMPLOYEE_SHIFT_EMPSYSID] ON [EMPLOYEE_SHIFT] ([EMPSHIFT_EMPSYSID]);
GO

PRINT '=== PHASE 2 COMPLETE: Tables Created ===';
GO

-- ==========================================
-- PHASE 3: Stored Procedures
-- ==========================================

-- Procedure: usp_AssignApprover
CREATE OR ALTER PROCEDURE dbo.usp_AssignApprover
(
    @p_EmpSysID BIGINT,
    @p_ApproverSysID BIGINT,
    @p_Level INT,
    @p_AssignedBy BIGINT,
    @p_ApproverID INT OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;
        
        SELECT @p_ApproverID = ISNULL(MAX(APPROVER_ID), 0) + 1 FROM EMPLOYEE_APPROVER;
        
        INSERT INTO EMPLOYEE_APPROVER
        (APPROVER_ID, APPROVER_EMPSYSID, APPROVER_LEVEL, APPROVER_SYSID, APPROVER_EFFDATE, APPROVER_MODIFIEDBY, APPROVER_MODIFIEDON)
        VALUES (@p_ApproverID, CAST(@p_EmpSysID AS VARCHAR(255)), @p_Level, @p_ApproverSysID, GETDATE(), @p_AssignedBy, GETDATE());
        
        COMMIT TRANSACTION;
        PRINT 'Approver assigned: ID = ' + CAST(@p_ApproverID AS VARCHAR);
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        RAISERROR('Approver assignment failed: %s', 16, 1, ERROR_MESSAGE());
    END CATCH
END;
GO

-- Procedure: usp_MapEmployeeCalendar
CREATE OR ALTER PROCEDURE dbo.usp_MapEmployeeCalendar
(
    @p_EmpSysID BIGINT,
    @p_CalendarID INT,
    @p_MappedBy BIGINT,
    @p_CalendarMapID BIGINT OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;
        
        SELECT @p_CalendarMapID = ISNULL(MAX(EMPCAL_ID), 0) + 1 FROM EMP_CALENDAR;
        
        INSERT INTO EMP_CALENDAR
        (EMPCAL_ID, EMPCAL_EMPSYSID, EMPCAL_CALENDARID, EMPCAL_EFFDATE, EMPCAL_LASTMODIFIEDBY, EMPCAL_LASTMODIFIEDON)
        VALUES (@p_CalendarMapID, @p_EmpSysID, @p_CalendarID, GETDATE(), @p_MappedBy, GETDATE());
        
        COMMIT TRANSACTION;
        PRINT 'Employee calendar mapped: ID = ' + CAST(@p_CalendarMapID AS VARCHAR);
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        RAISERROR('Calendar mapping failed: %s', 16, 1, ERROR_MESSAGE());
    END CATCH
END;
GO

PRINT '=== PHASE 3 COMPLETE: Procedures Created ===';
GO

-- ==========================================
-- PHASE 4: Verification Views
-- ==========================================
IF EXISTS (SELECT 1 FROM sys.views WHERE name = 'vw_EmployeeDB_Status')
    DROP VIEW vw_EmployeeDB_Status;
GO

CREATE VIEW vw_EmployeeDB_Status AS
SELECT 
    'EMPLOYEEDB' AS DatabaseName,
    'Employee Management Module' AS ModuleDescription,
    (SELECT COUNT(*) FROM EMP_TIMEINFO) AS EmployeeTimeInfo,
    (SELECT COUNT(*) FROM EMPLOYEE_APPROVER) AS ApproverMappings,
    (SELECT COUNT(*) FROM EMP_CALENDAR) AS CalendarMappings,
    (SELECT COUNT(*) FROM EMPLOYEE_PATTERN) AS PatternAssignments,
    GETDATE() AS LastChecked;
GO

PRINT '=== PHASE 4 COMPLETE: Views Created ===';
GO

-- ==========================================
-- PHASE 5: Final Verification
-- ==========================================
PRINT '=== PHASE 5: FINAL VERIFICATION ===';
SELECT 'System Tables' AS Object_Type, COUNT(*) AS Count FROM sys.tables;
SELECT 'Indexes' AS Object_Type, COUNT(*) AS Count FROM sys.indexes WHERE object_id > 0;
SELECT 'Procedures' AS Object_Type, COUNT(*) AS Count FROM sys.objects WHERE type = 'P';
SELECT 'Views' AS Object_Type, COUNT(*) AS Count FROM sys.views;

PRINT '======================================';
PRINT 'EMPLOYEEDB DEPLOYMENT COMPLETE';
PRINT '======================================';
PRINT 'Database: EMPLOYEEDB';
PRINT 'Tables: 12';
PRINT 'Indexes: 5';
PRINT 'Procedures: 2';
PRINT 'Views: 1';
PRINT 'Status: READY FOR DEPLOYMENT';
PRINT '======================================';
GO
