#!/bin/bash
# SSC Database Initialization Script
# Waits for SQL Server to be ready, then creates databases and schema

set -e

SQLCMD="/opt/mssql-tools18/bin/sqlcmd"
SERVER="localhost"
USER="sa"
PASSWORD="${MSSQL_SA_PASSWORD:-SSCAdmin@2026!}"

echo "Waiting for SQL Server to start..."
for i in {1..60}; do
    if $SQLCMD -S $SERVER -U $USER -P "$PASSWORD" -C -Q "SELECT 1" &>/dev/null; then
        echo "SQL Server is ready."
        break
    fi
    echo "  Attempt $i/60 - SQL Server not ready yet..."
    sleep 2
done

echo "============================================"
echo "Creating databases..."
echo "============================================"

$SQLCMD -S $SERVER -U $USER -P "$PASSWORD" -C -Q "
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'SSCDB')
    CREATE DATABASE SSCDB;
GO
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'SSCDB_CategoryVendor')
    CREATE DATABASE SSCDB_CategoryVendor;
GO
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'SSCDB_InvoiceProcessing')
    CREATE DATABASE SSCDB_InvoiceProcessing;
GO
"

echo "Databases created successfully."

echo "============================================"
echo "Creating SSCDB schema..."
echo "============================================"

$SQLCMD -S $SERVER -U $USER -P "$PASSWORD" -C -d SSCDB -Q "
-- ── User & Menu Tables ─────────────────────────────────────────────

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'USER_MAST')
CREATE TABLE [USER_MAST] (
    [USER_ID] BIGINT NOT NULL,
    [USER_HREMPSYSID] BIGINT NULL,
    [USER_NAME] VARCHAR(100) NOT NULL,
    [USER_PASSWORD] VARCHAR(50) NOT NULL,
    [USER_SPARSHUSERID] VARCHAR(50) NULL,
    [USER_EMAILID] VARCHAR(50) NULL,
    [USER_EFFECTIVE DATE] DATETIME2(3) NOT NULL,
    [USER_CLOSURE DATE] DATETIME2(3) NOT NULL,
    [USER_ENTEREDBY] BIGINT NOT NULL,
    CONSTRAINT [PK_USER_MAST] PRIMARY KEY ([USER_ID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'USER_ROLEMAP')
CREATE TABLE [USER_ROLEMAP] (
    [ROLE_MAPID] BIGINT NOT NULL,
    [ROLE_USERID] BIGINT NOT NULL,
    [ROLE_ID] BIGINT NOT NULL,
    [ROLE_DEFFLAG] VARCHAR(255) NOT NULL,
    [ROLE_CREATEDBY] DATETIME2(3) NOT NULL,
    [ROLE_CREATEDON] BIGINT NOT NULL,
    CONSTRAINT [PK_USER_ROLEMAP] PRIMARY KEY ([ROLE_MAPID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'USER_ORGMAP')
CREATE TABLE [USER_ORGMAP] (
    [ORG_MAPID] BIGINT NOT NULL,
    [ORG_USERID] BIGINT NOT NULL,
    [ORG_BUID] VARCHAR(25) NOT NULL,
    [ORG_CREATEDBY] BIGINT NOT NULL,
    [ORG_CREATEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_USER_ORGMAP] PRIMARY KEY ([ORG_MAPID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'USER_LOCATIONMAP')
CREATE TABLE [USER_LOCATIONMAP] (
    [LOC_MAPID] BIGINT NOT NULL,
    [LOC_USERID] BIGINT NOT NULL,
    [LOC_ID] INT NOT NULL,
    [LOC_CREATEDON] DATETIME2(3) NOT NULL,
    [LOC_CREATEDBY] BIGINT NOT NULL,
    CONSTRAINT [PK_USER_LOCATIONMAP] PRIMARY KEY ([LOC_MAPID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'MENU_MASTER')
CREATE TABLE [MENU_MASTER] (
    [MENU_ID] BIGINT NOT NULL,
    [MENU_NAME] VARCHAR(100) NOT NULL,
    [MENU_PAGENAME] VARCHAR(200) NOT NULL,
    [MENU_PARENTID] BIGINT NOT NULL,
    [MENU_DISPLAYORDER] INT NOT NULL,
    [MENU_MODIFIEDBY] BIGINT NOT NULL,
    [MENU_MODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_MENU_MASTER] PRIMARY KEY ([MENU_ID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ROLE_MENUACCESS')
CREATE TABLE [ROLE_MENUACCESS] (
    [MENU_ACCESSID] BIGINT NOT NULL,
    [MENU_ID] INT NOT NULL,
    [MENU_ROLEID] BIGINT NOT NULL,
    [ROLE_MODIFIEDBY] BIGINT NULL,
    [ROLE_MODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_ROLE_MENUACCESS] PRIMARY KEY ([MENU_ACCESSID])
);

-- ── Oracle Integration Tables ──────────────────────────────────────

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ORA_POMAST')
CREATE TABLE [ORA_POMAST] (
    [PO_SEQID] BIGINT NOT NULL,
    [PO_OUID] BIGINT NOT NULL,
    [PO_ID] BIGINT NOT NULL,
    [PO_NO] VARCHAR(25) NOT NULL,
    [PO_VENDORSITEID] BIGINT NOT NULL,
    [PO_DUEDAYS] BIGINT NOT NULL,
    [PO_DUE_DAY_MONTHOFF] BIGINT NOT NULL,
    [PO_MONTHFORWARD] BIGINT NOT NULL,
    CONSTRAINT [PK_ORA_POMAST] PRIMARY KEY ([PO_SEQID]),
    CONSTRAINT [UK_ORA_POMAST_PO_ID] UNIQUE ([PO_ID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ORA_VENDORMAST')
CREATE TABLE [ORA_VENDORMAST] (
    [VENDOR_ID] INT NOT NULL,
    [VENDOR_NAME] VARCHAR(200) NOT NULL,
    [VENDOR_CODE] VARCHAR(200) NOT NULL,
    CONSTRAINT [PK_ORA_VENDORMAST] PRIMARY KEY ([VENDOR_ID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ORA_VENDORSITEMAST')
CREATE TABLE [ORA_VENDORSITEMAST] (
    [VENDOR_SITEID] BIGINT NOT NULL,
    [VENDOR_ID] BIGINT NOT NULL,
    [VENDOR_SITECODE] VARCHAR(200) NOT NULL,
    [VENDOR_OUID] VARCHAR(25) NOT NULL,
    CONSTRAINT [PK_ORA_VENDORSITEMAST] PRIMARY KEY ([VENDOR_SITEID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ORA_VENDORSITEBUMAP')
CREATE TABLE [ORA_VENDORSITEBUMAP] (
    [VENDOR_SITEID] BIGINT NOT NULL,
    [VENDOR_BUID] BIGINT NOT NULL,
    CONSTRAINT [PK_ORA_VENDORSITEBUMAP] PRIMARY KEY ([VENDOR_SITEID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ORA_OUMAST')
CREATE TABLE [ORA_OUMAST] (
    [OU_ID] VARCHAR(25) NOT NULL,
    [OU_NAME] VARCHAR(250) NOT NULL,
    [OU_BUID] VARCHAR(25) NOT NULL,
    CONSTRAINT [PK_ORA_OUMAST] PRIMARY KEY ([OU_ID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ORA_MRCMAST')
CREATE TABLE [ORA_MRCMAST] (
    [MRC_SEQID] BIGINT NOT NULL,
    [MRC_POID] BIGINT NOT NULL,
    [MRC_NO] VARCHAR(25) NOT NULL,
    [MRC_SEQNO] BIGINT NULL,
    [MRC_RECDATE] DATETIME2(3) NULL,
    [MRC_VENDID] BIGINT NULL,
    [MRC_VENSITEID] BIGINT NULL,
    CONSTRAINT [PK_ORA_MRCMAST] PRIMARY KEY ([MRC_SEQID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ORA_OU_BUMAP')
CREATE TABLE [ORA_OU_BUMAP] (
    [OU_ID] BIGINT NOT NULL,
    [OU_BUID] VARCHAR(25) NOT NULL
);

-- ── Category & LOV Tables ──────────────────────────────────────────

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'MAINCAT_MAST')
CREATE TABLE [MAINCAT_MAST] (
    [MAINCAT_ID] BIGINT NOT NULL,
    [MAINCAT_NAME] VARCHAR(200) NOT NULL,
    [MAINCAT_PRIORITY] BIGINT NOT NULL,
    [MAINCAT_MODIFIEDBY] BIGINT NOT NULL,
    [MAINCAT_MODIFIEDON] DATETIME2(3) NOT NULL,
    [MAINCAT_DEFSUBCATID] BIGINT NULL,
    [MAINCAT_AVGRESTIME] BIGINT NULL,
    CONSTRAINT [PK_MAINCAT_MAST] PRIMARY KEY ([MAINCAT_ID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SUBCAT_MAST')
CREATE TABLE [SUBCAT_MAST] (
    [SUBCAT_ID] BIGINT NOT NULL,
    [SUBCAT_MAINID] BIGINT NOT NULL,
    [SUBCAT_NAME] VARCHAR(200) NOT NULL,
    [SUBCAT_MODIFIEDBY] BIGINT NOT NULL,
    [SUBCAT_MODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_SUBCAT_MAST] PRIMARY KEY ([SUBCAT_ID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LOV_MAST')
CREATE TABLE [LOV_MAST] (
    [LOV_ID] BIGINT NOT NULL,
    [LOV_TYPE] VARCHAR(10) NOT NULL,
    [LOV_NAME] VARCHAR(200) NOT NULL,
    CONSTRAINT [PK_LOV_MAST] PRIMARY KEY ([LOV_ID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LOV_TYPEMAST')
CREATE TABLE [LOV_TYPEMAST] (
    [LOV_TYPECODE] VARCHAR(10) NOT NULL,
    [LOV_TYPENAME] VARCHAR(50) NOT NULL,
    CONSTRAINT [PK_LOV_TYPEMAST] PRIMARY KEY ([LOV_TYPECODE])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'HOLDTYPE_MAST')
CREATE TABLE [HOLDTYPE_MAST] (
    [HOLD_ID] BIGINT NULL,
    [HOLD_NAME] VARCHAR(100) NULL,
    [HOLD_CATEGORY] CHAR(1) NULL,
    CONSTRAINT [PK_HOLDTYPE_MAST] PRIMARY KEY ([HOLD_ID])
);

-- ── Document Tables ────────────────────────────────────────────────

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DOC_DET')
CREATE TABLE [DOC_DET] (
    [DOC_ID] BIGINT NOT NULL,
    [DOC_ORGID] VARCHAR(25) NOT NULL,
    [DOC_LOCID] INT NOT NULL,
    [DOC_NO] VARCHAR(25) NULL,
    [DOC_TYPE] CHAR(3) NOT NULL,
    [DOC_MAINCAT] BIGINT NOT NULL,
    [DOC_SUBCAT] BIGINT NOT NULL,
    [DOC_PONO] VARCHAR(25) NOT NULL,
    [DOC_VNDSITEID] BIGINT NOT NULL,
    [DOC_VNDID] BIGINT NOT NULL,
    [DOC_DUEDAYS] INT NOT NULL,
    [DOC_POID] BIGINT NOT NULL,
    [DOC_MRCREM] VARCHAR(200) NULL,
    [DOC_VATFLAG] CHAR(1) NOT NULL,
    [DOC_INVOICENO] VARCHAR(100) NOT NULL,
    [DOC_INVAMT] BIGINT NOT NULL,
    [DOC_CURRENCY] INT NOT NULL,
    [DOC_INVDATE] DATETIME2(3) NOT NULL,
    [DOC_INVRECDATE] DATETIME2(3) NOT NULL,
    [DOC_PAGES] BIGINT NOT NULL,
    [DOC_REMARKS] VARCHAR(1000) NULL,
    [DOC_DUEDATE] DATETIME2(3) NOT NULL,
    [DOC_PAYBY] INT NOT NULL,
    [DOC_SIGNATORY1] BIGINT NULL,
    [DOC_SIGNATORY2] BIGINT NULL,
    [DOC_APPROVER] BIGINT NULL,
    [DOC_OWNER] BIGINT NOT NULL,
    [DOC_DOCSTATUS] CHAR(2) NOT NULL,
    [DOC_INVSTATUS] CHAR(2) NULL,
    [DOC_USERID] BIGINT NOT NULL,
    [DOC_CREATEDON] DATETIME2(3) NOT NULL,
    [DOC_SUBMITTEDON] DATETIME2(3) NOT NULL,
    [DOC_RECEIVEDBY] BIGINT NOT NULL,
    [DOC_RECEIVEDON] DATETIME2(3) NOT NULL,
    [DOC_CANCELFLAG] CHAR(1) NOT NULL,
    [DOC_CANCELUSER] BIGINT NOT NULL,
    [DOC_CANCELDATE] DATETIME2(3) NOT NULL,
    [DOC_APALLID] BIGINT NOT NULL,
    [DOC_ORAINVNO] BIGINT NOT NULL,
    [DOC_PAYTYPENO] BIGINT NOT NULL,
    [DOC_ACCOUNTCODE] VARCHAR(25) NOT NULL,
    [DOC_SSCINVOICEPDF] VARCHAR(200) NULL,
    [DOC_KEY] VARCHAR(25) NULL,
    [DOC_USRINVOICEPDF] VARCHAR(200) NULL,
    [DOC_FILEPATH] VARCHAR(200) NULL,
    [DOC_INVPROCDATE] DATETIME2(3) NULL,
    [DOC_INVPROCALLID] BIGINT NULL,
    [DOC_INVVALIDDATE] DATETIME2(3) NULL,
    [DOC_INVVALIDALLID] BIGINT NULL,
    [DOC_HOLDSTATUS] CHAR(1) NULL,
    [DOC_DEDUCTION] BIGINT NULL,
    [DOC_THIRDPARTYFLAG] CHAR(1) NULL,
    [DOC_THIRDPARTYVENDOR] VARCHAR(50) NULL,
    [DOC_DEDUCTIONREMARKS] VARCHAR(1000) NULL,
    [DOC_FILEID] BIGINT NULL,
    [DOC_CANCELREMARKS] VARCHAR(200) NULL,
    [DOC_HOLDPAYMENTFLAG] CHAR(1) NULL,
    [DOC_HOLDPAYMENTREMARKS] VARCHAR(200) NULL,
    [DOC_HOLDRELEASEREMARKS] VARCHAR(200) NULL,
    [DOC_SCANFLAG] CHAR(1) NULL,
    [DOC_APPROVEDBY] BIGINT NULL,
    CONSTRAINT [PK_DOC_DET] PRIMARY KEY ([DOC_ID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DOC_STATUS')
CREATE TABLE [DOC_STATUS] (
    [DOC_FLAG] CHAR(2) NOT NULL,
    [DOC_TYPE] CHAR(1) NOT NULL,
    [DOC_COMPLETEDREM] VARCHAR(100) NOT NULL,
    [DOC_PENDINGREM] VARCHAR(100) NOT NULL,
    [DOC_STAGEORDER] BIGINT NULL,
    [DOC_CATGROUP] VARCHAR(50) NULL,
    [DOC_STAGENO] BIGINT NULL,
    CONSTRAINT [PK_DOC_STATUS] PRIMARY KEY ([DOC_FLAG])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DOC_COUNTER')
CREATE TABLE [DOC_COUNTER] (
    [DOC_BUID] VARCHAR(25) NOT NULL,
    [DOC_NO] BIGINT NOT NULL,
    CONSTRAINT [PK_DOC_COUNTER] PRIMARY KEY ([DOC_BUID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DOC_ATTACHMENT')
CREATE TABLE [DOC_ATTACHMENT] (
    [ATTACH_ID] BIGINT NOT NULL,
    [ATTACH_DOCID] BIGINT NOT NULL,
    [ATTACH_FILEPATH] VARCHAR(25) NOT NULL,
    CONSTRAINT [PK_DOC_ATTACHMENT] PRIMARY KEY ([ATTACH_ID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DOC_POLIST')
CREATE TABLE [DOC_POLIST] (
    [PO_SEQID] BIGINT NOT NULL,
    [PO_DOCID] BIGINT NOT NULL,
    [PO_ID] BIGINT NOT NULL,
    [PO_NO] VARCHAR(15) NOT NULL,
    [PO_LINENO] VARCHAR(15) NOT NULL,
    [PO_LINE_ID] BIGINT NULL,
    [PO_DATE] DATETIME2(3) NULL,
    [PO_TERM_ID] BIGINT NULL,
    [PO_TERM_SEQNO] BIGINT NULL,
    CONSTRAINT [PK_DOC_POLIST] PRIMARY KEY ([PO_SEQID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DOC_APPDET')
CREATE TABLE [DOC_APPDET] (
    [APP_SEQID] BIGINT NOT NULL,
    [APP_DOCID] BIGINT NOT NULL,
    [APP_USERID] BIGINT NOT NULL,
    [APP_STATUS] CHAR(1) NOT NULL,
    [APP_REMARKS] VARCHAR(200) NULL,
    [APP_DATE] DATETIME2(3) NOT NULL
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DOC_MRCLIST')
CREATE TABLE [DOC_MRCLIST] (
    [MRC_SEQID] BIGINT NOT NULL,
    [MRC_DOCID] BIGINT NOT NULL,
    [MRC_LINEID] BIGINT NOT NULL,
    [MRC_ID] BIGINT NOT NULL,
    [MRC_NO] VARCHAR(15) NOT NULL,
    [MRC_DATE] DATETIME2(3) NULL,
    [MRC_PO_LINEID] BIGINT NULL,
    CONSTRAINT [PK_DOC_MRCLIST] PRIMARY KEY ([MRC_SEQID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DOC_CC')
CREATE TABLE [DOC_CC] (
    [CC_ID] BIGINT NOT NULL,
    [CC_DOCID] BIGINT NOT NULL,
    [CC_BUID] VARCHAR(25) NOT NULL,
    [CC_LOCCODE] VARCHAR(25) NOT NULL,
    [CC_ACCOUNTCODE] VARCHAR(25) NOT NULL,
    [CC_SUBACC] VARCHAR(25) NOT NULL,
    [CC_CODE] VARCHAR(25) NOT NULL,
    [CC_PRODUCT] VARCHAR(25) NOT NULL,
    [CC_PER] BIGINT NOT NULL,
    CONSTRAINT [PK_DOC_CC] PRIMARY KEY ([CC_ID])
);

-- ── Batch & Envelope Tables ────────────────────────────────────────

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BATCH_MAIN')
CREATE TABLE [BATCH_MAIN] (
    [BATCH_ID] BIGINT NOT NULL,
    [BATCH_CREATEDBY] BIGINT NOT NULL,
    [BATCH_CREATEDON] DATETIME2(3) NOT NULL,
    [BATCH_LOCATIONID] BIGINT NOT NULL,
    [BATCH_RECEIVEDBY] BIGINT NOT NULL,
    [BATCH_RECEIVEDON] DATETIME2(3) NOT NULL,
    [BATCH_PODNO] VARCHAR(25) NOT NULL,
    [BATCH_SUMMARYFLAG] CHAR(1) NOT NULL,
    [BATCH_CANCELBY] BIGINT NULL,
    [BATCH_CANCELDATE] DATETIME2(3) NULL,
    [BATCH_CONFIRMEDBY] BIGINT NULL,
    [BATCH_CONFIRMEDON] DATETIME2(3) NULL,
    [BATCH_COURIERNAME] VARCHAR(100) NULL,
    [BATCH_SCANFLAG] VARCHAR(25) NOT NULL,
    CONSTRAINT [PK_BATCH_MAIN] PRIMARY KEY ([BATCH_ID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BATCH_DET')
CREATE TABLE [BATCH_DET] (
    [BATCH_DETID] INT NOT NULL,
    [BATCH_ID] BIGINT NOT NULL,
    [BATCH_ENVID] INT NOT NULL,
    [BATCH_CREATEDBY] BIGINT NOT NULL,
    [BATCH_CREATEDON] DATETIME2(3) NOT NULL,
    [BATCH_RECEIVEFLAG] CHAR(1) NOT NULL,
    [BATCH_RECEIVEDBY] BIGINT NULL,
    [BATCH_RECEIVEDON] DATETIME2(3) NULL,
    [BATCH_CANCELDATE] DATETIME2(3) NOT NULL,
    [BATCH_CANCELBY] BIGINT NOT NULL,
    CONSTRAINT [PK_BATCH_DET] PRIMARY KEY ([BATCH_DETID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ENV_MAIN')
CREATE TABLE [ENV_MAIN] (
    [ENV_ID] BIGINT NOT NULL,
    [ENV_TYPE] CHAR(3) NOT NULL,
    [ENV_CREATEDBY] BIGINT NOT NULL,
    [ENV_CREATEDON] DATETIME2(3) NOT NULL,
    [ENV_RECEIVEDBY] BIGINT NULL,
    [ENV_RECEIVEDON] DATETIME2(3) NULL,
    [ENV_SUMMARYFLAG] CHAR(1) NOT NULL,
    [ENV_CANCELLEDBY] BIGINT NULL,
    [ENV_CANCELLEDON] DATETIME2(3) NULL,
    [ENV_CONFIRMEDBY] BIGINT NULL,
    [ENV_CONFIRMEDON] DATETIME2(3) NULL,
    [ENV_SCANLOTNO] BIGINT NULL,
    [ENV_LOCID] BIGINT NOT NULL,
    CONSTRAINT [PK_ENV_MAIN] PRIMARY KEY ([ENV_ID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ENV_DET')
CREATE TABLE [ENV_DET] (
    [ENV_DETID] BIGINT NOT NULL,
    [ENV_ID] BIGINT NOT NULL,
    [ENV_TYPE] CHAR(3) NOT NULL,
    [ENV_DOCID] INT NOT NULL,
    [ENV_CREATEDBY] BIGINT NOT NULL,
    [ENV_CREATEDON] DATETIME2(3) NOT NULL,
    [ENV_RECEIVEFLAG] CHAR(1) NOT NULL,
    [ENV_RECEIVEDBY] BIGINT NOT NULL,
    [ENV_RECEIVEDON] DATETIME2(3) NOT NULL,
    [ENV_CANCELDATE] DATETIME2(3) NOT NULL,
    [ENV_CANCELBY] BIGINT NOT NULL,
    CONSTRAINT [PK_ENV_DET] PRIMARY KEY ([ENV_DETID])
);

-- ── HR Document Tables ─────────────────────────────────────────────

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'HRDOC_DET')
CREATE TABLE [HRDOC_DET] (
    [DOC_ID] BIGINT NOT NULL,
    [DOC_NO] BIGINT NOT NULL,
    [DOC_TYPE] CHAR(3) NOT NULL,
    [DOC_PAYREFNO] BIGINT NOT NULL,
    [DOC_LOCID] BIGINT NOT NULL,
    [DOC_UNITID] BIGINT NOT NULL,
    [DOC_REMARKS] VARCHAR(100) NOT NULL,
    [DOC_USERID] BIGINT NOT NULL,
    [DOC_REFNO] VARCHAR(50) NULL,
    [DOC_REFNAME] VARCHAR(200) NULL,
    [DOC_CREATEDON] DATETIME2(3) NOT NULL,
    [DOC_DOCSTATUS] CHAR(2) NOT NULL,
    [DOC_SOURCE] CHAR(3) NOT NULL,
    [DOC_ACTIONSTATUS] CHAR(1) NULL,
    [DOC_ACTIONTAKENON] DATETIME2(3) NULL,
    [DOC_ACTIONTAKENBY] DECIMAL(38) NULL,
    [DOC_FILEPATH] VARCHAR(200) NULL,
    [DOC_CANCELFLAG] CHAR(1) NULL,
    [DOC_CANCELBY] DECIMAL(38) NULL,
    [DOC_CANCELON] DATETIME2(3) NULL,
    [DOC_PAYBY] DECIMAL(38) NULL,
    [DOC_REJECTREMARKS] VARCHAR(200) NULL,
    CONSTRAINT [PK_HRDOC_DET] PRIMARY KEY ([DOC_ID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'HRDOC_COUNTER')
CREATE TABLE [HRDOC_COUNTER] (
    [DOC_NO] BIGINT NULL
);

-- ── AP Group Tables ────────────────────────────────────────────────

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'APGROUP_MAST')
CREATE TABLE [APGROUP_MAST] (
    [GROUP_ID] BIGINT NOT NULL,
    [GROUP_NAME] VARCHAR(50) NOT NULL,
    [GROUP_CREATEDBY] BIGINT NOT NULL,
    [GROUP_CREATEDON] DATETIME2(3) NOT NULL,
    [GROUP_MODIFIEDBY] BIGINT NULL,
    [GROUP_MODIFIEDON] DATETIME2(3) NULL,
    [GROUP_PRIORITYID] BIGINT NULL,
    CONSTRAINT [PK_APGROUP_MAST] PRIMARY KEY ([GROUP_ID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'APGROUP_MAP')
CREATE TABLE [APGROUP_MAP] (
    [MAP_ID] BIGINT NOT NULL,
    [MAP_GROUPID] BIGINT NOT NULL,
    [MAP_PAYBYSPECIFIC] INT NOT NULL,
    [MAP_BUSPECIFIC] INT NOT NULL,
    [MAP_MAINCAT] BIGINT NOT NULL,
    [MAP_SUBCAT] BIGINT NOT NULL,
    [MAP_CURRENCY] CHAR(1) NULL,
    [MAP_CREATEDBY] BIGINT NOT NULL,
    [MAP_CREATEDON] DATETIME2(3) NOT NULL,
    [MAP_MODIFIEDBY] BIGINT NULL,
    [MAP_MODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_APGROUP_MAP] PRIMARY KEY ([MAP_ID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'APGROUP_USERMAP')
CREATE TABLE [APGROUP_USERMAP] (
    [MAP_ID] BIGINT NOT NULL,
    [MAP_GROUPID] BIGINT NOT NULL,
    [MAP_USERID] BIGINT NOT NULL,
    [MAP_EFFECTIVEDATE] DATETIME2(3) NOT NULL,
    [MAP_CLOSUREDATE] DATETIME2(3) NULL,
    [MAP_CREATEDBY] BIGINT NOT NULL,
    [MAP_CREATEDON] DATETIME2(3) NOT NULL,
    [MAP_MODIFIEDBY] BIGINT NULL,
    [MAP_MODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_APGROUP_USERMAP] PRIMARY KEY ([MAP_ID])
);

-- ── AP Allocation & Correspondence Tables ──────────────────────────

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DOC_APALLDET')
CREATE TABLE [DOC_APALLDET] (
    [APALL_ID] BIGINT NOT NULL,
    [APALL_DOCID] BIGINT NOT NULL,
    [APALL_ACTION] CHAR(1) NOT NULL,
    [APALL_GROUPID] BIGINT NOT NULL,
    [APALL_PULLSTATUS] CHAR(1) NOT NULL,
    [APALL_PULLUSERID] BIGINT NOT NULL,
    [APALL_PRIORITY] INT NOT NULL,
    [APALL_ALLBY] BIGINT NOT NULL,
    [APALL_ALLON] DATETIME2(3) NOT NULL,
    [APALL_REMARKS] VARCHAR(200) NULL,
    [APALL_ACTIONFLAG] CHAR(1) NOT NULL,
    [APALL_ACTIONDATE] DATETIME2(3) NULL,
    [APALL_CORRID] BIGINT NULL,
    [APALL_DEFTYPE] BIGINT NULL,
    [APALL_CLOSEREMARKS] VARCHAR(200) NULL,
    [APALL_MODIFIEDBY] BIGINT NOT NULL,
    [APALL_MODIFIEDON] DATETIME2(3) NOT NULL,
    [APALL_PULLEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_DOC_APALLDET] PRIMARY KEY ([APALL_ID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DOC_CORRESPOND')
CREATE TABLE [DOC_CORRESPOND] (
    [CORR_ID] BIGINT NOT NULL,
    [CORR_DOCID] BIGINT NOT NULL,
    [CORR_ALLID] BIGINT NOT NULL,
    [CORR_HOLDCAT] BIGINT NOT NULL,
    [CORR_HOLDTYPE] BIGINT NOT NULL,
    [CORR_HOLDDATE] DATETIME2(3) NOT NULL,
    [CORR_HOLDREMARKS] VARCHAR(200) NOT NULL,
    [CORR_HOLDBY] BIGINT NOT NULL,
    [CORR_HOLDSTATUS] CHAR(1) NOT NULL,
    [CORR_RELDATE] DATETIME2(3) NULL,
    [CORR_RELREMARKS] VARCHAR(200) NULL,
    [CORR_RELBY] BIGINT NULL,
    [CORR_HOLDNATURE] DECIMAL(38) NULL,
    CONSTRAINT [PK_DOC_CORRESPOND] PRIMARY KEY ([CORR_ID])
);

-- ── Filing Tables ──────────────────────────────────────────────────

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'FILE_MASTER')
CREATE TABLE [FILE_MASTER] (
    [FILE_ID] BIGINT NOT NULL,
    [FILE_ORGID] VARCHAR(25) NOT NULL,
    [FILE_YEAR] BIGINT NOT NULL,
    [FILE_NO] VARCHAR(25) NOT NULL,
    [FILE_STATUS] CHAR(1) NOT NULL,
    [FILE_REMARKS] VARCHAR(200) NULL,
    [FILE_PODNO] VARCHAR(50) NULL,
    [FILE_COURIERNAME] VARCHAR(200) NULL,
    [FILE_CREATEDON] DATETIME2(3) NOT NULL,
    [FILE_CREATEDBY] BIGINT NOT NULL,
    [FILE_UPDATEDON] DATETIME2(3) NOT NULL,
    [FILE_UPDATEDBY] BIGINT NOT NULL,
    [FILE_DISPATCHEDON] DATETIME2(3) NULL,
    [FILE_DISPATCHEDBY] BIGINT NULL,
    CONSTRAINT [PK_FILE_MASTER] PRIMARY KEY ([FILE_ID])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'FILING_COUNTER')
CREATE TABLE [FILING_COUNTER] (
    [FILING_BUID] VARCHAR(25) NOT NULL,
    [FILE_COUNT] BIGINT NOT NULL
);

-- ── Scanner Tables ─────────────────────────────────────────────────

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SCAN_LOTMAST')
CREATE TABLE [SCAN_LOTMAST] (
    [SCAN_LOTNO] BIGINT NOT NULL,
    [SCAN_USERID] BIGINT NOT NULL,
    [SCAN_STATUS] CHAR(1) NOT NULL,
    [SCAN_DEVICENO] INT NOT NULL,
    [SCAN_CLOSEDATE] DATETIME2(3) NULL,
    [SCAN_CREATEDON] DATETIME2(3) NULL,
    [SCAN_DEVICEID] BIGINT NULL,
    [SCAN_FLAG] CHAR(1) NULL,
    CONSTRAINT [PK_SCAN_LOTMAST] PRIMARY KEY ([SCAN_LOTNO])
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SCANNER_MASTER')
CREATE TABLE [SCANNER_MASTER] (
    [DEVICE_ID] BIGINT NOT NULL,
    [DEVICE_NAME] VARCHAR(100) NULL,
    [DEVICE_LOCID] BIGINT NOT NULL,
    [DEVICE_PATH] VARCHAR(1000) NULL
);

-- ── Vendor Document Tables ─────────────────────────────────────────

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'VENDOR_DOCDET')
CREATE TABLE [VENDOR_DOCDET] (
    [VNDDOC_ID] BIGINT NOT NULL,
    [VNDDOC_VENDORID] BIGINT NOT NULL,
    [VNDDOC_SITEID] BIGINT NOT NULL,
    [VNDDOC_BUID] BIGINT NOT NULL,
    [VNDDOC_INFCAT] BIGINT NOT NULL,
    [VNDDOC_REMARKS] VARCHAR(2000) NOT NULL,
    [VNDDOC_DOCFLAG] CHAR(1) NOT NULL,
    [VNDDOC_DOCTYPE] BIGINT NULL,
    [VNDDOC_DOCREFNO] VARCHAR(100) NULL,
    [VNDDOC_VALIDFROM] DATETIME2(3) NOT NULL,
    [VNDDOC_VALIDTO] DATETIME2(3) NULL,
    [VNDDOC_ACTIVESTATUS] CHAR(1) NOT NULL,
    [VNDDOC_MODIFIEDBY] BIGINT NOT NULL,
    [VNDDOC_MODIFIEDON] DATETIME2(3) NOT NULL,
    [VNDDOC_APPSTATUS] CHAR(1) NOT NULL,
    [VNDDOC_APPREMARKS] VARCHAR(500) NULL,
    [VNDDOC_APPROVEDBY] BIGINT NULL,
    [VNDDOC_APPROVEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_VENDOR_DOCDET] PRIMARY KEY ([VNDDOC_ID])
);

-- ── Pull Matrix Table ──────────────────────────────────────────────

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'PULLMATRIX_DET')
CREATE TABLE [PULLMATRIX_DET] (
    [MAT_ID] BIGINT NOT NULL,
    [MAT_UNITID] BIGINT NOT NULL,
    [MAT_PAYBY] CHAR(2) NOT NULL,
    [MAT_FLAG] CHAR(1) NOT NULL,
    [MAT_MAINCAT] BIGINT NOT NULL,
    [MAT_EMPSYSID] BIGINT NOT NULL,
    [MAT_MAXNOS] BIGINT NOT NULL,
    [MAT_CREATEDBY] BIGINT NOT NULL,
    [MAT_CREATEDON] DATETIME2(3) NOT NULL,
    [MAT_MODIFIEDBY] BIGINT NOT NULL,
    [MAT_MODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_PULLMATRIX_DET] PRIMARY KEY ([MAT_ID])
);

PRINT 'SSCDB schema created successfully.';
"

echo "============================================"
echo "Creating SSCDB stored procedures..."
echo "============================================"

$SQLCMD -S $SERVER -U $USER -P "$PASSWORD" -C -d SSCDB -Q "
IF OBJECT_ID('dbo.fn_GetActiveClubCount', 'FN') IS NOT NULL DROP FUNCTION dbo.fn_GetActiveClubCount;
"

$SQLCMD -S $SERVER -U $USER -P "$PASSWORD" -C -d SSCDB -Q "
CREATE FUNCTION dbo.fn_GetActiveClubCount ()
RETURNS INT
AS BEGIN
    DECLARE @Count INT = 0;
    BEGIN TRY
        SELECT @Count = COUNT(*) FROM dbo.CLUB_MASTER WHERE CLUB_STATUS = 'A';
    END TRY BEGIN CATCH SET @Count = 0; END CATCH
    RETURN @Count;
END;
"

echo "============================================"
echo "Database initialization complete!"
echo "============================================"
echo "  Databases: SSCDB, SSCDB_CategoryVendor, SSCDB_InvoiceProcessing"
echo "  Tables and procedures created in SSCDB"
