-- ==========================================
-- MODULE: STATIONERY
-- Component: Tables
-- Description: Stationery request, order, and inventory management tables
-- Database: ADMINDB
-- ==========================================

USE [ADMINDB];
GO

-- Table: STATIONARY_MASTER
-- Purpose: Master list of stationery items with pricing and stock information
CREATE TABLE [STATIONARY_MASTER] (
    [SM_STATIONARYID] BIGINT NOT NULL,
    [SM_CATID] BIGINT NOT NULL,
    [SM_LOC_ID] BIGINT NOT NULL,
    [SM_DESC] VARCHAR(200) NOT NULL,
    [SM_UOMID] BIGINT NOT NULL,
    [SM_MAKE] VARCHAR(10) NOT NULL,
    [SM_PRICE_PERUNIT] BIGINT NULL,
    [SM_REORDER_LEVEL] BIGINT NULL,
    [SM_UPDATED_BY] BIGINT NOT NULL,
    [SM_UPDATED_ON] DATETIME2(3) NOT NULL,
    [SM_VMID] BIGINT NOT NULL,
    [SM_CLOSED] CHAR(1) NOT NULL,
    [SM_OPENINGSTOCK] BIGINT NOT NULL,
    CONSTRAINT [PK_STATIONARY_MASTER] PRIMARY KEY ([SM_STATIONARYID])
);
GO

-- Table: SP_CATEGORY_DEFAULT
-- Purpose: Default category assignments for stationery items
CREATE TABLE [SP_CATEGORY_DEFAULT] (
    [CD_STATIONERYID] BIGINT NOT NULL,
    [CD_CATEGORYID] BIGINT NOT NULL,
    [CD_LOCATIONID] BIGINT NOT NULL,
    [CD_MODIFIEDBY] BIGINT NOT NULL,
    [CD_MODIFIEDON] DATETIME2(3) NOT NULL
);
GO

-- Table: SP_REQUEST_MAIN
-- Purpose: Main stationery request header
CREATE TABLE [SP_REQUEST_MAIN] (
    [RM_REQUESTID] BIGINT NOT NULL,
    [RM_REQUESTEDBY] BIGINT NOT NULL,
    [RM_REQUESTEDON] DATETIME2(3) NOT NULL,
    [RM_LOCATIONID] BIGINT NULL,
    [RM_UNITCODE] CHAR(3) NULL,
    CONSTRAINT [PK_SP_REQUEST_MAIN] PRIMARY KEY ([RM_REQUESTID])
);
GO

-- Table: SP_REQUEST_SUB
-- Purpose: Detail lines of stationery requests with approval and status tracking
CREATE TABLE [SP_REQUEST_SUB] (
    [RS_REQUESTSUB_ID] BIGINT NOT NULL,
    [RS_REQUESTID] BIGINT NOT NULL,
    [RS_STATIONARYID] BIGINT NOT NULL,
    [RS_DEPTID] BIGINT NOT NULL,
    [RS_EXPECTED_DATE] DATETIME2(3) NOT NULL,
    [RS_USER_SYSID] BIGINT NULL,
    [RS_REQUESTEDQTY] BIGINT NOT NULL,
    [RS_INDENTEDQTY] BIGINT NULL,
    [RS_APPROVEDQTY] BIGINT NULL,
    [RS_APPROVER_SYSID] BIGINT NULL,
    [RS_APPROVER_RAMARKS] VARCHAR(255) NULL,
    [RS_RECEIVED_DATE] DATETIME2(3) NULL,
    [RS_STATUS] VARCHAR(1) NOT NULL,
    [RS_UPDATED_BY] BIGINT NOT NULL,
    [RS_UPDATED_ON] DATETIME2(3) NOT NULL,
    [RS_APPROVED_ON] DATETIME2(3) NULL,
    CONSTRAINT [PK_SP_REQUEST_SUB] PRIMARY KEY ([RS_REQUESTSUB_ID]),
    CONSTRAINT [FK_SP_REQUEST_SUB_MAIN] FOREIGN KEY ([RS_REQUESTID]) REFERENCES [SP_REQUEST_MAIN]([RM_REQUESTID])
);
GO

-- Table: SP_ORDER_MAIN
-- Purpose: Main purchase order for approved stationery requests
CREATE TABLE [SP_ORDER_MAIN] (
    [OM_ORDERMAIN_ID] BIGINT NOT NULL,
    [OM_LOCATION_ID] BIGINT NOT NULL,
    [OM_VENDORID] BIGINT NOT NULL,
    [OM_DELIVERYDATE] DATETIME2(3) NOT NULL,
    [OM_ORDEREDDATE] DATETIME2(3) NOT NULL,
    [OM_ORDEREDBY] BIGINT NOT NULL,
    CONSTRAINT [PK_SP_ORDER_MAIN] PRIMARY KEY ([OM_ORDERMAIN_ID])
);
GO

-- Table: SP_ORDER_SUB
-- Purpose: Detailed items in purchase orders with receipt tracking
CREATE TABLE [SP_ORDER_SUB] (
    [OS_ORDERSUB_ID] BIGINT NOT NULL,
    [OS_ORDERMAIN_ID] BIGINT NOT NULL,
    [OS_REQUESTSUB_ID] BIGINT NOT NULL,
    [OS_ORDERED_QTY] BIGINT NOT NULL,
    [OS_RECEIVEDON] DATETIME2(3) NULL,
    [OS_RECEIVED_BY] BIGINT NOT NULL,
    [OS_ORDERPRICE] BIGINT NOT NULL,
    [OS_ACTUALPRICE] BIGINT NOT NULL,
    [OS_RECEIVEDDATE] DATETIME2(3) NOT NULL,
    [OS_DELIVERYDATE] DATETIME2(3) NOT NULL,
    [OS_RECEIPTENTRYBY] BIGINT NULL,
    [OS_RECEIPTENTRYON] DATETIME2(3) NULL,
    CONSTRAINT [PK_SP_ORDER_SUB] PRIMARY KEY ([OS_ORDERSUB_ID]),
    CONSTRAINT [FK_SP_ORDER_SUB_MAIN] FOREIGN KEY ([OS_ORDERMAIN_ID]) REFERENCES [SP_ORDER_MAIN]([OM_ORDERMAIN_ID]),
    CONSTRAINT [FK_SP_ORDER_SUB_REQSUB] FOREIGN KEY ([OS_REQUESTSUB_ID]) REFERENCES [SP_REQUEST_SUB]([RS_REQUESTSUB_ID])
);
GO

-- Table: SP_DEPT_BUDGET
-- Purpose: Budget allocation for departments at location level
CREATE TABLE [SP_DEPT_BUDGET] (
    [DB_LOCATION_ID] BIGINT NOT NULL,
    [DB_UNIT_CODE] CHAR(3) NOT NULL,
    [DB_DEPT_ID] BIGINT NOT NULL,
    [DB_FINYEAR_ID] BIGINT NOT NULL,
    [DB_BUDGETAMOUNT] BIGINT NOT NULL,
    [DB_UPDATED_BY] BIGINT NOT NULL,
    [DB_UPDATED_ON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_SP_DEPT_BUDGET] PRIMARY KEY ([DB_LOCATION_ID], [DB_DEPT_ID], [DB_FINYEAR_ID])
);
GO

-- Table: SP_UNIT_BUDGET
-- Purpose: Budget allocation for units across financial years
CREATE TABLE [SP_UNIT_BUDGET] (
    [UB_LOCATION_ID] BIGINT NOT NULL,
    [UB_UNIT_CODE] CHAR(3) NOT NULL,
    [UB_FINYEAR_ID] BIGINT NOT NULL,
    [UB_BUDGETAMOUNT] BIGINT NOT NULL,
    [UB_UPDATED_BY] BIGINT NOT NULL,
    [UB_UPDATED_ON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_SP_UNIT_BUDGET] PRIMARY KEY ([UB_LOCATION_ID], [UB_UNIT_CODE], [UB_FINYEAR_ID])
);
GO

-- Table: SP_DEPT_APPROVER
-- Purpose: Defines approvers and indenters for departments
CREATE TABLE [SP_DEPT_APPROVER] (
    [DA_LOCATION_ID] BIGINT NOT NULL,
    [DA_UNIT_CODE] CHAR(3) NOT NULL,
    [DA_DEPT_ID] BIGINT NOT NULL,
    [DA_EMP_SYSID] BIGINT NOT NULL,
    [DA_TYPE] CHAR(1) NOT NULL,  -- A - Approver, I - Indentor
    [DA_EFFECTIVE_DATE] DATETIME2(3) NOT NULL,
    [DA_CLOSURE_DATE] DATETIME2(3) NULL,
    [DA_UPDATED_BY] BIGINT NOT NULL,
    [DA_UPDATED_ON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_SP_DEPT_APPROVER] PRIMARY KEY ([DA_LOCATION_ID], [DA_DEPT_ID], [DA_EMP_SYSID], [DA_TYPE])
);
GO

-- Table: SP_UNIT_APPROVER
-- Purpose: Defines approvers and indenters for units
CREATE TABLE [SP_UNIT_APPROVER] (
    [UA_LOCATION_ID] BIGINT NOT NULL,
    [UA_UNIT_CODE] CHAR(3) NOT NULL,
    [UA_EMP_SYSID] BIGINT NOT NULL,
    [UA_TYPE] CHAR(1) NOT NULL,
    [UA_EFFECTIVE_DATE] DATETIME2(3) NOT NULL,
    [UA_CLOSURE_DATE] VARCHAR(255) NULL,
    [UA_UPDATED_BY] BIGINT NOT NULL,
    [UA_UPDATED_ON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_SP_UNIT_APPROVER] PRIMARY KEY ([UA_LOCATION_ID], [UA_UNIT_CODE], [UA_EMP_SYSID], [UA_TYPE])
);
GO

-- Table: SP_LOCATION_ADMIN
-- Purpose: Defines stationery administrators for locations
CREATE TABLE [SP_LOCATION_ADMIN] (
    [LA_LOCATION_ID] BIGINT NOT NULL,
    [LA_EMP_SYSID] BIGINT NOT NULL,
    [LA_EFFECTIVE_DATE] DATETIME2(3) NOT NULL,
    [LA_CLOSURE_DATE] DATETIME2(3) NULL,
    [LA_UPDATED_BY] BIGINT NOT NULL,
    [LA_UPDATED_ON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_SP_LOCATION_ADMIN] PRIMARY KEY ([LA_LOCATION_ID], [LA_EMP_SYSID])
);
GO

-- Create indexes for performance
CREATE INDEX [IDX_STATIONERY_MASTER_LOCID] ON [STATIONARY_MASTER]([SM_LOC_ID]);
GO

CREATE INDEX [IDX_REQUEST_MAIN_REQUESTEDBY] ON [SP_REQUEST_MAIN]([RM_REQUESTEDBY]);
GO

CREATE INDEX [IDX_REQUEST_SUB_REQUESTID] ON [SP_REQUEST_SUB]([RS_REQUESTID]);
GO

CREATE INDEX [IDX_REQUEST_SUB_STATUS] ON [SP_REQUEST_SUB]([RS_STATUS]);
GO

CREATE INDEX [IDX_ORDER_MAIN_VENDORID] ON [SP_ORDER_MAIN]([OM_VENDORID]);
GO

CREATE INDEX [IDX_ORDER_SUB_ORDERMAINID] ON [SP_ORDER_SUB]([OS_ORDERMAIN_ID]);
GO

-- ==========================================
-- END OF STATIONERY TABLES
-- ==========================================
