-- COMPENSATION MODULE - SCHEMA DEFINITION
-- CTC, salary components, benefits management

USE [Careers]
GO

/****** CTC_TABLE ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CTC_TABLE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CTC_ID] [bigint] NULL,
	[PER_MONTH] [money] NULL,
	[PER_ANNUM] [money] NULL,
	[APPLICABLE] [bit] NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
	[LOGIN_ID] [bigint] NULL,
	[SL_NO] [int] NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** CTC_COMPONENTS_MASTER ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CTC_COMPONENTS_MASTER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CTC_TYPE] [bigint] NULL,
	[COMPONENTS] [varchar](30) NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** COMPENSATION_HEADER_MASTER ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[COMPENSATION_HEADER_MASTER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[COMPENSATION_NAME] [varchar](100) NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[ENTERED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
 CONSTRAINT [PK_COMPENSATION_HEADER_MASTER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** BASIC_SALARY ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BASIC_SALARY](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOGIN_ID] [bigint] NULL,
	[SL_NO] [int] NULL,
	[COMPONENTS] [varchar](30) NULL,
	[PER_MONTH] [money] NULL,
	[PER_ANNUM] [money] NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** VARIABLE_PAY ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[VARIABLE_PAY](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOGIN_ID] [bigint] NULL,
	[SL_NO] [int] NULL,
	[COMPONENTS] [varchar](30) NULL,
	[PER_MONTH] [money] NULL,
	[PER_ANNUM] [money] NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** ADDITION_TO_CTC ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ADDITION_TO_CTC](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOGIN_ID] [bigint] NULL,
	[SL_NO] [int] NULL,
	[COMPONENTS] [varchar](30) NULL,
	[PER_MONTH] [money] NULL,
	[PER_ANNUM] [money] NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
