-- =========================================================================
-- MASTER DATA MODULE - Database Tables and Reference Data
-- Database: PFDB
-- Module: Master Data Configuration
-- Description: Manages all reference and configuration data
-- Created: March 9, 2026
-- =========================================================================

USE PFDB;
GO

-- PF Financial Year Rules
CREATE TABLE [PF_FINYEARRULES] (
    [PF_FINYEAR_CODE] BIGINT NOT NULL PRIMARY KEY,
    [PF_FINYEAR_RULES] VARCHAR(4000) NULL
);
GO

-- Fund Type Master
CREATE TABLE [FUND_TYPE_MASTER] (
    [FUND_TYPECODE] CHAR(3) NOT NULL PRIMARY KEY,
    [FUND_TYPENAME] VARCHAR(25) NOT NULL
);
GO

-- LOV (List of Values) Master
CREATE TABLE [LOV_MASTER] (
    [LOV_ID] DECIMAL(38) NOT NULL PRIMARY KEY,
    [LOV_CODE] VARCHAR(10) NOT NULL,
    [LOV_DESC] VARCHAR(100) NOT NULL,
    [LOV_VALUE] VARCHAR(20) NOT NULL,
    [LOV_CATEGORY] VARCHAR(50) NOT NULL,
    [LOV_STATUS] CHAR(1) DEFAULT 'A'
);
GO

-- Status Master
CREATE TABLE [STATUS_MASTER] (
    [STATUS_TYPE] CHAR(2) NOT NULL,
    [STATUS_CODE] CHAR(2) NOT NULL,
    [STATUS_NAME] VARCHAR(65) NULL,
    CONSTRAINT [PK_STATUS_MASTER] PRIMARY KEY ([STATUS_TYPE], [STATUS_CODE])
);
GO

-- Role Master
CREATE TABLE [ROLE_MASTER] (
    [ROLE_CODE] BIGINT NOT NULL PRIMARY KEY,
    [ROLE_NAME] VARCHAR(65) NOT NULL,
    [ROLE_DESCRIPTION] VARCHAR(200) NULL,
    [ROLE_STATUS] CHAR(1) DEFAULT 'A'
);
GO

-- Rate Type Master
CREATE TABLE [RATE_TYPE_MASTER] (
    [RATE_TYPE_CODE] CHAR(3) NOT NULL PRIMARY KEY,
    [RATE_TYPE_NAME] VARCHAR(25) NULL
);
GO

-- Rate Master
CREATE TABLE [RATE_MASTER] (
    [RT_TRUST_CODE] CHAR(3) NOT NULL,
    [RATE_ID] INT NOT NULL,
    [RT_RATE_TYPE_CODE] CHAR(3) NULL,
    [RATE_EFF_DATE] VARCHAR(255) NULL,
    [RATE_CLS_DATE] VARCHAR(255) NULL,
    [RATE_VALUE] DECIMAL(19,0) NULL,
    [RATE_DEL_FLAG] CHAR(1) NULL,
    [RT_REWRK_STS] CHAR(1) NULL,
    CONSTRAINT [PK_RATE_MASTER] PRIMARY KEY ([RT_TRUST_CODE], [RATE_ID])
);
GO

-- Computation Month Master
CREATE TABLE [COMP_MONTH] (
    [AC_SRL_NUM] BIGINT NOT NULL PRIMARY KEY,
    [AC_MNT_NAM] VARCHAR(15) NULL
);
GO

-- Computation Financial Year
CREATE TABLE [COMP_FINYEAR] (
    [AC_SRL_NUM] BIGINT NOT NULL PRIMARY KEY,
    [AC_STR_DAT] DATETIME2(3) NOT NULL,
    [AC_END_DAT] DATETIME2(3) NOT NULL,
    [AC_CLS_FLG] CHAR(1) NOT NULL,
    [AC_REMARKS] VARCHAR(4000) NULL,
    [AC_INT_FLG] CHAR(1) NULL,
    [AC_EMP_NAME] VARCHAR(65) NULL,
    [AC_EMP_DESG] VARCHAR(65) NULL,
    [AC_BAT_NUM] BIGINT NULL
);
GO

-- Investment Category Group Master
CREATE TABLE [INVCATGRP_MAST] (
    [INVGRP_ID] INT NOT NULL PRIMARY KEY,
    [INVGRP_SHTNAME] VARCHAR(20) NULL,
    [INVGRP_NAME] VARCHAR(50) NULL
);
GO

-- Investment Category Limits
CREATE TABLE [INVCAT_LIMIT] (
    [INVCAT_LIMITID] INT NOT NULL PRIMARY KEY,
    [INVCAT_ID] INT NOT NULL,
    [INVCAT_MAXPER] INT NOT NULL,
    [INVCAT_EFFDATE] DATETIME2(3) NOT NULL,
    [INVCAT_CLSDATE] DATETIME2(3) NULL
);
GO

-- Investment Group Limits
CREATE TABLE [INVGRP_LIMIT] (
    [INVGRP_LIMITID] INT NOT NULL PRIMARY KEY,
    [INVGRP_ID] INT NOT NULL,
    [INVGRP_MAXPER] INT NOT NULL,
    [INVGRP_EFFDATE] DATETIME2(3) NOT NULL,
    [INVGRP_CLSDATE] DATETIME2(3) NULL,
    [INVGRP_RANGE] VARCHAR(20) NULL
);
GO

-- PF HRIS Integration
CREATE TABLE [PF_HRIS] (
    [COM_COD] CHAR(3) NOT NULL,
    [EMP_NUM] DECIMAL(38) NOT NULL,
    [PIN_NUM] DECIMAL(38) NOT NULL,
    CONSTRAINT [PK_PF_HRIS] PRIMARY KEY ([COM_COD], [EMP_NUM])
);
GO

-- PF Main Accounts
CREATE TABLE [PF_MAIN_ACCOUNT] (
    [MAIN_ACC_COD] DECIMAL(38) NOT NULL PRIMARY KEY,
    [MAIN_ACC_NAM] VARCHAR(60) NOT NULL
);
GO

-- PF Main to Sub Account Mapping
CREATE TABLE [PF_MAIN_SUB] (
    [MAIN_ACC_COD] BIGINT NOT NULL,
    [SUB_ACC_COD] BIGINT NOT NULL,
    CONSTRAINT [PK_PF_MAIN_SUB] PRIMARY KEY ([MAIN_ACC_COD], [SUB_ACC_COD])
);
GO

-- Configuration Master
CREATE TABLE [CONFIGURATION] (
    [CONFIG_ID] INT IDENTITY(1,1) PRIMARY KEY,
    [CONFIG_KEY] VARCHAR(100) NOT NULL UNIQUE,
    [CONFIG_VALUE] VARCHAR(500) NOT NULL,
    [CONFIG_TYPE] VARCHAR(50) NOT NULL,
    [CONFIG_DESCRIPTION] VARCHAR(200) NULL,
    [CREATED_DATE] DATETIME2(3) NOT NULL,
    [UPDATED_DATE] DATETIME2(3) NULL,
    [CREATED_BY] BIGINT NOT NULL
);
GO

CREATE NONCLUSTERED INDEX [IDX_LOV_MASTER_CODE] ON [LOV_MASTER] ([LOV_CATEGORY], [LOV_CODE]);
CREATE NONCLUSTERED INDEX [IDX_CONFIG_KEY] ON [CONFIGURATION] ([CONFIG_KEY]);
CREATE NONCLUSTERED INDEX [IDX_RATE_MASTER_TYPE] ON [RATE_MASTER] ([RT_RATE_TYPE_CODE], [RATE_EFF_DATE]);

PRINT 'Master Data Module Tables created successfully!';
GO
