// <auto-generated />
using System;
using ContributionService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContributionService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContributionDbContext))]
    partial class ContributionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContributionService.Domain.Entities.ContributionBreakup", b =>
                {
                    b.Property<long>("ContributionPayTranNo")
                        .HasColumnType("bigint")
                        .HasColumnName("CONTRIBUTION_PAYTRANNO");

                    b.Property<long>("ContributionBatchNo")
                        .HasColumnType("bigint")
                        .HasColumnName("CONTRIBUTION_BATCH_NO");

                    b.Property<long>("ContributionId")
                        .HasColumnType("bigint")
                        .HasColumnName("CONTRIBUTION_ID");

                    b.Property<string>("ContributionComCod")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("CONTRIBUTION_COM_COD")
                        .IsFixedLength();

                    b.Property<string>("ContributionEdCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)")
                        .HasColumnName("CONTRIBUTION_EDCODE")
                        .IsFixedLength();

                    b.Property<decimal>("ContributionEeAmount")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("CONTRIBUTION_EEAMOUNT");

                    b.Property<decimal>("ContributionErAmount")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("CONTRIBUTION_ERAMOUNT");

                    b.Property<decimal>("ContributionPayAmount")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("CONTRIBUTION_PAYAMOUNT");

                    b.HasKey("ContributionPayTranNo", "ContributionBatchNo", "ContributionId");

                    b.ToTable("CONTRIBUTION_BREAKUP", (string)null);
                });

            modelBuilder.Entity("ContributionService.Domain.Entities.ContributionDetail", b =>
                {
                    b.Property<decimal>("ContributionId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CONTRIBUTION_ID");

                    b.Property<decimal>("ContributionBasicAmount")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CONTRIBUTION_BASIC_AMOUNT");

                    b.Property<decimal>("ContributionBatchNo")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CONTRIBUTION_BATCH_NO");

                    b.Property<decimal>("ContributionEeAmount")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CONTRIBUTION_EE_AMOUNT");

                    b.Property<decimal?>("ContributionEmpSysId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CONTRIBUTION_EMP_SYSID");

                    b.Property<decimal>("ContributionEmployeeNo")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CONTRIBUTION_EMPLOYEE_NO");

                    b.Property<string>("ContributionEntByUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CONTRIBUTION_ENT_BY_USER_ID");

                    b.Property<decimal>("ContributionEntEmpSysId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CONTRIBUTION_ENT_EMP_SYS_ID");

                    b.Property<DateTime>("ContributionEntOn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CONTRIBUTION_ENT_ON");

                    b.Property<decimal>("ContributionErAmount")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CONTRIBUTION_ER_AMOUNT");

                    b.Property<decimal>("ContributionFpAmount")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CONTRIBUTION_FP_AMOUNT");

                    b.Property<decimal>("ContributionFpsBasicAmount")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CONTRIBUTION_FPSBASIC_AMOUNT");

                    b.Property<decimal>("ContributionLoanInterest")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CONTRIBUTION_LOAN_INTEREST");

                    b.Property<decimal>("ContributionLoanPrincipal")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CONTRIBUTION_LOAN_PRINCIPAL");

                    b.Property<decimal>("ContributionMemberNo")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CONTRIBUTION_MEMBER_NO");

                    b.Property<decimal?>("ContributionReferenceNo")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CONTRIBUTION_REFERENCE_NO");

                    b.Property<string>("ContributionReferenceRemarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CONTRIBUTION_REFERENCE_REMARKS");

                    b.Property<string>("ContributionTypeCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("CONTRIBUTION_TYPE_CODE")
                        .IsFixedLength();

                    b.Property<string>("ContributionUnitCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("CONTRIBUTION_UNIT_CODE")
                        .IsFixedLength();

                    b.Property<decimal>("ContributionVeAmount")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CONTRIBUTION_VE_AMOUNT");

                    b.HasKey("ContributionId");

                    b.ToTable("CONTRIBUTION_DETAILS", (string)null);
                });

            modelBuilder.Entity("ContributionService.Domain.Entities.ContributionMain", b =>
                {
                    b.Property<long>("ContributionBatchNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CONTRIBUTION_BATCH_NO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ContributionBatchNo"));

                    b.Property<string>("ContributionCategory")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("CONTRIBUTION_CATEGORY")
                        .IsFixedLength();

                    b.Property<DateTime?>("ContributionEntOn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CONTRIBUTION_ENT_ON");

                    b.Property<decimal?>("ContributionJvNo")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CONTRIBUTION_JVNO");

                    b.Property<DateTime>("ContributionPayMonthEnd")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CONTRIBUTION_PAY_MONTHEND");

                    b.Property<DateTime>("ContributionPayMonthStart")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CONTRIBUTION_PAY_MONTHSTART");

                    b.Property<string>("ContributionPayunitCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("CONTRIBUTION_PAYUNIT_CODE")
                        .IsFixedLength();

                    b.Property<decimal?>("ContributionRecActranNo")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CONTRIBUTION_REC_ACTRAN_NO");

                    b.Property<long>("ContributionRefNo")
                        .HasColumnType("bigint")
                        .HasColumnName("CONTRIBUTION_REFNO");

                    b.Property<string>("ContributionStatus")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("CONTRIBUTION_STATUS")
                        .IsFixedLength();

                    b.Property<string>("ContributionTrustCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("CONTRIBUTION_TRUST_CODE")
                        .IsFixedLength();

                    b.HasKey("ContributionBatchNo");

                    b.ToTable("CONTRIBUTION_MAIN", (string)null);
                });

            modelBuilder.Entity("ContributionService.Domain.Entities.ContributionProcessLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LOG_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("LogMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LOG_MESSAGE");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("LOG_TYPE");

                    b.Property<DateTime>("ProcessDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("PROCESS_DATE");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("USER_ID");

                    b.HasKey("LogId");

                    b.ToTable("CONTRIBUTION_PROCESS_LOG", (string)null);
                });

            modelBuilder.Entity("ContributionService.Domain.Entities.ContributionTemp", b =>
                {
                    b.Property<long>("ContributionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CONTRIBUTION_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ContributionId"));

                    b.Property<decimal>("ContributionBasicAmount")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("CONTRIBUTION_BASIC_AMOUNT");

                    b.Property<long>("ContributionBatchNo")
                        .HasColumnType("bigint")
                        .HasColumnName("CONTRIBUTION_BATCH_NO");

                    b.Property<decimal>("ContributionEeAmount")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("CONTRIBUTION_EE_AMOUNT");

                    b.Property<int>("ContributionEmployeeNo")
                        .HasColumnType("int")
                        .HasColumnName("CONTRIBUTION_EMPLOYEE_NO");

                    b.Property<string>("ContributionEntByUserId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("CONTRIBUTION_ENT_BY_USER_ID");

                    b.Property<int>("ContributionEntEmpSysId")
                        .HasColumnType("int")
                        .HasColumnName("CONTRIBUTION_ENT_EMP_SYS_ID");

                    b.Property<DateTime>("ContributionEntOn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CONTRIBUTION_ENT_ON");

                    b.Property<decimal>("ContributionErAmount")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("CONTRIBUTION_ER_AMOUNT");

                    b.Property<decimal>("ContributionFpAmount")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("CONTRIBUTION_FP_AMOUNT");

                    b.Property<decimal>("ContributionFpsBasicAmount")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("CONTRIBUTION_FPSBASIC_AMOUNT");

                    b.Property<decimal>("ContributionLoanInterest")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("CONTRIBUTION_LOAN_INTEREST");

                    b.Property<decimal>("ContributionLoanPrincipal")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("CONTRIBUTION_LOAN_PRINCIPAL");

                    b.Property<long>("ContributionMemberNo")
                        .HasColumnType("bigint")
                        .HasColumnName("CONTRIBUTION_MEMBER_NO");

                    b.Property<int?>("ContributionReferenceNo")
                        .HasColumnType("int")
                        .HasColumnName("CONTRIBUTION_REFERENCE_NO");

                    b.Property<string>("ContributionReferenceRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CONTRIBUTION_REFERENCE_REMARKS");

                    b.Property<string>("ContributionTypeCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("CONTRIBUTION_TYPE_CODE")
                        .IsFixedLength();

                    b.Property<string>("ContributionUnitCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("CONTRIBUTION_UNIT_CODE")
                        .IsFixedLength();

                    b.Property<decimal>("ContributionVeAmount")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("CONTRIBUTION_VE_AMOUNT");

                    b.HasKey("ContributionId");

                    b.ToTable("CONTRIBUTION_TEMP", (string)null);
                });

            modelBuilder.Entity("ContributionService.Domain.Entities.SuperannuationBatch", b =>
                {
                    b.Property<long>("SnBatchNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SN_BATCH_NO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SnBatchNo"));

                    b.Property<string>("SnCategory")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("SN_CATEGORY")
                        .IsFixedLength();

                    b.Property<string>("SnConAmt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SN_CON_AMT");

                    b.Property<string>("SnEntOn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SN_ENT_ON");

                    b.Property<DateTime?>("SnPayDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("SN_PAY_DATE");

                    b.Property<DateTime?>("SnPayMonthEnd")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("SN_PAY_MONTHEND");

                    b.Property<string>("SnPayMonthStart")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SN_PAY_MONTHSTART");

                    b.Property<string>("SnPayunitCode")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("SN_PAYUNIT_CODE")
                        .IsFixedLength();

                    b.Property<string>("SnStatus")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("SN_STATUS")
                        .IsFixedLength();

                    b.Property<long?>("SnTrustCode")
                        .HasColumnType("bigint")
                        .HasColumnName("SN_TRUST_CODE");

                    b.HasKey("SnBatchNo");

                    b.ToTable("SUPERANN_BATCH", (string)null);
                });

            modelBuilder.Entity("ContributionService.Domain.Entities.SuperannuationBreakup", b =>
                {
                    b.Property<decimal?>("SnActAmt")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("SN_ACT_AMT");

                    b.Property<long?>("SnBatNo")
                        .HasColumnType("bigint")
                        .HasColumnName("SN_BAT_NO");

                    b.Property<DateTime?>("SnConDat")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("SN_CON_DAT");

                    b.Property<string>("SnConTyp")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("SN_CON_TYP")
                        .IsFixedLength();

                    b.Property<string>("SnEmpNam")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SN_EMP_NAM");

                    b.Property<DateTime?>("SnEntDat")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("SN_ENT_DAT");

                    b.Property<decimal?>("SnExgAmt")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("SN_EXG_AMT");

                    b.Property<long?>("SnFinYer")
                        .HasColumnType("bigint")
                        .HasColumnName("SN_FIN_YER");

                    b.Property<decimal?>("SnFudNum")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("SN_FUD_NUM");

                    b.Property<decimal?>("SnGrsAmt")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("SN_GRS_AMT");

                    b.Property<decimal?>("SnPayAmt")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("SN_PAY_AMT");

                    b.Property<long?>("SnPinNum")
                        .HasColumnType("bigint")
                        .HasColumnName("SN_PIN_NUM");

                    b.Property<decimal?>("SnTrsAmt")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("SN_TRS_AMT");

                    b.ToTable("SUPERANN_BREAKUP", (string)null);
                });

            modelBuilder.Entity("ContributionService.Domain.Entities.SuperannuationContribution", b =>
                {
                    b.Property<long>("SnSlrNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SN_SLR_NUM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SnSlrNum"));

                    b.Property<decimal?>("SnConAmt")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("SN_CON_AMT");

                    b.Property<DateTime?>("SnConDat")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("SN_CON_DAT");

                    b.Property<string>("SnConTyp")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("SN_CON_TYP")
                        .IsFixedLength();

                    b.Property<string>("SnEmpNam")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SN_EMP_NAM");

                    b.Property<DateTime?>("SnEntDat")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("SN_ENT_DAT");

                    b.Property<long?>("SnFinYer")
                        .HasColumnType("bigint")
                        .HasColumnName("SN_FIN_YER");

                    b.Property<decimal?>("SnFudNum")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("SN_FUD_NUM");

                    b.Property<decimal?>("SnNavAmt")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("SN_NAV_AMT");

                    b.Property<decimal?>("SnPinNum")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("SN_PIN_NUM");

                    b.Property<decimal?>("SnUntNos")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("SN_UNT_NOS");

                    b.HasKey("SnSlrNum");

                    b.ToTable("SUPERANN_CONTRIBUTION", (string)null);
                });

            modelBuilder.Entity("ContributionService.Domain.Entities.SuperannuationRate", b =>
                {
                    b.Property<long?>("SnFudNum")
                        .HasColumnType("bigint")
                        .HasColumnName("SN_FUD_NUM");

                    b.Property<DateTime?>("SnMonth")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("SN_MONTH");

                    b.Property<decimal?>("SnRate")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("SN_RATE");

                    b.ToTable("SUPERANN_RATE", (string)null);
                });

            modelBuilder.Entity("ContributionService.Domain.Entities.SuperannuationTrustName", b =>
                {
                    b.Property<decimal>("StFndNum")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("ST_FND_NUM");

                    b.Property<string>("StFndNam")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ST_FND_NAM");

                    b.HasKey("StFndNum");

                    b.ToTable("SUPERANN_TRUSTNAME", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
