apiVersion: v1
kind: Secret
metadata:
  name: canteentransaction-service-secrets
  namespace: canteentransaction-service
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=sql-server.default.svc.cluster.local;Database=CanteenTransactionDb;User Id=sa;Password=YourPassword123!;TrustServerCertificate=True;"
  Jwt__Key: "CanteenTransactionService-SuperSecretKey-ChangeInProduction-Min32Characters!"
  RabbitMQ__Password: "guest"
---
apiVersion: v1
kind: Secret
metadata:
  name: canteentransaction-service-docker-registry
  namespace: canteentransaction-service
type: kubernetes.io/dockercfg
data:
  .dockercfg: e30=
