apiVersion: v1
kind: Service
metadata:
  name: canteentransaction-service
  namespace: canteentransaction-service
  labels:
    app: canteentransaction-service
spec:
  type: LoadBalancer
  selector:
    app: canteentransaction-service
  ports:
  - name: http
    port: 80
    targetPort: 5195
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: v1
kind: Service
metadata:
  name: canteentransaction-service-internal
  namespace: canteentransaction-service
  labels:
    app: canteentransaction-service
spec:
  type: ClusterIP
  selector:
    app: canteentransaction-service
  ports:
  - name: http
    port: 5195
    targetPort: 5195
    protocol: TCP
