// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RequestServices.Infrastructure.Data;

#nullable disable

namespace RequestServices.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RequestDbContext))]
    partial class RequestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RequestServices.Domain.Entities.RequestAction", b =>
                {
                    b.Property<long>("SerialNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_SRL_NUM");

                    b.Property<string>("ActionFlag")
                        .HasColumnType("char(1)")
                        .HasColumnName("RQ_ACT_FLG");

                    b.Property<long?>("ActionNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_ACT_NUM");

                    b.Property<DateTime?>("CancellationDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("RQ_CAN_DAT");

                    b.Property<string>("CancellationRemark")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RQ_CAN_REM");

                    b.Property<long?>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_CRS_ID");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("RQ_ENT_DAT");

                    b.Property<string>("EntryUser")
                        .HasColumnType("char(1)")
                        .HasColumnName("RQ_ENT_USR");

                    b.Property<string>("KeyExperience")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RQ_KEY_EXP");

                    b.Property<long?>("RequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_REQ_ID");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("RQ_REV_DAT");

                    b.Property<long?>("ReviewNotes")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_REV_NOS");

                    b.Property<string>("ReviewUser")
                        .HasColumnType("char(1)")
                        .HasColumnName("RQ_REV_USR");

                    b.Property<string>("SupervisorExperience")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RQ_SUP_EXP");

                    b.Property<decimal?>("TimeExperience")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("RQ_TIM_EXP");

                    b.Property<string>("UsageExperience")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RQ_USG_EXP");

                    b.HasKey("SerialNumber");

                    b.ToTable("REQUEST_ACTION", (string)null);
                });

            modelBuilder.Entity("RequestServices.Domain.Entities.RequestApp", b =>
                {
                    b.Property<long>("RequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_REQ_ID");

                    b.Property<long>("SerialNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_SRL_NUM");

                    b.Property<DateTime>("ApprovalDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("RQ_APP_DAT");

                    b.Property<long>("ApprovalNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_APP_NUM");

                    b.Property<string>("ApprovalRemark")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("RQ_APP_REM");

                    b.Property<string>("ApprovalUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RQ_APP_USR");

                    b.HasKey("RequestId", "SerialNumber");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("IDX_REQUEST_APP_REQ_ID");

                    b.ToTable("REQUEST_APP", (string)null);
                });

            modelBuilder.Entity("RequestServices.Domain.Entities.RequestMain", b =>
                {
                    b.Property<long>("RequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_REQ_ID");

                    b.Property<string>("EmployeeUser")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("RQ_EMP_USR");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("RQ_REQ_DAT");

                    b.Property<string>("SupervisorUser")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("RQ_SUP_USR");

                    b.HasKey("RequestId");

                    b.HasIndex("EmployeeUser")
                        .HasDatabaseName("IDX_REQUEST_MAIN_EMP_USR");

                    b.HasIndex("SupervisorUser")
                        .HasDatabaseName("IDX_REQUEST_MAIN_SUP_USR");

                    b.ToTable("REQUEST_MAIN", (string)null);
                });

            modelBuilder.Entity("RequestServices.Domain.Entities.RequestNew", b =>
                {
                    b.Property<long>("SerialNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_SRL_NUM");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("RQ_CAT_COD");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_CRS_ID");

                    b.Property<string>("FunctionDescription")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("RQ_FNC_DES");

                    b.Property<long>("LevelNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_LVL_NUM");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_REQ_ID");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("RQ_SKL_NAM");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("RQ_SKL_TYP");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("RQ_STS_COD");

                    b.HasKey("SerialNumber");

                    b.ToTable("REQUEST_NEW", (string)null);
                });

            modelBuilder.Entity("RequestServices.Domain.Entities.RequestSub", b =>
                {
                    b.Property<long>("SerialNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_SRL_NUM");

                    b.Property<long>("ApprovalNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_APP_NUM");

                    b.Property<long>("ApprovalTime")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_APP_TIM");

                    b.Property<string>("BusinessBenefit")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RQ_BUS_BEN");

                    b.Property<DateTime?>("CancellationDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("RQ_CAN_DAT");

                    b.Property<string>("CancellationRemark")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RQ_CAN_REM");

                    b.Property<string>("CourseAvailability")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("RQ_CRS_AVL");

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RQ_CRS_DES");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_CRS_ID");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("RQ_END_DAT");

                    b.Property<string>("EnteredMode")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("RQ_ENT_MOD");

                    b.Property<string>("EnteredUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RQ_ENT_USR");

                    b.Property<string>("ExpectedCompetency")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RQ_EXP_CNP");

                    b.Property<string>("GoalDesignation")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("RQ_GOL_DES");

                    b.Property<string>("MentorRemark")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RQ_MEN_REM");

                    b.Property<string>("MentorUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RQ_MEN_USR");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("RQ_MOD_DAT");

                    b.Property<string>("ModifiedUser")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("RQ_MOD_USR");

                    b.Property<string>("ModuleTraining")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("RQ_MOD_TRN");

                    b.Property<long>("RefRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_REF_REQ");

                    b.Property<long>("RefSerialNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_REF_SRL");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("RQ_REQ_DAT");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_REQ_ID");

                    b.Property<string>("RequestSource")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("RQ_REQ_SRC");

                    b.Property<long>("ReviewDays")
                        .HasColumnType("bigint")
                        .HasColumnName("RQ_REV_DYS");

                    b.Property<string>("ReviewModule")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RQ_REV_MOD");

                    b.Property<string>("ReviewUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RQ_REV_USR");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("RQ_STR_DAT");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("RQ_STS_COD");

                    b.Property<string>("SupervisorUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RQ_SUP_USR");

                    b.Property<string>("TrainingNeed")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RQ_TRN_NED");

                    b.HasKey("SerialNumber");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("IDX_REQUEST_SUB_REQ_ID");

                    b.ToTable("REQUEST_SUB", (string)null);
                });

            modelBuilder.Entity("RequestServices.Domain.Entities.RequestSub", b =>
                {
                    b.HasOne("RequestServices.Domain.Entities.RequestMain", "RequestMain")
                        .WithMany("SubRequests")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestMain");
                });

            modelBuilder.Entity("RequestServices.Domain.Entities.RequestMain", b =>
                {
                    b.Navigation("SubRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
