-- ==========================================
-- Module: BATCH AND ENVELOPE MODULE
-- Description: Batch processing and envelope handling for document flow
-- Created: March 9, 2026
-- Database: SSCDB
-- ==========================================

USE SSCDB;
GO

-- ==========================================
-- BATCH_MAIN - Batch Master
-- ==========================================
IF OBJECT_ID('[BATCH_MAIN]', 'U') IS NOT NULL DROP TABLE [BATCH_MAIN];
GO
CREATE TABLE [BATCH_MAIN] (
    [BATCH_ID] BIGINT NOT NULL,
    [BATCH_CREATEDBY] BIGINT NOT NULL,
    [BATCH_CREATEDON] DATETIME2(3) NOT NULL,
    [BATCH_LOCATIONID] BIGINT NOT NULL,
    [BATCH_RECEIVEDBY] BIGINT NOT NULL,
    [BATCH_RECEIVEDON] DATETIME2(3) NOT NULL,
    [BATCH_PODNO] VARCHAR(25) NOT NULL,
    [BATCH_SUMMARYFLAG] CHAR(1) NOT NULL,
    [BATCH_CANCELBY] BIGINT NULL,
    [BATCH_CANCELDATE] DATETIME2(3) NULL,
    [BATCH_CONFIRMEDBY] BIGINT NULL,
    [BATCH_CONFIRMEDON] DATETIME2(3) NULL,
    [BATCH_COURIERNAME] VARCHAR(100) NULL,
    [BATCH_SCANFLAG] VARCHAR(25) NOT NULL,
    CONSTRAINT [PK_BATCH_MAIN] PRIMARY KEY ([BATCH_ID])
);
GO

-- ==========================================
-- BATCH_DET - Batch Details
-- ==========================================
IF OBJECT_ID('[BATCH_DET]', 'U') IS NOT NULL DROP TABLE [BATCH_DET];
GO
CREATE TABLE [BATCH_DET] (
    [BATCH_DETID] INT NOT NULL,
    [BATCH_ID] BIGINT NOT NULL,
    [BATCH_ENVID] INT NOT NULL,
    [BATCH_CREATEDBY] BIGINT NOT NULL,
    [BATCH_CREATEDON] DATETIME2(3) NOT NULL,
    [BATCH_RECEIVEFLAG] CHAR(1) NOT NULL,
    [BATCH_RECEIVEDBY] BIGINT NULL,
    [BATCH_RECEIVEDON] DATETIME2(3) NULL,
    [BATCH_CANCELDATE] DATETIME2(3) NOT NULL,
    [BATCH_CANCELBY] BIGINT NOT NULL,
    CONSTRAINT [PK_BATCH_DET] PRIMARY KEY ([BATCH_DETID])
);
GO

-- ==========================================
-- BATCH_RECDET - Batch Receipt Details
-- ==========================================
IF OBJECT_ID('[BATCH_RECDET]', 'U') IS NOT NULL DROP TABLE [BATCH_RECDET];
GO
CREATE TABLE [BATCH_RECDET] (
    [REC_ID] BIGINT NOT NULL,
    [REC_BATCHID] BIGINT NOT NULL,
    [REC_ENVID] BIGINT NOT NULL,
    [REC_UPDATEDBY] BIGINT NOT NULL,
    [REC_UPDATEDON] DATETIME2(3) NOT NULL,
    [REC_SCANLOCATIONID] BIGINT NULL,
    CONSTRAINT [PK_BATCH_RECDET] PRIMARY KEY ([REC_ID])
);
GO

-- ==========================================
-- ENV_MAIN - Envelope Master
-- ==========================================
IF OBJECT_ID('[ENV_MAIN]', 'U') IS NOT NULL DROP TABLE [ENV_MAIN];
GO
CREATE TABLE [ENV_MAIN] (
    [ENV_ID] BIGINT NOT NULL,
    [ENV_TYPE] CHAR(3) NOT NULL,
    [ENV_CREATEDBY] BIGINT NOT NULL,
    [ENV_CREATEDON] DATETIME2(3) NOT NULL,
    [ENV_RECEIVEDBY] BIGINT NULL,
    [ENV_RECEIVEDON] DATETIME2(3) NULL,
    [ENV_SUMMARYFLAG] CHAR(1) NOT NULL,
    [ENV_CANCELLEDBY] BIGINT NULL,
    [ENV_CANCELLEDON] DATETIME2(3) NULL,
    [ENV_CONFIRMEDBY] BIGINT NULL,
    [ENV_CONFIRMEDON] DATETIME2(3) NULL,
    [ENV_SCANLOTNO] BIGINT NULL,
    [ENV_LOCID] BIGINT NOT NULL,
    CONSTRAINT [PK_ENV_MAIN] PRIMARY KEY ([ENV_ID])
);
GO

-- ==========================================
-- SCAN_LOTMAST - Scan Lot Master
-- ==========================================
IF OBJECT_ID('[SCAN_LOTMAST]', 'U') IS NOT NULL DROP TABLE [SCAN_LOTMAST];
GO
CREATE TABLE [SCAN_LOTMAST] (
    [SCAN_LOTNO] BIGINT NOT NULL,
    [SCAN_USERID] BIGINT NOT NULL,
    [SCAN_STATUS] CHAR(1) NOT NULL,
    [SCAN_DEVICENO] INT NOT NULL,
    [SCAN_CLOSEDATE] DATETIME2(3) NULL,
    [SCAN_CREATEDON] DATETIME2(3) NULL,
    [SCAN_DEVICEID] BIGINT NULL,
    [SCAN_FLAG] CHAR(1) NULL,
    CONSTRAINT [PK_SCAN_LOTMAST] PRIMARY KEY ([SCAN_LOTNO])
);
GO

-- ==========================================
-- ENV_DET - Envelope Details
-- ==========================================
IF OBJECT_ID('[ENV_DET]', 'U') IS NOT NULL DROP TABLE [ENV_DET];
GO
CREATE TABLE [ENV_DET] (
    [ENV_DETID] BIGINT NOT NULL,
    [ENV_ID] BIGINT NOT NULL,
    [ENV_TYPE] CHAR(3) NOT NULL,
    [ENV_DOCID] INT NOT NULL,
    [ENV_CREATEDBY] BIGINT NOT NULL,
    [ENV_CREATEDON] DATETIME2(3) NOT NULL,
    [ENV_RECEIVEFLAG] CHAR(1) NOT NULL,
    [ENV_RECEIVEDBY] BIGINT NOT NULL,
    [ENV_RECEIVEDON] DATETIME2(3) NOT NULL,
    [ENV_CANCELDATE] DATETIME2(3) NOT NULL,
    [ENV_CANCELBY] BIGINT NOT NULL,
    CONSTRAINT [PK_ENV_DET] PRIMARY KEY ([ENV_DETID])
);
GO

-- ==========================================
-- ENV_RECDET - Envelope Receipt Details
-- ==========================================
IF OBJECT_ID('[ENV_RECDET]', 'U') IS NOT NULL DROP TABLE [ENV_RECDET];
GO
CREATE TABLE [ENV_RECDET] (
    [REC_ID] BIGINT NOT NULL,
    [REC_ENVID] BIGINT NOT NULL,
    [REC_DOCID] BIGINT NOT NULL,
    [REC_UPDATEDBY] BIGINT NOT NULL,
    [REC_UPDATEDON] DATETIME2(3) NOT NULL,
    [REC_ENVTYPE] CHAR(3) NULL,
    [REC_SCANLOCATIONID] BIGINT NULL,
    CONSTRAINT [PK_ENV_RECDET] PRIMARY KEY ([REC_ID])
);
GO

PRINT 'BATCH_AND_ENVELOPE_MODULE Schema created successfully.';
GO
