-- ==========================================
-- Module: CashManagement
-- Purpose: Cash Transactions and Bank Reconciliation
-- Created: March 9, 2026
-- Database: CASHDB
-- ==========================================

USE CASHDB;
GO

-- =====================================================
-- CREATE TABLES FOR CASH MANAGEMENT MODULE
-- =====================================================

-- Table: CASH_UNIT - Cash Management Unit (Petty Cash, Till, etc.)
CREATE TABLE [CASH_UNIT] (
    [CASH_UNIT_ID] BIGINT NOT NULL  -- Cash Unit ID,
    [CASH_UNIT_NAME] VARCHAR(100) NOT NULL  -- Cash Unit Name,
    [CASH_UNIT_CODE] VARCHAR(20) NOT NULL  -- Cash Unit Code,
    [CASH_UNIT_LOCATION] VARCHAR(100) NULL  -- Location,
    [CASH_UNIT_INCHARGE] BIGINT NULL  -- In-charge Employee ID,
    [CASH_UNIT_OPENINGBAL] DECIMAL(19,0) NULL  -- Opening Balance,
    [CASH_UNIT_STATUS] CHAR(1) NOT NULL DEFAULT 'A'  -- A - Active, I - Inactive,
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL,
    [UPDATED_BY] BIGINT NULL,
    [UPDATED_ON] DATETIME2(3) NULL,
    CONSTRAINT [PK_CASH_UNIT] PRIMARY KEY ([CASH_UNIT_ID])
);

-- Table: CASH_TRANSACTION - Cash Transaction Records
CREATE TABLE [CASH_TRANSACTION] (
    [CASH_TXN_ID] BIGINT NOT NULL IDENTITY(1,1)  -- Transaction ID,
    [CASH_UNIT_ID] BIGINT NOT NULL  -- Cash Unit ID,
    [CASH_TXN_TYPE] CHAR(1) NOT NULL  -- R - Receipt, D - Disbursement,
    [CASH_TXN_AMOUNT] DECIMAL(19,0) NOT NULL  -- Transaction Amount,
    [CASH_TXN_SOURCE] VARCHAR(100) NULL  -- Source of Transaction,
    [CASH_TXN_PAYEE_ID] BIGINT NULL  -- Payee ID,
    [CASH_TXN_REF_NO] VARCHAR(50) NULL  -- Reference Number,
    [CASH_TXN_DATE] DATETIME2(3) NOT NULL  -- Transaction Date,
    [CASH_TXN_REMARKS] VARCHAR(500) NULL  -- Remarks,
    [CASH_TXN_STATUS] CHAR(1) NOT NULL  -- P - Posted, H - Hold,
    [AUTHORIZED_BY] BIGINT NULL  -- Authorized By,
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_CASH_TRANSACTION] PRIMARY KEY ([CASH_TXN_ID]),
    CONSTRAINT [FK_CASH_TRANSACTION_UNIT] FOREIGN KEY ([CASH_UNIT_ID]) REFERENCES [CASH_UNIT]([CASH_UNIT_ID])
);

-- Table: BANK_ACCOUNT - Bank Account Details
CREATE TABLE [BANK_ACCOUNT] (
    [BANK_ACCOUNT_ID] BIGINT NOT NULL  -- Bank Account ID,
    [BANK_NAME] VARCHAR(100) NOT NULL  -- Bank Name,
    [BANK_ACCOUNT_NO] VARCHAR(20) NOT NULL  -- Account Number,
    [BANK_BRANCH] VARCHAR(100) NULL  -- Branch Name,
    [BANK_ACCOUNT_TYPE] VARCHAR(20) NULL  -- Savings, Current, etc.,
    [BANK_ACCOUNT_STATUS] CHAR(1) NOT NULL DEFAULT 'A'  -- A - Active, I - Inactive,
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL,
    [UPDATED_BY] BIGINT NULL,
    [UPDATED_ON] DATETIME2(3) NULL,
    CONSTRAINT [PK_BANK_ACCOUNT] PRIMARY KEY ([BANK_ACCOUNT_ID])
);

-- Table: BANK_TRANSACTION - Bank Transaction Records
CREATE TABLE [BANK_TRANSACTION] (
    [BANK_TXN_ID] BIGINT NOT NULL IDENTITY(1,1)  -- Transaction ID,
    [BANK_ACCOUNT_ID] BIGINT NOT NULL  -- Bank Account ID,
    [BANK_TXN_TYPE] CHAR(1) NOT NULL  -- D - Deposit, W - Withdrawal,
    [BANK_TXN_AMOUNT] DECIMAL(19,0) NOT NULL  -- Transaction Amount,
    [BANK_TXN_DATE] DATETIME2(3) NOT NULL  -- Transaction Date,
    [BANK_TXN_REFERENCE] VARCHAR(50) NULL  -- Reference Number,
    [BANK_TXN_REMARKS] VARCHAR(500) NULL  -- Remarks,
    [BANK_TXN_STATUS] CHAR(1) NOT NULL  -- P - Posted, H - Hold,
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_BANK_TRANSACTION] PRIMARY KEY ([BANK_TXN_ID]),
    CONSTRAINT [FK_BANK_TRANSACTION_ACCOUNT] FOREIGN KEY ([BANK_ACCOUNT_ID]) REFERENCES [BANK_ACCOUNT]([BANK_ACCOUNT_ID])
);

-- Table: CHEQUE_REGISTER - Cheque Tracking
CREATE TABLE [CHEQUE_REGISTER] (
    [CHEQUE_ID] BIGINT NOT NULL IDENTITY(1,1)  -- Cheque ID,
    [BANK_ACCOUNT_ID] BIGINT NOT NULL  -- Bank Account ID,
    [CHEQUE_NUMBER] VARCHAR(20) NOT NULL  -- Cheque Number,
    [PAYEE_NAME] VARCHAR(100) NOT NULL  -- Payee Name,
    [CHEQUE_AMOUNT] DECIMAL(19,0) NOT NULL  -- Cheque Amount,
    [CHEQUE_ISSUE_DATE] DATE NOT NULL  -- Date Cheque Issued,
    [CHEQUE_DATE] DATE NOT NULL  -- Cheque Date,
    [CHEQUE_REFERENCE] VARCHAR(100) NULL  -- Reference,
    [CHEQUE_STATUS] CHAR(1) NOT NULL  -- I - Issued, C - Cleared, B - Bounced, X - Cancelled,
    [CHEQUE_BOUNCE_REASON] VARCHAR(200) NULL  -- Bounce Reason,
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL,
    [UPDATED_BY] BIGINT NULL,
    [UPDATED_ON] DATETIME2(3) NULL,
    CONSTRAINT [PK_CHEQUE_REGISTER] PRIMARY KEY ([CHEQUE_ID]),
    CONSTRAINT [FK_CHEQUE_REGISTER_ACCOUNT] FOREIGN KEY ([BANK_ACCOUNT_ID]) REFERENCES [BANK_ACCOUNT]([BANK_ACCOUNT_ID]),
    CONSTRAINT [UQ_CHEQUE_REGISTER] UNIQUE ([BANK_ACCOUNT_ID], [CHEQUE_NUMBER])
);

-- Table: BANK_RECONCILIATION - Bank Reconciliation Records
CREATE TABLE [BANK_RECONCILIATION] (
    [RECON_ID] BIGINT NOT NULL IDENTITY(1,1)  -- Reconciliation ID,
    [BANK_ACCOUNT_ID] BIGINT NOT NULL  -- Bank Account ID,
    [BANK_STATEMENT_BALANCE] DECIMAL(19,0) NOT NULL  -- Bank Statement Balance,
    [LEDGER_BALANCE] DECIMAL(19,0) NOT NULL  -- Ledger Balance,
    [UNCLEARED_CHEQUES] DECIMAL(19,0) NULL  -- Uncleared Cheques Total,
    [DIFFERENCE_AMOUNT] DECIMAL(19,0) NULL  -- Difference Amount,
    [RECONCILIATION_STATUS] VARCHAR(10) NULL  -- R - Reconciled, D - Difference Found,
    [RECONCILIATION_DATE] DATE NOT NULL,
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_BANK_RECONCILIATION] PRIMARY KEY ([RECON_ID]),
    CONSTRAINT [FK_BANK_RECONCILIATION_ACCOUNT] FOREIGN KEY ([BANK_ACCOUNT_ID]) REFERENCES [BANK_ACCOUNT]([BANK_ACCOUNT_ID])
);

-- Table: CHEQUE_REGISTER_AUDIT - Cheque Audit Trail
CREATE TABLE [CHEQUE_REGISTER_AUDIT] (
    [AUDIT_ID] BIGINT NOT NULL IDENTITY(1,1)  -- Audit ID,
    [CHEQUE_ID] BIGINT NOT NULL  -- Cheque ID,
    [BANK_ACCOUNT_ID] BIGINT NOT NULL,
    [CHEQUE_NUMBER] VARCHAR(20) NOT NULL,
    [PREVIOUS_STATUS] VARCHAR(10) NULL,
    [NEW_STATUS] VARCHAR(10) NOT NULL,
    [AUDIT_ACTION] VARCHAR(10) NOT NULL  -- INSERT / UPDATE,
    [AUDIT_DATE] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_CHEQUE_REGISTER_AUDIT] PRIMARY KEY ([AUDIT_ID])
);

-- =====================================================
-- CREATE INDEXES
-- =====================================================

CREATE INDEX [IX_CASH_TRANSACTION_UNIT_DATE] ON [CASH_TRANSACTION] ([CASH_UNIT_ID], [CASH_TXN_DATE]);
CREATE INDEX [IX_CASH_TRANSACTION_TYPE] ON [CASH_TRANSACTION] ([CASH_TXN_TYPE]);
CREATE INDEX [IX_BANK_TRANSACTION_ACCOUNT_DATE] ON [BANK_TRANSACTION] ([BANK_ACCOUNT_ID], [BANK_TXN_DATE]);
CREATE INDEX [IX_BANK_TRANSACTION_TYPE] ON [BANK_TRANSACTION] ([BANK_TXN_TYPE]);
CREATE INDEX [IX_CHEQUE_REGISTER_ACCOUNT] ON [CHEQUE_REGISTER] ([BANK_ACCOUNT_ID]);
CREATE INDEX [IX_CHEQUE_REGISTER_STATUS] ON [CHEQUE_REGISTER] ([CHEQUE_STATUS]);
CREATE INDEX [IX_BANK_RECONCILIATION_ACCOUNT] ON [BANK_RECONCILIATION] ([BANK_ACCOUNT_ID]);

-- =====================================================
-- VERIFICATION
-- =====================================================

PRINT 'CashManagement Module Schema created successfully.';
GO

-- Verify table creation
IF OBJECT_ID('CASH_UNIT', 'U') IS NOT NULL
    PRINT 'Table CASH_UNIT: OK'
ELSE
    PRINT 'Table CASH_UNIT: FAILED'
GO

IF OBJECT_ID('CASH_TRANSACTION', 'U') IS NOT NULL
    PRINT 'Table CASH_TRANSACTION: OK'
ELSE
    PRINT 'Table CASH_TRANSACTION: FAILED'
GO

IF OBJECT_ID('BANK_ACCOUNT', 'U') IS NOT NULL
    PRINT 'Table BANK_ACCOUNT: OK'
ELSE
    PRINT 'Table BANK_ACCOUNT: FAILED'
GO

IF OBJECT_ID('BANK_TRANSACTION', 'U') IS NOT NULL
    PRINT 'Table BANK_TRANSACTION: OK'
ELSE
    PRINT 'Table BANK_TRANSACTION: FAILED'
GO

IF OBJECT_ID('CHEQUE_REGISTER', 'U') IS NOT NULL
    PRINT 'Table CHEQUE_REGISTER: OK'
ELSE
    PRINT 'Table CHEQUE_REGISTER: FAILED'
GO

IF OBJECT_ID('BANK_RECONCILIATION', 'U') IS NOT NULL
    PRINT 'Table BANK_RECONCILIATION: OK'
ELSE
    PRINT 'Table BANK_RECONCILIATION: FAILED'
GO

IF OBJECT_ID('CHEQUE_REGISTER_AUDIT', 'U') IS NOT NULL
    PRINT 'Table CHEQUE_REGISTER_AUDIT: OK'
ELSE
    PRINT 'Table CHEQUE_REGISTER_AUDIT: FAILED'
GO
