-- ==========================================
-- PROJECT Module - Table Scripts  
-- Database: MYWORKDB
-- Module: PROJECT
-- Description: Project Management and Planning Module
-- Created: March 9, 2026
-- ==========================================

USE MYWORKDB;
GO

-- =====================================================
-- PROJECT Core Tables
-- =====================================================

-- Table: PROJECT_MAIN - PROJECT MAIN
CREATE TABLE [PROJECT_MAIN] (
    [PROJ_ID] BIGINT NOT NULL  -- Project ID,
    [PROJ_NAME] VARCHAR(50) NOT NULL,
    [PROJ_CHARTERNO] DECIMAL(50,0) NOT NULL  -- Charter No,
    [PROJ_LEADERID] BIGINT NOT NULL  -- Project Leader ID,
    [PROJ_TYPEID] BIGINT NOT NULL  -- Project Type ID,
    [PROJ_LOCID] BIGINT NOT NULL  -- Location ID,
    [PROJ_PROCESSID] BIGINT NOT NULL  -- Process ID,
    [PROJ_STARTDATE] DATETIME2(3) NOT NULL  -- Start Date,
    [PROJ_ENDDATE] DATETIME2(3) NOT NULL  -- ENd DATE,
    [PROJ_ESTENDDATE] DATETIME2(3) NOT NULL  -- Planned End Date,
    [PROJ_STATUS] CHAR(1) NOT NULL  -- estimated End Date,
    [PROJ_REVNO] INT NOT NULL  -- Revision No,
    [PROJ_VERNO] INT NOT NULL  -- Version No,
    [PROJ_OBJID] BIGINT NULL  -- Objective ID,
    [PROJ_OBJDESC] VARCHAR(150) NULL  -- Objective Description,
    [PROJ_TARGETPROD] VARCHAR(50) NULL  -- Target Production,
    [PROJ_TARGETPRODREM] VARCHAR(150) NULL  -- Target Production  Remarks,
    [PROJ_TARGETSPECFILE] VARCHAR(150) NULL  -- Target Product Specification File,
    [PROJ_TARGETSPECREM] VARCHAR(150) NULL  -- Target Product Specification Remarks,
    [PROJ_TARGETYIELDFILE] VARCHAR(150) NULL  -- Target Yield File,
    [PROJ_TARGETYIELDREM] VARCHAR(150) NULL  -- Target Yield Remarks,
    [PROJ_NOTES] VARCHAR(2000) NULL  -- Notes,
    [PROJ_ACTUALPROD] VARCHAR(50) NULL  -- Actual Production,
    [PROJ_ACTUALPRODREM] VARCHAR(150) NULL  -- Actual Production  Remarks,
    [PROJ_ACTUALSPECFILE] VARCHAR(150) NULL  -- Actual Product Specification File,
    [PROJ_ACTUALSPECREM] VARCHAR(150) NULL  -- Actual Product Specification Remarks,
    [PROJ_ACTUALYIELDFILE] VARCHAR(150) NULL  -- Actual Yield File,
    [PROJ_ACTUALYIELDREM] VARCHAR(150) NULL  -- Actual Yield Remarks,
    [PROJ_CLSDATE] DATETIME2(3) NULL  -- Closed On,
    [PROJ_LASTMODIFIEDON] DATETIME2(3) NULL,
    [PROJ_APPEMPSYSID] DECIMAL(38) NULL,
    [PROJ_PLANFILE] VARCHAR(150) NULL  -- Project Plan File,
    [PROJ_TARGETLBL1] VARCHAR(100) NULL  -- Target Label text1,
    [PROJ_TARGETLBL2] VARCHAR(100) NULL  -- Target Label text2,
    [PROJ_TARGETLBL3] VARCHAR(100) NULL  -- Target Label text3,
    [PROJ_PPTXFILE] VARCHAR(150) NULL,
    CONSTRAINT [PK_PROJECT_MAIN] PRIMARY KEY ([PROJ_ID])
);

-- Table: PROJECT_MASTER - PROJECT MASTER
CREATE TABLE [PROJECT_MASTER] (
    [PROJECT_ID] BIGINT NOT NULL,
    [PROJECT_NAME] VARCHAR(200) NOT NULL,
    [PROJECT_CATEGORYID] BIGINT NOT NULL,
    [PROJECT_EFFDATE] DATETIME2(3) NOT NULL,
    [PROJECT_CLSDATE] DATETIME2(3) NULL,
    [PROJECT_TEAMID] DECIMAL(38) NOT NULL,
    [PROJECT_LISTALL] CHAR(1) NOT NULL,
    [PROJECT_LASTMODIFIEDBY] BIGINT NOT NULL,
    [PROJECT_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_PROJECT_MASTER] PRIMARY KEY ([PROJECT_ID])
);

-- Table: PROJECT_MEMBERS - PROJECT MEMBERS
CREATE TABLE [PROJECT_MEMBERS] (
    [PROJMEM_ID] BIGINT NOT NULL,
    [PROJMEM_PROJID] BIGINT NOT NULL,
    [PROJMEM_FUNCID] BIGINT NOT NULL,
    [PROJMEM_EMPSYSID] BIGINT NOT NULL,
    CONSTRAINT [PK_PROJECT_MEMBERS] PRIMARY KEY ([PROJMEM_ID])
);

-- Table: PROJECT_SCOPE - PROJECT SCOPE
CREATE TABLE [PROJECT_SCOPE] (
    [PROJSCOPE_ID] BIGINT NOT NULL  -- ProjectScope ID,
    [PROJSCOPE_PROJID] BIGINT NOT NULL  -- Project ID,
    [PROJSCOPE_SCOPEID] BIGINT NOT NULL  -- Scope Description,
    CONSTRAINT [PK_PROJECT_SCOPE] PRIMARY KEY ([PROJSCOPE_ID])
);

-- Table: PROJECT_STATUS - PROJECT STATUS
CREATE TABLE [PROJECT_STATUS] (
    [PROJSTATUS_ID] BIGINT NOT NULL  -- Status ID,
    [PROJSTATUS_PROJID] BIGINT NOT NULL  -- Project ID,
    [PROJSTATUS_FILE] VARCHAR(150) NULL  -- Status File,
    [PROJSTATUS_DATE] DATETIME2(3) NOT NULL  -- Status updated on,
    [PROJSTATUS_REM] VARCHAR(150) NOT NULL  -- Status remarks,
    [PROJSTATUS_REVNO] BIGINT NOT NULL  -- Revision No,
    [PROJSTATUS_VERNO] BIGINT NOT NULL  -- VERSION No,
    CONSTRAINT [PK_PROJECT_STATUS] PRIMARY KEY ([PROJSTATUS_ID])
);

-- Table: PROJECT_ADDLDEL - project add del
CREATE TABLE [PROJECT_ADDLDEL] (
    [PROJADLDEL_ID] BIGINT NOT NULL  -- Additional Project Deliverable ID,
    [PROJADLDEL_PROJID] BIGINT NOT NULL  -- Project ID,
    [PROJADLDEL_DESC] VARCHAR(50) NOT NULL  -- Additional Project Deliverable Description,
    CONSTRAINT [PK_PROJECT_ADDLDEL] PRIMARY KEY ([PROJADLDEL_ID])
);

-- Table: PROJECT_ADDLSCOPE - project scope
CREATE TABLE [PROJECT_ADDLSCOPE] (
    [PROJADSCOPE_ID] BIGINT NOT NULL  -- Project Additional Scope ID,
    [PROJADSCOPE_PROJID] BIGINT NOT NULL  -- Project ID,
    [PROJADSCOPE_DESC] VARCHAR(50) NOT NULL  -- Scope Description,
    CONSTRAINT [PK_PROJECT_ADDLSCOPE] PRIMARY KEY ([PROJADSCOPE_ID])
);

-- Table: PROJECT_APPRDETAILS - project appr details
CREATE TABLE [PROJECT_APPRDETAILS] (
    [PROJ_APPRID] BIGINT NOT NULL  -- Project Appr Id,
    [PROJ_APPRPROJID] BIGINT NOT NULL  -- Project Id,
    [PROJ_APPRTYPE] CHAR(1) NOT NULL  -- App type C- CharterClose A- CharterApproval D-Drop,
    [PROJ_APPRSENTON] DATETIME2(3) NOT NULL  -- Request Sent On,
    [PROJ_APPEMPSYSID] BIGINT NOT NULL  -- Approver EmpsysId,
    [PROJ_APPRAPPDATE] DATETIME2(3) NOT NULL  -- Approver date,
    [PROJ_APPRSTATUS] CHAR(1) NOT NULL  -- 'P'/'A' /'R' -Pending For Approval /Approved /Rejected,
    [PROJ_APPREMARKS] VARCHAR(150) NOT NULL  -- Approver Remarks,
    [PROJ_APPRDROPREMARKS] VARCHAR(150) NOT NULL  -- Drop Remarks,
    CONSTRAINT [PK_PROJECT_APPRDETAILS] PRIMARY KEY ([PROJ_APPRID])
);

-- Table: PROJECT_DEL - project delt
CREATE TABLE [PROJECT_DEL] (
    [PROJDEL_ID] BIGINT NOT NULL  -- Project ID,
    [PROJDEL_PROJID] BIGINT NOT NULL  -- Project Deliverable ID,
    [PROJDEL_DELID] BIGINT NOT NULL  -- Deliverable ID,
    CONSTRAINT [PK_PROJECT_DEL] PRIMARY KEY ([PROJDEL_ID])
);

-- Table: PROJECT_EMPMAP - project emp map
CREATE TABLE [PROJECT_EMPMAP] (
    [PROJEMP_ID] BIGINT NOT NULL  -- Project Employee ID,
    [PROJEMP_PROJECTID] BIGINT NOT NULL  -- Project ID,
    [PROJEMP_EMPSYSID] BIGINT NOT NULL  -- Employee System ID,
    [PROJEMP_LASTMODIFIEDBY] BIGINT NOT NULL  -- last modified by,
    [PROJEMP_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- last modified on,
    [PROJEMP_EFFDATE] DATETIME2(3) NOT NULL  -- Effective date,
    [PROJEMP_CLOSEDATE] DATETIME2(3) NOT NULL  -- close date,
    CONSTRAINT [PK_PROJECT_EMPMAP] PRIMARY KEY ([PROJEMP_ID])
);

-- Table: PROJECT_HOLD - project hold
CREATE TABLE [PROJECT_HOLD] (
    [PROJHOLD_ID] BIGINT NOT NULL  -- Hold ID,
    [PROJHOLD_PROJID] BIGINT NOT NULL  -- Project ID,
    [PROJHOLD_TYPE] CHAR(1) NOT NULL  -- Hold / Unhold (H/U),
    [PROJHOLD_DATE] DATETIME2(3) NOT NULL  -- Hold/Unhold Date,
    [PROJHOLD_REASON] VARCHAR(150) NOT NULL  -- Reason for Hold/Unhold,
    [PROJHOLD_UPDATEDBY] BIGINT NOT NULL  -- Updated by,
    [PROJHOLD_UPDATEDON] DATETIME2(3) NOT NULL  -- Updated on,
    CONSTRAINT [PK_PROJECT_HOLD] PRIMARY KEY ([PROJHOLD_ID])
);

-- =====================================================
-- PROJECT TYPE and CATEGORY Tables
-- =====================================================

-- Table: PROJECTCAT_MASTER - project cat master
CREATE TABLE [PROJECTCAT_MASTER] (
    [CATEGORY_ID] BIGINT NOT NULL  -- Category ID,
    [CATEGORY_NAME] VARCHAR(200) NOT NULL  -- Category Name,
    [CATEGORY_TEAMID] BIGINT NOT NULL  -- Time Sheet Team ID,
    [CATEGORY_LASTMODIFIEDBY] BIGINT NOT NULL,
    [CATEGORY_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_PROJECTCAT_MASTER] PRIMARY KEY ([CATEGORY_ID])
);

-- Table: PROJTYPE_MAST - PROJECT TYPE MASTER
CREATE TABLE [PROJTYPE_MAST] (
    [PROJTYPE_ID] DECIMAL(38) NOT NULL  -- Project Type ID,
    [PROJTYPE_NAME] VARCHAR(50) NOT NULL  -- Project Type NAME,
    [PROJTYPE_CODE] VARCHAR(50) NOT NULL  -- Project Type CODE,
    [PROJTYPE_DEPID] DECIMAL(38) NOT NULL  -- Project Type DEPTID,
    [PROJTYPE_CATID] DECIMAL(38) NOT NULL  -- Project Type CATID,
    [PROJTYPE_MODIFIEDBY] DECIMAL(38) NULL,
    [PROJTYPE_MODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_PROJTYPE_MAST] PRIMARY KEY ([PROJTYPE_ID])
);

-- Table: PROJTYPE_CATEGORYMAST - project category master
CREATE TABLE [PROJTYPE_CATEGORYMAST] (
    [PROJCAT_ID] BIGINT NOT NULL  -- Project Category ID,
    [PROJCAT_NAME] VARCHAR(50) NOT NULL  -- Project Category name,
    [PROJCAT_UPDATEDBY] BIGINT NOT NULL  -- last Updated By,
    [PROJCAT_UPDATEDON] DATETIME2(3) NOT NULL  -- last Updated on,
    CONSTRAINT [PK_PROJTYPE_CATEGORYMAST] PRIMARY KEY ([PROJCAT_ID])
);

-- Table: PROJTYPE_DELMAP - project type del map
CREATE TABLE [PROJTYPE_DELMAP] (
    [DEL_ID] BIGINT NOT NULL  -- Deliverable ID,
    [DEL_PROJTYPEID] BIGINT NOT NULL  -- Deliverable Project Type ID,
    [DEL_DESC] VARCHAR(500) NOT NULL  -- Deliverable Description,
    [DEL_MODIFIEDBY] DECIMAL(38) NOT NULL,
    [DEL_MODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_PROJTYPE_DELMAP] PRIMARY KEY ([DEL_ID])
);

-- Table: PROJTYPE_FINYEARSEQ - PROJECT TYPE REQ
CREATE TABLE [PROJTYPE_FINYEARSEQ] (
    [PROJTYPE_ID] BIGINT NOT NULL,
    [PROJTYPE_YEAR] INT NOT NULL,
    [PROJTYPE_SEQ] BIGINT NOT NULL,
    CONSTRAINT [PK_PROJTYPE_FINYEARSEQ] PRIMARY KEY ([PROJTYPE_ID])
);

-- Table: PROJTYPE_OBJMAP - PROJECT OBJ MAP
CREATE TABLE [PROJTYPE_OBJMAP] (
    [OBJ_ID] BIGINT NOT NULL  -- Objective Serial ID,
    [OBJ_PROJTYPEID] BIGINT NOT NULL  -- Project Type ID,
    [OBJ_DESC] VARCHAR(500) NOT NULL  -- Objective Decription,
    [OBJ_MODIFIEDBY] DECIMAL(38) NOT NULL,
    [OBJ_MODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_PROJTYPE_OBJMAP] PRIMARY KEY ([OBJ_ID])
);

-- Table: PROJTYPE_SCOPEMAP - project scope map
CREATE TABLE [PROJTYPE_SCOPEMAP] (
    [SCOPE_ID] BIGINT NOT NULL  -- Scope ID,
    [SCOPE_PROJTYPEID] BIGINT NOT NULL  -- Scope Project Type ID,
    [SCOPE_DESC] VARCHAR(500) NOT NULL  -- Scope Description,
    [SCOPE_MODIFIEDBY] DECIMAL(38) NOT NULL,
    [SCOPE_MODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_PROJTYPE_SCOPEMAP] PRIMARY KEY ([SCOPE_ID])
);

-- =====================================================
-- PROJECT SUPPORTING Tables
-- =====================================================

-- Table: PROJDEP_MAST - project dept master
CREATE TABLE [PROJDEP_MAST] (
    [PROJDEP_ID] DECIMAL(38) NOT NULL,
    [PROJDEP_NAME] VARCHAR(50) NOT NULL,
    [PROJDEP_CODE] VARCHAR(50) NOT NULL,
    [PROJDEP_LASTMODIFIEDBY] BIGINT NOT NULL,
    [PROJDEP_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_PROJDEP_MAST] PRIMARY KEY ([PROJDEP_ID])
);

-- Table: PROJLOC_MAST - project location map
CREATE TABLE [PROJLOC_MAST] (
    [LOC_ID] BIGINT NOT NULL  -- Location ID,
    [LOC_NAME] VARCHAR(250) NOT NULL  -- Location name,
    [LOC_LASTMODIFIEDBY] BIGINT NOT NULL,
    [LOC_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_PROJLOC_MAST] PRIMARY KEY ([LOC_ID])
);

-- Table: PROJPROC_MAST - project master
CREATE TABLE [PROJPROC_MAST] (
    [PROC_ID] BIGINT NOT NULL  -- Process ID,
    [PROC_NAME] VARCHAR(50) NOT NULL  -- Process name,
    [PROC_LASTMODIFIEDBY] BIGINT NOT NULL,
    [PROC_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_PROJPROC_MAST] PRIMARY KEY ([PROC_ID])
);

-- Table: PROJFUNC_MAST - project func master
CREATE TABLE [PROJFUNC_MAST] (
    [PROJFUNC_ID] BIGINT NOT NULL  -- Project Functional ID,
    [PROJFUNC_NAME] VARCHAR(50) NOT NULL  -- Project Functional name,
    [PROJFUNC_LASTMODIFIEDBY] BIGINT NOT NULL,
    [PROJFUNC_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_PROJFUNC_MAST] PRIMARY KEY ([PROJFUNC_ID])
);

-- Table: PROJFUNCEMP_MAP - project funct emp
CREATE TABLE [PROJFUNCEMP_MAP] (
    [PROJFUNCEMP_MAPID] BIGINT NOT NULL  -- Project Function Employee Map Id,
    [PROJFUNCEMP_MAPFUNCID] BIGINT NOT NULL  -- Function Id,
    [PROJFUNCEMP_MAPEMPSYSID] BIGINT NOT NULL  -- Employee SysId,
    [PROJFUNCEMP_UPDATEDBY] BIGINT NOT NULL,
    [PROJFUNCEMP_UPDATEDON] DATETIME2(3) NOT NULL,
    [PROJFUNCEMP_LIVEFLAG] CHAR(1) NOT NULL,
    CONSTRAINT [PK_PROJFUNCEMP_MAP] PRIMARY KEY ([PROJFUNCEMP_MAPID])
);

-- Table: PROJTYPEFUNC_MAP - project type function
CREATE TABLE [PROJTYPEFUNC_MAP] (
    [PROJTYPEFUNC_MAPID] BIGINT NOT NULL  -- Project Type Function Map Id,
    [PROJTYPEFUNC_TYPEID] BIGINT NOT NULL  -- Project Type,
    [PROJTYPEFUNC_FUNCID] BIGINT NOT NULL  -- Project Function Id,
    [PROJTYPEFUNC_ADDLNO] BIGINT NOT NULL  -- Additional Members,
    [PROJTYPEFUNC_UPDATEDBY] BIGINT NOT NULL  -- Updated By,
    [PROJTYPEFUNC_UPDATEDON] DATETIME2(3) NOT NULL  -- Updated on,
    CONSTRAINT [PK_PROJTYPEFUNC_MAP] PRIMARY KEY ([PROJTYPEFUNC_MAPID])
);

-- Table: PROJ_ACCESS - project access
CREATE TABLE [PROJ_ACCESS] (
    [PROJACC_ID] BIGINT NOT NULL,
    [PROJACC_EMPSYSID] BIGINT NOT NULL,
    [PROJACC_TYPE] CHAR(1) NOT NULL,
    [PROJACC_DEPID] BIGINT NOT NULL
);

PRINT 'PROJECT Module - Tables created successfully.';
GO
