-- ==========================================
-- WebsiteContentModule
-- Database: SRFSPARSHDB
-- Module Purpose: Website Content and News Management
-- Created: March 09, 2026
-- ==========================================

USE SRFSPARSHDB;
GO

-- Drop tables if they exist (reverse order for dependencies)
IF OBJECT_ID('[WEBSITE_NEWS]', 'U') IS NOT NULL DROP TABLE [WEBSITE_NEWS];
GO
IF OBJECT_ID('[WEBSITE_PAGES]', 'U') IS NOT NULL DROP TABLE [WEBSITE_PAGES];
GO

-- ==========================================
-- Table: WEBSITE_PAGES - Website Pages
-- Description: Static pages and content for website
-- ==========================================
CREATE TABLE [WEBSITE_PAGES] (
    [PAGE_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [PAGE_CODE] VARCHAR(100) NOT NULL UNIQUE,
    [PAGE_TITLE] VARCHAR(255) NOT NULL,
    [PAGE_CONTENT] NVARCHAR(MAX),
    [META_DESCRIPTION] VARCHAR(500),
    [META_KEYWORDS] VARCHAR(500),
    [PAGE_ORDER] INT,
    [PARENT_PAGE_ID] BIGINT,
    [IS_PUBLISHED] CHAR(1) DEFAULT 'N',
    [PUBLISHED_DATE] DATETIME2(3),
    [PAGE_STATUS] VARCHAR(20) DEFAULT 'ACTIVE',
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [UPDATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3)
);
GO

-- ==========================================
-- Table: WEBSITE_NEWS - Website News and Announcements
-- Description: News and announcements published on website
-- ==========================================
CREATE TABLE [WEBSITE_NEWS] (
    [NEWS_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [NEWS_TITLE] VARCHAR(500) NOT NULL,
    [NEWS_CONTENT] NVARCHAR(MAX) NOT NULL,
    [NEWS_SUMMARY] VARCHAR(500),
    [NEWS_CATEGORY] VARCHAR(100),
    [FEATURED_IMAGE] VARCHAR(500),
    [IS_FEATURED] CHAR(1) DEFAULT 'N',
    [IS_PUBLISHED] CHAR(1) DEFAULT 'N',
    [PUBLISHED_DATE] DATETIME2(3),
    [PUBLISH_START_DATE] DATETIME2(3),
    [PUBLISH_END_DATE] DATETIME2(3),
    [NEWS_STATUS] VARCHAR(20) DEFAULT 'DRAFT', -- DRAFT, PUBLISHED, ARCHIVED
    [VIEW_COUNT] INT DEFAULT 0,
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [UPDATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3)
);
GO

-- Create Indexes
CREATE INDEX [IX_WEBSITE_PAGES_CODE] ON [WEBSITE_PAGES]([PAGE_CODE]);
CREATE INDEX [IX_WEBSITE_PAGES_STATUS] ON [WEBSITE_PAGES]([PAGE_STATUS]);
CREATE INDEX [IX_WEBSITE_PAGES_PUBLISHED] ON [WEBSITE_PAGES]([IS_PUBLISHED]);
CREATE INDEX [IX_WEBSITE_PAGES_PARENT] ON [WEBSITE_PAGES]([PARENT_PAGE_ID]);
CREATE INDEX [IX_WEBSITE_NEWS_CATEGORY] ON [WEBSITE_NEWS]([NEWS_CATEGORY]);
CREATE INDEX [IX_WEBSITE_NEWS_STATUS] ON [WEBSITE_NEWS]([NEWS_STATUS]);
CREATE INDEX [IX_WEBSITE_NEWS_PUBLISHED] ON [WEBSITE_NEWS]([IS_PUBLISHED]);
CREATE INDEX [IX_WEBSITE_NEWS_DATE] ON [WEBSITE_NEWS]([PUBLISHED_DATE]);
GO

PRINT 'WebsiteContentModule_Schema created successfully.';
GO
