-- ============================================================
-- SCI ERP Microservices - Initial Database Setup Script
-- For Docker SQL Server container initialization
-- ============================================================

-- Wait for SQL Server to be ready
WAITFOR DELAY '00:00:05';
GO

-- Create Database if not exists
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'SCIDB')
BEGIN
    CREATE DATABASE [SCIDB];
    PRINT 'Database SCIDB created successfully.';
END
ELSE
BEGIN
    PRINT 'Database SCIDB already exists.';
END
GO

USE [SCIDB];
GO

-- ============================================================
-- 01. SECURITY MODULE Tables
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ACCESS_ROLE')
CREATE TABLE [ACCESS_ROLE] (
    [RA_USR_COD] VARCHAR(25) NULL,
    [RA_USR_NUM] BIGINT NULL,
    [RA_ROL_COD] BIGINT NULL,
    [RA_UPD_USR] VARCHAR(25) NULL,
    [RA_UPD_NUM] BIGINT NULL,
    [RA_UPD_DAT] DATETIME2(3) NULL,
    [RA_STR_DAT] DATETIME2(3) NULL,
    [RA_END_DAT] DATETIME2(3) NULL
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ACCESS_ROLE_MASTER')
CREATE TABLE [ACCESS_ROLE_MASTER] (
    [AR_ROL_COD] BIGINT NULL,
    [AR_ROL_NAM] VARCHAR(200) NULL,
    [AR_UPD_USR] VARCHAR(25) NULL,
    [AR_UPD_NUM] BIGINT NULL,
    [AR_UPD_DAT] DATETIME2(3) NULL
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ACCESSROLE_MENU')
CREATE TABLE [ACCESSROLE_MENU] (
    [ARM_ROL_COD] BIGINT NULL,
    [ARM_MEN_COD] BIGINT NULL,
    [ARM_UPD_USR] VARCHAR(25) NULL,
    [ARM_UPD_NUM] BIGINT NULL,
    [ARM_UPD_DAT] DATETIME2(3) NULL
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SCI_MENU')
CREATE TABLE [SCI_MENU] (
    [MN_COD] BIGINT NULL,
    [MN_NAM] VARCHAR(200) NULL,
    [MN_DSC] VARCHAR(500) NULL,
    [MN_URL] VARCHAR(500) NULL,
    [MN_PAR_COD] BIGINT NULL,
    [MN_ORD] INT NULL,
    [MN_ICN] VARCHAR(100) NULL,
    [MN_STS] VARCHAR(1) NULL,
    [MN_UPD_USR] VARCHAR(25) NULL,
    [MN_UPD_NUM] BIGINT NULL,
    [MN_UPD_DAT] DATETIME2(3) NULL
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SCI_USER')
CREATE TABLE [SCI_USER] (
    [USR_NUM] BIGINT NOT NULL IDENTITY(1,1),
    [USR_COD] VARCHAR(25) NULL,
    [USR_NAM] VARCHAR(200) NULL,
    [USR_PWD] VARCHAR(500) NULL,
    [USR_EML] VARCHAR(200) NULL,
    [USR_PHN] VARCHAR(15) NULL,
    [USR_STS] VARCHAR(1) NULL,
    [USR_TYP] VARCHAR(10) NULL,
    [USR_UPD_USR] VARCHAR(25) NULL,
    [USR_UPD_NUM] BIGINT NULL,
    [USR_UPD_DAT] DATETIME2(3) NULL,
    CONSTRAINT [PK_SCI_USER] PRIMARY KEY ([USR_NUM])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SCI_USER_LOGIN')
CREATE TABLE [SCI_USER_LOGIN] (
    [UL_USR_NUM] BIGINT NULL,
    [UL_LGN_DAT] DATETIME2(3) NULL,
    [UL_LGT_DAT] DATETIME2(3) NULL,
    [UL_LGN_IP] VARCHAR(50) NULL,
    [UL_STS] VARCHAR(1) NULL
);
GO

-- ============================================================
-- 02. VEHICLE TRACKING MODULE Tables
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'VEHICLE_MASTER')
CREATE TABLE [VEHICLE_MASTER] (
    [VH_NUM] BIGINT NOT NULL IDENTITY(1,1),
    [VH_REG_NUM] VARCHAR(20) NULL,
    [VH_TYP] VARCHAR(50) NULL,
    [VH_CAP] DECIMAL(10,2) NULL,
    [VH_STS] VARCHAR(1) NULL,
    [VH_UPD_USR] VARCHAR(25) NULL,
    [VH_UPD_DAT] DATETIME2(3) NULL,
    CONSTRAINT [PK_VEHICLE_MASTER] PRIMARY KEY ([VH_NUM])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'VEHICLE_TRACKING')
CREATE TABLE [VEHICLE_TRACKING] (
    [VT_ID] BIGINT NOT NULL IDENTITY(1,1),
    [VT_VH_NUM] BIGINT NULL,
    [VT_LAT] DECIMAL(10,6) NULL,
    [VT_LNG] DECIMAL(10,6) NULL,
    [VT_SPD] DECIMAL(6,2) NULL,
    [VT_TRK_DAT] DATETIME2(3) NULL,
    [VT_STS] VARCHAR(1) NULL,
    CONSTRAINT [PK_VEHICLE_TRACKING] PRIMARY KEY ([VT_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'VEHICLE_DIRECT_ENTRY')
CREATE TABLE [VEHICLE_DIRECT_ENTRY] (
    [VDE_ID] BIGINT NOT NULL IDENTITY(1,1),
    [VDE_TRK_NUM] VARCHAR(50) NULL,
    [VDE_ENT_DAT] DATETIME2(3) NULL,
    [VDE_ENT_USR] VARCHAR(25) NULL,
    CONSTRAINT [PK_VEHICLE_DIRECT_ENTRY] PRIMARY KEY ([VDE_ID])
);
GO

-- ============================================================
-- 03. DISPATCH PLANNING MODULE Tables
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DISPATCH_PLAN')
CREATE TABLE [DISPATCH_PLAN] (
    [DP_ID] BIGINT NOT NULL IDENTITY(1,1),
    [DP_PLN_DAT] DATETIME2(3) NULL,
    [DP_VH_NUM] BIGINT NULL,
    [DP_RTE] VARCHAR(500) NULL,
    [DP_STS] VARCHAR(1) NULL,
    [DP_CRT_USR] VARCHAR(25) NULL,
    [DP_CRT_DAT] DATETIME2(3) NULL,
    CONSTRAINT [PK_DISPATCH_PLAN] PRIMARY KEY ([DP_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DISPATCH_DETAIL')
CREATE TABLE [DISPATCH_DETAIL] (
    [DD_ID] BIGINT NOT NULL IDENTITY(1,1),
    [DD_DP_ID] BIGINT NULL,
    [DD_ITM_COD] VARCHAR(50) NULL,
    [DD_QTY] DECIMAL(10,2) NULL,
    [DD_STS] VARCHAR(1) NULL,
    CONSTRAINT [PK_DISPATCH_DETAIL] PRIMARY KEY ([DD_ID])
);
GO

-- ============================================================
-- 04. ORDER SCHEDULING MODULE Tables
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ORDER_SCHEDULE')
CREATE TABLE [ORDER_SCHEDULE] (
    [OS_ID] BIGINT NOT NULL IDENTITY(1,1),
    [OS_ORD_NUM] VARCHAR(50) NULL,
    [OS_SCH_DAT] DATETIME2(3) NULL,
    [OS_PRD_COD] VARCHAR(50) NULL,
    [OS_QTY] DECIMAL(10,2) NULL,
    [OS_STS] VARCHAR(1) NULL,
    [OS_CRT_USR] VARCHAR(25) NULL,
    [OS_CRT_DAT] DATETIME2(3) NULL,
    CONSTRAINT [PK_ORDER_SCHEDULE] PRIMARY KEY ([OS_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ORDER_DETAIL')
CREATE TABLE [ORDER_DETAIL] (
    [OD_ID] BIGINT NOT NULL IDENTITY(1,1),
    [OD_OS_ID] BIGINT NULL,
    [OD_LIN_NUM] INT NULL,
    [OD_ITM_COD] VARCHAR(50) NULL,
    [OD_QTY] DECIMAL(10,2) NULL,
    [OD_PRC] DECIMAL(15,2) NULL,
    [OD_STS] VARCHAR(1) NULL,
    CONSTRAINT [PK_ORDER_DETAIL] PRIMARY KEY ([OD_ID])
);
GO

-- ============================================================
-- 05. FILLING OPERATIONS MODULE Tables
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'FILLING_OPERATION')
CREATE TABLE [FILLING_OPERATION] (
    [FO_ID] BIGINT NOT NULL IDENTITY(1,1),
    [FO_BTH_NUM] VARCHAR(50) NULL,
    [FO_PRD_COD] VARCHAR(50) NULL,
    [FO_QTY] DECIMAL(10,2) NULL,
    [FO_STR_DAT] DATETIME2(3) NULL,
    [FO_END_DAT] DATETIME2(3) NULL,
    [FO_STS] VARCHAR(1) NULL,
    [FO_CRT_USR] VARCHAR(25) NULL,
    CONSTRAINT [PK_FILLING_OPERATION] PRIMARY KEY ([FO_ID])
);
GO

-- ============================================================
-- 06. EXIM MANAGEMENT MODULE Tables  
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ADVLIC_MASTER')
CREATE TABLE [ADVLIC_MASTER] (
    [ADVLIC_ID] BIGINT NOT NULL IDENTITY(1,1),
    [ADVLIC_NUM] VARCHAR(50) NULL,
    [ADVLIC_DAT] DATETIME2(3) NULL,
    [ADVLIC_STS] VARCHAR(1) NULL,
    [ADVLIC_CRT_USR] VARCHAR(25) NULL,
    CONSTRAINT [PK_ADVLIC_MASTER] PRIMARY KEY ([ADVLIC_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ADVLIC_ENTITLEMENT')
CREATE TABLE [ADVLIC_ENTITLEMENT] (
    [ADVLIC_ID] BIGINT NOT NULL,
    [ADVLIC_ENTITLERM] INT NOT NULL,
    CONSTRAINT [PK_ADVLIC_ENTITLEMENT] PRIMARY KEY ([ADVLIC_ID], [ADVLIC_ENTITLERM])
);
GO

-- ============================================================
-- 07. GST COMPLIANCE MODULE Tables
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'GST_RETURN')
CREATE TABLE [GST_RETURN] (
    [GR_ID] BIGINT NOT NULL IDENTITY(1,1),
    [GR_TYP] VARCHAR(10) NULL,
    [GR_PRD] VARCHAR(10) NULL,
    [GR_YR] INT NULL,
    [GR_AMT] DECIMAL(15,2) NULL,
    [GR_STS] VARCHAR(1) NULL,
    [GR_FIL_DAT] DATETIME2(3) NULL,
    [GR_CRT_USR] VARCHAR(25) NULL,
    CONSTRAINT [PK_GST_RETURN] PRIMARY KEY ([GR_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'GST_INVOICE')
CREATE TABLE [GST_INVOICE] (
    [GI_ID] BIGINT NOT NULL IDENTITY(1,1),
    [GI_INV_NUM] VARCHAR(50) NULL,
    [GI_INV_DAT] DATETIME2(3) NULL,
    [GI_GSTIN] VARCHAR(15) NULL,
    [GI_AMT] DECIMAL(15,2) NULL,
    [GI_TAX_AMT] DECIMAL(15,2) NULL,
    [GI_STS] VARCHAR(1) NULL,
    CONSTRAINT [PK_GST_INVOICE] PRIMARY KEY ([GI_ID])
);
GO

-- ============================================================
-- 08. INVENTORY MANAGEMENT MODULE Tables
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'INVENTORY_MASTER')
CREATE TABLE [INVENTORY_MASTER] (
    [INV_ID] BIGINT NOT NULL IDENTITY(1,1),
    [INV_ITM_COD] VARCHAR(50) NULL,
    [INV_ITM_NAM] VARCHAR(200) NULL,
    [INV_QTY] DECIMAL(15,2) NULL,
    [INV_UOM] VARCHAR(10) NULL,
    [INV_LOC] VARCHAR(100) NULL,
    [INV_STS] VARCHAR(1) NULL,
    [INV_UPD_DAT] DATETIME2(3) NULL,
    CONSTRAINT [PK_INVENTORY_MASTER] PRIMARY KEY ([INV_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'INVENTORY_TRANSACTION')
CREATE TABLE [INVENTORY_TRANSACTION] (
    [IT_ID] BIGINT NOT NULL IDENTITY(1,1),
    [IT_INV_ID] BIGINT NULL,
    [IT_TXN_TYP] VARCHAR(10) NULL,
    [IT_QTY] DECIMAL(15,2) NULL,
    [IT_DAT] DATETIME2(3) NULL,
    [IT_REF_NUM] VARCHAR(50) NULL,
    [IT_CRT_USR] VARCHAR(25) NULL,
    CONSTRAINT [PK_INVENTORY_TRANSACTION] PRIMARY KEY ([IT_ID])
);
GO

-- ============================================================
-- 09. PRODUCTION MANAGEMENT MODULE Tables
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'PRODUCTION_BATCH')
CREATE TABLE [PRODUCTION_BATCH] (
    [PB_ID] BIGINT NOT NULL IDENTITY(1,1),
    [PB_BTH_NUM] VARCHAR(50) NULL,
    [PB_PRD_COD] VARCHAR(50) NULL,
    [PB_PLN_QTY] DECIMAL(15,2) NULL,
    [PB_ACT_QTY] DECIMAL(15,2) NULL,
    [PB_STR_DAT] DATETIME2(3) NULL,
    [PB_END_DAT] DATETIME2(3) NULL,
    [PB_STS] VARCHAR(1) NULL,
    [PB_CRT_USR] VARCHAR(25) NULL,
    CONSTRAINT [PK_PRODUCTION_BATCH] PRIMARY KEY ([PB_ID])
);
GO

-- ============================================================
-- 10. MAM ALLOCATION MODULE Tables
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'MAM_ALLOCATION')
CREATE TABLE [MAM_ALLOCATION] (
    [MA_ID] BIGINT NOT NULL IDENTITY(1,1),
    [MA_PRD_COD] VARCHAR(50) NULL,
    [MA_ALC_QTY] DECIMAL(15,2) NULL,
    [MA_ALC_DAT] DATETIME2(3) NULL,
    [MA_STS] VARCHAR(1) NULL,
    [MA_CRT_USR] VARCHAR(25) NULL,
    CONSTRAINT [PK_MAM_ALLOCATION] PRIMARY KEY ([MA_ID])
);
GO

-- ============================================================
-- 11. PURCHASE SALES MODULE Tables
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'PURCHASE_ORDER')
CREATE TABLE [PURCHASE_ORDER] (
    [PO_ID] BIGINT NOT NULL IDENTITY(1,1),
    [PO_NUM] VARCHAR(50) NULL,
    [PO_DAT] DATETIME2(3) NULL,
    [PO_VND_COD] VARCHAR(50) NULL,
    [PO_AMT] DECIMAL(15,2) NULL,
    [PO_STS] VARCHAR(1) NULL,
    [PO_CRT_USR] VARCHAR(25) NULL,
    CONSTRAINT [PK_PURCHASE_ORDER] PRIMARY KEY ([PO_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SALES_ORDER')
CREATE TABLE [SALES_ORDER] (
    [SO_ID] BIGINT NOT NULL IDENTITY(1,1),
    [SO_NUM] VARCHAR(50) NULL,
    [SO_DAT] DATETIME2(3) NULL,
    [SO_CST_COD] VARCHAR(50) NULL,
    [SO_AMT] DECIMAL(15,2) NULL,
    [SO_STS] VARCHAR(1) NULL,
    [SO_CRT_USR] VARCHAR(25) NULL,
    CONSTRAINT [PK_SALES_ORDER] PRIMARY KEY ([SO_ID])
);
GO

-- ============================================================
-- 12. MASTER DATA MODULE Tables
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'PRODUCT_MASTER')
CREATE TABLE [PRODUCT_MASTER] (
    [PM_COD] VARCHAR(50) NOT NULL,
    [PM_NAM] VARCHAR(200) NULL,
    [PM_CAT] VARCHAR(100) NULL,
    [PM_UOM] VARCHAR(10) NULL,
    [PM_PRC] DECIMAL(15,2) NULL,
    [PM_STS] VARCHAR(1) NULL,
    [PM_UPD_DAT] DATETIME2(3) NULL,
    CONSTRAINT [PK_PRODUCT_MASTER] PRIMARY KEY ([PM_COD])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'CUSTOMER_MASTER')
CREATE TABLE [CUSTOMER_MASTER] (
    [CM_COD] VARCHAR(50) NOT NULL,
    [CM_NAM] VARCHAR(200) NULL,
    [CM_ADR] VARCHAR(500) NULL,
    [CM_CTY] VARCHAR(100) NULL,
    [CM_PHN] VARCHAR(15) NULL,
    [CM_EML] VARCHAR(200) NULL,
    [CM_STS] VARCHAR(1) NULL,
    CONSTRAINT [PK_CUSTOMER_MASTER] PRIMARY KEY ([CM_COD])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'VENDOR_MASTER')
CREATE TABLE [VENDOR_MASTER] (
    [VM_COD] VARCHAR(50) NOT NULL,
    [VM_NAM] VARCHAR(200) NULL,
    [VM_ADR] VARCHAR(500) NULL,
    [VM_CTY] VARCHAR(100) NULL,
    [VM_PHN] VARCHAR(15) NULL,
    [VM_EML] VARCHAR(200) NULL,
    [VM_STS] VARCHAR(1) NULL,
    CONSTRAINT [PK_VENDOR_MASTER] PRIMARY KEY ([VM_COD])
);
GO

-- ============================================================
-- 13. STRATEGIC STOCK MODULE Tables
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'STRATEGIC_STOCK')
CREATE TABLE [STRATEGIC_STOCK] (
    [SS_ID] BIGINT NOT NULL IDENTITY(1,1),
    [SS_PRD_COD] VARCHAR(50) NULL,
    [SS_MIN_QTY] DECIMAL(15,2) NULL,
    [SS_MAX_QTY] DECIMAL(15,2) NULL,
    [SS_CUR_QTY] DECIMAL(15,2) NULL,
    [SS_ROL_QTY] DECIMAL(15,2) NULL,
    [SS_STS] VARCHAR(1) NULL,
    [SS_UPD_DAT] DATETIME2(3) NULL,
    CONSTRAINT [PK_STRATEGIC_STOCK] PRIMARY KEY ([SS_ID])
);
GO

-- ============================================================
-- 14. ERROR LOGGING MODULE Tables
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ERROR_LOG')
CREATE TABLE [ERROR_LOG] (
    [EL_ID] BIGINT NOT NULL IDENTITY(1,1),
    [EL_SVC_NAM] VARCHAR(100) NULL,
    [EL_ERR_MSG] VARCHAR(4000) NULL,
    [EL_STK_TRC] VARCHAR(MAX) NULL,
    [EL_ERR_DAT] DATETIME2(3) NULL,
    [EL_USR_COD] VARCHAR(25) NULL,
    [EL_SEV] VARCHAR(10) NULL,
    CONSTRAINT [PK_ERROR_LOG] PRIMARY KEY ([EL_ID])
);
GO

-- ============================================================
-- SCI Transactional Tables
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SPARSH_NAVIGATION')
CREATE TABLE [SPARSH_NAVIGATION] (
    [NAV_ID] BIGINT NOT NULL IDENTITY(1,1),
    [NAV_NAME] VARCHAR(200) NULL,
    [NAV_URL] VARCHAR(500) NULL,
    [NAV_PARENT_ID] BIGINT NULL,
    [NAV_ORDER] INT NULL,
    [NAV_STATUS] VARCHAR(1) NULL,
    CONSTRAINT [PK_SPARSH_NAVIGATION] PRIMARY KEY ([NAV_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'NORMS_MAIN')
CREATE TABLE [NORMS_MAIN] (
    [NORM_NO] BIGINT NOT NULL IDENTITY(1,1),
    [NORM_NAME] VARCHAR(200) NULL,
    [NORM_TYPE] VARCHAR(50) NULL,
    [NORM_STATUS] VARCHAR(1) NULL,
    [CREATED_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_NORMS_MAIN] PRIMARY KEY ([NORM_NO])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'NORMS_MASTER')
CREATE TABLE [NORMS_MASTER] (
    [NORMS_ID] BIGINT NOT NULL IDENTITY(1,1),
    [NORM_NO] BIGINT NULL,
    [ITEM_CODE] VARCHAR(50) NULL,
    [ITEM_QTY] DECIMAL(15,2) NULL,
    [UOM] VARCHAR(10) NULL,
    CONSTRAINT [PK_NORMS_MASTER] PRIMARY KEY ([NORMS_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'AUTO_MAIL_STATUS')
CREATE TABLE [AUTO_MAIL_STATUS] (
    [MAIL_ID] BIGINT NOT NULL IDENTITY(1,1),
    [MAIL_TO] VARCHAR(500) NULL,
    [MAIL_SUBJECT] VARCHAR(500) NULL,
    [MAIL_BODY] VARCHAR(MAX) NULL,
    [MAIL_STATUS] VARCHAR(1) NULL,
    [SENT_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_AUTO_MAIL_STATUS] PRIMARY KEY ([MAIL_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'AUTO_MAILID')
CREATE TABLE [AUTO_MAILID] (
    [MAILID_ID] BIGINT NOT NULL IDENTITY(1,1),
    [EMAIL_ADDRESS] VARCHAR(200) NULL,
    [EMAIL_TYPE] VARCHAR(50) NULL,
    [IS_ACTIVE] BIT NULL,
    CONSTRAINT [PK_AUTO_MAILID] PRIMARY KEY ([MAILID_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ACTUAL_ORDER_MAP')
CREATE TABLE [ACTUAL_ORDER_MAP] (
    [TIED_ORDER_DETAIL_ID] DECIMAL(38) NULL,
    [ACTUAL_LINE_ID] DECIMAL(38) NULL,
    [MAPPING_QUANTITY] INT NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL
);
GO

-- ============================================================
-- Seed Data: Default Admin User
-- ============================================================
IF NOT EXISTS (SELECT 1 FROM SCI_USER WHERE USR_COD = 'admin')
BEGIN
    INSERT INTO SCI_USER (USR_COD, USR_NAM, USR_PWD, USR_EML, USR_STS, USR_TYP, USR_UPD_USR, USR_UPD_DAT)
    VALUES ('admin', 'System Administrator', 
            -- BCrypt hash of 'Admin@123'
            '$2a$11$K7Jq4qJ3hRqX5FGm5qJ9.OQQ/7EQrQqH8K5xXxqJ3hRqX5FGm5qJ9',
            'admin@scierp.com', 'A', 'ADMIN', 'SYSTEM', GETDATE());
    PRINT 'Default admin user created.';
END
GO

-- Seed Default Roles
IF NOT EXISTS (SELECT 1 FROM ACCESS_ROLE_MASTER WHERE AR_ROL_COD = 1)
BEGIN
    INSERT INTO ACCESS_ROLE_MASTER (AR_ROL_COD, AR_ROL_NAM, AR_UPD_USR, AR_UPD_DAT)
    VALUES (1, 'Administrator', 'SYSTEM', GETDATE());
    INSERT INTO ACCESS_ROLE_MASTER (AR_ROL_COD, AR_ROL_NAM, AR_UPD_USR, AR_UPD_DAT)
    VALUES (2, 'Manager', 'SYSTEM', GETDATE());
    INSERT INTO ACCESS_ROLE_MASTER (AR_ROL_COD, AR_ROL_NAM, AR_UPD_USR, AR_UPD_DAT)
    VALUES (3, 'Operator', 'SYSTEM', GETDATE());
    INSERT INTO ACCESS_ROLE_MASTER (AR_ROL_COD, AR_ROL_NAM, AR_UPD_USR, AR_UPD_DAT)
    VALUES (4, 'Viewer', 'SYSTEM', GETDATE());
    PRINT 'Default roles created.';
END
GO

-- Assign admin role
IF NOT EXISTS (SELECT 1 FROM ACCESS_ROLE WHERE RA_USR_COD = 'admin')
BEGIN
    INSERT INTO ACCESS_ROLE (RA_USR_COD, RA_USR_NUM, RA_ROL_COD, RA_UPD_USR, RA_UPD_DAT, RA_STR_DAT)
    VALUES ('admin', 1, 1, 'SYSTEM', GETDATE(), GETDATE());
    PRINT 'Admin role assignment created.';
END
GO

PRINT '============================================================';
PRINT 'SCIDB Database initialization completed successfully!';
PRINT '============================================================';
GO
