-- ==========================================
-- Module: COMPLAINT MANAGEMENT
-- Database: TASKDB
-- Purpose: Complaint/NCR Ticket Management
-- Tables for managing complaints, actions, escalations, and history
-- ==========================================

USE [TASKDB];
GO

-- ==========================================
-- COMPLAINT MANAGEMENT TABLES
-- ==========================================

-- Table: COMPL_MAIN
-- Purpose: Main complaint group registration
CREATE TABLE [COMPL_MAIN] (
    [CM_UNIT_CODE] CHAR(3) NOT NULL,
    [CM_GROUPID] VARCHAR(255) NOT NULL,
    [CM_GROUP_NAME] VARCHAR(2000) NOT NULL,
    [CM_GROUP_DESC] VARCHAR(2000) NULL,
    [CM_GROUP_SRC] DECIMAL(38) NOT NULL,
    [CM_BEHALF_FLG] CHAR(1) NULL,
    [CM_BEHALF_PIN] DECIMAL(38) NULL,
    [CM_REG_PIN] DECIMAL(38) NULL,
    [CM_SHIFT] VARCHAR(255) NULL,
    [CM_MAIL] VARCHAR(255) NULL,
    [CM_SUBMIT] VARCHAR(255) NULL,
    [CM_REG_DATE] DATETIME2(3) NULL,
    [CM_UPDATEDBY] VARCHAR(255) NULL,
    [CM_UPDATEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_COMPL_MAIN] PRIMARY KEY ([CM_GROUPID])
);

-- Table: COMPL_DET
-- Purpose: Complaint details - registering complaint/NCR tickets
CREATE TABLE [COMPL_DET] (
    [CD_TICKET_NUM] DECIMAL(38) NOT NULL,
    [CD_GROUPID] DECIMAL(38) NOT NULL,
    [CD_TYPE] DECIMAL(38) NOT NULL,
    [CD_LOCATION] DECIMAL(38) NOT NULL,
    [CD_DEPARTMENT] DECIMAL(38) NOT NULL,
    [CD_PROCESS] DECIMAL(38) NOT NULL,
    [CD_SUBJECT] VARCHAR(500) NULL,
    [CD_DESCRIPTION] VARCHAR(4000) NULL,
    [CD_NCR] CHAR(1) NULL,
    [CD_PICTUREPATH] VARCHAR(200) NULL,
    [CD_FILEPATH] VARCHAR(200) NULL,
    [CD_TARGET_DATE] VARCHAR(255) NOT NULL,
    [CD_CLOSURE_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_COMPL_DET] PRIMARY KEY ([CD_TICKET_NUM])
);

-- Table: COMPL_ACTION
-- Purpose: Complaint action tracking - multi-level resolution tracking (Primary, Secondary, Forward, Corrective)
CREATE TABLE [COMPL_ACTION] (
    [CA_ACTION_NUM] DECIMAL(38) NOT NULL,
    [CA_TASK_NUM] DECIMAL(38) NOT NULL,
    [CA_PRM_RESP] VARCHAR(300) NULL,
    [CA_PRM_ACTBY] DECIMAL(38) NULL,
    [CA_PRM_ACTDATE] DATETIME2(3) NULL,
    [CA_PRM_SOLUTION] VARCHAR(4000) NULL,
    [CA_SEC_ESCHRS] DECIMAL(38) NULL,
    [CA_SEC_RESP] VARCHAR(300) NULL,
    [CA_SEC_ACTBY] DECIMAL(38) NULL,
    [CA_SEC_ACTDATE] DATETIME2(3) NULL,
    [CA_SEC_SOLUTION] VARCHAR(4000) NULL,
    [CA_FWD_REMARKS] VARCHAR(4000) NULL,
    [CA_FWD_RESP] VARCHAR(300) NULL,
    [CA_FWD_ACTBY] DECIMAL(38) NULL,
    [CA_FWD_ACTDATE] DATETIME2(3) NULL,
    [CA_FWD_SOLUTION] VARCHAR(4000) NULL,
    [CA_CUR_ESCLEVEL] DECIMAL(38) NULL,
    [CA_CORR_ACTREQ] CHAR(1) NULL,
    [CA_CORR_REMARKS] VARCHAR(4000) NULL,
    [CA_CORR_RESP] VARCHAR(300) NULL,
    [CA_CORR_ACTBY] DECIMAL(38) NULL,
    [CA_CORR_ACTDATE] DATETIME2(3) NULL,
    [CA_CORR_SOLUTION] VARCHAR(4000) NULL,
    [CA_REOPEN_FLG] CHAR(1) NULL,
    [CA_REOPEN_REMARKS] VARCHAR(4000) NULL,
    [CA_TRG_DAT] DATETIME2(3) NULL,
    [CA_CLS_DAT] DATETIME2(3) NULL,
    [CA_UPATEDBY] DECIMAL(38) NULL,
    CONSTRAINT [PK_COMPL_ACTION] PRIMARY KEY ([CA_ACTION_NUM])
);

-- Table: COMPL_ESC
-- Purpose: Complaint escalation tracking
CREATE TABLE [COMPL_ESC] (
    [CE_TICKET_NUM] DECIMAL(38) NOT NULL,
    [CE_LEVEL_NUM] DECIMAL(38) NOT NULL,
    [CE_ESC_NOHRS] DECIMAL(38) NOT NULL,
    [CE_USER_PIN] DECIMAL(38) NOT NULL,
    [CE_EFF_DATE] DATETIME2(3) NOT NULL,
    [CE_CLS_DATE] DATETIME2(3) NULL,
    [CE_EXCLUDE] CHAR(1) NULL,
    [CE_UPDATEDBY] DECIMAL(38) NULL,
    [CE_UPDATEDON] DATETIME2(3) NULL
);

-- Table: COMPL_HIST
-- Purpose: Complaint history - audit trail of all changes
CREATE TABLE [COMPL_HIST] (
    [CH_HISTORY_NUM] DECIMAL(38) NOT NULL,
    [CH_ACTION_NUM] DECIMAL(38) NOT NULL,
    [CH_SERIAL_NUM] DECIMAL(38) NOT NULL,
    [CH_FROM] VARCHAR(65) NULL,
    [CH_TO] VARCHAR(1000) NULL,
    [CH_ACTION_DATE] DATETIME2(3) NOT NULL,
    [CH_ACTION_TYPE] CHAR(1) NOT NULL,
    [CH_REMARKS] VARCHAR(4000) NULL,
    [CH_UPDATEDBY] DECIMAL(38) NULL,
    [CH_UPDATEDON] DATETIME2(3) NULL,
    [CH_FILEPATH] VARCHAR(200) NULL,
    CONSTRAINT [PK_COMPL_HIST] PRIMARY KEY ([CH_HISTORY_NUM])
);

-- Table: COMPL_TASK
-- Purpose: Complaint task scheduling
CREATE TABLE [COMPL_TASK] (
    [CT_TASK_NUM] DECIMAL(38) NOT NULL,
    [CT_TICKET_NUM] DECIMAL(38) NOT NULL,
    [CT_SCHEDULE_FREQ] CHAR(2) NOT NULL,
    [CT_SCHEDULE_VALUE] VARCHAR(300) NULL,
    [CT_SCHEDULE_TIME] VARCHAR(12) NULL,
    [CT_SCHEDULE_DAY] VARCHAR(65) NULL,
    [CT_EFF_DATE] DATETIME2(3) NULL,
    [CT_CLS_DATE] DATETIME2(3) NULL,
    [CT_UPDATED_BY] DECIMAL(38) NULL,
    [CT_UPDATED_ON] DATETIME2(3) NULL,
    CONSTRAINT [PK_COMPL_TASK] PRIMARY KEY ([CT_TASK_NUM])
);

-- ==========================================
-- END OF SCRIPT - COMPLAINT MODULE TABLES
-- ==========================================
