// <auto-generated />
using System;
using ComplaintService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComplaintService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ComplaintDbContext))]
    partial class ComplaintDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComplaintService.Domain.Entities.ComplaintAction", b =>
                {
                    b.Property<decimal>("ActionNum")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CA_ACTION_NUM");

                    b.Property<DateTime?>("ClosureDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CA_CLS_DAT");

                    b.Property<decimal?>("CorrActBy")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CA_CORR_ACTBY");

                    b.Property<DateTime?>("CorrActDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CA_CORR_ACTDATE");

                    b.Property<string>("CorrActRequired")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("CA_CORR_ACTREQ")
                        .IsFixedLength();

                    b.Property<string>("CorrRemarks")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("CA_CORR_REMARKS");

                    b.Property<string>("CorrResp")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("CA_CORR_RESP");

                    b.Property<string>("CorrSolution")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("CA_CORR_SOLUTION");

                    b.Property<decimal?>("CurrentEscLevel")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CA_CUR_ESCLEVEL");

                    b.Property<decimal?>("FwdActBy")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CA_FWD_ACTBY");

                    b.Property<DateTime?>("FwdActDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CA_FWD_ACTDATE");

                    b.Property<string>("FwdRemarks")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("CA_FWD_REMARKS");

                    b.Property<string>("FwdResp")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("CA_FWD_RESP");

                    b.Property<string>("FwdSolution")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("CA_FWD_SOLUTION");

                    b.Property<decimal?>("PrimaryActBy")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CA_PRM_ACTBY");

                    b.Property<DateTime?>("PrimaryActDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CA_PRM_ACTDATE");

                    b.Property<string>("PrimaryResp")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("CA_PRM_RESP");

                    b.Property<string>("PrimarySolution")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("CA_PRM_SOLUTION");

                    b.Property<string>("ReopenFlag")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("CA_REOPEN_FLG")
                        .IsFixedLength();

                    b.Property<string>("ReopenRemarks")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("CA_REOPEN_REMARKS");

                    b.Property<decimal?>("SecActBy")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CA_SEC_ACTBY");

                    b.Property<DateTime?>("SecActDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CA_SEC_ACTDATE");

                    b.Property<decimal?>("SecEscHrs")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CA_SEC_ESCHRS");

                    b.Property<string>("SecResp")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("CA_SEC_RESP");

                    b.Property<string>("SecSolution")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("CA_SEC_SOLUTION");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CA_TRG_DAT");

                    b.Property<decimal>("TaskNum")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CA_TASK_NUM");

                    b.Property<decimal?>("UpdatedBy")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CA_UPATEDBY");

                    b.HasKey("ActionNum");

                    b.HasIndex("TaskNum")
                        .IsUnique();

                    b.ToTable("COMPL_ACTION", (string)null);
                });

            modelBuilder.Entity("ComplaintService.Domain.Entities.ComplaintEscalation", b =>
                {
                    b.Property<decimal>("TicketNum")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CE_TICKET_NUM");

                    b.Property<decimal>("LevelNum")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CE_LEVEL_NUM");

                    b.Property<DateTime?>("ClsDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CE_CLS_DATE");

                    b.Property<DateTime>("EffDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CE_EFF_DATE");

                    b.Property<decimal>("EscNoHrs")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CE_ESC_NOHRS");

                    b.Property<string>("Exclude")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("CE_EXCLUDE")
                        .IsFixedLength();

                    b.Property<decimal?>("UpdatedBy")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CE_UPDATEDBY");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CE_UPDATEDON");

                    b.Property<decimal>("UserPin")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CE_USER_PIN");

                    b.HasKey("TicketNum", "LevelNum");

                    b.ToTable("COMPL_ESC", (string)null);
                });

            modelBuilder.Entity("ComplaintService.Domain.Entities.ComplaintGroup", b =>
                {
                    b.Property<string>("GroupId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CM_GROUPID");

                    b.Property<string>("BehalfFlag")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("CM_BEHALF_FLG")
                        .IsFixedLength();

                    b.Property<decimal?>("BehalfPin")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CM_BEHALF_PIN");

                    b.Property<string>("GroupDesc")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("CM_GROUP_DESC");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("CM_GROUP_NAME");

                    b.Property<decimal>("GroupSrc")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CM_GROUP_SRC");

                    b.Property<string>("Mail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CM_MAIL");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CM_REG_DATE");

                    b.Property<decimal?>("RegPin")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CM_REG_PIN");

                    b.Property<string>("Shift")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CM_SHIFT");

                    b.Property<string>("Submit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CM_SUBMIT");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("CM_UNIT_CODE")
                        .IsFixedLength();

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CM_UPDATEDBY");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CM_UPDATEDON");

                    b.HasKey("GroupId");

                    b.ToTable("COMPL_MAIN", (string)null);
                });

            modelBuilder.Entity("ComplaintService.Domain.Entities.ComplaintHistory", b =>
                {
                    b.Property<decimal>("HistoryNum")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CH_HISTORY_NUM");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CH_ACTION_DATE");

                    b.Property<decimal>("ActionNum")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CH_ACTION_NUM");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("CH_ACTION_TYPE")
                        .IsFixedLength();

                    b.Property<string>("FilePath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CH_FILEPATH");

                    b.Property<string>("From")
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)")
                        .HasColumnName("CH_FROM");

                    b.Property<string>("Remarks")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("CH_REMARKS");

                    b.Property<decimal>("SerialNum")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CH_SERIAL_NUM");

                    b.Property<string>("To")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("CH_TO");

                    b.Property<decimal?>("UpdatedBy")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CH_UPDATEDBY");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CH_UPDATEDON");

                    b.HasKey("HistoryNum");

                    b.HasIndex("ActionNum");

                    b.ToTable("COMPL_HIST", (string)null);
                });

            modelBuilder.Entity("ComplaintService.Domain.Entities.ComplaintTask", b =>
                {
                    b.Property<decimal>("TaskNum")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CT_TASK_NUM");

                    b.Property<DateTime?>("ClsDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CT_CLS_DATE");

                    b.Property<DateTime?>("EffDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CT_EFF_DATE");

                    b.Property<string>("ScheduleDay")
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)")
                        .HasColumnName("CT_SCHEDULE_DAY");

                    b.Property<string>("ScheduleFreq")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("CT_SCHEDULE_FREQ")
                        .IsFixedLength();

                    b.Property<string>("ScheduleTime")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("CT_SCHEDULE_TIME");

                    b.Property<string>("ScheduleValue")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("CT_SCHEDULE_VALUE");

                    b.Property<decimal>("TicketNum")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CT_TICKET_NUM");

                    b.Property<decimal?>("UpdatedBy")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CT_UPDATED_BY");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CT_UPDATED_ON");

                    b.HasKey("TaskNum");

                    b.HasIndex("TicketNum");

                    b.ToTable("COMPL_TASK", (string)null);
                });

            modelBuilder.Entity("ComplaintService.Domain.Entities.ComplaintTicket", b =>
                {
                    b.Property<decimal>("TicketNum")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CD_TICKET_NUM");

                    b.Property<DateTime?>("ClosureDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CD_CLOSURE_DATE");

                    b.Property<decimal>("Department")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CD_DEPARTMENT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("CD_DESCRIPTION");

                    b.Property<string>("FilePath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CD_FILEPATH");

                    b.Property<decimal>("GroupId")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CD_GROUPID");

                    b.Property<string>("IsNCR")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("CD_NCR")
                        .IsFixedLength();

                    b.Property<decimal>("Location")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CD_LOCATION");

                    b.Property<string>("PicturePath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CD_PICTUREPATH");

                    b.Property<decimal>("Process")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CD_PROCESS");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CD_SUBJECT");

                    b.Property<string>("TargetDate")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CD_TARGET_DATE");

                    b.Property<decimal>("Type")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("CD_TYPE");

                    b.HasKey("TicketNum");

                    b.HasIndex("GroupId");

                    b.ToTable("COMPL_DET", (string)null);
                });

            modelBuilder.Entity("ComplaintService.Domain.Entities.ComplaintAction", b =>
                {
                    b.HasOne("ComplaintService.Domain.Entities.ComplaintTicket", "Ticket")
                        .WithOne("Action")
                        .HasForeignKey("ComplaintService.Domain.Entities.ComplaintAction", "TaskNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ComplaintService.Domain.Entities.ComplaintEscalation", b =>
                {
                    b.HasOne("ComplaintService.Domain.Entities.ComplaintTicket", null)
                        .WithMany("Escalations")
                        .HasForeignKey("TicketNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComplaintService.Domain.Entities.ComplaintHistory", b =>
                {
                    b.HasOne("ComplaintService.Domain.Entities.ComplaintAction", null)
                        .WithMany("Histories")
                        .HasForeignKey("ActionNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComplaintService.Domain.Entities.ComplaintTask", b =>
                {
                    b.HasOne("ComplaintService.Domain.Entities.ComplaintTicket", null)
                        .WithMany("Tasks")
                        .HasForeignKey("TicketNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComplaintService.Domain.Entities.ComplaintTicket", b =>
                {
                    b.HasOne("ComplaintService.Domain.Entities.ComplaintGroup", null)
                        .WithMany("Tickets")
                        .HasForeignKey("GroupId")
                        .HasPrincipalKey("GroupSrc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComplaintService.Domain.Entities.ComplaintAction", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("ComplaintService.Domain.Entities.ComplaintGroup", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ComplaintService.Domain.Entities.ComplaintTicket", b =>
                {
                    b.Navigation("Action");

                    b.Navigation("Escalations");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
