-- ============================================================================
-- CASHDB Initialization Script
-- Creates all schemas for Cash Services microservices
-- ============================================================================

-- Create CASHDB database
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'CASHDB')
BEGIN
    CREATE DATABASE CASHDB;
END
GO

USE CASHDB;
GO

-- ============================================================================
-- 01 - Currency Management Schema
-- ============================================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DEAL_CURRMAST')
BEGIN
    CREATE TABLE [dbo].[DEAL_CURRMAST] (
        [CURR_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [CURR_CODE] NVARCHAR(10) NOT NULL,
        [CURR_NAME] NVARCHAR(100) NOT NULL,
        [CURR_SYMBOL] NVARCHAR(10),
        [CURR_COUNTRY] NVARCHAR(100),
        [CURR_DECIMAL_PLACES] INT DEFAULT 2,
        [CURR_IS_ACTIVE] BIT DEFAULT 1,
        [CURR_CREATED_BY] BIGINT DEFAULT 1,
        [CURR_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        [CURR_UPDATED_BY] BIGINT,
        [CURR_UPDATED_ON] DATETIME2(3)
    );
    CREATE UNIQUE INDEX IX_DEAL_CURRMAST_CODE ON [DEAL_CURRMAST]([CURR_CODE]);
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DEAL_CURRATES')
BEGIN
    CREATE TABLE [dbo].[DEAL_CURRATES] (
        [RATE_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [RATE_CURR_ID] BIGINT NOT NULL,
        [RATE_BASE_CURR_ID] BIGINT NOT NULL,
        [RATE_BUY] DECIMAL(18,8) NOT NULL,
        [RATE_SELL] DECIMAL(18,8) NOT NULL,
        [RATE_MID] DECIMAL(18,8),
        [RATE_DATE] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
        [RATE_SOURCE] NVARCHAR(100),
        [RATE_IS_ACTIVE] BIT DEFAULT 1,
        [RATE_CREATED_BY] BIGINT DEFAULT 1,
        [RATE_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        CONSTRAINT FK_CURRATES_CURR FOREIGN KEY ([RATE_CURR_ID]) REFERENCES [DEAL_CURRMAST]([CURR_ID]),
        CONSTRAINT FK_CURRATES_BASE FOREIGN KEY ([RATE_BASE_CURR_ID]) REFERENCES [DEAL_CURRMAST]([CURR_ID])
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DEAL_ORGCURRMAP')
BEGIN
    CREATE TABLE [dbo].[DEAL_ORGCURRMAP] (
        [MAP_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [MAP_ORG_ID] BIGINT NOT NULL,
        [MAP_CURR_ID] BIGINT NOT NULL,
        [MAP_IS_DEFAULT] BIT DEFAULT 0,
        [MAP_IS_ACTIVE] BIT DEFAULT 1,
        [MAP_CREATED_BY] BIGINT DEFAULT 1,
        [MAP_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        CONSTRAINT FK_ORGCURRMAP_CURR FOREIGN KEY ([MAP_CURR_ID]) REFERENCES [DEAL_CURRMAST]([CURR_ID])
    );
END
GO

-- ============================================================================
-- 02 - Deal Ticketing Schema
-- ============================================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DEAL_BANKMASTER')
BEGIN
    CREATE TABLE [dbo].[DEAL_BANKMASTER] (
        [BANK_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [BANK_CODE] NVARCHAR(20) NOT NULL,
        [BANK_NAME] NVARCHAR(200) NOT NULL,
        [BANK_BRANCH] NVARCHAR(200),
        [BANK_IFSC] NVARCHAR(20),
        [BANK_SWIFT] NVARCHAR(20),
        [BANK_ACCOUNT_NO] NVARCHAR(50),
        [BANK_IS_ACTIVE] BIT DEFAULT 1,
        [BANK_CREATED_BY] BIGINT DEFAULT 1,
        [BANK_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        [BANK_UPDATED_BY] BIGINT,
        [BANK_UPDATED_ON] DATETIME2(3)
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DEAL_CATEGORYMASTER')
BEGIN
    CREATE TABLE [dbo].[DEAL_CATEGORYMASTER] (
        [CAT_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [CAT_CODE] NVARCHAR(20) NOT NULL,
        [CAT_NAME] NVARCHAR(200) NOT NULL,
        [CAT_DESCRIPTION] NVARCHAR(500),
        [CAT_IS_ACTIVE] BIT DEFAULT 1,
        [CAT_CREATED_BY] BIGINT DEFAULT 1,
        [CAT_CREATED_ON] DATETIME2(3) DEFAULT GETDATE()
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DEAL_LOVMASTER')
BEGIN
    CREATE TABLE [dbo].[DEAL_LOVMASTER] (
        [LOV_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [LOV_TYPE] NVARCHAR(50) NOT NULL,
        [LOV_CODE] NVARCHAR(50) NOT NULL,
        [LOV_VALUE] NVARCHAR(200) NOT NULL,
        [LOV_IS_ACTIVE] BIT DEFAULT 1,
        [LOV_SORT_ORDER] INT DEFAULT 0,
        [LOV_CREATED_BY] BIGINT DEFAULT 1,
        [LOV_CREATED_ON] DATETIME2(3) DEFAULT GETDATE()
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DEALTICKET_BATCH')
BEGIN
    CREATE TABLE [dbo].[DEALTICKET_BATCH] (
        [BATCH_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [BATCH_NO] NVARCHAR(50) NOT NULL,
        [BATCH_DATE] DATETIME2(3) NOT NULL,
        [BATCH_STATUS] NVARCHAR(20) DEFAULT 'OPEN',
        [BATCH_TOTAL_DEALS] INT DEFAULT 0,
        [BATCH_TOTAL_AMOUNT] DECIMAL(18,4) DEFAULT 0,
        [BATCH_CREATED_BY] BIGINT DEFAULT 1,
        [BATCH_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        [BATCH_UPDATED_BY] BIGINT,
        [BATCH_UPDATED_ON] DATETIME2(3)
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DEALTICKET_DET')
BEGIN
    CREATE TABLE [dbo].[DEALTICKET_DET] (
        [DEAL_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [DEAL_BATCH_ID] BIGINT,
        [DEAL_NO] NVARCHAR(50) NOT NULL,
        [DEAL_DATE] DATETIME2(3) NOT NULL,
        [DEAL_TYPE] NVARCHAR(20) NOT NULL,
        [DEAL_CATEGORY_ID] BIGINT,
        [DEAL_CURR_ID] BIGINT,
        [DEAL_AMOUNT] DECIMAL(18,4) NOT NULL,
        [DEAL_EXCHANGE_RATE] DECIMAL(18,8) DEFAULT 1.0,
        [DEAL_BASE_AMOUNT] DECIMAL(18,4),
        [DEAL_COUNTERPARTY] NVARCHAR(200),
        [DEAL_STATUS] NVARCHAR(20) DEFAULT 'DRAFT',
        [DEAL_REMARKS] NVARCHAR(500),
        [DEAL_CREATED_BY] BIGINT DEFAULT 1,
        [DEAL_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        [DEAL_UPDATED_BY] BIGINT,
        [DEAL_UPDATED_ON] DATETIME2(3),
        CONSTRAINT FK_DEALDET_BATCH FOREIGN KEY ([DEAL_BATCH_ID]) REFERENCES [DEALTICKET_BATCH]([BATCH_ID]),
        CONSTRAINT FK_DEALDET_CATEGORY FOREIGN KEY ([DEAL_CATEGORY_ID]) REFERENCES [DEAL_CATEGORYMASTER]([CAT_ID])
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DEALTICKET_SET')
BEGIN
    CREATE TABLE [dbo].[DEALTICKET_SET] (
        [SET_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [SET_DEAL_ID] BIGINT NOT NULL,
        [SET_TYPE] CHAR(1) DEFAULT 'U',
        [SET_DATE] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
        [SET_AMOUNT] DECIMAL(18,4) NOT NULL,
        [SET_SPOT_RATE] DECIMAL(18,8),
        [SET_EXCHANGE_RATE] DECIMAL(18,8),
        [SET_GAIN_LOSS] DECIMAL(18,4),
        [SET_PREMIUM] DECIMAL(18,4),
        [SET_WINDING_FEE] DECIMAL(18,4),
        [SET_NET_AMOUNT] DECIMAL(18,4),
        [SET_STATUS] NVARCHAR(20) DEFAULT 'PENDING',
        [SET_BANK_ID] BIGINT,
        [SET_CREATED_BY] BIGINT DEFAULT 1,
        [SET_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        CONSTRAINT FK_DEALSET_DEAL FOREIGN KEY ([SET_DEAL_ID]) REFERENCES [DEALTICKET_DET]([DEAL_ID])
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DEALTICKET_LOANSCH')
BEGIN
    CREATE TABLE [dbo].[DEALTICKET_LOANSCH] (
        [SCH_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [SCH_DEAL_ID] BIGINT NOT NULL,
        [SCH_DATE] DATETIME2(3) NOT NULL,
        [SCH_AMOUNT] DECIMAL(18,4) NOT NULL,
        [SCH_STATUS] NVARCHAR(20) DEFAULT 'PENDING',
        [SCH_CREATED_BY] BIGINT DEFAULT 1,
        [SCH_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        CONSTRAINT FK_LOANSCH_DEAL FOREIGN KEY ([SCH_DEAL_ID]) REFERENCES [DEALTICKET_DET]([DEAL_ID])
    );
END
GO

-- ============================================================================
-- 03 - Loan Management Schema
-- ============================================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LOAN_MAIN')
BEGIN
    CREATE TABLE [dbo].[LOAN_MAIN] (
        [LOAN_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [LOAN_NO] NVARCHAR(50) NOT NULL,
        [LOAN_TYPE] NVARCHAR(30) NOT NULL,
        [LOAN_PURPOSE] NVARCHAR(200),
        [LOAN_AMOUNT] DECIMAL(18,4) NOT NULL,
        [LOAN_CURR_ID] BIGINT,
        [LOAN_EXCHANGE_RATE] DECIMAL(18,8) DEFAULT 1.0,
        [LOAN_BASE_AMOUNT] DECIMAL(18,4),
        [LOAN_BANK_ID] BIGINT,
        [LOAN_DRAWDOWN_DATE] DATETIME2(3),
        [LOAN_MATURITY_DATE] DATETIME2(3),
        [LOAN_STATUS] NVARCHAR(20) DEFAULT 'ACTIVE',
        [LOAN_CREATED_BY] BIGINT DEFAULT 1,
        [LOAN_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        [LOAN_UPDATED_BY] BIGINT,
        [LOAN_UPDATED_ON] DATETIME2(3)
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LOAN_DISBSCH')
BEGIN
    CREATE TABLE [dbo].[LOAN_DISBSCH] (
        [DISB_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [DISB_LOAN_ID] BIGINT NOT NULL,
        [DISB_TRANCHE] INT DEFAULT 1,
        [DISB_DATE] DATETIME2(3) NOT NULL,
        [DISB_AMOUNT] DECIMAL(18,4) NOT NULL,
        [DISB_STATUS] NVARCHAR(20) DEFAULT 'PENDING',
        [DISB_BANK_ACCOUNT] NVARCHAR(50),
        [DISB_CREATED_BY] BIGINT DEFAULT 1,
        [DISB_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        CONSTRAINT FK_DISBSCH_LOAN FOREIGN KEY ([DISB_LOAN_ID]) REFERENCES [LOAN_MAIN]([LOAN_ID])
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LOAN_INTEREST')
BEGIN
    CREATE TABLE [dbo].[LOAN_INTEREST] (
        [INT_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [INT_LOAN_ID] BIGINT NOT NULL,
        [INT_TYPE] NVARCHAR(20) DEFAULT 'FIXED',
        [INT_RATE] DECIMAL(8,4) NOT NULL,
        [INT_BENCHMARK] NVARCHAR(50),
        [INT_SPREAD] DECIMAL(8,4),
        [INT_EFFECTIVE_DATE] DATETIME2(3) NOT NULL,
        [INT_END_DATE] DATETIME2(3),
        [INT_CREATED_BY] BIGINT DEFAULT 1,
        [INT_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        CONSTRAINT FK_INTEREST_LOAN FOREIGN KEY ([INT_LOAN_ID]) REFERENCES [LOAN_MAIN]([LOAN_ID])
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LOAN_REPAYSCH')
BEGIN
    CREATE TABLE [dbo].[LOAN_REPAYSCH] (
        [REPAY_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [REPAY_LOAN_ID] BIGINT NOT NULL,
        [REPAY_DUE_DATE] DATETIME2(3) NOT NULL,
        [REPAY_PRINCIPAL] DECIMAL(18,4) NOT NULL,
        [REPAY_INTEREST] DECIMAL(18,4) NOT NULL,
        [REPAY_TOTAL] DECIMAL(18,4) NOT NULL,
        [REPAY_STATUS] NVARCHAR(20) DEFAULT 'PENDING',
        [REPAY_ACTUAL_DATE] DATETIME2(3),
        [REPAY_ACTUAL_AMOUNT] DECIMAL(18,4),
        [REPAY_CREATED_BY] BIGINT DEFAULT 1,
        [REPAY_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        CONSTRAINT FK_REPAYSCH_LOAN FOREIGN KEY ([REPAY_LOAN_ID]) REFERENCES [LOAN_MAIN]([LOAN_ID])
    );
END
GO

-- ============================================================================
-- 04 - Cash Management Schema
-- ============================================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'CASH_UNIT')
BEGIN
    CREATE TABLE [dbo].[CASH_UNIT] (
        [UNIT_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [UNIT_CODE] NVARCHAR(20) NOT NULL,
        [UNIT_NAME] NVARCHAR(100) NOT NULL,
        [UNIT_TYPE] NVARCHAR(20),
        [UNIT_BALANCE] DECIMAL(18,4) DEFAULT 0,
        [UNIT_CURR_ID] BIGINT,
        [UNIT_IS_ACTIVE] BIT DEFAULT 1,
        [UNIT_CREATED_BY] BIGINT DEFAULT 1,
        [UNIT_CREATED_ON] DATETIME2(3) DEFAULT GETDATE()
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BANK_ACCOUNT')
BEGIN
    CREATE TABLE [dbo].[BANK_ACCOUNT] (
        [ACC_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [ACC_BANK_ID] BIGINT,
        [ACC_NUMBER] NVARCHAR(50) NOT NULL,
        [ACC_NAME] NVARCHAR(200),
        [ACC_TYPE] NVARCHAR(20),
        [ACC_CURR_ID] BIGINT,
        [ACC_BALANCE] DECIMAL(18,4) DEFAULT 0,
        [ACC_IS_ACTIVE] BIT DEFAULT 1,
        [ACC_CREATED_BY] BIGINT DEFAULT 1,
        [ACC_CREATED_ON] DATETIME2(3) DEFAULT GETDATE()
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'CASH_TRANSACTION')
BEGIN
    CREATE TABLE [dbo].[CASH_TRANSACTION] (
        [TXN_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [TXN_UNIT_ID] BIGINT NOT NULL,
        [TXN_DATE] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
        [TXN_TYPE] NVARCHAR(20) NOT NULL,
        [TXN_AMOUNT] DECIMAL(18,4) NOT NULL,
        [TXN_REFERENCE] NVARCHAR(100),
        [TXN_DESCRIPTION] NVARCHAR(500),
        [TXN_STATUS] NVARCHAR(20) DEFAULT 'COMPLETED',
        [TXN_CREATED_BY] BIGINT DEFAULT 1,
        [TXN_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        CONSTRAINT FK_CASHTXN_UNIT FOREIGN KEY ([TXN_UNIT_ID]) REFERENCES [CASH_UNIT]([UNIT_ID])
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BANK_TRANSACTION')
BEGIN
    CREATE TABLE [dbo].[BANK_TRANSACTION] (
        [BTXN_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [BTXN_ACC_ID] BIGINT NOT NULL,
        [BTXN_DATE] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
        [BTXN_TYPE] NVARCHAR(20) NOT NULL,
        [BTXN_AMOUNT] DECIMAL(18,4) NOT NULL,
        [BTXN_REFERENCE] NVARCHAR(100),
        [BTXN_DESCRIPTION] NVARCHAR(500),
        [BTXN_STATUS] NVARCHAR(20) DEFAULT 'COMPLETED',
        [BTXN_CREATED_BY] BIGINT DEFAULT 1,
        [BTXN_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        CONSTRAINT FK_BANKTXN_ACC FOREIGN KEY ([BTXN_ACC_ID]) REFERENCES [BANK_ACCOUNT]([ACC_ID])
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'CHEQUE_REGISTER')
BEGIN
    CREATE TABLE [dbo].[CHEQUE_REGISTER] (
        [CHQ_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [CHQ_ACC_ID] BIGINT NOT NULL,
        [CHQ_NUMBER] NVARCHAR(20) NOT NULL,
        [CHQ_DATE] DATETIME2(3) NOT NULL,
        [CHQ_AMOUNT] DECIMAL(18,4) NOT NULL,
        [CHQ_PAYEE] NVARCHAR(200),
        [CHQ_STATUS] NVARCHAR(20) DEFAULT 'ISSUED',
        [CHQ_CLEARED_DATE] DATETIME2(3),
        [CHQ_CREATED_BY] BIGINT DEFAULT 1,
        [CHQ_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        CONSTRAINT FK_CHEQUE_ACC FOREIGN KEY ([CHQ_ACC_ID]) REFERENCES [BANK_ACCOUNT]([ACC_ID])
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BANK_RECONCILIATION')
BEGIN
    CREATE TABLE [dbo].[BANK_RECONCILIATION] (
        [RECON_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [RECON_ACC_ID] BIGINT NOT NULL,
        [RECON_DATE] DATETIME2(3) NOT NULL,
        [RECON_BANK_BALANCE] DECIMAL(18,4) NOT NULL,
        [RECON_BOOK_BALANCE] DECIMAL(18,4) NOT NULL,
        [RECON_DIFFERENCE] DECIMAL(18,4),
        [RECON_STATUS] NVARCHAR(20) DEFAULT 'PENDING',
        [RECON_CREATED_BY] BIGINT DEFAULT 1,
        [RECON_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        CONSTRAINT FK_RECON_ACC FOREIGN KEY ([RECON_ACC_ID]) REFERENCES [BANK_ACCOUNT]([ACC_ID])
    );
END
GO

-- ============================================================================
-- 05 - Organization Setup Schema
-- ============================================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DEAL_ROLE')
BEGIN
    CREATE TABLE [dbo].[DEAL_ROLE] (
        [ROLE_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [ROLE_CODE] NVARCHAR(20) NOT NULL,
        [ROLE_NAME] NVARCHAR(100) NOT NULL,
        [ROLE_DESCRIPTION] NVARCHAR(500),
        [ROLE_IS_ACTIVE] BIT DEFAULT 1,
        [ROLE_CREATED_BY] BIGINT DEFAULT 1,
        [ROLE_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        [ROLE_UPDATED_BY] BIGINT,
        [ROLE_UPDATED_ON] DATETIME2(3)
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DEAL_USERMAP')
BEGIN
    CREATE TABLE [dbo].[DEAL_USERMAP] (
        [USERMAP_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [USERMAP_USER_ID] BIGINT NOT NULL,
        [USERMAP_ROLE_ID] BIGINT NOT NULL,
        [USERMAP_IS_ACTIVE] BIT DEFAULT 1,
        [USERMAP_CREATED_BY] BIGINT DEFAULT 1,
        [USERMAP_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        CONSTRAINT FK_USERMAP_ROLE FOREIGN KEY ([USERMAP_ROLE_ID]) REFERENCES [DEAL_ROLE]([ROLE_ID])
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DEAL_ORGPARAMS')
BEGIN
    CREATE TABLE [dbo].[DEAL_ORGPARAMS] (
        [PARAM_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [PARAM_CODE] NVARCHAR(50) NOT NULL,
        [PARAM_VALUE] NVARCHAR(500) NOT NULL,
        [PARAM_DESCRIPTION] NVARCHAR(500),
        [PARAM_IS_ACTIVE] BIT DEFAULT 1,
        [PARAM_CREATED_BY] BIGINT DEFAULT 1,
        [PARAM_CREATED_ON] DATETIME2(3) DEFAULT GETDATE()
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DEAL_PPLIMIT')
BEGIN
    CREATE TABLE [dbo].[DEAL_PPLIMIT] (
        [LIMIT_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [LIMIT_ROLE_ID] BIGINT,
        [LIMIT_AMOUNT] DECIMAL(18,4) NOT NULL,
        [LIMIT_CURR_ID] BIGINT,
        [LIMIT_IS_ACTIVE] BIT DEFAULT 1,
        [LIMIT_CREATED_BY] BIGINT DEFAULT 1,
        [LIMIT_CREATED_ON] DATETIME2(3) DEFAULT GETDATE()
    );
END
GO

-- ============================================================================
-- 06 - Email Notification Schema
-- ============================================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'EMAIL_TYPEMAST')
BEGIN
    CREATE TABLE [dbo].[EMAIL_TYPEMAST] (
        [TYPE_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [TYPE_CODE] NVARCHAR(50) NOT NULL,
        [TYPE_NAME] NVARCHAR(200) NOT NULL,
        [TYPE_SUBJECT_TEMPLATE] NVARCHAR(500),
        [TYPE_BODY_TEMPLATE] NVARCHAR(MAX),
        [TYPE_IS_ACTIVE] BIT DEFAULT 1,
        [TYPE_CREATED_BY] BIGINT DEFAULT 1,
        [TYPE_CREATED_ON] DATETIME2(3) DEFAULT GETDATE()
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'MAIL_ACCESS')
BEGIN
    CREATE TABLE [dbo].[MAIL_ACCESS] (
        [ACCESS_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
        [ACCESS_TYPE_ID] BIGINT NOT NULL,
        [ACCESS_USER_ID] BIGINT NOT NULL,
        [ACCESS_PERMISSION] NVARCHAR(20) DEFAULT 'READ',
        [ACCESS_IS_ACTIVE] BIT DEFAULT 1,
        [ACCESS_CREATED_BY] BIGINT DEFAULT 1,
        [ACCESS_CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
        CONSTRAINT FK_MAILACCESS_TYPE FOREIGN KEY ([ACCESS_TYPE_ID]) REFERENCES [EMAIL_TYPEMAST]([TYPE_ID])
    );
END
GO

-- ============================================================================
-- Seed Data - Currencies  
-- ============================================================================
IF NOT EXISTS (SELECT * FROM [DEAL_CURRMAST] WHERE [CURR_CODE] = 'INR')
BEGIN
    INSERT INTO [DEAL_CURRMAST] ([CURR_CODE], [CURR_NAME], [CURR_SYMBOL], [CURR_COUNTRY])
    VALUES ('INR', 'Indian Rupee', '₹', 'India'),
           ('USD', 'US Dollar', '$', 'United States'),
           ('EUR', 'Euro', '€', 'European Union'),
           ('GBP', 'British Pound', '£', 'United Kingdom'),
           ('JPY', 'Japanese Yen', '¥', 'Japan');
END
GO

-- Seed Data - Roles
IF NOT EXISTS (SELECT * FROM [DEAL_ROLE] WHERE [ROLE_CODE] = 'ADMIN')
BEGIN
    INSERT INTO [DEAL_ROLE] ([ROLE_CODE], [ROLE_NAME], [ROLE_DESCRIPTION])
    VALUES ('ADMIN', 'Administrator', 'Full system access'),
           ('DEALER', 'Dealer', 'Deal creation and management'),
           ('APPROVER', 'Approver', 'Deal approval authority'),
           ('VIEWER', 'Viewer', 'Read-only access');
END
GO

PRINT 'CASHDB initialization completed successfully.'
GO
