FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 5330
ENV ASPNETCORE_URLS=http://+:5330

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["src/ERPGateway/ERPGateway.csproj", "src/ERPGateway/"]
RUN dotnet restore "src/ERPGateway/ERPGateway.csproj"

COPY . .
RUN dotnet publish "src/ERPGateway/ERPGateway.csproj" \
    -c $BUILD_CONFIGURATION \
    -o /app/publish \
    --no-restore

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "ERPGateway.dll"]
