apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: erp-travel
type: Opaque
stringData:
  sa-password: "Erp@Travel2024!"
  traveldb-connection: "Server=sqlserver.erp-travel.svc.cluster.local,1433;Database=TRAVELDB;User Id=sa;Password=Erp@Travel2024!;TrustServerCertificate=True;MultipleActiveResultSets=True;Encrypt=True"
  financedb-connection: "Server=sqlserver.erp-travel.svc.cluster.local,1433;Database=FinanceServiceDb;User Id=sa;Password=Erp@Travel2024!;TrustServerCertificate=True;MultipleActiveResultSets=True;Encrypt=True"
  masterdatadb-connection: "Server=sqlserver.erp-travel.svc.cluster.local,1433;Database=MasterDataDB;User Id=sa;Password=Erp@Travel2024!;TrustServerCertificate=True;MultipleActiveResultSets=True;Encrypt=True"
  agencydb-connection: "Server=sqlserver.erp-travel.svc.cluster.local,1433;Database=AgencyServiceDb;User Id=sa;Password=Erp@Travel2024!;TrustServerCertificate=True;MultipleActiveResultSets=True;Encrypt=True"
  admindb-connection: "Server=sqlserver.erp-travel.svc.cluster.local,1433;Database=AdminServiceDb;User Id=sa;Password=Erp@Travel2024!;TrustServerCertificate=True;MultipleActiveResultSets=True;Encrypt=True"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: erp-travel
type: Opaque
stringData:
  username: "guest"
  password: "guest"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: erp-travel
type: Opaque
stringData:
  key: "TravelRequestServiceSecretKey2024!@#$%^&*()MinLength32Chars"
  issuer: "TravelRequestService"
  audience: "TravelRequestService.Clients"
