-- Module: Competency
USE DDDB;
GO

-- Table: BAND_CORECOMPETENCY
CREATE TABLE [BAND_CORECOMPETENCY] (
    [BAND_ID] DECIMAL(38) NOT NULL,
    [COMPETENCY_ID] DECIMAL(38) NOT NULL
);



-- Table: COMPETENCY_RATING_SCALE
CREATE TABLE [COMPETENCY_RATING_SCALE] (
    [COMPETENCY_ID] DECIMAL(38) NOT NULL,
    [R1_DESC] VARCHAR(250) NOT NULL,
    [R2_DESC] VARCHAR(500) NULL,
    [R3_DESC] VARCHAR(500) NOT NULL,
    [R4_DESC] VARCHAR(500) NULL,
    [R5_DESC] VARCHAR(500) NOT NULL,
    [MODIFIED_BY] DECIMAL(38) NULL,
    [MODIFIED_ON] DATETIME2(3) NULL
);



-- Table: DD_COMPENDGRAD
CREATE TABLE [DD_COMPENDGRAD] (
    [EM_MAN_COD] VARCHAR(10) NULL  -- Manager Code (JM, MM,SM, TM),
    [EM_QTN_NUM] DECIMAL(38) NULL  -- Question Number
);



-- Table: DD_COMPENDGRADEMP
CREATE TABLE [DD_COMPENDGRADEMP] (
    [EM_MAN_COD] VARCHAR(10) NULL,
    [EM_QTN_NUM] DECIMAL(38) NULL
);



-- Table: DD_COMPENDMAST
CREATE TABLE [DD_COMPENDMAST] (
    [CM_CPD_NUM] DECIMAL(38) NOT NULL  -- COMPENDENCY SERIAL NUMBER,
    [CM_CPD_NAM] VARCHAR(4000) NOT NULL  -- COMPENDENCY NAME,
    [CM_EFF_DAT] DATETIME2(3) NOT NULL  -- EFFECTIVE DATE,
    [CM_CLS_DAT] DATETIME2(3) NULL  -- CLOSURE DATE,
    [CM_CPD_REM] VARCHAR(4000) NULL  -- REMARKS,
    [CM_JOB_COD] DECIMAL(38) NULL  -- JOB CODE,
    [CM_POS_IND] VARCHAR(4000) NULL  -- POSITIVE INDICATOR,
    [CM_NEG_IND] VARCHAR(4000) NULL  -- NEGATIVE INDICATOR,
    [CM_CPD_SLF] VARCHAR(4000) NULL,
    [CM_CPD_TYPE] VARCHAR(10) NULL,
    [CM_PARENTID] DECIMAL(38) NULL
);



-- Table: DD_COMPETENCY_IND
CREATE TABLE [DD_COMPETENCY_IND] (
    [SRL_NO] DECIMAL(38) NULL  -- Serial No,
    [BAND] VARCHAR(50) NULL  -- Band,
    [COMP_NUM] DECIMAL(38) NULL  -- Competency No,
    [IND_FLAG] CHAR(1) NULL  -- Indicator Flag ( P / N ),
    [IND_DEFN] VARCHAR(4000) NULL  -- Indicator Definition
);



-- Table: DD_VTCCOMPETENCY
CREATE TABLE [DD_VTCCOMPETENCY] (
    [SRL_NO] DECIMAL(38) NULL  -- Serial Number,
    [BAND] VARCHAR(50) NULL  -- Band,
    [COMP_NUM] DECIMAL(38) NULL  -- Competency Number,
    [COMP_NAM] VARCHAR(50) NULL  -- Competency Name
);



-- Table: EMP_SPECIFIC_COMPETENCY
CREATE TABLE [EMP_SPECIFIC_COMPETENCY] (
    [EMP_SYSID] DECIMAL(38) NOT NULL,
    [COMPETENCY_ID] DECIMAL(38) NOT NULL,
    [COMPETENCY_TYPE] CHAR(1) NOT NULL,
    [DD_YEARID] DECIMAL(38) NOT NULL,
    [MODIFIED_BY] DECIMAL(38) NULL,
    [MODIFIED_ON] DATETIME2(3) NULL
);



-- Table: EMP_SPECIFIC_COMPETENCY_DEL
CREATE TABLE [EMP_SPECIFIC_COMPETENCY_DEL] (
    [EMP_SYSID] DECIMAL(38) NOT NULL,
    [COMPETENCY_ID] DECIMAL(38) NOT NULL,
    [COMPETENCY_TYPE] CHAR(1) NOT NULL,
    [DD_YEARID] DECIMAL(38) NOT NULL,
    [MODIFIED_BY] DECIMAL(38) NULL,
    [MODIFIED_ON] DATETIME2(3) NULL
);



-- Table: ROLE_SPECIFIC
CREATE TABLE [ROLE_SPECIFIC] (
    [EMP_SYSID] DECIMAL(38) NOT NULL,
    [COMPETENCY_ID] DECIMAL(38) NOT NULL,
    [EFF_FROM] DATETIME2(3) NULL,
    [EFF_TO] DATETIME2(3) NULL,
    [MODIFIED_BY] DECIMAL(38) NULL,
    [MODIFIED_ON] DATETIME2(3) NULL
);



-- Table: ROLE_SPECIFIC_DEL
CREATE TABLE [ROLE_SPECIFIC_DEL] (
    [EMP_SYSID] DECIMAL(38) NOT NULL,
    [COMPETENCY_ID] DECIMAL(38) NOT NULL,
    [EFF_FROM] DATETIME2(3) NULL,
    [EFF_TO] DATETIME2(3) NULL,
    [MODIFIED_BY] DECIMAL(38) NULL,
    [MODIFIED_ON] DATETIME2(3) NULL
);

