-- =============================================
-- Health ERP Microservices - Database Initialization
-- Creates all databases, tables, and seed data
-- Run against SQL Server with SA credentials
-- =============================================

USE [master];
GO

-- ─────────────── Create Databases ───────────────

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'HEALTHDB')
BEGIN
    CREATE DATABASE [HEALTHDB];
    PRINT 'Created database HEALTHDB';
END
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'HEALTHDB_MedicineManagement')
BEGIN
    CREATE DATABASE [HEALTHDB_MedicineManagement];
    PRINT 'Created database HEALTHDB_MedicineManagement';
END
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'HEALTHDB_HealthTransactions')
BEGIN
    CREATE DATABASE [HEALTHDB_HealthTransactions];
    PRINT 'Created database HEALTHDB_HealthTransactions';
END
GO

-- ═══════════════════════════════════════════════
-- HEALTHDB  (shared by Accident, Checkup, Insurance, Masters, MedicalVisit)
-- ═══════════════════════════════════════════════

USE [HEALTHDB];
GO

-- ─────────────── Masters Module ───────────────

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LOV_TYPEMASTER')
CREATE TABLE LOV_TYPEMASTER (
    LOV_TYPECODE   CHAR(3)       NOT NULL,
    LOV_TYPENAME   VARCHAR(100)  NOT NULL,
    LOV_TYPEDESC   VARCHAR(255)  NULL,
    CONSTRAINT PK_LOV_TYPEMASTER PRIMARY KEY (LOV_TYPECODE)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LOV_MASTER')
CREATE TABLE LOV_MASTER (
    LOV_ID         BIGINT IDENTITY(1,1) NOT NULL,
    LOV_TYPE       CHAR(3)       NOT NULL,
    LOV_CODE       VARCHAR(20)   NOT NULL,
    LOV_NAME       VARCHAR(100)  NOT NULL,
    LOV_DESC       VARCHAR(255)  NULL,
    LOV_ACTIVE     BIT           NOT NULL DEFAULT 1,
    CONSTRAINT PK_LOV_MASTER PRIMARY KEY (LOV_ID),
    CONSTRAINT FK_LOV_MASTER_TYPE FOREIGN KEY (LOV_TYPE) REFERENCES LOV_TYPEMASTER(LOV_TYPECODE)
);
GO
CREATE NONCLUSTERED INDEX IX_LOV_MASTER_TYPE ON LOV_MASTER(LOV_TYPE);
GO

-- ─────────────── Accident Module ───────────────

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ACCIDENT_SEVERITY')
CREATE TABLE ACCIDENT_SEVERITY (
    SEVERITY_ID    BIGINT IDENTITY(1,1) NOT NULL,
    SEVERITY_GUID  UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    CODE           VARCHAR(20)   NOT NULL,
    NAME           VARCHAR(100)  NOT NULL,
    DESCRIPTION    VARCHAR(255)  NULL,
    IS_ACTIVE      BIT           NOT NULL DEFAULT 1,
    CONSTRAINT PK_ACCIDENT_SEVERITY PRIMARY KEY (SEVERITY_ID)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ACCIDENT_STATUS')
CREATE TABLE ACCIDENT_STATUS (
    STATUS_ID      BIGINT IDENTITY(1,1) NOT NULL,
    STATUS_GUID    UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    CODE           VARCHAR(20)   NOT NULL,
    NAME           VARCHAR(100)  NOT NULL,
    DESCRIPTION    VARCHAR(255)  NULL,
    IS_ACTIVE      BIT           NOT NULL DEFAULT 1,
    CONSTRAINT PK_ACCIDENT_STATUS PRIMARY KEY (STATUS_ID)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'CATEGORY_INJURY')
CREATE TABLE CATEGORY_INJURY (
    CATEGORY_ID    BIGINT IDENTITY(1,1) NOT NULL,
    CATEGORY_GUID  UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    NAME           VARCHAR(100)  NOT NULL,
    DESCRIPTION    VARCHAR(255)  NULL,
    IS_ACTIVE      BIT           NOT NULL DEFAULT 1,
    CONSTRAINT PK_CATEGORY_INJURY PRIMARY KEY (CATEGORY_ID)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'NATURE_INJURY')
CREATE TABLE NATURE_INJURY (
    NATURE_ID      BIGINT IDENTITY(1,1) NOT NULL,
    NATURE_GUID    UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    NAME           VARCHAR(100)  NOT NULL,
    DESCRIPTION    VARCHAR(255)  NULL,
    IS_ACTIVE      BIT           NOT NULL DEFAULT 1,
    CONSTRAINT PK_NATURE_INJURY PRIMARY KEY (NATURE_ID)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ACC_CONTRCT_LST')
CREATE TABLE ACC_CONTRCT_LST (
    CONTRACTOR_ID   BIGINT IDENTITY(1,1) NOT NULL,
    CONTRACTOR_GUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    NAME            VARCHAR(200)  NOT NULL,
    CONTACT_PERSON  VARCHAR(100)  NULL,
    PHONE           VARCHAR(20)   NULL,
    EMAIL           VARCHAR(100)  NULL,
    IS_ACTIVE       BIT           NOT NULL DEFAULT 1,
    CONSTRAINT PK_ACC_CONTRCT_LST PRIMARY KEY (CONTRACTOR_ID)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DAILY_ACC_FIR')
CREATE TABLE DAILY_ACC_FIR (
    ACC_ID          BIGINT IDENTITY(1,1) NOT NULL,
    ACC_GUID        UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    ACC_NUM         BIGINT        NOT NULL,
    ACC_COM_COD     VARCHAR(3)    NOT NULL,
    ACC_DATE        DATETIME      NOT NULL,
    ACC_TIME        VARCHAR(10)   NULL,
    ACC_LOCATION    VARCHAR(200)  NULL,
    ACC_DESCRIPTION NVARCHAR(MAX) NULL,
    BODY_PART       VARCHAR(100)  NULL,
    SEVERITY_ID     BIGINT        NULL,
    STATUS_ID       BIGINT        NULL,
    CATEGORY_ID     BIGINT        NULL,
    NATURE_ID       BIGINT        NULL,
    MEDICAL_CENTRE  VARCHAR(200)  NULL,
    TREATMENT_GIVEN NVARCHAR(MAX) NULL,
    ENTERED_USER_ID VARCHAR(50)   NULL,
    ENTERED_DATE    DATETIME      NOT NULL DEFAULT GETDATE(),
    UPDATED_USER_ID VARCHAR(50)   NULL,
    UPDATED_DATE    DATETIME      NULL,
    IS_DELETED      BIT           NOT NULL DEFAULT 0,
    CONSTRAINT PK_DAILY_ACC_FIR PRIMARY KEY (ACC_ID),
    CONSTRAINT FK_ACC_SEVERITY FOREIGN KEY (SEVERITY_ID) REFERENCES ACCIDENT_SEVERITY(SEVERITY_ID),
    CONSTRAINT FK_ACC_STATUS FOREIGN KEY (STATUS_ID) REFERENCES ACCIDENT_STATUS(STATUS_ID),
    CONSTRAINT FK_ACC_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY_INJURY(CATEGORY_ID),
    CONSTRAINT FK_ACC_NATURE FOREIGN KEY (NATURE_ID) REFERENCES NATURE_INJURY(NATURE_ID)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ACC_PERS_INJ')
CREATE TABLE ACC_PERS_INJ (
    PERSON_ID       BIGINT IDENTITY(1,1) NOT NULL,
    PERSON_GUID     UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    ACC_ID          BIGINT        NOT NULL,
    PERSON_NAME     VARCHAR(200)  NOT NULL,
    PERSON_TYPE     VARCHAR(20)   NOT NULL,
    BADGE_NUMBER    VARCHAR(20)   NULL,
    DEPARTMENT      VARCHAR(100)  NULL,
    CONTRACTOR_ID   BIGINT        NULL,
    CONSTRAINT PK_ACC_PERS_INJ PRIMARY KEY (PERSON_ID),
    CONSTRAINT FK_PERS_ACC FOREIGN KEY (ACC_ID) REFERENCES DAILY_ACC_FIR(ACC_ID),
    CONSTRAINT FK_PERS_CONTRACTOR FOREIGN KEY (CONTRACTOR_ID) REFERENCES ACC_CONTRCT_LST(CONTRACTOR_ID)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'AUDIT_LOG')
CREATE TABLE AUDIT_LOG (
    LOG_ID          BIGINT IDENTITY(1,1) NOT NULL,
    EVENT_TYPE      VARCHAR(20)   NOT NULL,
    TABLE_NAME      VARCHAR(100)  NOT NULL,
    ENTITY_ID       BIGINT        NULL,
    CHANGES         NVARCHAR(MAX) NULL,
    CREATED_DATE    DATETIME      NOT NULL DEFAULT GETDATE(),
    CREATED_BY      VARCHAR(50)   NULL,
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (LOG_ID)
);
GO

-- ─────────────── Checkup Module ───────────────

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'FIELD_TYP_MAST')
CREATE TABLE FIELD_TYP_MAST (
    FTM_FLD_TYP    VARCHAR(3)    NOT NULL,
    FTM_FLD_DESC   VARCHAR(100)  NULL,
    CONSTRAINT PK_FIELD_TYP_MAST PRIMARY KEY (FTM_FLD_TYP)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'CHKUP_SYMP_MAST')
CREATE TABLE CHKUP_SYMP_MAST (
    CSM_SYMP_ID    BIGINT IDENTITY(1,1) NOT NULL,
    CSM_SYMP_NAME  VARCHAR(100)  NOT NULL,
    CSM_FLD_TYP    VARCHAR(3)    NULL,
    CSM_ACTIVE     BIT           NOT NULL DEFAULT 1,
    CONSTRAINT PK_CHKUP_SYMP_MAST PRIMARY KEY (CSM_SYMP_ID),
    CONSTRAINT FK_CSM_FLD_TYP FOREIGN KEY (CSM_FLD_TYP) REFERENCES FIELD_TYP_MAST(FTM_FLD_TYP)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TEST_MAST')
CREATE TABLE TEST_MAST (
    TM_TST_COD     VARCHAR(10)   NOT NULL,
    TM_TST_NAME    VARCHAR(100)  NOT NULL,
    TM_ACTIVE      BIT           NOT NULL DEFAULT 1,
    CONSTRAINT PK_TEST_MAST PRIMARY KEY (TM_TST_COD)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'CHECKUP_MAST')
CREATE TABLE CHECKUP_MAST (
    CM_CHKUP_COD   VARCHAR(10)   NOT NULL,
    CM_CHKUP_NAME  VARCHAR(100)  NOT NULL,
    CM_ACTIVE      BIT           NOT NULL DEFAULT 1,
    CONSTRAINT PK_CHECKUP_MAST PRIMARY KEY (CM_CHKUP_COD)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'HEALTH_MAIN')
CREATE TABLE HEALTH_MAIN (
    HM_HLTH_NUM    BIGINT        NOT NULL,
    HM_EMP_NUM     BIGINT        NOT NULL,
    HM_COM_COD     VARCHAR(3)    NOT NULL,
    HM_CHKUP_COD   VARCHAR(10)   NULL,
    HM_CHKUP_DATE  DATETIME      NULL,
    HM_DOCTOR      VARCHAR(100)  NULL,
    HM_REMARKS     NVARCHAR(MAX) NULL,
    HM_STATUS      VARCHAR(20)   NULL DEFAULT 'PENDING',
    CONSTRAINT PK_HEALTH_MAIN PRIMARY KEY (HM_HLTH_NUM)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'HEALTH_SUB')
CREATE TABLE HEALTH_SUB (
    HS_HLTH_NUM    BIGINT        NOT NULL,
    HS_TST_COD     VARCHAR(10)   NOT NULL,
    HS_RESULT      VARCHAR(100)  NULL,
    HS_REMARKS     VARCHAR(255)  NULL,
    CONSTRAINT PK_HEALTH_SUB PRIMARY KEY (HS_HLTH_NUM, HS_TST_COD),
    CONSTRAINT FK_HS_MAIN FOREIGN KEY (HS_HLTH_NUM) REFERENCES HEALTH_MAIN(HM_HLTH_NUM)
);
GO

-- ─────────────── MedicalVisit Module ───────────────

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'VISIT_MAIN')
CREATE TABLE VISIT_MAIN (
    VM_VISIT_NUM   BIGINT        NOT NULL,
    VM_EMP_NUM     BIGINT        NOT NULL,
    VM_COM_COD     VARCHAR(3)    NOT NULL,
    VM_VISIT_DATE  DATETIME      NOT NULL,
    VM_VISIT_TIME  VARCHAR(10)   NULL,
    VM_DOCTOR      VARCHAR(100)  NULL,
    VM_DIAGNOSIS   NVARCHAR(MAX) NULL,
    VM_TREATMENT   NVARCHAR(MAX) NULL,
    VM_STATUS      VARCHAR(20)   NULL DEFAULT 'ACTIVE',
    CONSTRAINT PK_VISIT_MAIN PRIMARY KEY (VM_VISIT_NUM)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'VISIT_SUB')
CREATE TABLE VISIT_SUB (
    VS_VISIT_NUM   BIGINT        NOT NULL,
    VS_TST_COD     VARCHAR(10)   NOT NULL,
    VS_RESULT      VARCHAR(100)  NULL,
    VS_REMARKS     VARCHAR(255)  NULL,
    CONSTRAINT PK_VISIT_SUB PRIMARY KEY (VS_VISIT_NUM, VS_TST_COD),
    CONSTRAINT FK_VS_MAIN FOREIGN KEY (VS_VISIT_NUM) REFERENCES VISIT_MAIN(VM_VISIT_NUM)
);
GO

-- ─────────────── Medicine Module (shared DB) ───────────────

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'MEDICINE_TYPMAST')
CREATE TABLE MEDICINE_TYPMAST (
    MT_TYP_COD     VARCHAR(3)    NOT NULL,
    MT_TYP_DESC    VARCHAR(100)  NOT NULL,
    CONSTRAINT PK_MEDICINE_TYPMAST PRIMARY KEY (MT_TYP_COD)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'MEDICINE_PKG')
CREATE TABLE MEDICINE_PKG (
    MP_PKG_COD     VARCHAR(3)    NOT NULL,
    MP_PKG_DESC    VARCHAR(100)  NOT NULL,
    CONSTRAINT PK_MEDICINE_PKG PRIMARY KEY (MP_PKG_COD)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'MEDICINE_MAST')
CREATE TABLE MEDICINE_MAST (
    MM_MED_COD     VARCHAR(10)   NOT NULL,
    MM_MED_NAME    VARCHAR(200)  NOT NULL,
    MM_TYP_COD     VARCHAR(3)    NULL,
    MM_PKG_COD     VARCHAR(3)    NULL,
    MM_UNIT_PRICE  DECIMAL(18,2) NULL DEFAULT 0,
    MM_STOCK_QTY   DECIMAL(18,2) NULL DEFAULT 0,
    MM_REORDER_LVL DECIMAL(18,2) NULL DEFAULT 0,
    MM_ACTIVE      BIT           NOT NULL DEFAULT 1,
    CONSTRAINT PK_MEDICINE_MAST PRIMARY KEY (MM_MED_COD),
    CONSTRAINT FK_MM_TYPE FOREIGN KEY (MM_TYP_COD) REFERENCES MEDICINE_TYPMAST(MT_TYP_COD),
    CONSTRAINT FK_MM_PKG FOREIGN KEY (MM_PKG_COD) REFERENCES MEDICINE_PKG(MP_PKG_COD)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DOCATTEND_MAST')
CREATE TABLE DOCATTEND_MAST (
    DA_DOC_COD     VARCHAR(10)   NOT NULL,
    DA_DOC_NAME    VARCHAR(200)  NOT NULL,
    DA_SPECIALITY  VARCHAR(100)  NULL,
    DA_ACTIVE      BIT           NOT NULL DEFAULT 1,
    CONSTRAINT PK_DOCATTEND_MAST PRIMARY KEY (DA_DOC_COD)
);
GO

-- ─────────────── Insurance Module (EF managed, create minimal) ───────────────

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'INSURANCE_PLAN_MASTER')
CREATE TABLE INSURANCE_PLAN_MASTER (
    PLAN_ID        BIGINT IDENTITY(1,1) NOT NULL,
    PLAN_CODE      VARCHAR(20)   NOT NULL,
    PLAN_NAME      VARCHAR(200)  NOT NULL,
    PLAN_TYPE      VARCHAR(50)   NULL,
    PREMIUM_AMOUNT DECIMAL(18,2) NULL DEFAULT 0,
    COVERAGE_LIMIT DECIMAL(18,2) NULL DEFAULT 0,
    IS_ACTIVE      BIT           NOT NULL DEFAULT 1,
    CONSTRAINT PK_INSURANCE_PLAN_MASTER PRIMARY KEY (PLAN_ID)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'INSURANCE_ENROLLMENT')
CREATE TABLE INSURANCE_ENROLLMENT (
    ENROLLMENT_ID   BIGINT IDENTITY(1,1) NOT NULL,
    EMP_SYS_ID      BIGINT        NOT NULL,
    PLAN_ID         BIGINT        NOT NULL,
    COVERAGE_TYPE   VARCHAR(50)   NULL,
    START_DATE      DATETIME      NOT NULL,
    END_DATE        DATETIME      NULL,
    STATUS          VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT PK_INSURANCE_ENROLLMENT PRIMARY KEY (ENROLLMENT_ID),
    CONSTRAINT FK_ENROLL_PLAN FOREIGN KEY (PLAN_ID) REFERENCES INSURANCE_PLAN_MASTER(PLAN_ID)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'INSURANCE_CLAIM')
CREATE TABLE INSURANCE_CLAIM (
    CLAIM_ID        BIGINT IDENTITY(1,1) NOT NULL,
    ENROLLMENT_ID   BIGINT        NOT NULL,
    CLAIM_TYPE      VARCHAR(50)   NULL,
    CLAIM_AMOUNT    DECIMAL(18,2) NOT NULL,
    SERVICE_DATE    DATETIME      NOT NULL,
    STATUS          VARCHAR(20)   NOT NULL DEFAULT 'SUBMITTED',
    SUBMITTED_DATE  DATETIME      NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_INSURANCE_CLAIM PRIMARY KEY (CLAIM_ID),
    CONSTRAINT FK_CLAIM_ENROLLMENT FOREIGN KEY (ENROLLMENT_ID) REFERENCES INSURANCE_ENROLLMENT(ENROLLMENT_ID)
);
GO

-- ═══════════════════════════════════════════════
-- HEALTHDB_MedicineManagement (separate DB for medicine service)
-- ═══════════════════════════════════════════════

USE [HEALTHDB_MedicineManagement];
GO

-- EF Core will auto-migrate these tables. Create schema placeholder only.
PRINT 'HEALTHDB_MedicineManagement ready for EF Core migrations.';
GO

-- ═══════════════════════════════════════════════
-- HEALTHDB_HealthTransactions (separate DB for transaction service)
-- ═══════════════════════════════════════════════

USE [HEALTHDB_HealthTransactions];
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'CHKUP_PRE_MAIN')
CREATE TABLE CHKUP_PRE_MAIN (
    CPM_EMP_NUM     BIGINT        NOT NULL,
    CPM_COM_COD     VARCHAR(3)    NOT NULL,
    CPM_HLTH_NUM    BIGINT        NOT NULL,
    CPM_PHYS_HNDCP  NVARCHAR(MAX) NULL,
    CPM_PROPOSED_EMP VARCHAR(200) NULL,
    CPM_IDENT_MARKS VARCHAR(200)  NULL,
    CPM_FINAL_REMARKS NVARCHAR(MAX) NULL,
    CPM_FIT_PH      CHAR(1)       NULL,
    CPM_FIT_FINAL   VARCHAR(50)   NULL,
    CPM_CHKUP_DATE  DATETIME      NULL,
    CONSTRAINT PK_CHKUP_PRE_MAIN PRIMARY KEY (CPM_EMP_NUM, CPM_COM_COD)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'HLTH_CHKUP_CARD')
CREATE TABLE HLTH_CHKUP_CARD (
    HCC_HLTH_NUM        BIGINT        NOT NULL,
    HCC_EMP_NUM         BIGINT        NULL,
    HCC_EMP_DATE        DATETIME      NULL,
    HCC_COM_COD         VARCHAR(3)    NULL,
    HCC_PERSONAL_DET    NVARCHAR(MAX) NULL,
    HCC_COMPLAINT_DET   NVARCHAR(MAX) NULL,
    HCC_ADV_REMARK1     NVARCHAR(MAX) NULL,
    HCC_ADV_REMARK2     NVARCHAR(MAX) NULL,
    HCC_DOC_DATE1       DATETIME      NULL,
    HCC_DOC_DATE2       DATETIME      NULL,
    HCC_ADV_FOLLOW1     NVARCHAR(MAX) NULL,
    HCC_ADV_FOLLOW2     NVARCHAR(MAX) NULL,
    CONSTRAINT PK_HLTH_CHKUP_CARD PRIMARY KEY (HCC_HLTH_NUM)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'HLTH_CHKCARD_SUB')
CREATE TABLE HLTH_CHKCARD_SUB (
    HCS_HLTH_NUM   BIGINT        NOT NULL,
    HCS_SYMP_ID    BIGINT        NOT NULL,
    HCS_FLAG_YN    CHAR(1)       NULL,
    HCS_SYMP_VAL   VARCHAR(100)  NULL,
    HCS_EMP_NUM    BIGINT        NULL,
    CONSTRAINT PK_HLTH_CHKCARD_SUB PRIMARY KEY (HCS_HLTH_NUM, HCS_SYMP_ID),
    CONSTRAINT FK_HCS_CARD FOREIGN KEY (HCS_HLTH_NUM) REFERENCES HLTH_CHKUP_CARD(HCC_HLTH_NUM) ON DELETE CASCADE
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'CHKUP_PFI_HIST')
CREATE TABLE CHKUP_PFI_HIST (
    CPH_HLTH_NUM   BIGINT        NOT NULL,
    CPH_SYMP_ID    BIGINT        NOT NULL,
    CPH_FLAG_YN    CHAR(1)       NULL,
    CPH_SYMP_VAL   VARCHAR(100)  NULL,
    CPH_EMP_NUM    BIGINT        NULL,
    CONSTRAINT PK_CHKUP_PFI_HIST PRIMARY KEY (CPH_HLTH_NUM, CPH_SYMP_ID)
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'HEALTH_DYN_DET')
CREATE TABLE HEALTH_DYN_DET (
    HDD_HLTH_NUM   BIGINT        NOT NULL,
    HDD_SYMP_ID    BIGINT        NOT NULL,
    HDD_FLAG_YN    CHAR(1)       NULL,
    HDD_SYMP_VAL   VARCHAR(100)  NULL,
    HDD_EMP_NUM    BIGINT        NULL,
    CONSTRAINT PK_HEALTH_DYN_DET PRIMARY KEY (HDD_HLTH_NUM, HDD_SYMP_ID)
);
GO

-- ═══════════════════════════════════════════════
-- Seed Data
-- ═══════════════════════════════════════════════

USE [HEALTHDB];
GO

-- Masters seed
IF NOT EXISTS (SELECT 1 FROM LOV_TYPEMASTER WHERE LOV_TYPECODE = 'MED')
BEGIN
    INSERT INTO LOV_TYPEMASTER (LOV_TYPECODE, LOV_TYPENAME, LOV_TYPEDESC) VALUES
        ('MED', 'Medicine Type', 'Types of medicines'),
        ('INJ', 'Injury Type', 'Types of injuries'),
        ('TST', 'Test Type', 'Types of medical tests'),
        ('CVG', 'Coverage Type', 'Insurance coverage types'),
        ('CLM', 'Claim Type', 'Insurance claim types'),
        ('SYM', 'Symptom Type', 'Types of symptoms');

    SET IDENTITY_INSERT LOV_MASTER ON;
    INSERT INTO LOV_MASTER (LOV_ID, LOV_TYPE, LOV_CODE, LOV_NAME, LOV_DESC) VALUES
        (1, 'MED', 'TAB', 'Tablet', 'Tablet form medicine'),
        (2, 'MED', 'CAP', 'Capsule', 'Capsule form medicine'),
        (3, 'MED', 'SYR', 'Syrup', 'Liquid syrup medicine'),
        (4, 'MED', 'INJ', 'Injection', 'Injectable medicine'),
        (5, 'MED', 'OIN', 'Ointment', 'Topical ointment'),
        (6, 'INJ', 'CUT', 'Cut', 'Cut/laceration injury'),
        (7, 'INJ', 'BRN', 'Burn', 'Burn injury'),
        (8, 'INJ', 'FRC', 'Fracture', 'Bone fracture'),
        (9, 'INJ', 'SPN', 'Sprain', 'Sprain/strain injury'),
        (10, 'INJ', 'BRS', 'Bruise', 'Bruise/contusion'),
        (11, 'TST', 'BLD', 'Blood Test', 'Complete blood count'),
        (12, 'TST', 'URN', 'Urine Test', 'Urinalysis'),
        (13, 'TST', 'XRY', 'X-Ray', 'Radiographic imaging'),
        (14, 'TST', 'ECG', 'ECG', 'Electrocardiogram'),
        (15, 'TST', 'EYE', 'Eye Test', 'Vision testing');
    SET IDENTITY_INSERT LOV_MASTER OFF;

    PRINT 'Masters seed data inserted.';
END
GO

-- Accident severity/status seed
IF NOT EXISTS (SELECT 1 FROM ACCIDENT_SEVERITY WHERE CODE = 'CRITICAL')
BEGIN
    INSERT INTO ACCIDENT_SEVERITY (CODE, NAME, DESCRIPTION) VALUES
        ('CRITICAL', 'Critical', 'Life-threatening or severe injury'),
        ('MAJOR', 'Major', 'Significant injury requiring hospital'),
        ('MINOR', 'Minor', 'Minor injury, first-aid treatment'),
        ('NEARMISS', 'Near Miss', 'No injury but could have been severe');

    INSERT INTO ACCIDENT_STATUS (CODE, NAME, DESCRIPTION) VALUES
        ('NEW', 'New', 'Newly reported'),
        ('INPROG', 'In Progress', 'Under investigation'),
        ('RESOLVED', 'Resolved', 'Investigation complete'),
        ('CLOSED', 'Closed', 'All actions completed');

    PRINT 'Accident seed data inserted.';
END
GO

PRINT '=== Database initialization complete ===';
GO
