<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GroupManagementService.Domain\GroupManagementService.Domain.csproj" />
    <ProjectReference Include="..\GroupManagementService.Application\GroupManagementService.Application.csproj" />
    <ProjectReference Include="..\GroupManagementService.Infrastructure\GroupManagementService.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.19.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
