-- ==========================================
-- VEHICLE TRACKING MODULE - Table Definitions
-- Database: SCIDB
-- Module: Vehicle Management & Tracking
-- Created: March 9, 2026
-- ==========================================

USE SCIDB;
GO

-- Table: VEHICLE_MAST (Vehicle Master)
CREATE TABLE [VEHICLE_MAST] (
    [VH_SRL_NUM] BIGINT NOT NULL,
    [VH_REG_NUM1] VARCHAR(3) NOT NULL,
    [VH_REG_NUM2] VARCHAR(2) NULL,
    [VH_REG_NUM3] VARCHAR(2) NULL,
    [VH_REG_NUM4] VARCHAR(4) NOT NULL,
    [VH_REG_DAT] DATETIME2(3) NULL,
    [VH_UPD_DAT] DATETIME2(3) NOT NULL,
    [VH_UPD_USR] VARCHAR(25) NOT NULL,
    [VH_UPD_NUM] BIGINT NOT NULL,
    [VH_LOG_USR] VARCHAR(25) NULL,
    [VH_LOG_NUM] BIGINT NULL,
    [VH_LOG_DAT] DATETIME2(3) NULL,
    CONSTRAINT [PK_VEHICLE_MAST] PRIMARY KEY ([VH_SRL_NUM])
);

-- Table: VEHICLE_STAGE (Vehicle Stage Tracking)
CREATE TABLE [VEHICLE_STAGE] (
    [ST_TRN_NUM] BIGINT NOT NULL,
    [ST_TRK_NUM] BIGINT NOT NULL,
    [ST_STG_SRL] BIGINT NOT NULL,
    [ST_ENT_DAT] DATETIME2(3) NOT NULL,
    [ST_ENT_USR] VARCHAR(25) NULL,
    [ST_ENT_NUM] BIGINT NOT NULL,
    [ST_LEV_DAT] DATETIME2(3) NOT NULL,
    [ST_ROL_COD] BIGINT NOT NULL,
    [ST_DEC_FLG] CHAR(1) NULL,
    [ST_CAN_STS] CHAR(1) NOT NULL,
    [ST_TIM_TKN] DECIMAL(38) NULL,
    [VT_STG_COD] BIGINT NOT NULL,
    [ST_STG_COM] VARCHAR(100) NULL,
    [VT_DEL_DAT] DATETIME2(3) NOT NULL,
    [VT_DEL_USR] VARCHAR(25) NULL,
    [VT_DEL_NUM] BIGINT NOT NULL
);

-- Table: VEHICLE_TRAN (Vehicle Transaction)
CREATE TABLE [VEHICLE_TRAN] (
    [TR_TRK_NUM] BIGINT NULL,
    [TR_VEH_SRL] BIGINT NULL,
    [TR_PTY_NAM] VARCHAR(200) NULL,
    [TR_REP_DAT] DATETIME2(3) NULL,
    [TR_PRP_COD] BIGINT NULL,
    [TR_STG_PRV] BIGINT NULL,
    [TR_PRV_DAT] DATETIME2(3) NULL,
    [TR_STG_CUR] DECIMAL(38) NULL,
    [TR_GAT_NAM] VARCHAR(25) NULL,
    [TR_TRN_NUM] VARCHAR(25) NULL,
    [TR_PRO_COD] VARCHAR(25) NULL,
    [TR_PRO_QTY] DECIMAL(38) NULL,
    [TR_STG_COM] VARCHAR(100) NULL,
    [TR_DRV_NAM] VARCHAR(100) NULL,
    [TR_DRV_CELL] VARCHAR(15) NULL,
    [TR_TYR_WGT] DECIMAL(38) NULL,
    [TR_GRS_WGT] DECIMAL(38) NULL,
    [TR_VEH_STS] CHAR(1) NULL,
    [TR_LOG_ENT_USR] VARCHAR(255) NULL,
    [TR_LOG_ENT_NUM] VARCHAR(255) NULL,
    [TR_LOG_ENT_DATE] DATETIME2(3) NULL,
    [TR_MAIN_PURPOSE] BIGINT NULL,
    [TR_SUP_COD] VARCHAR(25) NULL
);

-- Table: VEHICLE_INVOICE
CREATE TABLE [VEHICLE_INVOICE] (
    [IN_TRK_NUM] BIGINT NOT NULL,
    [IN_REF_NUM] BIGINT NOT NULL,
    [IN_INV_SRL] BIGINT NOT NULL,
    [IN_ORC_INV] BIGINT NULL,
    [IN_CHN_INV] BIGINT NOT NULL,
    [IN_CUS_COD] VARCHAR(25) NULL,
    [IN_CAN_FLG] CHAR(1) NULL,
    [IN_MOD_NUM] BIGINT NOT NULL,
    [IN_MOD_USR] VARCHAR(25) NOT NULL,
    [IN_MOD_DAT] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_VEHICLE_INVOICE] PRIMARY KEY ([IN_TRK_NUM], [IN_REF_NUM], [IN_INV_SRL])
);

-- Table: VEHICLE_DIRECT_ENTRY
CREATE TABLE [VEHICLE_DIRECT_ENTRY] (
    [VDE_ID] BIGINT NOT NULL,
    [VDE_TRK_NUM] BIGINT NOT NULL,
    [VDE_ENT_DAT] DATETIME2(3) NOT NULL,
    [VDE_ENT_USR] VARCHAR(25) NOT NULL,
    CONSTRAINT [PK_VEHICLE_DIRECT_ENTRY] PRIMARY KEY ([VDE_ID])
);

-- Table: DECISION_FLAG
CREATE TABLE [DECISION_FLAG] (
    [DF_TRC_NUM] BIGINT NOT NULL,
    [DF_PUR_COD] BIGINT NOT NULL,
    [DF_STG_COD] BIGINT NOT NULL,
    [DF_STG_DEC] CHAR(1) NOT NULL,
    [DF_CAN_FLG] CHAR(1) NOT NULL,
    [DF_REF_NUM] BIGINT NULL,
    [DF_UPD_DAT] DATETIME2(3) NULL,
    [DF_REMARK] VARCHAR(100) NULL,
    CONSTRAINT [PK_DECISION_FLAG] PRIMARY KEY ([DF_TRC_NUM], [DF_PUR_COD], [DF_STG_COD])
);

-- Table: DELLOG_VEHICLE_STAGE (Deletion Log for Vehicle Stage)
CREATE TABLE [DELLOG_VEHICLE_STAGE] (
    [ST_TRN_NUM] BIGINT NOT NULL,
    [ST_TRK_NUM] BIGINT NOT NULL,
    [ST_STG_SRL] BIGINT NOT NULL,
    [ST_ENT_DAT] DATETIME2(3) NOT NULL,
    [ST_ENT_USR] VARCHAR(25) NULL,
    [ST_ENT_NUM] BIGINT NOT NULL,
    [ST_LEV_DAT] DATETIME2(3) NOT NULL,
    [ST_ROL_COD] BIGINT NOT NULL,
    [ST_DEC_FLG] CHAR(1) NULL,
    [ST_CAN_STS] CHAR(1) NOT NULL,
    [ST_TIM_TKN] DECIMAL(38) NULL,
    [VT_STG_COD] BIGINT NOT NULL,
    [ST_STG_COM] VARCHAR(100) NULL,
    [VT_DEL_DAT] DATETIME2(3) NOT NULL,
    [VT_DEL_USR] VARCHAR(25) NULL,
    [VT_DEL_NUM] BIGINT NOT NULL
);

-- Table: LOG_VEHICLE_MAST (Log - Vehicle Master)
CREATE TABLE [LOG_VEHICLE_MAST] (
    [VH_SRL_NUM] BIGINT NOT NULL,
    [VH_REG_NUM1] VARCHAR(3) NOT NULL,
    [VH_REG_NUM2] VARCHAR(2) NULL,
    [VH_REG_NUM3] VARCHAR(2) NULL,
    [VH_REG_NUM4] VARCHAR(4) NOT NULL,
    [VH_REG_DAT] DATETIME2(3) NULL,
    [VH_UPD_DAT] DATETIME2(3) NOT NULL,
    [VH_UPD_USR] VARCHAR(25) NOT NULL,
    [VH_UPD_NUM] BIGINT NOT NULL,
    [VH_LOG_USR] VARCHAR(25) NULL,
    [VH_LOG_NUM] BIGINT NULL,
    [VH_LOG_DAT] DATETIME2(3) NULL
);

-- Table: LOG_VEHICLE_STAGE (Log - Vehicle Stage)
CREATE TABLE [LOG_VEHICLE_STAGE] (
    [ST_TRN_NUM] BIGINT NOT NULL,
    [ST_TRK_NUM] BIGINT NOT NULL,
    [ST_STG_SRL] BIGINT NOT NULL,
    [ST_ENT_DAT] DATETIME2(3) NOT NULL,
    [ST_ENT_USR] VARCHAR(25) NOT NULL,
    [ST_ENT_NUM] BIGINT NOT NULL,
    [ST_LEV_DAT] DATETIME2(3) NOT NULL,
    [ST_ROL_COD] BIGINT NOT NULL,
    [ST_DEC_FLG] CHAR(1) NULL,
    [ST_CAN_STS] CHAR(1) NOT NULL,
    [ST_TIM_TKN] DECIMAL(38) NULL,
    [VT_STG_COD] BIGINT NOT NULL,
    [ST_STG_COM] VARCHAR(100) NULL,
    [ST_LOG_USR] VARCHAR(25) NULL,
    [ST_LOG_NAM] BIGINT NULL,
    [ST_LOG_DAT] DATETIME2(3) NULL
);

-- Table: LOG_VEHICLE_TRAN (Log - Vehicle Transaction)
CREATE TABLE [LOG_VEHICLE_TRAN] (
    [TR_TRK_NUM] BIGINT NULL,
    [TR_VEH_SRL] BIGINT NULL,
    [TR_PTY_NAM] VARCHAR(200) NULL,
    [TR_REP_DAT] DATETIME2(3) NULL,
    [TR_PRP_COD] BIGINT NULL,
    [TR_STG_PRV] BIGINT NULL,
    [TR_PRV_DAT] DATETIME2(3) NULL,
    [TR_STG_CUR] DECIMAL(38) NULL,
    [TR_GAT_NAM] VARCHAR(25) NULL,
    [TR_TRN_NUM] VARCHAR(25) NULL,
    [TR_PRO_COD] VARCHAR(25) NULL,
    [TR_PRO_QTY] DECIMAL(38) NULL,
    [TR_STG_COM] VARCHAR(100) NULL,
    [TR_DRV_NAM] VARCHAR(100) NULL,
    [TR_DRV_CELL] VARCHAR(15) NULL,
    [TR_TYR_WGT] DECIMAL(38) NULL,
    [TR_GRS_WGT] DECIMAL(38) NULL,
    [TR_VEH_STS] CHAR(1) NULL,
    [TR_LOG_ENT_USR] VARCHAR(255) NULL,
    [TR_LOG_ENT_NUM] VARCHAR(255) NULL,
    [TR_LOG_ENT_DATE] DATETIME2(3) NULL,
    [TR_MAIN_PURPOSE] BIGINT NULL,
    [TR_SUP_COD] VARCHAR(25) NULL
);

-- Table: LOG_VEHICLE_INVOICE (Log - Vehicle Invoice)
CREATE TABLE [LOG_VEHICLE_INVOICE] (
    [IN_TRK_NUM] BIGINT NOT NULL,
    [IN_REF_NUM] BIGINT NOT NULL,
    [IN_INV_SRL] BIGINT NOT NULL,
    [IN_ORC_INV] BIGINT NULL,
    [IN_CHN_INV] BIGINT NOT NULL,
    [IN_CUS_COD] VARCHAR(25) NULL,
    [IN_CAN_FLG] CHAR(1) NULL,
    [IN_MOD_NUM] BIGINT NOT NULL,
    [IN_MOD_USR] VARCHAR(25) NOT NULL,
    [IN_MOD_DAT] DATETIME2(3) NOT NULL
);

-- Table: STAGE_MAST (Stage Master)
CREATE TABLE [STAGE_MAST] (
    [ST_STG_COD] BIGINT NOT NULL,
    [ST_OPT_NAM] VARCHAR(25) NOT NULL,
    [ST_UPD_USR] VARCHAR(25) NULL,
    [ST_UPD_NUM] BIGINT NULL,
    [ST_UPD_DAT] DATETIME2(3) NULL,
    CONSTRAINT [PK_STAGE_MAST] PRIMARY KEY ([ST_STG_COD])
);

-- Table: PURPOSE_MAST (Purpose Master)
CREATE TABLE [PURPOSE_MAST] (
    [PR_PRP_COD] BIGINT NOT NULL,
    [PR_PRP_NAM] VARCHAR(100) NULL,
    [PR_TRN_TYP] CHAR(1) NULL,
    [PR_PRP_CAT] VARCHAR(10) NULL,
    [PR_LST_STG] BIGINT NULL,
    [PR_PAR_PRP] DECIMAL(38) NULL,
    CONSTRAINT [PK_PURPOSE_MAST] PRIMARY KEY ([PR_PRP_COD])
);

-- Table: PURPOSE_STAGE (Purpose-Stage Mapping)
CREATE TABLE [PURPOSE_STAGE] (
    [PS_PRP_COD] BIGINT NOT NULL,
    [PS_STG_COD] BIGINT NOT NULL,
    [PS_STG_SRL] BIGINT NOT NULL,
    [PS_FLX_FLD] CHAR(1) NOT NULL,
    [PS_PRL_FLG] CHAR(1) NOT NULL,
    [PS_ROL_COD] BIGINT NOT NULL,
    [PS_BOL_FLG] CHAR(1) NOT NULL,
    [PS_BOL_DES] VARCHAR(200) NULL,
    [PS_TRU_STG] BIGINT NULL,
    [PS_FAL_STG] BIGINT NULL,
    [PS_REM_MRK] VARCHAR(2000) NULL,
    [PS_LOW_LIMIT] DECIMAL(38) NULL,
    [PS_HIGH_LIMIT] DECIMAL(38) NULL,
    [PS_TARGET_TIME] DECIMAL(38) NULL,
    CONSTRAINT [PK_PURPOSE_STAGE] PRIMARY KEY ([PS_PRP_COD], [PS_STG_COD])
);

-- Table: DELLOG_PURPOSE_STAGE (Deletion Log for Purpose-Stage)
CREATE TABLE [DELLOG_PURPOSE_STAGE] (
    [PS_PRP_COD] BIGINT NOT NULL,
    [PS_STG_COD] BIGINT NOT NULL,
    [PS_STG_SRL] BIGINT NOT NULL,
    [PS_FLX_FLD] CHAR(1) NOT NULL,
    [PS_PRL_FLG] CHAR(1) NULL,
    [PS_ROL_COD] BIGINT NOT NULL,
    [PS_BOL_FLG] CHAR(1) NULL,
    [PS_BOL_DES] VARCHAR(200) NOT NULL,
    [PS_TRU_STG] BIGINT NULL,
    [PS_FAL_STG] BIGINT NULL,
    [PS_REM_MRK] VARCHAR(2000) NULL,
    [PS_DEL_DAT] DATETIME2(3) NOT NULL,
    [PS_DEL_USR] VARCHAR(25) NOT NULL,
    [PS_DEL_NUM] BIGINT NOT NULL
);

-- Table: PURPOSE_PRODUCT (Purpose-Product Mapping)
CREATE TABLE [PURPOSE_PRODUCT] (
    [PP_PRO_COD] VARCHAR(25) NOT NULL,
    [PP_PUR_COD] BIGINT NOT NULL,
    CONSTRAINT [PK_PURPOSE_PRODUCT] PRIMARY KEY ([PP_PRO_COD], [PP_PUR_COD])
);

-- Table: STAGE_DECISION (Stage Decision Rules)
CREATE TABLE [STAGE_DECISION] (
    [SD_PUR_COD] BIGINT NOT NULL,
    [SD_STG_COD] BIGINT NOT NULL,
    [SD_OPT_NAM] VARCHAR(25) NOT NULL,
    [SD_OPT_ID] BIGINT NULL,
    [SD_STG_NEXT] BIGINT NOT NULL,
    CONSTRAINT [PK_STAGE_DECISION] PRIMARY KEY ([SD_PUR_COD], [SD_STG_COD], [SD_OPT_NAM])
);

-- Table: STAGE_FLEX (Stage Flex Rules)
CREATE TABLE [STAGE_FLEX] (
    [PS_PRP_COD] BIGINT NOT NULL,
    [PS_STG_SRL] BIGINT NOT NULL,
    [PS_FLX_NUM] BIGINT NOT NULL,
    [PS_FLX_DES] VARCHAR(200) NULL,
    [PS_LOV_FLG] CHAR(1) NOT NULL,
    [PS_LOV_TYP] CHAR(3) NULL,
    [PS_FLX_TYP] CHAR(1) NULL,
    CONSTRAINT [PK_STAGE_FLEX] PRIMARY KEY ([PS_PRP_COD])
);

-- Table: LOG_DECISION_FLAG (Log - Decision Flag)
CREATE TABLE [LOG_DECISION_FLAG] (
    [DF_TRC_NUM] BIGINT NOT NULL,
    [DF_PUR_COD] BIGINT NOT NULL,
    [DF_STG_COD] BIGINT NOT NULL,
    [DF_STG_DEC] CHAR(1) NOT NULL,
    [DF_CAN_FLG] CHAR(1) NOT NULL,
    [DF_REF_NUM] BIGINT NULL,
    [DF_UPD_DAT] DATETIME2(3) NULL,
    [DF_REMARK] VARCHAR(100) NULL,
    [DF_MOD_USR] VARCHAR(25) NULL,
    [DF_MOD_NUM] BIGINT NULL,
    [DF_MOD_DAT] DATETIME2(3) NULL
);

-- Table: SPARSH_NAVIGATION (Navigation Tracking)
CREATE TABLE [SPARSH_NAVIGATION] (
    [SN_REQ_NUM] BIGINT NOT NULL,
    [SN_USR_ID] VARCHAR(25) NOT NULL,
    [SN_USR_NUM] BIGINT NOT NULL,
    [SN_RAN_NUM] VARCHAR(25) NULL,
    [SN_UPD_DAT] DATETIME2(3) NOT NULL,
    [SN_SCI_ID] CHAR(1) NOT NULL,
    [SN_STS_FLG] CHAR(1) NULL,
    CONSTRAINT [PK_SPARSH_NAVIGATION] PRIMARY KEY ([SN_REQ_NUM])
);

-- Table: WEIGHT_INFO (Weight Information)
CREATE TABLE [WEIGHT_INFO] (
    [WI_TRK_NUM] BIGINT NOT NULL,
    [WI_TYR_WGT] DECIMAL(38) NULL,
    [WI_GRS_WGT] DECIMAL(38) NULL,
    [WI_NET_WGT] DECIMAL(38) NULL
);

PRINT 'VEHICLE_TRACKING_MODULE Tables created successfully.';
GO
