<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-WorkOrderService.Functions-eb227e26-0edd-4e09-82c5-ed94170bf0fa</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkOrderService.Application\WorkOrderService.Application.csproj" />
    <ProjectReference Include="..\WorkOrderService.Infrastructure\WorkOrderService.Infrastructure.csproj" />
  </ItemGroup>
</Project>
