apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: ""
namespace: loan-services

resources:
  - ../../base

# Override ConfigMap for dev
configMapGenerator:
  - name: loan-services-config
    behavior: merge
    literals:
      - ASPNETCORE_ENVIRONMENT=Development

# Patch: scale all microservices down to 1 replica in dev
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: loan-transaction
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: loan-application
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: loan-account
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: loan-definition
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: document-service
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: lov-service
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: utility-service
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: api-gateway
