-- ==========================================
-- EXIM MANAGEMENT MODULE - Table Definitions
-- Database: SCIDB
-- Module: Export-Import Management
-- Created: March 9, 2026
-- ==========================================

USE SCIDB;
GO

-- Table: EXIM_DATAFILE
CREATE TABLE [EXIM_DATAFILE] (
    [FILE_ID] BIGINT NOT NULL,
    [FILE_TYPE] VARCHAR(10) NOT NULL,
    [FILE_NAME] VARCHAR(200) NULL,
    [ORIGINALCOUNT] BIGINT NULL,
    [FINALCOUNT] BIGINT NULL,
    [FILE_UPLOADEDBY] BIGINT NULL,
    [FILE_UPLOADEDON] DATETIME2(3) NOT NULL,
    [REMARKS] VARCHAR(1000) NULL,
    [FILE_SOURCE] VARCHAR(10) NULL,
    [DEL_FLAG] CHAR(1) NULL,
    [DELETED_DATE] VARCHAR(255) NULL,
    [DELETED_BY] VARCHAR(255) NULL,
    [DATATYPE_CODE] CHAR(1) NULL,
    [DATATYPE_MONTH] VARCHAR(255) NULL,
    [DATA_XML] NVARCHAR(MAX) NULL,
    CONSTRAINT [PK_EXIM_DATAFILE] PRIMARY KEY ([FILE_ID])
);

-- Table: EXIM_DATA (EXIM Data)
CREATE TABLE [EXIM_DATA] (
    [DATA_ID] BIGINT NULL,
    [EXIM_DATE] DATETIME2(3) NULL,
    [MONTH_CODE] VARCHAR(10) NULL,
    [ITC_CODE] BIGINT NULL,
    [ITEM] VARCHAR(250) NULL,
    [EXPORTER] VARCHAR(100) NULL,
    [DESTINATION] VARCHAR(100) NULL,
    [COUNTRY] VARCHAR(50) NULL,
    [QUANTITY] BIGINT NULL,
    [UNIT] VARCHAR(10) NULL,
    [PORT] VARCHAR(50) NULL,
    [FOB_RS_PERUNIT] VARCHAR(255) NULL,
    [FOB_DOLLAR_PERTON] VARCHAR(255) NULL,
    [FOB_EURO_PERTON] VARCHAR(255) NULL,
    [MODE_BY] VARCHAR(10) NULL,
    [ADDRESS] VARCHAR(250) NULL,
    [SB_NO] VARCHAR(50) NULL,
    [VESSEL] VARCHAR(100) NULL,
    [IE_TYPE] VARCHAR(10) NULL,
    [FILE_ID] BIGINT NULL,
    [STATUS] CHAR(10) NULL,
    [RATEUS] BIGINT NULL,
    [RATEEURO] BIGINT NULL,
    [BASIC_DUTYUNIT] VARCHAR(20) NULL,
    [ADDL_DUTYUNIT] VARCHAR(20) NULL,
    [FOB_DOLLAR_PERUNIT] VARCHAR(255) NULL,
    [POSSIBLE_DRAWBACKRATE] VARCHAR(100) NULL,
    [DUTY_APPL_IMPORTS] VARCHAR(255) NULL,
    [APPL_DUTY_NOTACTUAL] VARCHAR(255) NULL,
    [APPL_DUTY_INR_NOTACTUAL] VARCHAR(255) NULL,
    [APPL_DUTY_INR] VARCHAR(255) NULL,
    [APPL_DUTY_USD] VARCHAR(255) NULL,
    [VALUE_INUSD] VARCHAR(255) NULL,
    CONSTRAINT [PK_EXIM_DATA] PRIMARY KEY ([DATA_ID])
);

-- Table: EXIM_DATA_EXPORT
CREATE TABLE [EXIM_DATA_EXPORT] (
    [DATA_ID] BIGINT NULL,
    [EXIM_DATE] DATETIME2(3) NULL,
    [HSCODE] BIGINT NULL,
    [PRODDESC] VARCHAR(500) NULL,
    [PORTDEST] VARCHAR(500) NULL,
    [COUNTRYDEST] VARCHAR(500) NULL,
    [PORTORIGIN] VARCHAR(200) NULL,
    [STDQTY] BIGINT NULL,
    [STDUNIT] VARCHAR(18) NULL,
    [STDUNITRATE] DECIMAL(200,0) NULL,
    [UNITRATEDOL] BIGINT NULL,
    [FOBINR] BIGINT NULL,
    [FOBDOL] BIGINT NULL,
    [MODESHIP] VARCHAR(200) NULL,
    [RECORDID] VARCHAR(200) NULL,
    [EMONTH] VARCHAR(200) NULL,
    [FILE_ID] BIGINT NULL,
    [EXP_NAME] VARCHAR(255) NULL,
    [EXP_ADD1] VARCHAR(255) NULL,
    [EXP_ADD2] VARCHAR(255) NULL,
    [EXP_CITY] VARCHAR(255) NULL,
    [EXP_STATE] VARCHAR(255) NULL,
    [IMP_NAME] VARCHAR(255) NULL,
    [IMP_ADD1] VARCHAR(255) NULL,
    [IMP_ADD2] VARCHAR(255) NULL,
    [IMP_COUNTRY] VARCHAR(255) NULL,
    [QTY] BIGINT NULL,
    [UNIT] VARCHAR(200) NULL,
    [UNITRATE_INR] VARCHAR(255) NULL,
    [UNITRATE_FC] VARCHAR(255) NULL,
    [VALUE_FC] VARCHAR(255) NULL,
    [IEC] VARCHAR(200) NULL,
    [SB_NO] VARCHAR(255) NULL,
    [INV_NO] VARCHAR(255) NULL,
    [ITEM_NO] VARCHAR(255) NULL,
    [DRAW_BACK] VARCHAR(255) NULL,
    [CURRENT_QUE] VARCHAR(255) NULL,
    [HS2] VARCHAR(200) NULL,
    [HS4] VARCHAR(200) NULL,
    [INV_SLNO] VARCHAR(255) NULL,
    [CHALLAN_NO] VARCHAR(255) NULL,
    [HS_DESC] VARCHAR(255) NULL,
    [CHA_PANNO] VARCHAR(255) NULL,
    [CHA_NAME] VARCHAR(255) NULL,
    [INV_DATE] DATETIME2(3) NULL
);

-- Table: EXIM_DATA_IMPORT
CREATE TABLE [EXIM_DATA_IMPORT] (
    [DATA_ID] BIGINT NULL,
    [EXIM_DATE] DATETIME2(3) NULL,
    [HSCODE] BIGINT NULL,
    [PRODDESC] VARCHAR(500) NULL,
    [PORTDEST] VARCHAR(500) NULL,
    [COUNTRYORG] VARCHAR(500) NULL,
    [STDQTY] DECIMAL(38) NULL,
    [STDUNIT] VARCHAR(200) NULL,
    [STDUNITRATE] DECIMAL(38) NULL,
    [UNITRATEDOL] DECIMAL(38) NULL,
    [FOBINR] DECIMAL(38) NULL,
    [FOBDOL] DECIMAL(38) NULL,
    [APPLICABLEDUTY_INR] VARCHAR(255) NULL,
    [MODESHIP] VARCHAR(200) NULL,
    [RECORDID] VARCHAR(200) NULL,
    [EMONTH] VARCHAR(200) NULL,
    [FILE_ID] BIGINT NULL,
    [IMP_NAME] VARCHAR(255) NULL,
    [IMP_ADD1] VARCHAR(255) NULL,
    [IMP_ADD2] VARCHAR(255) NULL,
    [IMP_CITY] VARCHAR(255) NULL,
    [IMP_PINCODE] VARCHAR(255) NULL,
    [IMP_STATE] VARCHAR(255) NULL,
    [IMP_PHONE] VARCHAR(255) NULL,
    [IMP_EMAIL] VARCHAR(255) NULL,
    [IMP_CONTACTPER] VARCHAR(255) NULL,
    [EXP_NAME] VARCHAR(255) NULL,
    [EXP_ADD1] VARCHAR(255) NULL,
    [QTY] DECIMAL(38) NULL,
    [UNIT] VARCHAR(200) NULL,
    [UNITRATE_INR] VARCHAR(255) NULL,
    [UNITPRICE_FC] VARCHAR(255) NULL,
    [ACTUALDUTY_INR] VARCHAR(255) NULL,
    [AVAD_INR] VARCHAR(255) NULL,
    [AVAD_USD] VARCHAR(255) NULL,
    [PORT_ORG] VARCHAR(255) NULL,
    [CHA_PANNO] VARCHAR(255) NULL,
    [CHA_NAME] VARCHAR(255) NULL,
    [AG] VARCHAR(200) NULL,
    [IEC] VARCHAR(200) NULL,
    [BE_NO] VARCHAR(255) NULL,
    [INV_NO] VARCHAR(255) NULL,
    [ITEM_NO] VARCHAR(255) NULL,
    [HS2] VARCHAR(200) NULL,
    [HS4] VARCHAR(200) NULL,
    [HS_DESC] VARCHAR(255) NULL,
    [INV_VALUE] VARCHAR(255) NULL,
    [INV_DATE] DATETIME2(3) NULL,
    [POSSIBLE_DUPLICATE] VARCHAR(255) NULL,
    CONSTRAINT [PK_EXIM_DATA_IMPORT] PRIMARY KEY ([DATA_ID])
);

-- Table: EXIM_DATA_EXPORT_INTERMEDIATE
CREATE TABLE [EXIM_DATA_EXPORT_INTERMEDIATE] (
    [DATA_ID] BIGINT NULL,
    [EXIM_DATE] DATETIME2(3) NULL,
    [HSCODE] BIGINT NULL,
    [PRODDESC] VARCHAR(500) NULL,
    [PORTDEST] VARCHAR(500) NULL,
    [COUNTRYDEST] VARCHAR(500) NULL,
    [PORTORIGIN] VARCHAR(200) NULL,
    [STDQTY] DECIMAL(38) NULL,
    [STDUNIT] VARCHAR(200) NULL,
    [STDUNITRATE] DECIMAL(38) NULL,
    [UNITRATEDOL] DECIMAL(38) NULL,
    [FOBINR] DECIMAL(38) NULL,
    [FOBDOL] DECIMAL(38) NULL,
    [MODESHIP] VARCHAR(200) NULL,
    [RECORDID] VARCHAR(200) NULL,
    [EMONTH] VARCHAR(200) NULL,
    [FILE_ID] BIGINT NULL,
    [EXP_NAME] VARCHAR(255) NULL,
    [EXP_ADD1] VARCHAR(255) NULL,
    [EXP_ADD2] VARCHAR(255) NULL,
    [EXP_CITY] VARCHAR(255) NULL,
    [EXP_STATE] VARCHAR(255) NULL,
    [IMP_NAME] VARCHAR(255) NULL,
    [IMP_ADD1] VARCHAR(255) NULL,
    [IMP_ADD2] VARCHAR(255) NULL,
    [IMP_COUNTRY] VARCHAR(255) NULL,
    [QTY] DECIMAL(38) NULL,
    [UNIT] VARCHAR(200) NULL,
    [UNITRATE_INR] VARCHAR(255) NULL,
    [UNITRATE_FC] VARCHAR(255) NULL,
    [VALUE_FC] VARCHAR(255) NULL,
    [IEC] VARCHAR(200) NULL,
    [SB_NO] VARCHAR(255) NULL,
    [INV_NO] VARCHAR(255) NULL,
    [ITEM_NO] VARCHAR(255) NULL,
    [DRAW_BACK] VARCHAR(255) NULL,
    [CURRENT_QUE] VARCHAR(255) NULL,
    [HS2] VARCHAR(200) NULL,
    [HS4] VARCHAR(200) NULL,
    [INV_SLNO] VARCHAR(255) NULL,
    [CHALLAN_NO] VARCHAR(255) NULL,
    [HS_DESC] VARCHAR(255) NULL,
    [CHA_PANNO] VARCHAR(255) NULL,
    [CHA_NAME] VARCHAR(255) NULL,
    [INV_DATE] DATETIME2(3) NULL
);

-- Table: EXIM_MAP_DATA
CREATE TABLE [EXIM_MAP_DATA] (
    [MAP_ID] BIGINT NOT NULL,
    [SEARCH_ID] BIGINT NOT NULL,
    [DATA_ID] BIGINT NOT NULL,
    [PRODUCT_ID] BIGINT NOT NULL,
    [LAST_UPDATED_BY] BIGINT NOT NULL,
    [LAST_UPDATED_ON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_EXIM_MAP_DATA] PRIMARY KEY ([MAP_ID])
);

-- Table: EXIM_PRODUCT
CREATE TABLE [EXIM_PRODUCT] (
    [PRODUCT_ID] BIGINT NOT NULL,
    [PRODUCT_NAME] VARCHAR(100) NOT NULL,
    [PRODUCT_ORACLE_CODE] VARCHAR(50) NULL,
    [LAST_UPDATED_BY] BIGINT NOT NULL,
    [LAST_UPDATED_ON] DATETIME2(3) NOT NULL,
    [STATUS] CHAR(1) NOT NULL,
    CONSTRAINT [PK_EXIM_PRODUCT] PRIMARY KEY ([PRODUCT_ID])
);

-- Table: EXIM_PRODUCT_SEARCH
CREATE TABLE [EXIM_PRODUCT_SEARCH] (
    [SEARCH_ID] BIGINT NOT NULL,
    [PRODUCT_ID] BIGINT NOT NULL,
    [SEARCH_ITC_CODE] VARCHAR(10) NULL,
    [SEARCH_TEXT] VARCHAR(50) NULL,
    [LAST_UPDATED_BY] BIGINT NULL,
    [LAST_UPDATED_ON] DATETIME2(3) NOT NULL,
    [NOTIN_TEXT] VARCHAR(50) NULL,
    CONSTRAINT [PK_EXIM_PRODUCT_SEARCH] PRIMARY KEY ([SEARCH_ID])
);

-- Table: EXIM_PRODUCTGROUP
CREATE TABLE [EXIM_PRODUCTGROUP] (
    [GROUP_ID] BIGINT NOT NULL,
    [GROUP_NAME] VARCHAR(100) NOT NULL,
    [LAST_UPDATED_BY] BIGINT NOT NULL,
    [LAST_UPDATED_ON] DATETIME2(3) NOT NULL,
    [STATUS] CHAR(1) NOT NULL,
    CONSTRAINT [PK_EXIM_PRODUCTGROUP] PRIMARY KEY ([GROUP_ID])
);

-- Table: EXIM_PRODUCTGROUP_MAP
CREATE TABLE [EXIM_PRODUCTGROUP_MAP] (
    [MAP_ID] BIGINT NOT NULL,
    [GROUP_ID] BIGINT NOT NULL,
    [PRODUCT_ID] BIGINT NOT NULL,
    [LAST_UPDATED_BY] BIGINT NOT NULL,
    [LAST_UPDATED_ON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_EXIM_PRODUCTGROUP_MAP] PRIMARY KEY ([MAP_ID])
);

-- Table: EXIM_PRODUCTGROUP_SEARCH
CREATE TABLE [EXIM_PRODUCTGROUP_SEARCH] (
    [SEARCH_ID] BIGINT NOT NULL,
    [GROUP_ID] BIGINT NOT NULL,
    [PRODUCT_ID] BIGINT NOT NULL,
    [LAST_UPDATED_BY] BIGINT NOT NULL,
    [LAST_UPDATED_ON] DATETIME2(3) NOT NULL
);

-- Table: EXIM_SEARCH
CREATE TABLE [EXIM_SEARCH] (
    [SEARCHID] BIGINT NULL,
    [SEARCHTEXT] VARCHAR(100) NULL
);

-- Table: EXIM_USERMASTER
CREATE TABLE [EXIM_USERMASTER] (
    [EXIM_USERID] BIGINT NOT NULL,
    [EXIM_EMPSYSID] BIGINT NULL,
    [EXIM_SPARSHID] VARCHAR(50) NULL,
    [EXIM_USER_EFFECTIVEDATE] DATETIME2(3) NOT NULL,
    [EXIM_USER_CLOSUREDATE] DATETIME2(3) NULL,
    [EXIM_USER_ENTEREDBY] BIGINT NOT NULL,
    CONSTRAINT [PK_EXIM_USERMASTER] PRIMARY KEY ([EXIM_USERID])
);

-- Table: EXIM_USERROLEMAP
CREATE TABLE [EXIM_USERROLEMAP] (
    [ROLE_MAPID] BIGINT NOT NULL,
    [MAP_USERID] BIGINT NOT NULL,
    [MAP_ROLEID] INT NOT NULL,
    [ROLE_DEFFLAG] CHAR(1) NOT NULL,
    [ROLE_CREATEDBY] BIGINT NOT NULL,
    [ROLE_CREATEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_EXIM_USERROLEMAP] PRIMARY KEY ([ROLE_MAPID])
);

-- Table: EXIM_MENU_MASTER
CREATE TABLE [EXIM_MENU_MASTER] (
    [MENU_ID] BIGINT NOT NULL,
    [MENU_NAME] VARCHAR(100) NOT NULL,
    [MENU_PAGENAME] VARCHAR(200) NULL,
    [MENU_PARENTID] BIGINT NULL,
    [MENU_DISPLAYORDER] INT NULL,
    [MENU_MODIFIEDBY] BIGINT NOT NULL,
    [MENU_MODIFIEDON] DATETIME2(3) NOT NULL
);

-- Table: EXIM_MENUROLEMAP
CREATE TABLE [EXIM_MENUROLEMAP] (
    [MENU_ACCESSID] BIGINT NOT NULL,
    [MAP_MENUID] INT NOT NULL,
    [MAP_ROLEID] BIGINT NOT NULL,
    [MODIFIEDBY] BIGINT NULL,
    [ROLE_MODIFIEDON] DATETIME2(3) NULL
);

-- Table: EXIMLOV_MAST
CREATE TABLE [EXIMLOV_MAST] (
    [LOV_ID] BIGINT NULL,
    [LOV_TYPE] VARCHAR(10) NOT NULL,
    [LOV_NAME] VARCHAR(2000) NOT NULL
);

-- Table: EXIMLOV_TYPEMAST
CREATE TABLE [EXIMLOV_TYPEMAST] (
    [LOV_TYPECODE] VARCHAR(10) NOT NULL,
    [LOV_TYPENAME] VARCHAR(50) NOT NULL,
    CONSTRAINT [PK_EXIMLOV_TYPEMAST] PRIMARY KEY ([LOV_TYPECODE])
);

PRINT 'EXIM_MANAGEMENT_MODULE Tables created successfully.';
GO
