apiVersion: v1
kind: Secret
metadata:
  name: health-secrets
  namespace: health-services
type: Opaque
stringData:
  sa-password: "CHANGE_ME_Strong!P@ss2024"
  rabbitmq-user: "healthadmin"
  rabbitmq-password: "CHANGE_ME_RabbitPass2024"
  jwt-secret-key: "CHANGE_ME_SuperSecretJWTKey2024!MustBeAtLeast32Chars"
  azure-storage-connection: ""
  redis-password: ""
