apiVersion: v1
kind: Namespace
metadata:
  name: auth-provider
  labels:
    name: auth-provider
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-provider-config
  namespace: auth-provider
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:7136"
  Jwt__Issuer: "AuthProvider"
  Jwt__Audience: "AuthProvider.Client"
  Jwt__ExpirationMinutes: "60"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft: "Warning"
