-- ==========================================
-- CSA Module - Table Scripts
-- Database: MYWORKDB
-- Module: CSA (Control Self Assessment)
-- Description: Control Self Assessment and Evidence Management
-- Created: March 9, 2026
-- ==========================================

USE MYWORKDB;
GO

-- =====================================================
-- CSA Core Tables
-- =====================================================

-- Table: CSA_EVIDENCE - CSA EVIDENCE
CREATE TABLE [CSA_EVIDENCE] (
    [CONTROLEV_ID] BIGINT NOT NULL  -- Evidence ID,
    [CONTROLEV_CONTROLID] BIGINT NOT NULL  -- Control ID,
    [CONTROLEV_NAME] VARCHAR(2000) NULL  -- Evidence Name,
    [CONTROLEV_TEMPNAME] VARCHAR(2000) NULL  -- TEMP name,
    CONSTRAINT [PK_CSA_EVIDENCE] PRIMARY KEY ([CONTROLEV_ID])
);

-- Table: CSA_MAIN - csa main
CREATE TABLE [CSA_MAIN] (
    [CONTROL_ID] BIGINT NOT NULL  -- Control ID,
    [CONTROL_TITLE] VARCHAR(200) NOT NULL  -- Title,
    [CONTROL_DESCRIPTION] VARCHAR(2000) NULL  -- P - Preventative ; D - Detective,
    [CONTROL_TYPE] CHAR(1) NULL  -- Control Type,
    [CONTROL_METHOD] CHAR(1) NULL  -- Control Method,
    [CONTROL_RISK] VARCHAR(2000) NULL  -- Risk,
    [CONTROL_PRIORITY] CHAR(1) NULL  -- Priority ; H - High ; M - Medium ; L - Low,
    [CONTROL_PROCESS] BIGINT NULL  -- Process ID,
    [CONTROL_SUBPROCESS] BIGINT NULL  -- Sub Process ID,
    [CONTROL_PERIODICITY] CHAR(1) NULL  -- M - Monthly ; Q - Quarter ; A - Annual,
    [CONTROL_EVIDENCEFLAG] CHAR(1) NULL  -- Y - Yes ; N - No,
    [CONTROL_APPROVERFLAG] CHAR(1) NULL  -- Y - Yes ; N - No,
    [CONTROL_CREATEDBY] BIGINT NULL  -- Created By,
    [CONTROL_CREATEDON] DATETIME2(3) NULL  -- Created On,
    [CONTROL_MODIFIEDBY] BIGINT NULL  -- Last Modified By,
    [CONTROL_MODIFIEDON] DATETIME2(3) NULL  -- Last Modified On,
    CONSTRAINT [PK_CSA_MAIN] PRIMARY KEY ([CONTROL_ID])
);

-- Table: CSA_MAIN_UPLOAD - csa main upload
CREATE TABLE [CSA_MAIN_UPLOAD] (
    [CONTROL_TITLE] VARCHAR(200) NOT NULL,
    [CONTROL_DESCRIPTION] VARCHAR(2000) NULL,
    [CONTROL_TYPE] CHAR(30) NULL,
    [CONTROL_METHOD] CHAR(30) NULL,
    [CONTROL_RISK] VARCHAR(2000) NULL,
    [CONTROL_PRIORITY] CHAR(30) NULL,
    [CONTROL_PROCESS] BIGINT NULL,
    [CONTROL_SUBPROCESS] BIGINT NULL,
    [CONTROL_PERIODICITY] CHAR(30) NULL,
    [CONTROL_EVIDENCEFLAG] CHAR(1) NULL,
    [CONTROL_EVIDENCE] VARCHAR(200) NULL,
    [CONTROL_APPROVERFLAG] CHAR(1) NULL,
    [SESSIONID] VARCHAR(200) NULL
);

-- Table: CSA_MAIN_UPLOADERR - csa main uploader
CREATE TABLE [CSA_MAIN_UPLOADERR] (
    [CONTROL_TITLE] VARCHAR(200) NOT NULL,
    [CONTROL_DESCRIPTION] VARCHAR(2000) NULL,
    [CONTROL_TYPE] CHAR(30) NULL,
    [CONTROL_METHOD] CHAR(30) NULL,
    [CONTROL_RISK] VARCHAR(2000) NULL,
    [CONTROL_PRIORITY] CHAR(30) NULL,
    [CONTROL_PROCESS] BIGINT NULL,
    [CONTROL_SUBPROCESS] BIGINT NULL,
    [CONTROL_PERIODICITY] CHAR(30) NULL,
    [CONTROL_EVIDENCEFLAG] CHAR(1) NULL,
    [CONTROL_EVIDENCE] VARCHAR(200) NULL,
    [CONTROL_APPROVERFLAG] CHAR(1) NULL,
    [ERRMSG] VARCHAR(200) NULL,
    [SESSIONID] VARCHAR(200) NULL
);

-- Table: CSA_PROCESSMAST - csa process master
CREATE TABLE [CSA_PROCESSMAST] (
    [PROCESS_ID] BIGINT NOT NULL,
    [PROCESS_NAME] VARCHAR(2000) NOT NULL,
    [PROCESS_CREATEDBY] BIGINT NULL,
    [PROCESS_CREATEDON] DATETIME2(3) NULL,
    [PROCESS_MODIFIEDBY] BIGINT NULL,
    [PROCESS_MODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_CSA_PROCESSMAST] PRIMARY KEY ([PROCESS_ID])
);

-- Table: CSA_RCSURVEYATTACHMENT - csa survey attach
CREATE TABLE [CSA_RCSURVEYATTACHMENT] (
    [SURQATT_ID] BIGINT NOT NULL  -- Attachment ID,
    [SURQATT_FEEDID] BIGINT NOT NULL  -- Feedback ID,
    [SURQATT_CONTROLEVID] BIGINT NOT NULL  -- Control Evidence ID,
    [SURQATT_ATTACHMENT] VARCHAR(200) NULL  -- Attachment,
    CONSTRAINT [PK_CSA_RCSURVEYATTACHMENT] PRIMARY KEY ([SURQATT_ID])
);

-- Table: CSA_RCSURVEYFEED - csa survey feed
CREATE TABLE [CSA_RCSURVEYFEED] (
    [SURQFEED_ID] BIGINT NOT NULL  -- Feedback ID,
    [SURQFEED_SURQID] BIGINT NOT NULL  -- Survey Question ID,
    [SURQFEED_EMPSYSID] BIGINT NOT NULL  -- Employee System ID,
    [SURQFEED_STATUS] CHAR(1) NOT NULL  -- Surveystatus ;P - Pass ; F - Fail ; N Not Applicable,
    [SURQFEED_TYPE] CHAR(1) NOT NULL  -- C - Control Owner ; A - Approver,
    [SURQFEED_REMFLAG] CHAR(1) NOT NULL  -- Remedial Flag Y - Yes ; N - No,
    [SURQFEED_REMDATE] DATETIME2(3) NULL  -- Remedial Date,
    [SURQFEED_REMARKS] VARCHAR(2000) NULL  -- Owner Remarks,
    [SURQFEED_ENTEREDON] DATETIME2(3) NOT NULL  -- Survey Completed On,
    [SURQFEED_EVIDENCEFLAG] CHAR(1) NOT NULL  -- Evidence Flag - Y - Yes ; N - No,
    [SURQFEED_APPFLAG] CHAR(1) NOT NULL  -- ApprovalFlag Pending ; Y-Approved ;N Rejected,
    [SURQFEED_APPREMARKS] VARCHAR(2000) NOT NULL  -- Approver Remarks,
    [SURQFEED_APPDATE] DATETIME2(3) NULL  -- Approved On,
    [SURQFEED_APPBY] BIGINT NULL  -- Approved By,
    [SURQFEED_ENTDATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_CSA_RCSURVEYFEED] PRIMARY KEY ([SURQFEED_ID])
);

-- Table: CSA_RCSURVEYMAIN - csa survey main
CREATE TABLE [CSA_RCSURVEYMAIN] (
    [SURVEY_ID] BIGINT NOT NULL  -- Survey ID,
    [SURVEY_TITLE] VARCHAR(1000) NOT NULL  -- Title,
    [SURVEY_DUEDATE] DATETIME2(3) NOT NULL  -- Period From,
    [SURVEY_CLOSEDATE] DATETIME2(3) NOT NULL  -- Period To,
    [SURVEY_STARTDATE] DATETIME2(3) NOT NULL  -- Owner Due Date,
    [SURVEY_ENDDATE] DATETIME2(3) NOT NULL  -- Approver Due Date,
    [SURVEY_ALERT1] BIGINT NULL,
    [SURVEY_ALERT2] BIGINT NULL,
    [SURVEY_CREATEDBY] BIGINT NOT NULL,
    [SURVEY_CREATEDON] DATETIME2(3) NOT NULL,
    [SURVEY_MODIFIEDBY] BIGINT NULL,
    [SURVEY_MODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_CSA_RCSURVEYMAIN] PRIMARY KEY ([SURVEY_ID])
);

-- Table: CSA_RCSURVEYQUESTION - CSA RC SURVEY QUES
CREATE TABLE [CSA_RCSURVEYQUESTION] (
    [SURQ_ID] BIGINT NOT NULL  -- Survey Question ID,
    [SURQ_SURVEYID] BIGINT NOT NULL  -- Survey ID,
    [SURQ_CONTROLID] BIGINT NOT NULL  -- Control ID,
    [SURQ_UNITID] BIGINT NOT NULL  -- Unit ID,
    [SURQ_OWNERID] BIGINT NOT NULL  -- Owner ID,
    [SURQ_APPROVERID] BIGINT NOT NULL  -- Approver ID,
    [SURQ_ORGDUEDATE] DATETIME2(3) NOT NULL  -- Original Due Date,
    [SURQ_DUEDATE] DATETIME2(3) NOT NULL  -- Survey Due Date / Remedial Date,
    [SURQ_CANCELDATE] DATETIME2(3) NULL  -- Survey Cancel Date,
    [SURQ_CREATEDBY] BIGINT NULL  -- Created By,
    [SURQ_CREATEDON] DATETIME2(3) NULL  -- Created On,
    [SURQ_MODIFIEDBY] BIGINT NULL  -- Last Modified By,
    [SURQ_MODIFIEDON] DATETIME2(3) NULL  -- Last Modified On,
    [SURQ_ASSFLAG] CHAR(1) NULL  -- Assessment Status P - Pending ; C - Control Assessed  (Pass); A - Approver Reviewed (Pass),
    [SURQ_APPFLAG] CHAR(1) NULL  -- N - Not Due for Approval ;  P - Awaiting Approval ; Y - Approved,
    [SURQ_REMFLAG] CHAR(1) NULL  -- Remedial Status ; N- Not Applicable; P - pending ; C - Control Assessed ; A - Approver Reviewed,
    [SURQ_REMDATE] DATETIME2(3) NULL  -- Remedial Due Date,
    [SURQ_ASSDATE] DATETIME2(3) NULL  -- Last Assessment Completed On,
    [SURQ_APPDATE] DATETIME2(3) NULL  -- Last Approver Completed On,
    [SURQ_DELAYDAYS] BIGINT NULL  -- Delay in Days,
    [SURQ_REMNOS] BIGINT NULL  -- Remedial Nos (Not more than 2),
    [SURQ_UNITNAME] VARCHAR(50) NULL  -- Unit Name col used for Old data,
    [SURQ_ENTFLG] CHAR(1) NULL,
    CONSTRAINT [PK_CSA_RCSURVEYQUESTION] PRIMARY KEY ([SURQ_ID])
);

-- Table: CSA_RCUNITMAPDET - CSA UNIT MAP DEPT
CREATE TABLE [CSA_RCUNITMAPDET] (
    [RCMAP_ID] BIGINT NOT NULL  -- Map ID,
    [RCMAP_CONTROLID] BIGINT NOT NULL  -- Control ID,
    [RCMAP_UNITID] BIGINT NOT NULL  -- Unit ID,
    [RCMAP_OWNERID] BIGINT NOT NULL  -- Owner Employee System ID,
    [RCMAP_APPROVERID] BIGINT NOT NULL  -- Approver Employee System ID,
    [RCMAP_REPMANAGER] CHAR(1) NOT NULL  -- (Yes -Y / No - N),
    [RCMAP_EFFDATE] DATETIME2(3) NOT NULL  -- Effective Date,
    [RCMAP_CLSDATE] DATETIME2(3) NULL  -- Closure Date,
    [RCMAP_DUEDATE] DATETIME2(3) NOT NULL  -- First Due Date,
    [RCMAP_CREATEDBY] BIGINT NOT NULL  -- Created By,
    [RCMAP_CREATEDON] DATETIME2(3) NOT NULL  -- Created On,
    [RCMAP_MODIFIEDBY] BIGINT NULL  -- Last Modified By,
    [RCMAP_MODIFIEDON] DATETIME2(3) NULL  -- Last Modified On,
    CONSTRAINT [PK_CSA_RCUNITMAPDET] PRIMARY KEY ([RCMAP_ID])
);

-- Table: CSA_SUBPROCESSMAST - CSA SUBPROCESS MAST
CREATE TABLE [CSA_SUBPROCESSMAST] (
    [SUBPROCESS_ID] BIGINT NOT NULL  -- Sub Process ID,
    [SUBPROCESS_PROCESSID] BIGINT NOT NULL  -- Process ID,
    [SUBPROCESS_NAME] VARCHAR(2000) NOT NULL  -- Sub Process Name,
    [SUBPROCESS_CREATEDBY] BIGINT NULL  -- Created By,
    [SUBPROCESS_CREATEDON] DATETIME2(3) NULL  -- Created On,
    [SUBPROCESS_MODIFIEDBY] BIGINT NULL  -- Last Modified By,
    [SUBPROCESS_MODIFIEDON] DATETIME2(3) NULL  -- Last Modified On,
    CONSTRAINT [PK_CSA_SUBPROCESSMAST] PRIMARY KEY ([SUBPROCESS_ID])
);

-- Table: CSA_UNITMASTER - CSA UNIT MASTER
CREATE TABLE [CSA_UNITMASTER] (
    [UNIT_ID] BIGINT NOT NULL  -- UNIT ID,
    [UNIT_NAME] VARCHAR(200) NOT NULL  -- UNIT NAME,
    [UNIT_SHTNAME] VARCHAR(200) NOT NULL  -- UNIT SHORT NAME,
    [UNIT_CODE] CHAR(3) NOT NULL  -- UNIT CODE,
    [UNIT_BUSINESSID] BIGINT NOT NULL  -- BUSINESS ID,
    [UNIT_LIVFLAG] CHAR(1) NOT NULL  -- LIVE FLAG,
    [UNIT_ORGID] BIGINT NOT NULL  -- ORGANIZATION ID,
    [UNIT_CREATEDBY] BIGINT NOT NULL  -- Created By,
    [UNIT_CREATEDON] DATETIME2(3) NOT NULL  -- Created On,
    [UNIT_MODIFIEDBY] BIGINT NULL  -- Last Modified By,
    [UNIT_MODIFIEDON] DATETIME2(3) NULL  -- Last Modified On,
    CONSTRAINT [PK_CSA_UNITMASTER] PRIMARY KEY ([UNIT_ID])
);

-- Table: CSA_USERS - CSA USERS
CREATE TABLE [CSA_USERS] (
    [USER_EMPNO] DECIMAL(38) NOT NULL,
    [USER_PINNUM] DECIMAL(20,0) NULL,
    [USER_NAME] VARCHAR(65) NULL,
    [USER_SYSID] BIGINT NULL,
    [USER_EMAIL] VARCHAR(65) NULL
);

-- Table: CSADATA - CSA DATA
CREATE TABLE [CSADATA] (
    [TITLE] NVARCHAR(2000) NULL,
    [CONTROL_METHOD] VARCHAR(4000) NULL,
    [CONTROL_TYPE] VARCHAR(4000) NULL,
    [PRIORITY] VARCHAR(4000) NULL,
    [CONTROL_DESCRIPTION] NVARCHAR(2000) NULL,
    [RISK] NVARCHAR(2000) NULL,
    [APPROVAL_REQUIRED] VARCHAR(4000) NULL,
    [CONTROLRECORD_REQUIRED] VARCHAR(4000) NULL,
    [FREQUENCYOFCONTROL] VARCHAR(4000) NULL,
    [PERIODICITY] VARCHAR(4000) NULL,
    [PROCESS] VARCHAR(4000) NULL,
    [SUB_PROCESS] VARCHAR(4000) NULL,
    [CREATED] DECIMAL(38) NULL,
    [MODIFIED] DECIMAL(38) NULL,
    [MODIFIED_BY] VARCHAR(4000) NULL,
    [ID] BIGINT NULL,
    [ITEM_TYPE] VARCHAR(4000) NULL,
    [PATH] VARCHAR(4000) NULL
);

-- =====================================================
-- CSA Indexes
-- =====================================================
CREATE INDEX [IDX_CSA_EVIDENCE_CONTROLEV_CONTROLID] ON [CSA_EVIDENCE]([CONTROLEV_CONTROLID]);
CREATE INDEX [IDX_CSA_MAIN_CONTROL_TITLE] ON [CSA_MAIN]([CONTROL_TITLE]);
CREATE INDEX [IDX_CSA_RCSURVEYATTACHMENT_SURQATT_FEEDID] ON [CSA_RCSURVEYATTACHMENT]([SURQATT_FEEDID]);
CREATE INDEX [IDX_CSA_RCSURVEYATTACHMENT_SURQATT_CONTROLEVID] ON [CSA_RCSURVEYATTACHMENT]([SURQATT_CONTROLEVID]);
CREATE INDEX [IDX_CSA_RCSURVEYFEED_SURQFEED_SURQID] ON [CSA_RCSURVEYFEED]([SURQFEED_SURQID]);
CREATE INDEX [IDX_CSA_RCSURVEYQUESTION_SURQ_SURVEYID] ON [CSA_RCSURVEYQUESTION]([SURQ_SURVEYID]);
CREATE INDEX [IDX_CSA_RCUNITMAPDET_RCMAP_CONTROLID] ON [CSA_RCUNITMAPDET]([RCMAP_CONTROLID]);
CREATE INDEX [IDX_CSA_SUBPROCESSMAST_SUBPROCESS_PROCESSID] ON [CSA_SUBPROCESSMAST]([SUBPROCESS_PROCESSID]);

PRINT 'CSA Module - Tables created successfully.';
GO
