// <auto-generated />
using System;
using CheckupManagementService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheckupManagementService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CheckupManagementDbContext))]
    partial class CheckupManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.CheckupMaster", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("CheckupCode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckupMasterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CheckupType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloseDate")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag")
                        .HasColumnType("char(1)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyCode", "CheckupCode");

                    b.HasIndex("CheckupCode")
                        .HasDatabaseName("IDX_CHECKUP_MAST_CM_CHK_COD");

                    b.ToTable("CHECKUP_MAST", (string)null);
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.CheckupOthers", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("CheckupCode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherSerialNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CheckupMasterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckupOthersId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentMedicines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FamilyHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldLabel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("FieldTypeCode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FieldTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LifestyleHabits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MandatoryFlag")
                        .HasColumnType("char(1)");

                    b.Property<string>("MedicineAllergy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PastSurgery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyCode", "CheckupCode", "OtherSerialNumber");

                    b.HasIndex("FieldTypeCode");

                    b.ToTable("CHKUP_OTHERS", (string)null);
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.CheckupOthersListOfValues", b =>
                {
                    b.Property<decimal>("ListOfValueSerialNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CheckupCode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CheckupOtherCheckupCode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CheckupOtherCompanyCode")
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("CheckupOtherOtherSerialNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ListOfValueDescription")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("OtherSerialNumber")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ListOfValueSerialNumber");

                    b.HasIndex("CheckupOtherCompanyCode", "CheckupOtherCheckupCode", "CheckupOtherOtherSerialNumber");

                    b.ToTable("CHKUP_OTHERS_LOV", (string)null);
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.CheckupPersonalFamilyHistory", b =>
                {
                    b.Property<decimal?>("HealthNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EmployeeNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SymptomId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ImmunizationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YesNoFlag")
                        .HasColumnType("char(1)");

                    b.HasKey("HealthNumber", "EmployeeNumber", "SymptomId");

                    b.HasIndex("SymptomId");

                    b.ToTable("CHKUP_PFI_HIST", (string)null);
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.CheckupSymptomMaster", b =>
                {
                    b.Property<decimal>("SymptomId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SymptomFlag")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("SymptomName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SymptomId");

                    b.ToTable("CHKUP_SYMP_MAST", (string)null);
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.CheckupTest", b =>
                {
                    b.Property<decimal>("SerialNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CheckboxFlag")
                        .HasColumnType("char(1)");

                    b.Property<decimal?>("CheckupCode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CloseFlag")
                        .HasColumnType("char(1)");

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OrderNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TestCode")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SerialNumber");

                    b.HasIndex("TestCode");

                    b.HasIndex("CompanyCode", "CheckupCode");

                    b.ToTable("CHKUP_TEST", (string)null);
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.FieldTypeMaster", b =>
                {
                    b.Property<decimal>("FieldTypeCode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ControlSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FieldTypeName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("FieldTypeCode");

                    b.ToTable("FIELD_TYP_MAST", (string)null);
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.HealthCheckCard", b =>
                {
                    b.Property<string>("AdviceFollowup1")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AdviceFollowup2")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AdviceRemark1")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AdviceRemark2")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckupMasterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DoctorDate1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DoctorDate2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EmployeeDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EmployeeNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HealthNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalDetails")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ScreeningDetails")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.ToTable("HLTH_CHKUP_CARD", (string)null);
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.HealthCheckCardSub", b =>
                {
                    b.Property<decimal?>("EmployeeNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FlagYesNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("HealthNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SymptomId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SymptomValue")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.ToTable("HLTH_CHKCARD_SUB", (string)null);
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.HealthCounter", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CounterCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<long>("CounterValue")
                        .HasColumnType("bigint");

                    b.HasKey("CompanyCode", "CounterCode");

                    b.ToTable("HEALTH_COUNTER", (string)null);
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.HealthDynamicDetail", b =>
                {
                    b.Property<decimal?>("CheckupCode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("ControlSourceId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DynamicValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("EmployeeNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HealthNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SystemDate")
                        .HasColumnType("datetime2");

                    b.ToTable("HEALTH_DYN_DET", (string)null);
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.HealthEntryLov", b =>
                {
                    b.Property<decimal>("TestCode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ListOfValueText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TestCode", "ListOfValueText");

                    b.ToTable("HEALTH_ENTRY_LOV", (string)null);
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.HealthMain", b =>
                {
                    b.Property<int>("HealthNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthNumber"));

                    b.Property<decimal?>("BMI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BloodPressure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CheckupCode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CheckupDate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CheckupMasterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorBlindness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ECG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EntryEmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EyeVision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hearing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("int");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LungsXRay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalClearance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallFitness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextField2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TextField3")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TextField4")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TextField5")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HealthNumber");

                    b.HasIndex("EmployeeNumber")
                        .HasDatabaseName("IDX_HEALTH_MAIN_HM_EMP_NUM");

                    b.HasIndex("HealthNumber")
                        .HasDatabaseName("IDX_HEALTH_MAIN_HM_HLT_NUM");

                    b.HasIndex("CompanyCode", "CheckupCode");

                    b.ToTable("HEALTH_MAIN", (string)null);
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.HealthMinMaxValue", b =>
                {
                    b.Property<decimal>("TestCode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TypeCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("UnitCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LovText")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaxText")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MinText")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SingleValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TestCode", "TypeCode", "UnitCode");

                    b.ToTable("HEALTH_MINMAX_VAL", (string)null);
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.HealthSub", b =>
                {
                    b.Property<int>("HealthNumber")
                        .HasColumnType("int");

                    b.Property<string>("TestCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorRemarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HealthId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthSubId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TestType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TestValue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TextField2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TextField3")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TextField4")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TextField5")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ValidationFlag")
                        .HasColumnType("char(1)");

                    b.HasKey("HealthNumber", "TestCode");

                    b.HasIndex("HealthNumber")
                        .HasDatabaseName("IDX_HEALTH_SUB_HM_HLT_NUM");

                    b.ToTable("HEALTH_SUB", (string)null);
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.PreEmploymentCheckupMain", b =>
                {
                    b.Property<DateTime?>("CheckupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("EmployeeNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FinalRemarks")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("FitFinal")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("FitPhysical")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("HealthNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IdentificationMarks")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhysicalHandicapDescription")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProposedDesignation")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.ToTable("CHKUP_PRE_MAIN", (string)null);
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.TestMaster", b =>
                {
                    b.Property<decimal>("TestCode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CheckboxFlag")
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CloseFlag")
                        .HasColumnType("char(1)");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NormalRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RangeValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TestCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestGroup")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TestId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("TestCode");

                    b.ToTable("TEST_MAST", (string)null);
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.CheckupOthers", b =>
                {
                    b.HasOne("CheckupManagementService.Domain.Entities.FieldTypeMaster", "FieldType")
                        .WithMany("CheckupOthers")
                        .HasForeignKey("FieldTypeCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CheckupManagementService.Domain.Entities.CheckupMaster", null)
                        .WithMany("CheckupOthers")
                        .HasForeignKey("CompanyCode", "CheckupCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldType");
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.CheckupOthersListOfValues", b =>
                {
                    b.HasOne("CheckupManagementService.Domain.Entities.CheckupOthers", "CheckupOther")
                        .WithMany("ListOfValues")
                        .HasForeignKey("CheckupOtherCompanyCode", "CheckupOtherCheckupCode", "CheckupOtherOtherSerialNumber");

                    b.Navigation("CheckupOther");
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.CheckupPersonalFamilyHistory", b =>
                {
                    b.HasOne("CheckupManagementService.Domain.Entities.CheckupSymptomMaster", "Symptom")
                        .WithMany("PersonalFamilyHistories")
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.CheckupTest", b =>
                {
                    b.HasOne("CheckupManagementService.Domain.Entities.TestMaster", "TestMaster")
                        .WithMany("CheckupTests")
                        .HasForeignKey("TestCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CheckupManagementService.Domain.Entities.CheckupMaster", "CheckupMaster")
                        .WithMany("CheckupTests")
                        .HasForeignKey("CompanyCode", "CheckupCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CheckupMaster");

                    b.Navigation("TestMaster");
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.HealthEntryLov", b =>
                {
                    b.HasOne("CheckupManagementService.Domain.Entities.TestMaster", "TestMaster")
                        .WithMany("HealthEntryLovs")
                        .HasForeignKey("TestCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestMaster");
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.HealthMain", b =>
                {
                    b.HasOne("CheckupManagementService.Domain.Entities.CheckupMaster", "CheckupMaster")
                        .WithMany("HealthMains")
                        .HasForeignKey("CompanyCode", "CheckupCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CheckupMaster");
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.HealthMinMaxValue", b =>
                {
                    b.HasOne("CheckupManagementService.Domain.Entities.TestMaster", "TestMaster")
                        .WithMany("HealthMinMaxValues")
                        .HasForeignKey("TestCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestMaster");
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.HealthSub", b =>
                {
                    b.HasOne("CheckupManagementService.Domain.Entities.HealthMain", "HealthMain")
                        .WithMany("HealthSubs")
                        .HasForeignKey("HealthNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthMain");
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.CheckupMaster", b =>
                {
                    b.Navigation("CheckupOthers");

                    b.Navigation("CheckupTests");

                    b.Navigation("HealthMains");
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.CheckupOthers", b =>
                {
                    b.Navigation("ListOfValues");
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.CheckupSymptomMaster", b =>
                {
                    b.Navigation("PersonalFamilyHistories");
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.FieldTypeMaster", b =>
                {
                    b.Navigation("CheckupOthers");
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.HealthMain", b =>
                {
                    b.Navigation("HealthSubs");
                });

            modelBuilder.Entity("CheckupManagementService.Domain.Entities.TestMaster", b =>
                {
                    b.Navigation("CheckupTests");

                    b.Navigation("HealthEntryLovs");

                    b.Navigation("HealthMinMaxValues");
                });
#pragma warning restore 612, 618
        }
    }
}
