-- Module: Authorization
USE DDDB;
GO

-- Table: DD_RIGHTS
CREATE TABLE [DD_RIGHTS] (
    [DD_RGT_COD] DECIMAL(38) NOT NULL  -- Right Code,
    [DD_RGT_DSC] VARCHAR(3) NULL  -- Right Description,
    CONSTRAINT [PK_DD_RIGHTS] PRIMARY KEY ([DD_RGT_COD])
);



-- Table: DD_SPECIALINPUTS
CREATE TABLE [DD_SPECIALINPUTS] (
    [SPL_ID] DECIMAL(38) NOT NULL,
    [SPL_YEARID] DECIMAL(38) NOT NULL,
    [SPL_ROLETYPE] VARCHAR(10) NOT NULL,
    [SPL_EMPSYSID] DECIMAL(38) NOT NULL,
    [SPL_APRSYSID] DECIMAL(38) NOT NULL,
    [SPL_INPUTS] VARCHAR(4000) NOT NULL,
    [SPL_STATUS] CHAR(1) NOT NULL,
    [SPL_CREATEDON] DATETIME2(3) NOT NULL,
    [SPL_SUBMITTEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_DD_SPECIALINPUTS] PRIMARY KEY ([SPL_ID])
);



-- Table: DD_SPECIALINPUT_MASTER
CREATE TABLE [DD_SPECIALINPUT_MASTER] (
    [SPL_ID] DECIMAL(38) NOT NULL,
    [SPL_YEARID] DECIMAL(38) NOT NULL,
    [SPL_ROLETYPE] VARCHAR(10) NOT NULL,
    [SPL_EMPSYSID] DECIMAL(38) NOT NULL,
    [SPL_APRSYSID] DECIMAL(38) NOT NULL,
    [SPL_CREATEDBY] DECIMAL(38) NOT NULL,
    [SPL_CREATEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_DD_SPECIALINPUT_MASTER] PRIMARY KEY ([SPL_ID])
);



-- Table: DD_TRACKERRIGHTS
CREATE TABLE [DD_TRACKERRIGHTS] (
    [DD_USR_ID] VARCHAR(65) NOT NULL  -- User Id,
    [DD_PIN_NUM] DECIMAL(38) NULL  -- User Pin Number,
    [DD_TRK_MOD] VARCHAR(3) NULL  -- Tracker Mode,
    [DD_TRK_BUS] VARCHAR(9) NULL  -- Business Code,
    [DD_TRK_UNT] VARCHAR(3) NULL  -- Unit Code,
    [DD_TRK_RGT] CHAR(1) NULL  -- Tracker Rights,
    [DD_VTC_RGT] CHAR(1) NULL  -- VTC Rights,
    [DD_REP_RGT] CHAR(1) NULL  -- Representing Unit,
    [DD_LET_RGT] CHAR(1) NULL  -- LET Right,
    [DD_CAR_RGT] CHAR(1) NULL  -- CAR Right
);



-- Table: DD_USERRIGHTS
CREATE TABLE [DD_USERRIGHTS] (
    [DD_USR_ID] VARCHAR(60) NULL  -- User Id,
    [DD_PIN_NUM] DECIMAL(38) NULL  -- Pin Number,
    [DD_RGT_COD] DECIMAL(38) NULL  -- Right Code,
    [DD_BUS_COD] VARCHAR(9) NULL  -- Business Code,
    [DD_UNT_COD] VARCHAR(6) NULL  -- Unit Code,
    [DD_RGT_MOD] DECIMAL(38) NULL  -- Right Mode
);

