-- ==========================================
-- PURCHASE SALES MODULE - Table Definitions
-- Database: SCIDB
-- Module: Purchase & Sales Management
-- Created: March 9, 2026
-- ==========================================

USE SCIDB;
GO

-- Table: PURCHASE_DETAILS
CREATE TABLE [PURCHASE_DETAILS] (
    [PD_SRL_NUM] BIGINT NOT NULL,
    [PD_TRC_NUM] BIGINT NOT NULL,
    [PD_TRN_NUM] BIGINT NOT NULL,
    [PD_PUR_COD] BIGINT NOT NULL,
    [PD_STG_COD] BIGINT NOT NULL,
    [PD_ORA_MRC] BIGINT NULL,
    [PD_SUP_COD] VARCHAR(25) NULL,
    [PD_TON_NUM_LD] VARCHAR(255) NULL,
    [PD_TON_NUM_UD] VARCHAR(255) NULL,
    [PD_USR_ID] VARCHAR(25) NULL,
    [PD_USR_NUM] BIGINT NULL,
    [PD_UPD_DAT] DATETIME2(3) NOT NULL,
    [PD_CAN_FLG] CHAR(1) NULL,
    CONSTRAINT [PK_PURCHASE_DETAILS] PRIMARY KEY ([PD_SRL_NUM])
);

-- Table: SALE_MAIN
CREATE TABLE [SALE_MAIN] (
    [SL_SER_NUM] BIGINT NOT NULL,
    [SL_TRC_NUM] BIGINT NOT NULL,
    [SL_TRN_NUM] BIGINT NOT NULL,
    [SL_PUR_COD] BIGINT NOT NULL,
    [SL_STG_COD] BIGINT NOT NULL,
    [SL_ISO_NUM] VARCHAR(25) NULL,
    [SL_ISO_DATE] DATETIME2(3) NULL,
    [SL_PRO_DES] VARCHAR(100) NULL,
    [SL_USR_ID] VARCHAR(25) NOT NULL,
    [SL_USR_NUM] BIGINT NOT NULL,
    [SL_UPD_DAT] DATETIME2(3) NOT NULL,
    [SL_CAN_FLG] CHAR(1) NULL,
    [SL_VEH_CUS] VARCHAR(100) NULL,
    CONSTRAINT [PK_SALE_MAIN] PRIMARY KEY ([SL_SER_NUM])
);

-- Table: SALE_SUB
CREATE TABLE [SALE_SUB] (
    [SS_REF_NUM] BIGINT NULL,
    [SS_SER_NUM] BIGINT NULL,
    [SS_PRO_COD] VARCHAR(255) NULL,
    [SS_PRO_QTN] DECIMAL(38) NULL,
    [SS_PRO_GRD] VARCHAR(255) NULL,
    [SS_USR_COM] VARCHAR(255) NULL,
    [SS_CHB_INV] VARCHAR(255) NULL,
    [SS_CAN_FLG] CHAR(1) NULL
);

-- Table: LOG_PURCHASE_DETAILS (Log - Purchase Details)
CREATE TABLE [LOG_PURCHASE_DETAILS] (
    [PD_SRL_NUM] BIGINT NOT NULL,
    [PD_TRC_NUM] BIGINT NOT NULL,
    [PD_TRN_NUM] BIGINT NOT NULL,
    [PD_PUR_COD] BIGINT NOT NULL,
    [PD_STG_COD] BIGINT NOT NULL,
    [PD_ORA_MRC] BIGINT NULL,
    [PD_SUP_COD] VARCHAR(25) NULL,
    [PD_TON_NUM_LD] BIGINT NULL,
    [PD_TON_NUM_UD] BIGINT NULL,
    [PD_USR_ID] VARCHAR(25) NOT NULL,
    [PD_USR_NUM] BIGINT NOT NULL,
    [PD_UPD_DAT] DATETIME2(3) NOT NULL,
    [PD_CAN_FLG] CHAR(1) NULL,
    [PD_MOD_USR] VARCHAR(25) NOT NULL,
    [PD_MOD_NUM] BIGINT NOT NULL,
    [PD_MOD_DAT] DATETIME2(3) NOT NULL
);

-- Table: LOG_SALE_MAIN (Log - Sale Main)
CREATE TABLE [LOG_SALE_MAIN] (
    [SL_SER_NUM] BIGINT NOT NULL,
    [SL_TRC_NUM] BIGINT NOT NULL,
    [SL_TRN_NUM] BIGINT NOT NULL,
    [SL_PUR_COD] BIGINT NOT NULL,
    [SL_STG_COD] BIGINT NOT NULL,
    [SL_ISO_NUM] VARCHAR(25) NULL,
    [SL_ISO_DATE] DATETIME2(3) NULL,
    [SL_PRO_DES] VARCHAR(100) NULL,
    [SL_USR_ID] VARCHAR(25) NOT NULL,
    [SL_USR_NUM] BIGINT NOT NULL,
    [SL_UPD_DAT] DATETIME2(3) NOT NULL,
    [SL_CAN_FLG] CHAR(1) NULL,
    [SL_MOD_USR] VARCHAR(25) NOT NULL,
    [SL_MOD_NUM] BIGINT NOT NULL,
    [SL_MOD_DAT] DATETIME2(3) NOT NULL
);

-- Table: LOG_SALE_SUB (Log - Sale Sub)
CREATE TABLE [LOG_SALE_SUB] (
    [SS_REF_NUM] BIGINT NOT NULL,
    [SS_SER_NUM] BIGINT NOT NULL,
    [SS_PRO_COD] VARCHAR(25) NOT NULL,
    [SS_PRO_QTN] DECIMAL(38) NULL,
    [SS_PRO_GRD] VARCHAR(25) NOT NULL,
    [SS_USR_COM] VARCHAR(200) NULL,
    [SS_CHB_INV] BIGINT NULL,
    [SS_CAN_FLG] CHAR(1) NULL,
    [SS_MOD_USR] VARCHAR(25) NOT NULL,
    [SS_MOD_NUM] BIGINT NOT NULL,
    [SS_MOD_DAT] DATETIME2(3) NOT NULL
);

PRINT 'PURCHASE_SALES_MODULE Tables created successfully.';
GO
