-- ==========================================
-- DISPATCH PLANNING MODULE - Table Definitions
-- Database: SCIDB
-- Module: Dispatch Plan Management
-- Created: March 9, 2026
-- ==========================================

USE SCIDB;
GO

-- Table: DISPATCH_PLAN_HEADER
CREATE TABLE [DISPATCH_PLAN_HEADER] (
    [DISPATCH_PLAN_HEADER_ID] INT NULL,
    [DISPATCH_PLAN_TYPE] CHAR(1) NULL,
    [DISPATCH_PLAN_MONTH] DATETIME2(3) NULL,
    [DISPATCH_PLAN_MPLUS1] VARCHAR(255) NULL,
    [DISPATCH_PLAN_MPLUS2] VARCHAR(255) NULL,
    [DISPATCH_PLAN_MPLUS3] VARCHAR(255) NULL,
    [DISPATCH_PLAN_MPLUS4] VARCHAR(255) NULL,
    [DISPATCH_PLAN_ENTRYDATE] DATETIME2(3) NULL,
    [COMPANY_UNIT_ID] INT NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_DISPATCH_PLAN_HEADER] PRIMARY KEY ([DISPATCH_PLAN_HEADER_ID])
);

-- Table: DISPATCH_PLAN_MAINGROUP
CREATE TABLE [DISPATCH_PLAN_MAINGROUP] (
    [MAIN_GROUP_ID] INT NOT NULL,
    [MAIN_GROUP_NAME] VARCHAR(20) NOT NULL,
    [GROUP_TYPE] CHAR(1) NOT NULL,
    [PRODUCT_SUMMARY] CHAR(1) NOT NULL,
    [TOTAL_DISPLAY_NAME] VARCHAR(20) NOT NULL,
    [MG_DISPLAY_ORDER] INT NOT NULL,
    [COMPANY_UNIT_ID] INT NOT NULL,
    [SCI_USER_ID_CREATED] INT NOT NULL,
    [CREATION_DATE] DATETIME2(3) NOT NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_DISPATCH_PLAN_MAINGROUP] PRIMARY KEY ([MAIN_GROUP_ID])
);

-- Table: DISPATCH_PLAN_SUBGROUP
CREATE TABLE [DISPATCH_PLAN_SUBGROUP] (
    [SUB_GROUP_ID] INT NOT NULL,
    [MAIN_GROUP_ID] INT NOT NULL,
    [SUB_GROUP_NAME] VARCHAR(20) NOT NULL,
    [PRODUCT_ID] INT NULL,
    [SG_DISPLAY_ORDER] INT NULL,
    [CAPTURE_TOTAL_DIRECTLY] CHAR(1) NOT NULL,
    [SCI_USER_ID_CREATED] INT NOT NULL,
    [CREATION_DATE] DATETIME2(3) NOT NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_DISPATCH_PLAN_SUBGROUP] PRIMARY KEY ([SUB_GROUP_ID])
);

-- Table: DISPATCH_PLAN_BREAKUP_ITEM
CREATE TABLE [DISPATCH_PLAN_BREAKUP_ITEM] (
    [BREAKUP_ITEM_ID] INT NOT NULL,
    [SUB_GROUP_ID] INT NOT NULL,
    [PRODUCT_ID] INT NOT NULL,
    [BREAKUP_ITEM_DESC] VARCHAR(4000) NOT NULL,
    [UNIT_ID] INT NOT NULL,
    [MAIN_PRODUCT_UNITS_CONFACTOR] INT NOT NULL,
    [BI_DISPLAY_ORDER] INT NOT NULL,
    [EFFECTIVE_DATE] DATETIME2(3) NOT NULL,
    [CLOSURE_DATE] VARCHAR(255) NULL,
    [SCI_USER_ID_CREATED] INT NOT NULL,
    [CREATION_DATE] DATETIME2(3) NOT NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] VARCHAR(255) NULL,
    [PACKAGE_ID] DECIMAL(38) NULL,
    CONSTRAINT [PK_DISPATCH_PLAN_BREAKUP_ITEM] PRIMARY KEY ([BREAKUP_ITEM_ID])
);

-- Table: DISPATCH_PLAN_ITEMWISE
CREATE TABLE [DISPATCH_PLAN_ITEMWISE] (
    [DISPATCH_PLAN_HEADER_ID] INT NOT NULL,
    [BREAKUP_ITEM_ID] INT NOT NULL,
    [TARGET_WEEK1] BIGINT NULL,
    [TARGET_WEEK2] BIGINT NULL,
    [TARGET_WEEK3] BIGINT NULL,
    [TARGET_WEEK4] BIGINT NULL,
    [TARGET_WEEK5] BIGINT NULL,
    [TARGET_MPLUS1] BIGINT NULL,
    [TARGET_MPLUS2] BIGINT NULL,
    [TARGET_MPLUS3] BIGINT NULL,
    [TARGET_MPLUS4] BIGINT NULL,
    [SCI_USER_ID_MODIFIED] INT NOT NULL,
    [MODIFIED_DATE] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_DISPATCH_PLAN_ITEMWISE] PRIMARY KEY ([DISPATCH_PLAN_HEADER_ID], [BREAKUP_ITEM_ID])
);

-- Table: DISPATCH_PLAN_SUBGROUPWISE
CREATE TABLE [DISPATCH_PLAN_SUBGROUPWISE] (
    [DISPATCH_PLAN_HEADER_ID] INT NOT NULL,
    [SUB_GROUP_ID] INT NOT NULL,
    [TARGET_WEEK1] BIGINT NULL,
    [TARGET_WEEK2] BIGINT NULL,
    [TARGET_WEEK3] BIGINT NULL,
    [TARGET_WEEK4] BIGINT NULL,
    [TARGET_WEEK5] BIGINT NULL,
    [TARGET_MPLUS1] BIGINT NULL,
    [TARGET_MPLUS2] BIGINT NULL,
    [TARGET_MPLUS3] BIGINT NULL,
    [TARGET_MPLUS4] BIGINT NULL,
    [SCI_USER_ID_MODIFIED] INT NOT NULL,
    [MODIFIED_DATE] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_DISPATCH_PLAN_SUBGROUPWISE] PRIMARY KEY ([DISPATCH_PLAN_HEADER_ID], [SUB_GROUP_ID])
);

-- Table: LOG_DISPATCH_PLAN_BREAKUP_ITEM (Log - Dispatch Plan Breakup Item)
CREATE TABLE [LOG_DISPATCH_PLAN_BREAKUP_ITEM] (
    [BREAKUP_ITEM_ID] INT NOT NULL,
    [SUB_GROUP_ID] INT NOT NULL,
    [PRODUCT_ID] INT NOT NULL,
    [BREAKUP_ITEM_DESC] VARCHAR(4000) NOT NULL,
    [UNIT_ID] INT NOT NULL,
    [MAIN_PRODUCT_UNITS_CONFACTOR] INT NOT NULL,
    [BI_DISPLAY_ORDER] INT NOT NULL,
    [EFFECTIVE_DATE] DATETIME2(3) NOT NULL,
    [CLOSURE_DATE] VARCHAR(255) NOT NULL,
    [SCI_USER_ID_CREATED] INT NOT NULL,
    [CREATION_DATE] DATETIME2(3) NOT NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] VARCHAR(255) NULL,
    [SCI_USER_ID_DELETE] INT NOT NULL,
    [DELETE_DATE] DATETIME2(3) NOT NULL,
    [PACKAGE_ID] DECIMAL(38) NULL
);

PRINT 'DISPATCH_PLANNING_MODULE Tables created successfully.';
GO
