apiVersion: v1
kind: Secret
metadata:
  name: cash-services-secrets
  namespace: cash-services
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: "CashServices2026!"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASS: "guest"
  ConnectionStrings__CASHDB: "Server=mssql-server.cash-services.svc.cluster.local;Database=CASHDB;User Id=sa;Password=CashServices2026!;Encrypt=False;TrustServerCertificate=True;Connection Timeout=30"
  ConnectionStrings__TransactionProcessingDb: "Server=mssql-server.cash-services.svc.cluster.local;Database=TransactionProcessingDb;User Id=sa;Password=CashServices2026!;Encrypt=False;TrustServerCertificate=True;Connection Timeout=30"
  ConnectionStrings__EmailNotificationDb: "Server=mssql-server.cash-services.svc.cluster.local;Database=EmailNotificationDb;User Id=sa;Password=CashServices2026!;Encrypt=False;TrustServerCertificate=True;Connection Timeout=30"
  JWT_SECRET: "YourSuperSecretKeyFor256BitHmacSha256AlgorithmMustBeAtLeast32Characters"
