-- ==========================================
-- FILLING OPERATIONS MODULE - Table Definitions
-- Database: SCIDB
-- Module: Filling Plant & Operations
-- Created: March 9, 2026
-- ==========================================

USE SCIDB;
GO

-- Table: FILLING_PLANT
CREATE TABLE [FILLING_PLANT] (
    [FILLING_PLANT_ID] INT NOT NULL,
    [COMPANY_UNIT_ID] INT NOT NULL,
    [FILLING_PLANT_NAME] VARCHAR(40) NOT NULL,
    [LOCATION] VARCHAR(20) NOT NULL,
    [SCI_USER_ID_CREATED] INT NOT NULL,
    [CREATION_DATE] DATETIME2(3) NOT NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_FILLING_PLANT] PRIMARY KEY ([FILLING_PLANT_ID])
);

-- Table: FILLING_LINE
CREATE TABLE [FILLING_LINE] (
    [FILLING_LINE_ID] INT NOT NULL,
    [FILLING_PLANT_ID] INT NOT NULL,
    [FILLING_LINE_NAME] VARCHAR(30) NOT NULL,
    [NO_OF_FILLING_POINTS] INT NOT NULL,
    [SCI_USER_ID_CREATED] INT NOT NULL,
    [CREATION_DATE] DATETIME2(3) NOT NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] VARCHAR(255) NULL,
    [PACKAGE_TYPE_ID] INT NULL,
    [ISCLOSED] VARCHAR(1) NULL,
    CONSTRAINT [PK_FILLING_LINE] PRIMARY KEY ([FILLING_LINE_ID])
);

-- Table: FILLING_POINT_GROUP
CREATE TABLE [FILLING_POINT_GROUP] (
    [FILLING_POINT_GROUP_ID] INT NOT NULL,
    [FILLING_POINT_GROUP_NAM] VARCHAR(30) NOT NULL,
    [FILLING_LINE_ID] INT NOT NULL,
    [NO_OF_FILLING_POINT] INT NOT NULL,
    [SCI_USER_ID_CREATED] INT NOT NULL,
    [CREATION_DATE] DATETIME2(3) NOT NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] VARCHAR(255) NULL,
    [EXCLUSIVE_USE] INT NULL,
    [ISCLOSED] VARCHAR(1) NULL,
    CONSTRAINT [PK_FILLING_POINT_GROUP] PRIMARY KEY ([FILLING_POINT_GROUP_ID])
);

-- Table: FILLING_LINE_PRODUCT_MAP (Filling Line - Product Mapping)
CREATE TABLE [FILLING_LINE_PRODUCT_MAP] (
    [FILLING_LINE_ID] INT NOT NULL,
    [MAIN_PRODUCT_ID] INT NOT NULL,
    [SCI_USER_ID_MODIFIED] INT NOT NULL,
    [MODIFIED_DATE] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_FILLING_LINE_PRODUCT_MAP] PRIMARY KEY ([FILLING_LINE_ID])
);

-- Table: FILLING_CAPACITY
CREATE TABLE [FILLING_CAPACITY] (
    [FILLING_POINT_GROUP_ID] INT NOT NULL,
    [MAIN_PRODUCT_ID] INT NOT NULL,
    [PACKAGE_TYPE_ID] INT NOT NULL,
    [ITEM_CAPACITY_ID] INT NOT NULL,
    [CAPACITY_PER_SHIFT] INT NOT NULL,
    [USAGE_PRIORITY] INT NOT NULL,
    [SCI_USERID_CREATED] INT NOT NULL,
    [CREATION_DATE] DATETIME2(3) NOT NULL,
    [SCI_USERID_MODIFIED] INT NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_FILLING_CAPACITY] PRIMARY KEY ([FILLING_POINT_GROUP_ID], [MAIN_PRODUCT_ID], [PACKAGE_TYPE_ID])
);

-- Table: FL_SWITCHOVER_TIME (Filling Line Switchover Time)
CREATE TABLE [FL_SWITCHOVER_TIME] (
    [FILLING_LINE_ID] INT NOT NULL,
    [FROM_MAIN_PRODUCT_ID] INT NOT NULL,
    [TO_MAIN_PRODUCT_ID] INT NOT NULL,
    [TIME_IN_HOURS] INT NOT NULL,
    [SCI_USER_ID_CREATED] INT NOT NULL,
    [CREATION_DATE] DATETIME2(3) NOT NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_FL_SWITCHOVER_TIME] PRIMARY KEY ([FILLING_LINE_ID], [FROM_MAIN_PRODUCT_ID], [TO_MAIN_PRODUCT_ID])
);

-- Table: FL_WORKING_SHIFT (Filling Line Working Shift)
CREATE TABLE [FL_WORKING_SHIFT] (
    [FL_WORKING_ID] DECIMAL(38) NULL,
    [FILLINGLINE_ID] DECIMAL(38) NOT NULL,
    [SHIFT_CODE] CHAR(1) NOT NULL,
    [START_DATE] DATETIME2(3) NOT NULL,
    [CLOSE_DATE] DATETIME2(3) NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL
);

-- Table: FPG_DOWNTIME (Filling Point Group Downtime)
CREATE TABLE [FPG_DOWNTIME] (
    [FPG_ID] INT NOT NULL,
    [FILLING_POINT_GROUP_ID] INT NULL,
    [START_DATE_TIME] DATETIME2(3) NOT NULL,
    [END_DATE_TIME] DATETIME2(3) NOT NULL,
    [NO_OF_FILLING_POINTS] CHAR(4) NULL,
    [DOWNTIME_TYPE] VARCHAR(255) NULL,
    [SCI_USER_ID_CREATED] INT NULL,
    [CREATION_DATE] DATETIME2(3) NOT NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_FPG_DOWNTIME] PRIMARY KEY ([FPG_ID])
);

-- Table: PLAN_DEVIATION (Plan Deviation)
CREATE TABLE [PLAN_DEVIATION] (
    [REASON_ID] INT NOT NULL,
    [PLAN_DATE] DATETIME2(3) NOT NULL,
    [FILLING_LINE_ID] INT NOT NULL,
    [PRODUCT_ID] INT NOT NULL,
    [REASON] VARCHAR(200) NULL,
    CONSTRAINT [PK_PLAN_DEVIATION] PRIMARY KEY ([REASON_ID])
);

PRINT 'FILLING_OPERATIONS_MODULE Tables created successfully.';
GO
