// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipmentService.Infrastructure.Data;

#nullable disable

namespace ShipmentService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ShipmentDbContext))]
    [Migration("20260321141017_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShipmentService.Domain.Entities.DeliveryAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attempt_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttemptDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("attempt_date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reason");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("result");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int")
                        .HasColumnName("shipment_id");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("DeliveryAttempt", (string)null);
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentsDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contents_description");

                    b.Property<string>("Dimensions")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("dimensions");

                    b.Property<string>("PackageNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("package_number");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int")
                        .HasColumnName("shipment_id");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tracking_number");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("volume");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasAlternateKey("ShipmentId", "PackageNumber")
                        .HasName("UQ_Package_Shipment");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("IX_Package_Shipment");

                    b.ToTable("Package", (string)null);
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shipment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Carrier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("carrier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("service_type");

                    b.Property<string>("ShipmentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("shipment_number");

                    b.Property<string>("ShipmentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("shipment_type");

                    b.Property<DateTime>("ShippedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("shipped_date");

                    b.Property<int?>("SoId")
                        .HasColumnType("int")
                        .HasColumnName("so_id");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("special_instructions");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalVolume")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("total_volume");

                    b.Property<decimal?>("TotalWeight")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("total_weight");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tracking_number");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Shipment_Customer");

                    b.HasIndex("ShipmentNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Shipment_ShipmentNumber");

                    b.HasIndex("SoId")
                        .HasDatabaseName("IX_Shipment_SO");

                    b.HasIndex("TrackingNumber")
                        .HasDatabaseName("IX_Shipment_TrackingNumber")
                        .HasFilter("tracking_number IS NOT NULL");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_Shipment_Warehouse");

                    b.ToTable("Shipment", (string)null);
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.ShipmentLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shipment_line_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BinId")
                        .HasColumnType("int")
                        .HasColumnName("bin_id");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lot_number");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<decimal>("QuantityShipped")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("quantity_shipped");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int")
                        .HasColumnName("shipment_id");

                    b.Property<int?>("SoLineId")
                        .HasColumnType("int")
                        .HasColumnName("so_line_id");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("BinId")
                        .HasDatabaseName("IX_ShipmentLine_Bin");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_ShipmentLine_Product");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("IX_ShipmentLine_Shipment");

                    b.HasIndex("SoLineId")
                        .HasDatabaseName("IX_ShipmentLine_SOLine");

                    b.ToTable("ShipmentLine", (string)null);
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.TrackingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tracking_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EventDatetime")
                        .HasColumnType("datetime2")
                        .HasColumnName("event_datetime");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("location");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("IX_TrackingHistory_Shipment");

                    b.ToTable("TrackingHistory", (string)null);
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.DeliveryAttempt", b =>
                {
                    b.HasOne("ShipmentService.Domain.Entities.Shipment", "Shipment")
                        .WithMany("DeliveryAttempts")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.Package", b =>
                {
                    b.HasOne("ShipmentService.Domain.Entities.Shipment", "Shipment")
                        .WithMany("Packages")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.ShipmentLine", b =>
                {
                    b.HasOne("ShipmentService.Domain.Entities.Shipment", "Shipment")
                        .WithMany("Lines")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.TrackingHistory", b =>
                {
                    b.HasOne("ShipmentService.Domain.Entities.Shipment", "Shipment")
                        .WithMany("TrackingHistory")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.Shipment", b =>
                {
                    b.Navigation("DeliveryAttempts");

                    b.Navigation("Lines");

                    b.Navigation("Packages");

                    b.Navigation("TrackingHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
