-- MASTERS MODULE - SCHEMA DEFINITION
-- Reference and lookup data used across the system

USE [Careers]
GO

/****** SPECIALISATION_MASTER ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SPECIALISATION_MASTER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[SPECIALISATION] [varchar](50) NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** FUNCTION_MASTER ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FUNCTION_MASTER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[FUNCTION_NAME] [varchar](100) NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** INDUCTRY_DOMAIN_MASTER ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[INDUCTRY_DOMAIN_MASTER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[INDUSTRY_DOMAIN] [varchar](50) NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** LOCATION_MASTER ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOCATION_MASTER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PREFERED_LOCATION] [varchar](50) NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** RELATIONSHIP_MASTER ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RELATIONSHIP_MASTER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[RELATIONSHIP] [varchar](30) NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** CLASS_MASTER ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CLASS_MASTER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CLASS_NAME] [varchar](50) NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[CHANGED_BY] [varchar](50) NULL,
	[CHANGED_ON] [datetime] NULL,
	[ISVALID] [bit] NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
