// <auto-generated />
using System;
using HRDocumentService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRDocumentService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HRDocumentDbContext))]
    [Migration("20260319132320_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRDocumentService.Domain.Entities.HRDocument", b =>
                {
                    b.Property<long>("DocId")
                        .HasColumnType("bigint")
                        .HasColumnName("DOC_ID");

                    b.Property<string>("DocActionStatus")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("DOC_ACTIONSTATUS");

                    b.Property<decimal?>("DocActionTakenBy")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("DOC_ACTIONTAKENBY");

                    b.Property<DateTime?>("DocActionTakenOn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("DOC_ACTIONTAKENON");

                    b.Property<decimal?>("DocCancelBy")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("DOC_CANCELBY");

                    b.Property<string>("DocCancelFlag")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("DOC_CANCELFLAG");

                    b.Property<DateTime?>("DocCancelOn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("DOC_CANCELON");

                    b.Property<DateTime>("DocCreatedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("DOC_CREATEDON");

                    b.Property<string>("DocDocStatus")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("DOC_DOCSTATUS");

                    b.Property<string>("DocFilePath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DOC_FILEPATH");

                    b.Property<long>("DocLocId")
                        .HasColumnType("bigint")
                        .HasColumnName("DOC_LOCID");

                    b.Property<long>("DocNo")
                        .HasColumnType("bigint")
                        .HasColumnName("DOC_NO");

                    b.Property<decimal?>("DocPayBy")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("DOC_PAYBY");

                    b.Property<long>("DocPayRefNo")
                        .HasColumnType("bigint")
                        .HasColumnName("DOC_PAYREFNO");

                    b.Property<string>("DocRefName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DOC_REFNAME");

                    b.Property<string>("DocRefNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DOC_REFNO");

                    b.Property<string>("DocRejectRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DOC_REJECTREMARKS");

                    b.Property<string>("DocRemarks")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DOC_REMARKS");

                    b.Property<string>("DocSource")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("DOC_SOURCE");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("DOC_TYPE");

                    b.Property<long>("DocUnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("DOC_UNITID");

                    b.Property<long>("DocUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("DOC_USERID");

                    b.HasKey("DocId");

                    b.ToTable("HRDOC_DET", (string)null);
                });

            modelBuilder.Entity("HRDocumentService.Domain.Entities.HRDocumentCounter", b =>
                {
                    b.Property<long>("DocNo")
                        .HasColumnType("bigint")
                        .HasColumnName("DOC_NO");

                    b.ToTable("HRDOC_COUNTER", (string)null);
                });

            modelBuilder.Entity("HRDocumentService.Domain.Entities.HRDocumentFile", b =>
                {
                    b.Property<long>("FileId")
                        .HasColumnType("bigint")
                        .HasColumnName("FILE_ID");

                    b.Property<long>("FileDocId")
                        .HasColumnType("bigint")
                        .HasColumnName("FILE_DOCID");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FILE_NAME");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("FILE_PATH");

                    b.HasKey("FileId");

                    b.HasIndex("FileDocId");

                    b.ToTable("HRDOC_SSFILELIST", (string)null);
                });

            modelBuilder.Entity("HRDocumentService.Domain.Entities.HRDocumentReceipt", b =>
                {
                    b.Property<long>("HRRecId")
                        .HasColumnType("bigint")
                        .HasColumnName("HRREC_ID");

                    b.Property<long>("HRRecEnvId")
                        .HasColumnType("bigint")
                        .HasColumnName("HRREC_ENVID");

                    b.Property<long>("HRRecHRDocId")
                        .HasColumnType("bigint")
                        .HasColumnName("HRREC_HRDOCID");

                    b.Property<long>("HRRecUpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("HRREC_UPDATEDBY");

                    b.Property<DateTime>("HRRecUpdatedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("HRREC_UPDATEDON");

                    b.HasKey("HRRecId");

                    b.HasIndex("HRRecHRDocId");

                    b.ToTable("HRDOC_RECDET", (string)null);
                });

            modelBuilder.Entity("HRDocumentService.Domain.Entities.HRDocumentFile", b =>
                {
                    b.HasOne("HRDocumentService.Domain.Entities.HRDocument", null)
                        .WithMany("Files")
                        .HasForeignKey("FileDocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRDocumentService.Domain.Entities.HRDocumentReceipt", b =>
                {
                    b.HasOne("HRDocumentService.Domain.Entities.HRDocument", null)
                        .WithMany("Receipts")
                        .HasForeignKey("HRRecHRDocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRDocumentService.Domain.Entities.HRDocument", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Receipts");
                });
#pragma warning restore 612, 618
        }
    }
}
