-- =========================================================================
-- INVESTMENT MODULE - Database Tables
-- Database: PFDB
-- Module: Investment Portfolio Management
-- Description: Manages investment portfolio and redemption operations
-- Created: March 9, 2026
-- =========================================================================

USE PFDB;
GO

-- Investment Main Records
CREATE TABLE [INV_MAIN] (
    [INV_NO] BIGINT NOT NULL PRIMARY KEY,
    [INV_GRPID] INT NULL,
    [INV_CATID] INT NULL,
    [INV_SUBCATID] INT NULL,
    [INV_TENURE] INT NULL,
    [INV_TENUREDAYS] INT NULL,
    [INV_INTOPTION] CHAR(2) NULL,
    [INV_ORGPURDATE] DATETIME2(3) NULL,
    [INV_MATDATE] DATETIME2(3) NULL,
    [INV_CALLPUTOPTION] CHAR(1) NULL,
    [INV_PURDATE] DATETIME2(3) NULL,
    [INV_CALLPER] DECIMAL(19,0) NULL,
    [INV_UNITS] DECIMAL(19,0) NULL,
    [INV_PURRATE] DECIMAL(19,0) NULL,
    [INV_FACEVALUE] DECIMAL(19,0) NULL,
    [INV_PREMIUM] DECIMAL(19,0) NULL,
    [INV_ISSINTRATE] DECIMAL(19,0) NULL,
    [INV_REVINTFROM] DATETIME2(3) NULL,
    [INV_REVINTRATE] DECIMAL(19,0) NULL,
    [INV_INTDENOM] DECIMAL(19,0) NULL,
    [INV_PURVALUE] DECIMAL(19,0) NULL,
    [INV_SECMARKET] CHAR(1) NULL,
    [INV_BROKERID] INT NULL,
    [INV_CUMINTFROM] DATETIME2(3) NULL,
    [INV_CUMINTTO] DATETIME2(3) NULL,
    [INV_CUMINTAMT] DECIMAL(19,0) NULL,
    [INV_CUMINTDYS] INT NULL,
    [INV_CRAGENCY1] INT NULL,
    [INV_CRAGENCY2] INT NULL,
    [INV_RATING1] INT NULL,
    [INV_RATING2] INT NULL,
    [INV_CLIENTID] VARCHAR(250) NULL,
    [INV_INTFREQUENCY] CHAR(1) NULL,
    [INV_PAYMODE] CHAR(1) NULL,
    [INV_INTDATES] VARCHAR(250) NULL,
    [INV_BANKID] INT NULL,
    [INV_CHQNUM] VARCHAR(20) NULL,
    [INV_CHQDATE] DATETIME2(3) NULL,
    [INV_BANKCHARGES] DECIMAL(19,0) NULL,
    [INV_STATUS] CHAR(1) NULL,
    [INV_CERTNO] VARCHAR(50) NULL,
    [INV_ENTEREDBY] BIGINT NULL,
    [INV_ENTEREDON] DATETIME2(3) NULL,
    [INV_LASTMODBY] BIGINT NULL,
    [INV_LASTMODON] DATETIME2(3) NULL,
    [INV_LASTSCHDATE] DATETIME2(3) NULL,
    [INV_YTMRATE] DECIMAL(19,0) NULL,
    [INV_NETVAL] DECIMAL(19,0) NULL
);
GO

-- Redemption/Sale Details
CREATE TABLE [INV_SALEDET] (
    [INV_SALENO] BIGINT NOT NULL PRIMARY KEY,
    [INV_NO] BIGINT NOT NULL,
    [INV_SALETYPE] CHAR(1) NOT NULL,
    [INV_SALEDATE] DATETIME2(3) NOT NULL,
    [INV_INTADJUSTED] DECIMAL(19,0) NOT NULL,
    [INV_SALPREMIUM] DECIMAL(19,0) NOT NULL,
    [INV_SALVALUE] DECIMAL(19,0) NOT NULL,
    [INV_SALTRANID] INT NOT NULL,
    [INV_SALREMARKS] VARCHAR(200) NULL,
    [INV_ENTEREDBY] BIGINT NOT NULL,
    [INV_ENTEREDON] DATETIME2(3) NOT NULL,
    [INV_LASTMODBY] BIGINT NOT NULL,
    [INV_LASTMODON] DATETIME2(3) NOT NULL
);
GO

-- Interest Schedule Details
CREATE TABLE [INV_SCHDET] (
    [SCH_ID] BIGINT NOT NULL PRIMARY KEY,
    [SCH_INVNO] BIGINT NOT NULL,
    [SCH_SLID] BIGINT NOT NULL,
    [SCH_TYPE] CHAR(3) NOT NULL,
    [SCH_INTFROM] DATETIME2(3) NOT NULL,
    [SCH_INTTO] DATETIME2(3) NOT NULL,
    [SCH_INTOPTION] DECIMAL(19,0) NOT NULL,
    [SCH_DUEAMT] DECIMAL(19,0) NOT NULL,
    [SCH_DUEDATE] DATETIME2(3) NOT NULL,
    [SCH_RECAMT] DECIMAL(19,0) NULL,
    [SCH_RECDATE] DATETIME2(3) NULL,
    [SCH_RECTRANID] BIGINT NULL,
    [SCH_LOGSYSID] BIGINT NULL,
    [SCH_YEAR] BIGINT NULL
);
GO

-- Call Details
CREATE TABLE [INV_CALLDET] (
    [INV_CALLDETID] BIGINT NOT NULL PRIMARY KEY,
    [INV_INVNO] BIGINT NOT NULL,
    [INV_CALLDATE] DATETIME2(3) NOT NULL,
    [INV_CALLAMOUNT] DECIMAL(19,0) NOT NULL,
    [INV_CNFSTATUS] CHAR(1) NOT NULL,
    [INV_INTREVFLAG] CHAR(1) NOT NULL,
    [INV_REVINTRATE] DECIMAL(19,0) NULL,
    [INV_SALEREFID] BIGINT NULL,
    [INV_LASTMODBY] DECIMAL(38) NULL,
    [INV_LASTMODON] DATETIME2(3) NULL,
    [INV_SLNO] BIGINT NULL
);
GO

-- Approval Details
CREATE TABLE [INV_APPRDETAILS] (
    [INV_APRDETID] DECIMAL(38) NOT NULL PRIMARY KEY,
    [INV_INVID] DECIMAL(38) NOT NULL,
    [INV_REFID] DECIMAL(38) NOT NULL,
    [INV_APRLEVEL] DECIMAL(38) NOT NULL,
    [INV_FLAG] CHAR(1) NOT NULL,
    [INV_APPROVERSYSID] DECIMAL(38) NOT NULL,
    [INV_APPROVEDON] DATETIME2(3) NULL,
    [INV_REMARKS] VARCHAR(200) NULL
);
GO

-- Category Masters
CREATE TABLE [INVCAT_MAST] (
    [INVCAT_CODE] INT NOT NULL PRIMARY KEY,
    [INVCAT_SHTCODE] VARCHAR(10) NOT NULL,
    [INVCAT_NAME] VARCHAR(50) NOT NULL,
    [INVCAT_DENOM] BIGINT NOT NULL,
    [INVCAT_GRPID] INT NOT NULL
);
GO

CREATE TABLE [INVSUBCAT_MAST] (
    [INVSUBCAT_ID] INT NOT NULL PRIMARY KEY,
    [INVSUBCAT_SHTNAME] VARCHAR(10) NOT NULL,
    [INVSUBCAT_NAME] VARCHAR(50) NOT NULL,
    [INVSUBCAT_CATID] INT NOT NULL,
    [INVSUBCAT_INTDEN] BIGINT NULL,
    [INVSUBCAT_SUBCAT] BIGINT NULL
);
GO

-- Credit Rating and Agency Masters
CREATE TABLE [CREDITAGENCY_MAST] (
    [AGENCY_ID] INT NOT NULL PRIMARY KEY,
    [AGENCY_NAME] VARCHAR(50) NOT NULL
);
GO

CREATE TABLE [CREDITRATING_MAST] (
    [RATING_ID] INT NOT NULL PRIMARY KEY,
    [RATING_NAME] VARCHAR(50) NOT NULL
);
GO

-- Broker Master
CREATE TABLE [INVBROKER_MASTER] (
    [BROKER_ID] DECIMAL(38) NOT NULL PRIMARY KEY,
    [BROKER_NAME] VARCHAR(50) NOT NULL,
    [BROKER_STATUS] CHAR(1) NOT NULL
);
GO

-- Interest Schedule Batch
CREATE TABLE [INV_INTSCHBATCH] (
    [INV_INTSCHBATHNO] BIGINT NOT NULL PRIMARY KEY,
    [INV_INTSCHINVID] BIGINT NULL,
    [INV_INVSCHYEAR] BIGINT NULL,
    [INV_INVSCHPREVRUNDATE] DATETIME2(3) NULL,
    [INV_INVSCHLASTRUNDATE] DATETIME2(3) NULL,
    [INV_INVSCHENTON] DATETIME2(3) NULL,
    [INV_INVSCHENTBY] DECIMAL(38) NULL
);
GO

-- Bank Details
CREATE TABLE [INV_BANKDET] (
    [BNK_TRANID] DECIMAL(38) NOT NULL PRIMARY KEY,
    [BNK_ENTRYTYPE] CHAR(3) NOT NULL,
    [BNK_TRANTYPE] CHAR(3) NOT NULL,
    [BNK_INVNO] BIGINT NOT NULL,
    [BNK_TRNAMT] DECIMAL(19,0) NOT NULL,
    [BNK_ID] BIGINT NOT NULL,
    [BNK_DEMATID] BIGINT NOT NULL,
    [BNK_TRANDATE] DATETIME2(3) NOT NULL,
    [BNK_REMARKS] VARCHAR(200) NOT NULL
);
GO

-- Create indexes
CREATE NONCLUSTERED INDEX [IDX_INV_MAIN_STATUS] ON [INV_MAIN] ([INV_STATUS]) INCLUDE ([INV_NO], [INV_PURDATE]);
CREATE NONCLUSTERED INDEX [IDX_INV_SALEDET_INVNO] ON [INV_SALEDET] ([INV_NO]) INCLUDE ([INV_SALEDATE]);
CREATE NONCLUSTERED INDEX [IDX_INV_SCHDET_INVNO] ON [INV_SCHDET] ([SCH_INVNO], [SCH_DUEDATE]);
CREATE NONCLUSTERED INDEX [IDX_INVCAT_MAST_NAME] ON [INVCAT_MAST] ([INVCAT_NAME]);

PRINT 'Investment Module Tables created successfully!';
GO
