FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["src/API/AgencyService.Api/AgencyService.Api.csproj", "src/API/AgencyService.Api/"]
COPY ["src/Application/AgencyService.Application/AgencyService.Application.csproj", "src/Application/AgencyService.Application/"]
COPY ["src/Domain/AgencyService.Domain/AgencyService.Domain.csproj", "src/Domain/AgencyService.Domain/"]
COPY ["src/Infrastructure/AgencyService.Infrastructure/AgencyService.Infrastructure.csproj", "src/Infrastructure/AgencyService.Infrastructure/"]

RUN dotnet restore "src/API/AgencyService.Api/AgencyService.Api.csproj"

COPY . .

RUN dotnet publish "src/API/AgencyService.Api/AgencyService.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
EXPOSE 8080

ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_URLS=http://+:8080

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "AgencyService.Api.dll"]
