<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AttendanceService.Functions</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AttendanceService.Application\AttendanceService.Application.csproj" />
    <ProjectReference Include="..\AttendanceService.Infrastructure\AttendanceService.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.2" />
  </ItemGroup>

</Project>
