-- Recruitment Module - Tables
USE [HRDB];
GO

-- Table: APPLICATION_HISTORY
CREATE TABLE [APPLICATION_HISTORY] (
    [APP_ID] DECIMAL(38) NOT NULL  -- Application ID,
    [APP_SL] DECIMAL(38) NOT NULL  -- Serial No,
    [APP_UNIT] CHAR(3) NULL  -- Application Unit,
    [APP_VACANCYID] DECIMAL(38) NULL  -- Vacancy ID,
    [APP_STATUS] CHAR(2) NULL  -- 01 - Application Received ; 02 - In Progress ; 03 - Not Suitable ; 04 - Shortlisted ;  05 - Selected ; 06 - Rejected,
    [APP_REMARKS] VARCHAR(4000) NULL  -- Application Remarks,
    [APP_UPDATEDBY] DECIMAL(22,0) NULL  -- Last updated by,
    [APP_UPDATEDON] DATETIME2(3) NULL  -- Last updated on,
    CONSTRAINT [PK_APPLICATION_HISTORY] PRIMARY KEY ([APP_ID])
);



-- Table: APPLICATION_QUALIFICATION
CREATE TABLE [APPLICATION_QUALIFICATION] (
    [APP_ID] DECIMAL(38) NOT NULL  -- Applicataion ID,
    [APP_QUAL_ID] DECIMAL(38) NOT NULL  -- Qualification ID,
    [APP_QUAL_CODE] DECIMAL(38) NULL  -- Qualification Code,
    [APP_QUAL_DESC] VARCHAR(65) NULL  -- Qualification Description,
    [APP_QUAL_YEARFRO] CHAR(7) NULL  -- Year from (MMYYYY),
    [APP_QUAL_YEARTO] CHAR(7) NULL  -- Year to (MMYYYY),
    [APP_QUAL_INST_CODE] CHAR(3) NULL  -- Institution Code,
    [APP_QUAL_INST_DESC] VARCHAR(65) NULL  -- Institution Description,
    [APP_QUAL_EDU_TYPE] CHAR(1) NULL  -- F - Full Time ; P - Partime ; C - Correspondance,
    [APP_QUAL_SPE_CODE] DECIMAL(38) NULL  -- Specialization Code,
    [APP_QUAL_SPE_DESC] VARCHAR(65) NULL  -- Specialization Description,
    [APP_QUAL_PERCENTAGE] VARCHAR(10) NULL  -- Percentage / Class,
    [APP_QUAL_DEGREE_CODE] DECIMAL(38) NULL  -- Degree Code,
    [APP_QUAL_DEGREE_DESC] VARCHAR(65) NULL  -- Degree Description,
    [APP_QUAL_INST_OTHERS] VARCHAR(100) NULL  -- Qualification Others,
    CONSTRAINT [PK_APPLICATION_QUALIFICATION] PRIMARY KEY ([APP_ID])
);



-- Table: APPLICATION_TRAINING
CREATE TABLE [APPLICATION_TRAINING] (
    [APP_ID] DECIMAL(38) NOT NULL  -- Applicataion ID,
    [APP_TRAINING_ID] DECIMAL(38) NOT NULL  -- Training ID,
    [APP_TRAINING_TITLE] VARCHAR(2000) NULL  -- Training Title,
    [APP_TRAINING_DURATION] VARCHAR(2000) NULL  -- Training Duration,
    [APP_TRAINING_INSTITUTE] VARCHAR(2000) NULL  -- Training Institute,
    [APP_TRAINING_LOCATION] VARCHAR(2000) NULL  -- Training Location,
    CONSTRAINT [PK_APPLICATION_TRAINING] PRIMARY KEY ([APP_ID])
);



-- Table: PROSPECT_ADDRESS
CREATE TABLE [PROSPECT_ADDRESS] (
    [ADDRESS_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [ADDRESS_FLAG] CHAR(1) NOT NULL  -- Address Flag - C/P,
    [ADDRESS_1] VARCHAR(65) NULL  -- Address - 1,
    [ADDRESS_2] VARCHAR(65) NULL  -- Address - 2,
    [ADDRESS_3] VARCHAR(65) NULL  -- Address - 3,
    [ADDRESS_4] VARCHAR(65) NULL  -- Address - 4,
    [ADDRESS_CITY] DECIMAL(38) NULL  -- City,
    [ADDRESS_PINCODE] DECIMAL(38) NULL  -- PIN Code,
    [ADDRESS_UPDATED_BY] DECIMAL(38) NULL  -- Mobile No,
    [ADDRESS_UPDATED_ON] DATETIME2(3) NULL  -- Landline number,
    [ADDRESS_MOBNO] VARCHAR(65) NULL,
    [ADDRESS_LANDLINE] VARCHAR(65) NULL,
    CONSTRAINT [PK_PROSPECT_ADDRESS] PRIMARY KEY ([ADDRESS_EMP_SYSID])
);



-- Table: PROSPECT_QUALIFICATION
CREATE TABLE [PROSPECT_QUALIFICATION] (
    [QUAL_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [QUAL_ID] DECIMAL(38) NOT NULL  -- Qualification ID,
    [QUAL_CODE] DECIMAL(38) NOT NULL  -- Qualification Code,
    [QUAL_DESC] VARCHAR(65) NULL  -- Qualification Description,
    [QUAL_YEARFRO] CHAR(6) NULL  -- Year from (MMYYYY),
    [QUAL_YEARTO] CHAR(6) NULL  -- Year to (MMYYYY),
    [QUAL_INST_CODE] DECIMAL(22,0) NULL  -- Institution Code,
    [QUAL_INST_DESC] VARCHAR(65) NULL  -- Institution Description,
    [QUAL_EDU_TYPE] CHAR(1) NULL  -- F - Full Time ; P - Partime ; C - Correspondance,
    [QUAL_SPE_CODE] DECIMAL(38) NULL  -- Specialization Code,
    [QUAL_SPE_DESC] VARCHAR(65) NULL  -- Specialization Description,
    [QUAL_PERCENTAGE] VARCHAR(10) NULL  -- Percentage / Class,
    [QUAL_DEGREE_CODE] DECIMAL(38) NULL  -- Degree Code,
    [QUAL_DEGREE_DESC] VARCHAR(65) NULL  -- Degree Description,
    [QUAL_UPDATEDBY] DECIMAL(38) NULL  -- Last updated by,
    [QUAL_UPDATEDON] DATETIME2(3) NULL  -- Last updated on,
    CONSTRAINT [PK_PROSPECT_QUALIFICATION] PRIMARY KEY ([QUAL_EMP_SYSID])
);



-- Table: PROSPECT_REFERENCE
CREATE TABLE [PROSPECT_REFERENCE] (
    [REF_EMP_SYS_ID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [REF_ID] DECIMAL(38) NOT NULL  -- Reference ID,
    [REF_NAME] VARCHAR(65) NULL  -- Reference Name,
    [REF_DESGN] VARCHAR(65) NULL  -- Reference Designation,
    [REF_ADDRESS1] VARCHAR(200) NULL  -- Reference Address-1,
    [REF_ADDRESS2] VARCHAR(200) NULL  -- Reference Address-2,
    [REF_PHONE] VARCHAR(50) NULL  -- Reference Phone,
    [REF_EMAIL] VARCHAR(200) NULL  -- Reference Email-ID,
    CONSTRAINT [PK_PROSPECT_REFERENCE] PRIMARY KEY ([REF_EMP_SYS_ID])
);



-- Table: PROSPECT_TRAINEE
CREATE TABLE [PROSPECT_TRAINEE] (
    [PROSPECT_ID] DECIMAL(22,0) NOT NULL  -- Regular Prospect ID,
    [TRAINEED_ID] DECIMAL(22,0) NOT NULL  -- Trainee Prospect ID,
    CONSTRAINT [PK_PROSPECT_TRAINEE] PRIMARY KEY ([PROSPECT_ID])
);



-- Table: PROSPECT_TRAINING
CREATE TABLE [PROSPECT_TRAINING] (
    [TRAINING_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [TRAINING_ID] DECIMAL(38) NOT NULL  -- Training ID,
    [TRAINING_TITLE] VARCHAR(2000) NULL  -- Training Title,
    [TRAINING_DURATION] VARCHAR(2000) NULL  -- Training Duration,
    [TRAINING_INSTITUTE] VARCHAR(2000) NULL  -- Training Institute,
    [TRAINING_LOCATION] VARCHAR(2000) NULL  -- Training Location,
    CONSTRAINT [PK_PROSPECT_TRAINING] PRIMARY KEY ([TRAINING_EMP_SYSID])
);



-- Table: VACANCY_MAIN
CREATE TABLE [VACANCY_MAIN] (
    [VACANCY_ID] DECIMAL(38) NOT NULL  -- Vacancy ID - Irrespective of Units,
    [VACANCY_UNIT] CHAR(3) NOT NULL  -- Unit Code,
    [VACANCY_GRADE] DECIMAL(38) NOT NULL  -- Grade,
    [VACANCY_POSITIONID] DECIMAL(38) NOT NULL  -- Position ID,
    [VACANCY_NAME] VARCHAR(65) NOT NULL  -- Vacancy Name,
    [VACANCY_REPORTING] VARCHAR(65) NULL  -- Reporting To,
    [VACANCY_LOCATION] DECIMAL(38) NOT NULL  -- Location of Work,
    [VACANCY_PROCESS] DECIMAL(38) NOT NULL  -- Process/Department,
    [VACANCY_AGE] VARCHAR(65) NOT NULL  -- Age criteria,
    [VACANCY_EXPERIENCE] VARCHAR(4000) NOT NULL  -- Minimum Experience Required,
    [VACANCY_QUALIFICATION] VARCHAR(4000) NOT NULL  -- Minimum Qualification Required,
    [VACANCY_NARRATION1] VARCHAR(4000) NULL  -- Roles and Responsibilties,
    [VACANCY_NARRATION2] VARCHAR(4000) NULL  -- Accountabilities/Control Points,
    [VACANCY_NARRATION3] VARCHAR(4000) NULL  -- Key Expectations,
    [VACANCY_NARRATION4] VARCHAR(1000) NULL  -- Eligibility Criteria,
    [VACANCY_ATTACHMENT] VARCHAR(65) NULL  -- File Attachment,
    [VACANCY_LASTDATE] DATETIME2(3) NULL  -- Last date for application,
    [VACANCY_ADINTRAFLAG] CHAR(1) NULL  -- Advt. in Intranet (Y/N),
    [VACANCY_ADINTRAFRODATE] DATETIME2(3) NULL  -- Advt. to be posted on,
    [VACANCY_ADINTRATODATE] DATETIME2(3) NULL  -- Advt. to be removed on,
    [VACANCY_ADINTERFLAG] CHAR(1) NULL  -- Advt. in Internet (Y/N),
    [VACANCY_ADINTERFRODATE] DATETIME2(3) NULL  -- Advt. to be posted on,
    [VACANCY_ADINTERTODATE] DATETIME2(3) NULL  -- Advt. to be removed on,
    [VACANCY_POSTBY] DECIMAL(38) NULL  -- Vacancy Posted by User ID,
    [VACANCY_POSTDATE] DATETIME2(3) NULL  -- Vacancy Posted on,
    [VACANCY_MODBY] DECIMAL(38) NULL  -- Vacancy Modified by User ID,
    [VACANCY_MODDATE] DATETIME2(3) NULL  -- Vacancy Modified on,
    [VACANCY_LIVESTATUS] CHAR(1) NULL  -- Y - Open ; N - Closed,
    [VACANCY_REMARKS] VARCHAR(4000) NULL,
    [VACANCY_INTREFRFLAG] CHAR(1) NULL  -- Internal Refferal allowed (Y/N),
    [VACANCY_INTREFMAILID] VARCHAR(65) NULL  -- Mail id for Internal Referral,
    [VACANCY_UNITID] DECIMAL(22,0) NOT NULL  -- Unit ID,
    [VACANCY_TYPE] VARCHAR(3) NULL  -- MS/NMS,
    [VACANCY_GRADELIST] VARCHAR(4000) NULL  -- Grade List in case of NMS,
    [VACANCY_GRADETYPE] VARCHAR(5) NULL  -- Grade Category,
    [VACANCY_NOS] DECIMAL(22,0) NULL  -- No of Vacancies,
    [VACANCY_CTCFROM] DECIMAL(38) NULL  -- CTC Range From,
    [VACANCY_CTCTO] DECIMAL(38) NULL  -- CTC Range To,
    [VACANCY_DESIGNATION] VARCHAR(100) NULL  -- Designation,
    [VACANCY_DOWNLOADFORM] CHAR(1) NULL  -- Allow to download application form,
    [VACANCY_APPLICATIONFORM] VARCHAR(200) NULL  -- Application Form File Name,
    [VACANCY_UPLOADRESUME] CHAR(1) NULL  -- Allow to upload resume,
    [VACANCY_INTREFCLSDATE] DATETIME2(3) NULL  -- Close Date for Employee Referral,
    [VACANCY_DISABILITYFLAG] CHAR(1) NULL,
    [VACANCY_DISABILITYLIMIT] VARCHAR(500) NULL,
    CONSTRAINT [PK_VACANCY_MAIN] PRIMARY KEY ([VACANCY_ID])
);



-- Table: WEBPROSPECT_MAST
CREATE TABLE [WEBPROSPECT_MAST] (
    [WEBUSER_ID] DECIMAL(38) NULL  -- User ID,
    [WEBUSER_PWD] VARCHAR(10) NULL  -- Password,
    [WEBUSER_FRS_NAME] VARCHAR(65) NULL  -- First Name,
    [WEBUSER_MID_NAME] VARCHAR(65) NULL  -- Middle Name,
    [WEBUSER_LST_NAME] VARCHAR(65) NULL  -- Last Name,
    [WEBUSER_EMAILID] VARCHAR(200) NULL  -- Email ID,
    [WEBUSER_STATUS] CHAR(1) NULL  -- L - Live ; C - Closed,
    [WEBUSER_DATEOFBIRTH] DATETIME2(3) NULL,
    [WEBUSER_CREATEDON] DATETIME2(3) NULL,
    [WEBUSER_TYPE] CHAR(1) NULL
);



-- Table: PREOFFER_MAIN
CREATE TABLE [PREOFFER_MAIN] (
    [PREOFFER_ID] DECIMAL(38) NOT NULL  -- PreOffer ID,
    [PREOFFER_NAME] VARCHAR(200) NOT NULL  -- Prospect Name,
    [PREOFFER_VERSION] DECIMAL(38) NOT NULL  -- Version,
    [PREOFFER_UNITID] DECIMAL(38) NOT NULL  -- Unit ID,
    [PREOFFER_GRADEID] DECIMAL(38) NOT NULL  -- Grade ID,
    [PREOFFER_EXPDOJ] DATETIME2(3) NOT NULL  -- Expected Date of Joining,
    [PREOFFER_LETTER_DATE] DATETIME2(3) NOT NULL  -- Letter given on,
    [PREOFFER_SALARYID] DECIMAL(38) NOT NULL  -- Salary ID,
    [PREOFFER_COMMENTS] VARCHAR(200) NULL  -- Comments,
    [PREOFFER_CREATEDBY] DECIMAL(38) NOT NULL  -- Created By,
    [PREOFFER_CREATEDON] DATETIME2(3) NOT NULL  -- Created On,
    [PREOFFER_MODIFIEDBY] DECIMAL(38) NULL,
    [PREOFFER_MODIFEDON] DATETIME2(3) NULL,
    [PREOFFER_ANNEXSIGNID] DECIMAL(38) NULL,
    [PREOFFER_PAYUNITID] DECIMAL(38) NULL,
    CONSTRAINT [PK_PREOFFER_MAIN] PRIMARY KEY ([PREOFFER_ID])
);



-- Table: EMPLOYEE_OFFER
CREATE TABLE [EMPLOYEE_OFFER] (
    [OFFER_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [OFFER_NO] DECIMAL(38) NOT NULL  -- Offer No,
    [OFFER_DATE] DATETIME2(3) NULL  -- Offer Date,
    [OFFER_EXP_JOININGDATE] DATETIME2(3) NULL  -- Expected Joining Date,
    [OFFER_STATUS] CHAR(1) NULL  -- C - Revised ; A - Accepted ; R - Rejected,
    [OFFER_UPDATEDBY] DECIMAL(38) NULL  -- Last updated  by,
    [OFFER_UPDATEDON] DATETIME2(3) NULL  -- Last updated on,
    CONSTRAINT [PK_EMPLOYEE_OFFER] PRIMARY KEY ([OFFER_EMP_SYSID])
);



-- Table: OFFER_MAILALERT
CREATE TABLE [OFFER_MAILALERT] (
    [OFFER_PROSPECTID] BIGINT NOT NULL,
    [OFFER_ID] BIGINT NOT NULL,
    [PROSPECTNAME] VARCHAR(4000) NULL,
    [OFFER_GRADELEVEL] DECIMAL(38) NULL,
    [MIN_GRADELEVEL] DECIMAL(38) NULL,
    [UNIT_CODE] CHAR(3) NOT NULL,
    [UNIT_SHTNAME] VARCHAR(20) NOT NULL,
    [GRADENAME] VARCHAR(4000) NULL,
    [LEVELNAME] VARCHAR(4000) NULL,
    [OFFER_GRADEID] BIGINT NOT NULL,
    [EMP_QUALIFICATION] VARCHAR(4000) NULL,
    [EMP_PREVEXP_YEARS] DECIMAL(38) NULL,
    [SALARY_CTC] BIGINT NOT NULL,
    [OFFER_UNITID] INT NOT NULL,
    [ENTEREDBY] VARCHAR(4000) NULL,
    [CHRMAILID] VARCHAR(4000) NULL,
    [TOMAILID] VARCHAR(4000) NULL,
    [CCMAILID] VARCHAR(4000) NULL
);

