CREATE TABLE [LOAN_MASTER] (
    [LOAN_ID] BIGINT NOT NULL,
    [LOAN_NAME] NVARCHAR(65) NOT NULL,
    [LOAN_PURPOSE] NVARCHAR(200) NOT NULL,
    [LOAN_APPLYToUNIT] INT NOT NULL DEFAULT 0,
    [LOAN_ORGID] BIGINT NOT NULL DEFAULT 0,
    [LOAN_UNITID] BIGINT NOT NULL DEFAULT 0,
    [LOAN_TYPEID] BIGINT NOT NULL,
    [LOAN_APPLYToCONFIRMEMP] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_GRADECATAGORY] NVARCHAR(3) NOT NULL DEFAULT N'',
    [LOAN_APPLYToALLGRADE] INT NOT NULL DEFAULT 0,
    [LOAN_GRADEID] BIGINT NOT NULL DEFAULT 0,
    [LOAN_MINIMUMLIMIT] BIGINT NOT NULL DEFAULT 0,
    [LOAN_MAXIMUMLIMIT] BIGINT NOT NULL DEFAULT 0,
    [LOAN_AUTOPAYONCOMPLETION] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_ALLOWFORCECLOSE] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_ALLOWMULTIPLENOS] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_ONCONFIRMATION] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_CHECKENTITLEMENT] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_RECOVERABLE] NVARCHAR(1) NOT NULL DEFAULT N'Y',
    [LOAN_APPLICATIONNOS] INT NOT NULL DEFAULT 0,
    [LOAN_CHECKNETPAYPERCENTAGE] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_BKDINTERESTRATEREVISION] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_SUBCLASSAVAILABLE] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_ITCLASS] NVARCHAR(3) NULL,
    [LOAN_DOCUMENTREQUIRED] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_DOCUMENTUPLOADREQUIRED] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_SLFAPPALLOWED] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_EMPSPECIFICRATESALLOWED] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_HRAPPROVAL] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_EFFDATE] DATETIME2 NOT NULL,
    [LOAN_CLSDATE] DATETIME2 NULL,
    [LOAN_COMFACTOR] NVARCHAR(1) NOT NULL DEFAULT N'',
    [LOAN_INTFREQUENCY] NVARCHAR(1) NOT NULL DEFAULT N'',
    [LOAN_RECTYPE] NVARCHAR(3) NOT NULL DEFAULT N'',
    [LOAN_CREATEDBY] BIGINT NOT NULL DEFAULT 0,
    [LOAN_CREATEDON] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    [LOAN_LASTMODIFIEDBY] BIGINT NOT NULL DEFAULT 0,
    [LOAN_LASTMODIFIEDON] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    [LOAN_BULKUPLOADALLOWED] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_PRNRECEDID] BIGINT NOT NULL DEFAULT 0,
    [LOAN_INTRECEDID] BIGINT NOT NULL DEFAULT 0,
    [LOAN_PRNPAYEDID] BIGINT NOT NULL DEFAULT 0,
    [LOAN_POLICYFILENAME] NVARCHAR(250) NOT NULL DEFAULT N'',
    [LOAN_GUARANTORREQUIRED] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_CHKBASICENTITLEMENT] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_ALLOWADDLLOAN] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_ADDITONALLOANNO] BIGINT NOT NULL DEFAULT 0,
    [LOAN_CURRECOVERY] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_REPUNITAPPLICABLE] NVARCHAR(1) NOT NULL DEFAULT N'N',
    [LOAN_REPUNITID] INT NOT NULL DEFAULT 0,
    [LOAN_FLEXIFIRSTINSDATE] NVARCHAR(1) NOT NULL DEFAULT N'N',
    CONSTRAINT [PK_LOAN_MASTER] PRIMARY KEY ([LOAN_ID])
);

CREATE INDEX [IDX_LOAN_MASTER_LOAN_TYPEID] ON [LOAN_MASTER]([LOAN_TYPEID]);

ALTER TABLE [LOAN_FESTIVALMAP] ADD CONSTRAINT [FK_LOAN_FESTIVALMAP_LOAN_MASTER_LOANFESTMAP_LOANID] FOREIGN KEY ([LOANFESTMAP_LOANID]) REFERENCES [LOAN_MASTER]([LOAN_ID]);
ALTER TABLE [LOAN_INTRATEMAST] ADD CONSTRAINT [FK_LOAN_INTRATEMAST_LOAN_MASTER_LOANINT_LOANID] FOREIGN KEY ([LOANINT_LOANID]) REFERENCES [LOAN_MASTER]([LOAN_ID]);
ALTER TABLE [LOAN_SUBCLASS] ADD CONSTRAINT [FK_LOAN_SUBCLASS_LOAN_MASTER_SUBCLASS_LOANID] FOREIGN KEY ([SUBCLASS_LOANID]) REFERENCES [LOAN_MASTER]([LOAN_ID]);
ALTER TABLE [LOANLIMITRANGE_MAST] ADD CONSTRAINT [FK_LOANLIMITRANGE_MAST_LOAN_MASTER_LOANLIMITRANGE_LOANID] FOREIGN KEY ([LOANLIMITRANGE_LOANID]) REFERENCES [LOAN_MASTER]([LOAN_ID]);

PRINT 'LOAN_MASTER created without IDENTITY - DONE';
SELECT COLUMNPROPERTY(OBJECT_ID('LOAN_MASTER'), 'LOAN_ID', 'IsIdentity') AS IsIdentity;
