apiVersion: v1
kind: Namespace
metadata:
  name: eligibility-service
  labels:
    name: eligibility-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eligibility-service-config
  namespace: eligibility-service
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:5193"
  Jwt__Issuer: "EligibilityService"
  Jwt__Audience: "EligibilityServiceClients"
  RabbitMQ__Host: "rabbitmq.eligibility-service.svc.cluster.local"
  RabbitMQ__Port: "5672"
  RabbitMQ__Username: "guest"
  RabbitMQ__VirtualHost: "/"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft: "Warning"
