apiVersion: v1
kind: ConfigMap
metadata:
  name: sparsh-config
  namespace: sparsh
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  SQL_SERVER_HOST: "sqlserver-svc"
  SQL_SERVER_PORT: "1433"
  RABBITMQ_HOST: "rabbitmq-svc"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: "sparsh"
  SPARSHDB_NAME: "SPARSHDB"
  PROBLEM_DB_NAME: "ProblemManagementDb"
  TRANSACTIONAL_DB_NAME: "SparshTransactionalDb"
