apiVersion: v1
kind: Secret
metadata:
  name: sparsh-secrets
  namespace: sparsh
type: Opaque
stringData:
  SQL_SA_PASSWORD: "YourStrong!Password123"
  RABBITMQ_USER: "sparsh_user"
  RABBITMQ_PASSWORD: "sparsh_pass_2024"
  JWT_SECRET_KEY: "YourSuperSecretKeyForJWT_MinLength32Chars!"
  AZURE_BLOB_CONNECTION: ""
