apiVersion: v1
kind: ConfigMap
metadata:
  name: tour-erp-config
  namespace: tour-erp
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  JWT_ISSUER: "TourERP.Gateway"
  JWT_AUDIENCE: "TourERP.Clients"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: "tour_vhost"
  AZURITE_ENDPOINT: "http://azurite-service:10000"
---
apiVersion: v1
kind: Secret
metadata:
  name: tour-erp-secrets
  namespace: tour-erp
type: Opaque
stringData:
  SA_PASSWORD: "TourERP@Str0ngP@ss!"
  JWT_KEY: "TourERP-Shared-Super-Secret-JWT-Key-2026-Production!"
  RABBITMQ_USER: "tour_user"
  RABBITMQ_PASSWORD: "TourRMQ@2026!"
  DB_CONNECTION: "Server=sqlserver-service;Database=TOURDB;User Id=sa;Password=TourERP@Str0ngP@ss!;TrustServerCertificate=True;Encrypt=True;"
