-- ==========================================
-- SRFStipendModule
-- Database: SRFSPARSHDB
-- Module Purpose: SRF (Senior Research Fellow) Stipend Management
-- Created: March 09, 2026
-- ==========================================

USE SRFSPARSHDB;
GO

-- Drop tables if they exist (reverse order for dependencies)
IF OBJECT_ID('[SRF_STIPEND_DISBURSEMENT]', 'U') IS NOT NULL DROP TABLE [SRF_STIPEND_DISBURSEMENT];
GO
IF OBJECT_ID('[SRF_STIPEND_MASTER]', 'U') IS NOT NULL DROP TABLE [SRF_STIPEND_MASTER];
GO

-- ==========================================
-- Table: SRF_STIPEND_MASTER - SRF Stipend Rate Master
-- Description: Master table for SRF monthly stipend rates by research category and rank
-- ==========================================
CREATE TABLE [SRF_STIPEND_MASTER] (
    [STIPEND_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [RESEARCH_CATEGORY_ID] BIGINT NOT NULL,
    [SRF_RANK_ID] BIGINT NOT NULL,
    [SRF_MONTHLY_STIPEND] DECIMAL(19,2) NOT NULL,
    [ADDITIONAL_ALLOWANCE] DECIMAL(19,2),
    [EFFECTIVE_FROM] DATE NOT NULL,
    [EFFECTIVE_TO] DATE,
    [STATUS] CHAR(1) DEFAULT 'A', -- A=Active, I=Inactive
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [UPDATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    CONSTRAINT [UC_STIPEND_CATEGORY_RANK] UNIQUE ([RESEARCH_CATEGORY_ID], [SRF_RANK_ID])
);
GO

-- ==========================================
-- Table: SRF_STIPEND_DISBURSEMENT - Stipend Disbursement History
-- Description: Tracks stipend disbursement transactions
-- Relationship: References SRF_STIPEND_MASTER
-- ==========================================
CREATE TABLE [SRF_STIPEND_DISBURSEMENT] (
    [DISBURSEMENT_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [SRF_ID] BIGINT NOT NULL,
    [STIPEND_ID] BIGINT NOT NULL,
    [DISBURSEMENT_DATE] DATE NOT NULL,
    [DISBURSEMENT_AMOUNT] DECIMAL(19,2) NOT NULL,
    [DISBURSEMENT_STATUS] VARCHAR(20) DEFAULT 'D', -- D=Disbursed, P=Processed, R=Rejected
    [MONTH_YEAR] VARCHAR(7), -- Format: YYYY-MM
    [BANK_REFERENCE] VARCHAR(100),
    [REFERENCE_NO] VARCHAR(100),
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [UPDATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    CONSTRAINT [FK_SRF_STIPEND_DISBURSE_MASTER] FOREIGN KEY ([STIPEND_ID]) REFERENCES [SRF_STIPEND_MASTER]([STIPEND_ID])
);
GO

-- Create Indexes
CREATE INDEX [IX_SRF_STIPEND_MASTER_CATEGORY] ON [SRF_STIPEND_MASTER]([RESEARCH_CATEGORY_ID]);
CREATE INDEX [IX_SRF_STIPEND_MASTER_RANK] ON [SRF_STIPEND_MASTER]([SRF_RANK_ID]);
CREATE INDEX [IX_SRF_STIPEND_MASTER_STATUS] ON [SRF_STIPEND_MASTER]([STATUS]);
CREATE INDEX [IX_SRF_STIPEND_MASTER_EFFECTIVE] ON [SRF_STIPEND_MASTER]([EFFECTIVE_FROM], [EFFECTIVE_TO]);
CREATE INDEX [IX_SRF_STIPEND_DISBURSEMENT_SRF_ID] ON [SRF_STIPEND_DISBURSEMENT]([SRF_ID]);
CREATE INDEX [IX_SRF_STIPEND_DISBURSEMENT_STIPEND_ID] ON [SRF_STIPEND_DISBURSEMENT]([STIPEND_ID]);
CREATE INDEX [IX_SRF_STIPEND_DISBURSEMENT_DATE] ON [SRF_STIPEND_DISBURSEMENT]([DISBURSEMENT_DATE]);
CREATE INDEX [IX_SRF_STIPEND_DISBURSEMENT_STATUS] ON [SRF_STIPEND_DISBURSEMENT]([DISBURSEMENT_STATUS]);
CREATE INDEX [IX_SRF_STIPEND_DISBURSEMENT_MONTH] ON [SRF_STIPEND_DISBURSEMENT]([MONTH_YEAR]);
GO

PRINT 'SRFStipendModule_Schema created successfully.';
GO
