-- ==========================================
-- TimesheetModule
-- Database: SRFSPARSHDB
-- Module Purpose: Timesheet and Work Hour Management
-- Created: March 09, 2026
-- ==========================================

USE SRFSPARSHDB;
GO

-- Drop table if exists
IF OBJECT_ID('[TSE_TIMESHEET]', 'U') IS NOT NULL DROP TABLE [TSE_TIMESHEET];
GO

-- ==========================================
-- Table: TSE_TIMESHEET - Employee Timesheet Entries
-- Description: Tracks daily work hours and timesheet entries with recorded dates
-- ==========================================
CREATE TABLE [TSE_TIMESHEET] (
    [TIMESHEET_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [EMP_SYSID] BIGINT NOT NULL,
    [TIMESHEET_DATE] DATE NOT NULL,
    [WORK_DATE] DATE NOT NULL,
    [START_TIME] TIME,
    [END_TIME] TIME,
    [TOTAL_HOURS] DECIMAL(5,2),
    [PROJECT_ID] BIGINT,
    [TASK_ID] BIGINT,
    [WORK_DESCRIPTION] NVARCHAR(MAX),
    [RECORDED_DATE] DATETIME2(3) NOT NULL, -- When the entry was recorded
    [TIMESHEET_STATUS] VARCHAR(20) DEFAULT 'DRAFT', -- DRAFT, SUBMITTED, APPROVED, REJECTED
    [APPROVAL_STATUS] VARCHAR(20) DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED
    [APPROVED_BY] BIGINT,
    [APPROVED_ON] DATETIME2(3),
    [REJECTION_REASON] NVARCHAR(MAX),
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [UPDATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3)
);
GO

-- Create Indexes
CREATE INDEX [IX_TSE_TIMESHEET_EMP_SYSID] ON [TSE_TIMESHEET]([EMP_SYSID]);
CREATE INDEX [IX_TSE_TIMESHEET_WORK_DATE] ON [TSE_TIMESHEET]([WORK_DATE]);
CREATE INDEX [IX_TSE_TIMESHEET_RECORDED_DATE] ON [TSE_TIMESHEET]([RECORDED_DATE]);
CREATE INDEX [IX_TSE_TIMESHEET_STATUS] ON [TSE_TIMESHEET]([TIMESHEET_STATUS]);
CREATE INDEX [IX_TSE_TIMESHEET_APPROVAL] ON [TSE_TIMESHEET]([APPROVAL_STATUS]);
CREATE INDEX [IX_TSE_TIMESHEET_PROJECT] ON [TSE_TIMESHEET]([PROJECT_ID]);
CREATE INDEX [IX_TSE_TIMESHEET_TASK] ON [TSE_TIMESHEET]([TASK_ID]);
GO

PRINT 'TimesheetModule_Schema created successfully.';
GO
