// <auto-generated />
using System;
using MedicineManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicineManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MedicineManagementDbContext))]
    [Migration("20260329044317_FixMedicineCreditPrimaryKey")]
    partial class FixMedicineCreditPrimaryKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicineManagement.Domain.Entities.DoctorAttendant", b =>
                {
                    b.Property<long>("SystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("DM_SYSID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SystemId"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("DM_COD");

                    b.Property<string>("Flag")
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("DM_FLAG");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("DM_NAME");

                    b.HasKey("SystemId");

                    b.ToTable("DOCATTEND_MAST", (string)null);
                });

            modelBuilder.Entity("MedicineManagement.Domain.Entities.Medicine", b =>
                {
                    b.Property<string>("MedicineCode")
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("MM_MED_COD");

                    b.Property<string>("Category")
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("MM_MED_CAT");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MM_ENT_DAT");

                    b.Property<string>("EntryUser")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("MM_ENT_USR");

                    b.Property<decimal?>("EntryUserPin")
                        .HasColumnType("DECIMAL(20,0)")
                        .HasColumnName("MM_USR_NUM");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MM_MED_NAM");

                    b.Property<string>("MedicineTypeCode")
                        .IsRequired()
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("MM_MED_TYP");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MM_MOD_DAT");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("MM_MOD_USR");

                    b.Property<decimal?>("ModifiedUserPin")
                        .HasColumnType("DECIMAL(20,0)")
                        .HasColumnName("MM_MOD_NUM");

                    b.Property<decimal?>("OrderLevelMax")
                        .HasColumnType("DECIMAL(20,0)")
                        .HasColumnName("MM_ORD_MAX");

                    b.Property<decimal?>("OrderLevelMin")
                        .HasColumnType("DECIMAL(20,0)")
                        .HasColumnName("MM_ORD_MIN");

                    b.HasKey("MedicineCode");

                    b.HasIndex("MedicineCode")
                        .HasDatabaseName("IDX_MEDICINE_MAST_MM_MED_COD");

                    b.HasIndex("MedicineTypeCode");

                    b.ToTable("MEDICINE_MAST", (string)null);
                });

            modelBuilder.Entity("MedicineManagement.Domain.Entities.MedicineCredit", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("MD_COM_COD");

                    b.Property<long>("TransactionCode")
                        .HasColumnType("bigint")
                        .HasColumnName("MD_TRN_COD");

                    b.Property<string>("CancelFlag")
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("MD_CAN_FLG");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MD_ENT_DAT");

                    b.Property<string>("EntryUser")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("MD_ENT_USR");

                    b.Property<decimal>("EntryUserPin")
                        .HasColumnType("DECIMAL(20,0)")
                        .HasColumnName("MD_USR_NUM");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MD_LOT_NUM");

                    b.Property<string>("MedicineCode")
                        .IsRequired()
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("MD_MED_COD");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MD_MOD_DAT");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("MD_MOD_USR");

                    b.Property<decimal?>("ModifiedUserPin")
                        .HasColumnType("DECIMAL(20,0)")
                        .HasColumnName("MD_MOD_NUM");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("MD_MED_QNT");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("MD_REC_TYP");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MD_TRN_DAT");

                    b.Property<long?>("TransactionNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("MD_TRN_NUM");

                    b.HasKey("CompanyCode", "TransactionCode");

                    b.HasIndex("CompanyCode")
                        .HasDatabaseName("IDX_MEDICINE_CREDIT_MD_COM_COD");

                    b.HasIndex("MedicineCode");

                    b.HasIndex("TransactionDate")
                        .HasDatabaseName("IDX_MEDICINE_CREDIT_MD_TRN_DAT");

                    b.ToTable("MEDICINE_CREDIT", (string)null);
                });

            modelBuilder.Entity("MedicineManagement.Domain.Entities.MedicineDebitCreditFlag", b =>
                {
                    b.Property<int?>("DebitCredit")
                        .HasColumnType("int")
                        .HasColumnName("MED_DRCR");

                    b.Property<string>("Flag")
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("MED_FLG");

                    b.ToTable("MED_DRCRFLG", (string)null);
                });

            modelBuilder.Entity("MedicineManagement.Domain.Entities.MedicineIssue", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("MD_COM_COD");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MD_ENT_DAT");

                    b.Property<string>("EntryUser")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("MD_ENT_USR");

                    b.Property<decimal?>("EntryUserPin")
                        .HasColumnType("DECIMAL(20,0)")
                        .HasColumnName("MD_USR_NUM");

                    b.Property<long?>("IssuedQuantity")
                        .HasColumnType("bigint")
                        .HasColumnName("MD_ISS_QNT");

                    b.Property<string>("MedicineCode")
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("MD_MED_COD");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MD_MOD_DAT");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("MD_MOD_USR");

                    b.Property<decimal?>("ModifiedUserPin")
                        .HasColumnType("DECIMAL(20,0)")
                        .HasColumnName("MD_MOD_NUM");

                    b.Property<string>("TransactionDate")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MD_TRN_DAT");

                    b.Property<string>("TransactionNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MD_TRN_NUM");

                    b.Property<string>("VisitNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MD_VIS_NUM");

                    b.ToTable("MEDICINE_ISSUE", (string)null);
                });

            modelBuilder.Entity("MedicineManagement.Domain.Entities.MedicinePackaging", b =>
                {
                    b.Property<string>("PackagingCode")
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("PK_PKG_COD");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("PK_ENT_DAT");

                    b.Property<string>("EntryUser")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("PK_ENT_USR");

                    b.Property<decimal?>("EntryUserPin")
                        .HasColumnType("DECIMAL(20,0)")
                        .HasColumnName("PK_USR_NUM");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("PK_MOD_DAT");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("PK_MOD_USR");

                    b.Property<decimal?>("ModifiedUserPin")
                        .HasColumnType("DECIMAL(38)")
                        .HasColumnName("PK_MOD_NUM");

                    b.Property<string>("PackagingType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PK_PKG_TYP");

                    b.HasKey("PackagingCode");

                    b.ToTable("MEDICINE_PKG", (string)null);
                });

            modelBuilder.Entity("MedicineManagement.Domain.Entities.MedicineType", b =>
                {
                    b.Property<string>("TypeCode")
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("MT_TYP_COD");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MT_ENT_DAT");

                    b.Property<string>("EntryUser")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("MT_ENT_USR");

                    b.Property<decimal?>("EntryUserPin")
                        .HasColumnType("DECIMAL(20,0)")
                        .HasColumnName("MT_USR_NUM");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MT_MOD_DAT");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("MT_MOD_USR");

                    b.Property<decimal?>("ModifiedUserPin")
                        .HasColumnType("DECIMAL(20,0)")
                        .HasColumnName("MT_MOD_NUM");

                    b.Property<string>("TypeName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MT_TYP_NAM");

                    b.HasKey("TypeCode");

                    b.ToTable("MEDICINE_TYPMAST", (string)null);
                });

            modelBuilder.Entity("MedicineManagement.Domain.Entities.PurchaseMain", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("MD_COM_COD");

                    b.Property<long>("TransactionNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("MD_TRN_NUM");

                    b.Property<string>("CancelFlag")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("MD_CAN_FLG");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MD_ENT_DAT");

                    b.Property<string>("EntryUser")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("MD_ENT_USR");

                    b.Property<decimal>("EntryUserPin")
                        .HasColumnType("DECIMAL(20,0)")
                        .HasColumnName("MD_USR_NUM");

                    b.Property<decimal>("InvoiceAmount")
                        .HasColumnType("DECIMAL(38)")
                        .HasColumnName("MD_INV_AMT");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MD_INV_DAT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MD_INV_NUM");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MD_MOD_DAT");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("MD_MOD_USR");

                    b.Property<decimal?>("ModifiedUserPin")
                        .HasColumnType("DECIMAL(20,0)")
                        .HasColumnName("MD_MOD_NUM");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MD_VND_NAM");

                    b.HasKey("CompanyCode", "TransactionNumber");

                    b.HasIndex("CompanyCode")
                        .HasDatabaseName("IDX_PURCHASE_MAIN_MD_COM_COD");

                    b.HasIndex("InvoiceDate")
                        .HasDatabaseName("IDX_PURCHASE_MAIN_MD_INV_DAT");

                    b.ToTable("PURCHASE_MAIN", (string)null);
                });

            modelBuilder.Entity("MedicineManagement.Domain.Entities.PurchaseSub", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("MD_COM_COD");

                    b.Property<long>("TransactionNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("MD_TRN_NUM");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MD_SRL_NUM");

                    b.Property<string>("CancelFlag")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("MD_CAN_FLG");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MD_ENT_DAT");

                    b.Property<string>("EntryUser")
                        .HasColumnType("CHAR(25)")
                        .HasColumnName("MD_ENT_USR");

                    b.Property<decimal?>("EntryUserPin")
                        .HasColumnType("DECIMAL(20,0)")
                        .HasColumnName("MD_USR_NUM");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MD_EXP_DAT");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MD_LOT_NUM");

                    b.Property<DateTime?>("ManufacturingDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MD_MFG_DAT");

                    b.Property<string>("MedicineCode")
                        .IsRequired()
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("MD_MED_COD");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("MD_MOD_DAT");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("MD_MOD_USR");

                    b.Property<decimal?>("ModifiedUserPin")
                        .HasColumnType("DECIMAL(20,0)")
                        .HasColumnName("MD_MOD_NUM");

                    b.Property<long?>("PackagingNos")
                        .HasColumnType("bigint")
                        .HasColumnName("MD_PKG_NOS");

                    b.Property<long?>("PackagingQuantity")
                        .HasColumnType("bigint")
                        .HasColumnName("MD_PKG_QNT");

                    b.Property<string>("PackagingType")
                        .IsRequired()
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("MD_PKG_TYP");

                    b.Property<long?>("TotalQuantity")
                        .HasColumnType("bigint")
                        .HasColumnName("MD_TOT_QNT");

                    b.HasKey("CompanyCode", "TransactionNumber", "SerialNumber");

                    b.HasIndex("TransactionNumber")
                        .HasDatabaseName("IDX_PURCHASE_SUB_MD_TRN_NUM");

                    b.ToTable("PURCHASE_SUB", (string)null);
                });

            modelBuilder.Entity("MedicineManagement.Domain.Entities.Medicine", b =>
                {
                    b.HasOne("MedicineManagement.Domain.Entities.MedicineType", "MedicineType")
                        .WithMany()
                        .HasForeignKey("MedicineTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicineType");
                });

            modelBuilder.Entity("MedicineManagement.Domain.Entities.MedicineCredit", b =>
                {
                    b.HasOne("MedicineManagement.Domain.Entities.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("MedicineManagement.Domain.Entities.PurchaseSub", b =>
                {
                    b.HasOne("MedicineManagement.Domain.Entities.PurchaseMain", "PurchaseMain")
                        .WithMany("LineItems")
                        .HasForeignKey("CompanyCode", "TransactionNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseMain");
                });

            modelBuilder.Entity("MedicineManagement.Domain.Entities.PurchaseMain", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
