-- Create missing Transaction tables in TOURDB
-- Tables already existing: TRAVEL_BATCHMAIN, TRAVEL_BATCHSUB
USE TOURDB;
GO

-- Table: JVEMP_MAIN
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'JVEMP_MAIN')
CREATE TABLE [JVEMP_MAIN] (
    [JV_BATCHID] BIGINT NOT NULL,
    [JV_TPID] BIGINT NOT NULL,
    [JV_TYPE] CHAR(3) NOT NULL,
    [JV_DATE] DATETIME2(3) NOT NULL,
    [JV_EMPSYSID] BIGINT NOT NULL,
    [JV_STATUS] CHAR(1) NOT NULL,
    [JV_CREATEDBY] BIGINT NOT NULL,
    [JV_CREATEDON] DATETIME2(3) NOT NULL,
    [JV_TRNTYPE] CHAR(3) NOT NULL,
    [JV_ORAREFNO] VARCHAR(50) NULL,
    [JV_NETAMT] DECIMAL(19,0) NOT NULL,
    [JV_PAYUNITID] BIGINT NOT NULL,
    [JV_TRNREFNO] BIGINT NULL,
    CONSTRAINT [PK_JVEMP_MAIN] PRIMARY KEY ([JV_BATCHID])
);
GO

-- Table: JVEMP_SUB
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'JVEMP_SUB')
CREATE TABLE [JVEMP_SUB] (
    [JV_SUBID] BIGINT NOT NULL,
    [JV_BATCHID] BIGINT NOT NULL,
    [JV_BU] VARCHAR(25) NOT NULL,
    [JV_ACCODE] VARCHAR(25) NOT NULL,
    [JV_SUBACC] VARCHAR(25) NOT NULL,
    [JV_CCCODE] VARCHAR(25) NOT NULL,
    [JV_PRODUCT] VARCHAR(25) NOT NULL,
    [JV_DCFLAG] VARCHAR(25) NOT NULL,
    [JV_TRNAMT] VARCHAR(25) NOT NULL,
    [JV_IUTABU] VARCHAR(25) NOT NULL,
    [JV_LOC] VARCHAR(25) NOT NULL,
    [JV_REMARKS] VARCHAR(100) NOT NULL,
    [JV_LINEFLAG] CHAR(1) NOT NULL,
    [JV_COMBINATIONID] VARCHAR(200) NULL,
    [JV_SUBTYPE] CHAR(3) NOT NULL,
    [JV_COMBINATIONCODE] VARCHAR(207) NULL,
    CONSTRAINT [PK_JVEMP_SUB] PRIMARY KEY ([JV_SUBID])
);
GO

-- Table: JVSUP_MAIN
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'JVSUP_MAIN')
CREATE TABLE [JVSUP_MAIN] (
    [JV_ID] BIGINT NOT NULL,
    [JV_TYPE] VARCHAR(10) NOT NULL,
    [JV_DATE] DATETIME2(3) NOT NULL,
    [JV_VENDORID] BIGINT NOT NULL,
    [JV_ORAREFNO] VARCHAR(50) NULL,
    [JV_STATUS] CHAR(1) NOT NULL,
    [JV_CREATEDBY] BIGINT NOT NULL,
    [JV_CREATEDON] DATETIME2(3) NOT NULL,
    [JV_PAYUNITID] BIGINT NOT NULL,
    [JV_REFINVNO] VARCHAR(25) NOT NULL,
    [JV_NETAMT] DECIMAL(19,0) NOT NULL,
    [JV_TRNTYPE] CHAR(3) NOT NULL,
    [JV_ORAVENDORID] BIGINT NOT NULL,
    [JV_ADMINID] BIGINT NOT NULL,
    [JV_INVBATCHID] BIGINT NOT NULL,
    [JV_ORASITEID] BIGINT NOT NULL,
    [JV_CENVATAPPLICABLE] CHAR(1) NOT NULL,
    [JV_DOCKEYNO] VARCHAR(100) NOT NULL,
    CONSTRAINT [PK_JVSUP_MAIN] PRIMARY KEY ([JV_ID])
);
GO

-- Table: JVSUP_SUB
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'JVSUP_SUB')
CREATE TABLE [JVSUP_SUB] (
    [JV_SUBID] BIGINT NOT NULL,
    [JV_ID] BIGINT NOT NULL,
    [JV_BU] VARCHAR(25) NOT NULL,
    [JV_ACCODE] VARCHAR(25) NOT NULL,
    [JV_SUBACC] VARCHAR(25) NOT NULL,
    [JV_CCCODE] VARCHAR(25) NOT NULL,
    [JV_PRODUCT] VARCHAR(25) NOT NULL,
    [JV_DCFLAG] CHAR(1) NOT NULL,
    [JV_TRNAMT] DECIMAL(19,0) NOT NULL,
    [JV_LOC] VARCHAR(25) NOT NULL,
    [JV_REMARKS] VARCHAR(25) NOT NULL,
    [JV_LINEFLAG] CHAR(1) NOT NULL,
    [JV_COMBINATIONID] VARCHAR(200) NOT NULL,
    [JV_SUBTYPE] CHAR(3) NOT NULL,
    [JV_COMBINATIONCODE] VARCHAR(207) NULL,
    [JV_IUTABU] VARCHAR(25) NOT NULL,
    [JV_TPID] BIGINT NOT NULL,
    [JV_BATCHSUBID] BIGINT NOT NULL,
    [JV_GSTBU] VARCHAR(25) NULL,
    [JV_GSTACCODE] VARCHAR(255) NULL,
    [JV_GSTSUBACC] VARCHAR(255) NULL,
    [JV_GSTCCCODE] VARCHAR(255) NULL,
    [JV_GSTPRODUCT] VARCHAR(255) NULL,
    [JV_GSTLOC] VARCHAR(255) NULL,
    [JV_GSTCOMBINATIONID] VARCHAR(255) NULL,
    [JV_GSTCOMBINATIONCODE] VARCHAR(255) NULL,
    [JV_INVNO] VARCHAR(255) NULL,
    [JV_INVDATE] DATETIME2(3) NULL,
    [JV_PAYTYPE] CHAR(3) NULL,
    [JV_TPCAT] CHAR(3) NULL,
    [JV_CLASS] INT NULL,
    [JV_BASRATEAMT] DECIMAL(19,0) NULL,
    CONSTRAINT [PK_JVSUP_SUB] PRIMARY KEY ([JV_SUBID])
);
GO

-- Table: TRAVEL_BATCHCC
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TRAVEL_BATCHCC')
CREATE TABLE [TRAVEL_BATCHCC] (
    [BATCHSCOST_NUM] DECIMAL(38) NULL,
    [BATCHSCOST_BATSUBNUM] DECIMAL(38) NULL,
    [BATCHSCOST_UNITID] VARCHAR(255) NULL,
    [BATCHSCOST_SUBACC] VARCHAR(255) NULL,
    [BATCHSCOST_CSTCOD] VARCHAR(255) NULL,
    [BATCHSCOST_PRJCOD] VARCHAR(255) NULL,
    [BATCHSCOST_LOCCOD] VARCHAR(255) NULL,
    [BATCHSCOST_IUTACOD] VARCHAR(255) NULL
);
GO

-- Table: TRAVEL_BATCHCONTRACT
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TRAVEL_BATCHCONTRACT')
CREATE TABLE [TRAVEL_BATCHCONTRACT] (
    [BATCHCON_NUM] DECIMAL(38) NULL,
    [BATCHCON_MAINNO] DECIMAL(38) NULL,
    [BATCHCON_BOOKCNFNO] DECIMAL(38) NULL,
    [BATCHCON_TKTCOST] VARCHAR(255) NULL,
    [BATCHCON_TKTCOSTADJ] VARCHAR(255) NULL,
    [BATCHCON_BASTAX] VARCHAR(255) NULL,
    [BATCHCON_TOTPAYAMT] VARCHAR(255) NULL,
    [BATCHCON_APPROVEDAMT] VARCHAR(255) NULL,
    [BATCHCON_SERVICE TAX] VARCHAR(255) NULL,
    [BATCHCON_CESSTAX] VARCHAR(255) NULL,
    [BATCHCON_ADLTAX] VARCHAR(255) NULL,
    [BATCHCON_REMARKS] VARCHAR(255) NULL,
    [BATCHCON_REMARKS1] VARCHAR(255) NULL,
    [BATCHCON_REMARKS2] VARCHAR(255) NULL
);
GO

-- Table: TRAVEL_BATCHSUBBRK
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TRAVEL_BATCHSUBBRK')
CREATE TABLE [TRAVEL_BATCHSUBBRK] (
    [BATCHBRK_ID] VARCHAR(255) NULL,
    [BATCHBRK_SUBID] VARCHAR(255) NULL,
    [BATCHBRK_VENDORID] VARCHAR(255) NULL,
    [BATCHBRK_VENDORSITEID] VARCHAR(255) NULL,
    [BATCHBRK_JVID] VARCHAR(255) NULL
);
GO

-- Table: JVEMPPAY_DET
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'JVEMPPAY_DET')
CREATE TABLE [JVEMPPAY_DET] (
    [PAY_ID] BIGINT NOT NULL,
    [PAY_TPID] BIGINT NOT NULL,
    [PAY_TRNTYPE] CHAR(3) NOT NULL,
    [PAY_EMPSYSID] BIGINT NOT NULL,
    [PAY_UNITID] BIGINT NOT NULL,
    [PAY_MODE] CHAR(3) NOT NULL,
    [PAY_TYPE] CHAR(3) NOT NULL,
    [PAY_DATE] DATETIME2(3) NULL,
    [PAY_AMOUNT] DECIMAL(19,0) NOT NULL,
    [PAY_REFID] BIGINT NOT NULL,
    [PAY_BATCHID] BIGINT NOT NULL,
    [PAY_CREATEDBY] BIGINT NOT NULL,
    [PAY_CREATEDON] DATETIME2(3) NOT NULL,
    [PAY_JVID] BIGINT NOT NULL,
    CONSTRAINT [PK_JVEMPPAY_DET] PRIMARY KEY ([PAY_ID])
);
GO

-- Table: TRAVEL_EMPPAYDET
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TRAVEL_EMPPAYDET')
CREATE TABLE [TRAVEL_EMPPAYDET] (
    [EMPPAY_ID] VARCHAR(255) NULL,
    [EMPPAY_EMPSYSID] VARCHAR(255) NULL,
    [EMPPAY_TYPE] VARCHAR(255) NULL,
    [EMPPAY_MODE] VARCHAR(255) NULL,
    [EMPPAY_TRNDATE] DATETIME2(3) NULL,
    [EMPPAY_AMOUNT] VARCHAR(255) NULL,
    [EMPPAY_SOURCE] VARCHAR(255) NULL,
    [EMPPAY_TRNTYPE] VARCHAR(255) NULL,
    [EMPPAY_DATE] DATETIME2(3) NULL,
    [EMPPAY_REFID] VARCHAR(255) NULL,
    [EMPPAY_ACCTYPE] VARCHAR(255) NULL,
    [EMPPAY_ACCREFNO] VARCHAR(255) NULL,
    [EMPPAY_TPID] VARCHAR(255) NULL
);
GO

-- Table: TICKET_AIRLINEINOVICE
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TICKET_AIRLINEINOVICE')
CREATE TABLE [TICKET_AIRLINEINOVICE] (
    [AIRTICKET_ID] VARCHAR(255) NULL,
    [AIRTICKET_BOOKCNFID] VARCHAR(255) NULL,
    [AIRTICKET_TICKETNUMBER] VARCHAR(255) NULL,
    [AIRTICKET_TICKETPNRNUM] VARCHAR(255) NULL,
    [AIRTICKET_AIRLINEVNDID] VARCHAR(255) NULL,
    [AIRTICKET_ENTRYDATE] DATETIME2(3) NULL,
    [AIRTICKET_ENTREDBY] VARCHAR(255) NULL,
    [AIRTICKET_INVOICENUM] VARCHAR(255) NULL,
    [AIRTICKET_INVOICEDATE] DATETIME2(3) NULL,
    [AIRTICKET_INVOICECOST] VARCHAR(255) NULL,
    [AIRTICKET_CGST] VARCHAR(255) NULL,
    [AIRTICKET_SGST] VARCHAR(255) NULL,
    [AIRTICKET_IGST] VARCHAR(255) NULL,
    [AIRTICKET_DEBITCREDIT] VARCHAR(255) NULL,
    [AIRTICKET_REFADDCOST] VARCHAR(255) NULL,
    [AIRTICKET_REFCHRTAX] VARCHAR(255) NULL,
    [AIRTICKET_VNDGSTNUM] VARCHAR(255) NULL,
    [AIRTICKET_VNDATTACHMENT] VARCHAR(255) NULL
);
GO

-- Table: TEMPJVEMP_MAIN
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TEMPJVEMP_MAIN')
CREATE TABLE [TEMPJVEMP_MAIN] (
    [JV_BATCHID] BIGINT NOT NULL,
    [JV_TPID] BIGINT NOT NULL,
    [JV_TYPE] CHAR(3) NOT NULL,
    [JV_DATE] DATETIME2(3) NOT NULL,
    [JV_EMPSYSID] BIGINT NOT NULL,
    [JV_CREATEDBY] BIGINT NOT NULL,
    [JV_CREATEDON] DATETIME2(3) NOT NULL,
    [JV_TRNTYPE] CHAR(3) NOT NULL,
    [JV_ORAREFNO] VARCHAR(50) NULL,
    [JV_NETAMT] DECIMAL(19,0) NOT NULL,
    [JV_PAYUNITID] BIGINT NOT NULL,
    [JV_TRNREFNO] BIGINT NULL,
    CONSTRAINT [PK_TEMPJVEMP_MAIN] PRIMARY KEY ([JV_BATCHID])
);
GO

-- Table: TEMPJVEMP_SUB
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TEMPJVEMP_SUB')
CREATE TABLE [TEMPJVEMP_SUB] (
    [JV_BATCHID] BIGINT NOT NULL,
    [JV_BU] VARCHAR(25) NOT NULL,
    [JV_ACCODE] VARCHAR(25) NOT NULL,
    [JV_SUBACC] VARCHAR(25) NOT NULL,
    [JV_CCCODE] VARCHAR(25) NOT NULL,
    [JV_PRODUCT] VARCHAR(25) NOT NULL,
    [JV_DCFLAG] VARCHAR(25) NOT NULL,
    [JV_TRNAMT] VARCHAR(25) NOT NULL,
    [JV_IUTABU] VARCHAR(25) NOT NULL,
    [JV_LOC] VARCHAR(25) NOT NULL,
    [JV_REMARKS] VARCHAR(100) NOT NULL,
    [JV_LINEFLAG] CHAR(1) NOT NULL,
    [JV_COMBINATIONID] VARCHAR(200) NULL,
    [JV_SUBTYPE] CHAR(3) NOT NULL,
    [JV_COMBINATIONCODE] VARCHAR(207) NULL,
    [JV_BATCHSUBID] BIGINT NULL
);
GO

-- Table: TEMPJVSUP_MAIN
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TEMPJVSUP_MAIN')
CREATE TABLE [TEMPJVSUP_MAIN] (
    [JV_BATCHID] BIGINT NOT NULL,
    [JV_TYPE] CHAR(3) NOT NULL,
    [JV_DATE] DATETIME2(3) NOT NULL,
    [JV_VENDORID] BIGINT NOT NULL,
    [JV_CREATEDBY] BIGINT NOT NULL,
    [JV_CREATEDON] DATETIME2(3) NOT NULL,
    [JV_PAYUNITID] BIGINT NOT NULL,
    [JV_REFINVNO] VARCHAR(25) NOT NULL,
    [JV_NETAMT] DECIMAL(19,0) NOT NULL,
    [JV_TRNTYPE] CHAR(3) NOT NULL,
    [JV_ORAVENDORID] BIGINT NOT NULL,
    [JV_ADMINID] BIGINT NOT NULL,
    [JV_INVBATCHID] BIGINT NOT NULL,
    [JV_ORASITEID] BIGINT NOT NULL,
    CONSTRAINT [PK_TEMPJVSUP_MAIN] PRIMARY KEY ([JV_BATCHID])
);
GO

-- Table: TEMPJVSUP_SUB
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TEMPJVSUP_SUB')
CREATE TABLE [TEMPJVSUP_SUB] (
    [JV_BATCHID] BIGINT NOT NULL,
    [JV_BU] VARCHAR(25) NOT NULL,
    [JV_ACCODE] VARCHAR(25) NOT NULL,
    [JV_SUBACC] VARCHAR(25) NOT NULL,
    [JV_CCCODE] VARCHAR(25) NOT NULL,
    [JV_PRODUCT] VARCHAR(25) NOT NULL,
    [JV_DCFLAG] CHAR(1) NOT NULL,
    [JV_TRNAMT] DECIMAL(19,0) NOT NULL,
    [JV_LOC] VARCHAR(25) NOT NULL,
    [JV_REMARKS] VARCHAR(25) NOT NULL,
    [JV_LINEFLAG] CHAR(1) NOT NULL,
    [JV_COMBINATIONID] VARCHAR(200) NOT NULL,
    [JV_SUBTYPE] CHAR(3) NOT NULL,
    [JV_COMBINATIONCODE] VARCHAR(207) NULL,
    [JV_IUTABU] VARCHAR(25) NOT NULL,
    [JV_TPID] BIGINT NOT NULL,
    [JV_BATCHSUBID] BIGINT NOT NULL,
    [JV_GSTBU] VARCHAR(25) NOT NULL,
    [JV_GSTACCODE] VARCHAR(25) NOT NULL,
    [JV_GSTSUBACC] VARCHAR(25) NOT NULL,
    [JV_GSTCCCODE] VARCHAR(25) NOT NULL,
    [JV_GSTPRODUCT] VARCHAR(25) NOT NULL,
    [JV_GSTDCFLAG] CHAR(1) NOT NULL,
    [JV_GSTLOC] VARCHAR(25) NOT NULL,
    [JV_GSTINVNO] VARCHAR(25) NOT NULL,
    [JV_GSTINVDATE] VARCHAR(25) NOT NULL
);
GO

PRINT 'All transaction tables created successfully';
GO
