-- =========================================================================
-- ACCOUNTING MODULE - Database Tables
-- Database: PFDB
-- Module: Account and Transaction Management
-- Description: Manages accounting transactions and ledger
-- Created: March 9, 2026
-- =========================================================================

USE PFDB;
GO

-- Account Details
CREATE TABLE [ACC_DET] (
    [AC_SYS_ID] BIGINT NOT NULL PRIMARY KEY,
    [AC_TRUST_CODE] CHAR(3) NOT NULL,
    [AC_TRAN_CODE] CHAR(3) NOT NULL,
    [AC_TRAN_NO] BIGINT NOT NULL,
    [AC_DOC_NO] BIGINT NOT NULL,
    [AC_FIN_YER] BIGINT NOT NULL,
    [AC_DOC_DAT] DATETIME2(3) NOT NULL,
    [AC_MAIN_CODE] CHAR(6) NOT NULL,
    [AC_SUB_CODE] CHAR(6) NOT NULL,
    [AC_DC_TYPE] CHAR(1) NOT NULL,
    [AC_TRAN_AMT] DECIMAL(19,0) NOT NULL,
    [AC_REF_TRANCODE] CHAR(3) NOT NULL,
    [AC_REF_TRANNO] BIGINT NOT NULL,
    [AC_REMARKS] VARCHAR(2000) NULL
);
GO

-- Account Lookup
CREATE TABLE [ACC_LOOKUP] (
    [CON_TYP] CHAR(1) NOT NULL PRIMARY KEY,
    [ED_COD] CHAR(3) NOT NULL,
    [ACC_COD] BIGINT NULL,
    [TRN_TYP] CHAR(1) NULL
);
GO

-- Main Account Master
CREATE TABLE [MAINACCOUNT_MASTER] (
    [MAIN_ACCOUNT_CODE] VARCHAR(10) NOT NULL PRIMARY KEY,
    [MAIN_ACCOUNT_NAME] VARCHAR(200) NULL,
    [MAIN_ACCOUNT_SHRT_NAME] VARCHAR(30) NULL,
    [MAIN_CLOSURE_FLAG] CHAR(1) NULL
);
GO

-- Transaction Details
CREATE TABLE [TRAN_DET] (
    [TD_TRUST_CODE] CHAR(3) NOT NULL,
    [TRANSACTION_ID] INT NOT NULL,
    [TD_TRANSACTION_CODE] CHAR(3) NOT NULL,
    [TD_TRANSACTION_TYPE] CHAR(1) NULL,
    [TD_TRANSACTION_DATE] DATETIME2(3) NOT NULL,
    [TD_AMOUNT] DECIMAL(19,0) NOT NULL,
    [TD_REMARKS] VARCHAR(255) NULL,
    [TD_MEMBER_NO] INT NULL,
    [TD_REFERENCE_TYPE] VARCHAR(25) NULL,
    [TD_CONTRIBUTION_REFERENCE_NO] VARCHAR(255) NULL,
    [TD_TYPE_CODE] CHAR(1) NOT NULL,
    [TD_LAST_MODIFIED_ON] DATETIME2(3) NOT NULL,
    [TD_LAST_MODIFIED_EMP_SYSID] VARCHAR(50) NOT NULL,
    [TD_FINYEAR] BIGINT NOT NULL,
    [TD_JV_VOUCHER_TYPE] CHAR(3) NOT NULL,
    [TD_JV_NO] VARCHAR(255) NOT NULL,
    [TD_CANCEL_STATUS] BIGINT NULL,
    [TD_CANCEL_DATE] DATETIME2(3) NULL,
    [TD_TRN_SUB_TYPE] CHAR(3) NULL,
    CONSTRAINT [PK_TRAN_DET] PRIMARY KEY ([TD_TRUST_CODE], [TRANSACTION_ID])
);
GO

-- Transaction Master
CREATE TABLE [TRANSACTION_MASTER] (
    [TRANSACTION_TRUST_CODE] CHAR(3) NOT NULL,
    [TRANSACTION_CODE] CHAR(3) NOT NULL,
    [TRANSACTION_NAME] VARCHAR(25) NOT NULL,
    [TRANSACTION_TYPE] CHAR(3) NOT NULL,
    [TRANSACTION_VALUE] VARCHAR(255) NOT NULL,
    CONSTRAINT [PK_TRANSACTION_MASTER] PRIMARY KEY ([TRANSACTION_TRUST_CODE], [TRANSACTION_CODE])
);
GO

-- PF Sub Accounts
CREATE TABLE [PF_SUB_ACCOUNT] (
    [SUB_ACC_COD] BIGINT NOT NULL PRIMARY KEY,
    [SUB_ACC_NAM] VARCHAR(255) NOT NULL
);
GO

-- GL Account Posting
CREATE TABLE [GL_POSTING] (
    [POSTING_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [ACCOUNT_CODE] VARCHAR(10) NOT NULL,
    [POSTING_DATE] DATETIME2(3) NOT NULL,
    [DEBIT_AMOUNT] DECIMAL(19,0) DEFAULT 0,
    [CREDIT_AMOUNT] DECIMAL(19,0) DEFAULT 0,
    [REFERENCE_ID] BIGINT NOT NULL,
    [POSTING_REMARKS] VARCHAR(200) NULL,
    CONSTRAINT [FK_GL_POSTING_ACCOUNT] FOREIGN KEY ([ACCOUNT_CODE]) REFERENCES [MAINACCOUNT_MASTER]([MAIN_ACCOUNT_CODE])
);
GO

CREATE NONCLUSTERED INDEX [IDX_ACC_DET_TRUST_DATE] ON [ACC_DET] ([AC_TRUST_CODE], [AC_DOC_DAT]);
CREATE NONCLUSTERED INDEX [IDX_TRAN_DET_TYPE] ON [TRAN_DET] ([TD_TRANSACTION_TYPE], [TD_TRANSACTION_DATE]);
CREATE NONCLUSTERED INDEX [IDX_GL_POSTING_ACCOUNT] ON [GL_POSTING] ([ACCOUNT_CODE], [POSTING_DATE]);

PRINT 'Accounting Module Tables created successfully!';
GO
