-- Module: Learning
USE DDDB;
GO

-- Table: DD_CAT_DEV_DETAIL
CREATE TABLE [DD_CAT_DEV_DETAIL] (
    [CT_REQ_NUM] DECIMAL(38) NOT NULL  -- Request Number,
    [CT_QTN_NUM] DECIMAL(38) NOT NULL  -- Question Number,
    [CT_ANS_SRL] DECIMAL(38) NOT NULL  -- Answer serial number,
    [CT_APP_ID] VARCHAR(30) NOT NULL  -- User id,
    [CT_APP_NUM] DECIMAL(38) NOT NULL  -- User Number,
    [CT_ENT_DAT] DATETIME2(3) NULL  -- date,
    [CT_DESC] VARCHAR(400) NULL  -- Areas for Development,
    [CT_NEED] VARCHAR(400) NULL  -- Why do you need it?
);



-- Table: LET_FEEDBACK
CREATE TABLE [LET_FEEDBACK] (
    [LET_SRL] DECIMAL(38) NOT NULL  -- LET ID (Sequence),
    [LET_DDREQNO] DECIMAL(38) NOT NULL  -- DD Request No,
    [LET_SPECIFIC_NEED] VARCHAR(2000) NULL  -- Identified LET Need for Previous Year,
    [LET_TRAINING] VARCHAR(500) NULL  -- Training Program / Workshop Attended,
    [LET_FEEDBACK_STATUS] CHAR(1) NULL  -- Did the Program Satisfy Identified Need (Y/N/P),
    [LET_APPRAISEE_COMMENTS] VARCHAR(2000) NULL  -- Appraisee Comments,
    [LET_APPRAISER_COMMENTS] VARCHAR(2000) NULL  -- Appraiser Comments,
    [LET_REVIEWER_COMMENTS] VARCHAR(2000) NULL  -- Reviewer Comments,
    [LET_MODIFIEDBY] DECIMAL(38) NOT NULL  -- Modified By,
    [LET_MODIFIEDON] DATETIME2(3) NOT NULL  -- Modified On,
    [LET_APPR_NEEDSTATUS] CHAR(1) NULL,
    [LET_APPR_POSTTRAINING] VARCHAR(2000) NULL,
    CONSTRAINT [PK_LET_FEEDBACK] PRIMARY KEY ([LET_SRL])
);



-- Table: LET_FEEDBACK_LOG
CREATE TABLE [LET_FEEDBACK_LOG] (
    [LET_SRL] DECIMAL(38) NOT NULL,
    [LET_DDREQNO] DECIMAL(38) NOT NULL,
    [LET_SPECIFIC_NEED] VARCHAR(2000) NULL,
    [LET_TRAINING] VARCHAR(500) NULL,
    [LET_FEEDBACK_STATUS] CHAR(1) NULL,
    [LET_APPRAISEE_COMMENTS] VARCHAR(2000) NULL,
    [LET_APPRAISER_COMMENTS] VARCHAR(2000) NULL,
    [LET_REVIEWER_COMMENTS] VARCHAR(2000) NULL,
    [LET_MODIFIEDBY] DECIMAL(38) NOT NULL,
    [LET_MODIFIEDON] DATETIME2(3) NOT NULL,
    [LET_APPR_NEEDSTATUS] CHAR(1) NULL,
    [LET_APPR_POSTTRAINING] VARCHAR(2000) NULL
);



-- Table: LET_MAIN09
CREATE TABLE [LET_MAIN09] (
    [LET_ID] DECIMAL(38) NOT NULL  -- Let Id,
    [LET_DD_REQNO] DECIMAL(38) NOT NULL  -- Request Number,
    [LET_DEV_SOURCE] DECIMAL(38) NULL  -- Development Souce,
    [LET_SPECIFIC_NEED] VARCHAR(2000) NULL  -- Specific Need,
    [LET_INDICATOR] VARCHAR(2000) NULL  -- Indicator,
    [LET_MODIFIEDBY] DECIMAL(38) NOT NULL  -- Modified By,
    [LET_MODIFIEDON] DATETIME2(3) NOT NULL  -- Modified On,
    [LET_DEV_AREA] VARCHAR(2000) NULL  -- Area of Development,
    [LET_BHRSTATUS] CHAR(1) NULL  -- BHR Status-'Y'-Appraiser Can Modify,'N'-Appraiser Cannot Modify,
    [LET_EXPECTEDPOST_TRAINING] VARCHAR(2000) NULL  -- Post Training details,
    [LET_REVIEWER_COMMENTS] VARCHAR(2000) NULL  -- Reviewer Comments,
    [LET_APP_OPINION] VARCHAR(2000) NULL,
    [LET_APPR_COMMENTS] VARCHAR(2000) NULL,
    CONSTRAINT [PK_LET_MAIN09] PRIMARY KEY ([LET_ID])
);



-- Table: LET_MAIN09LOG
CREATE TABLE [LET_MAIN09LOG] (
    [LET_ID] DECIMAL(38) NOT NULL,
    [LET_DD_REQNO] DECIMAL(38) NOT NULL,
    [LET_DEV_SOURCE] DECIMAL(38) NULL,
    [LET_SPECIFIC_NEED] VARCHAR(2000) NULL,
    [LET_INDICATOR] VARCHAR(2000) NULL,
    [LET_MODIFIEDBY] DECIMAL(38) NOT NULL,
    [LET_MODIFIEDON] DATETIME2(3) NOT NULL,
    [LET_DEV_AREA] VARCHAR(2000) NULL,
    [LET_BHRSTATUS] CHAR(1) NULL,
    [LET_EXPECTEDPOST_TRAINING] VARCHAR(2000) NULL,
    [LET_REVIEWER_COMMENTS] VARCHAR(2000) NULL,
    [LET_APP_OPINION] VARCHAR(2000) NULL,
    [LET_APPR_COMMENTS] VARCHAR(2000) NULL
);



-- Table: LET_SUB09
CREATE TABLE [LET_SUB09] (
    [LET_MODID] DECIMAL(38) NOT NULL  -- LET Sub ID,
    [LET_DD_REQNO] DECIMAL(38) NOT NULL  -- DD Reqnum,
    [LET_ID] DECIMAL(38) NOT NULL  -- LET Main  Id,
    [LET_DEVELOPMEN_MODE] DECIMAL(38) NOT NULL  -- Development Mode,
    [LET_TRAINING_ID] DECIMAL(38) NOT NULL  -- Training Id,
    [LET_TRAINING_DET] VARCHAR(1000) NULL  -- Training Detail,
    [LET_REMARKS] VARCHAR(200) NULL  -- Remarks,
    [LET_DEVELOPMENTID] DECIMAL(38) NOT NULL  -- LET_Development id,
    [LET_FINALREVIEW] VARCHAR(50) NULL  -- Final review,
    CONSTRAINT [PK_LET_SUB09] PRIMARY KEY ([LET_MODID])
);



-- Table: LET_SUB09LOG
CREATE TABLE [LET_SUB09LOG] (
    [LET_MODID] DECIMAL(38) NOT NULL,
    [LET_DD_REQNO] DECIMAL(38) NOT NULL,
    [LET_ID] DECIMAL(38) NOT NULL,
    [LET_DEVELOPMEN_MODE] DECIMAL(38) NOT NULL,
    [LET_TRAINING_ID] DECIMAL(38) NOT NULL,
    [LET_TRAINING_DET] VARCHAR(1000) NULL,
    [LET_REMARKS] VARCHAR(200) NULL,
    [LET_DEVELOPMENTID] DECIMAL(38) NOT NULL,
    [LET_FINALREVIEW] VARCHAR(50) NULL,
    [MOD_BY] DECIMAL(38) NULL  -- Modified by,
    [MOD_ON] DATETIME2(3) NULL  -- Modified On
);

