apiVersion: v1
kind: Secret
metadata:
  name: ssc-secrets
  namespace: ssc-services
type: Opaque
stringData:
  SA_PASSWORD: "REPLACE_WITH_STRONG_PASSWORD"
  RABBITMQ_USER: "ssc_user"
  RABBITMQ_PASS: "REPLACE_WITH_STRONG_PASSWORD"
  JWT_SECRET: "REPLACE_WITH_PRODUCTION_SECRET_KEY_MIN_32_CHARS"
  SSCDB_CONNECTION: "Server=sqlserver-service;Database=SSCDB;User Id=sa;Password=REPLACE_WITH_STRONG_PASSWORD;TrustServerCertificate=True;Encrypt=True"
  SSCDB_CATVENDOR_CONNECTION: "Server=sqlserver-service;Database=SSCDB_CategoryVendor;User Id=sa;Password=REPLACE_WITH_STRONG_PASSWORD;TrustServerCertificate=True;Encrypt=True"
  SSCDB_INVOICE_CONNECTION: "Server=sqlserver-service;Database=SSCDB_InvoiceProcessing;User Id=sa;Password=REPLACE_WITH_STRONG_PASSWORD;TrustServerCertificate=True;Encrypt=True"
  RABBITMQ_CONNECTION: "amqp://ssc_user:REPLACE_WITH_STRONG_PASSWORD@rabbitmq-service:5672/"
  AZURE_BLOB_CONNECTION: "REPLACE_WITH_AZURE_BLOB_CONNECTION_STRING"
