-- ==========================================
-- Database: AIMSDB
-- Module: AIMS Transaction Services
-- Idempotent Deployment Script
-- ==========================================

USE master;
GO

-- ==========================================
-- PHASE 1: Database Creation (Idempotent)
-- ==========================================
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'AIMSDB')
BEGIN
    CREATE DATABASE [AIMSDB];
    PRINT '+ AIMSDB created';
END
ELSE
    PRINT '= AIMSDB already exists';
GO

ALTER DATABASE [AIMSDB] SET READ_COMMITTED_SNAPSHOT ON;
GO

PRINT '=== PHASE 1 COMPLETE: Database Ready ===';
GO

-- ==========================================
-- PHASE 2: Table Definitions (Idempotent)
-- ==========================================
USE AIMSDB;
GO

-- Table: SWIPE_RAWPUNCH - Raw swipe/punch records
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SWIPE_RAWPUNCH')
BEGIN
    CREATE TABLE [SWIPE_RAWPUNCH] (
        [SRP_SYSID]        BIGINT        NOT NULL,
        [SRP_EMPSYSID]     BIGINT        NOT NULL,
        [SRP_PUNCHTIME]    DATETIME2(3)  NOT NULL,
        [SRP_PULLSTATUS]   NVARCHAR(1)   NOT NULL,
        [SRP_UPDATEDBY]    BIGINT        NOT NULL,
        [SRP_UPDATEDON]    DATETIME2(3)  NOT NULL,
        [SRP_GATENO]       INT           NOT NULL,
        [SRP_INOUTSTATUS]  NVARCHAR(1)   NOT NULL,
        [SRP_MACHINENO]    INT           NULL,
        [SRP_REFERENCENO]  NVARCHAR(50)  NULL,
        CONSTRAINT [PK_SWIPE_RAWPUNCH] PRIMARY KEY ([SRP_SYSID])
    );
    PRINT '+ SWIPE_RAWPUNCH table created';
END
ELSE
    PRINT '= SWIPE_RAWPUNCH already exists';
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_SWIPE_RAWPUNCH_EMPSYSID' AND object_id = OBJECT_ID('SWIPE_RAWPUNCH'))
BEGIN
    CREATE INDEX [IX_SWIPE_RAWPUNCH_EMPSYSID] ON [SWIPE_RAWPUNCH] ([SRP_EMPSYSID]);
    PRINT '+ IX_SWIPE_RAWPUNCH_EMPSYSID created';
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_SWIPE_RAWPUNCH_PUNCHTIME' AND object_id = OBJECT_ID('SWIPE_RAWPUNCH'))
BEGIN
    CREATE INDEX [IX_SWIPE_RAWPUNCH_PUNCHTIME] ON [SWIPE_RAWPUNCH] ([SRP_PUNCHTIME]);
    PRINT '+ IX_SWIPE_RAWPUNCH_PUNCHTIME created';
END
GO

-- Table: ATTENDANCE_BATCH - Attendance batch processing records
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ATTENDANCE_BATCH')
BEGIN
    CREATE TABLE [ATTENDANCE_BATCH] (
        [ATB_SYSID]       BIGINT        NOT NULL,
        [ATB_MONTHSTART]  DATETIME2(3)  NOT NULL,
        [ATB_MONTHEND]    DATETIME2(3)  NOT NULL,
        [ATB_STATUS]      NVARCHAR(1)   NOT NULL,
        [ATB_CREATEDBY]   BIGINT        NOT NULL,
        [ATB_CREATEDON]   DATETIME2(3)  NOT NULL,
        CONSTRAINT [PK_ATTENDANCE_BATCH] PRIMARY KEY ([ATB_SYSID])
    );
    PRINT '+ ATTENDANCE_BATCH table created';
END
ELSE
    PRINT '= ATTENDANCE_BATCH already exists';
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_ATTENDANCE_BATCH_STATUS' AND object_id = OBJECT_ID('ATTENDANCE_BATCH'))
BEGIN
    CREATE INDEX [IX_ATTENDANCE_BATCH_STATUS] ON [ATTENDANCE_BATCH] ([ATB_STATUS]);
    PRINT '+ IX_ATTENDANCE_BATCH_STATUS created';
END
GO

-- Table: ATTENDANCE_LOPMAIN - Monthly LOP main records
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ATTENDANCE_LOPMAIN')
BEGIN
    CREATE TABLE [ATTENDANCE_LOPMAIN] (
        [ALM_SYSID]         BIGINT        NOT NULL,
        [ALM_EMPSYSID]      BIGINT        NOT NULL,
        [ALM_MONTHSTART]    DATETIME2(3)  NOT NULL,
        [ALM_MONTHEND]      DATETIME2(3)  NOT NULL,
        [ALM_CALENDARDAYS]  INT           NOT NULL,
        [ALM_CREATEDBY]     BIGINT        NOT NULL,
        [ALM_CREATEDON]     DATETIME2(3)  NOT NULL,
        CONSTRAINT [PK_ATTENDANCE_LOPMAIN] PRIMARY KEY ([ALM_SYSID])
    );
    PRINT '+ ATTENDANCE_LOPMAIN table created';
END
ELSE
    PRINT '= ATTENDANCE_LOPMAIN already exists';
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_ATTENDANCE_LOPMAIN_EMPSYSID' AND object_id = OBJECT_ID('ATTENDANCE_LOPMAIN'))
BEGIN
    CREATE INDEX [IX_ATTENDANCE_LOPMAIN_EMPSYSID] ON [ATTENDANCE_LOPMAIN] ([ALM_EMPSYSID]);
    PRINT '+ IX_ATTENDANCE_LOPMAIN_EMPSYSID created';
END
GO

-- Table: ATTENDANCE_LOPDET - LOP detail records
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ATTENDANCE_LOPDET')
BEGIN
    CREATE TABLE [ATTENDANCE_LOPDET] (
        [ALD_SYSID]       BIGINT         NOT NULL,
        [ALD_LOPMAINID]   BIGINT         NOT NULL,
        [ALD_LOPDATE]     DATETIME2(3)   NOT NULL,
        [ALD_LOPHOURS]    DECIMAL(5,2)   NOT NULL,
        [ALD_LOPREASON]   NVARCHAR(255)  NULL,
        CONSTRAINT [PK_ATTENDANCE_LOPDET] PRIMARY KEY ([ALD_SYSID])
    );
    PRINT '+ ATTENDANCE_LOPDET table created';
END
ELSE
    PRINT '= ATTENDANCE_LOPDET already exists';
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_ATTENDANCE_LOPDET_LOPMAINID' AND object_id = OBJECT_ID('ATTENDANCE_LOPDET'))
BEGIN
    CREATE INDEX [IX_ATTENDANCE_LOPDET_LOPMAINID] ON [ATTENDANCE_LOPDET] ([ALD_LOPMAINID]);
    PRINT '+ IX_ATTENDANCE_LOPDET_LOPMAINID created';
END
GO

-- Table: ATTENDANCE_OVERTIME - Overtime records
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ATTENDANCE_OVERTIME')
BEGIN
    CREATE TABLE [ATTENDANCE_OVERTIME] (
        [ATO_SYSID]       BIGINT        NOT NULL,
        [ATO_EMPSYSID]    BIGINT        NOT NULL,
        [ATO_OTDATE]      DATETIME2(3)  NOT NULL,
        [ATO_OTHOURS]     DECIMAL(5,2)  NOT NULL,
        [ATO_STATUS]      NVARCHAR(1)   NOT NULL,
        [ATO_CREATEDBY]   BIGINT        NOT NULL,
        [ATO_CREATEDON]   DATETIME2(3)  NOT NULL,
        CONSTRAINT [PK_ATTENDANCE_OVERTIME] PRIMARY KEY ([ATO_SYSID])
    );
    PRINT '+ ATTENDANCE_OVERTIME table created';
END
ELSE
    PRINT '= ATTENDANCE_OVERTIME already exists';
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_ATTENDANCE_OVERTIME_EMPSYSID' AND object_id = OBJECT_ID('ATTENDANCE_OVERTIME'))
BEGIN
    CREATE INDEX [IX_ATTENDANCE_OVERTIME_EMPSYSID] ON [ATTENDANCE_OVERTIME] ([ATO_EMPSYSID]);
    PRINT '+ IX_ATTENDANCE_OVERTIME_EMPSYSID created';
END
GO

-- Table: ATTENDANCE_SUMMARY - Monthly attendance summary
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ATTENDANCE_SUMMARY')
BEGIN
    CREATE TABLE [ATTENDANCE_SUMMARY] (
        [ATS_SYSID]        BIGINT        NOT NULL,
        [ATS_EMPSYSID]     BIGINT        NOT NULL,
        [ATS_MONTHSTART]   DATETIME2(3)  NOT NULL,
        [ATS_MONTHEND]     DATETIME2(3)  NOT NULL,
        [ATS_WORKINGDAYS]  INT           NOT NULL,
        [ATS_PRESENTDAYS]  INT           NOT NULL,
        [ATS_ABSENTDAYS]   INT           NOT NULL,
        [ATS_OTHOURS]      DECIMAL(7,2)  NOT NULL,
        [ATS_LOPDAYS]      DECIMAL(5,2)  NOT NULL,
        [ATS_CREATEDBY]    BIGINT        NOT NULL,
        [ATS_CREATEDON]    DATETIME2(3)  NOT NULL,
        CONSTRAINT [PK_ATTENDANCE_SUMMARY] PRIMARY KEY ([ATS_SYSID])
    );
    PRINT '+ ATTENDANCE_SUMMARY table created';
END
ELSE
    PRINT '= ATTENDANCE_SUMMARY already exists';
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_ATTENDANCE_SUMMARY_EMPSYSID' AND object_id = OBJECT_ID('ATTENDANCE_SUMMARY'))
BEGIN
    CREATE INDEX [IX_ATTENDANCE_SUMMARY_EMPSYSID] ON [ATTENDANCE_SUMMARY] ([ATS_EMPSYSID]);
    PRINT '+ IX_ATTENDANCE_SUMMARY_EMPSYSID created';
END
GO

-- Table: LEAVE_DETAILS - Leave application records
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LEAVE_DETAILS')
BEGIN
    CREATE TABLE [LEAVE_DETAILS] (
        [LVD_SYSID]       BIGINT         NOT NULL,
        [LVD_EMPSYSID]    BIGINT         NOT NULL,
        [LVD_LEAVEID]     BIGINT         NOT NULL,
        [LVD_FROMDATE]    DATETIME2(3)   NOT NULL,
        [LVD_TODATE]      DATETIME2(3)   NOT NULL,
        [LVD_LEAVEDAYS]   DECIMAL(5,2)   NOT NULL,
        [LVD_REASON]      NVARCHAR(500)  NULL,
        [LVD_STATUS]      NVARCHAR(1)    NOT NULL,
        [LVD_APPLIEDON]   DATETIME2(3)   NOT NULL,
        [LVD_APPLIEDBY]   BIGINT         NOT NULL,
        [LVD_APPROVEDON]  DATETIME2(3)   NULL,
        [LVD_APPROVEDBY]  BIGINT         NULL,
        [LVD_REMARKS]     NVARCHAR(500)  NULL,
        CONSTRAINT [PK_LEAVE_DETAILS] PRIMARY KEY ([LVD_SYSID])
    );
    PRINT '+ LEAVE_DETAILS table created';
END
ELSE
    PRINT '= LEAVE_DETAILS already exists';
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_LEAVE_DETAILS_EMPSYSID' AND object_id = OBJECT_ID('LEAVE_DETAILS'))
BEGIN
    CREATE INDEX [IX_LEAVE_DETAILS_EMPSYSID] ON [LEAVE_DETAILS] ([LVD_EMPSYSID]);
    PRINT '+ IX_LEAVE_DETAILS_EMPSYSID created';
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_LEAVE_DETAILS_STATUS' AND object_id = OBJECT_ID('LEAVE_DETAILS'))
BEGIN
    CREATE INDEX [IX_LEAVE_DETAILS_STATUS] ON [LEAVE_DETAILS] ([LVD_STATUS]);
    PRINT '+ IX_LEAVE_DETAILS_STATUS created';
END
GO

-- Table: LEAVE_DETAILSAPR - Leave approval records
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LEAVE_DETAILSAPR')
BEGIN
    CREATE TABLE [LEAVE_DETAILSAPR] (
        [LDA_SYSID]       BIGINT        NOT NULL,
        [LDA_LVDSYSID]    BIGINT        NOT NULL,
        [LDA_APPROVEDBY]  BIGINT        NOT NULL,
        [LDA_APPROVEDON]  DATETIME2(3)  NOT NULL,
        CONSTRAINT [PK_LEAVE_DETAILSAPR] PRIMARY KEY ([LDA_SYSID])
    );
    PRINT '+ LEAVE_DETAILSAPR table created';
END
ELSE
    PRINT '= LEAVE_DETAILSAPR already exists';
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_LEAVE_DETAILSAPR_LVDSYSID' AND object_id = OBJECT_ID('LEAVE_DETAILSAPR'))
BEGIN
    CREATE INDEX [IX_LEAVE_DETAILSAPR_LVDSYSID] ON [LEAVE_DETAILSAPR] ([LDA_LVDSYSID]);
    PRINT '+ IX_LEAVE_DETAILSAPR_LVDSYSID created';
END
GO

-- Table: LEAVE_CREDIT - Leave credit/balance records
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LEAVE_CREDIT')
BEGIN
    CREATE TABLE [LEAVE_CREDIT] (
        [LVC_SYSID]       BIGINT         NOT NULL,
        [LVC_EMPSYSID]    BIGINT         NOT NULL,
        [LVC_LEAVEID]     INT            NOT NULL,
        [LVC_CREDITDAYS]  DECIMAL(5,2)   NOT NULL,
        [LVC_CREDITDATE]  DATETIME2(3)   NOT NULL,
        [LVC_REMARKS]     NVARCHAR(255)  NOT NULL,
        [LVC_CREATEDBY]   BIGINT         NOT NULL,
        [LVC_CREATEDON]   DATETIME2(3)   NOT NULL,
        CONSTRAINT [PK_LEAVE_CREDIT] PRIMARY KEY ([LVC_SYSID])
    );
    PRINT '+ LEAVE_CREDIT table created';
END
ELSE
    PRINT '= LEAVE_CREDIT already exists';
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_LEAVE_CREDIT_EMP_LEAVE' AND object_id = OBJECT_ID('LEAVE_CREDIT'))
BEGIN
    CREATE INDEX [IX_LEAVE_CREDIT_EMP_LEAVE] ON [LEAVE_CREDIT] ([LVC_EMPSYSID], [LVC_LEAVEID]);
    PRINT '+ IX_LEAVE_CREDIT_EMP_LEAVE created';
END
GO

-- Table: COMPOFF_ADJUST - Compensatory off records
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'COMPOFF_ADJUST')
BEGIN
    CREATE TABLE [COMPOFF_ADJUST] (
        [COA_SYSID]           BIGINT        NOT NULL,
        [COA_EMPSYSID]        BIGINT        NOT NULL,
        [COA_HOURSREQUESTED]  DECIMAL(5,2)  NOT NULL,
        [COA_STATUS]          NVARCHAR(1)   NOT NULL,
        [COA_REQUESTEDON]     DATETIME2(3)  NOT NULL,
        [COA_REQUESTEDBY]     BIGINT        NOT NULL,
        [COA_APPROVEDON]      DATETIME2(3)  NULL,
        [COA_APPROVEDBY]      BIGINT        NULL,
        CONSTRAINT [PK_COMPOFF_ADJUST] PRIMARY KEY ([COA_SYSID])
    );
    PRINT '+ COMPOFF_ADJUST table created';
END
ELSE
    PRINT '= COMPOFF_ADJUST already exists';
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_COMPOFF_ADJUST_EMPSYSID' AND object_id = OBJECT_ID('COMPOFF_ADJUST'))
BEGIN
    CREATE INDEX [IX_COMPOFF_ADJUST_EMPSYSID] ON [COMPOFF_ADJUST] ([COA_EMPSYSID]);
    PRINT '+ IX_COMPOFF_ADJUST_EMPSYSID created';
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_COMPOFF_ADJUST_STATUS' AND object_id = OBJECT_ID('COMPOFF_ADJUST'))
BEGIN
    CREATE INDEX [IX_COMPOFF_ADJUST_STATUS] ON [COMPOFF_ADJUST] ([COA_STATUS]);
    PRINT '+ IX_COMPOFF_ADJUST_STATUS created';
END
GO

PRINT '';
PRINT '=== PHASE 2 COMPLETE: All Tables Ready ===';
PRINT 'AIMSDB deployment complete. 10 tables created/verified.';
GO
