<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-TimeSheetService.Functions-22f4c073-1910-4f16-a9e6-42bc52a584fc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TimeSheetService.Application\TimeSheetService.Application.csproj" />
    <ProjectReference Include="..\TimeSheetService.Infrastructure\TimeSheetService.Infrastructure.csproj" />
  </ItemGroup>
</Project>
