IF OBJECT_ID('DOC_APALLDET','U') IS NULL
CREATE TABLE [DOC_APALLDET] (
    [APALL_ID] BIGINT NOT NULL,
    [APALL_DOCID] BIGINT NOT NULL,
    [APALL_ACTION] CHAR(1) NOT NULL,
    [APALL_GROUPID] BIGINT NOT NULL,
    [APALL_PULLSTATUS] CHAR(1) NOT NULL,
    [APALL_PULLUSERID] BIGINT NOT NULL,
    [APALL_PRIORITY] INT NOT NULL,
    [APALL_ALLBY] BIGINT NOT NULL,
    [APALL_ALLON] DATETIME2(3) NOT NULL,
    [APALL_REMARKS] VARCHAR(200) NULL,
    [APALL_ACTIONFLAG] CHAR(1) NOT NULL,
    [APALL_ACTIONDATE] DATETIME2(3) NULL,
    [APALL_CORRID] BIGINT NULL,
    [APALL_DEFTYPE] BIGINT NULL,
    [APALL_CLOSEREMARKS] VARCHAR(200) NULL,
    [APALL_MODIFIEDBY] BIGINT NOT NULL,
    [APALL_MODIFIEDON] DATETIME2(3) NOT NULL,
    [APALL_PULLEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_DOC_APALLDET] PRIMARY KEY ([APALL_ID])
);
GO

IF OBJECT_ID('DOC_CORRESPOND','U') IS NULL
CREATE TABLE [DOC_CORRESPOND] (
    [CORR_ID] BIGINT NOT NULL,
    [CORR_DOCID] BIGINT NOT NULL,
    [CORR_ALLID] BIGINT NOT NULL,
    [CORR_HOLDCAT] BIGINT NOT NULL,
    [CORR_HOLDTYPE] BIGINT NOT NULL,
    [CORR_HOLDDATE] DATETIME2(3) NOT NULL,
    [CORR_HOLDREMARKS] VARCHAR(200) NOT NULL,
    [CORR_HOLDBY] BIGINT NOT NULL,
    [CORR_HOLDSTATUS] CHAR(1) NOT NULL,
    [CORR_RELDATE] DATETIME2(3) NULL,
    [CORR_RELREMARKS] VARCHAR(200) NULL,
    [CORR_RELBY] BIGINT NULL,
    [CORR_HOLDNATURE] DECIMAL(38) NULL,
    CONSTRAINT [PK_DOC_CORRESPOND] PRIMARY KEY ([CORR_ID])
);
GO

IF OBJECT_ID('DOC_CORRESPONDATT','U') IS NULL
CREATE TABLE [DOC_CORRESPONDATT] (
    [ATT_ID] BIGINT NOT NULL,
    [ATT_CORRID] BIGINT NOT NULL,
    [ATT_CORRSTATUS] CHAR(1) NOT NULL,
    [ATT_FILEPATH] VARCHAR(200) NOT NULL,
    CONSTRAINT [PK_DOC_CORRESPONDATT] PRIMARY KEY ([ATT_ID])
);
GO

IF OBJECT_ID('DOC_DEFECTIVEATT','U') IS NULL
CREATE TABLE [DOC_DEFECTIVEATT] (
    [DEFATT_ID] BIGINT NOT NULL,
    [DEFATT_ALLID] BIGINT NOT NULL,
    [DEFATT_FILEPATH] VARCHAR(200) NOT NULL,
    CONSTRAINT [PK_DOC_DEFECTIVEATT] PRIMARY KEY ([DEFATT_ID])
);
GO

IF OBJECT_ID('DOC_STATUS','U') IS NULL
CREATE TABLE [DOC_STATUS] (
    [DOC_FLAG] CHAR(2) NOT NULL,
    [DOC_TYPE] CHAR(1) NOT NULL,
    [DOC_COMPLETEDREM] VARCHAR(100) NOT NULL,
    [DOC_PENDINGREM] VARCHAR(100) NOT NULL,
    [DOC_STAGEORDER] BIGINT NULL,
    [DOC_CATGROUP] VARCHAR(50) NULL,
    [DOC_STAGENO] BIGINT NULL,
    CONSTRAINT [PK_DOC_STATUS] PRIMARY KEY ([DOC_FLAG])
);
GO

IF OBJECT_ID('DOC_RESCANDET','U') IS NULL
CREATE TABLE [DOC_RESCANDET] (
    [RESCAN_ID] BIGINT NOT NULL,
    [RESCAN_DOCID] BIGINT NOT NULL,
    [RESCAN_ALLID] BIGINT NOT NULL,
    [RESCAN_STATUS] CHAR(1) NOT NULL,
    [RESCAN_DATE] DATETIME2(3) NOT NULL,
    [RESCAN_TO] CHAR(1) NOT NULL,
    [RESCAN_REMARKS] VARCHAR(100) NOT NULL,
    [RESCAN_ON] DATETIME2(3) NULL,
    [RESCAN_BY] BIGINT NULL,
    [RESCAN_COMPLETIONREM] VARCHAR(100) NULL,
    [RESCAN_FILEPATH] VARCHAR(200) NULL,
    CONSTRAINT [PK_DOC_RESCANDET] PRIMARY KEY ([RESCAN_ID])
);
GO

IF OBJECT_ID('DOC_REVOKEDET','U') IS NULL
CREATE TABLE [DOC_REVOKEDET] (
    [DOC_REVOKEDETID] BIGINT NOT NULL,
    [DOC_ID] BIGINT NOT NULL,
    [DOC_REVOKEREMARKS] VARCHAR(1000) NOT NULL,
    [DOC_REVOKESTATUS] CHAR(10) NOT NULL,
    [DOC_REVOKEDBY] BIGINT NOT NULL,
    [DOC_REVOKEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_DOC_REVOKEDET] PRIMARY KEY ([DOC_REVOKEDETID])
);
GO

IF OBJECT_ID('DOC_APPROVER','U') IS NULL
CREATE TABLE [DOC_APPROVER] (
    [DOC_APPRID] BIGINT NOT NULL,
    [DOC_BU] VARCHAR(25) NOT NULL,
    [DOC_LOC] BIGINT NOT NULL,
    [DOC_APPRTYPE] CHAR(1) NOT NULL,
    [DOC_APPREMPID] BIGINT NOT NULL,
    [DOC_ENTBY] BIGINT NOT NULL,
    [DOC_ENTON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_DOC_APPROVER] PRIMARY KEY ([DOC_APPRID])
);
GO

IF OBJECT_ID('DOC_APPDET','U') IS NULL
CREATE TABLE [DOC_APPDET] (
    [APP_SEQID] BIGINT NOT NULL,
    [APP_DOCID] BIGINT NOT NULL,
    [APP_USERID] BIGINT NOT NULL,
    [APP_STATUS] CHAR(1) NOT NULL,
    [APP_REMARKS] VARCHAR(200) NULL,
    [APP_DATE] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_DOC_APPDET] PRIMARY KEY ([APP_SEQID])
);
GO

IF OBJECT_ID('DOC_ORACLEINVDET','U') IS NULL
CREATE TABLE [DOC_ORACLEINVDET] (
    [DOC_INVID] BIGINT NOT NULL,
    [DOC_ID] BIGINT NOT NULL,
    [DOC_VOUCHERNO] DECIMAL(38) NULL,
    [DOC_INVOICETYPE] VARCHAR(25) NULL,
    [DOC_VENDORID] BIGINT NULL,
    [DOC_VENDOR_SITEID] BIGINT NULL,
    [DOC_INVOICENUM] VARCHAR(50) NULL,
    [DOC_INVOICEDATE] DATETIME2(3) NULL,
    [DOC_INVOICEAMOUNT] DECIMAL(38) NULL,
    [DOC_INVOICEID] BIGINT NOT NULL,
    [DOC_INVOICESTATUS] VARCHAR(4000) NULL,
    [DOC_INVOICECREATEDON] DATETIME2(3) NULL,
    [DOC_INVOICECREATEDBY] DECIMAL(38) NULL,
    [DOC_PAYMENT_METHOD_CODE] VARCHAR(30) NULL,
    [DOC_ACCOUNTING_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_DOC_ORACLEINVDET] PRIMARY KEY ([DOC_INVID])
);
GO

IF OBJECT_ID('DOC_ORACLEPAYDET','U') IS NULL
CREATE TABLE [DOC_ORACLEPAYDET] (
    [DOC_PAYID] BIGINT NOT NULL,
    [DOC_ID] BIGINT NOT NULL,
    [DOC_PAYMENTNUM] BIGINT NOT NULL,
    [DOC_INVOICEID] BIGINT NOT NULL,
    [DOC_DUEDATE] DATETIME2(3) NULL,
    [DOC_GROSSAMOUNT] DECIMAL(38) NULL,
    [DOC_AMOUNTREMAINING] DECIMAL(38) NULL,
    [DOC_PAYMENT_STATUS] VARCHAR(14) NULL,
    [DOC_PAYMENT_METHOD] VARCHAR(30) NULL,
    [DOC_PREPAYMENT_APPLIED] VARCHAR(3) NULL,
    [DOC_PAYMENT_CREATEDBY] DECIMAL(38) NULL,
    [DOC_PAYMENT_CREATEDON] DATETIME2(3) NULL,
    [CHECK_ID] BIGINT NULL,
    [BNKSTATUS] CHAR(1) NULL,
    [CHECK_NUMBER] BIGINT NULL,
    [CHECK_DATE] DATETIME2(3) NULL,
    [CHECK_AMOUNT] DECIMAL(38) NULL,
    CONSTRAINT [PK_DOC_ORACLEPAYDET] PRIMARY KEY ([DOC_PAYID])
);
GO

IF OBJECT_ID('DOC_ORACLEBNKDET','U') IS NULL
CREATE TABLE [DOC_ORACLEBNKDET] (
    [DOC_BNKID] BIGINT NOT NULL,
    [DOC_ID] BIGINT NOT NULL,
    [TYPE] VARCHAR(255) NULL,
    [CHECK_ID] VARCHAR(255) NOT NULL,
    [BUSINESS] VARCHAR(255) NULL,
    [ORG_ID] VARCHAR(255) NULL,
    [VENDOR_SITE_ID] VARCHAR(255) NULL,
    [FILE_NAME] VARCHAR(255) NULL,
    [RECORD_IDETIFIER] VARCHAR(255) NULL,
    [TRANSACTION_TYPE] VARCHAR(255) NULL,
    [VENDOR_CODE] VARCHAR(255) NULL,
    [MAIL_TO] VARCHAR(255) NULL,
    [BENE_MAIL_ADDRESS] VARCHAR(255) NULL,
    [BENE_BANK_AC] VARCHAR(255) NULL,
    [PAY_TO] VARCHAR(255) NULL,
    [CHECK_DATE] VARCHAR(255) NULL,
    [AMOUNT] VARCHAR(255) NULL,
    [HUNDI] VARCHAR(255) NULL,
    [CURRENCY] VARCHAR(255) NULL,
    [PAYMENT_LOCATION] VARCHAR(255) NULL,
    [PAYMENT_NUMBER] VARCHAR(255) NULL,
    [CHECK_NUMBER] VARCHAR(255) NULL,
    [PAYMENT_DATE] VARCHAR(255) NULL,
    [RECORS_ANNEXURE] VARCHAR(255) NULL,
    [PRINT_LOCATION] VARCHAR(255) NULL,
    [BENE_IFSC] VARCHAR(255) NULL,
    [BENE_ACCOUNT_TYPE] VARCHAR(255) NULL,
    [BENE_BANK_NAME] VARCHAR(255) NULL,
    [BENE_BANK_AC22] VARCHAR(255) NULL,
    [BENE_BANK_BRANCH] VARCHAR(255) NULL,
    [BENE_BANK_LOCATION] VARCHAR(255) NULL,
    [BENE_MAIL_ID] VARCHAR(255) NULL,
    [REF_NO] VARCHAR(255) NULL,
    [UTR_NO] VARCHAR(255) NULL,
    [REJECT_REASON1] VARCHAR(255) NULL,
    [REJECT_REASON2] VARCHAR(255) NULL,
    [STATUS_LOOKUP_CODE] VARCHAR(25) NULL,
    CONSTRAINT [PK_DOC_ORACLEBNKDET] PRIMARY KEY ([DOC_BNKID])
);
GO

IF OBJECT_ID('DOC_ORACLEDUEDET','U') IS NULL
CREATE TABLE [DOC_ORACLEDUEDET] (
    [DOC_DUEID] BIGINT NOT NULL,
    [DOC_ID] BIGINT NOT NULL,
    [ORG_ID] BIGINT NULL,
    [INVOICEID] BIGINT NOT NULL,
    [VOUCHER_NO] DECIMAL(38) NULL,
    [DOCUMENT_ID] VARCHAR(150) NULL,
    [DUEDATE] DATETIME2(3) NULL,
    [PAYMENT_NUM] BIGINT NULL,
    [DUE_AMOUNT] DECIMAL(38) NULL,
    [DOC_DUECREATEDBY] DECIMAL(38) NULL,
    [DOC_DUECREATEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_DOC_ORACLEDUEDET] PRIMARY KEY ([DOC_DUEID])
);
GO
