-- Seed data for TASK_MAIL table
-- Run this script against TASKDB if not using EF migrations

USE [TASKDB];
GO

IF NOT EXISTS (SELECT 1 FROM TASK_MAIL WHERE MID = 1)
    INSERT INTO TASK_MAIL (MID, SYSID) VALUES (1, 1001);

IF NOT EXISTS (SELECT 1 FROM TASK_MAIL WHERE MID = 2)
    INSERT INTO TASK_MAIL (MID, SYSID) VALUES (2, 1002);

IF NOT EXISTS (SELECT 1 FROM TASK_MAIL WHERE MID = 3)
    INSERT INTO TASK_MAIL (MID, SYSID) VALUES (3, 1001);

PRINT 'Seed data inserted successfully.';
GO
