// <auto-generated />
using System;
using LoanService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LoanDbContext))]
    partial class LoanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoanService.Domain.Entities.LoanDeduction", b =>
                {
                    b.Property<long>("DedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("DED_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DedId"));

                    b.Property<decimal?>("ContributionId")
                        .HasColumnType("decimal(38)")
                        .HasColumnName("CONTRIBUTION_ID");

                    b.Property<decimal>("DedAmount")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("DED_AMOUNT");

                    b.Property<DateTime>("DedDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("DED_DATE");

                    b.Property<long>("LoanNo")
                        .HasColumnType("bigint")
                        .HasColumnName("LOAN_NO");

                    b.HasKey("DedId");

                    b.HasIndex("LoanNo");

                    b.ToTable("LOAN_DEDUCTION", (string)null);
                });

            modelBuilder.Entity("LoanService.Domain.Entities.LoanMain", b =>
                {
                    b.Property<long>("LoanNo")
                        .HasColumnType("bigint")
                        .HasColumnName("LOAN_NO");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("LOAN_APPROVAL_DATE");

                    b.Property<DateTime?>("ClosureDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("LOAN_CLOSURE_DATE");

                    b.Property<string>("ClsFlag")
                        .HasColumnType("char(1)")
                        .HasColumnName("LOAN_CLSFLAG");

                    b.Property<decimal?>("LoanAmount")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("LOAN_AMOUNT");

                    b.Property<DateTime?>("LoanDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("LOAN_DATE");

                    b.Property<string>("LoanReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LOAN_REASON");

                    b.Property<string>("LoanTenure")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("LOAN_TENURE");

                    b.Property<long?>("LoanType")
                        .HasColumnType("bigint")
                        .HasColumnName("LOAN_TYPE");

                    b.Property<long?>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("LOAN_MEMBER_ID");

                    b.Property<decimal?>("PrincipalOutstanding")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("LOAN_PRINCIPALOS");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("LOAN_RATE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("LOAN_STATUS");

                    b.Property<string>("TrustCode")
                        .HasColumnType("char(3)")
                        .HasColumnName("LOAN_TRUST_CODE");

                    b.Property<long?>("UpdatedByEmpId")
                        .HasColumnType("bigint")
                        .HasColumnName("LOAN_UPDBY_EMP_SYSIDC");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("LOAN_UPDON");

                    b.HasKey("LoanNo");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("IDX_LOAN_MAIN_MEMBER");

                    b.ToTable("LOAN_MAIN", (string)null);
                });

            modelBuilder.Entity("LoanService.Domain.Entities.LoanRepayment", b =>
                {
                    b.Property<long>("RepayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("REPAY_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RepayId"));

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("REPAY_DUE_DATE");

                    b.Property<int>("InstallmentNo")
                        .HasColumnType("int")
                        .HasColumnName("REPAY_INSTALLMENT_NO");

                    b.Property<long>("LoanNo")
                        .HasColumnType("bigint")
                        .HasColumnName("LOAN_NO");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("REPAY_PAID_AMOUNT");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("REPAY_PAID_DATE");

                    b.Property<decimal>("RepayAmount")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("REPAY_AMOUNT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("O")
                        .HasColumnName("REPAY_STATUS");

                    b.HasKey("RepayId");

                    b.HasIndex("LoanNo", "Status")
                        .HasDatabaseName("IDX_LOAN_REPAYMENT_LOAN");

                    b.ToTable("LOAN_REPAYMENT", (string)null);
                });

            modelBuilder.Entity("LoanService.Domain.Entities.LoanDeduction", b =>
                {
                    b.HasOne("LoanService.Domain.Entities.LoanMain", "Loan")
                        .WithMany("Deductions")
                        .HasForeignKey("LoanNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LoanService.Domain.Entities.LoanRepayment", b =>
                {
                    b.HasOne("LoanService.Domain.Entities.LoanMain", "Loan")
                        .WithMany("Repayments")
                        .HasForeignKey("LoanNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LoanService.Domain.Entities.LoanMain", b =>
                {
                    b.Navigation("Deductions");

                    b.Navigation("Repayments");
                });
#pragma warning restore 612, 618
        }
    }
}
