apiVersion: v1
kind: ConfigMap
metadata:
  name: pf-config
  namespace: pf-services
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_HTTP_PORTS: "8080"
  RabbitMQ__HostName: "rabbitmq"
  RabbitMQ__Port: "5672"
  RabbitMQ__VirtualHost: "/"
  Jwt__Issuer: "PFServices"
  Jwt__Audience: "PFServiceClients"
