apiVersion: v1
kind: Secret
metadata:
  name: swipe-transaction-service-secrets
  namespace: swipe-transaction-service
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=sql-server.default.svc.cluster.local;Database=SwipeTransactionDb;User Id=sa;Password=YourPassword123!;TrustServerCertificate=True;"
  Jwt__Secret: "SwipeTransactionService-SuperSecretKey-ChangeInProduction-Min32Characters!"
  RabbitMQ__Password: "guest"
---
apiVersion: v1
kind: Secret
metadata:
  name: swipe-transaction-service-docker-registry
  namespace: swipe-transaction-service
type: kubernetes.io/dockercfg
data:
  .dockercfg: e30=
