-- ==========================================
-- SECURITY MODULE - Table Definitions
-- Database: SCIDB
-- Module: User, Role & Access Management
-- Created: March 9, 2026
-- ==========================================

USE SCIDB;
GO

-- Table: USER_MASTER
CREATE TABLE [USER_MASTER] (
    [UM_USR_COD] VARCHAR(25) NOT NULL,
    [UM_USR_NUM] BIGINT NOT NULL,
    [UM_USR_NAM] VARCHAR(100) NULL,
    [UM_USR_MAI] VARCHAR(100) NULL,
    [UM_USR_PHN] BIGINT NULL,
    [UM_STR_DAT] DATETIME2(3) NOT NULL,
    [UM_END_DAT] DATETIME2(3) NULL,
    [UM_USR_TYP] CHAR(1) NULL,
    [UM_UPD_USR] VARCHAR(25) NULL,
    [UM_UPD_NUM] BIGINT NULL,
    [UM_UPD_DAT] DATETIME2(3) NULL,
    CONSTRAINT [PK_USER_MASTER] PRIMARY KEY ([UM_USR_NUM])
);

-- Table: USER_ROLE
CREATE TABLE [USER_ROLE] (
    [UR_USR_NUM] BIGINT NOT NULL,
    [UR_ROL_COD] BIGINT NOT NULL,
    [UR_STR_DAT] DATETIME2(3) NOT NULL,
    [UR_END_DAT] DATETIME2(3) NULL,
    [UR_UPD_USR] VARCHAR(25) NULL,
    [UR_UPD_NUM] BIGINT NULL,
    [UR_UPD_DAT] DATETIME2(3) NULL,
    CONSTRAINT [PK_USER_ROLE] PRIMARY KEY ([UR_USR_NUM], [UR_ROL_COD])
);

-- Table: ROLE_MAST
CREATE TABLE [ROLE_MAST] (
    [RL_ROL_COD] BIGINT NOT NULL,
    [RL_ROL_NAM] VARCHAR(200) NOT NULL,
    [RL_UPD_USR] VARCHAR(50) NULL,
    [RL_UPD_NUM] BIGINT NULL,
    [RL_UPD_DAT] DATETIME2(3) NULL,
    CONSTRAINT [PK_ROLE_MAST] PRIMARY KEY ([RL_ROL_COD])
);

-- Table: ACCESS_ROLE
CREATE TABLE [ACCESS_ROLE] (
    [RA_USR_COD] VARCHAR(25) NULL,
    [RA_USR_NUM] BIGINT NULL,
    [RA_ROL_COD] BIGINT NULL,
    [RA_UPD_USR] VARCHAR(25) NULL,
    [RA_UPD_NUM] BIGINT NULL,
    [RA_UPD_DAT] DATETIME2(3) NULL,
    [RA_STR_DAT] DATETIME2(3) NULL,
    [RA_END_DAT] DATETIME2(3) NULL
);

-- Table: ACCESS_ROLE_MASTER
CREATE TABLE [ACCESS_ROLE_MASTER] (
    [AR_ROL_COD] BIGINT NULL,
    [AR_ROL_NAM] VARCHAR(200) NULL,
    [AR_UPD_USR] VARCHAR(25) NULL,
    [AR_UPD_NUM] BIGINT NULL,
    [AR_UPD_DAT] DATETIME2(3) NULL
);

-- Table: ACCESSROLE_MENU
CREATE TABLE [ACCESSROLE_MENU] (
    [ARM_ROL_COD] BIGINT NULL,
    [ARM_MEN_COD] BIGINT NULL,
    [ARM_UPD_USR] VARCHAR(25) NULL,
    [ARM_UPD_NUM] BIGINT NULL,
    [ARM_UPD_DAT] DATETIME2(3) NULL
);

-- Table: MENUMASTER
CREATE TABLE [MENUMASTER] (
    [MENU_ID] BIGINT NULL,
    [MENU_NAME] VARCHAR(100) NULL,
    [URL] VARCHAR(50) NULL,
    [PARENT_MENU_ID] BIGINT NULL,
    [DISPLAYORDER] BIGINT NULL
);

-- Table: USER_MASTER_MAP (User Department/Organization Mapping)
CREATE TABLE [USER_MASTER_MAP] (
    [UM_MAP_ID] BIGINT NOT NULL,
    [UM_USR_NUM] BIGINT NOT NULL,
    [UM_DEPT_COD] VARCHAR(25) NOT NULL,
    [UM_STR_DAT] DATETIME2(3) NOT NULL,
    [UM_END_DAT] DATETIME2(3) NULL,
    CONSTRAINT [PK_USER_MASTER_MAP] PRIMARY KEY ([UM_MAP_ID])
);

PRINT 'SECURITY_MODULE Tables created successfully.';
GO
