-- ==========================================
-- PRODUCTION MANAGEMENT MODULE - Table Definitions
-- Database: SCIDB
-- Module: Production Planning
-- Created: March 9, 2026
-- ==========================================

USE SCIDB;
GO

-- Table: PRODUCTION_PLANT
CREATE TABLE [PRODUCTION_PLANT] (
    [PRODUCTION_PLANT_ID] INT NOT NULL,
    [COMPANY_UNIT_ID] INT NOT NULL,
    [PLANT_NAME] VARCHAR(60) NOT NULL,
    [LOCATION] VARCHAR(25) NOT NULL,
    [SCI_USER_ID_CREATED] INT NULL,
    [CREATION_DATE] DATETIME2(3) NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] VARCHAR(255) NULL,
    CONSTRAINT [PK_PRODUCTION_PLANT] PRIMARY KEY ([PRODUCTION_PLANT_ID])
);

-- Table: PRODUCTION_PLAN
CREATE TABLE [PRODUCTION_PLAN] (
    [PRODUCTION_PLANT_ID] INT NOT NULL,
    [SCI_ITEM_ID] INT NOT NULL,
    [QTY_PERDAY] INT NOT NULL,
    [PLAN_START_DATE] DECIMAL(38) NOT NULL,
    [PLAN_CLOSURE_DATE] DATETIME2(3) NULL,
    [SCI_USER_ID_MODIFIED] INT NOT NULL,
    [MODIFIED_DATE] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_PRODUCTION_PLAN] PRIMARY KEY ([PRODUCTION_PLANT_ID], [SCI_ITEM_ID])
);

-- Table: PRODUCTIONPLAN_ENTRY
CREATE TABLE [PRODUCTIONPLAN_ENTRY] (
    [ORACLE_CODE] VARCHAR(50) NULL,
    [MONTH] VARCHAR(10) NULL,
    [PRO_TYPE] CHAR(1) NULL,
    [PRO_VALUE] INT NULL,
    [FACTORY_ID] INT NULL,
    [ZONE] VARCHAR(10) NULL,
    [PRO_YEAR] INT NULL
);

-- Table: PRODUCTIONPLANT_PRODUCT_MAP
CREATE TABLE [PRODUCTIONPLANT_PRODUCT_MAP] (
    [PRODUCTION_PLANT_ID] INT NOT NULL,
    [PRODUCT_ID] INT NOT NULL,
    [SCI_USER_ID_CREATED] INT NOT NULL,
    [CREATION_DATE] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_PRODUCTIONPLANT_PRODUCT_MAP] PRIMARY KEY ([PRODUCTION_PLANT_ID], [PRODUCT_ID])
);

-- Table: MAM_PRODUCTION_DET (MAM Production Details)
CREATE TABLE [MAM_PRODUCTION_DET] (
    [PRODUCTION_NO] BIGINT NULL,
    [PRODUCTION_DATE] DATETIME2(3) NULL,
    [PRODUCTION_FG] INT NULL,
    [PRODUCTION_QTY] DECIMAL(19,0) NULL
);

-- Table: MAM_PRODUCTION_MAP (MAM Production Map)
CREATE TABLE [MAM_PRODUCTION_MAP] (
    [RM_CODE] INT NULL,
    [FG_CODE] INT NULL,
    [SLNO] DECIMAL(38) NULL
);

-- Table: NORMS_MAIN (Norms Main)
CREATE TABLE [NORMS_MAIN] (
    [NORM_NO] BIGINT NOT NULL,
    [NORM_EFF_DATE] DATETIME2(3) NOT NULL,
    [NORM_CLS_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_NORMS_MAIN] PRIMARY KEY ([NORM_NO])
);

-- Table: NORMS_MASTER (Norms Master)
CREATE TABLE [NORMS_MASTER] (
    [NORM_ID] BIGINT NULL,
    [NORM_INPUT_CODE] INT NULL,
    [NORM_OUTPUT_CODE] INT NULL,
    [NORM_RATE] INT NULL,
    [NORM_NO] BIGINT NULL
);

PRINT 'PRODUCTION_MANAGEMENT_MODULE Tables created successfully.';
GO
