-- ==========================================
-- COURSE MODULE - Schema
-- Database: LETDB
-- Purpose: Course & Training Management
-- Created: March 9, 2026
-- ==========================================

USE LETDB;
GO

-- ==========================================
-- COURSE MODULE - Core Tables
-- ==========================================

-- Table: COURSE_MAST - Course Master
CREATE TABLE [COURSE_MAST] (
    [CR_CRS_ID] BIGINT NOT NULL PRIMARY KEY,
    [CR_CRS_TYP] CHAR(1) NOT NULL,
    [CR_CRS_DES] VARCHAR(255) NOT NULL,
    [CR_EFF_DAT] DATETIME2(3) NOT NULL,
    [CR_CLS_DAT] DATETIME2(3) NOT NULL,
    [CR_OBJ_DES] VARCHAR(255) NOT NULL,
    [CR_LOC_COD] CHAR(1) NOT NULL,
    [CR_ADD_LN1] VARCHAR(255) NOT NULL,
    [CR_ADD_LN2] VARCHAR(255) NOT NULL,
    [CR_ADD_LN3] VARCHAR(255) NOT NULL,
    [CR_PIN_COD] BIGINT NOT NULL,
    [CR_PHN_NUM] VARCHAR(255) NOT NULL,
    [CR_STR_DAT] DATETIME2(3) NOT NULL,
    [CR_END_DAT] DATETIME2(3) NOT NULL,
    [CR_LST_DAT] DATETIME2(3) NOT NULL,
    [CR_NO_DYS] BIGINT NOT NULL,
    [CR_TRN_TYP] CHAR(1) NOT NULL,
    [CR_CAN_DAT] DATETIME2(3) NULL,
    [CR_CAN_REM] VARCHAR(255) NULL,
    [CR_FIL_NAM] VARCHAR(255) NULL,
    [CR_TRN_NAM1] VARCHAR(255) NULL,
    [CR_TRN_NAM2] VARCHAR(255) NULL,
    [CR_TRN_NAM3] VARCHAR(255) NULL,
    [CR_TRN_DES1] VARCHAR(255) NULL,
    [CR_TRN_DES2] VARCHAR(255) NULL,
    [CR_TRN_DES3] VARCHAR(255) NULL,
    [CR_TRN_CNT1] VARCHAR(255) NULL,
    [CR_TRN_CNT2] VARCHAR(255) NULL,
    [CR_TRN_CNT3] VARCHAR(255) NULL,
    [CR_TRN_COD] BIGINT NULL,
    [CR_TRN_RAT] DECIMAL(38) NULL,
    [CR_CNT_RAT] DECIMAL(38) NULL,
    [CR_ADM_RAT] DECIMAL(38) NULL,
    [CR_PEN_DAT] DATETIME2(3) NULL,
    [CR_THMB_PIC] VARCHAR(255) NULL,
    [CR_CRS_DUR] VARCHAR(255) NULL,
    [CR_EVAL_ID] BIGINT NULL
);

-- Table: COURSE_MASTTEST - Course Master Test
CREATE TABLE [COURSE_MASTTEST] (
    [CR_CRS_ID] BIGINT NULL,
    [CR_CRS_TYP] CHAR(1) NULL,
    [CR_CRS_DES] VARCHAR(255) NULL,
    [CR_EFF_DAT] DATETIME2(3) NULL,
    [CR_CLS_DAT] DATETIME2(3) NULL,
    [CR_OBJ_DES] VARCHAR(255) NULL,
    [CR_LOC_COD] CHAR(1) NULL,
    [CR_ADD_LN1] VARCHAR(255) NULL,
    [CR_ADD_LN2] VARCHAR(255) NULL,
    [CR_ADD_LN3] VARCHAR(255) NULL,
    [CR_PIN_COD] BIGINT NULL,
    [CR_PHN_NUM] VARCHAR(255) NULL,
    [CR_STR_DAT] DATETIME2(3) NULL,
    [CR_END_DAT] DATETIME2(3) NULL,
    [CR_LST_DAT] DATETIME2(3) NULL,
    [CR_NO_DYS] BIGINT NULL,
    [CR_TRN_TYP] CHAR(1) NULL,
    [CR_CAN_DAT] DATETIME2(3) NULL,
    [CR_CAN_REM] VARCHAR(255) NULL,
    [CR_FIL_NAM] VARCHAR(255) NULL,
    [CR_TRN_NAM1] VARCHAR(255) NULL,
    [CR_TRN_NAM2] VARCHAR(255) NULL,
    [CR_TRN_NAM3] VARCHAR(255) NULL,
    [CR_TRN_DES1] VARCHAR(255) NULL,
    [CR_TRN_DES2] VARCHAR(255) NULL,
    [CR_TRN_DES3] VARCHAR(255) NULL,
    [CR_TRN_CNT1] VARCHAR(255) NULL,
    [CR_TRN_CNT2] VARCHAR(255) NULL,
    [CR_TRN_CNT3] VARCHAR(255) NULL,
    [CR_TRN_COD] BIGINT NULL,
    [CR_TRN_RAT] DECIMAL(38) NULL,
    [CR_CNT_RAT] DECIMAL(38) NULL,
    [CR_ADM_RAT] DECIMAL(38) NULL,
    [CR_PEN_DAT] DATETIME2(3) NULL,
    [CR_THMB_PIC] VARCHAR(255) NULL
);

-- Table: COURSE_ALLOCATION
CREATE TABLE [COURSE_ALLOCATION] (
    [CS_CRS_ID] BIGINT NOT NULL PRIMARY KEY,
    [CS_SRL_NUM] BIGINT NOT NULL,
    [CS_CST_COD] BIGINT NOT NULL,
    [CS_ALL_NUM] DECIMAL(19,0) NOT NULL,
    [CS_UNT_COD] CHAR(3) NOT NULL,
    [CS_CST_REM] VARCHAR(25) NOT NULL
);

-- Table: COURSE_BAND
CREATE TABLE [COURSE_BAND] (
    [COURSEBAND_COURSEID] BIGINT NULL PRIMARY KEY,
    [COURSEBAND_ID] BIGINT NULL
);

-- Table: COURSE_COST
CREATE TABLE [COURSE_COST] (
    [CS_CRS_ID] BIGINT NULL PRIMARY KEY,
    [CS_CST_COD] BIGINT NULL,
    [CS_CST_AMT] BIGINT NULL,
    [CS_CST_TYP] CHAR(1) NULL,
    [CS_REM_MRK] VARCHAR(200) NULL,
    [CS_UNT_COD] CHAR(6) NULL
);

-- Table: COURSE_COSTALL
CREATE TABLE [COURSE_COSTALL] (
    [CS_CRS_ID] BIGINT NOT NULL PRIMARY KEY,
    [CS_SRL_NUM] BIGINT NOT NULL,
    [CS_CST_COD] CHAR(1) NOT NULL,
    [CS_UNT_COD] CHAR(1) NOT NULL,
    [CS_CST_AMT] DECIMAL(19,0) NOT NULL,
    [CS_ALL_DAT] DATETIME2(3) NOT NULL,
    [CS_PST_DAT] DATETIME2(3) NULL
);

-- Table: COURSE_SCHEDULE
CREATE TABLE [COURSE_SCHEDULE] (
    [CS_CRS_ID] BIGINT NOT NULL,
    [CS_SCH_SRL] BIGINT NOT NULL PRIMARY KEY,
    [CS_SCH_DAT] DATETIME2(3) NOT NULL,
    [CS_STR_TIM] CHAR(5) NOT NULL,
    [CS_END_TIM] CHAR(5) NOT NULL,
    [CS_LOC_NAM] VARCHAR(65) NOT NULL,
    [CS_TRN_NAM] VARCHAR(65) NOT NULL,
    CONSTRAINT [FK_COURSE_SCHEDULE_COURSE_MAST] FOREIGN KEY ([CS_CRS_ID]) REFERENCES [COURSE_MAST]([CR_CRS_ID])
);

-- Table: COURSE_RATE
CREATE TABLE [COURSE_RATE] (
    [CR_CRS_ID] BIGINT NOT NULL PRIMARY KEY,
    [CR_EVL_TYP] BIGINT NOT NULL,
    [CR_EVL_RAT] DECIMAL(19,0) NULL,
    [CR_UNT_COD] CHAR(3) NULL
);

-- Table: COURSE_MODEL
CREATE TABLE [COURSE_MODEL] (
    [MD_CRS_ID] BIGINT NOT NULL,
    [MD_SKL_NUM] BIGINT NOT NULL,
    [MD_LVL_NUM] BIGINT NOT NULL,
    [MD_SKL_GRP] CHAR(3) NULL,
    CONSTRAINT [PK_COURSE_MODEL] PRIMARY KEY ([MD_CRS_ID], [MD_SKL_NUM])
);

-- Table: COURSE_PARTICIPANT_MGT
CREATE TABLE [COURSE_PARTICIPANT_MGT] (
    [CS_CRS_ID] BIGINT NULL,
    [CS_NOM_NUM] BIGINT NULL,
    [CS_USR_COD] VARCHAR(255) NULL,
    [CS_CAN_DAT] DATETIME2(3) NULL,
    [CS_CAN_REM] VARCHAR(255) NULL,
    [CS_ENR_DAT] DATETIME2(3) NULL,
    [CS_APPR_APPROV] CHAR(1) NULL,
    [CS_APR_CANCEL] CHAR(1) NULL,
    [CS_USR_PIN] BIGINT NULL,
    [CS_APPR_COD] VARCHAR(255) NULL,
    [CS_APPR_PIN] BIGINT NULL,
    [CS_NOM_STS] BIGINT NULL,
    [CS_REQNUM] BIGINT NULL,
    [CS_TYPE] CHAR(1) NULL,
    [CS_CRS_DESC] VARCHAR(255) NULL,
    [CS_TRAINING_DATE] VARCHAR(255) NULL,
    [CS_STARTDAT] DATETIME2(3) NULL,
    [CS_ENDATE] DATETIME2(3) NULL,
    [CS_ATTEN] CHAR(1) NULL,
    [CS_STRDAT] DATETIME2(3) NULL,
    [CS_ENDAT] DATETIME2(3) NULL
);

-- Table: JOB_BAND
CREATE TABLE [JOB_BAND] (
    [JB_JOB_CODE] BIGINT NULL,
    [JB_CRS_ID] BIGINT NULL
);

-- ==========================================
-- INDEXES FOR COURSE MODULE
-- ==========================================

CREATE INDEX [IDX_COURSE_MAST_CRS_TYP] ON [COURSE_MAST]([CR_CRS_TYP]);
CREATE INDEX [IDX_COURSE_SCHEDULE_CRS_ID] ON [COURSE_SCHEDULE]([CS_CRS_ID]);
CREATE INDEX [IDX_COURSE_PARTICIPANT_CRS_ID] ON [COURSE_PARTICIPANT_MGT]([CS_CRS_ID]);
CREATE INDEX [IDX_COURSE_PARTICIPANT_USR_COD] ON [COURSE_PARTICIPANT_MGT]([CS_USR_COD]);

PRINT 'Course Module Schema created successfully.';
GO
