apiVersion: v1
kind: Namespace
metadata:
  name: itemmaster-service
  labels:
    name: itemmaster-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: itemmaster-service-config
  namespace: itemmaster-service
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:5194"
  Jwt__Issuer: "ItemMasterService"
  Jwt__Audience: "ItemMasterServiceClients"
  Jwt__ExpiresInMinutes: "60"
  RabbitMQ__Host: "rabbitmq.itemmaster-service.svc.cluster.local"
  RabbitMQ__Port: "5672"
  RabbitMQ__Username: "guest"
  RabbitMQ__VirtualHost: "/"
  RabbitMQ__ExchangeName: "itemmaster.exchange"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft: "Warning"
