-- ==========================================
-- Database: GROUPINCENTIVEDB
-- Module: Group Incentive Management System
-- Generated Module Script
-- ==========================================

USE master;
GO

-- ==========================================
-- PHASE 1: Database Creation
-- ==========================================
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'GROUPINCENTIVEDB')
    DROP DATABASE GROUPINCENTIVEDB;
GO

CREATE DATABASE GROUPINCENTIVEDB
ON PRIMARY (
    NAME = 'GROUPINCENTIVEDB_Data',
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15\MSSQL\DATA\GROUPINCENTIVEDB_Data.mdf',
    SIZE = 120MB,
    MAXSIZE = 600MB,
    FILEGROWTH = 12MB
)
LOG ON (
    NAME = 'GROUPINCENTIVEDB_Log',
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15\MSSQL\DATA\GROUPINCENTIVEDB_Log.ldf',
    SIZE = 50MB,
    MAXSIZE = 200MB,
    FILEGROWTH = 6MB
);
GO

PRINT '=== PHASE 1 COMPLETE: Database Created ===';
GO

-- ==========================================
-- PHASE 2: Table Definitions
-- ==========================================
USE GROUPINCENTIVEDB;
GO

-- Table: Group_Master - Group Master Information
CREATE TABLE [Group_Master] (
    [GROUP_ID] INT NOT NULL,
    [GROUP_NAME] VARCHAR(255) NOT NULL,
    [GROUP_DESCRIPTION] VARCHAR(500) NULL,
    [GROUP_EFFDATE] DATETIME2(3) NOT NULL,
    [GROUP_CLSDATE] DATETIME2(3) NULL,
    [GROUP_STATUS] CHAR(1) NOT NULL,
    [GROUP_LASTMODIFIEDBY] BIGINT NOT NULL,
    [GROUP_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_Group_Master] PRIMARY KEY ([GROUP_ID]),
    CONSTRAINT [UQ_GROUP_NAME] UNIQUE ([GROUP_NAME])
);

-- Table: GROUP_EMPLOYEEMAP - Group to Employee Mapping
CREATE TABLE [GROUP_EMPLOYEEMAP] (
    [GRPEMPMAP_ID] BIGINT NOT NULL,
    [GRPEMPMAP_GROUPID] INT NOT NULL,
    [GRPEMPMAP_EMPSYSID] BIGINT NOT NULL,
    [GRPEMPMAP_EFFDATE] DATETIME2(3) NOT NULL,
    [GRPEMPMAP_CLSDATE] DATETIME2(3) NULL,
    [GRPEMPMAP_ROLE] VARCHAR(50) NULL,
    [GRPEMPMAP_LASTMODIFIEDBY] BIGINT NOT NULL,
    [GRPEMPMAP_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_GROUP_EMPLOYEEMAP] PRIMARY KEY ([GRPEMPMAP_ID]),
    CONSTRAINT [FK_GRPEMPMAP_GROUPID] FOREIGN KEY ([GRPEMPMAP_GROUPID]) REFERENCES [Group_Master]([GROUP_ID]),
    CONSTRAINT [UQ_GRPEMPMAP] UNIQUE ([GRPEMPMAP_GROUPID], [GRPEMPMAP_EMPSYSID], [GRPEMPMAP_EFFDATE])
);

-- Table: GROUPINCENTIVE_MAIN - Group Incentive Main Record
CREATE TABLE [GROUPINCENTIVE_MAIN] (
    [GRPINC_ID] BIGINT NOT NULL,
    [GRPINC_GROUPID] INT NOT NULL,
    [GRPINC_INCMONTH] INT NOT NULL,
    [GRPINC_INCYEAR] INT NOT NULL,
    [GRPINC_TOTALAMOUNT] DECIMAL(15,2) NOT NULL,
    [GRPINC_APPSTATUS] CHAR(1) NOT NULL,
    [GRPINC_APPROVEDAMOUNT] DECIMAL(15,2) NULL,
    [GRPINC_APPROVER] BIGINT NULL,
    [GRPINC_APPROVALDATE] DATETIME2(3) NULL,
    [GRPINC_ENTEREDON] DATETIME2(3) NOT NULL,
    [GRPINC_ENTEREDBY] BIGINT NOT NULL,
    [GRPINC_LASTMODIFIEDBY] BIGINT NOT NULL,
    [GRPINC_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_GROUPINCENTIVE_MAIN] PRIMARY KEY ([GRPINC_ID]),
    CONSTRAINT [FK_GRPINC_GROUPID] FOREIGN KEY ([GRPINC_GROUPID]) REFERENCES [Group_Master]([GROUP_ID])
);

-- Table: GROUPINCENTIVE_DET - Group Incentive Detail Record (Per Employee)
CREATE TABLE [GROUPINCENTIVE_DET] (
    [GRPINCDET_ID] BIGINT NOT NULL,
    [GRPINCDET_MAINID] BIGINT NOT NULL,
    [GRPINCDET_EMPSYSID] BIGINT NOT NULL,
    [GRPINCDET_ALLOCPERCENTAGE] DECIMAL(5,2) NOT NULL,
    [GRPINCDET_ALLOCAMOUNT] DECIMAL(15,2) NOT NULL,
    [GRPINCDET_APPROVEDAMOUNT] DECIMAL(15,2) NULL,
    [GRPINCDET_APPSTATUS] CHAR(1) NOT NULL,
    [GRPINCDET_LASTMODIFIEDBY] BIGINT NOT NULL,
    [GRPINCDET_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_GROUPINCENTIVE_DET] PRIMARY KEY ([GRPINCDET_ID]),
    CONSTRAINT [FK_GRPINCDET_MAINID] FOREIGN KEY ([GRPINCDET_MAINID]) REFERENCES [GROUPINCENTIVE_MAIN]([GRPINC_ID]),
    CONSTRAINT [UQ_GRPINCDET] UNIQUE ([GRPINCDET_MAINID], [GRPINCDET_EMPSYSID])
);

-- Table: GROUPINCENTIVE_BREAK - Group Incentive Break Rules
CREATE TABLE [GROUPINCENTIVE_BREAK] (
    [GRPINCBRK_ID] INT NOT NULL,
    [GRPINCBRK_GROUPID] INT NOT NULL,
    [GRPINCBRK_ATTPERCENTAGE] DECIMAL(5,2) NOT NULL,
    [GRPINCBRK_INCPERCENTAGE] DECIMAL(5,2) NOT NULL,
    [GRPINCBRK_EFFDATE] DATETIME2(3) NOT NULL,
    [GRPINCBRK_CLSDATE] DATETIME2(3) NULL,
    [GRPINCBRK_LASTMODIFIEDBY] BIGINT NOT NULL,
    [GRPINCBRK_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_GROUPINCENTIVE_BREAK] PRIMARY KEY ([GRPINCBRK_ID]),
    CONSTRAINT [FK_GRPINCBRK_GROUPID] FOREIGN KEY ([GRPINCBRK_GROUPID]) REFERENCES [Group_Master]([GROUP_ID])
);

-- Table: GROUPINCENTIVE_APPROVAL - Group Incentive Approval History
CREATE TABLE [GROUPINCENTIVE_APPROVAL] (
    [GRPINCAPP_ID] BIGINT NOT NULL,
    [GRPINCAPP_MAINID] BIGINT NOT NULL,
    [GRPINCAPP_APPROVER] BIGINT NOT NULL,
    [GRPINCAPP_STATUS] CHAR(1) NOT NULL,
    [GRPINCAPP_REMARKS] VARCHAR(500) NULL,
    [GRPINCAPP_APPROVALDATE] DATETIME2(3) NOT NULL,
    [GRPINCAPP_LASTMODIFIEDBY] BIGINT NOT NULL,
    [GRPINCAPP_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_GROUPINCENTIVE_APPROVAL] PRIMARY KEY ([GRPINCAPP_ID]),
    CONSTRAINT [FK_GRPINCAPP_MAINID] FOREIGN KEY ([GRPINCAPP_MAINID]) REFERENCES [GROUPINCENTIVE_MAIN]([GRPINC_ID])
);

-- Create Indexes
CREATE INDEX [IX_Group_Master_STATUS] ON [Group_Master] ([GROUP_STATUS]);
CREATE INDEX [IX_GROUP_EMPLOYEEMAP_GROUPID] ON [GROUP_EMPLOYEEMAP] ([GRPEMPMAP_GROUPID]);
CREATE INDEX [IX_GROUP_EMPLOYEEMAP_EMPSYSID] ON [GROUP_EMPLOYEEMAP] ([GRPEMPMAP_EMPSYSID]);
CREATE INDEX [IX_GROUPINCENTIVE_MAIN_GROUPID] ON [GROUPINCENTIVE_MAIN] ([GRPINC_GROUPID]);
CREATE INDEX [IX_GROUPINCENTIVE_MAIN_APPSTATUS] ON [GROUPINCENTIVE_MAIN] ([GRPINC_APPSTATUS]);
CREATE INDEX [IX_GROUPINCENTIVE_DET_MAINID] ON [GROUPINCENTIVE_DET] ([GRPINCDET_MAINID]);
CREATE INDEX [IX_GROUPINCENTIVE_DET_APPSTATUS] ON [GROUPINCENTIVE_DET] ([GRPINCDET_APPSTATUS]);

PRINT '=== PHASE 2 COMPLETE: Tables Created ===';
GO

-- ==========================================
-- PHASE 3: Functions & Procedures
-- ==========================================

-- Function: fn_GetGroupTotalIncentive
CREATE OR ALTER FUNCTION dbo.fn_GetGroupTotalIncentive
(
    @p_GroupID INT,
    @p_Month INT,
    @p_Year INT
)
RETURNS DECIMAL(15,2)
DETERMINISTIC
AS
BEGIN
    DECLARE @TotalAmount DECIMAL(15,2) = 0;
    
    SELECT @TotalAmount = SUM(GRPINC_TOTALAMOUNT)
    FROM GROUPINCENTIVE_MAIN
    WHERE GRPINC_GROUPID = @p_GroupID
      AND GRPINC_INCMONTH = @p_Month
      AND GRPINC_INCYEAR = @p_Year
      AND GRPINC_APPSTATUS = 'Y';
    
    RETURN ISNULL(@TotalAmount, 0);
END;
GO

-- Function: fn_GetEmployeeGroupIncentiveAmount
CREATE OR ALTER FUNCTION dbo.fn_GetEmployeeGroupIncentiveAmount
(
    @p_EmployeeID BIGINT,
    @p_Month INT,
    @p_Year INT
)
RETURNS DECIMAL(15,2)
DETERMINISTIC
AS
BEGIN
    DECLARE @Amount DECIMAL(15,2) = 0;
    
    SELECT @Amount = SUM(GRPINCDET_APPROVEDAMOUNT)
    FROM GROUPINCENTIVE_DET gid
    INNER JOIN GROUPINCENTIVE_MAIN gim ON gid.GRPINCDET_MAINID = gim.GRPINC_ID
    WHERE gid.GRPINCDET_EMPSYSID = @p_EmployeeID
      AND gim.GRPINC_INCMONTH = @p_Month
      AND gim.GRPINC_INCYEAR = @p_Year
      AND gid.GRPINCDET_APPSTATUS = 'Y';
    
    RETURN ISNULL(@Amount, 0);
END;
GO

-- Procedure: usp_CreateGroupIncentive
CREATE OR ALTER PROCEDURE dbo.usp_CreateGroupIncentive
(
    @p_GroupID INT,
    @p_Month INT,
    @p_Year INT,
    @p_TotalAmount DECIMAL(15,2),
    @p_CreatedBy BIGINT,
    @p_IncentiveID BIGINT OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;
        
        IF NOT EXISTS (SELECT 1 FROM Group_Master WHERE GROUP_ID = @p_GroupID AND GROUP_STATUS = 'Y')
            THROW 50001, 'Group not found or inactive', 1;
        
        IF @p_TotalAmount < 0
            THROW 50002, 'Total amount cannot be negative', 1;
        
        SELECT @p_IncentiveID = ISNULL(MAX(GRPINC_ID), 0) + 1 FROM GROUPINCENTIVE_MAIN;
        
        INSERT INTO GROUPINCENTIVE_MAIN
        (GRPINC_ID, GRPINC_GROUPID, GRPINC_INCMONTH, GRPINC_INCYEAR, GRPINC_TOTALAMOUNT,
         GRPINC_APPSTATUS, GRPINC_ENTEREDON, GRPINC_ENTEREDBY, GRPINC_LASTMODIFIEDBY, GRPINC_LASTMODIFIEDON)
        VALUES (@p_IncentiveID, @p_GroupID, @p_Month, @p_Year, @p_TotalAmount,
                'P', GETDATE(), @p_CreatedBy, @p_CreatedBy, GETDATE());
        
        COMMIT TRANSACTION;
        PRINT 'Group incentive created: ID = ' + CAST(@p_IncentiveID AS VARCHAR);
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        RAISERROR('Group incentive creation failed: %s', 16, 1, ERROR_MESSAGE());
    END CATCH
END;
GO

-- Procedure: usp_ApproveGroupIncentive
CREATE OR ALTER PROCEDURE dbo.usp_ApproveGroupIncentive
(
    @p_IncentiveID BIGINT,
    @p_ApprovedAmount DECIMAL(15,2),
    @p_ApprovedBy BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;
        
        IF NOT EXISTS (SELECT 1 FROM GROUPINCENTIVE_MAIN WHERE GRPINC_ID = @p_IncentiveID)
            THROW 50003, 'Incentive record not found', 1;
        
        IF @p_ApprovedAmount < 0
            THROW 50004, 'Approved amount cannot be negative', 1;
        
        UPDATE GROUPINCENTIVE_MAIN
        SET GRPINC_APPSTATUS = 'Y',
            GRPINC_APPROVEDAMOUNT = @p_ApprovedAmount,
            GRPINC_APPROVER = @p_ApprovedBy,
            GRPINC_APPROVALDATE = GETDATE(),
            GRPINC_LASTMODIFIEDBY = @p_ApprovedBy,
            GRPINC_LASTMODIFIEDON = GETDATE()
        WHERE GRPINC_ID = @p_IncentiveID;
        
        INSERT INTO GROUPINCENTIVE_APPROVAL
        (GRPINCAPP_ID, GRPINCAPP_MAINID, GRPINCAPP_APPROVER, GRPINCAPP_STATUS, GRPINCAPP_APPROVALDATE, GRPINCAPP_LASTMODIFIEDBY, GRPINCAPP_LASTMODIFIEDON)
        SELECT ISNULL(MAX(GRPINCAPP_ID), 0) + 1, @p_IncentiveID, @p_ApprovedBy, 'Y', GETDATE(), @p_ApprovedBy, GETDATE()
        FROM GROUPINCENTIVE_APPROVAL;
        
        COMMIT TRANSACTION;
        PRINT 'Group incentive approved: ID = ' + CAST(@p_IncentiveID AS VARCHAR);
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        RAISERROR('Group incentive approval failed: %s', 16, 1, ERROR_MESSAGE());
    END CATCH
END;
GO

PRINT '=== PHASE 3 COMPLETE: Functions and Procedures Created ===';
GO

-- ==========================================
-- PHASE 4: Verification Views
-- ==========================================
CREATE VIEW vw_GroupIncentiveDB_Status AS
SELECT 
    'GROUPINCENTIVEDB' AS DatabaseName,
    'Group Incentive Management Module' AS ModuleDescription,
    (SELECT COUNT(*) FROM Group_Master WHERE GROUP_STATUS = 'Y') AS ActiveGroups,
    (SELECT COUNT(*) FROM GROUP_EMPLOYEEMAP) AS GroupEmployees,
    (SELECT COUNT(*) FROM GROUPINCENTIVE_MAIN WHERE GRPINC_APPSTATUS = 'P') AS PendingIncentives,
    (SELECT ISNULL(SUM(GRPINC_APPROVEDAMOUNT), 0) FROM GROUPINCENTIVE_MAIN WHERE GRPINC_APPSTATUS = 'Y') AS TotalApprovedAmount,
    GETDATE() AS LastChecked;
GO

PRINT '=== PHASE 4 COMPLETE: Views Created ===';
GO

-- ==========================================
-- PHASE 5: Final Verification
-- ==========================================
PRINT '=== PHASE 5: FINAL VERIFICATION ===';
SELECT 'System Tables' AS Object_Type, COUNT(*) AS Count FROM sys.tables;
SELECT 'Indexes' AS Object_Type, COUNT(*) AS Count FROM sys.indexes WHERE object_id > 0;
SELECT 'Procedures' AS Object_Type, COUNT(*) AS Count FROM sys.objects WHERE type = 'P';
SELECT 'Functions' AS Object_Type, COUNT(*) AS Count FROM sys.objects WHERE type = 'FN';
SELECT 'Views' AS Object_Type, COUNT(*) AS Count FROM sys.views;

PRINT '======================================';
PRINT 'GROUPINCENTIVEDB DEPLOYMENT COMPLETE';
PRINT '======================================';
PRINT 'Database: GROUPINCENTIVEDB';
PRINT 'Tables: 7';
PRINT 'Indexes: 7';
PRINT 'Procedures: 2';
PRINT 'Functions: 2';
PRINT 'Views: 1';
PRINT 'Status: READY FOR DEPLOYMENT';
PRINT '======================================';
GO
