-- ==========================================
-- LEAVE MODULE - Schema
-- Database: LETDB
-- Purpose: Leave Management & Encashment
-- Created: March 9, 2026
-- ==========================================

USE LETDB;
GO

-- ==========================================
-- LEAVE MODULE - Main Core Tables
-- ==========================================

-- Table: LET_MAIN - Leave Request Main
CREATE TABLE [LET_MAIN] (
    [REQ_NUM] BIGINT NOT NULL PRIMARY KEY,
    [FINYEAR_SRLNO] INT NOT NULL,
    [EMP_USERID] VARCHAR(25) NOT NULL,
    [SUP_USERID] VARCHAR(25) NULL,
    [REQ_DATE] DATETIME2(3) NULL
);

-- Table: LET_SUB - Leave Request Details
CREATE TABLE [LET_SUB] (
    [LS_REQ_NUM] BIGINT NOT NULL,
    [LS_SRL_NUM] INT NOT NULL PRIMARY KEY,
    [LS_MOD_DAT] DATETIME2(3) NULL,
    [LS_MOD_USER] VARCHAR(25) NULL,
    [LS_PREF_MODDEV] CHAR(1) NULL,
    [LS_ACT_TAKEN] VARCHAR(200) NULL,
    [LS_CRS_ID] INT NULL,
    [LS_TRNPRG_BHR] VARCHAR(200) NULL,
    [LS_IMPBEN_PRO] VARCHAR(200) NULL,
    [LS_MEASURE_CP] VARCHAR(200) NULL,
    [LS_MIDYER_REVNAM] VARCHAR(200) NULL,
    [LS_MIDYER_REVDAT] VARCHAR(200) NULL,
    [LS_MIDYER_REVREM] VARCHAR(200) NULL,
    [LS_ANNYER_REVNAM] VARCHAR(200) NULL,
    [LS_ANNYER_REVDAT] VARCHAR(200) NULL,
    [LS_ANNYER_REVREM] VARCHAR(200) NULL,
    [LS_COMP_DEV] INT NULL,
    [LS_DOMKNOW_DEV] VARCHAR(255) NULL,
    [LS_DOMKNOW_DEV_DET] VARCHAR(255) NULL,
    [LS_PROCES_DEV] VARCHAR(255) NULL,
    [LS_PROCES_DEV_DET] VARCHAR(255) NULL,
    [LS_LETSUB_CODE] CHAR(1) NULL,
    [LS_REV_TYPE] VARCHAR(255) NULL,
    CONSTRAINT [FK_LET_SUB_LET_MAIN] FOREIGN KEY ([LS_REQ_NUM]) REFERENCES [LET_MAIN]([REQ_NUM])
);

-- ==========================================
-- LEAVE ENCASHMENT TABLES (Missing from original schema)
-- ==========================================

-- Table: LEAVE_ENCASHMENT
CREATE TABLE [LEAVE_ENCASHMENT] (
    [ENCASHMENT_ID] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
    [EMP_SYS_ID] BIGINT NOT NULL,
    [LEAVE_TYPE] VARCHAR(20) NOT NULL,
    [ENCASHMENT_DAYS] INT NOT NULL,
    [ENCASHMENT_AMOUNT] DECIMAL(19,2) NOT NULL,
    [REQUEST_DATE] DATE NOT NULL,
    [ENCASHMENT_STATUS] CHAR(1) NOT NULL DEFAULT 'P',
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [MODIFIED_ON] DATETIME2(3) NULL,
    [MODIFIED_BY] BIGINT NULL
);

-- Table: LOSS_OF_PAY
CREATE TABLE [LOSS_OF_PAY] (
    [LOP_ID] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
    [EMP_SYS_ID] BIGINT NOT NULL,
    [LOP_DAYS] INT NOT NULL,
    [LOP_MONTH] DATE NOT NULL,
    [LOP_REMARKS] VARCHAR(500) NULL,
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [MODIFIED_ON] DATETIME2(3) NULL,
    [MODIFIED_BY] BIGINT NULL
);

-- ==========================================
-- LEAVE COUNTER TABLE
-- ==========================================

-- Table: LET_COUNTERS
CREATE TABLE [LET_COUNTERS] (
    [LT_TYP_COD] CHAR(3) NOT NULL PRIMARY KEY,
    [LT_CNT_NUM] BIGINT NULL,
    [LT_CNT_DES] VARCHAR(65) NULL
);

-- ==========================================
-- LEAVE MODEL & SIGNATURE TABLE
-- ==========================================

-- Table: LET_MODEL
CREATE TABLE [LET_MODEL] (
    [LT_SKL_COD] BIGINT NOT NULL,
    [LT_LVL_NUM] BIGINT NOT NULL,
    [LT_FNC_COD] CHAR(3) NOT NULL,
    [LT_JOB_COD] BIGINT NOT NULL,
    CONSTRAINT [PK_LET_MODEL] PRIMARY KEY ([LT_SKL_COD], [LT_LVL_NUM])
);

-- Table: LET_SIGID - Leave Signature IDs
CREATE TABLE [LET_SIGID] (
    [LET_SIGID] VARCHAR(100) NULL,
    [SIG_NAME] VARCHAR(50) NULL,
    [SIG_DESG] VARCHAR(10) NULL
);

-- ==========================================
-- LEAVE PLANNING TRACKER TABLES
-- ==========================================

-- Table: LETPLAN_MANHOUR
CREATE TABLE [LETPLAN_MANHOUR] (
    [LET_USR_ID] VARCHAR(65) NULL,
    [LET_USR_PIN] DECIMAL(20,0) NULL,
    [LET_BUS_COD] VARCHAR(9) NULL,
    [LET_BUS_NAM] VARCHAR(65) NULL,
    [LET_COM_COD] VARCHAR(3) NULL,
    [LET_COM_NAM] VARCHAR(65) NULL,
    [LET_APR] BIGINT NULL,
    [LET_MAY] BIGINT NULL,
    [LET_JUN] BIGINT NULL,
    [LET_JUL] BIGINT NULL,
    [LET_AUG] BIGINT NULL,
    [LET_SEP] BIGINT NULL,
    [LET_OCT] BIGINT NULL,
    [LET_NOV] BIGINT NULL,
    [LET_DEC] BIGINT NULL,
    [LET_JAN] BIGINT NULL,
    [LET_FEB] BIGINT NULL,
    [LET_MAR] BIGINT NULL
);

-- Table: LETPLAN_TRACKER
CREATE TABLE [LETPLAN_TRACKER] (
    [LET_USR_ID] VARCHAR(65) NULL,
    [LET_USR_PIN] DECIMAL(20,0) NULL,
    [LET_BUS_COD] VARCHAR(9) NULL,
    [LET_BUS_NAM] VARCHAR(65) NULL,
    [LET_COM_COD] VARCHAR(3) NULL,
    [LET_COM_NAM] VARCHAR(65) NULL,
    [LET_TOT_PLAN] BIGINT NULL,
    [LET_COURSE_ATTEN] BIGINT NULL,
    [LET_NOT_ATTEN] BIGINT NULL,
    [LET_FED_GIVEN] BIGINT NULL,
    [LET_FED_NOTGIVEN] BIGINT NULL,
    [LET_REV_PEN] BIGINT NULL,
    [REV_COMP] BIGINT NULL,
    [LE_FED1] BIGINT NULL,
    [LET_FED2] BIGINT NULL
);

-- Table: LETPLANDRILL_TRACKER
CREATE TABLE [LETPLANDRILL_TRACKER] (
    [LET_USR_ID] VARCHAR(65) NULL,
    [LET_USR_PIN] DECIMAL(20,0) NULL,
    [LET_BUS_COD] VARCHAR(9) NULL,
    [LET_COM_COD] VARCHAR(3) NULL,
    [EM_USR_ID] VARCHAR(100) NULL,
    [CS_CRS_DESC] VARCHAR(4000) NULL,
    [CS_STRDAT] VARCHAR(100) NULL,
    [CS_NOM_NUM] VARCHAR(100) NULL,
    [CS_REQNUM] VARCHAR(100) NULL,
    [CS_USR_PIN] VARCHAR(100) NULL,
    [EM_OEML_ID] VARCHAR(100) NULL,
    [EM_USR_ID1] VARCHAR(100) NULL,
    [AP_USR_ID] VARCHAR(100) NULL,
    [SC_COM_NAM] VARCHAR(100) NULL
);

-- ==========================================
-- INDEXES FOR LEAVE MODULE
-- ==========================================

CREATE INDEX [IDX_LEAVE_MAIN_EMP_USERID] ON [LET_MAIN]([EMP_USERID]);
CREATE INDEX [IDX_LEAVE_SUB_REQ_NUM] ON [LET_SUB]([LS_REQ_NUM]);
CREATE INDEX [IDX_LEAVE_ENCASHMENT_EMP_ID] ON [LEAVE_ENCASHMENT]([EMP_SYS_ID]);
CREATE INDEX [IDX_LOSS_OF_PAY_EMP_ID] ON [LOSS_OF_PAY]([EMP_SYS_ID]);
CREATE INDEX [IDX_LETPLAN_TRACKER_USR_ID] ON [LETPLAN_TRACKER]([LET_USR_ID]);

PRINT 'Leave Module Schema created successfully.';
GO
