-- Module: Document
USE DDDB;
GO

-- Table: DDLETTER_LOGHISTORY
CREATE TABLE [DDLETTER_LOGHISTORY] (
    [DDLETTER_LOGSYSID] DECIMAL(38) NOT NULL,
    [DDLETTER_IPADDRESS] VARCHAR(100) NOT NULL,
    [DDLETTER_OPENEDON] DATETIME2(3) NOT NULL,
    [DDLETTER_FINYEARID] DECIMAL(38) NULL,
    [DDLETTER_EMPSYSID] DECIMAL(38) NULL,
    [DDLETTER_TYPE] VARCHAR(3) NULL
);



-- Table: DD_ANNEXURE1
CREATE TABLE [DD_ANNEXURE1] (
    [DD_CRT_PIN] DECIMAL(38) NULL  -- Entry User Pin Number,
    [DD_USR_PIN] DECIMAL(38) NULL  -- User Pin Number,
    [DD_USR_NAM] VARCHAR(150) NULL  -- User Name,
    [DD_AN1_PR1] VARCHAR(1000) NULL  -- Answer 1,
    [DD_AN2_PR2] VARCHAR(1000) NULL  -- Answer 2,
    [DD_AN3_PR3] VARCHAR(1000) NULL  -- Answer 3,
    [DD_SIG_NAM] VARCHAR(150) NULL  -- Signatory Name,
    [DD_SIG_DSG] VARCHAR(100) NULL  -- Signatory Desgination,
    [DD_USR_RNM] VARCHAR(150) NULL  -- Uner Random Number,
    [DD_USR_UNT] VARCHAR(50) NULL  -- User Unit Code,
    [DD_PRN_DAT] DATETIME2(3) NULL  -- Print Date,
    [DD_AN4_PR4] VARCHAR(1000) NULL  -- Answer 4,
    [DD_APR_LMP] DECIMAL(38) NULL,
    [DD_APR_BAS] DECIMAL(38) NULL  -- Appraisal Basic Pay,
    [DD_APR_FLX] DECIMAL(38) NULL  -- Appraiser Flexi Pay,
    [DD_EFF_DAT] DATETIME2(3) NULL  -- Effective Date
);



-- Table: DD_ANNEXURE2
CREATE TABLE [DD_ANNEXURE2] (
    [DD_CRT_PIN] DECIMAL(38) NULL,
    [DD_USR_PIN] DECIMAL(38) NULL  -- User Pin No,
    [DD_USR_NAM] VARCHAR(150) NULL  -- User Name,
    [DD_BAS_OLD] DECIMAL(38) NULL  -- Basic Old,
    [DD_BAS_NEW] DECIMAL(38) NULL  -- Basic New,
    [DD_FLX_PAY] DECIMAL(38) NULL  -- Flexi Pay New,
    [DD_SIG_NAM] VARCHAR(150) NULL  -- Signatory name,
    [DD_SIG_DSG] VARCHAR(100) NULL  -- Signatory Designation,
    [DD_EFF_DAT] DATETIME2(3) NULL  -- Effective Date,
    [DD_PRN_DAT] VARCHAR(20) NULL  -- Print Date,
    [DD_BND_NAM] VARCHAR(1) NULL  -- Band Name
);



-- Table: DD_APPRAISALLETTER
CREATE TABLE [DD_APPRAISALLETTER] (
    [DD_SRL_NO] DECIMAL(38) NOT NULL  -- Serial No,
    [DD_APR_BND] DECIMAL(38) NULL  -- O , A , B , C , D,
    [DD_APR_TYP] CHAR(3) NULL  -- APR - Appraisal Letter, AN1 - Annexure 1, AN2 - Annexure 2,
    [DD_APR_FRM] DATETIME2(3) NULL  -- Appraisal From Date,
    [DD_APR_END] DATETIME2(3) NULL  -- Appraisal To Date,
    [DD_APR_PR1] VARCHAR(1000) NULL  -- Paragraph 1,
    [DD_APR_PR2] VARCHAR(1000) NULL  -- Paragraph 2,
    [DD_APR_PR3] VARCHAR(1000) NULL  -- Paragraph 3,
    [DD_APR_PR4] VARCHAR(1000) NULL  -- Paragraph 4,
    [DD_APR_PR5] VARCHAR(1000) NULL  -- Paragraph 5,
    [DD_EFF_DAT] DATETIME2(3) NULL  -- Effective Date,
    [DD_BAS_DAT] DATETIME2(3) NULL  -- Basic Pay Effective Date,
    [DD_PRN_DAT] DATETIME2(3) NULL  -- Print date,
    CONSTRAINT [PK_DD_APPRAISALLETTER] PRIMARY KEY ([DD_SRL_NO])
);



-- Table: DD_APPRAISALLETTER_NEW
CREATE TABLE [DD_APPRAISALLETTER_NEW] (
    [DD_SRL_NO] DECIMAL(38) NOT NULL,
    [DD_APR_BND] DECIMAL(38) NULL,
    [DD_APR_TYP] VARCHAR(9) NULL,
    [DD_APR_FRM] DATETIME2(3) NULL,
    [DD_APR_END] DATETIME2(3) NULL,
    [DD_APR_PR1] VARCHAR(1000) NULL,
    [DD_APR_PR2] VARCHAR(1000) NULL,
    [DD_APR_PR3] VARCHAR(1000) NULL,
    [DD_APR_PR4] VARCHAR(1000) NULL,
    [DD_APR_PR5] VARCHAR(1000) NULL,
    [DD_EFF_DAT] DATETIME2(3) NULL,
    [DD_BAS_DAT] DATETIME2(3) NULL,
    [DD_PRN_DAT] DATETIME2(3) NULL,
    [DD_APR_PR6] VARCHAR(1000) NULL,
    [DD_LET_TYP] VARCHAR(3) NULL
);



-- Table: DD_GENERATELETTER
CREATE TABLE [DD_GENERATELETTER] (
    [DD_CRT_PIN] DECIMAL(38) NULL  -- Entry User Pin Number,
    [DD_USR_PIN] DECIMAL(38) NULL  -- User Pin Number,
    [DD_USR_NAM] VARCHAR(150) NULL  -- User Name,
    [DD_SIG_NAM] VARCHAR(150) NULL  -- Signatory Name,
    [DD_SIG_DSG] VARCHAR(100) NULL  -- Signatory Desgination,
    [DD_USR_RNM] VARCHAR(150) NULL  -- User Random Number,
    [DD_USR_UNT] VARCHAR(50) NULL  -- User Unit Code,
    [DD_PRN_DAT] DATETIME2(3) NULL  -- Print Date,
    [DD_APR_LMP] DECIMAL(38) NULL,
    [DD_APR_BAS] DECIMAL(38) NULL  -- Appraisal Basic Pay,
    [DD_APR_FLX] DECIMAL(38) NULL  -- Appraiser Flexi Pay,
    [DD_EFF_DAT] DATETIME2(3) NULL  -- Effective Date,
    [DD_LETTERTYPE] VARCHAR(10) NULL  -- Letter Type,
    [DD_FINALRATING] VARCHAR(5) NULL,
    [DD_APR_INC] DECIMAL(38) NULL,
    [DD_PRM_LEVEL] DECIMAL(38) NULL,
    [DD_APR_DSG] VARCHAR(100) NULL,
    [DD_APR_BND] VARCHAR(50) NULL,
    [DD_SIG_NAM2] VARCHAR(150) NULL,
    [DD_SIG_DSG2] VARCHAR(100) NULL,
    [DD_INC_TEMPID] DECIMAL(38) NULL,
    [DD_RAT_TEMPID] DECIMAL(38) NULL
);



-- Table: DD_SIGNATORY
CREATE TABLE [DD_SIGNATORY] (
    [DD_SIG_NUM] DECIMAL(38) NOT NULL  -- Serial No,
    [DD_SIG_NAM] VARCHAR(200) NULL  -- Signatory Name,
    [DD_SIG_DSG] VARCHAR(200) NULL  -- Signatory Designation,
    [DD_LIVE_FLG] VARCHAR(1) NULL,
    [DD_EMPSYSID] DECIMAL(38) NULL  -- Employee SysId,
    [DD_SIG_IMG] VARCHAR(50) NULL  -- Signatory Image,
    [DD_DIGITALSIGN_PFXFILENAME] VARCHAR(200) NULL,
    [DD_DIGITALSIGN_PFXPASSWORD] VARCHAR(100) NULL,
    [DD_SIG_IMGALT] VARCHAR(50) NULL,
    CONSTRAINT [PK_DD_SIGNATORY] PRIMARY KEY ([DD_SIG_NUM])
);

