// <auto-generated />
using System;
using BankService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BankDbContext))]
    partial class BankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankService.Domain.Entities.BankAccount", b =>
                {
                    b.Property<long>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ACCOUNT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AccountId"));

                    b.Property<decimal>("AccountBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(19,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ACCOUNT_BALANCE");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ACCOUNT_NUMBER");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("ACCOUNT_STATUS")
                        .IsFixedLength();

                    b.Property<string>("AccountTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ACCOUNT_TITLE");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ACCOUNT_TYPE");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)")
                        .HasColumnName("BANK_CODE")
                        .IsFixedLength();

                    b.Property<DateTime?>("ClosingDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CLOSING_DATE");

                    b.Property<DateTime>("OpeningDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("OPENING_DATE");

                    b.Property<string>("TrustCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("TRUST_CODE")
                        .IsFixedLength();

                    b.HasKey("AccountId");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("TrustCode", "AccountStatus")
                        .HasDatabaseName("IDX_BANK_ACCOUNT_TRUST");

                    b.ToTable("BANK_ACCOUNT", (string)null);
                });

            modelBuilder.Entity("BankService.Domain.Entities.BankMaster", b =>
                {
                    b.Property<string>("BankTrustCode")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("BANK_TRUST_CODE")
                        .IsFixedLength();

                    b.Property<string>("BankCode")
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)")
                        .HasColumnName("BANK_CODE")
                        .IsFixedLength();

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("nchar(65)")
                        .HasColumnName("BANK_NAME")
                        .IsFixedLength();

                    b.Property<string>("BranchAddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BRANCH_ADDRESS_LINE_1");

                    b.Property<string>("BranchAddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BRANCH_ADDRESS_LINE_2");

                    b.Property<string>("BranchAddressLine3")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BRANCH_ADDRESS_LINE_3");

                    b.Property<string>("BranchAddressLine4")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BRANCH_ADDRESS_LINE_4");

                    b.Property<DateTime?>("BranchClsDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("BRANCH_CLS_DATE");

                    b.Property<DateTime>("BranchEffDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("BRANCH_EFF_DATE");

                    b.Property<string>("BranchFaxNo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BRANCH_FAX_NO");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)")
                        .HasColumnName("BRANCH_NAME");

                    b.Property<string>("BranchPhoneNo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BRANCH_PHONE_NO");

                    b.Property<string>("BranchStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("BRANCH_STATUS")
                        .IsFixedLength();

                    b.Property<string>("MicrCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nchar(9)")
                        .HasColumnName("MICR_CODE")
                        .IsFixedLength();

                    b.HasKey("BankTrustCode", "BankCode");

                    b.HasIndex("BankTrustCode", "BranchStatus")
                        .HasDatabaseName("IDX_BANK_MASTER_TRUST");

                    b.ToTable("BANK_MASTER", (string)null);
                });

            modelBuilder.Entity("BankService.Domain.Entities.ChequeDetail", b =>
                {
                    b.Property<long>("ChequeId")
                        .HasColumnType("bigint")
                        .HasColumnName("CHEQUE_ID");

                    b.Property<long?>("ChequeActranNo")
                        .HasColumnType("bigint")
                        .HasColumnName("CHEQUE_ACTRAN_NO");

                    b.Property<decimal?>("ChequeAmount")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("CHEQUE_AMOUNT");

                    b.Property<long?>("ChequeBank")
                        .HasColumnType("bigint")
                        .HasColumnName("CHEQUE_BANK");

                    b.Property<string>("ChequeBranch")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CHEQUE_BRANCH");

                    b.Property<DateTime?>("ChequeClearedDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CHEQUE_CLEARED_DATE");

                    b.Property<DateTime?>("ChequeDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CHEQUE_DATE");

                    b.Property<decimal?>("ChequeNo")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("CHEQUE_NO");

                    b.Property<string>("ChequePayee")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CHEQUE_PAYEE");

                    b.Property<string>("ChequeRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CHEQUE_REMARKS");

                    b.Property<string>("ChequeStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasDefaultValue("I")
                        .HasColumnName("CHEQUE_STATUS")
                        .IsFixedLength();

                    b.HasKey("ChequeId");

                    b.HasIndex("ChequeStatus", "ChequeDate")
                        .HasDatabaseName("IDX_CHEQUE_DET_STATUS");

                    b.ToTable("CHEQUE_DET", (string)null);
                });

            modelBuilder.Entity("BankService.Domain.Entities.ChequeRegister", b =>
                {
                    b.Property<long>("RegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("REGISTER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RegisterId"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("ACCOUNT_ID");

                    b.Property<string>("ChequeBookId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CHEQUE_BOOK_ID");

                    b.Property<decimal>("ChequeNoFrom")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("CHEQUE_NO_FROM");

                    b.Property<decimal>("ChequeNoTo")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("CHEQUE_NO_TO");

                    b.Property<DateTime>("IssuedDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("ISSUED_DATE");

                    b.Property<string>("RegisterStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("REGISTER_STATUS")
                        .IsFixedLength();

                    b.HasKey("RegisterId");

                    b.HasIndex("AccountId", "RegisterStatus")
                        .HasDatabaseName("IDX_CHEQUE_REGISTER_ACCOUNT");

                    b.ToTable("CHEQUE_REGISTER", (string)null);
                });

            modelBuilder.Entity("BankService.Domain.Entities.PaymentReconciliation", b =>
                {
                    b.Property<long>("ReconId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RECON_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReconId"));

                    b.Property<long>("ChequeId")
                        .HasColumnType("bigint")
                        .HasColumnName("CHEQUE_ID");

                    b.Property<decimal>("ReconAmount")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("RECON_AMOUNT");

                    b.Property<DateTime>("ReconDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("RECON_DATE");

                    b.Property<string>("ReconReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RECON_REFERENCE");

                    b.Property<string>("ReconStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasDefaultValue("O")
                        .HasColumnName("RECON_STATUS")
                        .IsFixedLength();

                    b.HasKey("ReconId");

                    b.HasIndex("ChequeId")
                        .IsUnique();

                    b.ToTable("PAYMENT_RECONCILIATION", (string)null);
                });

            modelBuilder.Entity("BankService.Domain.Entities.ChequeRegister", b =>
                {
                    b.HasOne("BankService.Domain.Entities.BankAccount", "Account")
                        .WithMany("ChequeRegisters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CHEQUE_REGISTER_ACCOUNT");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BankService.Domain.Entities.PaymentReconciliation", b =>
                {
                    b.HasOne("BankService.Domain.Entities.ChequeDetail", "Cheque")
                        .WithOne("Reconciliation")
                        .HasForeignKey("BankService.Domain.Entities.PaymentReconciliation", "ChequeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PAYMENT_RECON_CHEQUE");

                    b.Navigation("Cheque");
                });

            modelBuilder.Entity("BankService.Domain.Entities.BankAccount", b =>
                {
                    b.Navigation("ChequeRegisters");
                });

            modelBuilder.Entity("BankService.Domain.Entities.ChequeDetail", b =>
                {
                    b.Navigation("Reconciliation");
                });
#pragma warning restore 612, 618
        }
    }
}
