-- ExitManagement Module - Tables
USE [HRDB];
GO

-- Table: EMPLOYEE_EXIT_INT
CREATE TABLE [EMPLOYEE_EXIT_INT] (
    [INT_EXITNO] DECIMAL(38) NOT NULL  -- Employee System ID,
    [INT_SLNO] DECIMAL(38) NOT NULL  -- Serial No,
    [INT_QUES_ID] CHAR(4) NULL  -- Question ID for Feedback,
    [INT_FEEDBACK] VARCHAR(1000) NULL  -- Remarks,
    [INT_UPDATED_BY] DECIMAL(38) NULL  -- Last updated by,
    [INT_UPDATED_ON] DATETIME2(3) NULL  -- Last updated on,
    CONSTRAINT [PK_EMPLOYEE_EXIT_INT] PRIMARY KEY ([INT_EXITNO])
);



-- Table: TTBT_EXIT_TEV
CREATE TABLE [TTBT_EXIT_TEV] (
    [EXIT_NO] DECIMAL(38) NULL,
    [EXIT_EMP_SYSID] DECIMAL(38) NOT NULL,
    [EXIT_LET_GIVON] DATETIME2(3) NULL,
    [EXIT_EXP_RELDT] DATETIME2(3) NULL,
    [EXIT_RES_TYPE] VARCHAR(25) NULL,
    [EXIT_RES_ID] DECIMAL(38) NOT NULL,
    [EXIT_REMARKS] VARCHAR(300) NULL,
    [EXIT_STATUS] CHAR(1) NULL,
    [EXIT_REL_GIVON] DATETIME2(3) NULL,
    [EXIT_INTCONDON] DATETIME2(3) NULL,
    [EXIT_INTCONDBY] VARCHAR(200) NULL,
    [EXIT_REVOKE_REASON] VARCHAR(300) NULL,
    [EXIT_REVOKE_DATE] DATETIME2(3) NULL,
    [EXIT_UPDATED_BY] DECIMAL(38) NULL,
    [EXIT_UPDATED_ON] DATETIME2(3) NULL,
    [EXIT_SIGN_ID] DECIMAL(38) NULL,
    [EXIT_REVOKE_RESIGNATION] CHAR(1) NULL,
    [EXIT_PAYROLL_SETTLEMENT] CHAR(1) NULL,
    [EXIT_STOPSAL_DATE] DATETIME2(3) NULL,
    [EXIT_NEXTOFFICER] DECIMAL(38) NULL,
    [EXIT_SETTYPEID] DECIMAL(38) NULL,
    [EXIT_MAILDIS_DATE] DATETIME2(3) NULL,
    [EXIT_MAILDEL_DATE] DATETIME2(3) NULL,
    [EXIT_MAILFWD_SYSID] DECIMAL(22,0) NULL,
    [EXIT_FORMALITYBY] DECIMAL(22,0) NULL,
    [EXIT_FORMALITYON] DATETIME2(3) NULL,
    [EXIT_USERCONFSTATUS] CHAR(1) NULL,
    [EXIT_BYPASSFORMALITY] CHAR(1) NULL,
    [EXIT_APPSTATUS] CHAR(1) NULL,
    [EXIT_APPBY] DECIMAL(22,0) NULL,
    [EXIT_APPON] DATETIME2(3) NULL,
    [EXIT_NOTDATE] DATETIME2(3) NULL,
    [EXIT_MAILSTATUS] CHAR(1) NULL,
    [EXIT_CHKSTATUS] CHAR(1) NULL,
    [EXIT_LSNO] DECIMAL(22,0) NULL,
    [EXIT_FSNO] DECIMAL(22,0) NULL,
    [EXIT_FSBY] DECIMAL(22,0) NULL,
    [EXIT_FSON] DATETIME2(3) NULL,
    [EXIT_NPP] DECIMAL(38) NULL,
    [EXIT_MAILTOUSER] CHAR(1) NULL,
    [EXIT_CONDUCTDESC] VARCHAR(500) NULL,
    [EXIT_JVBATCHID] DECIMAL(38) NULL,
    [EXIT_JVPOSTEDBY] DECIMAL(38) NULL,
    [EXIT_JVPOSTEDON] DATETIME2(3) NULL,
    [EXIT_DESGONJOINING] VARCHAR(100) NULL,
    [EXIT_REASONFORLEAVING] VARCHAR(100) NULL
);



-- Table: TT_EXIT_QUESTIONS
CREATE TABLE [TT_EXIT_QUESTIONS] (
    [QUESTION_ID] VARCHAR(4) NULL,
    [QUESTION_DESC] VARCHAR(500) NULL,
    [QUESTION_ORDER] DECIMAL(22,0) NULL
);



-- Table: TT_EXIT_INTERVIEW
CREATE TABLE [TT_EXIT_INTERVIEW] (
    [QUESTION_ID] CHAR(3) NULL,
    [QUESTION_DESC] VARCHAR(500) NULL,
    [ORDER_ID] DECIMAL(38) NULL
);



-- Table: TT_EMPLOYEE_EXITRESPEX
CREATE TABLE [TT_EMPLOYEE_EXITRESPEX] (
    [TT_ID] DECIMAL(22,0) NULL,
    [TT_SYSID] DECIMAL(22,0) NULL,
    [TT_CHKMAPID] DECIMAL(22,0) NULL,
    [TT_PRI] VARCHAR(30) NULL,
    [TT_SEC] VARCHAR(30) NULL,
    [TT_FHEAD] VARCHAR(30) NULL
);

