-- ==========================================
-- TOURDB Tables - Docker Initialization
-- All tables for Tour ERP Microservices
-- ==========================================

USE TOURDB;
GO

-- ══════════════════════════════════════════
-- ADMIN MODULE
-- ══════════════════════════════════════════

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ADMIN_MASTER')
CREATE TABLE [ADMIN_MASTER] (
    [ADMIN_ID] VARCHAR(255) NOT NULL,
    [ADMIN_NAME] VARCHAR(255) NOT NULL,
    [ADMIN_PIC] VARCHAR(255) NOT NULL,
    [ADMIN_UNITID] VARCHAR(255) NOT NULL,
    [ADMIN_UNITHEADSYSID] VARCHAR(255) NOT NULL,
    [ADMIN_LOCSTATUS] CHAR(1) NULL,
    CONSTRAINT [PK_ADMIN_MASTER] PRIMARY KEY ([ADMIN_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ADMIN_USERMAP')
CREATE TABLE [ADMIN_USERMAP] (
    [ADMIN_MAPID] VARCHAR(255) NOT NULL,
    [ADMIN_BOOKTYPE] VARCHAR(255) NOT NULL,
    [ADMIN_MODE] VARCHAR(255) NOT NULL,
    [ADMIN_EMPSYSID] VARCHAR(255) NOT NULL,
    [ADMIN_ID] VARCHAR(255) NOT NULL,
    [ADMIN_LASTMODIFIEDBY] VARCHAR(255) NOT NULL,
    [ADMIN_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_ADMIN_USERMAP] PRIMARY KEY ([ADMIN_MAPID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ADMIN_FINUSERMAP')
CREATE TABLE [ADMIN_FINUSERMAP] (
    [FINANCE_MAPID] VARCHAR(255) NOT NULL,
    [FINANCE_PAYUNITID] VARCHAR(255) NOT NULL,
    [FINANCE_EMPSYSID] VARCHAR(255) NOT NULL,
    [FINANCE_LASTMODIFIEDBY] VARCHAR(255) NULL,
    [FINANCE_LASTMODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_ADMIN_FINUSERMAP] PRIMARY KEY ([FINANCE_MAPID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ADMIN_ACCESSRIGHTS')
CREATE TABLE [ADMIN_ACCESSRIGHTS] (
    [AR_ID] BIGINT IDENTITY(1,1) NOT NULL,
    [AR_EMPSYSID] VARCHAR(255) NOT NULL,
    [AR_MODULE] VARCHAR(100) NOT NULL,
    [AR_PERMISSION] VARCHAR(50) NOT NULL,
    [AR_GRANTEDBY] VARCHAR(255) NOT NULL,
    [AR_GRANTEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_ADMIN_ACCESSRIGHTS] PRIMARY KEY ([AR_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ADMIN_ACCESSRIGHTSLOG')
CREATE TABLE [ADMIN_ACCESSRIGHTSLOG] (
    [ARL_ID] BIGINT IDENTITY(1,1) NOT NULL,
    [ARL_ARID] BIGINT NOT NULL,
    [ARL_ACTION] VARCHAR(50) NOT NULL,
    [ARL_CHANGEDBY] VARCHAR(255) NOT NULL,
    [ARL_CHANGEDON] DATETIME2(3) NOT NULL,
    [ARL_OLDVALUE] NVARCHAR(MAX) NULL,
    [ARL_NEWVALUE] NVARCHAR(MAX) NULL,
    CONSTRAINT [PK_ADMIN_ACCESSRIGHTSLOG] PRIMARY KEY ([ARL_ID])
);
GO

-- ══════════════════════════════════════════
-- BOOKING MODULE
-- ══════════════════════════════════════════

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BOOKREQUEST_MAIN')
CREATE TABLE [BOOKREQUEST_MAIN] (
    [BOOK_ID] BIGINT NOT NULL,
    [BOOK_TPID] BIGINT NOT NULL,
    [BOOK_TYPE] VARCHAR(10) NOT NULL,
    [BOOK_EMPSYSID] VARCHAR(255) NOT NULL,
    [BOOK_STATUS] CHAR(1) NULL,
    [BOOK_REMARKS] VARCHAR(500) NULL,
    [BOOK_CREATEDBY] VARCHAR(255) NULL,
    [BOOK_CREATEDON] DATETIME2(3) NULL,
    [BOOK_LASTMODIFIEDBY] VARCHAR(255) NULL,
    [BOOK_LASTMODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_BOOKREQUEST_MAIN] PRIMARY KEY ([BOOK_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BOOKREQUEST_TICKET')
CREATE TABLE [BOOKREQUEST_TICKET] (
    [BTKT_ID] BIGINT NOT NULL,
    [BTKT_BOOKID] BIGINT NOT NULL,
    [BTKT_TRAVELMODE] VARCHAR(50) NULL,
    [BTKT_FROM] VARCHAR(255) NULL,
    [BTKT_TO] VARCHAR(255) NULL,
    [BTKT_DEPART] DATETIME2(3) NULL,
    [BTKT_ARRIVAL] DATETIME2(3) NULL,
    [BTKT_CLASS] VARCHAR(50) NULL,
    [BTKT_PAXNAME] VARCHAR(255) NULL,
    [BTKT_REMARKS] VARCHAR(500) NULL,
    CONSTRAINT [PK_BOOKREQUEST_TICKET] PRIMARY KEY ([BTKT_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BOOKREQUEST_STAY')
CREATE TABLE [BOOKREQUEST_STAY] (
    [BSTY_ID] BIGINT NOT NULL,
    [BSTY_BOOKID] BIGINT NOT NULL,
    [BSTY_CITY] VARCHAR(255) NULL,
    [BSTY_CHECKIN] DATETIME2(3) NULL,
    [BSTY_CHECKOUT] DATETIME2(3) NULL,
    [BSTY_STAYTYPE] VARCHAR(50) NULL,
    [BSTY_REMARKS] VARCHAR(500) NULL,
    CONSTRAINT [PK_BOOKREQUEST_STAY] PRIMARY KEY ([BSTY_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BOOKREQUEST_CAB')
CREATE TABLE [BOOKREQUEST_CAB] (
    [BCAB_ID] BIGINT NOT NULL,
    [BCAB_BOOKID] BIGINT NOT NULL,
    [BCAB_CITY] VARCHAR(255) NULL,
    [BCAB_FROMDATE] DATETIME2(3) NULL,
    [BCAB_TODATE] DATETIME2(3) NULL,
    [BCAB_CABTYPE] VARCHAR(50) NULL,
    [BCAB_REMARKS] VARCHAR(500) NULL,
    CONSTRAINT [PK_BOOKREQUEST_CAB] PRIMARY KEY ([BCAB_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BOOKREQUEST_CC')
CREATE TABLE [BOOKREQUEST_CC] (
    [BOOKCC_ID] BIGINT NOT NULL,
    [BOOKCC_MAINID] BIGINT NOT NULL,
    [BOOKCC_CODE] VARCHAR(255) NULL,
    [BOOKCC_PERCENT] DECIMAL(5,2) NULL,
    CONSTRAINT [PK_BOOKREQUEST_CC] PRIMARY KEY ([BOOKCC_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BOOKREQUEST_OTHERS')
CREATE TABLE [BOOKREQUEST_OTHERS] (
    [BKOTH_ID] BIGINT NOT NULL,
    [BKOTH_BOOKID] BIGINT NOT NULL,
    [BKOTH_GUESTNAME] VARCHAR(255) NULL,
    [BKOTH_DESIGNATION] VARCHAR(255) NULL,
    [BKOTH_COMPANY] VARCHAR(255) NULL,
    CONSTRAINT [PK_BOOKREQUEST_OTHERS] PRIMARY KEY ([BKOTH_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BOOKCONFIRMATION_MAIN')
CREATE TABLE [BOOKCONFIRMATION_MAIN] (
    [BCNF_ID] BIGINT NOT NULL,
    [BCNF_BOOKID] BIGINT NOT NULL,
    [BCNF_VENDORID] VARCHAR(255) NULL,
    [BCNF_STATUS] CHAR(1) NULL,
    [BCNF_AMOUNT] DECIMAL(19,2) NULL,
    [BCNF_CREATEDBY] VARCHAR(255) NULL,
    [BCNF_CREATEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_BOOKCONFIRMATION_MAIN] PRIMARY KEY ([BCNF_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BOOKCONF_CAB')
CREATE TABLE [BOOKCONF_CAB] (
    [CNFCAB_CONFID] BIGINT NOT NULL,
    [CNFCAB_BOOKID] BIGINT NOT NULL,
    [CNFCAB_ID] BIGINT NOT NULL,
    CONSTRAINT [PK_BOOKCONF_CAB] PRIMARY KEY ([CNFCAB_CONFID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BOOKCONF_TICKET')
CREATE TABLE [BOOKCONF_TICKET] (
    [CNFTKT_CONFID] BIGINT NOT NULL,
    [CNFTKT_BOOKID] BIGINT NOT NULL,
    [CNFTKT_ID] BIGINT NOT NULL,
    [CNFTKT_PNR] VARCHAR(50) NULL,
    [CNFTKT_TICKETNO] VARCHAR(100) NULL,
    CONSTRAINT [PK_BOOKCONF_TICKET] PRIMARY KEY ([CNFTKT_CONFID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BOOKCONF_STAY')
CREATE TABLE [BOOKCONF_STAY] (
    [CNFSTY_CONFID] BIGINT NOT NULL,
    [CNFSTY_BOOKID] BIGINT NOT NULL,
    [CNFSTY_ID] BIGINT NOT NULL,
    [CNFSTY_HOTELNAME] VARCHAR(255) NULL,
    CONSTRAINT [PK_BOOKCONF_STAY] PRIMARY KEY ([CNFSTY_CONFID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BOOKCONFIRMATION_CC')
CREATE TABLE [BOOKCONFIRMATION_CC] (
    [BOOKCNFCC_ID] BIGINT NOT NULL,
    [BOOKCNFCC_MAINID] BIGINT NOT NULL,
    [BOOKCNFCC_CODE] VARCHAR(255) NULL,
    [BOOKCNFCC_PERCENT] DECIMAL(5,2) NULL,
    CONSTRAINT [PK_BOOKCONFIRMATION_CC] PRIMARY KEY ([BOOKCNFCC_ID])
);
GO

-- ══════════════════════════════════════════
-- CONFIG MODULE
-- ══════════════════════════════════════════

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'CURRENCY_MASTER')
CREATE TABLE [CURRENCY_MASTER] (
    [CUR_CODE] VARCHAR(10) NOT NULL,
    [CUR_NAME] VARCHAR(100) NOT NULL,
    [CUR_SYMBOL] NVARCHAR(10) NULL,
    [CUR_STATUS] CHAR(1) NULL,
    CONSTRAINT [PK_CURRENCY_MASTER] PRIMARY KEY ([CUR_CODE])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'VENDOR_MASTER')
CREATE TABLE [VENDOR_MASTER] (
    [VEN_ID] VARCHAR(255) NOT NULL,
    [VEN_NAME] VARCHAR(255) NOT NULL,
    [VEN_TYPE] VARCHAR(50) NULL,
    [VEN_GSTNO] VARCHAR(50) NULL,
    [VEN_PANNO] VARCHAR(50) NULL,
    [VEN_EMAIL] VARCHAR(255) NULL,
    [VEN_PHONE] VARCHAR(50) NULL,
    [VEN_ADDRESS] VARCHAR(500) NULL,
    [VEN_STATUS] CHAR(1) NULL,
    CONSTRAINT [PK_VENDOR_MASTER] PRIMARY KEY ([VEN_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'VENDOR_TAXRATE')
CREATE TABLE [VENDOR_TAXRATE] (
    [VTAX_ID] BIGINT NOT NULL,
    [VTAX_VENDORID] VARCHAR(255) NOT NULL,
    [VTAX_TAXTYPE] VARCHAR(50) NULL,
    [VTAX_RATE] DECIMAL(5,2) NULL,
    CONSTRAINT [PK_VENDOR_TAXRATE] PRIMARY KEY ([VTAX_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'VENDOR_UNITMAP')
CREATE TABLE [VENDOR_UNITMAP] (
    [VUNIT_ID] BIGINT NOT NULL,
    [VUNIT_VENDORID] VARCHAR(255) NOT NULL,
    [VUNIT_UNITID] VARCHAR(255) NOT NULL,
    CONSTRAINT [PK_VENDOR_UNITMAP] PRIMARY KEY ([VUNIT_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'VENDOR_CHARGES')
CREATE TABLE [VENDOR_CHARGES] (
    [VCHG_ID] BIGINT NOT NULL,
    [VCHG_VENDORID] VARCHAR(255) NOT NULL,
    [VCHG_CHARGETYPE] VARCHAR(100) NULL,
    [VCHG_AMOUNT] DECIMAL(19,2) NULL,
    CONSTRAINT [PK_VENDOR_CHARGES] PRIMARY KEY ([VCHG_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TRAVEL_CITYMASTER')
CREATE TABLE [TRAVEL_CITYMASTER] (
    [CITY_ID] VARCHAR(255) NOT NULL,
    [CITY_NAME] VARCHAR(255) NOT NULL,
    [CITY_COUNTRYCODE] VARCHAR(10) NULL,
    [CITY_STATUS] CHAR(1) NULL,
    CONSTRAINT [PK_TRAVEL_CITYMASTER] PRIMARY KEY ([CITY_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TRAVEL_COUNTRYMASTER')
CREATE TABLE [TRAVEL_COUNTRYMASTER] (
    [CTRY_CODE] VARCHAR(10) NOT NULL,
    [CTRY_NAME] VARCHAR(255) NOT NULL,
    [CTRY_STATUS] CHAR(1) NULL,
    CONSTRAINT [PK_TRAVEL_COUNTRYMASTER] PRIMARY KEY ([CTRY_CODE])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TRAVEL_CLASS')
CREATE TABLE [TRAVEL_CLASS] (
    [TCLASS_ID] VARCHAR(50) NOT NULL,
    [TCLASS_NAME] VARCHAR(100) NOT NULL,
    [TCLASS_MODE] VARCHAR(50) NULL,
    CONSTRAINT [PK_TRAVEL_CLASS] PRIMARY KEY ([TCLASS_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TRAVELMODE_MAST')
CREATE TABLE [TRAVELMODE_MAST] (
    [TMODE_ID] VARCHAR(50) NOT NULL,
    [TMODE_NAME] VARCHAR(100) NOT NULL,
    [TMODE_STATUS] CHAR(1) NULL,
    CONSTRAINT [PK_TRAVELMODE_MAST] PRIMARY KEY ([TMODE_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TRAVELLOV_CAT')
CREATE TABLE [TRAVELLOV_CAT] (
    [LOVCAT_ID] VARCHAR(50) NOT NULL,
    [LOVCAT_NAME] VARCHAR(255) NOT NULL,
    [LOVCAT_STATUS] CHAR(1) NULL,
    CONSTRAINT [PK_TRAVELLOV_CAT] PRIMARY KEY ([LOVCAT_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TRAVELLOV_MAST')
CREATE TABLE [TRAVELLOV_MAST] (
    [LOV_ID] BIGINT NOT NULL,
    [LOV_CATID] VARCHAR(50) NOT NULL,
    [LOV_VALUE] VARCHAR(255) NOT NULL,
    [LOV_DESCRIPTION] VARCHAR(500) NULL,
    [LOV_STATUS] CHAR(1) NULL,
    CONSTRAINT [PK_TRAVELLOV_MAST] PRIMARY KEY ([LOV_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'EXPENSETYPE_MAST')
CREATE TABLE [EXPENSETYPE_MAST] (
    [EXP_ID] VARCHAR(50) NOT NULL,
    [EXP_NAME] VARCHAR(255) NOT NULL,
    [EXP_GROUPID] VARCHAR(50) NULL,
    [EXP_STATUS] CHAR(1) NULL,
    CONSTRAINT [PK_EXPENSETYPE_MAST] PRIMARY KEY ([EXP_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'EXPENSEGROUP_MAST')
CREATE TABLE [EXPENSEGROUP_MAST] (
    [EXPGRP_ID] VARCHAR(50) NOT NULL,
    [EXPGRP_NAME] VARCHAR(255) NOT NULL,
    [EXPGRP_STATUS] CHAR(1) NULL,
    CONSTRAINT [PK_EXPENSEGROUP_MAST] PRIMARY KEY ([EXPGRP_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'GLOBALPAY_PARAMS')
CREATE TABLE [GLOBALPAY_PARAMS] (
    [GP_ID] BIGINT NOT NULL,
    [GP_PARAMNAME] VARCHAR(255) NOT NULL,
    [GP_PARAMVALUE] VARCHAR(500) NULL,
    CONSTRAINT [PK_GLOBALPAY_PARAMS] PRIMARY KEY ([GP_ID])
);
GO

-- ══════════════════════════════════════════
-- TOURPLAN MODULE
-- ══════════════════════════════════════════

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TOURPLAN_MAIN')
CREATE TABLE [TOURPLAN_MAIN] (
    [TP_ID] BIGINT NOT NULL,
    [TP_EMPSYSID] VARCHAR(255) NOT NULL,
    [TP_EMPNAME] VARCHAR(255) NULL,
    [TP_TRAVELTYPE] VARCHAR(50) NULL,
    [TP_PURPOSE] VARCHAR(500) NULL,
    [TP_FROMDATE] DATE NULL,
    [TP_TODATE] DATE NULL,
    [TP_STATUS] CHAR(1) NULL,
    [TP_CREATEDBY] VARCHAR(255) NULL,
    [TP_CREATEDON] DATETIME2(3) NULL,
    [TP_LASTMODIFIEDBY] VARCHAR(255) NULL,
    [TP_LASTMODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_TOURPLAN_MAIN] PRIMARY KEY ([TP_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TOURPLAN_ADVANCE')
CREATE TABLE [TOURPLAN_ADVANCE] (
    [TPA_ID] BIGINT NOT NULL,
    [TPA_TPID] BIGINT NOT NULL,
    [TPA_AMOUNT] DECIMAL(19,2) NULL,
    [TPA_CURRENCY] VARCHAR(10) NULL,
    [TPA_STATUS] CHAR(1) NULL,
    CONSTRAINT [PK_TOURPLAN_ADVANCE] PRIMARY KEY ([TPA_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TOURPLAN_AGENDA')
CREATE TABLE [TOURPLAN_AGENDA] (
    [TPAG_ID] BIGINT NOT NULL,
    [TPAG_TPID] BIGINT NOT NULL,
    [TPAG_DATE] DATE NULL,
    [TPAG_CITY] VARCHAR(255) NULL,
    [TPAG_DETAILS] VARCHAR(1000) NULL,
    CONSTRAINT [PK_TOURPLAN_AGENDA] PRIMARY KEY ([TPAG_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TOURPLAN_COSTCENTRE')
CREATE TABLE [TOURPLAN_COSTCENTRE] (
    [TPCC_ID] BIGINT NOT NULL,
    [TPCC_TPID] BIGINT NOT NULL,
    [TPCC_CODE] VARCHAR(255) NULL,
    [TPCC_PERCENT] DECIMAL(5,2) NULL,
    CONSTRAINT [PK_TOURPLAN_COSTCENTRE] PRIMARY KEY ([TPCC_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TOURPLAN_EXPENSE')
CREATE TABLE [TOURPLAN_EXPENSE] (
    [TPEXP_ID] BIGINT NOT NULL,
    [TPEXP_TPID] BIGINT NOT NULL,
    [TPEXP_TYPE] VARCHAR(50) NULL,
    [TPEXP_AMOUNT] DECIMAL(19,2) NULL,
    [TPEXP_CURRENCY] VARCHAR(10) NULL,
    CONSTRAINT [PK_TOURPLAN_EXPENSE] PRIMARY KEY ([TPEXP_ID])
);
GO

-- ══════════════════════════════════════════
-- TOUR MODULE
-- ══════════════════════════════════════════

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TOUR_PACKAGE')
CREATE TABLE [TOUR_PACKAGE] (
    [TOUR_ID] BIGINT IDENTITY(1,1) NOT NULL,
    [TOUR_NAME] VARCHAR(200) NOT NULL,
    [DESTINATION] VARCHAR(100) NOT NULL,
    [START_DATE] DATE NOT NULL,
    [END_DATE] DATE NOT NULL,
    [TOUR_PACKAGE_COST] DECIMAL(19,0) NOT NULL,
    [MAX_PARTICIPANTS] INT NOT NULL,
    [TOUR_STATUS] CHAR(1) NOT NULL DEFAULT 'P',
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME NOT NULL DEFAULT GETDATE(),
    [MODIFIED_BY] BIGINT NULL,
    [MODIFIED_ON] DATETIME NULL,
    CONSTRAINT [PK_TOUR_PACKAGE] PRIMARY KEY ([TOUR_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TOUR_REGISTRATION')
CREATE TABLE [TOUR_REGISTRATION] (
    [REGISTRATION_ID] BIGINT IDENTITY(1,1) NOT NULL,
    [TOUR_ID] BIGINT NOT NULL,
    [PARTICIPANT_ID] BIGINT NOT NULL,
    [REGISTRATION_DATE] DATE NOT NULL,
    [REGISTRATION_STATUS] CHAR(1) NOT NULL DEFAULT 'R',
    [PAYMENT_STATUS] CHAR(1) NOT NULL DEFAULT 'P',
    [AMOUNT_PAID] DECIMAL(19,0) NULL DEFAULT 0,
    [REGISTERED_BY] BIGINT NOT NULL,
    [REGISTERED_ON] DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT [PK_TOUR_REGISTRATION] PRIMARY KEY ([REGISTRATION_ID]),
    CONSTRAINT [FK_TOUR_REG_PACKAGE] FOREIGN KEY ([TOUR_ID]) REFERENCES [TOUR_PACKAGE]([TOUR_ID])
);
GO

-- ══════════════════════════════════════════
-- TRANSACTION MODULE
-- ══════════════════════════════════════════

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'JVEMP_MAIN')
CREATE TABLE [JVEMP_MAIN] (
    [JE_ID] BIGINT NOT NULL,
    [JE_EMPSYSID] VARCHAR(255) NOT NULL,
    [JE_TPID] BIGINT NULL,
    [JE_JVNO] VARCHAR(50) NULL,
    [JE_JVDATE] DATE NULL,
    [JE_TOTALAMOUNT] DECIMAL(19,2) NULL,
    [JE_STATUS] CHAR(1) NULL,
    [JE_CREATEDBY] VARCHAR(255) NULL,
    [JE_CREATEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_JVEMP_MAIN] PRIMARY KEY ([JE_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'JVEMP_SUB')
CREATE TABLE [JVEMP_SUB] (
    [JES_ID] BIGINT NOT NULL,
    [JES_JEID] BIGINT NOT NULL,
    [JES_EXPTYPE] VARCHAR(50) NULL,
    [JES_AMOUNT] DECIMAL(19,2) NULL,
    [JES_CCCODE] VARCHAR(255) NULL,
    CONSTRAINT [PK_JVEMP_SUB] PRIMARY KEY ([JES_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'JVSUP_MAIN')
CREATE TABLE [JVSUP_MAIN] (
    [JS_ID] BIGINT NOT NULL,
    [JS_VENDORID] VARCHAR(255) NOT NULL,
    [JS_JVNO] VARCHAR(50) NULL,
    [JS_JVDATE] DATE NULL,
    [JS_TOTALAMOUNT] DECIMAL(19,2) NULL,
    [JS_STATUS] CHAR(1) NULL,
    [JS_CREATEDBY] VARCHAR(255) NULL,
    [JS_CREATEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_JVSUP_MAIN] PRIMARY KEY ([JS_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'JVSUP_SUB')
CREATE TABLE [JVSUP_SUB] (
    [JSS_ID] BIGINT NOT NULL,
    [JSS_JSID] BIGINT NOT NULL,
    [JSS_EXPTYPE] VARCHAR(50) NULL,
    [JSS_AMOUNT] DECIMAL(19,2) NULL,
    [JSS_CCCODE] VARCHAR(255) NULL,
    CONSTRAINT [PK_JVSUP_SUB] PRIMARY KEY ([JSS_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TRAVEL_BATCHMAIN')
CREATE TABLE [TRAVEL_BATCHMAIN] (
    [TB_ID] BIGINT NOT NULL,
    [TB_BATCHNO] VARCHAR(50) NOT NULL,
    [TB_VENDORID] VARCHAR(255) NULL,
    [TB_TOTALAMOUNT] DECIMAL(19,2) NULL,
    [TB_STATUS] CHAR(1) NULL,
    [TB_CREATEDBY] VARCHAR(255) NULL,
    [TB_CREATEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_TRAVEL_BATCHMAIN] PRIMARY KEY ([TB_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TRAVEL_BATCHSUB')
CREATE TABLE [TRAVEL_BATCHSUB] (
    [TBS_ID] BIGINT NOT NULL,
    [TBS_BATCHID] BIGINT NOT NULL,
    [TBS_BOOKID] BIGINT NULL,
    [TBS_AMOUNT] DECIMAL(19,2) NULL,
    CONSTRAINT [PK_TRAVEL_BATCHSUB] PRIMARY KEY ([TBS_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TRAVEL_BATCHCC')
CREATE TABLE [TRAVEL_BATCHCC] (
    [TBCC_ID] BIGINT NOT NULL,
    [TBCC_BATCHID] BIGINT NOT NULL,
    [TBCC_CCCODE] VARCHAR(255) NULL,
    [TBCC_PERCENT] DECIMAL(5,2) NULL,
    CONSTRAINT [PK_TRAVEL_BATCHCC] PRIMARY KEY ([TBCC_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TRAVEL_EMPPAYDET')
CREATE TABLE [TRAVEL_EMPPAYDET] (
    [TEP_ID] BIGINT NOT NULL,
    [TEP_EMPSYSID] VARCHAR(255) NOT NULL,
    [TEP_TPID] BIGINT NULL,
    [TEP_AMOUNT] DECIMAL(19,2) NULL,
    [TEP_PAYDATE] DATE NULL,
    [TEP_STATUS] CHAR(1) NULL,
    CONSTRAINT [PK_TRAVEL_EMPPAYDET] PRIMARY KEY ([TEP_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TICKET_AIRLINEINOVICE')
CREATE TABLE [TICKET_AIRLINEINOVICE] (
    [TAI_ID] BIGINT NOT NULL,
    [TAI_BOOKID] BIGINT NULL,
    [TAI_TICKETNO] VARCHAR(100) NULL,
    [TAI_AIRLINE] VARCHAR(100) NULL,
    [TAI_AMOUNT] DECIMAL(19,2) NULL,
    [TAI_INVOICENO] VARCHAR(100) NULL,
    CONSTRAINT [PK_TICKET_AIRLINEINOVICE] PRIMARY KEY ([TAI_ID])
);
GO

-- ══════════════════════════════════════════
-- TRAVEL MODULE (additional)
-- ══════════════════════════════════════════

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TRAVEL_CONTACT')
CREATE TABLE [TRAVEL_CONTACT] (
    [TC_ID] BIGINT NOT NULL,
    [TC_NAME] VARCHAR(255) NOT NULL,
    [TC_PHONE] VARCHAR(50) NULL,
    [TC_EMAIL] VARCHAR(255) NULL,
    [TC_CITY] VARCHAR(255) NULL,
    CONSTRAINT [PK_TRAVEL_CONTACT] PRIMARY KEY ([TC_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TRAVEL_PROMOTERS')
CREATE TABLE [TRAVEL_PROMOTERS] (
    [TPR_ID] BIGINT NOT NULL,
    [TPR_NAME] VARCHAR(255) NOT NULL,
    [TPR_EMPSYSID] VARCHAR(255) NULL,
    [TPR_STATUS] CHAR(1) NULL,
    CONSTRAINT [PK_TRAVEL_PROMOTERS] PRIMARY KEY ([TPR_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TRAVEL_TIPS')
CREATE TABLE [TRAVEL_TIPS] (
    [TIP_ID] BIGINT NOT NULL,
    [TIP_CITY] VARCHAR(255) NOT NULL,
    [TIP_DESCRIPTION] VARCHAR(1000) NULL,
    CONSTRAINT [PK_TRAVEL_TIPS] PRIMARY KEY ([TIP_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'VENDOR_ADMINMAP')
CREATE TABLE [VENDOR_ADMINMAP] (
    [VAM_ID] BIGINT NOT NULL,
    [VAM_VENDORID] VARCHAR(255) NOT NULL,
    [VAM_ADMINID] VARCHAR(255) NOT NULL,
    CONSTRAINT [PK_VENDOR_ADMINMAP] PRIMARY KEY ([VAM_ID])
);
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DEFAULT_VENDORID_MAP')
CREATE TABLE [DEFAULT_VENDORID_MAP] (
    [DVM_ID] BIGINT NOT NULL,
    [DVM_BOOKTYPE] VARCHAR(50) NOT NULL,
    [DVM_MODE] VARCHAR(50) NULL,
    [DVM_VENDORID] VARCHAR(255) NOT NULL,
    CONSTRAINT [PK_DEFAULT_VENDORID_MAP] PRIMARY KEY ([DVM_ID])
);
GO

PRINT 'All tables created successfully.';
GO
