-- ==========================================
-- TIMESHEET Module - Table Scripts
-- Database: MYWORKDB
-- Module: TIMESHEET
-- Description: Timesheet, Time Collection, and Project Tracking Module
-- Created: March 9, 2026
-- ==========================================

USE MYWORKDB;
GO

-- =====================================================
-- TIMESHEET Core Tables
-- =====================================================

-- Table: TIMESHEET_MAIN - TIMESHEET MAIN
CREATE TABLE [TIMESHEET_MAIN] (
    [TIME_ID] BIGINT NULL  -- Time Sheet ID,
    [TIME_EMPSYSID] BIGINT NOT NULL  -- Employee System ID,
    [TIME_DATE] DATETIME2(3) NOT NULL  -- Date,
    [TIME_IN] DATETIME2(3) NULL  -- Time In,
    [TIME_OUT] DATETIME2(3) NULL  -- Time Out,
    [TIME_HOURS] BIGINT NOT NULL  -- Total Hours worked,
    [TIME_REMARKS] VARCHAR(200) NULL  -- Remarks,
    [TIME_ENTRYTYPE] CHAR(1) NOT NULL  -- S/M/A - Self/Manual/Automatic,
    [TIME_LASTMODIFIEDBY] BIGINT NOT NULL  -- Last modified by,
    [TIME_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last modified on,
    CONSTRAINT [PK_TIMESHEET_MAIN] PRIMARY KEY ([TIME_ID])
);

-- Table: TIMESHEET_DET - TIMESHEET DETAILS
CREATE TABLE [TIMESHEET_DET] (
    [TIMEDET_ID] BIGINT NULL  -- Time sheet detail ID,
    [TIMEDET_TIMEID] BIGINT NOT NULL  -- Time Sheet ID,
    [TIMEDET_HOURS] BIGINT NOT NULL  -- Hours,
    [TIMEDET_PROJECTID] BIGINT NOT NULL  -- Project ID,
    [TIMEDET_SUBCATID] BIGINT NOT NULL  -- Sub Category ID,
    [TIMEDET_REMARKS] VARCHAR(1000) NULL  -- Remarks,
    [TIMEDET_LASTMODIFIEDBY] BIGINT NOT NULL,
    [TIMEDET_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    [TIMEDET_CALLNO] BIGINT NOT NULL  -- Remarks,
    CONSTRAINT [PK_TIMESHEET_DET] PRIMARY KEY ([TIMEDET_ID])
);

-- Table: TIMESHEET_USERS - USERS TIMESHEET
CREATE TABLE [TIMESHEET_USERS] (
    [USER_TEAMID] BIGINT NOT NULL  -- Team id,
    [USER_EMPSYSID] BIGINT NOT NULL  -- Employee System id,
    CONSTRAINT [PK_TIMESHEET_USERS] PRIMARY KEY ([USER_EMPSYSID], [USER_TEAMID])
);

-- Table: TIMESHEET_MANPOWER - TIMESHEET MAN POWER
CREATE TABLE [TIMESHEET_MANPOWER] (
    [TIMEDET_PROJECTID] BIGINT NULL,
    [TIMEDET_HOURS] BIGINT NULL,
    [TIME_EMPSYSID] BIGINT NULL,
    [TIME_DATE] DATETIME2(3) NULL,
    [TIMEDET_SUBCATID] BIGINT NULL,
    [PROJECT_ID] BIGINT NULL,
    [PROJECT_NAME] VARCHAR(200) NULL,
    [PROJECT_CATEGORYID] BIGINT NULL,
    [CATEGORY_ID] BIGINT NULL,
    [CATEGORY_NAME] VARCHAR(200) NULL,
    [CATEGORY_TEAMID] BIGINT NULL,
    [PROJEMP_EMPSYSID] BIGINT NULL,
    [PROJWISE_SUBCAT] BIGINT NULL,
    [STAGEWISE_SUBCAT] BIGINT NULL,
    [SUBCAT_NAME] VARCHAR(200) NULL,
    [SUBCAT_PROCESSID] BIGINT NULL,
    [PROCESS_NAME] VARCHAR(200) NULL,
    [PROCESS_EMP_SYSID] BIGINT NULL,
    [GRADE_NAME] VARCHAR(200) NULL,
    [GRADE_DESIGNATION] VARCHAR(200) NULL,
    [TM_MONTH] BIGINT NULL,
    [TM_YEAR] BIGINT NULL,
    [TM_FINYEAR] BIGINT NULL,
    [TM_QUARTER] VARCHAR(50) NULL,
    [TM_LOCATION] VARCHAR(50) NULL,
    [TM_COST] VARCHAR(200) NULL,
    [USER_SYSID] BIGINT NULL,
    CONSTRAINT [PK_TIMESHEET_MANPOWER] PRIMARY KEY ([TIMEDET_PROJECTID])
);

-- =====================================================
-- TC (TIME COLLECTION) MODULE Tables
-- =====================================================

-- Table: TCTIMESHEET_MAIN - TIMESHEET MAIN
CREATE TABLE [TCTIMESHEET_MAIN] (
    [TIME_ID] BIGINT NOT NULL  -- Time Sheet ID,
    [TIME_EMPSYSID] BIGINT NOT NULL  -- Employee System ID,
    [TIME_DATE] DATETIME2(3) NOT NULL  -- Date,
    [TIME_IN] DATETIME2(3) NULL  -- Time In,
    [TIME_OUT] DATETIME2(3) NULL  -- Time Out,
    [TIME_HOURS] BIGINT NOT NULL  -- Total Hours worked,
    [TIME_REMARKS] VARCHAR(200) NULL  -- Remarks,
    [TIME_ENTRYTYPE] CHAR(1) NOT NULL  -- S/M/A - Self/Manual/Automatic,
    [TIME_LASTMODIFIEDBY] BIGINT NOT NULL  -- Last modified by,
    [TIME_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last modified ON,
    CONSTRAINT [PK_TCTIMESHEET_MAIN] PRIMARY KEY ([TIME_ID])
);

-- Table: TCTIMESHEET_DET - TIMESHEET DETAILS
CREATE TABLE [TCTIMESHEET_DET] (
    [TIMEDET_ID] BIGINT NOT NULL  -- Time sheet detail ID,
    [TIMEDET_TIMEID] BIGINT NOT NULL  -- Time Sheet ID,
    [TIMEDET_HOURS] BIGINT NOT NULL  -- Hours,
    [TIMEDET_PROJECTID] BIGINT NOT NULL  -- Project ID,
    [TIMEDET_SUBCATID] BIGINT NOT NULL  -- Sub Category ID,
    [TIMEDET_REMARKS] VARCHAR(1000) NULL  -- Remarks,
    [TIMEDET_LASTMODIFIEDBY] BIGINT NOT NULL,
    [TIMEDET_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    [TIMEDET_CALLNO] BIGINT NULL,
    CONSTRAINT [PK_TCTIMESHEET_DET] PRIMARY KEY ([TIMEDET_ID])
);

-- Table: TCPROJECT_MASTER - TC PROJECT MASTER
CREATE TABLE [TCPROJECT_MASTER] (
    [PROJECT_ID] BIGINT NOT NULL  -- Project ID,
    [PROJECT_NAME] VARCHAR(200) NOT NULL  -- Project Name,
    [PROJECT_CATEGORYID] BIGINT NOT NULL  -- Project Category ID,
    [PROJECT_EFFDATE] DATETIME2(3) NOT NULL  -- Project Effective Date,
    [PROJECT_CLSDATE] DATETIME2(3) NULL  -- Project Close Date,
    [PROJECT_TEAMID] BIGINT NOT NULL  -- Team ID ( 2 - TC Team),
    [PROJECT_LISTALL] CHAR(1) NOT NULL  -- List to All Employee,
    [PROJECT_LASTMODIFIEDBY] BIGINT NOT NULL  -- Last Updated By,
    [PROJECT_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last Updated on,
    [PROJECT_OLDPROJID] BIGINT NULL  -- Old Project ID for Reference,
    CONSTRAINT [PK_TCPROJECT_MASTER] PRIMARY KEY ([PROJECT_ID])
);

-- Table: TCPROJECTCAT_MASTER - TC PROJECT CATEGORY MASTER
CREATE TABLE [TCPROJECTCAT_MASTER] (
    [CATEGORY_ID] BIGINT NOT NULL  -- Category ID,
    [CATEGORY_NAME] VARCHAR(200) NOT NULL  -- Category NAME,
    [CATEGORY_TEAMID] BIGINT NOT NULL  -- Time Sheet Team ID,
    [CATEGORY_LASTMODIFIEDBY] BIGINT NOT NULL  -- Last Modified By,
    [CATEGORY_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last Modified ON,
    [CATEGORY_OLDCATID] BIGINT NULL  -- Old Cat ID Reference,
    CONSTRAINT [PK_TCPROJECTCAT_MASTER] PRIMARY KEY ([CATEGORY_ID])
);

-- Table: TCSUBCAT_MASTER - SUB CATEGORY MASTER
CREATE TABLE [TCSUBCAT_MASTER] (
    [SUBCAT_ID] BIGINT NOT NULL,
    [SUBCAT_NAME] VARCHAR(200) NOT NULL,
    [SUBCAT_PROJECTID] BIGINT NOT NULL,
    [SUBCAT_LASTMODIFIEDBY] BIGINT NOT NULL,
    [SUBCAT_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    [SUBCAT_OLDSUBCATID] BIGINT NULL,
    CONSTRAINT [PK_TCSUBCAT_MASTER] PRIMARY KEY ([SUBCAT_ID])
);

-- Table: TCSUBCAT_EMPMAP - SUB CATEGORY EMP MAP
CREATE TABLE [TCSUBCAT_EMPMAP] (
    [SUBCAT_MAPID] BIGINT NOT NULL,
    [SUBCAT_ID] BIGINT NOT NULL,
    [SUBCAT_EMPSYSID] BIGINT NOT NULL,
    [SUBCAT_STARTDATE] DATETIME2(3) NOT NULL,
    [SUBCAT_ENDDATE] DATETIME2(3) NULL,
    [SUBCAT_PLANNEDENDDATE] DATETIME2(3) NULL,
    [SUBCAT_PLANNEDHRS] INT NOT NULL,
    [SUBCAT_LASTMODIFIEDBY] BIGINT NOT NULL,
    [SUBCAT_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_TCSUBCAT_EMPMAP] PRIMARY KEY ([SUBCAT_MAPID])
);

-- =====================================================
-- TIMESHEET CATEGORY MANAGEMENT Tables
-- =====================================================

-- Table: SUBCAT_MASTER - SUB CATEGORY MASTER
CREATE TABLE [SUBCAT_MASTER] (
    [SUBCAT_ID] BIGINT NOT NULL,
    [SUBCAT_NAME] VARCHAR(200) NOT NULL,
    [SUBCAT_TEAMID] BIGINT NOT NULL,
    [SUBCAT_LASTMODIFIEDBY] BIGINT NOT NULL,
    [SUBCAT_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_SUBCAT_MASTER] PRIMARY KEY ([SUBCAT_ID])
);

-- Table: SUBCAT_PROJECTMAP - SUB CAT PROJECT MAP
CREATE TABLE [SUBCAT_PROJECTMAP] (
    [SUBCAT_MAPID] BIGINT NOT NULL,
    [SUBCAT_ID] BIGINT NOT NULL,
    [SUBCAT_PROJECTID] BIGINT NOT NULL,
    [SUBCAT_LASTMODIFIEDBY] BIGINT NOT NULL,
    [SUBCAT_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    [SUBCAT_STARTDATE] DATETIME2(3) NOT NULL,
    [SUBCAT_ENDDATE] DATETIME2(3) NULL,
    [SUBCAT_PLANNEDENDDATE] DATETIME2(3) NULL,
    [SUBCAT_PLANNEDHRS] INT NOT NULL,
    CONSTRAINT [PK_SUBCAT_PROJECTMAP] PRIMARY KEY ([SUBCAT_MAPID])
);

-- Table: SUBCAT_PROCESSMAP - SUB CAT PROCESS MAP
CREATE TABLE [SUBCAT_PROCESSMAP] (
    [SUBCAT_MAPID] BIGINT NOT NULL,
    [SUBCAT_ID] BIGINT NOT NULL,
    [SUBCAT_PROCESSID] BIGINT NOT NULL,
    [SUBCAT_LASTMODIFIEDBY] BIGINT NOT NULL,
    [SUBCAT_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_SUBCAT_PROCESSMAP] PRIMARY KEY ([SUBCAT_MAPID])
);

-- =====================================================
-- TS (TASK SCHEDULING) MODULE Tables
-- =====================================================

-- Table: TSPROJECT_MASTER - project master
CREATE TABLE [TSPROJECT_MASTER] (
    [PROJECT_ID] VARCHAR(255) NOT NULL  -- Project ID,
    [PROJECT_GROUP] VARCHAR(255) NOT NULL  -- Project Group (For Later Use),
    [PROJECT_NAME] VARCHAR(200) NOT NULL  -- Project Name,
    [PROJECT_EFFDATE] DATETIME2(3) NOT NULL  -- Effective Date,
    [PROJECT_CLSDATE] DATETIME2(3) NULL  -- Closure Date,
    [PROJECT_TYPE] CHAR(1) NOT NULL  -- P - Project ; S - Support ; G - General,
    [PROJECT_APPID] INT NOT NULL  -- Application ID - 1 - SPARSH ; 2 - Shriconnect; 3 - Common,
    [PROJECT_APPLYALL] CHAR(1) NOT NULL  -- Apply to all Employees - Y/N,
    [PROJECT_LASTMODIFIEDBY] BIGINT NOT NULL  -- Last Modified By,
    [PROJECT_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last Modified ON,
    CONSTRAINT [PK_TSPROJECT_MASTER] PRIMARY KEY ([PROJECT_ID])
);

-- Table: TSSTAGE_MASTER - stage master
CREATE TABLE [TSSTAGE_MASTER] (
    [STAGE_ID] VARCHAR(255) NOT NULL,
    [STAGE_NAME] VARCHAR(100) NOT NULL,
    [STAGE_PROJECTID] VARCHAR(255) NOT NULL,
    [STAGE_LASTMODIFIEDBY] BIGINT NOT NULL,
    [STAGE_LASTMODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_TSSTAGE_MASTER] PRIMARY KEY ([STAGE_ID])
);

-- Table: TSSTAGE_EMPMAP - stage emp map
CREATE TABLE [TSSTAGE_EMPMAP] (
    [STMAP_ID] BIGINT NOT NULL  -- Map ID,
    [STMAP_STAGEID] BIGINT NOT NULL  -- Stage ID,
    [STMAP_EMPSYSID] BIGINT NOT NULL  -- Employee System ID,
    [STMAP_HOURS] BIGINT NOT NULL  -- Hours Budgeted,
    [STMAP_STARTDATE] DATETIME2(3) NOT NULL  -- Start Date,
    [STMAP_PLANNEDENDDATE] DATETIME2(3) NOT NULL  -- Planned End Date,
    [STMAP_CLOSUREDATE] DATETIME2(3) NULL  -- Closure Date,
    [STMAP_LASTMODIFIEDBY] BIGINT NOT NULL  -- Last Modified By,
    [STMAP_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last Modified ON,
    [STMAP_GROUPID] DECIMAL(38) NULL,
    CONSTRAINT [PK_TSSTAGE_EMPMAP] PRIMARY KEY ([STMAP_ID])
);

-- Table: TSTIMESHEET_DET - timesheet details
CREATE TABLE [TSTIMESHEET_DET] (
    [TIME_ID] BIGINT NOT NULL,
    [TIME_EMPSYSID] BIGINT NOT NULL,
    [TIME_DATE] DATETIME2(3) NOT NULL,
    [TIME_PROJECTID] BIGINT NOT NULL,
    [TIME_STAGEID] BIGINT NOT NULL,
    [TIME_ACTIVITYID] BIGINT NOT NULL,
    [TIME_HOURS] BIGINT NOT NULL,
    [TIME_REMARKS] VARCHAR(500) NOT NULL,
    [TIME_MODULEID] BIGINT NULL,
    [TIME_REFID] VARCHAR(100) NULL,
    [TIME_CREATEDBY] BIGINT NOT NULL,
    [TIME_CREATEDON] DATETIME2(3) NOT NULL,
    [TIME_MODIFIEDBY] BIGINT NULL,
    [TIME_MODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_TSTIMESHEET_DET] PRIMARY KEY ([TIME_ID])
);

-- Table: TSACTIVITY_MASTER - activity master
CREATE TABLE [TSACTIVITY_MASTER] (
    [ACTIVITY_ID] BIGINT NOT NULL  -- Role Name,
    [ACTIVITY_NAME] VARCHAR(100) NOT NULL  -- Role ID,
    [ACTIVITY_ROLE] CHAR(2) NOT NULL  -- SD/TL/PM,
    [ACTIVITY_LASTMODIFIEDBY] BIGINT NOT NULL  -- Last Modified By,
    [ACTIVITY_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last Modified on,
    CONSTRAINT [PK_TSACTIVITY_MASTER] PRIMARY KEY ([ACTIVITY_ID])
);

-- Table: TSMODULE_MAST - module master
CREATE TABLE [TSMODULE_MAST] (
    [MODULE_ID] BIGINT NOT NULL  -- Module ID,
    [MODULE_APPID] INT NOT NULL  -- Application ID - 1 - SPARSH ; 2 - Shriconnect; 3 - Common,
    [MODULE_NAME] VARCHAR(25) NOT NULL  -- Module Name,
    [MODULE_LASTMODIFIEDBY] BIGINT NULL,
    [MODULE_LASTMODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_TSMODULE_MAST] PRIMARY KEY ([MODULE_ID])
);

-- Table: SC_ROLLINGPLAN - SCROLL ROLLING PLAN
CREATE TABLE [SC_ROLLINGPLAN] (
    [SCROLL_PLANID] BIGINT NOT NULL,
    [SCROLL_REFNO] BIGINT NULL,
    [SCROLL_RESPONSIBLE] BIGINT NULL,
    [SCROLL_TASK] VARCHAR(200) NULL,
    [SCROLL_EFFORTHOURS] BIGINT NULL,
    CONSTRAINT [PK_SC_ROLLINGPLAN] PRIMARY KEY ([SCROLL_PLANID])
);

PRINT 'TIMESHEET Module - Tables created successfully.';
GO
