apiVersion: v1
kind: Secret
metadata:
  name: erp-secrets
  namespace: erp-microservices
type: Opaque
stringData:
  sql-sa-password: "YourStrong!Passw0rd"          # CHANGE IN PRODUCTION
  rabbitmq-user: "erp_admin"
  rabbitmq-pass: "ErpR@bbit2024!"                  # CHANGE IN PRODUCTION
  jwt-secret-key: "ERP-Microservice-Shared-JWT-Secret-Key-For-Authentication-2024!"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: erp-config
  namespace: erp-microservices
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  DOTNET_ENVIRONMENT: "Production"
  SQL_SERVER: "sqlserver-service"
  SQL_DATABASE: "TASKDB"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  JWT_ISSUER: "ERP-Gateway"
  JWT_AUDIENCE: "ERP-Services"
