// <auto-generated />
using System;
using MasterService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace MasterService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MasterService.Domain.Entities.Benefit", b =>
            {
                b.Property<string>("BenefitCode").HasColumnName("BE_BEN_COD").HasMaxLength(3).IsFixedLength().HasColumnType("char(3)");
                b.Property<string>("BenefitDescription").HasColumnName("BE_BEN_DES").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("BenefitCode");
                b.ToTable("BENEFIT_MAST");
            });

            modelBuilder.Entity("MasterService.Domain.Entities.Category", b =>
            {
                b.Property<string>("CategoryCode").HasColumnName("CT_CAT_COD").HasMaxLength(3).IsFixedLength().HasColumnType("char(3)");
                b.Property<string>("CategoryName").HasColumnName("CT_CAT_NAM").IsRequired().HasMaxLength(65).HasColumnType("nvarchar(65)");
                b.Property<long?>("SerialNumber").HasColumnName("CT_SRL_NUM").HasColumnType("bigint");
                b.HasKey("CategoryCode");
                b.ToTable("CAT_MAST");
            });

            modelBuilder.Entity("MasterService.Domain.Entities.CompanyFinancialYear", b =>
            {
                b.Property<long>("SerialNumber").ValueGeneratedNever().HasColumnName("AC_SRL_NUM").HasColumnType("bigint");
                b.Property<DateTime>("StartDate").HasColumnName("AC_STR_DAT").HasColumnType("datetime2(3)");
                b.Property<DateTime>("EndDate").HasColumnName("AC_END_DAT").HasColumnType("datetime2(3)");
                b.Property<string>("CloseFlag").HasColumnName("AC_CLS_FLG").IsRequired().HasMaxLength(1).HasColumnType("nvarchar(1)");
                b.HasKey("SerialNumber");
                b.ToTable("COMP_FINYEAR");
            });

            modelBuilder.Entity("MasterService.Domain.Entities.CostMaster", b =>
            {
                b.Property<long>("CostCode").ValueGeneratedNever().HasColumnName("CS_CST_COD").HasColumnType("bigint");
                b.Property<string>("CostName").HasColumnName("CS_CST_NAM").IsRequired().HasMaxLength(65).HasColumnType("nvarchar(65)");
                b.HasKey("CostCode");
                b.ToTable("COST_MAST");
            });

            modelBuilder.Entity("MasterService.Domain.Entities.FunctionGroup", b =>
            {
                b.Property<string>("GroupCode").HasColumnName("GR_GRP_COD").HasMaxLength(3).IsFixedLength().HasColumnType("char(3)");
                b.Property<string>("GroupName").HasColumnName("GR_GRP_NAM").IsRequired().HasMaxLength(65).HasColumnType("nvarchar(65)");
                b.Property<long?>("SerialNumber").HasColumnName("GR_SRL_NUM").HasColumnType("bigint");
                b.HasKey("GroupCode");
                b.ToTable("FUNCTION_GROUP");
            });

            modelBuilder.Entity("MasterService.Domain.Entities.FunctionMaster", b =>
            {
                b.Property<string>("FunctionCode").HasColumnName("FN_FNC_COD").HasMaxLength(3).IsFixedLength().HasColumnType("char(3)");
                b.Property<string>("FunctionName").HasColumnName("FN_FNC_NAM").IsRequired().HasMaxLength(65).HasColumnType("nvarchar(65)");
                b.Property<string>("GroupCode").HasColumnName("FN_GRP_COD").IsRequired().HasMaxLength(3).IsFixedLength().HasColumnType("char(3)");
                b.Property<string>("UnitCode").HasColumnName("FN_UNT_COD").IsRequired().HasMaxLength(9).HasColumnType("nvarchar(9)");
                b.Property<long?>("SerialNumber").HasColumnName("FN_SRL_NUM").HasColumnType("bigint");
                b.HasKey("FunctionCode");
                b.ToTable("FUNCTION_MAST");
            });

            modelBuilder.Entity("MasterService.Domain.Entities.Goal", b =>
            {
                b.Property<string>("GoalCode").HasColumnName("GL_GOL_COD").HasMaxLength(3).IsFixedLength().HasColumnType("char(3)");
                b.Property<string>("GoalName").HasColumnName("GL_GOL_NAM").IsRequired().HasMaxLength(65).HasColumnType("nvarchar(65)");
                b.HasKey("GoalCode");
                b.ToTable("GOAL_MAST");
            });

            modelBuilder.Entity("MasterService.Domain.Entities.JobMaster", b =>
            {
                b.Property<long>("JobCode").ValueGeneratedNever().HasColumnName("JB_JOB_COD").HasColumnType("bigint");
                b.Property<string>("JobName").HasColumnName("JB_JOB_NAM").IsRequired().HasMaxLength(65).HasColumnType("nvarchar(65)");
                b.Property<string>("CategoryCode").HasColumnName("JB_CAT_COD").IsRequired().HasMaxLength(3).IsFixedLength().HasColumnType("char(3)");
                b.Property<long?>("SerialNumber").HasColumnName("JB_SRL_NUM").HasColumnType("bigint");
                b.HasKey("JobCode");
                b.ToTable("JOB_MAST");
            });

            modelBuilder.Entity("MasterService.Domain.Entities.Mode", b =>
            {
                b.Property<string>("ModeCode").HasColumnName("MD_MOD_COD").HasMaxLength(3).IsFixedLength().HasColumnType("char(3)");
                b.Property<string>("ModeDescription").HasColumnName("MD_MOD_DES").IsRequired().HasMaxLength(65).HasColumnType("nvarchar(65)");
                b.HasKey("ModeCode");
                b.ToTable("MODE_MAST");
            });

            modelBuilder.Entity("MasterService.Domain.Entities.Skill", b =>
            {
                b.Property<long>("SkillCode").ValueGeneratedNever().HasColumnName("SK_SKL_COD").HasColumnType("bigint");
                b.Property<string>("SkillName").HasColumnName("SK_SKL_NAM").IsRequired().HasMaxLength(255).HasColumnType("nvarchar(255)");
                b.Property<string>("SkillType").HasColumnName("SK_SKL_TYP").IsRequired().HasMaxLength(1).HasColumnType("nvarchar(1)");
                b.Property<decimal?>("WeightNum").HasColumnName("SK_WGT_NUM").HasColumnType("decimal(19,0)");
                b.Property<string>("Remark").HasColumnName("SK_SKL_REM").HasMaxLength(4000).HasColumnType("nvarchar(4000)");
                b.Property<DateTime?>("EffectiveDate").HasColumnName("SK_EFF_DAT").HasColumnType("datetime2");
                b.Property<DateTime?>("CloseDate").HasColumnName("SK_CLS_DAT").HasColumnType("datetime2");
                b.HasKey("SkillCode");
                b.ToTable("SKILL_MAST");
            });

            modelBuilder.Entity("MasterService.Domain.Entities.SkillGroup", b =>
            {
                b.Property<string>("GroupCode").HasColumnName("SK_GRP_COD").HasMaxLength(3).IsFixedLength().HasColumnType("char(3)");
                b.Property<string>("GroupName").HasColumnName("SK_GRP_NAM").IsRequired().HasMaxLength(25).HasColumnType("nvarchar(25)");
                b.HasKey("GroupCode");
                b.ToTable("SKILL_GROUP");
            });

            modelBuilder.Entity("MasterService.Domain.Entities.Source", b =>
            {
                b.Property<string>("SourceCode").HasColumnName("SR_SRC_COD").HasMaxLength(3).IsFixedLength().HasColumnType("char(3)");
                b.Property<string>("SourceName").HasColumnName("SR_SRC_NAM").IsRequired().HasMaxLength(65).HasColumnType("nvarchar(65)");
                b.HasKey("SourceCode");
                b.ToTable("SOURCE_MAST");
            });

            modelBuilder.Entity("MasterService.Domain.Entities.TrainingGroup", b =>
            {
                b.Property<long>("GroupCode").ValueGeneratedNever().HasColumnName("TR_GRP_COD").HasColumnType("bigint");
                b.Property<string>("GroupName").HasColumnName("TR_GRP_NAM").HasMaxLength(65).HasColumnType("nvarchar(65)");
                b.HasKey("GroupCode");
                b.ToTable("TRAIN_GROUP");
            });

            modelBuilder.Entity("MasterService.Domain.Entities.TrainingProvider", b =>
            {
                b.Property<long>("TrainingCode").ValueGeneratedNever().HasColumnName("TR_TRN_COD").HasColumnType("bigint");
                b.Property<string>("TrainingName").HasColumnName("TR_TRN_NAM").IsRequired().HasMaxLength(255).HasColumnType("nvarchar(255)");
                b.Property<string>("Address1").HasColumnName("TR_TRN_ADD1").HasMaxLength(255).HasColumnType("nvarchar(255)");
                b.Property<DateTime?>("CancelDate").HasColumnName("TR_CAN_DAT").HasColumnType("datetime2");
                b.Property<DateTime?>("EffectiveDate").HasColumnName("TR_EFF_DAT").HasColumnType("datetime2");
                b.HasKey("TrainingCode");
                b.ToTable("TRAIN_MAST");
            });
#pragma warning restore 612, 618
        }
    }
}
