<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LoanService.Domain\LoanService.Domain.csproj" />
    <ProjectReference Include="..\LoanService.Application\LoanService.Application.csproj" />
    <ProjectReference Include="..\LoanService.Infrastructure\LoanService.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
