-- ==========================================
-- LocationModule
-- Database: SRFSPARSHDB
-- Module Purpose: Location, Room and Resource Management
-- Created: March 09, 2026
-- ==========================================

USE SRFSPARSHDB;
GO

-- Drop tables if they exist (reverse order for dependencies)
IF OBJECT_ID('[ROOM_RESOURCE]', 'U') IS NOT NULL DROP TABLE [ROOM_RESOURCE];
GO
IF OBJECT_ID('[ROOM_MAST]', 'U') IS NOT NULL DROP TABLE [ROOM_MAST];
GO
IF OBJECT_ID('[LOCATION_CONTACT]', 'U') IS NOT NULL DROP TABLE [LOCATION_CONTACT];
GO

-- ==========================================
-- Table: LOCATION_CONTACT - Location Contact Information
-- Description: Contact details for each location
-- ==========================================
CREATE TABLE [LOCATION_CONTACT] (
    [LOCATION_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [LOCATION_CODE] VARCHAR(50) NOT NULL UNIQUE,
    [LOCATION_NAME] VARCHAR(255) NOT NULL,
    [LOCATION_ADDRESS] NVARCHAR(MAX),
    [CITY] VARCHAR(100),
    [STATE] VARCHAR(100),
    [PIN_CODE] VARCHAR(10),
    [COUNTRY] VARCHAR(100),
    [PHONE] VARCHAR(20),
    [EMAIL] VARCHAR(255),
    [CONTACT_PERSON] VARCHAR(255),
    [LOCATION_STATUS] CHAR(1) DEFAULT 'A', -- A=Active, I=Inactive
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [UPDATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3)
);
GO

-- ==========================================
-- Table: ROOM_MAST - Room Master with Location Code
-- Description: Rooms available at each location
-- Relationship: References LOCATION_CONTACT
-- ==========================================
CREATE TABLE [ROOM_MAST] (
    [ROOM_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [LOCATION_ID] BIGINT NOT NULL,
    [ROOM_CODE] VARCHAR(50) NOT NULL,
    [ROOM_NAME] VARCHAR(255) NOT NULL,
    [ROOM_CAPACITY] INT,
    [ROOM_TYPE] VARCHAR(50), -- MEETING, TRAINING, CONFERENCE, etc.
    [FLOOR_NUMBER] INT,
    [ROOM_STATUS] CHAR(1) DEFAULT 'A', -- A=Active, I=Inactive
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [UPDATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    CONSTRAINT [FK_ROOM_MAST_LOCATION] FOREIGN KEY ([LOCATION_ID]) REFERENCES [LOCATION_CONTACT]([LOCATION_ID]),
    CONSTRAINT [UC_ROOM_CODE_LOCATION] UNIQUE ([LOCATION_ID], [ROOM_CODE])
);
GO

-- ==========================================
-- Table: ROOM_RESOURCE - Room Resources with Location Code
-- Description: Resources allocated to each room (Projectors, Whiteboards, etc.)
-- Relationship: References ROOM_MAST
-- ==========================================
CREATE TABLE [ROOM_RESOURCE] (
    [RESOURCE_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [ROOM_ID] BIGINT NOT NULL,
    [LOCATION_ID] BIGINT NOT NULL,
    [RESOURCE_CODE] VARCHAR(50) NOT NULL,
    [RESOURCE_NAME] VARCHAR(255) NOT NULL,
    [RESOURCE_TYPE] VARCHAR(100), -- PROJECTOR, WHITEBOARD, MICROPHONE, etc.
    [RESOURCE_QUANTITY] INT,
    [RESOURCE_STATUS] CHAR(1) DEFAULT 'A', -- A=Active, I=Inactive
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [UPDATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3),
    CONSTRAINT [FK_ROOM_RESOURCE_ROOM] FOREIGN KEY ([ROOM_ID]) REFERENCES [ROOM_MAST]([ROOM_ID]),
    CONSTRAINT [FK_ROOM_RESOURCE_LOCATION] FOREIGN KEY ([LOCATION_ID]) REFERENCES [LOCATION_CONTACT]([LOCATION_ID])
);
GO

-- Create Indexes
CREATE INDEX [IX_LOCATION_CONTACT_CODE] ON [LOCATION_CONTACT]([LOCATION_CODE]);
CREATE INDEX [IX_LOCATION_CONTACT_STATUS] ON [LOCATION_CONTACT]([LOCATION_STATUS]);
CREATE INDEX [IX_ROOM_MAST_LOCATION_ID] ON [ROOM_MAST]([LOCATION_ID]);
CREATE INDEX [IX_ROOM_MAST_CODE] ON [ROOM_MAST]([ROOM_CODE]);
CREATE INDEX [IX_ROOM_MAST_TYPE] ON [ROOM_MAST]([ROOM_TYPE]);
CREATE INDEX [IX_ROOM_RESOURCE_ROOM_ID] ON [ROOM_RESOURCE]([ROOM_ID]);
CREATE INDEX [IX_ROOM_RESOURCE_LOCATION_ID] ON [ROOM_RESOURCE]([LOCATION_ID]);
CREATE INDEX [IX_ROOM_RESOURCE_TYPE] ON [ROOM_RESOURCE]([RESOURCE_TYPE]);
GO

PRINT 'LocationModule_Schema created successfully.';
GO
