apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-config
  namespace: transaction-service
  labels:
    app: transaction-service
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:5185"
  RabbitMQ__Host: "rabbitmq-service"
  RabbitMQ__Port: "5672"
  RabbitMQ__Username: "guest"
  RabbitMQ__Enabled: "true"
  BlobStorage__ContainerName: "stationery-images"
  Jwt__Issuer: "TransactionService"
  Jwt__Audience: "TransactionServiceClients"
  Jwt__ExpiryMinutes: "60"
