<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MenuAndSecurityService.Functions-78f28684-e2cd-4331-be84-357e471882e0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MenuAndSecurityService.Infrastructure\MenuAndSecurityService.Infrastructure.csproj" />
    <ProjectReference Include="..\MenuAndSecurityService.Application\MenuAndSecurityService.Application.csproj" />
  </ItemGroup>
</Project>
