apiVersion: v1
kind: ConfigMap
metadata:
  name: let-erp-config
  namespace: let-erp
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ConnectionStrings__DefaultConnection: "Server=sqlserver-svc;Database=LETDB;User Id=sa;Password=REPLACED_BY_SECRET;TrustServerCertificate=True"
  RabbitMQ__Host: "rabbitmq-svc"
  RabbitMQ__Port: "5672"
  RabbitMQ__UserName: "letadmin"
  RabbitMQ__Enabled: "true"
  Jwt__Issuer: "LET-ERP-Gateway"
  Jwt__Audience: "LET-ERP-Services"
