apiVersion: v1
kind: Secret
metadata:
  name: let-erp-secrets
  namespace: let-erp
type: Opaque
stringData:
  sql-sa-password: "REPLACE_WITH_STRONG_PASSWORD"
  rabbitmq-password: "REPLACE_WITH_STRONG_PASSWORD"
  jwt-secret-key: "REPLACE_WITH_MIN_32_CHAR_SECRET"
