-- ==========================================
-- Module: SwipeTransaction
-- Table Scripts
-- ==========================================

-- Table: CANTEEN_SWIPE_CARD_UPLOAD
CREATE TABLE [CANTEEN_SWIPE_CARD_UPLOAD] (
    [CN_COM_COD] BIGINT NOT NULL,  -- COMPANY CODE
    [CN_EMP_NUM] VARCHAR(20) NOT NULL,  -- EMPLOYEE NUMBER
    [CN_SWP_TIM] DATETIME2(3) NOT NULL,  -- PUNCH TIME
    [CN_ITM_COD] BIGINT NOT NULL,  -- ITEM CODE
    [CN_ITM_QTN] BIGINT NOT NULL,  -- ITEM QUANTITY
    [CN_BAT_DAT] DATETIME2(3) NOT NULL,  -- BATCH DATE
    [CN_BAT_NUM] BIGINT NOT NULL,  -- BATCH NUMBER
    [CN_SRL_NUM] BIGINT NOT NULL,  -- SERIAL NUMBER
    [CN_ENT_DAT] DATETIME2(3) NOT NULL,  -- ENTRY DATE
    [CN_CAN_NUM] CHAR(1) NOT NULL,  -- BREAKFAST/DINNER
    [CN_GAT_NUM] CHAR(3) NOT NULL,  -- MANUAL/ UPLAOD PUNCH
    [CN_UPD_STS] CHAR(1) NOT NULL,  -- ITEM NUMBER AS PER AS OLD SYSTEM
    [CN_FLX_FLD1] CHAR(5) NULL,  -- BREAKFAST/DINNER AS PER AS OLD SYSTEM
    [CN_FLX_FLD2] VARCHAR(20) NULL,  -- FLX FIELD
    [CN_FLX_FLD3] DECIMAL(38) NULL,  -- CN_FLX_FLD
    [CN_FLX_FLD4] DATETIME2(3) NULL,
    [CN_FLX_FLD5] VARCHAR(100) NULL
);

-- Table: CANTEEN_MIS_SBT
CREATE TABLE [CANTEEN_MIS_SBT] (
    [CN_COM_COD] BIGINT NOT NULL,
    [CN_EMP_NUM] VARCHAR(20) NOT NULL,
    [CN_SWP_TIM] DATETIME2(3) NOT NULL,
    [CN_ITM_COD] BIGINT NOT NULL,
    [CN_ITM_QTN] BIGINT NOT NULL,
    [CN_BAT_DAT] DATETIME2(3) NOT NULL,
    [CN_BAT_NUM] BIGINT NOT NULL,
    [CN_SRL_NUM] BIGINT NOT NULL,
    [CN_ENT_DAT] DATETIME2(3) NOT NULL,
    [CN_CAN_NUM] CHAR(1) NOT NULL,
    [CN_GAT_NUM] CHAR(3) NOT NULL,
    [CN_UPD_STS] CHAR(1) NOT NULL,
    [CN_FLX_FLD1] CHAR(5) NULL,
    [CN_FLX_FLD2] VARCHAR(20) NULL,
    [CN_FLX_FLD3] DECIMAL(38) NULL,
    [CN_FLX_FLD4] DATETIME2(3) NULL,
    [CN_FLX_FLD5] VARCHAR(100) NULL
);

-- Table: SWIPE_DEL
CREATE TABLE [SWIPE_DEL] (
    [CN_COM_COD] BIGINT NOT NULL,
    [CN_EMP_NUM] VARCHAR(20) NOT NULL,
    [CN_SWP_TIM] DATETIME2(3) NOT NULL,
    [CN_ITM_COD] BIGINT NOT NULL,
    [CN_ITM_QTN] BIGINT NOT NULL,
    [CN_BAT_DAT] DATETIME2(3) NOT NULL,
    [CN_BAT_NUM] BIGINT NOT NULL,
    [CN_SRL_NUM] BIGINT NOT NULL,
    [CN_ENT_DAT] DATETIME2(3) NOT NULL,
    [CN_CAN_NUM] CHAR(1) NOT NULL,
    [CN_GAT_NUM] CHAR(3) NOT NULL,
    [CN_UPD_STS] CHAR(1) NOT NULL,
    [CN_FLX_FLD1] CHAR(5) NULL,
    [CN_FLX_FLD2] VARCHAR(20) NULL,
    [CN_FLX_FLD3] DECIMAL(38) NULL,
    [CN_FLX_FLD4] DATETIME2(3) NULL,
    [CN_FLX_FLD5] VARCHAR(100) NULL
);

-- Table: CANTEEN_SWIPE_CARD_HO
CREATE TABLE [CANTEEN_SWIPE_CARD_HO] (
    [CN_UNT_COD] VARCHAR(10) NULL,
    [CN_EMP_ID] VARCHAR(10) NOT NULL,
    [CN_CRD_ID] VARCHAR(50) NULL,
    [CN_ATT_DAT] DATETIME2(3) NOT NULL,
    [CN_BIL_ID] BIGINT NULL,
    [CN_ITM_NAM] VARCHAR(50) NULL,
    [CN_ITM_QTY] BIGINT NULL,
    [CN_ITM_AMT] DECIMAL(38) NULL,
    [CN_TOT_AMT] DECIMAL(38) NULL,
    [CN_EMP_NAM] VARCHAR(50) NULL,
    [CN_TRF_STS] VARCHAR(15) NULL,
    [CN_BAT_NUM] VARCHAR(25) NULL
);

-- Table: CANTEENDATA_HO
CREATE TABLE [CANTEENDATA_HO] (
    [CARDNO] VARCHAR(10) NULL,
    [PUNCHDATE] DATETIME2(3) NULL,
    [ITEMCODE] VARCHAR(20) NULL,
    [ITEMRATE] INT NULL,
    [DISCOUNT] BIGINT NULL,
    [TOTAL_AMOUNT] BIGINT NULL,
    [GUEST] CHAR(1) NULL,
    [QUANTITY] BIGINT NULL
);

-- Table: SWIPEDATA_PFI
CREATE TABLE [SWIPEDATA_PFI] (
    [CARDNO] VARCHAR(25) NULL,
    [OFFICEPUNCH] DATETIME2(3) NULL,
    [MC_NO] VARCHAR(10) NULL,
    [INOUT] VARCHAR(1) NULL
);

-- Table: SWIPE_CARD_SRJCANTEEN
CREATE TABLE [SWIPE_CARD_SRJCANTEEN] (
    [AT_UNT_COD] VARCHAR(10) NULL,
    [AT_MAC_ID] VARCHAR(10) NULL,
    [AT_ATT_DAT] DATETIME2(3) NULL,
    [AT_FUNCTION] VARCHAR(10) NULL,
    [AT_EMP_NUM] VARCHAR(25) NULL,
    [AT_TRF_STS] VARCHAR(10) NULL,
    [AT_BAT_NUM] VARCHAR(10) NULL,
    [AT_ID] VARCHAR(10) NULL
);

-- Table: CANTEEN_DAYWISE_AVAILED
CREATE TABLE [CANTEEN_DAYWISE_AVAILED] (
    [CN_SRL_NUM] BIGINT NOT NULL,  -- Serial Number
    [CN_COM_COD] BIGINT NOT NULL,  -- Company Code
    [CN_SYS_ID] BIGINT NOT NULL,  -- Employee Number
    [CN_EMP_TYP] CHAR(1) NULL,  -- Employee Type
    [CN_SWP_DAT] VARCHAR(255) NULL,  -- Canteen Swipe Date
    [CN_ITM_COD] BIGINT NULL,  -- Item Code
    [CN_ITM_TYP] CHAR(1) NULL,  -- Item Type
    [CN_EE_CON] DECIMAL(38) NULL,  -- Employee Contribution
    [CN_ER_CON] DECIMAL(38) NULL,  -- Employer Contribution
    [CN_CAN_NUM] VARCHAR(255) NULL,  -- Canteen Number
    [CN_ITM_QTY] BIGINT NULL,  -- Item Quantity
    [CN_ENT_USR] BIGINT NULL,  -- Entry User
    [CN_ENT_DAT] VARCHAR(255) NULL,  -- Entry Date
    [CN_FLEX1] VARCHAR(20) NULL,  -- Flex Field
    [CN_GRD_CAT] CHAR(3) NULL,
    CONSTRAINT [PK_CANTEEN_DAYWISE_AVAILED] PRIMARY KEY ([CN_SRL_NUM])
);

-- Table: CAN_DAYWISE_EMP_PUNCH
CREATE TABLE [CAN_DAYWISE_EMP_PUNCH] (
    [CN_SRL_NUM] BIGINT NULL,  -- SERIAL NUMBER
    [CN_COM_COD] BIGINT NOT NULL,  -- COMPANY CODE
    [CN_SYSID] BIGINT NOT NULL,  -- EMPLOYEE NUMBER
    [CN_CAN_NUM] BIGINT NOT NULL,  -- CANTEEN PROCESSING NUMBER
    [CN_PUN_DAT] DATETIME2(3) NOT NULL,  -- PUNCH DATE
    [CN_TIM_IN] VARCHAR(255) NULL,  -- PUNCH IN TIME
    [CN_TIM_OUT] VARCHAR(255) NULL,  -- PUNCH OUT TIME
    [CN_WRK_HRS] DECIMAL(38) NULL,  -- WORKS HOURS
    CONSTRAINT [PK_CAN_DAYWISE_EMP_PUNCH] PRIMARY KEY ([CN_SRL_NUM])
);

-- Table: CANTEEDN_DACON
CREATE TABLE [CANTEEDN_DACON] (
    [CN_SRL_NUM] BIGINT NULL,
    [CN_COM_COD] BIGINT NULL,
    [CN_SYS_ID] BIGINT NOT NULL,
    [CN_EMP_TYP] CHAR(1) NULL,
    [CN_SWP_DAT] VARCHAR(255) NULL,
    [CN_ITM_COD] BIGINT NULL,
    [CN_ITM_TYP] CHAR(1) NULL,
    [CN_EE_CON] DECIMAL(38) NULL,
    [CN_ER_CON] DECIMAL(38) NULL,
    [CN_CAN_NUM] VARCHAR(255) NULL,
    [CN_ITM_QTY] BIGINT NULL,
    [CN_ENT_USR] BIGINT NULL,
    [CN_ENT_DAT] VARCHAR(255) NULL,
    [CN_FLEX1] VARCHAR(20) NULL,
    [CN_GRD_CAT] CHAR(3) NULL
);
