-- Module: Feedback
USE DDDB;
GO

-- Table: APP_FEEDBACKMAIN
CREATE TABLE [APP_FEEDBACKMAIN] (
    [FB_FEEDBACKID] DECIMAL(38) NULL,
    [FB_REQUESTNO] DECIMAL(38) NOT NULL,
    [FB_APPRSYSID] DECIMAL(38) NOT NULL,
    [FB_STATUS] CHAR(1) NULL,
    [FB_REMARKS] VARCHAR(2000) NULL,
    [CREATEDON] DATETIME2(3) NOT NULL,
    [UPDATEDON] DATETIME2(3) NULL
);



-- Table: APP_FEEDBACKSUB
CREATE TABLE [APP_FEEDBACKSUB] (
    [FB_FEEDBACKID] DECIMAL(38) NOT NULL,
    [FB_QTNNO] DECIMAL(38) NOT NULL,
    [FB_ANSNO] DECIMAL(38) NULL,
    [UPDATEDON] DATETIME2(3) NULL
);



-- Table: LOV_FEEDBACK
CREATE TABLE [LOV_FEEDBACK] (
    [DD_FEEDBACKID] DECIMAL(38) NULL,
    [DD_FEEDBACKNAME] NVARCHAR(400) NULL
);

