-- ==========================================
-- INVENTORY MANAGEMENT MODULE - Table Definitions
-- Database: SCIDB
-- Module: Product & Item Management
-- Created: March 9, 2026
-- ==========================================

USE SCIDB;
GO

-- Table: MAIN_PRODUCT_MASTER
CREATE TABLE [MAIN_PRODUCT_MASTER] (
    [PRODUCT_ID] INT NULL,
    [PRODUCT_NAME] VARCHAR(20) NULL,
    [PRODUCT_DESCRIPTION] VARCHAR(100) NULL,
    [UNIT_ID] INT NULL,
    [PRODUCT_TYPE_ID] INT NULL,
    [COMPANY_UNIT_ID] INT NULL,
    [SCI_USER_ID_CREATED] INT NULL,
    [CREATION_DATE] DATETIME2(3) NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] VARCHAR(255) NULL,
    [MAM_FLAG] CHAR(1) NULL,
    CONSTRAINT [PK_MAIN_PRODUCT_MASTER] PRIMARY KEY ([PRODUCT_ID])
);

-- Table: PRODUCT_MASTER
CREATE TABLE [PRODUCT_MASTER] (
    [PM_PRO_COD] VARCHAR(25) NOT NULL,
    [PM_PRO_DESC] VARCHAR(255) NOT NULL,
    [PM_ORA_DES] VARCHAR(255) NOT NULL,
    [PM_UOM_COD] VARCHAR(255) NULL,
    CONSTRAINT [PK_PRODUCT_MASTER] PRIMARY KEY ([PM_PRO_COD])
);

-- Table: PRODUCT_TYPE_MASTER
CREATE TABLE [PRODUCT_TYPE_MASTER] (
    [PRODUCT_TYPE_ID] INT NOT NULL,
    [TYPE_NAME] VARCHAR(20) NOT NULL,
    [TYPE_DESCRIPTION] VARCHAR(50) NULL,
    [SCI_USER_ID_CREATED] INT NULL,
    [CREATION_DATE] DATETIME2(3) NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] VARCHAR(255) NULL,
    CONSTRAINT [PK_PRODUCT_TYPE_MASTER] PRIMARY KEY ([PRODUCT_TYPE_ID])
);

-- Table: ITEM_MASTER
CREATE TABLE [ITEM_MASTER] (
    [SCI_ITEM_ID] INT NOT NULL,
    [ORACLE_CODE] VARCHAR(20) NOT NULL,
    [ORACLE_ITEM_ID] INT NOT NULL,
    [MAIN_PRODUCT_ID] INT NULL,
    [ITEM_NAME] VARCHAR(100) NULL,
    [ORACLE_DESCRIPTION] VARCHAR(200) NULL,
    [ITEM_TYPE] VARCHAR(20) NOT NULL,
    [PACKAGE_TYPE_ID] INT NULL,
    [ITEM_UOM_ID] INT NOT NULL,
    [MAIN_PRODUCT_UOM_CONFACTOR] DECIMAL(38) NOT NULL,
    [ISBULK_SOURCE] VARCHAR(1) NOT NULL,
    [ISBULK_ITEM] CHAR(1) NOT NULL,
    [MATERIAL_TAXCLASS] INT NULL,
    [PRODUCT_CLASS] CHAR(2) NULL,
    [EFFECTIVE_DATE] VARCHAR(255) NULL,
    [CLOSURE_DATE] VARCHAR(255) NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] VARCHAR(255) NULL,
    [LEAD_TIME] INT NULL,
    [ITEM_CAPACITY_ID] INT NULL,
    [ITEM_USAGE] CHAR(2) NULL,
    [MAM_FLAG] CHAR(1) NULL,
    [ITEM_ACC_TYPE] CHAR(1) NULL,
    CONSTRAINT [PK_ITEM_MASTER] PRIMARY KEY ([SCI_ITEM_ID])
);

-- Table: PACKAGE_TYPE
CREATE TABLE [PACKAGE_TYPE] (
    [PACKAGE_TYPE_ID] INT NOT NULL,
    [PACKAGE_TYPE_NAME] VARCHAR(20) NOT NULL,
    [SCI_USER_ID_CREATED] INT NULL,
    [CREATION_DATE] DATETIME2(3) NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] VARCHAR(255) NULL,
    CONSTRAINT [PK_PACKAGE_TYPE] PRIMARY KEY ([PACKAGE_TYPE_ID])
);

-- Table: ITEM_CAPACITY
CREATE TABLE [ITEM_CAPACITY] (
    [CAPACITY_ID] INT NOT NULL,
    [CAPACITY_NAME] VARCHAR(20) NOT NULL,
    [SCI_USER_ID_CREATED] INT NOT NULL,
    [CREATION_DATE] DATETIME2(3) NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_ITEM_CAPACITY] PRIMARY KEY ([CAPACITY_ID])
);

-- Table: ITEM_TYPE
CREATE TABLE [ITEM_TYPE] (
    [ITEM_TYPE_ID] INT NOT NULL,
    [ITEM_TYPE_CODE] VARCHAR(2) NULL,
    [DESCRIPTION] VARCHAR(60) NULL,
    [SCI_USER_ID_CREATED] INT NULL,
    [CREATION_DATE] DATETIME2(3) NOT NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_ITEM_TYPE] PRIMARY KEY ([ITEM_TYPE_ID])
);

-- Table: ITEM_GRADE
CREATE TABLE [ITEM_GRADE] (
    [ITEM_GRADE_ID] INT NOT NULL,
    [ITEM_GRADE_NAME] VARCHAR(20) NOT NULL,
    [SCI_USER_ID_CREATED] INT NOT NULL,
    [CREATION_DATE] DATETIME2(3) NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_ITEM_GRADE] PRIMARY KEY ([ITEM_GRADE_ID])
);

-- Table: GRADE_MASTER
CREATE TABLE [GRADE_MASTER] (
    [GM_GRD_COD] VARCHAR(25) NOT NULL,
    [GM_GRD_DESC] VARCHAR(200) NOT NULL,
    [GM_PRO_COD] VARCHAR(25) NOT NULL,
    CONSTRAINT [PK_GRADE_MASTER] PRIMARY KEY ([GM_GRD_COD])
);

-- Table: ITEM_MAP
CREATE TABLE [ITEM_MAP] (
    [OSP_ITEM_ID] BIGINT NOT NULL,
    [OSP_UOM_CODE] VARCHAR(3) NOT NULL,
    [ITEM_ID] BIGINT NOT NULL,
    [UOM_CODE] DECIMAL(38) NOT NULL,
    [QUANTITY] VARCHAR(3) NOT NULL,
    [ORACLE_CODE] DECIMAL(20,0) NULL,
    CONSTRAINT [PK_ITEM_MAP] PRIMARY KEY ([OSP_ITEM_ID], [OSP_UOM_CODE], [ITEM_ID], [UOM_CODE])
);

-- Table: MATERIAL_TAX_CLASS
CREATE TABLE [MATERIAL_TAX_CLASS] (
    [MATERIAL_TAXCLASS_ID] INT NOT NULL,
    [DESCRIPTION] VARCHAR(60) NULL,
    [SCI_USER_ID_CREATED] INT NOT NULL,
    [CREATION_DATE] DATETIME2(3) NOT NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_MATERIAL_TAX_CLASS] PRIMARY KEY ([MATERIAL_TAXCLASS_ID])
);

-- Table: UNIT_OF_MEASURE
CREATE TABLE [UNIT_OF_MEASURE] (
    [UNIT_ID] INT NOT NULL,
    [UNIT_CODE] VARCHAR(3) NOT NULL,
    [UNIT_OF_MEASURENT] VARCHAR(25) NOT NULL,
    [UNIT_CLASS_ID] INT NOT NULL,
    [BASE_UNIT_FLAG] CHAR(1) NOT NULL,
    [DESCRIPTION] VARCHAR(50) NULL,
    [SCI_USER_ID_CREATED] INT NULL,
    [CREATION_DATE] DATETIME2(3) NOT NULL,
    [SCI_USER_ID_MODIFIED] INT NULL,
    [MODIFIED_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_UNIT_OF_MEASURE] PRIMARY KEY ([UNIT_ID])
);

-- Table: UNITS_CLASS
CREATE TABLE [UNITS_CLASS] (
    [UNITS_CLASS_ID] INT NOT NULL,
    [UNITS_CLASS] VARCHAR(10) NULL,
    CONSTRAINT [PK_UNITS_CLASS] PRIMARY KEY ([UNITS_CLASS_ID])
);

-- Table: ADVLIC_MASTER (Advance License Master)
CREATE TABLE [ADVLIC_MASTER] (
    [ADVLIC_ID] BIGINT NOT NULL,
    [ADVLIC_NO] VARCHAR(40) NULL,
    [ADVLIC_FG] INT NULL,
    [ADVLIC_EOAMT] DECIMAL(19,0) NULL,
    [ADVLIC_EXPAMT] DECIMAL(19,0) NULL,
    CONSTRAINT [PK_ADVLIC_MASTER] PRIMARY KEY ([ADVLIC_ID])
);

-- Table: ADVLIC_ENTITLEMENT
CREATE TABLE [ADVLIC_ENTITLEMENT] (
    [ADVLIC_ID] BIGINT NOT NULL,
    [ADVLIC_ENTITLERM] INT NOT NULL,
    CONSTRAINT [PK_ADVLIC_ENTITLEMENT] PRIMARY KEY ([ADVLIC_ID], [ADVLIC_ENTITLERM])
);

PRINT 'INVENTORY_MANAGEMENT_MODULE Tables created successfully.';
GO
