-- ==========================================
-- MAM ALLOCATION MODULE - Table Definitions
-- Database: SCIDB
-- Module: Material Allocation Management
-- Created: March 9, 2026
-- ==========================================

USE SCIDB;
GO

-- Table: MAM_ALLOCATION_DET
CREATE TABLE [MAM_ALLOCATION_DET] (
    [ALL_DATE] DATETIME2(3) NOT NULL,
    [ALL_RM] INT NOT NULL,
    [ALL_ENTOPEN] DECIMAL(19,0) NULL,
    [ALL_FORMIVDDF] DECIMAL(19,0) NULL,
    [ALL_FORMIVIDF] DECIMAL(19,0) NULL,
    [ALL_FORMIVIDP] DECIMAL(19,0) NULL,
    [ALL_FORMIVDDP] DECIMAL(19,0) NULL,
    [ALL_FORMIVIDFWO] DECIMAL(19,0) NULL,
    [ALL_FORMIVDDFWO] DECIMAL(19,0) NULL,
    [ALL_CLOSEDDF] DECIMAL(19,0) NULL,
    [ALL_CLOSEIDF] DECIMAL(19,0) NULL,
    [ALL_CLOSEIDP] DECIMAL(19,0) NULL,
    [ALL_CLOSEDDP] DECIMAL(19,0) NULL,
    [ALL_ENTDEBIT] DECIMAL(19,0) NULL,
    [ALL_PRODENTDEBIT] DECIMAL(19,0) NULL,
    [ALL_DISPENTCREDIT] DECIMAL(19,0) NULL,
    [ALL_NETENT] DECIMAL(19,0) NULL,
    [ALL_ADDDDF] DECIMAL(19,0) NULL,
    [ALL_ADDIDF] DECIMAL(19,0) NULL,
    [ALL_ADDIDP] DECIMAL(19,0) NULL,
    [ALL_ADDDDP] DECIMAL(19,0) NULL,
    [ALL_PROD] DECIMAL(19,0) NULL,
    [ALL_CONS] DECIMAL(19,0) NULL,
    [ALL_RG1DDF] DECIMAL(19,0) NULL,
    [ALL_RG1DDP] DECIMAL(19,0) NULL,
    [ALL_CLOSERG1DDF] DECIMAL(19,0) NULL,
    [ALL_CLOSERG1DDP] DECIMAL(19,0) NULL,
    [ALL_SALEFORMIVIDP] DECIMAL(19,0) NULL,
    [ALL_SALEFORMIVDDP] DECIMAL(19,0) NULL,
    [ALL_SALERG1DDP] DECIMAL(19,0) NULL,
    [ALL_SALE] DECIMAL(19,0) NULL,
    [ALL_ADDRGDDF] DECIMAL(19,0) NULL,
    [ALL_ADDRGDDP] DECIMAL(19,0) NULL,
    CONSTRAINT [PK_MAM_ALLOCATION_DET] PRIMARY KEY ([ALL_DATE], [ALL_RM])
);

-- Table: MAM_ALLOCATION_PRODDET
CREATE TABLE [MAM_ALLOCATION_PRODDET] (
    [ALL_DATE] DATETIME2(3) NULL,
    [ALL_SRL] BIGINT NULL,
    [ALL_FG] INT NULL,
    [DDF_QTY] DECIMAL(19,0) NULL,
    [DDP_QTY] DECIMAL(19,0) NULL,
    [PRD_QTY] DECIMAL(19,0) NULL,
    [ALL_RM] DECIMAL(19,0) NULL
);

-- Table: MAM_ALLOCATIONFG
CREATE TABLE [MAM_ALLOCATIONFG] (
    [ALL_DATE] DATETIME2(3) NULL,
    [FG_CODE] BIGINT NULL,
    [DOM_DISPATCH] INT NULL,
    [EXP_DISPATCH] DECIMAL(19,0) NULL,
    [DUTY_FREE] DECIMAL(19,0) NULL,
    [DUTY_PAID] DECIMAL(19,0) NULL
);

-- Table: MAM_ARRIVAL_DET
CREATE TABLE [MAM_ARRIVAL_DET] (
    [ARRIVAL_NO] BIGINT NULL,
    [ARRIVAL_DATE] DATETIME2(3) NULL,
    [ARRIVAL_QTY] DECIMAL(19,0) NULL,
    [ARRIVAL_ITEM] INT NULL,
    [ARRIVAL_RECEIPTNO] DECIMAL(38) NULL
);

-- Table: MAM_CONSUMPTION_DET
CREATE TABLE [MAM_CONSUMPTION_DET] (
    [CONSUMPTION_NO] BIGINT NULL,
    [CONSUMPTION_DATE] DATETIME2(3) NULL,
    [CONSUMPTION_RM] INT NULL,
    [CONSUMPTION_QTY] DECIMAL(19,0) NULL
);

-- Table: MAM_DISPATCH_DET
CREATE TABLE [MAM_DISPATCH_DET] (
    [DISPATCH_NO] DECIMAL(38) NULL,
    [DISPATCH_DATE] DATETIME2(3) NULL,
    [DISPATCH_FG] INT NULL,
    [DISPATCH_QTY] DECIMAL(19,0) NULL,
    [DISPATCH_TYPE] CHAR(1) NULL,
    [DISPATCH_AREDATE] DATETIME2(3) NULL,
    [DISPATCH_INVOICENO] VARCHAR(20) NULL,
    [DISPATCH_ADVNO] BIGINT NULL
);

-- Table: MAM_FG_ALLOCATION
CREATE TABLE [MAM_FG_ALLOCATION] (
    [SNO] BIGINT NULL,
    [FG_CODE] BIGINT NULL,
    [FLAG] CHAR(1) NULL
);

-- Table: MAM_PRODUCT_ALLOCATION
CREATE TABLE [MAM_PRODUCT_ALLOCATION] (
    [SNO] BIGINT NULL,
    [RM_CODE] BIGINT NULL
);

PRINT 'MAM_ALLOCATION_MODULE Tables created successfully.';
GO
