// <auto-generated />
using System;
using GroupIncentiveService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroupIncentiveService.Infrastructure.Migrations
{
    [DbContext(typeof(GroupIncentiveDbContext))]
    [Migration("20260311082321_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GroupIncentiveService.Domain.Entities.GroupEmployeeMap", b =>
                {
                    b.Property<long>("GrpEmpMapId")
                        .HasColumnType("bigint")
                        .HasColumnName("GRPEMPMAP_ID");

                    b.Property<DateTime?>("GrpEmpMapClsDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("GRPEMPMAP_CLSDATE");

                    b.Property<DateTime>("GrpEmpMapEffDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("GRPEMPMAP_EFFDATE");

                    b.Property<long>("GrpEmpMapEmpSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("GRPEMPMAP_EMPSYSID");

                    b.Property<int>("GrpEmpMapGroupId")
                        .HasColumnType("int")
                        .HasColumnName("GRPEMPMAP_GROUPID");

                    b.Property<long>("GrpEmpMapLastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("GRPEMPMAP_LASTMODIFIEDBY");

                    b.Property<DateTime>("GrpEmpMapLastModifiedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("GRPEMPMAP_LASTMODIFIEDON");

                    b.Property<string>("GrpEmpMapRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("GRPEMPMAP_ROLE");

                    b.HasKey("GrpEmpMapId");

                    b.HasIndex("GrpEmpMapEmpSysId")
                        .HasDatabaseName("IX_GROUP_EMPLOYEEMAP_EMPSYSID");

                    b.HasIndex("GrpEmpMapGroupId")
                        .HasDatabaseName("IX_GROUP_EMPLOYEEMAP_GROUPID");

                    b.HasIndex("GrpEmpMapGroupId", "GrpEmpMapEmpSysId", "GrpEmpMapEffDate")
                        .IsUnique()
                        .HasDatabaseName("UQ_GRPEMPMAP");

                    b.ToTable("GROUP_EMPLOYEEMAP", (string)null);
                });

            modelBuilder.Entity("GroupIncentiveService.Domain.Entities.GroupIncentiveApproval", b =>
                {
                    b.Property<long>("GrpIncAppId")
                        .HasColumnType("bigint")
                        .HasColumnName("GRPINCAPP_ID");

                    b.Property<DateTime>("GrpIncAppApprovalDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("GRPINCAPP_APPROVALDATE");

                    b.Property<long>("GrpIncAppApprover")
                        .HasColumnType("bigint")
                        .HasColumnName("GRPINCAPP_APPROVER");

                    b.Property<long>("GrpIncAppLastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("GRPINCAPP_LASTMODIFIEDBY");

                    b.Property<DateTime>("GrpIncAppLastModifiedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("GRPINCAPP_LASTMODIFIEDON");

                    b.Property<long>("GrpIncAppMainId")
                        .HasColumnType("bigint")
                        .HasColumnName("GRPINCAPP_MAINID");

                    b.Property<string>("GrpIncAppRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GRPINCAPP_REMARKS");

                    b.Property<string>("GrpIncAppStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("GRPINCAPP_STATUS");

                    b.HasKey("GrpIncAppId");

                    b.HasIndex("GrpIncAppMainId");

                    b.ToTable("GROUPINCENTIVE_APPROVAL", (string)null);
                });

            modelBuilder.Entity("GroupIncentiveService.Domain.Entities.GroupIncentiveBreak", b =>
                {
                    b.Property<int>("GrpIncBrkId")
                        .HasColumnType("int")
                        .HasColumnName("GRPINCBRK_ID");

                    b.Property<decimal>("GrpIncBrkAttPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("GRPINCBRK_ATTPERCENTAGE");

                    b.Property<DateTime?>("GrpIncBrkClsDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("GRPINCBRK_CLSDATE");

                    b.Property<DateTime>("GrpIncBrkEffDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("GRPINCBRK_EFFDATE");

                    b.Property<int>("GrpIncBrkGroupId")
                        .HasColumnType("int")
                        .HasColumnName("GRPINCBRK_GROUPID");

                    b.Property<decimal>("GrpIncBrkIncPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("GRPINCBRK_INCPERCENTAGE");

                    b.Property<long>("GrpIncBrkLastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("GRPINCBRK_LASTMODIFIEDBY");

                    b.Property<DateTime>("GrpIncBrkLastModifiedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("GRPINCBRK_LASTMODIFIEDON");

                    b.HasKey("GrpIncBrkId");

                    b.HasIndex("GrpIncBrkGroupId");

                    b.ToTable("GROUPINCENTIVE_BREAK", (string)null);
                });

            modelBuilder.Entity("GroupIncentiveService.Domain.Entities.GroupIncentiveDet", b =>
                {
                    b.Property<long>("GrpIncDetId")
                        .HasColumnType("bigint")
                        .HasColumnName("GRPINCDET_ID");

                    b.Property<decimal>("GrpIncDetAllocAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("GRPINCDET_ALLOCAMOUNT");

                    b.Property<decimal>("GrpIncDetAllocPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("GRPINCDET_ALLOCPERCENTAGE");

                    b.Property<string>("GrpIncDetAppStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("GRPINCDET_APPSTATUS");

                    b.Property<decimal?>("GrpIncDetApprovedAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("GRPINCDET_APPROVEDAMOUNT");

                    b.Property<long>("GrpIncDetEmpSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("GRPINCDET_EMPSYSID");

                    b.Property<long>("GrpIncDetLastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("GRPINCDET_LASTMODIFIEDBY");

                    b.Property<DateTime>("GrpIncDetLastModifiedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("GRPINCDET_LASTMODIFIEDON");

                    b.Property<long>("GrpIncDetMainId")
                        .HasColumnType("bigint")
                        .HasColumnName("GRPINCDET_MAINID");

                    b.HasKey("GrpIncDetId");

                    b.HasIndex("GrpIncDetAppStatus")
                        .HasDatabaseName("IX_GROUPINCENTIVE_DET_APPSTATUS");

                    b.HasIndex("GrpIncDetMainId")
                        .HasDatabaseName("IX_GROUPINCENTIVE_DET_MAINID");

                    b.HasIndex("GrpIncDetMainId", "GrpIncDetEmpSysId")
                        .IsUnique()
                        .HasDatabaseName("UQ_GRPINCDET");

                    b.ToTable("GROUPINCENTIVE_DET", (string)null);
                });

            modelBuilder.Entity("GroupIncentiveService.Domain.Entities.GroupIncentiveMain", b =>
                {
                    b.Property<long>("GrpIncId")
                        .HasColumnType("bigint")
                        .HasColumnName("GRPINC_ID");

                    b.Property<string>("GrpIncAppStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("GRPINC_APPSTATUS");

                    b.Property<DateTime?>("GrpIncApprovalDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("GRPINC_APPROVALDATE");

                    b.Property<decimal?>("GrpIncApprovedAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("GRPINC_APPROVEDAMOUNT");

                    b.Property<long?>("GrpIncApprover")
                        .HasColumnType("bigint")
                        .HasColumnName("GRPINC_APPROVER");

                    b.Property<long>("GrpIncEnteredBy")
                        .HasColumnType("bigint")
                        .HasColumnName("GRPINC_ENTEREDBY");

                    b.Property<DateTime>("GrpIncEnteredOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("GRPINC_ENTEREDON");

                    b.Property<int>("GrpIncGroupId")
                        .HasColumnType("int")
                        .HasColumnName("GRPINC_GROUPID");

                    b.Property<int>("GrpIncIncMonth")
                        .HasColumnType("int")
                        .HasColumnName("GRPINC_INCMONTH");

                    b.Property<int>("GrpIncIncYear")
                        .HasColumnType("int")
                        .HasColumnName("GRPINC_INCYEAR");

                    b.Property<long>("GrpIncLastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("GRPINC_LASTMODIFIEDBY");

                    b.Property<DateTime>("GrpIncLastModifiedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("GRPINC_LASTMODIFIEDON");

                    b.Property<decimal>("GrpIncTotalAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("GRPINC_TOTALAMOUNT");

                    b.HasKey("GrpIncId");

                    b.HasIndex("GrpIncAppStatus")
                        .HasDatabaseName("IX_GROUPINCENTIVE_MAIN_APPSTATUS");

                    b.HasIndex("GrpIncGroupId")
                        .HasDatabaseName("IX_GROUPINCENTIVE_MAIN_GROUPID");

                    b.ToTable("GROUPINCENTIVE_MAIN", (string)null);
                });

            modelBuilder.Entity("GroupIncentiveService.Domain.Entities.GroupMaster", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GROUP_ID");

                    b.Property<DateTime?>("GroupClsDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("GROUP_CLSDATE");

                    b.Property<string>("GroupDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GROUP_DESCRIPTION");

                    b.Property<DateTime>("GroupEffDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("GROUP_EFFDATE");

                    b.Property<long>("GroupLastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("GROUP_LASTMODIFIEDBY");

                    b.Property<DateTime>("GroupLastModifiedOn")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("GROUP_LASTMODIFIEDON");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("GROUP_NAME");

                    b.Property<string>("GroupStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("GROUP_STATUS");

                    b.HasKey("GroupId");

                    b.HasIndex("GroupName")
                        .IsUnique()
                        .HasDatabaseName("UQ_GROUP_NAME");

                    b.HasIndex("GroupStatus")
                        .HasDatabaseName("IX_Group_Master_STATUS");

                    b.ToTable("Group_Master", (string)null);
                });

            modelBuilder.Entity("GroupIncentiveService.Domain.Entities.GroupEmployeeMap", b =>
                {
                    b.HasOne("GroupIncentiveService.Domain.Entities.GroupMaster", "Group")
                        .WithMany("EmployeeMappings")
                        .HasForeignKey("GrpEmpMapGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GroupIncentiveService.Domain.Entities.GroupIncentiveApproval", b =>
                {
                    b.HasOne("GroupIncentiveService.Domain.Entities.GroupIncentiveMain", "Main")
                        .WithMany("Approvals")
                        .HasForeignKey("GrpIncAppMainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Main");
                });

            modelBuilder.Entity("GroupIncentiveService.Domain.Entities.GroupIncentiveBreak", b =>
                {
                    b.HasOne("GroupIncentiveService.Domain.Entities.GroupMaster", "Group")
                        .WithMany("IncentiveBreaks")
                        .HasForeignKey("GrpIncBrkGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GroupIncentiveService.Domain.Entities.GroupIncentiveDet", b =>
                {
                    b.HasOne("GroupIncentiveService.Domain.Entities.GroupIncentiveMain", "Main")
                        .WithMany("Details")
                        .HasForeignKey("GrpIncDetMainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Main");
                });

            modelBuilder.Entity("GroupIncentiveService.Domain.Entities.GroupIncentiveMain", b =>
                {
                    b.HasOne("GroupIncentiveService.Domain.Entities.GroupMaster", "Group")
                        .WithMany()
                        .HasForeignKey("GrpIncGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GroupIncentiveService.Domain.Entities.GroupIncentiveMain", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Details");
                });

            modelBuilder.Entity("GroupIncentiveService.Domain.Entities.GroupMaster", b =>
                {
                    b.Navigation("EmployeeMappings");

                    b.Navigation("IncentiveBreaks");
                });
#pragma warning restore 612, 618
        }
    }
}
