-- AlertsNotifications Module - Tables
USE [HRDB];
GO

-- Table: ALERT_MASTER
CREATE TABLE [ALERT_MASTER] (
    [ALERT_ID] DECIMAL(38) NOT NULL  -- Alert ID,
    [ALERT_APPS] VARCHAR(10) NOT NULL  -- Alert Apps,
    [ALERT_NAME] VARCHAR(50) NOT NULL  -- Alert Name,
    [ALERT_TYPE] VARCHAR(10) NOT NULL  -- Alert Type - WD :Workflow Direct / WO :Workflow Others  / SD :Schedulde Direct / SO : Schedulde Others,
    [ALERT_DESC] VARCHAR(200) NOT NULL  -- Alert Frequency Description,
    [ALERT_TODESC] VARCHAR(200) NULL  -- TO Email Descrciption,
    [ALERT_CCDESC] VARCHAR(200) NULL  -- CC Email Descrciption,
    [ALERT_GRADECAT] VARCHAR(3) NULL  -- ALL / NMS/ OFF,
    [ALERT_UNITSPECIFIC] CHAR(1) NULL  -- If unit specfic then 'Y' and have values Alert_unitmap table
);



-- Table: ALERTGRP_MASTER
CREATE TABLE [ALERTGRP_MASTER] (
    [ALGRP_ID] DECIMAL(22,0) NOT NULL  -- Alert Group ID,
    [ALGRP_NAME] VARCHAR(100) NOT NULL  -- Alert Group Name,
    [ALGRP_TYPE] CHAR(1) NOT NULL  -- Alert Group Type (R/P/C) Reporting Unit/Payroll Unit/Calendar Wise,
    [ALGRP_CREATEDBY] DECIMAL(38) NOT NULL  -- Created by,
    [ALGRP_CREATEDON] DATETIME2(3) NOT NULL  -- Created On,
    [ALGRP_MODIFIEDBY] DECIMAL(38) NULL  -- Modifeid by,
    [ALGRP_MODIFIEDON] DATETIME2(3) NULL  -- Modified on,
    CONSTRAINT [PK_ALERTGRP_MASTER] PRIMARY KEY ([ALGRP_ID])
);



-- Table: PROBCONFALERT
CREATE TABLE [PROBCONFALERT] (
    [PROBATION_ID] BIGINT NOT NULL,
    [PROBATION_EMPSYSID] BIGINT NOT NULL,
    [PROBATION_GRADE] BIGINT NOT NULL,
    [PROBATION_DATE] DATETIME2(3) NOT NULL,
    [SELFAPPRAISAL] CHAR(1) NULL,
    [ALERT_SENTON] DATETIME2(3) NULL
);



-- Table: CIRCULAR_LIST
CREATE TABLE [CIRCULAR_LIST] (
    [CIRCULAR_ID] BIGINT NULL,
    [CIRCULAR_NO] VARCHAR(100) NULL,
    [CIRCULAR_YEARID] INT NOT NULL,
    [CIRCULAR_TYPE] BIGINT NOT NULL,
    [CIRCULAR_ORGID] BIGINT NOT NULL,
    [CIRCULAR_BUSPECIFIC] INT NOT NULL,
    [CIRCULAR_UNITSPECIFIC] INT NOT NULL,
    [CIRCULAR_HRROLEID] INT NULL,
    [CIRCULAR_VERSIONNO] INT NOT NULL,
    [CIRCULAR_TEMPLATEID] BIGINT NULL,
    [CIRCULAR_PDFFILENAME] VARCHAR(200) NULL,
    [CIRCULAR_RTF] VARCHAR(255) NULL,
    [CIRCULAR_SIGNATORYID] BIGINT NOT NULL,
    [CIRCULAR_SPARSHFLAG] CHAR(1) NOT NULL,
    [CIRCULAR_POSTDATE] DATETIME2(3) NULL,
    [CIRCULAR_REMOVEDATE] DATETIME2(3) NULL,
    [CIRCULAR_DESC] VARCHAR(4000) NOT NULL,
    [CIRCULAR_SUBJECT] VARCHAR(1000) NOT NULL,
    [CIRCULAR_TOLIST] VARCHAR(4000) NOT NULL,
    [CIRCULAR_CCLIST] VARCHAR(4000) NULL,
    [CIRCULAR_STATUS] CHAR(1) NOT NULL,
    [CIRCULAR_ATTACHEMPFLAG] CHAR(1) NULL,
    [CIRCULAR_CREATEDBY] BIGINT NOT NULL,
    [CIRCULAR_CREATEDON] DATETIME2(3) NOT NULL,
    [CIRCULAR_MODIFIEDBY] DECIMAL(38) NOT NULL,
    [CIRCULAR_MODIFIEDON] DATETIME2(3) NOT NULL,
    [CIRCULAR_APPROVEDBY] BIGINT NULL,
    [CIRCULAR_APPROVEDON] DATETIME2(3) NULL,
    [CIRCULAR_APPREMARKS] VARCHAR(2000) NULL
);



-- Table: CIRCULAR_SIGNATORY
CREATE TABLE [CIRCULAR_SIGNATORY] (
    [CIRSIGNATORY_ID] BIGINT NOT NULL,
    [CIRSIGNATORY_UNITID] BIGINT NOT NULL,
    [CIRSIGNATORY_TYPEID] BIGINT NOT NULL,
    [CIRSIGNATORY_SIGNID] BIGINT NOT NULL,
    [CIRSIGNATORY_STATUS] CHAR(1) NOT NULL,
    [CIRSIGNATORY_CREATEDBY] BIGINT NOT NULL,
    [CIRSIGNATORY_CREATEDON] DATETIME2(3) NOT NULL
);



-- Table: CIRCULAR_TEMPLATE
CREATE TABLE [CIRCULAR_TEMPLATE] (
    [CIRTEMPLATE_ID] BIGINT NOT NULL,
    [CIRTEMPLATE_APPLYTOUNIT] BIGINT NOT NULL,
    [CIRTEMPLATE_UNITID] BIGINT NOT NULL,
    [CIRTEMPLATE_TYPEID] BIGINT NOT NULL,
    [CIRTEMPLATE_NAME] VARCHAR(200) NOT NULL,
    [CIRTEMPLATE_HTML] VARCHAR(255) NOT NULL,
    [CIRTEMPLATE_CLSDATE] DATETIME2(3) NULL,
    [CIRTEMPLATE_MODIFIEDBY] BIGINT NOT NULL,
    [CIRTEMPLATE_MODIFIEDON] DATETIME2(3) NOT NULL
);

