apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: ""
namespace: loan-services

resources:
  - ../../base

# Patch: scale microservices to 3 replicas in production
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: loan-transaction
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: loan-application
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: loan-account
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: loan-definition
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: document-service
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: lov-service
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: utility-service
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: api-gateway
  # Increase HPA max for prod
  - patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 10
    target:
      kind: HorizontalPodAutoscaler
      name: loan-transaction-hpa
  - patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 10
    target:
      kind: HorizontalPodAutoscaler
      name: loan-application-hpa
  - patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 10
    target:
      kind: HorizontalPodAutoscaler
      name: loan-account-hpa
  - patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 10
    target:
      kind: HorizontalPodAutoscaler
      name: loan-definition-hpa
  - patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 10
    target:
      kind: HorizontalPodAutoscaler
      name: document-service-hpa
  - patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 10
    target:
      kind: HorizontalPodAutoscaler
      name: lov-service-hpa
  - patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 10
    target:
      kind: HorizontalPodAutoscaler
      name: utility-service-hpa
