-- ==========================================
-- MASTER DATA MODULE - Table Definitions
-- Database: SCIDB
-- Module: Master Data Configuration
-- Created: March 9, 2026
-- ==========================================

USE SCIDB;
GO

-- Table: COMPANY_UNITMASTER
CREATE TABLE [COMPANY_UNITMASTER] (
    [COMPANY_UNIT_ID] INT NOT NULL,
    [COMPANY_UNIT_CODE] CHAR(3) NOT NULL,
    [COMPANY_UNIT_NAME] VARCHAR(1000) NOT NULL,
    CONSTRAINT [PK_COMPANY_UNITMASTER] PRIMARY KEY ([COMPANY_UNIT_ID])
);

-- Table: LOCATION_MASTER
CREATE TABLE [LOCATION_MASTER] (
    [LOCATION_ID] INT NOT NULL,
    [LOCATION_NAME] VARCHAR(50) NOT NULL,
    CONSTRAINT [PK_LOCATION_MASTER] PRIMARY KEY ([LOCATION_ID])
);

-- Table: SUPPLIER_MASTER
CREATE TABLE [SUPPLIER_MASTER] (
    [SU_CUS_COD] VARCHAR(25) NOT NULL,
    [SU_CUS_NAM] VARCHAR(100) NOT NULL,
    [SU_CUS_DET] VARCHAR(200) NULL,
    [SU_ENT_DAT] DATETIME2(3) NOT NULL,
    [SU_ENT_ID] VARCHAR(25) NOT NULL,
    [SU_ENT_NUM] DECIMAL(38) NOT NULL,
    CONSTRAINT [PK_SUPPLIER_MASTER] PRIMARY KEY ([SU_CUS_COD])
);

-- Table: ORA_STATEMASTER
CREATE TABLE [ORA_STATEMASTER] (
    [ORA_STATECODE] VARCHAR(100) NOT NULL,
    [ORA_STATENAME] VARCHAR(200) NOT NULL,
    CONSTRAINT [PK_ORA_STATEMASTER] PRIMARY KEY ([ORA_STATECODE])
);

-- Table: ORA_CITYMASTER
CREATE TABLE [ORA_CITYMASTER] (
    [ORA_CITYCODE] VARCHAR(100) NULL,
    [ORA_CITYNAME] VARCHAR(200) NULL,
    [ORA_STATECODE] VARCHAR(100) NULL
);

-- Table: AUTO_MAIL_STATUS (Auto Mail Status)
CREATE TABLE [AUTO_MAIL_STATUS] (
    [MAIL_TYPE] VARCHAR(25) NOT NULL,
    [MAIL_DATE] DATETIME2(3) NOT NULL,
    [MAIL_STATUS] CHAR(1) NOT NULL,
    [MAIL_REMARKS] VARCHAR(1000) NULL,
    CONSTRAINT [PK_AUTO_MAIL_STATUS] PRIMARY KEY ([MAIL_TYPE], [MAIL_DATE])
);

-- Table: AUTO_MAILID (Auto Mail ID)
CREATE TABLE [AUTO_MAILID] (
    [ID_TYPE] VARCHAR(25) NULL,
    [MAILID] VARCHAR(40) NULL,
    [STARTDATE] DATETIME2(3) NULL,
    [ENDDATE] DATETIME2(3) NULL,
    [MAIL_TYPE] VARCHAR(3) NULL
);

PRINT 'MASTER_DATA_MODULE Tables created successfully.';
GO
