-- ==========================================
-- Module: BOOKING
-- Description: Booking request and confirmation management
-- Tables: Core tables for managing travel bookings
-- ==========================================

USE [TRAVELDB];
GO

-- Table: BOOK_REQUEST - Booking request from employee
CREATE TABLE [BOOK_REQUEST] (
    [BK_BOK_NUM] DECIMAL(20,0) NOT NULL  -- BOOKING REQUEST NO,
    [BK_SRL_NUM] DECIMAL(20,0) NOT NULL  -- BOOKING REQUEST SERIAL NO,
    [BK_BOK_TYP] VARCHAR(1) NULL  -- TYPE OF BOOKING (S-STAY;T-TRAVEL;L-LOCAL CONVEYANCE),
    [BK_USR_COD] VARCHAR(25) NULL  -- USER ID,
    [BK_USR_NUM] BIGINT NULL  -- USER NO,
    [BK_ADM_SLF] CHAR(1) NULL  -- ARRANGEMENTS TO BE MADE BY SELF( Y - YES ; N - NO),
    [BK_ADM_UNT] INT NULL  -- ARRANGEMENT TO BE MADE BY SELF-Y,COUPON -C,ADMINUNIT-N,
    [BK_REQ_TYP] BIGINT NULL  -- REQUEST GENERATED THROUGH TOUR PLAN,
    [BK_REQ_NUM] BIGINT NULL  -- PLAN REQUEST NO,
    [BK_MOD_COD] BIGINT NULL  -- MODE OF TRAVEL/TYPE OF STAY,
    [BK_PER_STS] CHAR(1) NULL  -- BOOKINGS FOR (S)ELF; (G)UEST,
    [BK_PER_NAM] VARCHAR(200) NULL  -- BOOKING TO BE DONE FOR - PERSON NAME(S),
    [BK_FRO_DAT] DATETIME2(3) NULL  -- TRAVEL/STAY FROM DATE/TIME,
    [BK_FRM_TIM] DECIMAL(38) NULL  -- TRAVEL FROM TIME,
    [BK_RET_DAT] DATETIME2(3) NULL  -- TRAVEL RETURN FATE/STAY TO DATE/TIME,
    [BK_RET_TIM] DECIMAL(38) NULL  -- TRAVEL RETURN TIME,
    [BK_FRO_CIT] BIGINT NULL  -- CITY FROM,
    [BK_TO_CIT] BIGINT NULL  -- CITY TO,
    [BK_PCK_FLG] CHAR(2) NULL  -- PICKUP FLAG IN CASE OF LOCAL CONVEYANCE,
    [BK_FRO_LOC] VARCHAR(200) NULL  -- FROM LOCATION/PICKUP FROM,
    [BK_TO_LOC] VARCHAR(200) NULL  -- LOCATION/PICKUP TO,
    [BK_PER_SEX] CHAR(1) NULL  -- (M)ALE ; (F)EMALE,
    [BK_DEP_NOS] BIGINT NULL  -- NO OF DEPENDANTS,
    [BK_ADM_REM] VARCHAR(200) NULL  -- COMMENTS TO ADMIN(TRAVEL/STAY/PICKUP),
    [BK_BUD_AMT] DECIMAL(19,0) NULL  -- BUDGETED AMOUNT IF ANY,
    [BK_CAN_DAT] DATETIME2(3) NULL  -- CANCELLED ON,
    [BK_CAN_REM] VARCHAR(200) NULL  -- CANCELLATION REMARKS,
    [BK_CAN_USR] VARCHAR(25) NULL  -- CANCELLED BY,
    [BK_APP_STS] CHAR(1) NULL  -- BOOKING REQUEST STATUS,
    [BK_CNF_NUM] BIGINT NULL  -- BOOKING CONFIRMATION NO,
    [BK_APP_DAT] DATETIME2(3) NULL  -- Applied Date,
    [BK_TRA_CLS] BIGINT NULL  -- Travel Class,
    [BK_AIR_COD] CHAR(3) NULL  -- Airline Code,
    [BK_TRVL_TYPE] BIGINT NULL  -- 1-Own Arrangement,2-Sponsored by others,
    [BK_CAB_TO_FLG] CHAR(1) NULL,
    [BK_CAB_TO_UNIT] CHAR(3) NULL,
    [BK_CAB_TO_COST] VARCHAR(25) NULL,
    [BK_CAB_TO_ADD] VARCHAR(500) NULL,
    [BK_CAB_TO_TRIP] CHAR(1) NULL,
    [BK_CAB_SEGMENT] BIGINT NULL,
    [BK_PRODUCT_CODE] VARCHAR(25) NULL,
    [BK_SUBACCOUNT_CODE] VARCHAR(25) NULL,
    CONSTRAINT [PK_BOOK_REQUEST] PRIMARY KEY ([BK_BOK_NUM])
);

-- Table: BOOK_CONFIRMATION - Booking confirmation after admin approval
CREATE TABLE [BOOK_CONFIRMATION] (
    [BK_CNF_NUM] BIGINT NOT NULL  -- BOOKING CONFIRMATION NO,
    [BK_CNF_SRL] BIGINT NOT NULL  -- BOOKING CONFIRMATION SERIAL,
    [BK_BOK_NUM] BIGINT NULL  -- BOOKING REQUEST NO,
    [BK_SRL_NUM] BIGINT NULL  -- BOOKING REQUEST SERIAL NO,
    [BK_REQ_DAT] DATETIME2(3) NULL  -- REQUESTED ON,
    [BK_FRO_DAT] DATETIME2(3) NULL  -- TRAVEL/STAY FROM DATE/TIME,
    [BK_TO_DAT] DATETIME2(3) NULL  -- TRAVEL/STAY TO DATE/TIME,
    [BK_FRO_CIT] BIGINT NULL  -- CITY FROM,
    [BK_TO_CIT] BIGINT NULL  -- CITY to,
    [BK_MOD_COD] BIGINT NOT NULL  -- MODE OF TRAVEL/TYPE OF STAY,
    [BK_FRM_LOC] VARCHAR(200) NULL  -- From Location for others,
    [BK_TO_LOC] VARCHAR(200) NULL  -- To Location for others,
    [BK_AIR_LIN] CHAR(3) NULL  -- Airline code,
    [BK_TRL_NUM] VARCHAR(50) NULL  -- Flight No/Train Number/BusNumber/Cab Registration No,
    [BK_TRL_NAM] VARCHAR(200) NULL  -- Train Name/Bus Name/Hotel Name/Cab Name,
    [BK_ADM_RMK] VARCHAR(2000) NULL  -- Admin Remarks,
    [BK_TRL_CLS] BIGINT NULL  -- Class of Travel,
    [BK_VND_COD] BIGINT NULL  -- Vendor code,
    [BK_GHE_COD] BIGINT NULL  -- Guest House Code,
    [BK_ROM_NUM] CHAR(10) NULL  -- Room number,
    [BK_PHE_NUM] BIGINT NULL  -- Operator Phone number/contact number,
    [BK_CPN_COD] BIGINT NULL  -- Coupon Code,
    [BK_CPN_TCK] BIGINT NULL  -- Coupon Ticket No,
    [BK_STS_COD] CHAR(1) NULL  -- C-Cancelled K-Request for cancellation N-New Y - Confirmed,
    [BK_NO_PER] BIGINT NULL  -- No of Persons,
    [BK_DRV_NAM] VARCHAR(50) NULL  -- Driver Name,
    [BK_TRL_CST] BIGINT NULL  -- Cost beared by company in case of company arrangement,
    [BK_SLF_CST] BIGINT NULL  -- Cost in case of self Arrangement Else 0,
    [BK_SLF_FLG] CHAR(1) NULL  -- In case of Self Booking -Y,Else in case of Admin Booking -N,
    [BK_TCK_NUM] VARCHAR(25) NULL  -- Ticket number,
    [BK_AGN_COD] BIGINT NULL  -- AGENCY CODE,
    [BK_TRVL_TYPE] BIGINT NULL  -- 1-Own Arrangement,2-Sponsored by others,
    [BK_CAB_UNIT] CHAR(3) NULL,
    [BK_COST_COD] VARCHAR(25) NULL,
    [BK_CAB_ADD] VARCHAR(500) NULL,
    [BK_TRIP_COD] CHAR(1) NULL,
    [BK_CAB_SEGMENT] BIGINT NULL,
    [BK_APP_STS] CHAR(1) NULL,
    [BK_ADMN_BOKDAT] DATETIME2(3) NULL,
    [BK_REGN_NO] VARCHAR(50) NULL,
    [BK_PRODUCT_CODE] VARCHAR(25) NULL,
    [BK_SUBACCOUNT_CODE] VARCHAR(25) NULL,
    CONSTRAINT [PK_BOOK_CONFIRMATION] PRIMARY KEY ([BK_CNF_NUM])
);

-- Table: BOOK_FORWARD_UNIT - Booking forwarding to admin units
CREATE TABLE [BOOK_FORWARD_UNIT] (
    [BK_BOK_NUM] DECIMAL(20,0) NOT NULL,
    [BK_SRL_NUM] DECIMAL(20,0) NOT NULL,
    [ADM_UNIT] BIGINT NOT NULL,
    [FWD_ADM_UNIT] BIGINT NOT NULL,
    [FWD_DATE] DATETIME2(3) NULL
);

-- Table: COUPON_REQUEST - Coupon/Ticket request
CREATE TABLE [COUPON_REQUEST] (
    [CPN_REQ_ID] BIGINT NOT NULL,
    [CPN_REQ_DAT] DATETIME2(3) NULL,
    [CPN_REQ_USR] VARCHAR(50) NULL,
    [CPN_NOF_CPN] BIGINT NULL,
    [CPN_ARL_NAM] CHAR(3) NULL,
    [CPN_REQ_RMK] VARCHAR(500) NULL,
    [CPN_ARG_UNT] BIGINT NULL,
    [CPN_APV_USR] VARCHAR(50) NULL,
    [CPN_ACT_DAT] DATETIME2(3) NULL,
    [CPN_REQ_STS] CHAR(1) NULL,
    [CPN_ACT_RMK] VARCHAR(500) NULL,
    [CPN_FLX_FLD1] BIGINT NULL,
    [CPN_FLX_FLD2] VARCHAR(200) NULL,
    [CPN_FLX_FLD3] DATETIME2(3) NULL,
    [CPN_FLX_FLD4] VARCHAR(500) NULL,
    CONSTRAINT [PK_COUPON_REQUEST] PRIMARY KEY ([CPN_REQ_ID])
);

-- Table: COUPON_MAIN - Coupon main record
CREATE TABLE [COUPON_MAIN] (
    [CPN_CUP_ID] BIGINT NOT NULL,
    [CPN_REF_ID] VARCHAR(25) NULL,
    [CPN_REQ_ID] BIGINT NULL,
    [CPN_NOF_TCK] BIGINT NULL,
    [CPN_ARL_NAM] CHAR(3) NULL,
    [CPN_CUP_STR] BIGINT NULL,
    [CPN_CUP_END] BIGINT NULL,
    [CPN_VLD_FRM] DATETIME2(3) NULL,
    [CPN_VLD_TO] DATETIME2(3) NULL,
    [CPN_CUP_CST] BIGINT NULL,
    [CPN_ISE_REK] VARCHAR(500) NULL,
    [CPN_USG_FLG] CHAR(1) NULL,
    [CPN_USR_ID] VARCHAR(50) NULL,
    [CPN_USR_PIN] BIGINT NULL,
    [CPN_ADN_USR] VARCHAR(50) NULL,
    [CPN_ADN_UNT] CHAR(5) NULL,
    [CPN_ISS_DAT] DATETIME2(3) NULL,
    [CPN_FLX_FLD1] BIGINT NULL,
    [CPN_FLX_FLD2] VARCHAR(25) NULL,
    [CPN_FLX_FLD3] DATETIME2(3) NULL,
    [CPN_FLX_FLD] CHAR(5) NULL,
    CONSTRAINT [PK_COUPON_MAIN] PRIMARY KEY ([CPN_CUP_ID])
);

-- Table: COUPON_SUB - Coupon ticket details
CREATE TABLE [COUPON_SUB] (
    [CPN_CUP_ID] BIGINT NULL,
    [CPN_SRL_NUM] BIGINT NULL,
    [CPN_TCK_NUM] VARCHAR(20) NULL,
    [CPN_USG_FLG] CHAR(1) NULL
);

-- Table: CABPICK - Cab pickup configuration
CREATE TABLE [CABPICK] (
    [CITYFROM] VARCHAR(25) NULL,
    [CITYTO] VARCHAR(25) NULL,
    [PICKFLAG] VARCHAR(4) NULL
);

-- Table: ROOMAVAIL_TEMP - Temporary room availability
CREATE TABLE [ROOMAVAIL_TEMP] (
    [BK_GHCODE] BIGINT NULL,
    [BK_ROOMNO] CHAR(10) NULL,
    [BK_FRODAT] DATETIME2(3) NULL,
    [BK_TODAT] DATETIME2(3) NULL,
    [TOTALHR_OCCUPIED] INT NULL
);

GO
