// <auto-generated />
using System;
using AccountingService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    partial class AccountingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountingService.Domain.Entities.AccountDetail", b =>
                {
                    b.Property<long>("AcSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("AC_SYS_ID");

                    b.Property<string>("AcDcType")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("AC_DC_TYPE");

                    b.Property<DateTime>("AcDocDat")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("AC_DOC_DAT");

                    b.Property<long>("AcDocNo")
                        .HasColumnType("bigint")
                        .HasColumnName("AC_DOC_NO");

                    b.Property<long>("AcFinYer")
                        .HasColumnType("bigint")
                        .HasColumnName("AC_FIN_YER");

                    b.Property<string>("AcMainCode")
                        .IsRequired()
                        .HasColumnType("CHAR(6)")
                        .HasColumnName("AC_MAIN_CODE");

                    b.Property<string>("AcRefTranCode")
                        .IsRequired()
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("AC_REF_TRANCODE");

                    b.Property<long>("AcRefTranNo")
                        .HasColumnType("bigint")
                        .HasColumnName("AC_REF_TRANNO");

                    b.Property<string>("AcRemarks")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("AC_REMARKS");

                    b.Property<string>("AcSubCode")
                        .IsRequired()
                        .HasColumnType("CHAR(6)")
                        .HasColumnName("AC_SUB_CODE");

                    b.Property<decimal>("AcTranAmt")
                        .HasColumnType("DECIMAL(19,0)")
                        .HasColumnName("AC_TRAN_AMT");

                    b.Property<string>("AcTranCode")
                        .IsRequired()
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("AC_TRAN_CODE");

                    b.Property<long>("AcTranNo")
                        .HasColumnType("bigint")
                        .HasColumnName("AC_TRAN_NO");

                    b.Property<string>("AcTrustCode")
                        .IsRequired()
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("AC_TRUST_CODE");

                    b.HasKey("AcSysId");

                    b.HasIndex("AcTrustCode", "AcDocDat")
                        .HasDatabaseName("IDX_ACC_DET_TRUST_DATE");

                    b.ToTable("ACC_DET", (string)null);
                });

            modelBuilder.Entity("AccountingService.Domain.Entities.AccountLookup", b =>
                {
                    b.Property<string>("ConTyp")
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("CON_TYP");

                    b.Property<long?>("AccCod")
                        .HasColumnType("bigint")
                        .HasColumnName("ACC_COD");

                    b.Property<string>("EdCod")
                        .IsRequired()
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("ED_COD");

                    b.Property<string>("TrnTyp")
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("TRN_TYP");

                    b.HasKey("ConTyp");

                    b.ToTable("ACC_LOOKUP", (string)null);
                });

            modelBuilder.Entity("AccountingService.Domain.Entities.GlPosting", b =>
                {
                    b.Property<long>("PostingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("POSTING_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PostingId"));

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ACCOUNT_CODE");

                    b.Property<decimal>("CreditAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(19,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("CREDIT_AMOUNT");

                    b.Property<decimal>("DebitAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(19,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("DEBIT_AMOUNT");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("POSTING_DATE");

                    b.Property<string>("PostingRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("POSTING_REMARKS");

                    b.Property<long>("ReferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("REFERENCE_ID");

                    b.HasKey("PostingId");

                    b.HasIndex("AccountCode", "PostingDate")
                        .HasDatabaseName("IDX_GL_POSTING_ACCOUNT");

                    b.ToTable("GL_POSTING", (string)null);
                });

            modelBuilder.Entity("AccountingService.Domain.Entities.MainAccount", b =>
                {
                    b.Property<string>("MainAccountCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MAIN_ACCOUNT_CODE");

                    b.Property<string>("MainAccountName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MAIN_ACCOUNT_NAME");

                    b.Property<string>("MainAccountShrtName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MAIN_ACCOUNT_SHRT_NAME");

                    b.Property<string>("MainClosureFlag")
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("MAIN_CLOSURE_FLAG");

                    b.HasKey("MainAccountCode");

                    b.ToTable("MAINACCOUNT_MASTER", (string)null);

                    b.HasData(
                        new
                        {
                            MainAccountCode = "100000",
                            MainAccountName = "Cash and Cash Equivalents",
                            MainAccountShrtName = "Cash",
                            MainClosureFlag = "N"
                        },
                        new
                        {
                            MainAccountCode = "110000",
                            MainAccountName = "Bank Accounts",
                            MainAccountShrtName = "Bank",
                            MainClosureFlag = "N"
                        },
                        new
                        {
                            MainAccountCode = "200000",
                            MainAccountName = "Member Contributions Payable",
                            MainAccountShrtName = "Contributions",
                            MainClosureFlag = "N"
                        },
                        new
                        {
                            MainAccountCode = "210000",
                            MainAccountName = "Employer Contributions",
                            MainAccountShrtName = "Emp Contrib",
                            MainClosureFlag = "N"
                        },
                        new
                        {
                            MainAccountCode = "300000",
                            MainAccountName = "Investment Portfolio",
                            MainAccountShrtName = "Investments",
                            MainClosureFlag = "N"
                        },
                        new
                        {
                            MainAccountCode = "310000",
                            MainAccountName = "Investment Income",
                            MainAccountShrtName = "Inv Income",
                            MainClosureFlag = "N"
                        },
                        new
                        {
                            MainAccountCode = "400000",
                            MainAccountName = "Operating Expenses",
                            MainAccountShrtName = "Expenses",
                            MainClosureFlag = "N"
                        },
                        new
                        {
                            MainAccountCode = "410000",
                            MainAccountName = "Administrative Expenses",
                            MainAccountShrtName = "Admin Exp",
                            MainClosureFlag = "N"
                        },
                        new
                        {
                            MainAccountCode = "500000",
                            MainAccountName = "Member Benefits Payable",
                            MainAccountShrtName = "Benefits",
                            MainClosureFlag = "N"
                        },
                        new
                        {
                            MainAccountCode = "510000",
                            MainAccountName = "Withdrawal Benefits",
                            MainAccountShrtName = "Withdrawals",
                            MainClosureFlag = "N"
                        });
                });

            modelBuilder.Entity("AccountingService.Domain.Entities.PfSubAccount", b =>
                {
                    b.Property<long>("SubAccCod")
                        .HasColumnType("bigint")
                        .HasColumnName("SUB_ACC_COD");

                    b.Property<string>("SubAccNam")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SUB_ACC_NAM");

                    b.HasKey("SubAccCod");

                    b.ToTable("PF_SUB_ACCOUNT", (string)null);

                    b.HasData(
                        new
                        {
                            SubAccCod = 1001L,
                            SubAccNam = "Employee Contribution"
                        },
                        new
                        {
                            SubAccCod = 1002L,
                            SubAccNam = "Employer Contribution"
                        },
                        new
                        {
                            SubAccCod = 1003L,
                            SubAccNam = "Voluntary Contribution"
                        },
                        new
                        {
                            SubAccCod = 2001L,
                            SubAccNam = "Normal Withdrawal"
                        },
                        new
                        {
                            SubAccCod = 2002L,
                            SubAccNam = "Death Benefit"
                        },
                        new
                        {
                            SubAccCod = 2003L,
                            SubAccNam = "Disability Benefit"
                        },
                        new
                        {
                            SubAccCod = 3001L,
                            SubAccNam = "Fixed Deposit Return"
                        },
                        new
                        {
                            SubAccCod = 3002L,
                            SubAccNam = "Equity Dividend"
                        });
                });

            modelBuilder.Entity("AccountingService.Domain.Entities.TransactionDetail", b =>
                {
                    b.Property<string>("TdTrustCode")
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("TD_TRUST_CODE");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int")
                        .HasColumnName("TRANSACTION_ID");

                    b.Property<decimal>("TdAmount")
                        .HasColumnType("DECIMAL(19,0)")
                        .HasColumnName("TD_AMOUNT");

                    b.Property<DateTime?>("TdCancelDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("TD_CANCEL_DATE");

                    b.Property<long?>("TdCancelStatus")
                        .HasColumnType("bigint")
                        .HasColumnName("TD_CANCEL_STATUS");

                    b.Property<string>("TdContributionReferenceNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TD_CONTRIBUTION_REFERENCE_NO");

                    b.Property<long>("TdFinyear")
                        .HasColumnType("bigint")
                        .HasColumnName("TD_FINYEAR");

                    b.Property<string>("TdJvNo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TD_JV_NO");

                    b.Property<string>("TdJvVoucherType")
                        .IsRequired()
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("TD_JV_VOUCHER_TYPE");

                    b.Property<string>("TdLastModifiedEmpSysid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TD_LAST_MODIFIED_EMP_SYSID");

                    b.Property<DateTime>("TdLastModifiedOn")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("TD_LAST_MODIFIED_ON");

                    b.Property<int?>("TdMemberNo")
                        .HasColumnType("int")
                        .HasColumnName("TD_MEMBER_NO");

                    b.Property<string>("TdReferenceType")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("TD_REFERENCE_TYPE");

                    b.Property<string>("TdRemarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TD_REMARKS");

                    b.Property<string>("TdTransactionCode")
                        .IsRequired()
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("TD_TRANSACTION_CODE");

                    b.Property<DateTime>("TdTransactionDate")
                        .HasColumnType("DATETIME2(3)")
                        .HasColumnName("TD_TRANSACTION_DATE");

                    b.Property<string>("TdTransactionType")
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("TD_TRANSACTION_TYPE");

                    b.Property<string>("TdTrnSubType")
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("TD_TRN_SUB_TYPE");

                    b.Property<string>("TdTypeCode")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("TD_TYPE_CODE");

                    b.HasKey("TdTrustCode", "TransactionId");

                    b.HasIndex("TdTransactionType", "TdTransactionDate")
                        .HasDatabaseName("IDX_TRAN_DET_TYPE");

                    b.ToTable("TRAN_DET", (string)null);
                });

            modelBuilder.Entity("AccountingService.Domain.Entities.TransactionMaster", b =>
                {
                    b.Property<string>("TransactionTrustCode")
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("TRANSACTION_TRUST_CODE");

                    b.Property<string>("TransactionCode")
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("TRANSACTION_CODE");

                    b.Property<string>("TransactionName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("TRANSACTION_NAME");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("TRANSACTION_TYPE");

                    b.Property<string>("TransactionValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TRANSACTION_VALUE");

                    b.HasKey("TransactionTrustCode", "TransactionCode");

                    b.ToTable("TRANSACTION_MASTER", (string)null);

                    b.HasData(
                        new
                        {
                            TransactionTrustCode = "PF1",
                            TransactionCode = "CON",
                            TransactionName = "Contributions",
                            TransactionType = "C  ",
                            TransactionValue = "Member Contribution"
                        },
                        new
                        {
                            TransactionTrustCode = "PF1",
                            TransactionCode = "WIT",
                            TransactionName = "Withdrawal",
                            TransactionType = "W  ",
                            TransactionValue = "Member Withdrawal"
                        },
                        new
                        {
                            TransactionTrustCode = "PF1",
                            TransactionCode = "JV1",
                            TransactionName = "Journal Voucher",
                            TransactionType = "J  ",
                            TransactionValue = "Journal Entry"
                        },
                        new
                        {
                            TransactionTrustCode = "PF1",
                            TransactionCode = "DIV",
                            TransactionName = "Dividend",
                            TransactionType = "D  ",
                            TransactionValue = "Investment Dividend"
                        },
                        new
                        {
                            TransactionTrustCode = "PF1",
                            TransactionCode = "TRF",
                            TransactionName = "Transfer In/Out",
                            TransactionType = "T  ",
                            TransactionValue = "Fund Transfer"
                        },
                        new
                        {
                            TransactionTrustCode = "PF2",
                            TransactionCode = "CON",
                            TransactionName = "Contributions",
                            TransactionType = "C  ",
                            TransactionValue = "Member Contribution"
                        },
                        new
                        {
                            TransactionTrustCode = "PF2",
                            TransactionCode = "WIT",
                            TransactionName = "Withdrawal",
                            TransactionType = "W  ",
                            TransactionValue = "Member Withdrawal"
                        });
                });

            modelBuilder.Entity("AccountingService.Domain.Entities.GlPosting", b =>
                {
                    b.HasOne("AccountingService.Domain.Entities.MainAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GL_POSTING_ACCOUNT");

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
