-- Seed Data Script for REFERENCEDB
-- This script populates reference data for testing and initial setup

USE REFERENCEDB;
GO

-- ==========================================
-- Seed LOV Types
-- ==========================================
SET IDENTITY_INSERT LOV_TYPEMAST OFF;
GO

IF NOT EXISTS (SELECT 1 FROM LOV_TYPEMAST WHERE LOV_TYPEID = 1)
BEGIN
    INSERT INTO LOV_TYPEMAST (LOV_TYPEID, LOV_TYPENAME, LOV_DESCRIPTION, LOV_TYPESEQ, LOV_STATUS, LOV_LASTMODIFIEDBY, LOV_LASTMODIFIEDON)
    VALUES (1, 'DEPARTMENT', 'Department Master', 1, 'Y', 1, GETDATE());
END
GO

IF NOT EXISTS (SELECT 1 FROM LOV_TYPEMAST WHERE LOV_TYPEID = 2)
BEGIN
    INSERT INTO LOV_TYPEMAST (LOV_TYPEID, LOV_TYPENAME, LOV_DESCRIPTION, LOV_TYPESEQ, LOV_STATUS, LOV_LASTMODIFIEDBY, LOV_LASTMODIFIEDON)
    VALUES (2, 'DESIGNATION', 'Designation Master', 2, 'Y', 1, GETDATE());
END
GO

IF NOT EXISTS (SELECT 1 FROM LOV_TYPEMAST WHERE LOV_TYPEID = 3)
BEGIN
    INSERT INTO LOV_TYPEMAST (LOV_TYPEID, LOV_TYPENAME, LOV_DESCRIPTION, LOV_TYPESEQ, LOV_STATUS, LOV_LASTMODIFIEDBY, LOV_LASTMODIFIEDON)
    VALUES (3, 'EMPLOYEE_STATUS', 'Employee Status', 3, 'Y', 1, GETDATE());
END
GO

-- ==========================================
-- Seed LOV Values for DEPARTMENT
-- ==========================================
IF NOT EXISTS (SELECT 1 FROM LOV_MAST WHERE LOV_ID = 1)
BEGIN
    INSERT INTO LOV_MAST (LOV_ID, LOV_TYPEID, LOV_CODE, LOV_DESCRIPTION, LOV_LONGDESCRIPTION, LOV_SEQUENCE, LOV_STATUS, LOV_LASTMODIFIEDBY, LOV_LASTMODIFIEDON)
    VALUES (1, 1, 'IT', 'Information Technology', 'Information Technology Department', 1, 'Y', 1, GETDATE());
END
GO

IF NOT EXISTS (SELECT 1 FROM LOV_MAST WHERE LOV_ID = 2)
BEGIN
    INSERT INTO LOV_MAST (LOV_ID, LOV_TYPEID, LOV_CODE, LOV_DESCRIPTION, LOV_LONGDESCRIPTION, LOV_SEQUENCE, LOV_STATUS, LOV_LASTMODIFIEDBY, LOV_LASTMODIFIEDON)
    VALUES (2, 1, 'HR', 'Human Resources', 'Human Resources Department', 2, 'Y', 1, GETDATE());
END
GO

IF NOT EXISTS (SELECT 1 FROM LOV_MAST WHERE LOV_ID = 3)
BEGIN
    INSERT INTO LOV_MAST (LOV_ID, LOV_TYPEID, LOV_CODE, LOV_DESCRIPTION, LOV_LONGDESCRIPTION, LOV_SEQUENCE, LOV_STATUS, LOV_LASTMODIFIEDBY, LOV_LASTMODIFIEDON)
    VALUES (3, 1, 'FIN', 'Finance', 'Finance Department', 3, 'Y', 1, GETDATE());
END
GO

-- ==========================================
-- Seed LOV Values for DESIGNATION
-- ==========================================
IF NOT EXISTS (SELECT 1 FROM LOV_MAST WHERE LOV_ID = 4)
BEGIN
    INSERT INTO LOV_MAST (LOV_ID, LOV_TYPEID, LOV_CODE, LOV_DESCRIPTION, LOV_LONGDESCRIPTION, LOV_SEQUENCE, LOV_STATUS, LOV_LASTMODIFIEDBY, LOV_LASTMODIFIEDON)
    VALUES (4, 2, 'MGR', 'Manager', 'Manager Level', 1, 'Y', 1, GETDATE());
END
GO

IF NOT EXISTS (SELECT 1 FROM LOV_MAST WHERE LOV_ID = 5)
BEGIN
    INSERT INTO LOV_MAST (LOV_ID, LOV_TYPEID, LOV_CODE, LOV_DESCRIPTION, LOV_LONGDESCRIPTION, LOV_SEQUENCE, LOV_STATUS, LOV_LASTMODIFIEDBY, LOV_LASTMODIFIEDON)
    VALUES (5, 2, 'SE', 'Software Engineer', 'Software Engineer Level', 2, 'Y', 1, GETDATE());
END
GO

-- ==========================================
-- Seed LOV Values for EMPLOYEE_STATUS
-- ==========================================
IF NOT EXISTS (SELECT 1 FROM LOV_MAST WHERE LOV_ID = 6)
BEGIN
    INSERT INTO LOV_MAST (LOV_ID, LOV_TYPEID, LOV_CODE, LOV_DESCRIPTION, LOV_LONGDESCRIPTION, LOV_SEQUENCE, LOV_STATUS, LOV_LASTMODIFIEDBY, LOV_LASTMODIFIEDON)
    VALUES (6, 3, 'ACTIVE', 'Active', 'Employee is Active', 1, 'Y', 1, GETDATE());
END
GO

IF NOT EXISTS (SELECT 1 FROM LOV_MAST WHERE LOV_ID = 7)
BEGIN
    INSERT INTO LOV_MAST (LOV_ID, LOV_TYPEID, LOV_CODE, LOV_DESCRIPTION, LOV_LONGDESCRIPTION, LOV_SEQUENCE, LOV_STATUS, LOV_LASTMODIFIEDBY, LOV_LASTMODIFIEDON)
    VALUES (7, 3, 'INACTIVE', 'Inactive', 'Employee is Inactive', 2, 'Y', 1, GETDATE());
END
GO

-- ==========================================
-- Seed Permission Rules
-- ==========================================
IF NOT EXISTS (SELECT 1 FROM PERMISSION_RULES WHERE PERM_ID = 1)
BEGIN
    INSERT INTO PERMISSION_RULES (PERM_ID, PERM_RESOURCEID, PERM_ACTION, PERM_DESCRIPTION, PERM_APPCODE, PERM_STATUS, PERM_LASTMODIFIEDBY, PERM_LASTMODIFIEDON)
    VALUES (1, 'LovTypes', 'Read', 'Read LOV Types', 'REFERENCE', 'Y', 1, GETDATE());
END
GO

IF NOT EXISTS (SELECT 1 FROM PERMISSION_RULES WHERE PERM_ID = 2)
BEGIN
    INSERT INTO PERMISSION_RULES (PERM_ID, PERM_RESOURCEID, PERM_ACTION, PERM_DESCRIPTION, PERM_APPCODE, PERM_STATUS, PERM_LASTMODIFIEDBY, PERM_LASTMODIFIEDON)
    VALUES (2, 'LovTypes', 'Create', 'Create LOV Types', 'REFERENCE', 'Y', 1, GETDATE());
END
GO

IF NOT EXISTS (SELECT 1 FROM PERMISSION_RULES WHERE PERM_ID = 3)
BEGIN
    INSERT INTO PERMISSION_RULES (PERM_ID, PERM_RESOURCEID, PERM_ACTION, PERM_DESCRIPTION, PERM_APPCODE, PERM_STATUS, PERM_LASTMODIFIEDBY, PERM_LASTMODIFIEDON)
    VALUES (3, 'LovTypes', 'Update', 'Update LOV Types', 'REFERENCE', 'Y', 1, GETDATE());
END
GO

IF NOT EXISTS (SELECT 1 FROM PERMISSION_RULES WHERE PERM_ID = 4)
BEGIN
    INSERT INTO PERMISSION_RULES (PERM_ID, PERM_RESOURCEID, PERM_ACTION, PERM_DESCRIPTION, PERM_APPCODE, PERM_STATUS, PERM_LASTMODIFIEDBY, PERM_LASTMODIFIEDON)
    VALUES (4, 'LovTypes', 'Delete', 'Delete LOV Types', 'REFERENCE', 'Y', 1, GETDATE());
END
GO

-- ==========================================
-- Seed Leave Flags
-- ==========================================
IF NOT EXISTS (SELECT 1 FROM LEAVEFLAG WHERE LEAVEFLAG_ID = 1)
BEGIN
    INSERT INTO LEAVEFLAG (LEAVEFLAG_ID, LEAVEFLAG_CODE, LEAVEFLAG_DESCRIPTION, LEAVEFLAG_TYPE, LEAVEFLAG_STATUS, LEAVEFLAG_LASTMODIFIEDBY, LEAVEFLAG_LASTMODIFIEDON)
    VALUES (1, 'FULL', 'Full Day Leave', 'PAID', 'Y', 1, GETDATE());
END
GO

IF NOT EXISTS (SELECT 1 FROM LEAVEFLAG WHERE LEAVEFLAG_ID = 2)
BEGIN
    INSERT INTO LEAVEFLAG (LEAVEFLAG_ID, LEAVEFLAG_CODE, LEAVEFLAG_DESCRIPTION, LEAVEFLAG_TYPE, LEAVEFLAG_STATUS, LEAVEFLAG_LASTMODIFIEDBY, LEAVEFLAG_LASTMODIFIEDON)
    VALUES (2, 'HALF', 'Half Day Leave', 'PAID', 'Y', 1, GETDATE());
END
GO

IF NOT EXISTS (SELECT 1 FROM LEAVEFLAG WHERE LEAVEFLAG_ID = 3)
BEGIN
    INSERT INTO LEAVEFLAG (LEAVEFLAG_ID, LEAVEFLAG_CODE, LEAVEFLAG_DESCRIPTION, LEAVEFLAG_TYPE, LEAVEFLAG_STATUS, LEAVEFLAG_LASTMODIFIEDBY, LEAVEFLAG_LASTMODIFIEDON)
    VALUES (3, 'UNPAID', 'Unpaid Leave', 'UNPAID', 'Y', 1, GETDATE());
END
GO

PRINT '=== SEED DATA INSERTED SUCCESSFULLY ===';
