-- =====================================================
-- Advanced CFS (Customer Field Scheduling) Tables
-- Date-wise, Location-wise, Distance-wise Scheduling
-- with Automatic Service Order Assignment
-- =====================================================

USE [DELL_RTU_SCHEDULING]
GO

-- =====================================================
-- LOCATION_COORDINATE (Customer/Service Location Coordinates)
-- =====================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOCATION_COORDINATE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOCATION_CODE] [varchar](50) NOT NULL,
	[LOCATION_NAME] [varchar](200) NULL,
	[ADDRESS] [varchar](500) NULL,
	[CITY] [varchar](100) NULL,
	[STATE] [varchar](50) NULL,
	[PINCODE] [varchar](10) NULL,
	[LATITUDE] [decimal](10,8) NULL,
	[LONGITUDE] [decimal](11,8) NULL,
	[SERVICE_AREA] [varchar](100) NULL,
	[BRANCH] [varchar](50) NULL,
	[REMARKS] [varchar](500) NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](15) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](15) NULL,
	CONSTRAINT [PK_LOCATION_COORDINATE] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [UX_LOCATION_CODE] UNIQUE NONCLUSTERED 
	(
		[LOCATION_CODE] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- =====================================================
-- DISTANCE_MATRIX (Pre-calculated distances between locations)
-- =====================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DISTANCE_MATRIX](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[FROM_LOCATION_ID] [bigint] NOT NULL,
	[TO_LOCATION_ID] [bigint] NOT NULL,
	[DISTANCE_KM] [decimal](8,2) NULL,
	[TRAVEL_TIME_MINUTES] [int] NULL,
	[ROUTE_TYPE] [varchar](20) NULL,
	[LAST_CALCULATED] [datetime] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](15) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](15) NULL,
	CONSTRAINT [PK_DISTANCE_MATRIX] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [UX_DISTANCE_PAIR] UNIQUE NONCLUSTERED 
	(
		[FROM_LOCATION_ID] ASC,
		[TO_LOCATION_ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- =====================================================
-- ENGINEER_CAPACITY (Engineer daily/weekly capacity planning)
-- =====================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ENGINEER_CAPACITY](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ENGINEER_ID] [varchar](15) NOT NULL,
	[CAPACITY_DATE] [datetime] NOT NULL,
	[MAX_CALLS_PER_DAY] [int] NULL,
	[CURRENT_CALLS] [int] NULL,
	[AVAILABLE_CAPACITY] [int] NULL,
	[TOTAL_DRIVE_TIME_MINUTES] [int] NULL,
	[AVAILABLE_DRIVE_TIME] [int] NULL,
	[WORKLOAD_PERCENTAGE] [decimal](5,2) NULL,
	[STATUS] [varchar](20) NULL,
	[NOTES] [varchar](500) NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](15) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](15) NULL,
	CONSTRAINT [PK_ENGINEER_CAPACITY] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [UX_ENGINEER_DATE] UNIQUE NONCLUSTERED 
	(
		[ENGINEER_ID] ASC,
		[CAPACITY_DATE] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- =====================================================
-- SERVICE_ROUTE (Optimized daily routes for engineers)
-- =====================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SERVICE_ROUTE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ROUTE_ID] [varchar](20) NOT NULL,
	[ENGINEER_ID] [varchar](15) NOT NULL,
	[ROUTE_DATE] [datetime] NOT NULL,
	[ROUTE_SEQUENCE] [int] NULL,
	[TOTAL_STOPS] [int] NULL,
	[TOTAL_DISTANCE_KM] [decimal](8,2) NULL,
	[ESTIMATED_TIME_HOURS] [decimal](5,2) NULL,
	[START_LOCATION_ID] [bigint] NULL,
	[END_LOCATION_ID] [bigint] NULL,
	[OPTIMIZATION_SCORE] [decimal](5,2) NULL,
	[IS_OPTIMIZED] [bit] NULL,
	[ROUTE_STATUS] [varchar](20) NULL,
	[NOTES] [varchar](500) NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](15) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](15) NULL,
	CONSTRAINT [PK_SERVICE_ROUTE] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [UX_ROUTE_ID] UNIQUE NONCLUSTERED 
	(
		[ROUTE_ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- =====================================================
-- ROUTE_STOP (Individual stops/appointments in a route)
-- =====================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ROUTE_STOP](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ROUTE_ID] [bigint] NOT NULL,
	[SERNO_DELL] [varchar](12) NULL,
	[STOP_SEQUENCE] [int] NULL,
	[LOCATION_ID] [bigint] NULL,
	[SCHEDULED_ARRIVAL_TIME] [datetime] NULL,
	[SCHEDULED_DEPARTURE_TIME] [datetime] NULL,
	[ESTIMATED_SERVICE_DURATION_MINUTES] [int] NULL,
	[DISTANCE_FROM_PREVIOUS_KM] [decimal](8,2) NULL,
	[DRIVE_TIME_FROM_PREVIOUS_MINUTES] [int] NULL,
	[PRIORITY] [int] NULL,
	[STOP_STATUS] [varchar](20) NULL,
	[ACTUAL_ARRIVAL_TIME] [datetime] NULL,
	[ACTUAL_DEPARTURE_TIME] [datetime] NULL,
	[NOTES] [varchar](500) NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](15) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](15) NULL,
	CONSTRAINT [PK_ROUTE_STOP] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- =====================================================
-- SCHEDULING_RULE (Rules for automatic assignment)
-- =====================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SCHEDULING_RULE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[RULE_NAME] [varchar](100) NOT NULL,
	[RULE_CODE] [varchar](30) NOT NULL,
	[PRIORITY] [int] NULL,
	[MATCH_CRITERIA] [varchar](max) NULL,
	[ASSIGNMENT_LOGIC] [varchar](max) NULL,
	[DATE_RANGE_FROM] [datetime] NULL,
	[DATE_RANGE_TO] [datetime] NULL,
	[APPLICABLE_BRANCHES] [varchar](500) NULL,
	[APPLICABLE_ENGINEERS] [varchar](max) NULL,
	[LOCATION_RADIUS_KM] [decimal](8,2) NULL,
	[MAX_DISTANCE_PREFERENCE] [varchar](20) NULL,
	[AUTO_ASSIGNMENTS_ENABLED] [bit] NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](15) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](15) NULL,
	CONSTRAINT [PK_SCHEDULING_RULE] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [UX_RULE_CODE] UNIQUE NONCLUSTERED 
	(
		[RULE_CODE] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- =====================================================
-- CFS_SCHEDULE_OPTIMIZATION (Main CFS optimization record)
-- =====================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CFS_SCHEDULE_OPTIMIZATION](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[OPTIMIZATION_ID] [varchar](30) NOT NULL,
	[SCHEDULE_DATE] [datetime] NOT NULL,
	[BRANCH] [varchar](50) NULL,
	[OPTIMIZATION_TYPE] [varchar](50) NULL,
	[TOTAL_SERVICE_ORDERS] [int] NULL,
	[ASSIGNED_ORDERS] [int] NULL,
	[UNASSIGNED_ORDERS] [int] NULL,
	[TOTAL_ENGINEERS] [int] NULL,
	[ROUTES_GENERATED] [int] NULL,
	[TOTAL_DISTANCE_KM] [decimal](10,2) NULL,
	[TOTAL_DRIVE_TIME_HOURS] [decimal](8,2) NULL,
	[OPTIMIZATION_SCORE] [decimal](5,2) NULL,
	[EFFICIENCY_PERCENTAGE] [decimal](5,2) NULL,
	[OPTIMIZATION_ALGORITHM] [varchar](100) NULL,
	[EXECUTION_TIME_SECONDS] [int] NULL,
	[OPTIMIZATION_STATUS] [varchar](20) NULL,
	[EXECUTION_TIMESTAMP] [datetime] NULL,
	[NOTES] [varchar](1000) NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](15) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](15) NULL,
	CONSTRAINT [PK_CFS_SCHEDULE_OPTIMIZATION] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [UX_OPTIMIZATION_ID] UNIQUE NONCLUSTERED 
	(
		[OPTIMIZATION_ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- =====================================================
-- ASSIGNMENT_LOG (Audit log of automatic assignments)
-- =====================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ASSIGNMENT_LOG](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[SERNO_DELL] [varchar](12) NOT NULL,
	[OPTIMIZATION_ID] [varchar](30) NULL,
	[PREVIOUS_ENGINEER_ID] [varchar](15) NULL,
	[ASSIGNED_ENGINEER_ID] [varchar](15) NOT NULL,
	[ASSIGNMENT_REASON] [varchar](200) NULL,
	[MATCHING_CRITERIA] [varchar](500) NULL,
	[RULE_APPLIED] [varchar](30) NULL,
	[CONFIDENCE_SCORE] [decimal](5,2) NULL,
	[ASSIGNMENT_TYPE] [varchar](50) NULL,
	[AUTO_ASSIGNMENT] [bit] NULL,
	[APPROVED_BY] [varchar](15) NULL,
	[APPROVAL_TIMESTAMP] [datetime] NULL,
	[ASSIGNMENT_TIMESTAMP] [datetime] NULL,
	[NOTES] [varchar](500) NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](15) NULL,
	CONSTRAINT [PK_ASSIGNMENT_LOG] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- =====================================================
-- SCHEDULING_ANALYSIS (Analytics and performance metrics)
-- =====================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SCHEDULING_ANALYSIS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ANALYSIS_ID] [varchar](30) NOT NULL,
	[ANALYSIS_DATE] [datetime] NOT NULL,
	[BRANCH] [varchar](50) NULL,
	[METRIC_NAME] [varchar](100) NULL,
	[METRIC_VALUE] [decimal](10,2) NULL,
	[TARGET_VALUE] [decimal](10,2) NULL,
	[VARIANCE_PERCENTAGE] [decimal](5,2) NULL,
	[ENGINEER_ID] [varchar](15) NULL,
	[ANALYSIS_TYPE] [varchar](50) NULL,
	[DATA_PERIOD_START] [datetime] NULL,
	[DATA_PERIOD_END] [datetime] NULL,
	[INSIGHTS] [varchar](max) NULL,
	[RECOMMENDATIONS] [varchar](max) NULL,
	[ANALYSIS_TIMESTAMP] [datetime] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](15) NULL,
	CONSTRAINT [PK_SCHEDULING_ANALYSIS] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- =====================================================
-- CALENDAR_MAINTENANCE (Calendar settings and maintenance)
-- =====================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CALENDAR_MAINTENANCE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CALENDAR_DATE] [datetime] NOT NULL,
	[EVENT_TYPE] [varchar](50) NULL,
	[EVENT_NAME] [varchar](200) NULL,
	[DESCRIPTION] [varchar](500) NULL,
	[APPLICABLE_BRANCHES] [varchar](500) NULL,
	[APPLICABLE_ENGINEERS] [varchar](max) NULL,
	[IMPACT_ON_SCHEDULING] [varchar](50) NULL,
	[SCHEDULING_DISABLED] [bit] NULL,
	[START_TIME] [time] NULL,
	[END_TIME] [time] NULL,
	[RECURRING] [bit] NULL,
	[RECURRING_PATTERN] [varchar](50) NULL,
	[ISVALID] [bit] NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](15) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](15) NULL,
	CONSTRAINT [PK_CALENDAR_MAINTENANCE] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- =====================================================
-- SCHEDULING_PERFORMANCE (Performance tracking per engineer/date)
-- =====================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SCHEDULING_PERFORMANCE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PERFORMANCE_ID] [varchar](30) NOT NULL,
	[ENGINEER_ID] [varchar](15) NOT NULL,
	[PERFORMANCE_DATE] [datetime] NOT NULL,
	[SCHEDULED_CALLS] [int] NULL,
	[COMPLETED_CALLS] [int] NULL,
	[COMPLETION_RATE_PERCENTAGE] [decimal](5,2) NULL,
	[PLANNED_DISTANCE_KM] [decimal](8,2) NULL,
	[ACTUAL_DISTANCE_KM] [decimal](8,2) NULL,
	[DISTANCE_VARIANCE_PERCENTAGE] [decimal](5,2) NULL,
	[PLANNED_TIME_HOURS] [decimal](5,2) NULL,
	[ACTUAL_TIME_HOURS] [decimal](5,2) NULL,
	[TIME_VARIANCE_PERCENTAGE] [decimal](5,2) NULL,
	[CANCELLED_CALLS] [int] NULL,
	[RESCHEDULED_CALLS] [int] NULL,
	[CUSTOMER_SATISFACTION_RATING] [decimal](3,1) NULL,
	[SCHEDULING_EFFICIENCY_SCORE] [decimal](5,2) NULL,
	[ROUTE_USAGE_SCORE] [decimal](5,2) NULL,
	[NOTES] [varchar](500) NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](15) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](15) NULL,
	CONSTRAINT [PK_SCHEDULING_PERFORMANCE] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [UX_PERF_ID] UNIQUE NONCLUSTERED 
	(
		[PERFORMANCE_ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- =====================================================
-- SCHEDULING_CONFLICT (Conflicting assignments/constraints)
-- =====================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SCHEDULING_CONFLICT](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CONFLICT_ID] [varchar](30) NOT NULL,
	[SERNO_DELL] [varchar](12) NULL,
	[CONFLICT_TYPE] [varchar](50) NULL,
	[CONFLICT_DESCRIPTION] [varchar](500) NULL,
	[ENGINEER_ID] [varchar](15) NULL,
	[AFFECTED_DATE] [datetime] NULL,
	[CONFLICTING_APPOINTMENT_ID] [bigint] NULL,
	[PRIORITY] [varchar](20) NULL,
	[RESOLUTION_STATUS] [varchar](20) NULL,
	[RECOMMENDED_ACTION] [varchar](500) NULL,
	[RESOLVED_BY] [varchar](15) NULL,
	[RESOLUTION_TIMESTAMP] [datetime] NULL,
	[RESOLUTION_NOTES] [varchar](500) NULL,
	[ENTERED_ON] [datetime] NULL,
	[ENTERED_BY] [varchar](15) NULL,
	[CHANGED_ON] [datetime] NULL,
	[CHANGED_BY] [varchar](15) NULL,
	CONSTRAINT [PK_SCHEDULING_CONFLICT] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [UX_CONFLICT_ID] UNIQUE NONCLUSTERED 
	(
		[CONFLICT_ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- =====================================================
-- Create Indexes for Performance
-- =====================================================

-- LOCATION_COORDINATE Indexes
CREATE INDEX [IX_LOCATION_BRANCH] ON [dbo].[LOCATION_COORDINATE] ([BRANCH] ASC)
CREATE INDEX [IX_LOCATION_CITY] ON [dbo].[LOCATION_COORDINATE] ([CITY] ASC)
CREATE INDEX [IX_LOCATION_COORDINATES] ON [dbo].[LOCATION_COORDINATE] ([LATITUDE] ASC, [LONGITUDE] ASC)

-- ENGINEER_CAPACITY Indexes
CREATE INDEX [IX_CAPACITY_ENGINEER_DATE] ON [dbo].[ENGINEER_CAPACITY] ([ENGINEER_ID] ASC, [CAPACITY_DATE] ASC)
CREATE INDEX [IX_CAPACITY_DATE] ON [dbo].[ENGINEER_CAPACITY] ([CAPACITY_DATE] ASC)

-- SERVICE_ROUTE Indexes
CREATE INDEX [IX_ROUTE_ENGINEER_DATE] ON [dbo].[SERVICE_ROUTE] ([ENGINEER_ID] ASC, [ROUTE_DATE] ASC)
CREATE INDEX [IX_ROUTE_STATUS] ON [dbo].[SERVICE_ROUTE] ([ROUTE_STATUS] ASC)

-- CFS_SCHEDULE_OPTIMIZATION Indexes
CREATE INDEX [IX_CFS_SCHEDULE_DATE] ON [dbo].[CFS_SCHEDULE_OPTIMIZATION] ([SCHEDULE_DATE] ASC)
CREATE INDEX [IX_CFS_BRANCH_DATE] ON [dbo].[CFS_SCHEDULE_OPTIMIZATION] ([BRANCH] ASC, [SCHEDULE_DATE] ASC)

-- ASSIGNMENT_LOG Indexes
CREATE INDEX [IX_ASSIGNMENT_SERNO] ON [dbo].[ASSIGNMENT_LOG] ([SERNO_DELL] ASC)
CREATE INDEX [IX_ASSIGNMENT_ENGINEER] ON [dbo].[ASSIGNMENT_LOG] ([ASSIGNED_ENGINEER_ID] ASC)
CREATE INDEX [IX_ASSIGNMENT_DATE] ON [dbo].[ASSIGNMENT_LOG] ([ASSIGNMENT_TIMESTAMP] ASC)

-- SCHEDULING_ANALYSIS Indexes
CREATE INDEX [IX_ANALYSIS_DATE] ON [dbo].[SCHEDULING_ANALYSIS] ([ANALYSIS_DATE] ASC)
CREATE INDEX [IX_ANALYSIS_BRANCH] ON [dbo].[SCHEDULING_ANALYSIS] ([BRANCH] ASC)

-- SCHEDULING_PERFORMANCE Indexes
CREATE INDEX [IX_PERF_ENGINEER_DATE] ON [dbo].[SCHEDULING_PERFORMANCE] ([ENGINEER_ID] ASC, [PERFORMANCE_DATE] ASC)
CREATE INDEX [IX_PERF_DATE] ON [dbo].[SCHEDULING_PERFORMANCE] ([PERFORMANCE_DATE] ASC)

GO
