-- CompensationBenefits Module - Tables
USE [HRDB];
GO

-- Table: SALARY_MAIN
CREATE TABLE [SALARY_MAIN] (
    [SALARY_ID] DECIMAL(38) NOT NULL  -- Salary ID,
    [SALARY_TYPE] CHAR(1) NOT NULL  -- CTC Based / Fixed,
    [SALARY_CTC] DECIMAL(38) NOT NULL  -- CTC Amount,
    [SALARY_STRUCTUREID] DECIMAL(38) NOT NULL  -- Structure ID,
    [SALARY_FOOTERID] DECIMAL(38) NOT NULL  -- Structure ID,
    [SALARY_COPYEMPSYSID] DECIMAL(38) NULL  -- Salary Structure Copied from Another Offer Prospect No,
    [SALARY_CREATEDBY] DECIMAL(38) NOT NULL  -- Created By,
    [SALARY_CREATEDON] DATETIME2(3) NOT NULL  -- Created On,
    [SALARY_CANCELLEDBY] DECIMAL(38) NULL,
    [SALARY_CANCELLEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_SALARY_MAIN] PRIMARY KEY ([SALARY_ID])
);



-- Table: SALARY_DET
CREATE TABLE [SALARY_DET] (
    [SALDET_ID] DECIMAL(38) NOT NULL  -- Salary Detail ID,
    [SALDET_SALARYID] DECIMAL(38) NOT NULL  -- Salary ID,
    [SALDET_SRL] DECIMAL(38) NOT NULL  -- Salary Serial ID/Sort No,
    [SALDET_ANNGROUP] VARCHAR(50) NULL  -- Annexure Printing Group,
    [SALDET_EDID] DECIMAL(38) NOT NULL  -- ED ID,
    [SALDET_CATEGORY] CHAR(1) NOT NULL  -- Earnings/Retirals/Other,
    [SALDET_EDNAME] VARCHAR(50) NOT NULL  -- ED Name,
    [SALDET_EDAMT] DECIMAL(38) NOT NULL  -- ED Amount,
    [SALDET_FREQUENCY] CHAR(1) NOT NULL  -- Frequency,
    [SALDET_SUPERCHAR] VARCHAR(25) NULL  -- Superscript Notation,
    [SALDET_SUPERDESC] VARCHAR(1000) NULL  -- Superscript Remarks,
    [SALDET_YEARTYPE] CHAR(1) NULL  -- Calendar Year/Financial Year/LTA block year,
    [SALDET_GLOBALUNITID] DECIMAL(38) NULL  -- Global Unit ID,
    [SALDET_FORMULA] CHAR(1) NOT NULL  -- Y/N Formula Based component in Payroll (Only for  CalType - % on Components),
    [SALDET_SHOWMONTHLY] CHAR(1) NOT NULL,
    [SALDET_ANNEXONLY] CHAR(1) NOT NULL,
    CONSTRAINT [PK_SALARY_DET] PRIMARY KEY ([SALDET_ID])
);



-- Table: SALSTRUCTURE_MAIN
CREATE TABLE [SALSTRUCTURE_MAIN] (
    [STRUCTURE_ID] DECIMAL(38) NOT NULL  -- Structure ID,
    [STRUCTURE_UNITID] DECIMAL(38) NOT NULL  -- Reporting Unit ID,
    [STRUCTURE_NAME] VARCHAR(200) NOT NULL  -- Structure Name,
    [STRUCTURE_GRADECATEGORY] CHAR(3) NOT NULL  -- Grade Category code,
    [STRUCTURE_APPLYTOALL] DECIMAL(38) NOT NULL  -- Apply to all Grades (0- All; 1 - Selected),
    [STRUCTURE_GRADEID] DECIMAL(38) NOT NULL  -- Grade ID,
    [STRUCTURE_TYPE] CHAR(1) NOT NULL  -- Type (C)TC Based/ (F)ixed Values),
    [STRUCTURE_CTCMIN] DECIMAL(38) NOT NULL  -- Minimum CTC,
    [STRUCTURE_CTCMAX] DECIMAL(38) NOT NULL  -- Maximum CTC,
    [STRUCTURE_FOOTERID] DECIMAL(38) NOT NULL  -- Footer ID,
    [STRUCTURE_CLSDATE] DATETIME2(3) NULL  -- Closure Date,
    [STRUCTURE_CREATEDBY] DECIMAL(38) NOT NULL  -- Created By,
    [STRUCTURE_CREATEDON] DATETIME2(3) NOT NULL  -- Created On,
    [STRUCTURE_LASTMODIFIEDBY] DECIMAL(38) NOT NULL  -- Last Modified By,
    [STRUCTURE_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last Modified On,
    [STRUCTURET_APPLYTOALLUNIT] DECIMAL(38) NULL  -- Apply to all Units (0- All; 1 - Selected),
    [STRUCTURE_OFFERFOOTERID] DECIMAL(38) NULL,
    CONSTRAINT [PK_SALSTRUCTURE_MAIN] PRIMARY KEY ([STRUCTURE_ID])
);



-- Table: SALSTRUCTURE_DET
CREATE TABLE [SALSTRUCTURE_DET] (
    [STRUCTDET_ID] DECIMAL(38) NOT NULL  -- Structure Detail ID,
    [STRUCTDET_STRUCTUREID] DECIMAL(38) NOT NULL  -- Structure ID,
    [STRUCTDET_EDID] DECIMAL(38) NOT NULL  -- ED Code,
    [STRUCTDET_AMTTYPE] CHAR(1) NOT NULL,
    [STRUCTDET_CALTYPE] DECIMAL(38) NOT NULL  -- Calculation Type,
    [STRUCTDET_CATEGORY] CHAR(1) NOT NULL  -- Earnings/Retirals/Others,
    [STRUCTDET_FREQUENCY] CHAR(1) NOT NULL  -- Frequency,
    [STRUCTDET_EDAMT] DECIMAL(38) NOT NULL  -- ED Amount,
    [STRUCTDET_MINVALUE] DECIMAL(38) NOT NULL  -- Minimum Value,
    [STRUCTDET_MAXVALUE] DECIMAL(38) NULL  -- Maximum Value,
    [STRUCTDET_GLOBALUNITID] DECIMAL(38) NULL  -- Global Unit ID,
    [STRUCTDET_SUPERCHAR] VARCHAR(25) NULL  -- Superscript,
    [STRUCTDET_SUPERDESC] VARCHAR(1000) NULL  -- Superscript Description,
    [STRUCTDET_MODIFY] CHAR(1) NOT NULL  -- Allow to Modify the final ED Value at the time of Offer Letter Generation (Y/N),
    [STRUCTDET_FORMULA] CHAR(1) NOT NULL  -- Y/N Formula Based component in Payroll (Only for  CalType - % on Components),
    [STRUCTDET_CREATEDBY] DECIMAL(38) NOT NULL  -- Created By,
    [STRUCTDET_CREATEDON] DATETIME2(3) NOT NULL  -- Created On,
    [STRUCTDET_LASTMODIFIEDBY] DECIMAL(38) NOT NULL  -- Last Modified By,
    [STRUCTDET_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last Modified On,
    [STRUCTURE_SHOWMONTHLY] CHAR(1) NOT NULL,
    [STRUCTURE_ANNEXONLY] CHAR(1) NOT NULL,
    CONSTRAINT [PK_SALSTRUCTURE_DET] PRIMARY KEY ([STRUCTDET_ID])
);



-- Table: EMP_RETIRALS_EMPSPECIFIC
CREATE TABLE [EMP_RETIRALS_EMPSPECIFIC] (
    [EMPRET_ID] BIGINT NOT NULL,
    [EMPRET_EMPSYSID] BIGINT NOT NULL,
    [EMPRET_PAYTYPE] VARCHAR(3) NOT NULL,
    [EMPRET_EDID] BIGINT NOT NULL,
    [EMPRET_EFFDATE] DATETIME2(3) NOT NULL,
    [EMPRET_CLSDATE] DATETIME2(3) NULL,
    [EMPRET_PERCENTAGE] BIGINT NOT NULL,
    [EMPRET_CREATEDBY] BIGINT NOT NULL,
    [EMPRET_CREATEDON] DATETIME2(3) NOT NULL,
    [EMPRET_MODIFIEDBY] BIGINT NULL,
    [EMPRET_MODIFIEDON] DATETIME2(3) NULL
);



-- Table: EMP_RETIRALSDET
CREATE TABLE [EMP_RETIRALSDET] (
    [ERDET_ID] DECIMAL(38) NOT NULL  -- Retirals ID,
    [ERDET_EMPSYSID] DECIMAL(38) NOT NULL  -- EmpSys ID,
    [ERDET_PFCLSDATE] DATETIME2(3) NOT NULL  -- Close date,
    [ERDET_REMARKS] VARCHAR(200) NOT NULL  -- Remarks,
    [ERDET_MODIFIEDBY] DECIMAL(38) NOT NULL  -- Modified By,
    [ERDET_MODIFIEDON] DATETIME2(3) NOT NULL  -- Modified On
);



-- Table: RETRIALS_RANGEMAST
CREATE TABLE [RETRIALS_RANGEMAST] (
    [RRMAST_ID] DECIMAL(38) NOT NULL  -- ID,
    [RRMAST_UNITID] DECIMAL(38) NOT NULL  -- Unit ID,
    [RRMAST_FROMYEAR] DECIMAL(38) NOT NULL  -- from Year,
    [RRMAST_TOYEAR] DECIMAL(38) NOT NULL  -- To Year,
    [RRMAST_PERCENTAGE] DECIMAL(38) NOT NULL  -- Percentage,
    [RRMAST_MODIFIEDBY] DECIMAL(38) NOT NULL  -- Modified By,
    [RRMAST_MODIFIEDON] DATETIME2(3) NOT NULL  -- Modified On,
    CONSTRAINT [PK_RETRIALS_RANGEMAST] PRIMARY KEY ([RRMAST_ID])
);



-- Table: MEDICLAIM_MASTER
CREATE TABLE [MEDICLAIM_MASTER] (
    [MEDICLAIM_ID] DECIMAL(38) NOT NULL  -- Mediclaim ID,
    [MEDICLAIM_REFNAME] VARCHAR(200) NULL  -- Mediclain Ref Name like Policy year etc,
    [MEDICLAIM_PROVIDERID] DECIMAL(38) NULL  -- Provider ID from MEDICLAIM_PROVIDER,
    [MEDICLAIM_TPPID] DECIMAL(38) NULL  -- Third Party Provider ID from MEDICLAIM_PROVIDER,
    [MEDICLAIM_STARTDATE] DATETIME2(3) NULL  -- Start Date,
    [MEDICLAIM_CLOSEDATE] DATETIME2(3) NULL  -- End Date,
    [MEDICLAIM_MAXENTRYDATE] DATETIME2(3) NULL  -- Date up which Nomination can be made in Sparsh.,
    [MEDICLAIM_INSREFNO] VARCHAR(100) NULL  -- MEDICLAIM_INSREFNO,
    [MEDICLAIM_TYPE] VARCHAR(1) NULL  -- I/ F,
    [MEDICLAIM_PAIDBY] CHAR(1) NULL  -- Paid By  E (Employee)/C (Company / U (Up to a Level by Company),
    [MEICLAIM_SERVICETAXPER] BIGINT NULL  -- ServiceTaxPer  when Paid By value is E and U,
    [MEDICLAIM_COMPPAYLIMIT] DECIMAL(38) NULL  -- CompanyPayLimit.,
    [MEDICLAIM_LOADINGPER] BIGINT NULL,
    [MEDICLAIM_NONCLAIMPER] BIGINT NULL,
    CONSTRAINT [PK_MEDICLAIM_MASTER] PRIMARY KEY ([MEDICLAIM_ID])
);



-- Table: MEDICLAIM_DET
CREATE TABLE [MEDICLAIM_DET] (
    [MED_NOMINATIONRUNID] DECIMAL(38) NOT NULL  -- Nomination RUNID,
    [MED_NOMINATIONID] DECIMAL(38) NOT NULL  -- Nomination ID,
    [MED_RELATIONSHIP] DECIMAL(38) NOT NULL  -- Relationship ID,
    [MED_NOMINEENAME] VARCHAR(200) NOT NULL  -- Nominee Name,
    [MED_NOMINEEDOB] DATETIME2(3) NULL  -- Date of Birth,
    [MED_NOMINEEAGE] DECIMAL(38) NULL,
    [MED_NOMINEEGENDER] CHAR(1) NOT NULL  -- Gender,
    [MED_PREMIUM] DECIMAL(38) NULL  -- Premium,
    [MED_TAXSTATUS] CHAR(1) NOT NULL  -- Tax Status,
    [MED_NETPREMIUM] DECIMAL(19,0) NULL  -- Net Premium,
    [MED_PREMIUMSERVICETAX] DECIMAL(19,0) NULL  -- Service Tax,
    [MED_GROSSPREMIUM] DECIMAL(19,0) NULL  -- Gross Premium,
    CONSTRAINT [PK_MEDICLAIM_DET] PRIMARY KEY ([MED_NOMINATIONRUNID])
);



-- Table: MEDICLAIM_EXCEPTION
CREATE TABLE [MEDICLAIM_EXCEPTION] (
    [MEDICLAIM_EMPSYSID] DECIMAL(38) NOT NULL,
    [MEDICLAIM_ID] DECIMAL(38) NOT NULL
);



-- Table: MEDICLAIM_PREMPERCENTAGE
CREATE TABLE [MEDICLAIM_PREMPERCENTAGE] (
    [MED_PPID] DECIMAL(38) NOT NULL,
    [MED_RELATIONSHIPID] DECIMAL(38) NOT NULL,
    [MED_PERCENTAGE] DECIMAL(38) NOT NULL,
    CONSTRAINT [PK_MEDICLAIM_PREMPERCENTAGE] PRIMARY KEY ([MED_PPID])
);



-- Table: MEDICLAIM_YEARLYPREM
CREATE TABLE [MEDICLAIM_YEARLYPREM] (
    [MEDYP_YEARLYPREMID] DECIMAL(38) NOT NULL  -- Sequence Id,
    [MEDYP_MEDICLAIMID] DECIMAL(38) NOT NULL  -- Mediclaim ID,
    [MEDYP_SUMASSURED] DECIMAL(38) NOT NULL  -- Sum Assured,
    [MEDYP_PREMIUMAMNT] DECIMAL(38) NOT NULL  -- Premium Amount,
    [MEDYP_MODIFIEDBY] DECIMAL(38) NOT NULL  -- Modified By,
    [MEDYP_MODIFIEDON] DATETIME2(3) NOT NULL  -- Modified On,
    [MEDYP_TYPE] CHAR(1) NOT NULL  -- Type - R Regular   T Top Up,
    CONSTRAINT [PK_MEDICLAIM_YEARLYPREM] PRIMARY KEY ([MEDYP_YEARLYPREMID])
);



-- Table: MOBILE_CONNECTION
CREATE TABLE [MOBILE_CONNECTION] (
    [CONN_ID] BIGINT NOT NULL,
    [CONN_EMPSYSID] BIGINT NOT NULL,
    [CONN_EFFDATE] DATETIME2(3) NOT NULL,
    [CONN_CLSDATE] DATETIME2(3) NULL,
    [CONN_TYPE] CHAR(1) NOT NULL,
    [CONN_PHONENO] BIGINT NOT NULL,
    [CONN_REMARKS] VARCHAR(500) NULL,
    [CONN_OPENREQUESTNO] BIGINT NULL,
    [CONN_CLOSEREQUESTNO] BIGINT NULL,
    [CONN_CALENDARID] BIGINT NOT NULL,
    [CONN_CREATEDBY] BIGINT NOT NULL,
    [CONN_CREATEDON] DATETIME2(3) NOT NULL,
    [CONN_MODIFIEDBY] BIGINT NULL,
    [CONN_MODIFIEDON] DATETIME2(3) NULL
);



-- Table: MOBILE_LIMITMAST
CREATE TABLE [MOBILE_LIMITMAST] (
    [LIMIT_ID] BIGINT NOT NULL,
    [LIMIT_ORG] BIGINT NOT NULL,
    [LIMIT_UNITID] BIGINT NOT NULL,
    [LIMIT_GRADECATID] CHAR(3) NOT NULL,
    [LIMIT_GRADEID] BIGINT NOT NULL,
    [LIMIT_ELGAMT] BIGINT NOT NULL,
    [LIMIT_EFFDATE] DATETIME2(3) NOT NULL,
    [LIMIT_CLSDATE] DATETIME2(3) NULL,
    [LIMIT_CREATEDBY] BIGINT NOT NULL,
    [LIMIT_CREATEDON] DATETIME2(3) NOT NULL,
    [LIMIT_MODIFIEDBY] BIGINT NULL,
    [LIMIT_MODIFIEDON] DATETIME2(3) NULL
);



-- Table: MOBILE_ADDLIMIT
CREATE TABLE [MOBILE_ADDLIMIT] (
    [ADD_ID] BIGINT NOT NULL,
    [ADD_EMPSYSID] BIGINT NOT NULL,
    [ADD_EFFDATE] DATETIME2(3) NOT NULL,
    [ADD_CLSDATE] DATETIME2(3) NULL,
    [ADD_REMARKS] VARCHAR(500) NULL,
    [ADD_AMT] BIGINT NOT NULL,
    [ADD_CALENDARID] BIGINT NOT NULL,
    [ADD_CREATEDBY] BIGINT NOT NULL,
    [ADD_CREATEDON] DATETIME2(3) NOT NULL,
    [ADD_MODIFIEDBY] DECIMAL(38) NULL,
    [ADD_MODIFIEDON] DATETIME2(3) NULL
);



-- Table: MOBILECONNUPLOAD
CREATE TABLE [MOBILECONNUPLOAD] (
    [EMPLOYEENO] BIGINT NOT NULL,
    [EMPNAME] VARCHAR(200) NOT NULL,
    [CONNTYPE] CHAR(1) NOT NULL,
    [CONNNO] BIGINT NOT NULL,
    [CONNREMARKS] VARCHAR(250) NOT NULL,
    [REPUNIT] BIGINT NOT NULL,
    [BILLLOC] BIGINT NOT NULL,
    [EMPSYSID] BIGINT NULL,
    CONSTRAINT [PK_MOBILECONNUPLOAD] PRIMARY KEY ([EMPLOYEENO])
);



-- Table: BASIC_SLABINC
CREATE TABLE [BASIC_SLABINC] (
    [SLAB_INCID] BIGINT NOT NULL  -- Slab Increment ID,
    [SLAB_GRADEID] BIGINT NOT NULL  -- Grade ID,
    [SLAB_UNITID] BIGINT NOT NULL  -- Unit ID,
    [SLAB_INCSTRTDATE] DATETIME2(3) NOT NULL  -- Effective Date,
    [SLAB_INCCLSDATE] DATETIME2(3) NULL  -- Close Date,
    [SLAB_INCMODIFIEDBY] BIGINT NOT NULL  -- Modified By,
    [SLAB_INCMODIFIEDON] DATETIME2(3) NOT NULL  -- Modified On,
    CONSTRAINT [PK_BASIC_SLABINC] PRIMARY KEY ([SLAB_INCID])
);



-- Table: COMP_PARAMS
CREATE TABLE [COMP_PARAMS] (
    [CP_ID] DECIMAL(38) NOT NULL  -- Id,
    [CP_COUNTRYCODE] VARCHAR(3) NOT NULL  -- Country Code,
    [CP_EDGROUP] VARCHAR(3) NOT NULL  -- Ed Group,
    [CP_TYPE] VARCHAR(3) NOT NULL  -- Type EMP/COM,
    [CP_EDID] DECIMAL(38) NOT NULL  -- ED ID,
    [CP_MODIFIEDBY] DECIMAL(38) NOT NULL,
    [CP_MODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_COMP_PARAMS] PRIMARY KEY ([CP_ID])
);



-- Table: DILIGENCE_RATEMAST
CREATE TABLE [DILIGENCE_RATEMAST] (
    [DILIGENCE_ID] BIGINT NOT NULL,
    [DILIGENCE_PAYUNITID] BIGINT NOT NULL,
    [DILIGENCE_GRADECATEGORY] CHAR(3) NOT NULL,
    [DILIGENCE_EDID] BIGINT NOT NULL,
    [DILIGENCE_YEARID] INT NOT NULL,
    [DILIGENCE_AMOUNT] DECIMAL(19,0) NOT NULL,
    [DILIGENCE_EFFDATE] DATETIME2(3) NOT NULL,
    [DILIGENCE_CLSDATE] DATETIME2(3) NULL,
    [DILIGENCE_LASTMODIFIEDBY] BIGINT NOT NULL,
    [DILIGENCE_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    [DILIGENCE_BENLOGID] BIGINT NULL,
    CONSTRAINT [PK_DILIGENCE_RATEMAST] PRIMARY KEY ([DILIGENCE_ID])
);



-- Table: PMS_CASHPAY
CREATE TABLE [PMS_CASHPAY] (
    [CASHPAY_ID] DECIMAL(38) NOT NULL  -- Pay Id,
    [CASHPAY_UNITID] DECIMAL(38) NOT NULL  -- Unit Id,
    [CASHPAY_GRADECAT] VARCHAR(5) NOT NULL  -- Grade Category,
    [CASHPAY_PAYTYPE] CHAR(1) NOT NULL  -- I -Immediate P- Part Payment,
    [CASHPAY_EFFDATE] DATETIME2(3) NOT NULL  -- Effective Date,
    [CASHPAY_CLSDATE] DATETIME2(3) NULL  -- Close Date,
    [CASHPAY_MODIFIEDBY] DECIMAL(38) NOT NULL  -- Modified By,
    [CASHPAY_MODIFIEDON] DATETIME2(3) NOT NULL  -- Modified On,
    CONSTRAINT [PK_PMS_CASHPAY] PRIMARY KEY ([CASHPAY_ID])
);



-- Table: PMS_CASHPAYDET
CREATE TABLE [PMS_CASHPAYDET] (
    [CASHPAY_DETID] DECIMAL(38) NOT NULL  -- Pay Det ID,
    [CASHPAY_ID] DECIMAL(38) NOT NULL  -- Pay ID,
    [CASHPAY_PER] DECIMAL(38) NOT NULL  -- Percentage,
    [CASHPAY_PAYDATE] VARCHAR(20) NOT NULL  -- Pay Date,
    CONSTRAINT [PK_PMS_CASHPAYDET] PRIMARY KEY ([CASHPAY_DETID])
);



-- Table: EMPLOYEE_CTCREMARKS
CREATE TABLE [EMPLOYEE_CTCREMARKS] (
    [CTCREM_EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [CTCREM_ID] DECIMAL(38) NOT NULL  -- Remarks ID,
    [CTCREM_LINE1] VARCHAR(200) NULL  -- CTC Remarks Line - 1,
    [CTCREM_LINE2] VARCHAR(200) NULL  -- CTC Remarks Line - 2,
    [CTCREM_LINE3] VARCHAR(200) NULL  -- CTC Remarks Line - 3,
    [CTCREM_UPDATEDBY] DECIMAL(38) NULL  -- Last updated by,
    [CTCREM_UPDATEDON] DATETIME2(3) NULL  -- Last updated on,
    CONSTRAINT [PK_EMPLOYEE_CTCREMARKS] PRIMARY KEY ([CTCREM_EMP_SYSID])
);



-- Table: TEVCTC
CREATE TABLE [TEVCTC] (
    [CTC_EMP_SYSID] DECIMAL(38) NOT NULL,
    [CTC_ID] DECIMAL(38) NOT NULL,
    [CTC_EFF_DAT] DATETIME2(3) NOT NULL,
    [CTC_CLS_DAT] DATETIME2(3) NULL,
    [CTC_ED_ID] DECIMAL(38) NOT NULL,
    [CTC_ED_FREQ] CHAR(1) NOT NULL,
    [CTC_ED_AMTPA] DECIMAL(38) NOT NULL,
    [CTC_TRANNO] DECIMAL(38) NOT NULL,
    [CTC_SOURCE] CHAR(3) NOT NULL,
    [CTC_STRUCTUREID] DECIMAL(38) NOT NULL,
    [CTC_UPDATEDBY] DECIMAL(38) NOT NULL,
    [CTC_UPDATEDON] DATETIME2(3) NOT NULL,
    [CTC_FORMULA] CHAR(1) NOT NULL,
    [CTC_LOGNO] DECIMAL(22,0) NULL
);

