-- ==========================================
-- MODULE: SCHOLARSHIP
-- Component: Tables
-- Description: Scholarship application and tracking tables
-- Database: ADMINDB
-- ==========================================

USE [ADMINDB];
GO

-- Table: SCHOLARSHIP_AMOUNT
-- Purpose: Defines eligible scholarship amounts for different grades, exams, and financial years
CREATE TABLE [SCHOLARSHIP_AMOUNT] (
    [SCH_AMTID] BIGINT NOT NULL,
    [SCH_ORGID] BIGINT NOT NULL  -- Org ID
    [SCH_GRADECAT] CHAR(3) NOT NULL  -- Grade Category
    [SCH_ELGIBLEEXAM] VARCHAR(2) NOT NULL  -- 10 or 12
    [SCH_APPLICABLEALLGRADE] CHAR(1) NOT NULL  -- 0-All, 1-Specific ID
    [SCH_GRADEID] DECIMAL(38) NOT NULL  -- Specific Grade ID
    [SCH_FROMYEAR] DECIMAL(38) NOT NULL,
    [SCH_CLOSEYEAR] DECIMAL(38) NULL,
    [SCH_ELGIBLEAMOUNT] BIGINT NOT NULL,
    [SCH_ELGIBLEYEAR] INT NOT NULL  -- Max Course year for which scholarship is given
    [SCH_CUTOFFMARKS] INT NOT NULL,
    [SCH_CREATEDON] BIGINT NULL,
    [SCH_CREATEDBY] DATETIME2(3) NULL,
    [SCH_UPDATEDON] DATETIME2(3) NULL,
    [SCH_UPDATEDBY] BIGINT NULL,
    CONSTRAINT [PK_SCHOLARSHIP_AMOUNT] PRIMARY KEY ([SCH_AMTID])
);
GO

-- Table: SCHOLARSHIP_DETAIL
-- Purpose: Detailed records of scholarship amounts for each year of the course
CREATE TABLE [SCHOLARSHIP_DETAIL] (
    [SCHDET_ID] BIGINT NOT NULL,
    [SCHDET_MAINID] BIGINT NOT NULL,
    [SCHDET_YEAR] INT NOT NULL  -- Join Year + 1 till Max Course Year
    [SCHDET_MARKSFILE] VARCHAR(100) NOT NULL  -- Yearly Completed Certificate
    [SCHDET_MARKSTATUS] CHAR(1) NOT NULL  -- S-Scheduled, P-Uploaded/Pending, A-Approved, R-Rejected
    [SCHDET_PAYSTATUS] CHAR(1) NOT NULL  -- S-scheduled, A-HR approved, P-Pending, C-completed, O-offline paid, B-backdated
    [SCHDET_CREATEDON] DATETIME2(3) NOT NULL,
    [SCHDET_CREATEDBY] BIGINT NOT NULL,
    [SCHDET_UPDATEDON] DATETIME2(3) NULL,
    [SCHDET_UPDATEDBY] BIGINT NULL,
    [SCHDET_APPROVEDON] DATETIME2(3) NULL,
    [SCHDET_APPROVEDBY] BIGINT NULL,
    [SCHDET_PAYAPPROVEDON] DATETIME2(3) NULL,
    [SCHDET_PAYAPPROVEDBY] BIGINT NULL,
    [SCHDET_PAYDATE] DATETIME2(3) NULL,
    [SCHDET_PAYAMOUNT] BIGINT NULL,
    [SCHDET_PAYUPDATEDON] DATETIME2(3) NULL,
    [SCHDET_PAYUPDATEDBY] BIGINT NULL,
    CONSTRAINT [PK_SCHOLARSHIP_DETAIL] PRIMARY KEY ([SCHDET_ID]),
    CONSTRAINT [FK_SCHOLARSHIP_DETAIL_MAIN] FOREIGN KEY ([SCHDET_MAINID]) REFERENCES [SCHOLARSHIP_MAIN]([SCH_ID])
);
GO

-- Table: SCHOLARSHIP_MAIN
-- Purpose: Main scholarship application record for employees' children
CREATE TABLE [SCHOLARSHIP_MAIN] (
    [SCH_ID] INT NOT NULL,
    [SCH_EMPSYSID] INT NOT NULL,
    [SCH_GRADEID] INT NOT NULL,
    [SCH_DEPENDID] INT NOT NULL,
    [SCH_CHILDNAME] VARCHAR(100) NOT NULL,
    [SCH_LASTSCHOOL] VARCHAR(100) NOT NULL,
    [SCH_LASTYEAROFSCHOOL] DECIMAL(38) NOT NULL,
    [SCH_LASTEXAM] CHAR(2) NOT NULL  -- E-Entered, A-Approved, N-Not Eligible, B-Returned
    [SCH_CGPAFLAG] CHAR(1) NOT NULL,
    [SCH_MARKSPER] DECIMAL(19,0) NOT NULL,
    [SCH_MARKSGPA] DECIMAL(19,0) NOT NULL,
    [SCH_MARKSFILE] VARCHAR(100) NOT NULL,
    [SCH_COURSENAME] VARCHAR(100) NOT NULL,
    [SCH_COURSEJOINYEAR] INT NOT NULL,
    [SCH_COURSEJOINMONTH] DECIMAL(20,0) NOT NULL,
    [SCH_COURSEDURATION] BIGINT NOT NULL,
    [SCH_ADMRECPTFILE] VARCHAR(100) NULL,
    [SCH_PAYMODE] CHAR(3) NULL,
    [SCH_CHILDACCNO] VARCHAR(20) NULL,
    [SCH_CHILLDBANKIFSC] VARCHAR(12) NULL,
    [SCH_CHILLDBANKMICR] VARCHAR(12) NULL,
    [SCH_ENTRYSTATUS] CHAR(1) NULL,
    [SCH_SOURCE] CHAR(1) NOT NULL,
    [SCH_DISBAMOUNT] DECIMAL(19,0) NOT NULL,
    [SCH_DISBFREQ] CHAR(1) NOT NULL,
    [SCH_LIVESTATUS] CHAR(1) NOT NULL,
    [SCH_CREATEDON] DATETIME2(3) NOT NULL,
    [SCH_CREATEDBY] INT NOT NULL,
    [SCH_UPDATEDON] DATETIME2(3) NOT NULL,
    [SCH_UPDATEDBY] BIGINT NOT NULL,
    [SCH_APPROVALBY] INT NOT NULL,
    [SCH_APPROVALON] DATETIME2(3) NOT NULL,
    [SCH_APPREMARKS] VARCHAR(200) NOT NULL,
    [SCH_STOPREASON] VARCHAR(200) NOT NULL,
    [SCH_STOPDATE] DATETIME2(3) NOT NULL,
    [SCH_STOPENTEREDON] DATETIME2(3) NOT NULL,
    [SCH_STOPENTEREDBY] INT NOT NULL,
    [SCH_OFFLINE] CHAR(1) NOT NULL,
    [SCH_OFFLINEYEAR] INT NULL,
    CONSTRAINT [PK_SCHOLARSHIP_MAIN] PRIMARY KEY ([SCH_ID])
);
GO

-- Create indexes for performance
CREATE INDEX [IDX_SCHOLARSHIP_AMOUNT_GRADECAT] ON [SCHOLARSHIP_AMOUNT]([SCH_GRADECAT], [SCH_ELGIBLEEXAM]);
GO

CREATE INDEX [IDX_SCHOLARSHIP_MAIN_EMPSYSID] ON [SCHOLARSHIP_MAIN]([SCH_EMPSYSID]);
GO

CREATE INDEX [IDX_SCHOLARSHIP_DETAIL_MAINID] ON [SCHOLARSHIP_DETAIL]([SCHDET_MAINID]);
GO

-- ==========================================
-- END OF SCHOLARSHIP TABLES
-- ==========================================
