-- ==========================================
-- Database: ScholarshipDB
-- Microservice: Scholarship Service
-- Description: Scholarship applications, details, and eligible amounts
-- ==========================================

CREATE DATABASE ScholarshipDB;
GO

USE ScholarshipDB;
GO

-- Table: SCHOLARSHIP_MAIN
CREATE TABLE [SCHOLARSHIP_MAIN] (
    [SCH_ID] INT NOT NULL,
    [SCH_EMPSYSID] INT NOT NULL,
    [SCH_GRADEID] INT NOT NULL,
    [SCH_DEPENDID] INT NOT NULL,
    [SCH_CHILDNAME] VARCHAR(100) NOT NULL,
    [SCH_LASTSCHOOL] VARCHAR(100) NOT NULL,
    [SCH_LASTYEAROFSCHOOL] DECIMAL(38,0) NOT NULL,
    [SCH_LASTEXAM] CHAR(2) NOT NULL,
    [SCH_CGPAFLAG] CHAR(1) NOT NULL,
    [SCH_MARKSPER] DECIMAL(19,0) NOT NULL,
    [SCH_MARKSGPA] DECIMAL(19,0) NOT NULL,
    [SCH_MARKSFILE] VARCHAR(100) NOT NULL,
    [SCH_COURSENAME] VARCHAR(100) NOT NULL,
    [SCH_COURSEJOINYEAR] INT NOT NULL,
    [SCH_COURSEJOINMONTH] DECIMAL(20,0) NOT NULL,
    [SCH_COURSEDURATION] BIGINT NOT NULL,
    [SCH_ADMRECPTFILE] VARCHAR(100) NULL,
    [SCH_PAYMODE] CHAR(3) NULL,
    [SCH_CHILDACCNO] VARCHAR(20) NULL,
    [SCH_CHILLDBANKIFSC] VARCHAR(12) NULL,
    [SCH_CHILLDBANKMICR] VARCHAR(12) NULL,
    [SCH_ENTRYSTATUS] CHAR(1) NULL,
    [SCH_SOURCE] CHAR(1) NOT NULL,
    [SCH_DISBAMOUNT] DECIMAL(19,0) NOT NULL,
    [SCH_DISBFREQ] CHAR(1) NOT NULL,
    [SCH_LIVESTATUS] CHAR(1) NOT NULL,
    [SCH_CREATEDON] DATETIME2(3) NOT NULL,
    [SCH_CREATEDBY] INT NOT NULL,
    [SCH_UPDATEDON] DATETIME2(3) NOT NULL,
    [SCH_UPDATEDBY] BIGINT NOT NULL,
    [SCH_APPROVALBY] INT NOT NULL,
    [SCH_APPROVALON] DATETIME2(3) NOT NULL,
    [SCH_APPREMARKS] VARCHAR(200) NOT NULL,
    [SCH_STOPREASON] VARCHAR(200) NOT NULL,
    [SCH_STOPDATE] DATETIME2(3) NOT NULL,
    [SCH_STOPENTEREDON] DATETIME2(3) NOT NULL,
    [SCH_STOPENTEREDBY] INT NOT NULL,
    [SCH_OFFLINE] CHAR(1) NOT NULL,
    [SCH_OFFLINEYEAR] INT NULL,
    CONSTRAINT [PK_SCHOLARSHIP_MAIN] PRIMARY KEY ([SCH_ID])
);

-- Table: SCHOLARSHIP_DETAIL
CREATE TABLE [SCHOLARSHIP_DETAIL] (
    [SCHDET_ID] BIGINT NOT NULL,
    [SCHDET_MAINID] BIGINT NOT NULL,
    [SCHDET_YEAR] INT NOT NULL,
    [SCHDET_MARKSFILE] VARCHAR(100) NOT NULL,
    [SCHDET_MARKSTATUS] CHAR(1) NOT NULL,
    [SCHDET_PAYSTATUS] CHAR(1) NOT NULL,
    [SCHDET_CREATEDON] DATETIME2(3) NOT NULL,
    [SCHDET_CREATEDBY] BIGINT NOT NULL,
    [SCHDET_UPDATEDON] DATETIME2(3) NULL,
    [SCHDET_UPDATEDBY] BIGINT NULL,
    [SCHDET_APPROVEDON] DATETIME2(3) NULL,
    [SCHDET_APPROVEDBY] BIGINT NULL,
    [SCHDET_PAYAPPROVEDON] DATETIME2(3) NULL,
    [SCHDET_PAYAPPROVEDBY] BIGINT NULL,
    [SCHDET_PAYDATE] DATETIME2(3) NULL,
    [SCHDET_PAYAMOUNT] BIGINT NULL,
    [SCHDET_PAYUPDATEDON] DATETIME2(3) NULL,
    [SCHDET_PAYUPDATEDBY] BIGINT NULL,
    CONSTRAINT [PK_SCHOLARSHIP_DETAIL] PRIMARY KEY ([SCHDET_ID])
);

-- Table: SCHOLARSHIP_AMOUNT
CREATE TABLE [SCHOLARSHIP_AMOUNT] (
    [SCH_AMTID] BIGINT NULL,
    [SCH_ORGID] BIGINT NOT NULL,
    [SCH_GRADECAT] CHAR(3) NOT NULL,
    [SCH_ELGIBLEEXAM] VARCHAR(2) NOT NULL,
    [SCH_APPLICABLEALLGRADE] CHAR(1) NOT NULL,
    [SCH_GRADEID] DECIMAL(38) NOT NULL,
    [SCH_FROMYEAR] DECIMAL(38) NOT NULL,
    [SCH_CLOSEYEAR] DECIMAL(38) NULL,
    [SCH_ELGIBLEAMOUNT] BIGINT NOT NULL,
    [SCH_ELGIBLEYEAR] INT NOT NULL,
    [SCH_CUTOFFMARKS] INT NOT NULL,
    [SCH_CREATEDON] BIGINT NULL,
    [SCH_CREATEDBY] DATETIME2(3) NULL,
    [SCH_UPDATEDON] DATETIME2(3) NULL,
    [SCH_UPDATEDBY] BIGINT NULL,
    CONSTRAINT [PK_SCHOLARSHIP_AMOUNT] PRIMARY KEY ([SCH_AMTID])
);

-- Function: fn_GetScholarshipEligibleAmount
CREATE OR ALTER FUNCTION dbo.fn_GetScholarshipEligibleAmount
(
    @p_GradeCat CHAR(3),
    @p_EligibleExam VARCHAR(2),
    @p_Year INT
)
RETURNS BIGINT
AS
BEGIN
    DECLARE @Amount BIGINT;
    SELECT TOP 1 @Amount = SCH_ELGIBLEAMOUNT
    FROM SCHOLARSHIP_AMOUNT
    WHERE SCH_GRADECAT = @p_GradeCat
      AND SCH_ELGIBLEEXAM = @p_EligibleExam
      AND @p_Year BETWEEN SCH_FROMYEAR AND ISNULL(SCH_CLOSEYEAR, @p_Year)
    ORDER BY SCH_FROMYEAR DESC;
    RETURN ISNULL(@Amount, 0);
END;
GO

-- Procedure: usp_ScholarshipApplication
CREATE OR ALTER PROCEDURE dbo.usp_ScholarshipApplication
(
    @p_SCH_EMPSYSID INT,
    @p_SCH_GRADEID INT,
    @p_SCH_DEPENDID INT,
    @p_SCH_CHILDNAME VARCHAR(100),
    @p_SCH_LASTSCHOOL VARCHAR(100),
    @p_SCH_LASTYEAROFSCHOOL DECIMAL(38,0),
    @p_SCH_LASTEXAM CHAR(2),
    @p_SCH_CGPAFLAG CHAR(1),
    @p_SCH_MARKSPER DECIMAL(19,0),
    @p_SCH_MARKSGPA DECIMAL(19,0),
    @p_SCH_MARKSFILE VARCHAR(100),
    @p_SCH_COURSENAME VARCHAR(100),
    @p_SCH_COURSEJOINYEAR INT,
    @p_SCH_COURSEJOINMONTH DECIMAL(20,0),
    @p_SCH_COURSEDURATION BIGINT,
    @p_SCH_ADMRECPTFILE VARCHAR(100) = NULL,
    @p_SCH_PAYMODE CHAR(3) = NULL,
    @p_SCH_CHILDACCNO VARCHAR(20) = NULL,
    @p_SCH_CHILLDBANKIFSC VARCHAR(12) = NULL,
    @p_SCH_CHILLDBANKMICR VARCHAR(12) = NULL,
    @p_SCH_ENTRYSTATUS CHAR(1) = 'E',
    @p_SCH_SOURCE CHAR(1),
    @p_SCH_DISBAMOUNT DECIMAL(19,0),
    @p_SCH_DISBFREQ CHAR(1),
    @p_SCH_LIVESTATUS CHAR(1) = 'A',
    @p_CreatedBy INT,
    @p_SCH_OFFLINE CHAR(1) = 'N',
    @p_SCH_OFFLINEYEAR INT = NULL,
    @p_NewSchID INT OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;
        SELECT @p_NewSchID = ISNULL(MAX(SCH_ID), 0) + 1 FROM SCHOLARSHIP_MAIN;
        INSERT INTO SCHOLARSHIP_MAIN (...)
        VALUES (...);  -- (full insert as in original, omitted here for brevity)
        -- Create first detail record
        DECLARE @NewDetID BIGINT;
        SELECT @NewDetID = ISNULL(MAX(SCHDET_ID), 0) + 1 FROM SCHOLARSHIP_DETAIL;
        INSERT INTO SCHOLARSHIP_DETAIL (...)
        VALUES (...);
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

-- Procedure: usp_ScholarshipApprove
CREATE OR ALTER PROCEDURE dbo.usp_ScholarshipApprove
(
    @p_SCH_ID INT,
    @p_ApprovedBy INT,
    @p_AppRemarks VARCHAR(200) = NULL
)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;
        UPDATE SCHOLARSHIP_MAIN
        SET SCH_ENTRYSTATUS = 'A',
            SCH_APPROVALBY = @p_ApprovedBy,
            SCH_APPROVALON = GETDATE(),
            SCH_APPREMARKS = ISNULL(@p_AppRemarks, ''),
            SCH_UPDATEDON = GETDATE(),
            SCH_UPDATEDBY = @p_ApprovedBy
        WHERE SCH_ID = @p_SCH_ID;
        UPDATE SCHOLARSHIP_DETAIL
        SET SCHDET_MARKSTATUS = 'A',
            SCHDET_APPROVEDON = GETDATE(),
            SCHDET_APPROVEDBY = @p_ApprovedBy,
            SCHDET_UPDATEDON = GETDATE(),
            SCHDET_UPDATEDBY = @p_ApprovedBy
        WHERE SCHDET_MAINID = @p_SCH_ID AND SCHDET_MARKSTATUS = 'P';
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

-- Trigger: trg_ScholarshipDetail_UpdateAudit
CREATE OR ALTER TRIGGER dbo.trg_ScholarshipDetail_UpdateAudit
ON dbo.SCHOLARSHIP_DETAIL
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE SD
    SET SCHDET_UPDATEDON = GETDATE()
    FROM dbo.SCHOLARSHIP_DETAIL SD
    INNER JOIN inserted I ON SD.SCHDET_ID = I.SCHDET_ID;
END;
GO