// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeAttendance.Infrastructure.Persistence;

#nullable disable

namespace TimeAttendance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TimeAttendanceDbContext))]
    [Migration("20260314075419_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TimeAttendance.Domain.Entities.AbsenteeismDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ABS_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AbsentManDays")
                        .HasColumnType("bigint")
                        .HasColumnName("ABS_ABSMANDAYS");

                    b.Property<long>("AgeId")
                        .HasColumnType("bigint")
                        .HasColumnName("ABS_AGEID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("")
                        .HasColumnName("CREATED_BY");

                    b.Property<long>("ExperienceId")
                        .HasColumnType("bigint")
                        .HasColumnName("ABS_EXPERIENCEID");

                    b.Property<long>("FunctionId")
                        .HasColumnType("bigint")
                        .HasColumnName("ABS_FUNCTIONID");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("ABS_GENDER")
                        .IsFixedLength();

                    b.Property<string>("GradeCategory")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("ABS_GRADECAT")
                        .IsFixedLength();

                    b.Property<long>("InternalExperienceId")
                        .HasColumnType("bigint")
                        .HasColumnName("ABS_INTEXPID");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("LAST_MODIFIED_AT");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LAST_MODIFIED_BY");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("ABS_MONTH");

                    b.Property<long>("TotalExperienceId")
                        .HasColumnType("bigint")
                        .HasColumnName("ABS_TOTEXPID");

                    b.Property<long>("TotalManDays")
                        .HasColumnType("bigint")
                        .HasColumnName("ABS_TOTMANDAYS");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("ABS_UNITID");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("ABS_YEAR");

                    b.HasKey("Id");

                    b.HasIndex("UnitId", "Year", "Month")
                        .HasDatabaseName("IX_ABSENTEEISM_DET_UNIT_PERIOD");

                    b.ToTable("ABSENTEEISM_DET", (string)null);
                });

            modelBuilder.Entity("TimeAttendance.Domain.Entities.AbsenteeismMis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ABSID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AnnualPaidLeave")
                        .HasColumnType("DECIMAL(38,2)")
                        .HasColumnName("APL");

                    b.Property<decimal?>("BankLeave")
                        .HasColumnType("DECIMAL(38,2)")
                        .HasColumnName("BKL");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CID");

                    b.Property<decimal?>("CompensatoryOff")
                        .HasColumnType("DECIMAL(38,2)")
                        .HasColumnName("COF");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("")
                        .HasColumnName("CREATED_BY");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("DID");

                    b.Property<string>("Grade")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("GRD")
                        .IsFixedLength();

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("LAST_MODIFIED_AT");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LAST_MODIFIED_BY");

                    b.Property<decimal?>("LeaveWithoutPay")
                        .HasColumnType("DECIMAL(38,2)")
                        .HasColumnName("LWOP");

                    b.Property<decimal?>("LeaveWithoutPayPercentage")
                        .HasColumnType("DECIMAL(38,2)")
                        .HasColumnName("LWOPP");

                    b.Property<decimal?>("LogSystemId")
                        .HasColumnType("DECIMAL(38,2)")
                        .HasColumnName("LOGSYSID");

                    b.Property<string>("Month")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("MNTH");

                    b.Property<decimal?>("NumberOfPresentHours")
                        .HasColumnType("DECIMAL(38,2)")
                        .HasColumnName("NPH");

                    b.Property<decimal?>("OnDuty")
                        .HasColumnType("DECIMAL(38,2)")
                        .HasColumnName("OND");

                    b.Property<decimal?>("PaidDays")
                        .HasColumnType("DECIMAL(38,2)")
                        .HasColumnName("PDS");

                    b.Property<decimal?>("PenaltyLeave")
                        .HasColumnType("DECIMAL(38,2)")
                        .HasColumnName("PNL");

                    b.Property<decimal?>("PlannedLeave")
                        .HasColumnType("DECIMAL(38,2)")
                        .HasColumnName("PLD");

                    b.Property<decimal?>("ShiftSwap")
                        .HasColumnType("DECIMAL(38,2)")
                        .HasColumnName("SWP");

                    b.Property<long?>("SystemId")
                        .HasColumnType("bigint")
                        .HasColumnName("SYSID");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UNTID");

                    b.Property<decimal?>("WeeklyOff")
                        .HasColumnType("DECIMAL(38,2)")
                        .HasColumnName("WOFF");

                    b.HasKey("Id");

                    b.HasIndex("UnitId", "Month")
                        .HasDatabaseName("IX_ABSMIS_UNIT_MONTH");

                    b.ToTable("ABSMIS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
