-- =========================================================================
-- SETTLEMENT MODULE - Database Tables
-- Database: PFDB
-- Module: PF Settlement and Withdrawal Management
-- Description: Manages settlement and withdrawal operations
-- Created: March 9, 2026
-- =========================================================================

USE PFDB;
GO

-- Settlement Main Records
CREATE TABLE [SET_MAIN] (
    [ST_SET_NUM] BIGINT NOT NULL PRIMARY KEY,
    [ST_TRUST_CODE] CHAR(3) NULL,
    [ST_MEMBER_NO] BIGINT NULL,
    [ST_SET_TYPE] CHAR(1) NULL,
    [ST_SET_DATE] DATETIME2(3) NULL,
    [ST_DOL_DAT] DATETIME2(3) NULL,
    [ST_REASON] VARCHAR(200) NULL,
    [ST_UPDON] DATETIME2(3) NULL,
    [ST_UPDBY_EMP_SYSID] BIGINT NULL,
    [ST_ACC_DATE] DATETIME2(3) NULL,
    [ST_FINYEAR] BIGINT NULL,
    [ST_JV_VOUCHER_TYPE] CHAR(3) NULL,
    [ST_JV_NO] BIGINT NULL,
    [ST_SET_INT_FLG] CHAR(1) NULL,
    [ST_TAXSTS] VARCHAR(200) NULL,
    [ST_TAXRATE] BIGINT NULL,
    [ST_SETTLEMENT_AMOUNT] DECIMAL(19,0) NULL,
    [ST_STATUS] CHAR(1) DEFAULT 'P'
);
GO

-- Settlement Deduction Details
CREATE TABLE [SET_DEDUCTION] (
    [SET_DED_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [SET_NUM] BIGINT NOT NULL,
    [DED_TYPE] VARCHAR(50) NOT NULL,
    [DED_AMOUNT] DECIMAL(19,0) NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL,
    CONSTRAINT [FK_SET_DEDUCTION] FOREIGN KEY ([SET_NUM]) REFERENCES [SET_MAIN]([ST_SET_NUM])
);
GO

-- Settlement Approval Workflow
CREATE TABLE [SET_APPROVAL] (
    [APR_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [SET_NUM] BIGINT NOT NULL,
    [APR_LEVEL] INT NOT NULL,
    [APR_BY_SYSID] BIGINT NOT NULL,
    [APR_STATUS] CHAR(1) NOT NULL,
    [APR_REMARKS] VARCHAR(200) NULL,
    [APR_DATE] DATETIME2(3) NOT NULL,
    CONSTRAINT [FK_SET_APPROVAL] FOREIGN KEY ([SET_NUM]) REFERENCES [SET_MAIN]([ST_SET_NUM])
);
GO

-- Settlement Payments
CREATE TABLE [SET_PAYMENT] (
    [PAY_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [SET_NUM] BIGINT NOT NULL,
    [PAY_MODE] VARCHAR(20) NOT NULL,
    [PAY_AMOUNT] DECIMAL(19,0) NOT NULL,
    [PAY_DATE] DATETIME2(3) NOT NULL,
    [PAY_REF_NO] VARCHAR(50) NULL,
    [PAY_STATUS] CHAR(1) DEFAULT 'P',
    CONSTRAINT [FK_SET_PAYMENT] FOREIGN KEY ([SET_NUM]) REFERENCES [SET_MAIN]([ST_SET_NUM])
);
GO

CREATE NONCLUSTERED INDEX [IDX_SET_MAIN_MEMBER] ON [SET_MAIN] ([ST_MEMBER_NO]) INCLUDE ([ST_SET_NUM], [ST_STATUS]);
CREATE NONCLUSTERED INDEX [IDX_SET_MAIN_STATUS] ON [SET_MAIN] ([ST_STATUS], [ST_SET_DATE]);

PRINT 'Settlement Module Tables created successfully!';
GO
