-- ==========================================
-- Module: DealTicketing
-- Purpose: Deal Management and Ticket Processing
-- Created: March 9, 2026
-- Database: CASHDB
-- ==========================================

USE CASHDB;
GO

-- =====================================================
-- CREATE TABLES FOR DEAL TICKETING MODULE
-- =====================================================

-- Table: DEAL_BANKMASTER - Bank Master Data
CREATE TABLE [DEAL_BANKMASTER] (
    [BANK_ID] BIGINT NOT NULL  -- Bank ID,
    [BANK_NAME] VARCHAR(50) NOT NULL  -- Bank Name,
    [BANK_EFFDATE] DATETIME2(3) NOT NULL  -- Effective Date,
    [BANK_CLSDATE] DATETIME2(3) NULL  -- Closure Date,
    [BANK_MODIFIEDBY] DECIMAL(38) NOT NULL  -- Modified By,
    [BANK_MODIFIEDON] DATETIME2(3) NOT NULL  -- Modified On,
    CONSTRAINT [PK_DEAL_BANKMASTER] PRIMARY KEY ([BANK_ID])
);

-- Table: DEAL_CATEGORYMASTER - Deal Category Master
CREATE TABLE [DEAL_CATEGORYMASTER] (
    [CATEGORY_ID] BIGINT NOT NULL  -- Category ID,
    [CATEGORY_NAME] VARCHAR(50) NOT NULL  -- Category Name,
    [CATEGORY_TYPE] CHAR(1) NOT NULL  -- Category Type,
    [CATEGORY_MODIFIEDON] DATETIME2(3) NOT NULL  -- Last Modified On,
    [CATEGORY_MODIFIEDBY] DECIMAL(38) NOT NULL  -- Last Modified By,
    CONSTRAINT [PK_DEAL_CATEGORYMASTER] PRIMARY KEY ([CATEGORY_ID])
);

-- Table: DEAL_LOVMASTER - List of Values Master
CREATE TABLE [DEAL_LOVMASTER] (
    [LOV_ID] BIGINT NOT NULL  -- LOV ID,
    [LOV_TYPE] VARCHAR(10) NOT NULL  -- LOV Type - 001 Derivative Type   002 Deal Nature   003 Deal Category  004 Options Type 005 Floating Base,
    [LOV_NAME] VARCHAR(150) NOT NULL  -- LOV Name,
    CONSTRAINT [PK_DEAL_LOVMASTER] PRIMARY KEY ([LOV_ID])
);

-- Table: DEALTICKET_BATCH - Deal Batch Master
CREATE TABLE [DEALTICKET_BATCH] (
    [DEAL_BATCHID] BIGINT NOT NULL  -- Deal Batch ID,
    [DEAL_DATE] DATETIME2(3) NOT NULL  -- Deal Date,
    [DEAL_DERTYPE] BIGINT NOT NULL  -- Derivative Type,
    [DEAL_SCREENSHOT] VARCHAR(50) NULL  -- Reuters Screenshot,
    [DEAL_BOOKEDBY] BIGINT NULL  -- Deal Booked By,
    [DEAL_BANKTRADER] VARCHAR(50) NULL  -- Bank Trader,
    [DEAL_BANKID] BIGINT NULL  -- Deal Bank ID,
    [DEAL_OPTIONTYPE] BIGINT NULL  -- Option Type,
    [DEAL_BUSINESSID] DECIMAL(38) NOT NULL  -- Business ID,
    [DEAL_REJSTATUS] CHAR(1) NULL  -- Rejected Status - Y/N,
    [DEAL_REJREASON] VARCHAR(50) NULL  -- Reason for Rejection,
    [DEAL_ERRREMARKS] VARCHAR(50) NULL  -- Reason for error at the batch level,
    [DEAL_MODIFIEDBY] DECIMAL(38) NOT NULL  -- Modified By,
    [DEAL_MODIFIEDON] DATETIME2(3) NOT NULL  -- Modified On,
    [DEAL_UNITID] DECIMAL(38) NULL,
    CONSTRAINT [PK_DEALTICKET_BATCH] PRIMARY KEY ([DEAL_BATCHID]),
    CONSTRAINT [FK_DEALTICKET_BATCH_BANKMASTER] FOREIGN KEY ([DEAL_BANKID]) REFERENCES [DEAL_BANKMASTER]([BANK_ID])
);

-- Table: DEALTICKET_DET - Deal Details
CREATE TABLE [DEALTICKET_DET] (
    [DEAL_ID] BIGINT NOT NULL  -- Deal ID,
    [DEAL_NO] BIGINT NOT NULL  -- Deal No,
    [DEAL_VERSIONID] BIGINT NOT NULL  -- Version ID,
    [DEAL_BATCHID] BIGINT NOT NULL  -- Deal Batch ID,
    [DEAL_TRANTYPE] CHAR(1) NULL  -- Transaction Type (Buy/Sell/Put/Call),
    [DEAL_POSITION] CHAR(2) NULL  -- Option Position (BC/BP/SP/SC),
    [DEAL_ENTRYDATE] DATETIME2(3) NULL  -- Entry Date,
    [DEAL_AMOUNT] DECIMAL(19,0) NULL  -- Deal Amount,
    [DEAL_BANKID] BIGINT NULL  -- Bank ID,
    [DEAL_CURRENCY1] BIGINT NULL  -- Currency-1,
    [DEAL_CURRENCY2] BIGINT NULL  -- Currency-2,
    [DEAL_SPOTRATE] DECIMAL(19,0) NULL  -- Spot Rate,
    [DEAL_FORPOINTS] DECIMAL(19,0) NULL  -- Forward Points,
    [DEAL_BANKMARGIN] DECIMAL(19,0) NULL  -- Bank Margin,
    [DEAL_BOOKRATE] DECIMAL(19,0) NULL  -- Booked Rate,
    [DEAL_MATDATE] DATETIME2(3) NULL  -- Maturity Date,
    [DEAL_DEALTYPE] BIGINT NULL  -- Deal Type,
    [DEAL_BUSINESS] BIGINT NULL  -- Business ID,
    [DEAL_CATEGORY] BIGINT NULL  -- Deal Category,
    [DEAL_STRIKEPRICE] BIGINT NULL  -- Strike Price,
    [DEAL_PPLMITOUT] BIGINT NULL  -- PP Limit Outstanding,
    [DEAL_APPSTATUS] CHAR(1) NULL  -- Confirmation Status - Y/N/R /P - Confirmed / Pending  for submission/ Rejected / Pending for confirmation,
    [DEAL_APPREMARKS] VARCHAR(200) NULL  -- Approval / Rejection Remarks,
    [DEAL_ERRREMARKS] VARCHAR(200) NULL  -- Reason for Error/Correction,
    [DEAL_CORRECTNESS] VARCHAR(200) NULL  -- Confirm Correctness that all Data entered,
    [DEAL_SIGNED] CHAR(1) NULL  -- Signed deal sent to bank,
    [DEAL_APPBUSINESS] BIGINT NULL  -- Approved Business,
    [DEAL_DEALCONFNO] VARCHAR(50) NULL  -- Modified By,
    [DEAL_MODIFIEDON] DATETIME2(3) NULL  -- Modified On,
    [DEAL_MODIFIEDBY] DECIMAL(38) NULL,
    [DEAL_REMARKS] VARCHAR(500) NULL,
    [DEAL_IRLOAN] VARCHAR(500) NULL  -- Loan Descrciption,
    [DEAL_IRTYPE] CHAR(3) NULL  -- Interest Rate Derivative Type (IRS/ Interest Rate Cap/Interest Rate Floor),
    [DEAL_STARTDATE] DATETIME2(3) NULL  -- Loan Start Date,
    [DEAL_NOTPRINCIPAL] DECIMAL(19,0) NULL  -- Notional Principal Swapped,
    [DEAL_IRSTYPE] VARCHAR(25) NULL  -- PAYFIXRECFLOAT/PAYFLOATRECFIX,
    [DEAL_TOPAY] DECIMAL(38) NULL  -- Company to Pay,
    [DEAL_TOREC] DECIMAL(38) NULL  -- Çompany to Receive,
    [DEAL_RATESCREENSHOT] VARCHAR(500) NULL  -- Rate Screenshot,
    [DEAL_RATEPER] BIGINT NULL  -- Interest Rate Cap/Floor %,
    [DEAL_LOANAMT] DECIMAL(38) NULL  -- Loan Amount,
    [DEAL_LOANCURRENCY] BIGINT NULL  -- Loan Currency,
    [DEAL_SETAMT] DECIMAL(19,0) NULL  -- Settlement Amount,
    [DEAL_CANAMT] DECIMAL(19,0) NULL  -- Cancelled Amount,
    [DEAL_ROLLAMT] DECIMAL(19,0) NULL  -- Rollover Amount,
    [DEAL_SETSTATUS] CHAR(1) NULL  -- Settlement Status - Live/Closed,
    [DEAL_UNITID] DECIMAL(38) NULL,
    [DEAL_NETBASISPOINT] DECIMAL(19,0) NULL,
    [DEAL_ROLLOVERDEALNO] DECIMAL(38) NULL,
    [DEAL_BOOKINGCHARGES] DECIMAL(38) NULL,
    [DEAL_SENTOBANK] CHAR(1) NULL,
    CONSTRAINT [PK_DEALTICKET_DET] PRIMARY KEY ([DEAL_ID]),
    CONSTRAINT [FK_DEALTICKET_DET_BATCH] FOREIGN KEY ([DEAL_BATCHID]) REFERENCES [DEALTICKET_BATCH]([DEAL_BATCHID]),
    CONSTRAINT [FK_DEALTICKET_DET_BANKMASTER] FOREIGN KEY ([DEAL_BANKID]) REFERENCES [DEAL_BANKMASTER]([BANK_ID])
);

-- Table: DEALTICKET_LOANSCH - Deal Loan Schedule
CREATE TABLE [DEALTICKET_LOANSCH] (
    [DEAL_SCHID] BIGINT NOT NULL  -- Schedule ID,
    [DEAL_ID] BIGINT NOT NULL  -- Deal ID,
    [DEAL_SCHDATE] DATETIME2(3) NOT NULL  -- Schedule Date,
    [DEAL_SCHAMT] BIGINT NOT NULL  -- Schedule Amount,
    CONSTRAINT [PK_DEALTICKET_LOANSCH] PRIMARY KEY ([DEAL_SCHID]),
    CONSTRAINT [FK_DEALTICKET_LOANSCH_DET] FOREIGN KEY ([DEAL_ID]) REFERENCES [DEALTICKET_DET]([DEAL_ID])
);

-- Table: DEALTICKET_SET - Deal Settlement
CREATE TABLE [DEALTICKET_SET] (
    [SET_ID] BIGINT NOT NULL  -- Settlement ID,
    [SET_DEALID] BIGINT NOT NULL  -- Deal ID,
    [SET_SPOTRATE] DECIMAL(19,0) NULL  -- Spot Rate on Date of Maturity,
    [SET_DATE] DATETIME2(3) NULL  -- Settlement Date,
    [SET_MONEYTYPE] CHAR(3) NULL  -- IN/OUT - In the Money / Out of  Money,
    [SET_EXCTYPE] CHAR(1) NULL  -- Execution Type - Y/N - Yes/No,
    [SET_GAINLOSSAMT] DECIMAL(19,0) NOT NULL  -- Calculated Gain or Loss Amount ( Exchange Rate* Gain or Loss Amount),
    [SET_TYPE] CHAR(3) NULL  -- U  - Utilized ; C - Cancelled ; R - Rollover,
    [SET_CANDATE] DATETIME2(3) NULL  -- Utilised Date / Cancelled Date/ Rollover Date,
    [SET_PREMIUMRATE] DECIMAL(19,0) NULL  -- Premium Rate,
    [SET_PREMIUMAMOUNT] DECIMAL(19,0) NULL  -- Premium Amount,
    [SET_IRDAYS] BIGINT NULL  -- No of Days,
    [SET_IRSTARTDATE] DATETIME2(3) NULL  -- Start Date,
    [SET_IRAMOUNT] DECIMAL(19,0) NULL  -- IR Amount,
    [SET_WINDFEE] DECIMAL(19,0) NULL  -- Winding up fee,
    [SET_WINDRATE] DECIMAL(19,0) NULL  -- Winding up Rate,
    [SET_AMOUNT] DECIMAL(19,0) NULL  -- Amount Utilised,
    [SET_CREDITDEBIT] DECIMAL(19,0) NULL  -- Amount Credited/Debited,
    [SET_MODIFIEDBY] BIGINT NULL,
    [SET_MODIFIEDON] DATETIME2(3) NULL,
    [SET_EXCHANGERATE] DECIMAL(19,0) NULL  -- Exchange Rate,
    [SET_ACTGAINLOSSAMT] DECIMAL(19,0) NULL  -- Gain or Loss Amount,
    [SET_DCDATE] DATETIME2(3) NULL,
    [SET_DCAMNT] DECIMAL(38) NULL,
    [SET_BANKNAME] VARCHAR(100) NULL,
    [SET_BANKACNO] VARCHAR(20) NULL,
    CONSTRAINT [PK_DEALTICKET_SET] PRIMARY KEY ([SET_ID]),
    CONSTRAINT [FK_DEALTICKET_SET_DET] FOREIGN KEY ([SET_DEALID]) REFERENCES [DEALTICKET_DET]([DEAL_ID])
);

-- Table: DEATICKET_ATTACHMENT - Deal Attachment
CREATE TABLE [DEATICKET_ATTACHMENT] (
    [DEAL_ATTACHMENTID] BIGINT NOT NULL  -- Attachment ID,
    [DEAL_BATCHID] BIGINT NOT NULL  -- Deal Batch ID,
    [DEAL_ID] BIGINT NOT NULL  -- Deal ID,
    [DEAL_ATTACHMENTTYPE] VARCHAR(10) NOT NULL  -- Attachment Type,
    [DEAL_ATTACHMENTFILE] VARCHAR(200) NOT NULL  -- Attachment File Name,
    CONSTRAINT [PK_DEATICKET_ATTACHMENT] PRIMARY KEY ([DEAL_ATTACHMENTID]),
    CONSTRAINT [FK_DEATICKET_ATTACHMENT_DET] FOREIGN KEY ([DEAL_ID]) REFERENCES [DEALTICKET_DET]([DEAL_ID]),
    CONSTRAINT [FK_DEATICKET_ATTACHMENT_BATCH] FOREIGN KEY ([DEAL_BATCHID]) REFERENCES [DEALTICKET_BATCH]([DEAL_BATCHID])
);

-- Table: DEATICKETSET_ATTACHMENT - Deal Settlement Attachment
CREATE TABLE [DEATICKETSET_ATTACHMENT] (
    [DEAL_ATTACHMENTID] BIGINT NOT NULL  -- Attachment ID,
    [DEAL_SETID] BIGINT NOT NULL  -- Deal Settlement ID,
    [DEAL_ATTACHMENTTYPE] VARCHAR(10) NOT NULL  -- Attachment Type,
    [DEAL_ATTACHMENTFILE] VARCHAR(200) NOT NULL  -- Attachment File Name,
    CONSTRAINT [PK_DEATICKETSET_ATTACHMENT] PRIMARY KEY ([DEAL_ATTACHMENTID]),
    CONSTRAINT [FK_DEATICKETSET_ATTACHMENT_SET] FOREIGN KEY ([DEAL_SETID]) REFERENCES [DEALTICKET_SET]([SET_ID])
);

-- =====================================================
-- CREATE INDEXES
-- =====================================================

CREATE INDEX [IX_DEALTICKET_BATCH_DATE] ON [DEALTICKET_BATCH] ([DEAL_DATE]);
CREATE INDEX [IX_DEALTICKET_BATCH_BANKID] ON [DEALTICKET_BATCH] ([DEAL_BANKID]);
CREATE INDEX [IX_DEALTICKET_DET_BATCHID] ON [DEALTICKET_DET] ([DEAL_BATCHID]);
CREATE INDEX [IX_DEALTICKET_DET_DEALID] ON [DEALTICKET_DET] ([DEAL_ID]);
CREATE INDEX [IX_DEALTICKET_SET_DEALID] ON [DEALTICKET_SET] ([SET_DEALID]);
CREATE INDEX [IX_DEATICKET_ATTACHMENT_DEALID] ON [DEATICKET_ATTACHMENT] ([DEAL_ID]);

-- =====================================================
-- VERIFICATION
-- =====================================================

PRINT 'DealTicketing Module Schema created successfully.';
GO

-- Verify table creation
IF OBJECT_ID('DEAL_BANKMASTER', 'U') IS NOT NULL
    PRINT 'Table DEAL_BANKMASTER: OK'
ELSE
    PRINT 'Table DEAL_BANKMASTER: FAILED'
GO

IF OBJECT_ID('DEAL_CATEGORYMASTER', 'U') IS NOT NULL
    PRINT 'Table DEAL_CATEGORYMASTER: OK'
ELSE
    PRINT 'Table DEAL_CATEGORYMASTER: FAILED'
GO

IF OBJECT_ID('DEAL_LOVMASTER', 'U') IS NOT NULL
    PRINT 'Table DEAL_LOVMASTER: OK'
ELSE
    PRINT 'Table DEAL_LOVMASTER: FAILED'
GO

IF OBJECT_ID('DEALTICKET_BATCH', 'U') IS NOT NULL
    PRINT 'Table DEALTICKET_BATCH: OK'
ELSE
    PRINT 'Table DEALTICKET_BATCH: FAILED'
GO

IF OBJECT_ID('DEALTICKET_DET', 'U') IS NOT NULL
    PRINT 'Table DEALTICKET_DET: OK'
ELSE
    PRINT 'Table DEALTICKET_DET: FAILED'
GO

IF OBJECT_ID('DEALTICKET_LOANSCH', 'U') IS NOT NULL
    PRINT 'Table DEALTICKET_LOANSCH: OK'
ELSE
    PRINT 'Table DEALTICKET_LOANSCH: FAILED'
GO

IF OBJECT_ID('DEALTICKET_SET', 'U') IS NOT NULL
    PRINT 'Table DEALTICKET_SET: OK'
ELSE
    PRINT 'Table DEALTICKET_SET: FAILED'
GO

IF OBJECT_ID('DEATICKET_ATTACHMENT', 'U') IS NOT NULL
    PRINT 'Table DEATICKET_ATTACHMENT: OK'
ELSE
    PRINT 'Table DEATICKET_ATTACHMENT: FAILED'
GO

IF OBJECT_ID('DEATICKETSET_ATTACHMENT', 'U') IS NOT NULL
    PRINT 'Table DEATICKETSET_ATTACHMENT: OK'
ELSE
    PRINT 'Table DEATICKETSET_ATTACHMENT: FAILED'
GO
