apiVersion: v1
kind: Secret
metadata:
  name: wms-secrets
  namespace: wms
  labels:
    app.kubernetes.io/part-of: wms-platform
type: Opaque
stringData:
  sa-password: "WmsStr0ng!Passw0rd2024"
  rabbitmq-user: "wms_user"
  rabbitmq-password: "WmsR@bbitMQ2024!"
  jwt-key: "WMSApiGatewaySuperSecretKey2024AtLeast32Characters!!"
  jwt-issuer: "WMSApiGateway"
  jwt-audience: "WMSApiGatewayClients"
