-- ==========================================
-- REVIEW MODULE - Schema
-- Database: LETDB
-- Purpose: Course Review & Feedback Management
-- Created: March 9, 2026
-- ==========================================

USE LETDB;
GO

-- ==========================================
-- REVIEW MODULE - Core Tables
-- ==========================================

-- Table: REVIEW_MAIN
CREATE TABLE [REVIEW_MAIN] (
    [REV_SRL_NUM] BIGINT NOT NULL PRIMARY KEY,
    [REV_FED_NUM] BIGINT NULL,
    [REV_REM_MRK1] VARCHAR(4000) NULL,
    [REV_REM_MRK2] VARCHAR(4000) NULL,
    [REV_REM_MRK3] VARCHAR(4000) NULL,
    [REV_REM_MRK4] VARCHAR(4000) NULL,
    [REV_REM_MRK5] VARCHAR(4000) NULL,
    [REV_REM_MRK6] VARCHAR(4000) NULL,
    [REV_REM_MRK7] VARCHAR(4000) NULL,
    [REV_REM_MRK8] VARCHAR(4000) NULL,
    [REV_REM_MRK9] VARCHAR(4000) NULL,
    [REV_REM_MRK10] VARCHAR(4000) NULL,
    [REV_ENT_DATE] VARCHAR(2000) NULL,
    [REV_STATUS] CHAR(1) NULL,
    [REV_NEXT_DATE] DATETIME2(3) NULL
);

-- Table: REVIEW_SUB
CREATE TABLE [REVIEW_SUB] (
    [REV_MAIN_SRL] BIGINT NULL,
    [REV_REV_NUM] BIGINT NULL,
    [REV_NEXT_STATUS] CHAR(1) NULL,
    [REV_DATE] DATETIME2(3) NULL,
    [REV_BY] BIGINT NULL,
    [REV_REM_MRK] VARCHAR(4000) NULL,
    [REV_STATUS] VARCHAR(10) NULL,
    [REV_PROG_REM] VARCHAR(4000) NULL
);

-- Table: REVIEW_MAST
CREATE TABLE [REVIEW_MAST] (
    [RV_TYP_COD] CHAR(3) NOT NULL PRIMARY KEY,
    [RV_TYP_NAM] VARCHAR(65) NOT NULL,
    [RV_GRP_COD] VARCHAR(65) NOT NULL
);

-- Table: REVIEW_SKILL
CREATE TABLE [REVIEW_SKILL] (
    [SK_REQ_ID] BIGINT NOT NULL PRIMARY KEY,
    [SK_SRL_NUM] BIGINT NOT NULL,
    [SK_ACT_NUM] BIGINT NOT NULL,
    [SK_REV_NUM] BIGINT NOT NULL,
    [SK_SKL_COD] BIGINT NOT NULL,
    [SK_LVL_NUM] BIGINT NOT NULL,
    [SK_RAT_PER] DECIMAL(38) NOT NULL,
    [SK_REM_MRK] VARCHAR(255) NOT NULL
);

-- ==========================================
-- FEEDBACK TABLES
-- ==========================================

-- Table: COURSE_FEEDBACKMAIN
CREATE TABLE [COURSE_FEEDBACKMAIN] (
    [FD_FED_NUM] BIGINT NULL,
    [FD_NOM_NUM] BIGINT NULL,
    [FD_STS_COD] CHAR(1) NULL,
    [FD_FED_DAT] DATETIME2(3) NULL,
    [FD_MOD_DAT] DATETIME2(3) NULL,
    [FD_FIN_RAT] BIGINT NULL,
    [FD_REM_LIN1] VARCHAR(255) NULL,
    [FD_REM_LIN2] VARCHAR(255) NULL,
    [FD_REM_LIN3] VARCHAR(255) NULL,
    [FD_REV_SRL] DECIMAL(38) NULL,
    [FD_CANCEL_REM] VARCHAR(255) NULL,
    [FD_REQ_NUM] BIGINT NULL,
    [FD_REM_LIN9] VARCHAR(255) NULL,
    [FD_REM_LIN4] VARCHAR(255) NULL,
    [FD_REM_LIN5] VARCHAR(255) NULL,
    [FD_REM_LIN6] BIGINT NULL,
    [FD_REM_LIN7] VARCHAR(255) NULL,
    [FD_REM_LIN8] VARCHAR(255) NULL
);

-- Table: COURSE_FEEDBACKSUB
CREATE TABLE [COURSE_FEEDBACKSUB] (
    [FD_FED_NUM] BIGINT NULL,
    [FD_FED_TYP] BIGINT NULL,
    [FD_RAT_NUM] BIGINT NULL,
    [FD_REM_MRK] VARCHAR(4000) NULL
);

-- Table: COURSE_FEEDMAIN
CREATE TABLE [COURSE_FEEDMAIN] (
    [FD_CRS_ID] BIGINT NOT NULL,
    [FD_USR_ID] VARCHAR(255) NOT NULL,
    [FD_REV_DAT] DATETIME2(3) NOT NULL,
    [FD_GEN_REM] VARCHAR(255) NOT NULL,
    [FD_REQ_NUM] BIGINT NOT NULL,
    [FD_MOD_DAT] DATETIME2(3) NOT NULL,
    [FD_SRL_NUM] BIGINT NULL,
    CONSTRAINT [PK_COURSE_FEEDMAIN] PRIMARY KEY ([FD_USR_ID], [FD_CRS_ID])
);

-- Table: COURSE_FEEDSUB
CREATE TABLE [COURSE_FEEDSUB] (
    [FD_REQ_NUM] BIGINT NOT NULL,
    [FD_REQ_SRL] BIGINT NOT NULL,
    [FD_SRL_NUM] BIGINT NOT NULL,
    [FD_TYP_COD] BIGINT NOT NULL,
    [FD_TYP_NUM] BIGINT NULL,
    [FD_TYP_DES] VARCHAR(65) NULL,
    CONSTRAINT [PK_COURSE_FEEDSUB] PRIMARY KEY ([FD_REQ_NUM], [FD_REQ_SRL], [FD_SRL_NUM])
);

-- Table: COURSE_REVIEWMAIN
CREATE TABLE [COURSE_REVIEWMAIN] (
    [RV_CRS_ID] BIGINT NOT NULL PRIMARY KEY,
    [RV_USR_ID] CHAR(1) NOT NULL,
    [RV_REV_DAT] DATETIME2(3) NOT NULL,
    [RV_GEN_REM] VARCHAR(255) NOT NULL,
    [RQ_SUP_USR] VARCHAR(255) NOT NULL,
    [RV_SRL_NUM] CHAR(1) NOT NULL,
    [RV_SUP_REM] CHAR(1) NOT NULL,
    [RV_RAT_PER] CHAR(1) NOT NULL,
    [RV_FIL_NAM] CHAR(1) NOT NULL,
    [RV_NXT_DAT] DATETIME2(3) NOT NULL,
    [RV_ORG_DAT] DATETIME2(3) NOT NULL
);

-- Table: COURSE_REVIEWSUB
CREATE TABLE [COURSE_REVIEWSUB] (
    [RV_CRS_ID] BIGINT NOT NULL,
    [RV_USR_ID] CHAR(1) NOT NULL,
    [RV_SRL_NUM] BIGINT NOT NULL,
    [RV_TYP_COD] CHAR(1) NOT NULL,
    [RV_TYP_NUM] BIGINT NOT NULL,
    CONSTRAINT [PK_COURSE_REVIEWSUB] PRIMARY KEY ([RV_CRS_ID], [RV_USR_ID])
);

-- Table: FEED_EVALMAST
CREATE TABLE [FEED_EVALMAST] (
    [FD_EVL_TYP] BIGINT NULL,
    [FD_EVL_DES] VARCHAR(2000) NULL,
    [FD_WGT_NUM] DECIMAL(19,0) NULL
);

-- Table: FEED_MAST
CREATE TABLE [FEED_MAST] (
    [FD_TYP_COD] BIGINT NOT NULL PRIMARY KEY,
    [FD_TYP_NAM] VARCHAR(500) NOT NULL,
    [FD_NUM_TYP] CHAR(1) NOT NULL,
    [FD_EVL_COD] VARCHAR(10) NULL
);

-- Table: FEED_MASTER
CREATE TABLE [FEED_MASTER] (
    [FD_TYP_ID] BIGINT NULL,
    [FD_TYP_NAM] VARCHAR(5000) NULL,
    [FD_EVL_COD] BIGINT NULL
);

-- Table: TRAINER_FEED
CREATE TABLE [TRAINER_FEED] (
    [TR_GRP_COD] BIGINT NOT NULL,
    [TR_FED_NUM] BIGINT NOT NULL,
    [TR_SRL_NUM] BIGINT NULL,
    [TR_QTN_GRP] VARCHAR(255) NULL,
    [TR_GRP_NUM] BIGINT NULL,
    [TR_WGT_NUM] BIGINT NULL,
    [TR_EFF_DAT] DATETIME2(3) NULL,
    [TR_CLS_DAT] DATETIME2(3) NULL,
    CONSTRAINT [PK_TRAINER_FEED] PRIMARY KEY ([TR_GRP_COD], [TR_FED_NUM])
);

-- ==========================================
-- INDEXES FOR REVIEW MODULE
-- ==========================================

CREATE INDEX [IDX_REVIEW_FEEDMAIN_CRS_ID] ON [COURSE_FEEDMAIN]([FD_CRS_ID]);
CREATE INDEX [IDX_REVIEW_REVIEWMAIN_CRS_ID] ON [COURSE_REVIEWMAIN]([RV_CRS_ID]);
CREATE INDEX [IDX_REVIEW_SKILL_REQ_ID] ON [REVIEW_SKILL]([SK_REQ_ID]);

PRINT 'Review Module Schema created successfully.';
GO
