-- ==========================================
-- REQUEST MODULE - Schema
-- Database: LETDB
-- Purpose: Training/Learning Request Management
-- Created: March 9, 2026
-- ==========================================

USE LETDB;
GO

-- ==========================================
-- REQUEST MODULE - Core Tables
-- ==========================================

-- Table: REQUEST_MAIN
CREATE TABLE [REQUEST_MAIN] (
    [RQ_REQ_ID] BIGINT NOT NULL PRIMARY KEY,
    [RQ_EMP_USR] VARCHAR(25) NOT NULL,
    [RQ_REQ_DAT] DATETIME2(3) NOT NULL,
    [RQ_SUP_USR] VARCHAR(25) NOT NULL
);

-- Table: REQUEST_SUB
CREATE TABLE [REQUEST_SUB] (
    [RQ_REQ_ID] BIGINT NOT NULL,
    [RQ_SRL_NUM] BIGINT NOT NULL PRIMARY KEY,
    [RQ_REQ_DAT] DATETIME2(3) NOT NULL,
    [RQ_MOD_DAT] DATETIME2(3) NOT NULL,
    [RQ_MOD_USR] CHAR(1) NOT NULL,
    [RQ_REQ_SRC] CHAR(1) NOT NULL,
    [RQ_MOD_TRN] CHAR(1) NOT NULL,
    [RQ_GOL_DES] CHAR(1) NOT NULL,
    [RQ_STS_COD] CHAR(1) NOT NULL,
    [RQ_TRN_NED] VARCHAR(255) NOT NULL,
    [RQ_CAN_DAT] DATETIME2(3) NULL,
    [RQ_CAN_REM] VARCHAR(255) NULL,
    [RQ_MEN_USR] VARCHAR(255) NOT NULL,
    [RQ_MEN_REM] VARCHAR(255) NOT NULL,
    [RQ_CRS_ID] BIGINT NOT NULL,
    [RQ_APP_NUM] BIGINT NOT NULL,
    [RQ_REV_DYS] BIGINT NOT NULL,
    [RQ_REV_USR] VARCHAR(255) NOT NULL,
    [RQ_REV_MOD] VARCHAR(255) NOT NULL,
    [RQ_STR_DAT] DATETIME2(3) NOT NULL,
    [RQ_END_DAT] DATETIME2(3) NOT NULL,
    [RQ_REF_REQ] BIGINT NOT NULL,
    [RQ_REF_SRL] BIGINT NOT NULL,
    [RQ_SUP_USR] VARCHAR(255) NOT NULL,
    [RQ_ENT_USR] VARCHAR(255) NOT NULL,
    [RQ_ENT_MOD] CHAR(1) NOT NULL,
    [RQ_APP_TIM] BIGINT NOT NULL,
    [RQ_BUS_BEN] VARCHAR(255) NOT NULL,
    [RQ_EXP_CNP] VARCHAR(255) NOT NULL,
    [RQ_CRS_DES] VARCHAR(255) NOT NULL,
    [RQ_CRS_AVL] CHAR(1) NOT NULL,
    CONSTRAINT [FK_REQUEST_SUB_REQUEST_MAIN] FOREIGN KEY ([RQ_REQ_ID]) REFERENCES [REQUEST_MAIN]([RQ_REQ_ID])
);

-- Table: REQUEST_NEW
CREATE TABLE [REQUEST_NEW] (
    [RQ_REQ_ID] BIGINT NOT NULL,
    [RQ_SRL_NUM] BIGINT NOT NULL PRIMARY KEY,
    [RQ_SKL_NAM] VARCHAR(10) NOT NULL,
    [RQ_LVL_NUM] BIGINT NOT NULL,
    [RQ_FNC_DES] VARCHAR(10) NOT NULL,
    [RQ_CAT_COD] VARCHAR(10) NOT NULL,
    [RQ_SKL_TYP] CHAR(10) NOT NULL,
    [RQ_STS_COD] CHAR(10) NOT NULL,
    [RQ_CRS_ID] BIGINT NOT NULL
);

-- Table: REQUEST_ACTION
CREATE TABLE [REQUEST_ACTION] (
    [RQ_REQ_ID] BIGINT NULL,
    [RQ_SRL_NUM] BIGINT NOT NULL PRIMARY KEY,
    [RQ_ACT_NUM] BIGINT NULL,
    [RQ_KEY_EXP] VARCHAR(255) NULL,
    [RQ_USG_EXP] VARCHAR(255) NULL,
    [RQ_TIM_EXP] DECIMAL(38) NULL,
    [RQ_SUP_EXP] VARCHAR(255) NULL,
    [RQ_CAN_DAT] DATETIME2(3) NULL,
    [RQ_ENT_DAT] DATETIME2(3) NULL,
    [RQ_ENT_USR] CHAR(1) NULL,
    [RQ_REV_USR] CHAR(1) NULL,
    [RQ_REV_DAT] DATETIME2(3) NOT NULL,
    [RQ_REV_NOS] BIGINT NULL,
    [RQ_CRS_ID] BIGINT NULL,
    [RQ_ACT_FLG] CHAR(1) NULL,
    [RQ_CAN_REM] VARCHAR(255) NULL
);

-- Table: REQUEST_APP
CREATE TABLE [REQUEST_APP] (
    [RQ_REQ_ID] BIGINT NOT NULL,
    [RQ_SRL_NUM] BIGINT NOT NULL,
    [RQ_APP_DAT] DATETIME2(3) NOT NULL,
    [RQ_APP_NUM] BIGINT NOT NULL,
    [RQ_APP_REM] VARCHAR(200) NOT NULL,
    [RQ_APP_USR] CHAR(20) NOT NULL,
    CONSTRAINT [PK_REQUEST_APP] PRIMARY KEY ([RQ_REQ_ID], [RQ_SRL_NUM])
);

-- ==========================================
-- INDEXES FOR REQUEST MODULE
-- ==========================================

CREATE INDEX [IDX_REQUEST_MAIN_EMP_USR] ON [REQUEST_MAIN]([RQ_EMP_USR]);
CREATE INDEX [IDX_REQUEST_MAIN_SUP_USR] ON [REQUEST_MAIN]([RQ_SUP_USR]);
CREATE INDEX [IDX_REQUEST_SUB_REQ_ID] ON [REQUEST_SUB]([RQ_REQ_ID]);
CREATE INDEX [IDX_REQUEST_APP_REQ_ID] ON [REQUEST_APP]([RQ_REQ_ID]);

PRINT 'Request Module Schema created successfully.';
GO
