-- ==========================================
-- Module: BOOKING
-- Description: Booking Requests & Confirmations Module
-- Database: TOURDB
-- Created: March 9, 2026
-- ==========================================

USE TOURDB;
GO

-- Table: BOOKREQUEST_MAIN - Booking Request Main
CREATE TABLE [BOOKREQUEST_MAIN] (
    [BOOKMAIN_ID] VARCHAR(255) NOT NULL  -- Booking Request ID,
    [BOOKMAIN_TPSTATUS] VARCHAR(255) NOT NULL  -- Against Tour Plan (Yes/No),
    [BOOKMAIN_TPID] VARCHAR(255) NOT NULL  -- TP ID - Common for all admin bookings,
    [BOOKMAIN_EMPSYSID] VARCHAR(255) NOT NULL  -- Employee System ID,
    [BOOKMAIN_THROUGH] VARCHAR(255) NOT NULL  -- Booking By (Self/Admin/Subordinate),
    [BOOKMAIN_ADMINID] VARCHAR(255) NOT NULL  -- Admin ID,
    [BOOKMAIN_REMARKS] VARCHAR(255) NOT NULL  -- Booking Remarks/Instruction to admin,
    [BOOKMAIN_TYPE] VARCHAR(255) NOT NULL  -- Type (TKT/STY/CAB),
    [BOOKMAIN_APPSTATUS] VARCHAR(255) NOT NULL  -- Finance Approval Status,
    [BOOKMAIN_CNFSTATUS] VARCHAR(255) NOT NULL  -- Booking Status (Pending/Confirmed),
    [BOOKMAIN_PROOF] VARCHAR(255) NULL  -- Proof Type,
    [BOOKMAIN_FOODPREF] VARCHAR(255) NULL  -- VEG / NON-VEG / NOT APPLICABLE,
    [BOOKMAIN_LASTMODIFIEDON] DATETIME2(3) NOT NULL,
    [BOOKMAIN_BUDCOST] VARCHAR(255) NULL  -- Budgeted Costs,
    [BOOKMAIN_ENTBY] VARCHAR(255) NULL  -- Entered by,
    [BOOKMAIN_ENTON] DATETIME2(3) NULL  -- Entered on,
    [BOOKMAIN_EMPCALID] VARCHAR(255) NULL  -- Employee Calendar ID,
    CONSTRAINT [PK_BOOKREQUEST_MAIN] PRIMARY KEY ([BOOKMAIN_ID])
);

-- Table: BOOKREQUEST_TICKET - Booking Travel Tickets Request
CREATE TABLE [BOOKREQUEST_TICKET] (
    [BOOKTKT_ID] VARCHAR(255) NOT NULL  -- Ticket Request ID,
    [BOOKTKT_MAINID] VARCHAR(255) NOT NULL  -- Request Main ID,
    [BOOKTKT_MODEID] VARCHAR(255) NOT NULL  -- Travel Mode,
    [BOOKTKT_CLASSID] VARCHAR(255) NOT NULL  -- Travel Class,
    [BOOKTKT_TYPE] VARCHAR(255) NOT NULL  -- Type (Departure/Arrival) - DEP/ARR,
    [BOOKTKT_STARTDATE] DATETIME2(3) NOT NULL  -- Departure Date,
    [BOOKTKT_STARTTIME] VARCHAR(255) NOT NULL  -- Departure Time  (FN/AN),
    [BOOKTKT_STARTCITYID] VARCHAR(255) NOT NULL  -- Departure City ID,
    [BOOKTKT_STARTCITY] VARCHAR(255) NOT NULL  -- Departure City Name,
    [BOOKTKT_ENDCITYID] VARCHAR(255) NOT NULL  -- Arrival City ID,
    [BOOKTKT_ENDCITY] VARCHAR(255) NOT NULL  -- Arrival City Name,
    [BOOKTKT_CNFNO] VARCHAR(255) NOT NULL  -- Confirmation No,
    [BOOKTKT_APPSTATUS] VARCHAR(255) NOT NULL  -- Ticket  Status,
    [BOOKTKT_LASTMODIFIEDBY] VARCHAR(255) NOT NULL  -- Last ModifiedBy,
    [BOOKTKT_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last ModifiedOn,
    [BOOKTKT_BUDGETCOST] VARCHAR(255) NOT NULL  -- Budgeted Costs,
    [BOOKTKT_ADMREMARKS] VARCHAR(255) NOT NULL  -- Admin Cancel Remarks,
    [BOOKTKT_SPECIALSANCTION] VARCHAR(255) NOT NULL  -- Special Sanction Required Y/N,
    [BOOKTKT_SPLREASON] VARCHAR(255) NOT NULL  -- Reason for Special Sanction Required,
    CONSTRAINT [PK_BOOKREQUEST_TICKET] PRIMARY KEY ([BOOKTKT_ID])
);

-- Table: BOOKREQUEST_STAY - Booking Stay Request
CREATE TABLE [BOOKREQUEST_STAY] (
    [BOOKSTY_ID] VARCHAR(255) NOT NULL  -- Stay Request ID,
    [BOOKSTY_MAINID] VARCHAR(255) NOT NULL  -- Request Main ID,
    [BOOKSTY_CITYID] VARCHAR(255) NOT NULL  -- Stay City ID,
    [BOOKSTY_CITY] VARCHAR(255) NOT NULL  -- Stay City Name,
    [BOOKSTY_CHECKINDATE] DATETIME2(3) NOT NULL  -- Check in Date/Time,
    [BOOKSTY_CHECKOUTDATE] DATETIME2(3) NOT NULL  -- Check out Date/Time,
    [BOOKSTY_CNFNO] VARCHAR(255) NOT NULL  -- Confirmation No,
    [BOOKSTY_LASTMODIFIEDBY] VARCHAR(255) NOT NULL  -- Last ModifiedBy,
    [BOOKSTY_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last ModifiedOn,
    CONSTRAINT [PK_BOOKREQUEST_STAY] PRIMARY KEY ([BOOKSTY_ID])
);

-- Table: BOOKREQUEST_CAB - Booking Cab Request
CREATE TABLE [BOOKREQUEST_CAB] (
    [BOOKCAB_ID] VARCHAR(255) NOT NULL  -- Cab Request ID,
    [BOOKCAB_MAINID] VARCHAR(255) NOT NULL  -- Request Main ID,
    [BOOKCAB_PICKUPLOC] VARCHAR(255) NOT NULL  -- Pick up location,
    [BOOKCAB_DROPLOC] VARCHAR(255) NOT NULL  -- Drop Location,
    [BOOKCAB_PICKUPDATE] DATETIME2(3) NOT NULL  -- Pick up Date/Time,
    [BOOKCAB_CARTYPE] VARCHAR(255) NULL  -- Car Type,
    [BOOKCAB_PREFERENCE] VARCHAR(255) NOT NULL  -- Preference Type (AC/Non AC),
    [BOOKCAB_TRIPTYPE] VARCHAR(255) NOT NULL  -- Trip for (Official/Personal) - OFF/PER,
    [BOOKCAB_ADDRESS] VARCHAR(255) NOT NULL  -- Pick up detailed address,
    [BOOKCAB_CNFNO] VARCHAR(255) NOT NULL  -- Confirmation No,
    [BOOKCAB_LASTMODIFIEDBY] VARCHAR(255) NOT NULL  -- Last ModifiedBy,
    [BOOKCAB_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last ModifiedOn,
    [BOOKCAB_NATURE] VARCHAR(255) NULL  -- Travel Nature,
    CONSTRAINT [PK_BOOKREQUEST_CAB] PRIMARY KEY ([BOOKCAB_ID])
);

-- Table: BOOKREQUEST_CC - Booking Cost Centre
CREATE TABLE [BOOKREQUEST_CC] (
    [BOOKCC_ID] VARCHAR(255) NOT NULL  -- Cost Centre ID,
    [BOOKCC_MAINID] VARCHAR(255) NOT NULL  -- Request Main ID,
    [BOOKCC_BUCODE] VARCHAR(255) NOT NULL  -- Unit,
    [BOOKCC_CCCODE] VARCHAR(255) NOT NULL  -- Location,
    [BOOKCC_SUBACCCODE] VARCHAR(255) NOT NULL  -- Cost Centre,
    [BOOKCC_PRODUCTCODE] VARCHAR(255) NOT NULL  -- Sub Account Code,
    [BOOKCC_LOCSEGMENT] VARCHAR(255) NOT NULL  -- Product,
    [BOOKCC_ALLLPER] VARCHAR(255) NOT NULL  -- Percentage,
    CONSTRAINT [PK_BOOKREQUEST_CC] PRIMARY KEY ([BOOKCC_ID])
);

-- Table: BOOKREQUEST_OTHERS - Booking Guest Info
CREATE TABLE [BOOKREQUEST_OTHERS] (
    [BOOKOTH_ID] VARCHAR(255) NOT NULL  -- Request Sub ID,
    [BOOKOTH_BOOKID] VARCHAR(255) NOT NULL  -- Request ID,
    [BOOKOTH_FOR] VARCHAR(255) NOT NULL  -- Booking for - In case of direct,
    [BOOKOTH_GENDER] VARCHAR(255) NOT NULL  -- Gender (Male/Female) = M/F,
    [BOOKOTH_AGE] VARCHAR(255) NOT NULL  -- Age,
    [BOOKOTH_CONTACTNO] VARCHAR(255) NOT NULL  -- Contact No,
    [BOOKOTH_APPROVEDBY] VARCHAR(255) NOT NULL  -- Approved By,
    [BOOKOTH_APPROVEDON] DATETIME2(3) NULL  -- Approved On,
    CONSTRAINT [PK_BOOKREQUEST_OTHERS] PRIMARY KEY ([BOOKOTH_ID])
);

-- Table: BOOKREQUEST_CONFIRMATION - Booking Confirmation
CREATE TABLE [BOOKREQUEST_CONFIRMATION] (
    [BOOKCNF_ID] VARCHAR(255) NOT NULL  -- Booking confirmation ID,
    [BOOKCNF_MODE] VARCHAR(255) NOT NULL  -- Type of Booking CAB/TKT-TICKET/STY- Stay,
    [BOOKCNF_BOOKID] VARCHAR(255) NOT NULL  -- Booking Request ID,
    [BOOKCNF_REFID] VARCHAR(255) NOT NULL  -- Ticketid/Stayid/Cab ID,
    [BOOKCNF_DATE] DATETIME2(3) NOT NULL  -- Confirmation Entry Date,
    [BOOKCNF_STARTDATE] DATETIME2(3) NOT NULL  -- Checkin Date & Time/ Departure Date,
    [BOOKCNF_ENDDATE] DATETIME2(3) NOT NULL  -- Checkout Date & Time,
    [BOOKCNF_COST] VARCHAR(255) NOT NULL  -- Cost of Ticket,
    [BOOKCNF_CLASSID] VARCHAR(255) NOT NULL  -- Ticket Class ID,
    [BOOKCNF_VENDORID] VARCHAR(255) NOT NULL  -- Vendor ID,
    [BOOKCNF_GHSITEID] VARCHAR(255) NOT NULL  -- Guest House Site ID,
    [BOOKCNF_CABCONFID] VARCHAR(255) NOT NULL  -- Cab Confirmation ID,
    [BOOKCNF_REFUNDCOST] VARCHAR(255) NOT NULL  -- Cost of Ticket - Refund,
    [BOOKCNF_CANCELDATE] DATETIME2(3) NOT NULL  -- Cancellation Entry Date,
    [BOOKCNF_DEBITMEMOBATCH] VARCHAR(255) NOT NULL  -- Debit Memo Batch ID,
    [BOOKCNF_CREDITMEMOBATCH] VARCHAR(255) NOT NULL  -- Credit Memo Batch ID,
    [BOOKCNF_ADMREMARKS] VARCHAR(255) NOT NULL  -- Admin remarks,
    [BOOKCNF_LASTMODIFIEDON] DATETIME2(3) NOT NULL  -- Last Modified On,
    [BOOKCNF_LASTMODIFIEDBY] VARCHAR(255) NOT NULL  -- Last Modified By,
    [BOOKCNF_CONFIRMEDBY] VARCHAR(255) NOT NULL  -- Confirmed By (A /V),
    [BOOKCNF_VENDORSLF] VARCHAR(255) NULL  -- Self Entry by Vendor (Y/N),
    [BOOKCNF_ATTACHMENT] VARCHAR(255) NULL  -- Attachment file name,
    [BOOKCNF_APPROVALSTS] VARCHAR(255) NOT NULL  -- Confirmation approval Status,
    [BOOKCNF_ENTID] VARCHAR(255) NULL  -- Entered by ID (Vendor UserID),
    [BOOKCNF_OLDREQID] VARCHAR(255) NOT NULL  -- Re-issue old request ID,
    [BOOKCNF_AIRLINEVNDID] VARCHAR(255) NULL  -- Airline Vendor ID,
    [BOOKCNF_AIRPNRNUM] VARCHAR(255) NULL  -- Airline PNR Number,
    CONSTRAINT [PK_BOOKREQUEST_CONFIRMATION] PRIMARY KEY ([BOOKCNF_ID])
);

-- Table: BOOKCONF_CAB - Book confirmation cab
CREATE TABLE [BOOKCONF_CAB] (
    [CNFCAB_CONFID] BIGINT NOT NULL  -- Booking confirmation ID,
    [CNFCAB_BOOKID] BIGINT NOT NULL  -- Booking Request ID,
    [CNFCAB_ID] BIGINT NOT NULL  -- CAB Id,
    CONSTRAINT [PK_BOOKCONF_CAB] PRIMARY KEY ([CNFCAB_CONFID])
);

-- Table: BOOKCONF_TICKET - Booking Tickets Confirmation
CREATE TABLE [BOOKCONF_TICKET] (
    [CNFTKT_ID] VARCHAR(255) NULL  -- Booking confirmation ID,
    [CNFTKT_BOOKID] VARCHAR(255) NULL  -- Booking Request ID,
    [CNFTKT_TICKETID] VARCHAR(255) NULL  -- Ticket ID,
    [CNFTKT_ENTDATE] DATETIME2(3) NULL  -- Confirmation Entry Date,
    [CNFTKT_DEPDATE] DATETIME2(3) NULL  -- Departure Date,
    [CNFTKT_COST] VARCHAR(255) NOT NULL  -- Ticket Cost,
    [CNFTKT_CNFID] VARCHAR(255) NULL  -- Confirmation Main ID,
    CONSTRAINT [PK_BOOKCONF_TICKET] PRIMARY KEY ([CNFTKT_ID])
);

-- Table: BOOKCONF_STAY - Booking Stay Confirmation
CREATE TABLE [BOOKCONF_STAY] (
    [CNFSTY_ID] VARCHAR(255) NULL  -- Stay ID,
    [CNFSTY_BOOKID] VARCHAR(255) NULL  -- Booking Request ID,
    [CNFSTY_CHECKINDATE] DATETIME2(3) NULL  -- Check in Date,
    [CNFSTY_CHECKOUTDATE] DATETIME2(3) NULL  -- Check out Date,
    [CNFSTY_GHSITEID] VARCHAR(255) NOT NULL  -- Guest House Site ID,
    [CNFSTY_CNFID] VARCHAR(255) NOT NULL  -- Confirmation Main ID,
    CONSTRAINT [PK_BOOKCONF_STAY] PRIMARY KEY ([CNFSTY_ID])
);

-- Table: BOOKCONFIRMATION_CC - book confirmation cc
CREATE TABLE [BOOKCONFIRMATION_CC] (
    [BOOKCNFCC_ID] BIGINT NOT NULL  -- Cost Centre ID,
    [BOOKCNFCC_MAINID] BIGINT NOT NULL  -- Booking confirmation Request Main ID,
    [BOOKCNF_BUCODE] VARCHAR(25) NULL  -- Unit,
    [BOOKCNF_CCCODE] VARCHAR(255) NULL  -- Cost Centre,
    [BOOKCNF_SUBACCCODE] VARCHAR(255) NULL  -- Sub Account Code,
    [BOOKCNF_PRODUCTCODE] VARCHAR(255) NULL  -- Product,
    [BOOKCNF_LOCSEGMENT] VARCHAR(255) NULL  -- Location,
    [BOOKCNF_ALLLPER] INT NULL  -- Percentage,
    CONSTRAINT [PK_BOOKCONFIRMATION_CC] PRIMARY KEY ([BOOKCNFCC_ID])
);

-- Table: BOOKCONFIRMATION_MAIN - Booking Confirmation
CREATE TABLE [BOOKCONFIRMATION_MAIN] (
    [BOOKCNF_ID] VARCHAR(255) NULL  -- Booking confirmation ID,
    [BOOKCNF_MODE] VARCHAR(255) NULL  -- Type of Booking CAB/TKT-TICKET/STY- Stay,
    [BOOKCNF_BOOKID] VARCHAR(255) NULL  -- Booking Request ID,
    [BOOKCNF_REFID] VARCHAR(255) NULL  -- Ticketid/Stayid/Cab ID,
    [BOOKCNF_DATE] DATETIME2(3) NULL  -- Confirmation Entry Date,
    [BOOKCNF_STARTDATE] DATETIME2(3) NULL  -- From Date Check IN date/Departure Date/Pickup Date,
    [BOOKCNF_ENDDATE] DATETIME2(3) NULL  -- To Date Checkout Date,
    [BOOKCNF_BOOKTYPE] VARCHAR(255) NULL  -- Mode sub type,
    [BOOKCNF_STATUS] VARCHAR(255) NULL  -- Booked/Cancelled/Payment Processed,
    [BOOKCNF_REMARKS] VARCHAR(255) NULL  -- Admin Remarks,
    [BOOKCNF_ADMUNIT] VARCHAR(255) NULL  -- Admin Unit,
    [BOOKCNF_PAYBATCHNO] VARCHAR(255) NULL  -- Payment Batch No,
    [BOOKCNF_CONTRACTID] VARCHAR(255) NULL  -- Contract ID of Ticket/Stay/Cab,
    [BOOKCNF_VENDORID] VARCHAR(255) NULL  -- Vendor ID,
    [BOOKCNF_TRIPCODE] VARCHAR(255) NULL  -- Personal/Official
);

PRINT 'BOOKING Module - Tables created successfully.';
GO
