-- EmployeeRelations Module - Tables
USE [HRDB];
GO

-- Table: DISCIPLINARY_ACTION
CREATE TABLE [DISCIPLINARY_ACTION] (
    [DISACTION_ID] DECIMAL(38) NOT NULL  -- Disciplinary Action ID,
    [DISACTION_MAINID] DECIMAL(38) NOT NULL  -- Disciplinary Main ID from  DISCIPLINARY_MAIN,
    [DISACTION_EMPSYSID] DECIMAL(38) NOT NULL  -- Employee Sys ID,
    [DISACTION_TYPEID] DECIMAL(38) NOT NULL  -- Action Type,
    [DISACTION_DATE] DATETIME2(3) NOT NULL  -- Action Taken Date,
    [DISACTION_REMARKS] VARCHAR(500) NOT NULL  -- Action Remarks,
    [DISACTION_DOC] VARCHAR(100) NULL  -- Action Related File,
    [DISACTION_ENTRYSTATUS] CHAR(1) NOT NULL  -- E-Entered, A- Approved,R- Returned,
    [DISACTION_CREATEDBY] DECIMAL(38) NOT NULL  -- Created By,
    [DISACTION_CREATEDON] DATETIME2(3) NOT NULL  -- Created On,
    [DISACTION_MODIFIEDBY] DECIMAL(38) NULL  -- Modified by,
    [DISACTION_MODIFIEDON] DATETIME2(3) NULL  -- Modified On,
    [DISACTION_APPROVEDBY] DECIMAL(38) NULL  -- Approved by,
    [DISACTION_APPROVEDON] DATETIME2(3) NULL  -- Approved On,
    [DISACTION_RETURNREMARKS] VARCHAR(500) NULL  -- Return remarks,
    CONSTRAINT [PK_DISCIPLINARY_ACTION] PRIMARY KEY ([DISACTION_ID])
);



-- Table: DISCIPLINARY_EMP
CREATE TABLE [DISCIPLINARY_EMP] (
    [DISEMP_MAINID] DECIMAL(38) NOT NULL  -- Disciplinary Main ID from  DISCIPLINARY_MAIN,
    [DISEMP_EMPSYSID] DECIMAL(38) NOT NULL  -- Employee Sys ID,
    [DISEMP_MODIFIEDBY] DECIMAL(38) NULL  -- Last Modified by,
    [DISEMP_MODIFIEDON] DATETIME2(3) NULL  -- Last Modified on
);



-- Table: DISCIPLINARY_MAIN
CREATE TABLE [DISCIPLINARY_MAIN] (
    [DISCIPLINE_MAINID] DECIMAL(38) NOT NULL  -- Main ID,
    [DISCIPLINE_UNITID] DECIMAL(38) NOT NULL  -- Unit ID,
    [DISCIPLINE_DATE] DATETIME2(3) NOT NULL  -- Date,
    [DISCIPLINE_DETAILS] VARCHAR(500) NOT NULL  -- InDiscipline Details,
    [DISCIPLINE_CREATEDBY] DECIMAL(38) NOT NULL  -- Created By,
    [DISCIPLINE_CREATEDON] DATETIME2(3) NOT NULL  -- Created On,
    [DISCIPLINE_MODIFIEDBY] DECIMAL(38) NULL  -- Modified by,
    [DISCIPLINE_MODIFIEDON] DATETIME2(3) NULL  -- Modified On,
    CONSTRAINT [PK_DISCIPLINARY_MAIN] PRIMARY KEY ([DISCIPLINE_MAINID])
);



-- Table: EWS_MAIN
CREATE TABLE [EWS_MAIN] (
    [EWS_ID] BIGINT NOT NULL  -- EWS ID,
    [EWS_EMPSYSID] BIGINT NOT NULL  -- Employee System ID,
    [EWS_PERIODNO] INT NOT NULL  -- Period No,
    [EWS_HRENTRYBY] BIGINT NULL  -- HR Entry By,
    [EWS_HRENTRYDATE] DATETIME2(3) NULL  -- HR Entry Date,
    [EWS_HRFLAG] CHAR(1) NULL  -- R - Red / G - Green / A - Amber,
    [EWS_STATUS] CHAR(1) NOT NULL  -- EWS Status ( N - Pending for HR Inputs ; A - Form Pending for Appraiser Inputs; Y - Form Completed by Appraiser),
    [EWS_EES] CHAR(1) NULL  -- R - Red / G - Green / A - Amber,
    [EWS_PULSE] CHAR(1) NULL  -- R - Red / G - Green / A - Amber,
    [EWS_DD] CHAR(1) NULL  -- R - Red / G - Green / A - Amber,
    [EWS_IJP] CHAR(1) NULL  -- R - Red / G - Green / A - Amber,
    [EWS_COMP] CHAR(1) NULL  -- R - Red / G - Green / A - Amber,
    [EWS_LEAVE] CHAR(1) NULL  -- R - Red / G - Green / A - Amber,
    [EWS_FINAL] CHAR(1) NULL  -- R - Red / G - Green / A - Amber,
    [EWS_HRREMARKS] VARCHAR(500) NULL,
    [EWS_CHRFLAG] CHAR(1) NULL  -- CHR Flag,
    [EWS_CHRREMARKS] VARCHAR(500) NULL,
    [EWS_APRFLAG] CHAR(1) NULL,
    [EWS_APRREMARKS] VARCHAR(500) NULL,
    [EWS_REOPEN] CHAR(1) NULL,
    [EWS_REOPENBY] BIGINT NULL,
    [EWS_GRADEID] DECIMAL(38) NULL,
    [EWS_CTC] DECIMAL(19,0) NULL,
    [EWS_APRSCORE] CHAR(1) NULL,
    CONSTRAINT [PK_EWS_MAIN] PRIMARY KEY ([EWS_ID])
);



-- Table: EWS_APPINPUTS
CREATE TABLE [EWS_APPINPUTS] (
    [APP_INPUTID] BIGINT NOT NULL  -- Approver Input ID,
    [APP_EWSID] BIGINT NOT NULL  -- EWS ID,
    [APP_EMPSYSID] BIGINT NOT NULL  -- Approver Employee System ID,
    [APP_TYPE] CHAR(1) NOT NULL  -- Approver type (P- Primary / S - Secondary),
    [APP_ENTEREDON] DATETIME2(3) NULL  -- Approver Entered On,
    [APP_ENGLEVEL] CHAR(1) NULL  -- Engagement Level,
    [APP_LEAVEFLAG] CHAR(1) NULL  -- Leave Flag,
    [APP_REMARKS] VARCHAR(200) NULL  -- Approver Remarks if any,
    [APRR_REOPEN] CHAR(1) NULL,
    CONSTRAINT [PK_EWS_APPINPUTS] PRIMARY KEY ([APP_INPUTID])
);



-- Table: EWS_CATEGORY
CREATE TABLE [EWS_CATEGORY] (
    [EWS_CATID] DECIMAL(38) NOT NULL,
    [EWS_CATCODE] CHAR(1) NOT NULL,
    [EWS_CATDESC] VARCHAR(50) NOT NULL,
    CONSTRAINT [PK_EWS_CATEGORY] PRIMARY KEY ([EWS_CATID])
);



-- Table: EWS_FACTORS
CREATE TABLE [EWS_FACTORS] (
    [EWS_FACTORID] BIGINT NULL  -- Factor Id,
    [EWS_DESC] VARCHAR(200) NULL  -- Factor Description,
    [EWS_EFFDATE] DATETIME2(3) NULL  -- Eff Date,
    [EWS_CLSDATE] DATETIME2(3) NULL  -- Closure Date,
    [EWS_MODBY] DECIMAL(38) NULL  -- Modified By,
    [EWS_MODON] DATETIME2(3) NULL  -- Modified On
);



-- Table: EWS_MENU
CREATE TABLE [EWS_MENU] (
    [MENUID] DECIMAL(38) NOT NULL,
    [MENUCODE] CHAR(3) NOT NULL,
    [MENUDESC] VARCHAR(200) NOT NULL,
    [ACTIVEFLAG] CHAR(1) NOT NULL,
    [REMARKS] VARCHAR(500) NULL,
    CONSTRAINT [PK_EWS_MENU] PRIMARY KEY ([MENUID])
);



-- Table: EWS_PERIOD
CREATE TABLE [EWS_PERIOD] (
    [PERIOD_ID] INT NOT NULL  -- Period No,
    [PERIOD_YEAR] INT NOT NULL  -- Period Year,
    [PERIOD_QUARTER] INT NOT NULL  -- Quarter No (1,2,3,4),
    [PERIOD_FROMDATE] DATETIME2(3) NOT NULL  -- From Date,
    [PERIOD_TODATE] DATETIME2(3) NOT NULL  -- To Date,
    [PERIOD_LIVEFLAG] CHAR(1) NOT NULL  -- Live Flag,
    [PERIOD_RELEASEDATE] DATETIME2(3) NOT NULL  -- Mail Trigger Date,
    [PERIOD_LEAVESTART] DATETIME2(3) NOT NULL,
    [PERIOD_CLOSEDATE] DATETIME2(3) NOT NULL,
    [PERIOD_DDYEAR] INT NULL,
    [PERIOD_DDPREVYEAR] INT NULL,
    [PERIOD_EESID] INT NULL,
    [PERIOD_STATUS] CHAR(1) NOT NULL,
    CONSTRAINT [PK_EWS_PERIOD] PRIMARY KEY ([PERIOD_ID])
);



-- Table: EWS_TRIGGER
CREATE TABLE [EWS_TRIGGER] (
    [TR_ID] BIGINT NOT NULL  -- Trigger ID,
    [TR_EMPSYSID] BIGINT NOT NULL  -- Employee System ID,
    [TR_DATE] DATETIME2(3) NOT NULL  -- Trigger On,
    [TR_INPUTBY] CHAR(3) NOT NULL  -- Input By (UHR/BHR/CHR/APP),
    [TR_INPUTEMPSYSID] BIGINT NOT NULL  -- Input given by Employee System ID,
    [TR_INPUTREMARKS] VARCHAR(500) NOT NULL  -- Input Remarks,
    [TR_INPUTFLAG] CHAR(1) NOT NULL,
    CONSTRAINT [PK_EWS_TRIGGER] PRIMARY KEY ([TR_ID])
);



-- Table: EWS_VALUES
CREATE TABLE [EWS_VALUES] (
    [VALID] DECIMAL(38) NOT NULL,
    [TYPE] CHAR(1) NOT NULL,
    [EWSID] BIGINT NOT NULL,
    [PERNUM] INT NOT NULL,
    [SURID] BIGINT NULL,
    [ANSID] BIGINT NULL,
    [FEEDBACK] VARCHAR(200) NULL,
    [UPDON] DATETIME2(3) NULL,
    [SFLAG] VARCHAR(2) NULL,
    [GAP] DECIMAL(38) NULL,
    [LTYPE] VARCHAR(2) NULL,
    [FLAG] CHAR(1) NULL,
    [PREVLEV] DATETIME2(3) NULL,
    [PREVLTYPE] CHAR(2) NULL,
    [GRADE] VARCHAR(50) NULL,
    [RATING] VARCHAR(5) NULL,
    [BUSINESS] VARCHAR(10) NULL,
    [CTC] DECIMAL(19,0) NULL,
    [PROMDATE] DATETIME2(3) NULL,
    [BANDMEDIAN] DECIMAL(19,0) NULL,
    [BANDMEDPER] VARCHAR(20) NULL,
    [YEARID] DECIMAL(38) NULL,
    [RORDER] DECIMAL(38) NULL,
    [PERIOD] VARCHAR(30) NULL,
    [DDINCAMT] DECIMAL(19,0) NULL,
    [DDINCPER] DECIMAL(19,0) NULL,
    [DDCTCAMT] DECIMAL(19,0) NULL,
    CONSTRAINT [PK_EWS_VALUES] PRIMARY KEY ([VALID])
);



-- Table: SURVEY_MASTER
CREATE TABLE [SURVEY_MASTER] (
    [SURVEY_ID] BIGINT NOT NULL  -- Survey ID,
    [SURVEY_NAME] VARCHAR(100) NOT NULL  -- Survey Name,
    [SURVEY_IMAGE] VARCHAR(100) NOT NULL  -- Survey Picture,
    [SURVEY_STARTDATE] DATETIME2(3) NOT NULL  -- Survey Start Date,
    [SURVEY_ENDDATE] DATETIME2(3) NULL  -- Survey Last Date,
    [SURVEY_CLSDATE] DATETIME2(3) NULL  -- Survey Closure  Date,
    [SURVEY_AUTOLOCK] CHAR(1) NOT NULL  -- Auto Closure Sparsh after Duedate,
    [SURVEY_FLAG] CHAR(1) NULL,
    [SURVEY_TEMPLATEID] BIGINT NULL,
    CONSTRAINT [PK_SURVEY_MASTER] PRIMARY KEY ([SURVEY_ID])
);



-- Table: SURVEY_QUESTIONS
CREATE TABLE [SURVEY_QUESTIONS] (
    [SURVEY_QUESTID] BIGINT NOT NULL  -- Question ID,
    [SURVEY_ID] BIGINT NOT NULL  -- Survey ID,
    [SURVEY_QUESTNAME] VARCHAR(1000) NOT NULL  -- Question Name,
    [SURVEY_QUESTTYPE] VARCHAR(100) NOT NULL  -- Question Type (TextBox/Multi TextBox/Radio Button List/CheckBox List/Dropdown List  -TEXTBOX/MTEXTBOX/RADIOLIST/CHECKLIST/COMBOBOX),
    [SURVEY_MAXOPTLIMIT] INT NULL  -- Multi Select Max Limit,
    [SURVEY_SECTIONID] BIGINT NOT NULL  -- Section Head ID,
    [SURVEY_MANDATORY] CHAR(1) NOT NULL  -- Mandatory,
    [SURVEY_SORT] BIGINT NOT NULL  -- Question sort Order,
    [SURVEY_MINOPTLIMIT] INT NULL  -- Multi Select Min Limit,
    CONSTRAINT [PK_SURVEY_QUESTIONS] PRIMARY KEY ([SURVEY_QUESTID])
);



-- Table: SURVEY_OPTIONS
CREATE TABLE [SURVEY_OPTIONS] (
    [SURVEY_OPTIONID] BIGINT NOT NULL  -- Option ID,
    [SURVEY_QUESTIONID] BIGINT NOT NULL  -- Question ID,
    [SURVEY_DESCRIPTION] VARCHAR(200) NOT NULL  -- Option Description,
    CONSTRAINT [PK_SURVEY_OPTIONS] PRIMARY KEY ([SURVEY_OPTIONID])
);



-- Table: SURVEY_RESPONSEMAIN
CREATE TABLE [SURVEY_RESPONSEMAIN] (
    [RESPONSE_ID] BIGINT NOT NULL,
    [RESPONSE_SURVEYID] BIGINT NOT NULL,
    [RESPONSE_EMPSYSID] BIGINT NOT NULL,
    [RESPONSE_UPDATEDBY] BIGINT NOT NULL,
    [RESPONSE_UPDATEDON] DATETIME2(3) NOT NULL,
    [RESPONSE_STATUS] CHAR(1) NOT NULL,
    [RESPONSE_SKIP] BIGINT NULL,
    CONSTRAINT [PK_SURVEY_RESPONSEMAIN] PRIMARY KEY ([RESPONSE_ID])
);



-- Table: SURVEY_RESPONSEDET
CREATE TABLE [SURVEY_RESPONSEDET] (
    [RESPONSE_QUESTIONID] BIGINT NOT NULL,
    [RESPONSE_ID] BIGINT NOT NULL,
    [RESPONSE_OPTION] VARCHAR(1000) NULL,
    [RESPONSE_TEXT] VARCHAR(1000) NULL
);

