// <auto-generated />
using System;
using BookingService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingService.Domain.Entities.BookingConfirmation", b =>
                {
                    b.Property<long>("BkCnfNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("BK_CNF_NUM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BkCnfNum"));

                    b.Property<string>("BkAdmRmk")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("BK_ADM_RMK");

                    b.Property<DateTime?>("BkAdmnBokdat")
                        .HasColumnType("datetime2")
                        .HasColumnName("BK_ADMN_BOKDAT");

                    b.Property<long?>("BkAgnCod")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_AGN_COD");

                    b.Property<string>("BkAirLin")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("BK_AIR_LIN");

                    b.Property<string>("BkAppSts")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("BK_APP_STS");

                    b.Property<long?>("BkBokNum")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_BOK_NUM");

                    b.Property<string>("BkCabAdd")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("BK_CAB_ADD");

                    b.Property<long?>("BkCabSegment")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_CAB_SEGMENT");

                    b.Property<string>("BkCabUnit")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("BK_CAB_UNIT");

                    b.Property<long>("BkCnfSrl")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_CNF_SRL");

                    b.Property<string>("BkCostCod")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("BK_COST_COD");

                    b.Property<long?>("BkCpnCod")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_CPN_COD");

                    b.Property<long?>("BkCpnTck")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_CPN_TCK");

                    b.Property<string>("BkDrvNam")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BK_DRV_NAM");

                    b.Property<string>("BkFrmLoc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BK_FRM_LOC");

                    b.Property<long?>("BkFroCit")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_FRO_CIT");

                    b.Property<DateTime?>("BkFroDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("BK_FRO_DAT");

                    b.Property<long?>("BkGheCod")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_GHE_COD");

                    b.Property<long>("BkModCod")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_MOD_COD");

                    b.Property<long?>("BkNoPer")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_NO_PER");

                    b.Property<long?>("BkPheNum")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_PHE_NUM");

                    b.Property<string>("BkProductCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("BK_PRODUCT_CODE");

                    b.Property<string>("BkRegnNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BK_REGN_NO");

                    b.Property<DateTime?>("BkReqDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("BK_REQ_DAT");

                    b.Property<string>("BkRomNum")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("BK_ROM_NUM");

                    b.Property<long?>("BkSlfCst")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_SLF_CST");

                    b.Property<string>("BkSlfFlg")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("BK_SLF_FLG");

                    b.Property<long?>("BkSrlNum")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_SRL_NUM");

                    b.Property<string>("BkStsCod")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("BK_STS_COD");

                    b.Property<string>("BkSubaccountCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("BK_SUBACCOUNT_CODE");

                    b.Property<string>("BkTckNum")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("BK_TCK_NUM");

                    b.Property<long?>("BkToCit")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_TO_CIT");

                    b.Property<DateTime?>("BkToDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("BK_TO_DAT");

                    b.Property<string>("BkToLoc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BK_TO_LOC");

                    b.Property<string>("BkTripCod")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("BK_TRIP_COD");

                    b.Property<long?>("BkTrlCls")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_TRL_CLS");

                    b.Property<long?>("BkTrlCst")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_TRL_CST");

                    b.Property<string>("BkTrlNam")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BK_TRL_NAM");

                    b.Property<string>("BkTrlNum")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BK_TRL_NUM");

                    b.Property<long?>("BkTrvlType")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_TRVL_TYPE");

                    b.Property<long?>("BkVndCod")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_VND_COD");

                    b.HasKey("BkCnfNum");

                    b.ToTable("BOOK_CONFIRMATION", "dbo");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.BookingForwardUnit", b =>
                {
                    b.Property<decimal>("BkBokNum")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("BK_BOK_NUM");

                    b.Property<decimal>("BkSrlNum")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("BK_SRL_NUM");

                    b.Property<long>("AdmUnit")
                        .HasColumnType("bigint")
                        .HasColumnName("ADM_UNIT");

                    b.Property<long>("FwdAdmUnit")
                        .HasColumnType("bigint")
                        .HasColumnName("FWD_ADM_UNIT");

                    b.Property<DateTime?>("FwdDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("FWD_DATE");

                    b.HasKey("BkBokNum", "BkSrlNum", "AdmUnit");

                    b.ToTable("BOOK_FORWARD_UNIT", "dbo");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.BookingRequest", b =>
                {
                    b.Property<decimal>("BkBokNum")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("BK_BOK_NUM");

                    b.Property<string>("BkAdmRem")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BK_ADM_REM");

                    b.Property<string>("BkAdmSlf")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("BK_ADM_SLF");

                    b.Property<int?>("BkAdmUnt")
                        .HasColumnType("int")
                        .HasColumnName("BK_ADM_UNT");

                    b.Property<string>("BkAirCod")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("BK_AIR_COD");

                    b.Property<DateTime?>("BkAppDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("BK_APP_DAT");

                    b.Property<string>("BkAppSts")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("BK_APP_STS");

                    b.Property<string>("BkBokTyp")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("BK_BOK_TYP");

                    b.Property<decimal?>("BkBudAmt")
                        .HasColumnType("decimal(19,0)")
                        .HasColumnName("BK_BUD_AMT");

                    b.Property<long?>("BkCabSegment")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_CAB_SEGMENT");

                    b.Property<string>("BkCabToAdd")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("BK_CAB_TO_ADD");

                    b.Property<string>("BkCabToCost")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("BK_CAB_TO_COST");

                    b.Property<string>("BkCabToFlg")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("BK_CAB_TO_FLG");

                    b.Property<string>("BkCabToTrip")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("BK_CAB_TO_TRIP");

                    b.Property<string>("BkCabToUnit")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("BK_CAB_TO_UNIT");

                    b.Property<DateTime?>("BkCanDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("BK_CAN_DAT");

                    b.Property<string>("BkCanRem")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BK_CAN_REM");

                    b.Property<string>("BkCanUsr")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("BK_CAN_USR");

                    b.Property<long?>("BkCnfNum")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_CNF_NUM");

                    b.Property<long?>("BkDepNos")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_DEP_NOS");

                    b.Property<decimal?>("BkFrmTim")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("BK_FRM_TIM");

                    b.Property<long?>("BkFroCit")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_FRO_CIT");

                    b.Property<DateTime?>("BkFroDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("BK_FRO_DAT");

                    b.Property<string>("BkFroLoc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BK_FRO_LOC");

                    b.Property<long?>("BkModCod")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_MOD_COD");

                    b.Property<string>("BkPckFlg")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("BK_PCK_FLG");

                    b.Property<string>("BkPerNam")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BK_PER_NAM");

                    b.Property<string>("BkPerSex")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("BK_PER_SEX");

                    b.Property<string>("BkPerSts")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("BK_PER_STS");

                    b.Property<string>("BkProductCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("BK_PRODUCT_CODE");

                    b.Property<long?>("BkReqNum")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_REQ_NUM");

                    b.Property<long?>("BkReqTyp")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_REQ_TYP");

                    b.Property<DateTime?>("BkRetDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("BK_RET_DAT");

                    b.Property<decimal?>("BkRetTim")
                        .HasColumnType("decimal(38,0)")
                        .HasColumnName("BK_RET_TIM");

                    b.Property<decimal>("BkSrlNum")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("BK_SRL_NUM");

                    b.Property<string>("BkSubaccountCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("BK_SUBACCOUNT_CODE");

                    b.Property<long?>("BkToCit")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_TO_CIT");

                    b.Property<string>("BkToLoc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BK_TO_LOC");

                    b.Property<long?>("BkTraCls")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_TRA_CLS");

                    b.Property<long?>("BkTrvlType")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_TRVL_TYPE");

                    b.Property<string>("BkUsrCod")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("BK_USR_COD");

                    b.Property<long?>("BkUsrNum")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_USR_NUM");

                    b.HasKey("BkBokNum");

                    b.ToTable("BOOK_REQUEST", "dbo");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.CabPick", b =>
                {
                    b.Property<string>("CityFrom")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("CITYFROM");

                    b.Property<string>("CityTo")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("CITYTO");

                    b.Property<string>("PickFlag")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("PICKFLAG");

                    b.ToTable("CABPICK", "dbo");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.CouponMain", b =>
                {
                    b.Property<long>("CpnCupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CPN_CUP_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CpnCupId"));

                    b.Property<string>("CpnAdnUnt")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CPN_ADN_UNT");

                    b.Property<string>("CpnAdnUsr")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CPN_ADN_USR");

                    b.Property<string>("CpnArlNam")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("CPN_ARL_NAM");

                    b.Property<long?>("CpnCupCst")
                        .HasColumnType("bigint")
                        .HasColumnName("CPN_CUP_CST");

                    b.Property<long?>("CpnCupEnd")
                        .HasColumnType("bigint")
                        .HasColumnName("CPN_CUP_END");

                    b.Property<long?>("CpnCupStr")
                        .HasColumnType("bigint")
                        .HasColumnName("CPN_CUP_STR");

                    b.Property<string>("CpnIseRek")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CPN_ISE_REK");

                    b.Property<DateTime?>("CpnIssDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("CPN_ISS_DAT");

                    b.Property<long?>("CpnNofTck")
                        .HasColumnType("bigint")
                        .HasColumnName("CPN_NOF_TCK");

                    b.Property<string>("CpnRefId")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("CPN_REF_ID");

                    b.Property<long?>("CpnReqId")
                        .HasColumnType("bigint")
                        .HasColumnName("CPN_REQ_ID");

                    b.Property<string>("CpnUsgFlg")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("CPN_USG_FLG");

                    b.Property<string>("CpnUsrId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CPN_USR_ID");

                    b.Property<long?>("CpnUsrPin")
                        .HasColumnType("bigint")
                        .HasColumnName("CPN_USR_PIN");

                    b.Property<DateTime?>("CpnVldFrm")
                        .HasColumnType("datetime2")
                        .HasColumnName("CPN_VLD_FRM");

                    b.Property<DateTime?>("CpnVldTo")
                        .HasColumnType("datetime2")
                        .HasColumnName("CPN_VLD_TO");

                    b.HasKey("CpnCupId");

                    b.ToTable("COUPON_MAIN", "dbo");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.CouponRequest", b =>
                {
                    b.Property<long>("CpnReqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CPN_REQ_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CpnReqId"));

                    b.Property<DateTime?>("CpnActDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("CPN_ACT_DAT");

                    b.Property<string>("CpnActRmk")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CPN_ACT_RMK");

                    b.Property<string>("CpnApvUsr")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CPN_APV_USR");

                    b.Property<long?>("CpnArgUnt")
                        .HasColumnType("bigint")
                        .HasColumnName("CPN_ARG_UNT");

                    b.Property<string>("CpnArlNam")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("CPN_ARL_NAM");

                    b.Property<long?>("CpnFlxFld1")
                        .HasColumnType("bigint")
                        .HasColumnName("CPN_FLX_FLD1");

                    b.Property<string>("CpnFlxFld2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CPN_FLX_FLD2");

                    b.Property<DateTime?>("CpnFlxFld3")
                        .HasColumnType("datetime2")
                        .HasColumnName("CPN_FLX_FLD3");

                    b.Property<string>("CpnFlxFld4")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CPN_FLX_FLD4");

                    b.Property<long?>("CpnNofCpn")
                        .HasColumnType("bigint")
                        .HasColumnName("CPN_NOF_CPN");

                    b.Property<DateTime?>("CpnReqDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("CPN_REQ_DAT");

                    b.Property<string>("CpnReqRmk")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CPN_REQ_RMK");

                    b.Property<string>("CpnReqSts")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("CPN_REQ_STS");

                    b.Property<string>("CpnReqUsr")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CPN_REQ_USR");

                    b.HasKey("CpnReqId");

                    b.ToTable("COUPON_REQUEST", "dbo");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.CouponSub", b =>
                {
                    b.Property<long?>("CpnCupId")
                        .HasColumnType("bigint")
                        .HasColumnName("CPN_CUP_ID");

                    b.Property<long?>("CpnSrlNum")
                        .HasColumnType("bigint")
                        .HasColumnName("CPN_SRL_NUM");

                    b.Property<string>("CpnTckNum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CPN_TCK_NUM");

                    b.Property<string>("CpnUsgFlg")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("CPN_USG_FLG");

                    b.ToTable("COUPON_SUB", "dbo");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.RoomAvailTemp", b =>
                {
                    b.Property<DateTime?>("BkFrodat")
                        .HasColumnType("datetime2")
                        .HasColumnName("BK_FRODAT");

                    b.Property<long?>("BkGhcode")
                        .HasColumnType("bigint")
                        .HasColumnName("BK_GHCODE");

                    b.Property<string>("BkRoomno")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("BK_ROOMNO");

                    b.Property<DateTime?>("BkTodat")
                        .HasColumnType("datetime2")
                        .HasColumnName("BK_TODAT");

                    b.Property<int?>("TotalHrOccupied")
                        .HasColumnType("int")
                        .HasColumnName("TOTALHR_OCCUPIED");

                    b.ToTable("ROOMAVAIL_TEMP", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
