apiVersion: v1
kind: Secret
metadata:
  name: erp-secrets
  namespace: erp-system
type: Opaque
stringData:
  SQL_SA_PASSWORD: "YourStr0ng!Passw0rd"
  RABBITMQ_PASSWORD: "guest"
  # Connection strings per service
  ACCESS_DB_CONN: "Server=sqlserver-service;Database=ACCESSDB;User Id=sa;Password=YourStr0ng!Passw0rd;TrustServerCertificate=true;"
  ATTENDANCE_DB_CONN: "Server=sqlserver-service;Database=ATTENDANCEDB;User Id=sa;Password=YourStr0ng!Passw0rd;TrustServerCertificate=true;"
  BUS_DB_CONN: "Server=sqlserver-service;Database=BUSDB;User Id=sa;Password=YourStr0ng!Passw0rd;TrustServerCertificate=true;"
  CALENDAR_DB_CONN: "Server=sqlserver-service;Database=CALENDARDB;User Id=sa;Password=YourStr0ng!Passw0rd;TrustServerCertificate=true;"
  EMPLOYEE_DB_CONN: "Server=sqlserver-service;Database=EMPLOYEEDB;User Id=sa;Password=YourStr0ng!Passw0rd;TrustServerCertificate=true;"
  GROUPINCENTIVE_DB_CONN: "Server=sqlserver-service;Database=GROUPINCENTIVEDB;User Id=sa;Password=YourStr0ng!Passw0rd;TrustServerCertificate=true;"
  LEAVE_DB_CONN: "Server=sqlserver-service;Database=LEAVEDB;User Id=sa;Password=YourStr0ng!Passw0rd;TrustServerCertificate=true;"
  REFERENCE_DB_CONN: "Server=sqlserver-service;Database=REFERENCEDB;User Id=sa;Password=YourStr0ng!Passw0rd;TrustServerCertificate=true;"
  VISITOR_DB_CONN: "Server=sqlserver-service;Database=VISITORDB;User Id=sa;Password=YourStr0ng!Passw0rd;TrustServerCertificate=true;"
  # JWT keys per service
  JWT_KEY_GATEWAY: "ApiGateway_SuperSecretSigningKey_2026_MinLength32Chars!!"
  JWT_KEY_ACCESS: "your-very-long-secret-key-here-min-32-characters"
  JWT_KEY_ATTENDANCE: "AttendanceSuperSecretKey_Change_In_Production_2026!"
  JWT_KEY_BUS: "BusServices-SuperSecretKey-Min32Chars!!"
  JWT_KEY_CALENDAR: "CalendarServiceSuperSecretKey_ChangeInProd_256bit!"
  JWT_KEY_EMPLOYEE: "EmployeeServiceSuperSecretSigningKey2026!!"
  JWT_KEY_GROUPINCENTIVE: "GroupIncentiveService_Super_Secret_Key_2026_MinLength32Chars!"
  JWT_KEY_LEAVE: "CHANGE_ME_TO_A_STRONG_256BIT_SECRET_KEY_IN_PRODUCTION"
  JWT_KEY_REFERENCE: "your-secret-key-must-be-at-least-32-characters-long!"
  JWT_KEY_VISITOR: "VisitorServices_SuperSecretKey_32chars!"
