-- ==========================================
-- UserManagementModule
-- Database: SRFSPARSHDB
-- Module Purpose: User Profile and Policy Management
-- Created: March 09, 2026
-- ==========================================

USE SRFSPARSHDB;
GO

-- Drop tables if they exist (reverse order for dependencies)
IF OBJECT_ID('[WEBSITE_CON_MAILID]', 'U') IS NOT NULL DROP TABLE [WEBSITE_CON_MAILID];
GO
IF OBJECT_ID('[USER_PROFILEHIST]', 'U') IS NOT NULL DROP TABLE [USER_PROFILEHIST];
GO
IF OBJECT_ID('[USER_POLICY]', 'U') IS NOT NULL DROP TABLE [USER_POLICY];
GO

-- ==========================================
-- Table: USER_POLICY - User Policy Management
-- Description: User policies including permissions, restrictions and settings
-- ==========================================
CREATE TABLE [USER_POLICY] (
    [POLICY_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [USER_SYSID] BIGINT NOT NULL UNIQUE,
    [POLICY_CODE] VARCHAR(50) NOT NULL,
    [POLICY_TYPE] VARCHAR(100), -- SECURITY, NOTIFICATION, PREFERENCES, etc.
    [DATA_RETENTION_DAYS] INT,
    [SESSION_TIMEOUT_MINS] INT,
    [MAX_LOGIN_ATTEMPTS] INT,
    [POLICY_STATUS] CHAR(1) DEFAULT 'A', -- A=Active, I=Inactive
    [EFFECTIVE_FROM] DATE NOT NULL,
    [EFFECTIVE_TO] DATE,
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [UPDATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3)
);
GO

-- ==========================================
-- Table: USER_PROFILEHIST - User Profile History
-- Description: Audit history of user profile changes
-- Relationship: References USER_POLICY
-- ==========================================
CREATE TABLE [USER_PROFILEHIST] (
    [HIST_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [POLICY_ID] BIGINT NOT NULL,
    [USER_SYSID] BIGINT NOT NULL,
    [PROFILE_FIELD] VARCHAR(100),
    [OLD_VALUE] NVARCHAR(500),
    [NEW_VALUE] NVARCHAR(500),
    [CHAR_REASON] VARCHAR(500),
    [CHANGED_BY] BIGINT NOT NULL,
    [CHANGED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    CONSTRAINT [FK_USER_PROFILEHIST_POLICY] FOREIGN KEY ([POLICY_ID]) REFERENCES [USER_POLICY]([POLICY_ID])
);
GO

-- ==========================================
-- Table: WEBSITE_CON_MAILID - Website Contact Email
-- Description: Website contact and email information for users
-- ==========================================
CREATE TABLE [WEBSITE_CON_MAILID] (
    [CONTACT_ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [USER_SYSID] BIGINT NOT NULL,
    [PRIMARY_EMAIL] VARCHAR(255) NOT NULL,
    [SECONDARY_EMAIL] VARCHAR(255),
    [PHONE] VARCHAR(20),
    [MOBILE] VARCHAR(20),
    [WEBSITE] VARCHAR(255),
    [SOCIAL_MEDIA] VARCHAR(500),
    [NEWSLETTER_OPT_IN] CHAR(1) DEFAULT 'Y',
    [CONTACT_STATUS] CHAR(1) DEFAULT 'A', -- A=Active, I=Inactive
    [CREATED_BY] BIGINT NOT NULL,
    [CREATED_ON] DATETIME2(3) NOT NULL DEFAULT GETDATE(),
    [UPDATED_BY] BIGINT,
    [UPDATED_ON] DATETIME2(3)
);
GO

-- Create Indexes
CREATE INDEX [IX_USER_POLICY_USER_SYSID] ON [USER_POLICY]([USER_SYSID]);
CREATE INDEX [IX_USER_POLICY_STATUS] ON [USER_POLICY]([POLICY_STATUS]);
CREATE INDEX [IX_USER_POLICY_TYPE] ON [USER_POLICY]([POLICY_TYPE]);
CREATE INDEX [IX_USER_PROFILEHIST_POLICY_ID] ON [USER_PROFILEHIST]([POLICY_ID]);
CREATE INDEX [IX_USER_PROFILEHIST_USER_SYSID] ON [USER_PROFILEHIST]([USER_SYSID]);
CREATE INDEX [IX_USER_PROFILEHIST_DATE] ON [USER_PROFILEHIST]([CHANGED_ON]);
CREATE INDEX [IX_WEBSITE_CON_MAILID_USER_SYSID] ON [WEBSITE_CON_MAILID]([USER_SYSID]);
CREATE INDEX [IX_WEBSITE_CON_MAILID_EMAIL] ON [WEBSITE_CON_MAILID]([PRIMARY_EMAIL]);
CREATE INDEX [IX_WEBSITE_CON_MAILID_STATUS] ON [WEBSITE_CON_MAILID]([CONTACT_STATUS]);
GO

PRINT 'UserManagementModule_Schema created successfully.';
GO
