<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ApiGateway</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ocelot" Version="23.4.3" />
    <PackageReference Include="Ocelot.Cache.CacheManager" Version="23.4.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.13" />
    <PackageReference Include="Polly" Version="8.5.2" />
    <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
    <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" Version="8.0.1" />
  </ItemGroup>

</Project>
