-- Module: Compensation
USE DDDB;
GO

-- Table: SAA_BUDGET
CREATE TABLE [SAA_BUDGET] (
    [BUDGET_ID] DECIMAL(38) NOT NULL  -- Budget ID,
    [BUSINESS_ID] DECIMAL(38) NOT NULL  -- Business ID,
    [YEAR_ID] DECIMAL(38) NOT NULL  -- Year,
    [BUDGET_AMOUNT] DECIMAL(38) NOT NULL  -- Budget Amount,
    [UPDATED_BY] DECIMAL(38) NOT NULL  -- Updated By,
    [UPDATED_ON] DATETIME2(3) NOT NULL  -- Updated On,
    CONSTRAINT [PK_SAA_BUDGET] PRIMARY KEY ([BUDGET_ID])
);



-- Table: SAA_BUDGETLOG
CREATE TABLE [SAA_BUDGETLOG] (
    [LOGID] DECIMAL(38) NOT NULL  -- Budget Log Id,
    [BUDGETID] DECIMAL(38) NOT NULL  -- Budget Id,
    [BUDGET_AMOUNT] DECIMAL(38) NOT NULL  -- Budget Amount,
    [UPDATED_BY] DECIMAL(38) NOT NULL  -- Updated By,
    [UPDATED_ON] DATETIME2(3) NOT NULL  -- Updated On,
    [MOD_BY] DECIMAL(38) NOT NULL  -- Modified By,
    [MOD_ON] DATETIME2(3) NOT NULL  -- Modified On,
    CONSTRAINT [PK_SAA_BUDGETLOG] PRIMARY KEY ([LOGID])
);



-- Table: SAA_GRADE
CREATE TABLE [SAA_GRADE] (
    [GRADEID] DECIMAL(38) NOT NULL,
    CONSTRAINT [PK_SAA_GRADE] PRIMARY KEY ([GRADEID])
);



-- Table: SAA_LEVEL
CREATE TABLE [SAA_LEVEL] (
    [LEVEL_ID] DECIMAL(38) NOT NULL  -- Level Id,
    [LEVEL_DESC] VARCHAR(10) NOT NULL  -- Level Description,
    [LEVEL_AMOUNT] VARCHAR(100) NOT NULL  -- Level Amount,
    [LEVEL_REASON] VARCHAR(100) NOT NULL  -- Level Reason,
    [LEVEL_MIN] DECIMAL(38) NOT NULL  -- Level Min,
    [LEVEL_MAX] DECIMAL(38) NOT NULL  -- Level Max,
    [LEVEL_EFFDATE] DATETIME2(3) NOT NULL  -- Level Effective Date,
    [LEVEL_CLOSEDATE] DATETIME2(3) NULL  -- Level Close Date,
    [LEVEL_UPDATEDBY] DECIMAL(38) NOT NULL  -- Updated By,
    [LEVEL_UPDATEDON] DATETIME2(3) NOT NULL  -- Updated On,
    CONSTRAINT [PK_SAA_LEVEL] PRIMARY KEY ([LEVEL_ID])
);



-- Table: SAA_MAILTRIGGER
CREATE TABLE [SAA_MAILTRIGGER] (
    [MT_ID] DECIMAL(38) NOT NULL  -- Auto Id,
    [MT_QID] DECIMAL(38) NOT NULL  -- Quarter Id,
    [MT_SYSID] DECIMAL(38) NOT NULL  -- Employee System Id,
    [MT_MAILID] VARCHAR(200) NOT NULL  -- Mail Id,
    [MT_TRIGGEREDBY] DECIMAL(38) NOT NULL  -- Triggered By,
    [MT_TRIGGEREDON] DATETIME2(3) NOT NULL  -- Triggered On,
    CONSTRAINT [PK_SAA_MAILTRIGGER] PRIMARY KEY ([MT_ID])
);



-- Table: SAA_PERIOD
CREATE TABLE [SAA_PERIOD] (
    [PERIOD_ID] DECIMAL(38) NOT NULL  -- Period ID,
    [YEAR_ID] DECIMAL(38) NOT NULL  -- Year,
    [QUARTER_NO] DECIMAL(38) NOT NULL  -- Quarter No,
    [STATUS] CHAR(1) NOT NULL  -- Status [Open ; Circular Generated ; Confirmed to Payroll],
    [PERIOD_OPENDATE] DATETIME2(3) NOT NULL  -- Period Open Date,
    [PERIOD_CLOSEDATE] DATETIME2(3) NOT NULL  -- Period Close Date,
    [CIRCULAR_GENON] DATETIME2(3) NULL  -- Circular Genereted On,
    [CIRCULAR_GENBY] DECIMAL(38) NULL  -- Circular Genereted By,
    [REMINDER_LETON] DATETIME2(3) NULL  -- Reminder Letter on,
    [FORM_OPENDATE] DATETIME2(3) NOT NULL  -- Form Open Date,
    [APRAISER_LASTDATE] DATETIME2(3) NULL  -- Last Date for Appraiser Entry,
    [REVIEWER_LASTDATE] DATETIME2(3) NULL  -- Last Date for Reviewer Entry,
    [BHR_LASTDATE] DATETIME2(3) NULL  -- Last Date for BHR Entry,
    [UHR_LASTDATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_SAA_PERIOD] PRIMARY KEY ([PERIOD_ID])
);



-- Table: SAA_RECOMMEND
CREATE TABLE [SAA_RECOMMEND] (
    [RECOMMEND_ID] DECIMAL(38) NOT NULL  -- Recommendation ID,
    [YEAR_ID] DECIMAL(38) NOT NULL  -- Year ID,
    [PERIOD_ID] DECIMAL(38) NOT NULL  -- Quarter ID,
    [EMP_SYSID] DECIMAL(38) NOT NULL  -- Employee System ID,
    [LEVEL_ID] DECIMAL(38) NOT NULL  -- Level,
    [CTC_AMOUNT] DECIMAL(38) NOT NULL  -- CTC Amount,
    [MAXIMUM_CAP] DECIMAL(38) NOT NULL  -- Maximum Cap,
    [ELIGIBILITY_AMOUNT] DECIMAL(38) NOT NULL  -- Eligibility Amount,
    [RECOMMEND_AMOUNT] DECIMAL(38) NULL  -- Recommended Amount,
    [INITIATIVE_TAKEN] VARCHAR(2000) NOT NULL  -- Initiative Taken,
    [RESULTS] VARCHAR(2000) NOT NULL  -- Results,
    [ADD_REMARKS] VARCHAR(1000) NULL  -- Additional Remarks,
    [STATUS] DECIMAL(38) NOT NULL  -- Status,
    [REJECTION_BY] DECIMAL(38) NULL  -- Rejected BY,
    [REJECTION_ON] DATETIME2(3) NULL  -- Rejection On,
    [RECOMMEND_BY] CHAR(3) NOT NULL  -- Recommended by (APR/REV/BHR/CHR),
    [RECOMMEND_SUBMITBY] DECIMAL(38) NULL  -- Recommended User Employee System ID,
    [RECOMMEND_SUBMITON] DATETIME2(3) NULL  -- Recommended User Submitted On,
    [REVIEWER_SUBMITBY] DECIMAL(38) NULL  -- Reviewer Employee System ID,
    [REVIEWER_SUBMITON] DATETIME2(3) NULL  -- Reviewer Submitted On,
    [BHR_SUBMITBY] DECIMAL(38) NULL  -- BHR Employee System ID,
    [BHR_SUBMITON] DATETIME2(3) NULL  -- BHR Submitted On,
    [CHR_SUBMITBY] DECIMAL(38) NULL  -- CHR Employee System ID,
    [CHR_SUBMITON] DATETIME2(3) NULL  -- CHR Submitted On,
    [REJECTION_REMARKS] VARCHAR(1000) NULL,
    [FINAL_LEVEL] DECIMAL(38) NULL,
    [FINAL_AMOUNT] DECIMAL(38) NULL,
    [INITIATIVE_LETTER] VARCHAR(2000) NULL,
    [RESULTS_LETTER] VARCHAR(2000) NULL,
    [UHR_SUBMITBY] DECIMAL(38) NULL,
    [UHR_SUBMITON] DATETIME2(3) NULL,
    [RECOMMEND_SIGNID] DECIMAL(38) NULL,
    [RECOMMEND_SIGNID2] DECIMAL(38) NULL,
    CONSTRAINT [PK_SAA_RECOMMEND] PRIMARY KEY ([RECOMMEND_ID])
);



-- Table: SAA_RECOMMEND1
CREATE TABLE [SAA_RECOMMEND1] (
    [RECOMMEND_ID] DECIMAL(38) NOT NULL,
    [YEAR_ID] DECIMAL(38) NOT NULL,
    [PERIOD_ID] DECIMAL(38) NOT NULL,
    [EMP_SYSID] DECIMAL(38) NOT NULL,
    [LEVEL_ID] DECIMAL(38) NOT NULL,
    [CTC_AMOUNT] DECIMAL(38) NOT NULL,
    [MAXIMUM_CAP] DECIMAL(38) NOT NULL,
    [ELIGIBILITY_AMOUNT] DECIMAL(38) NOT NULL,
    [RECOMMEND_AMOUNT] DECIMAL(38) NOT NULL,
    [INITIATIVE_TAKEN] VARCHAR(2000) NOT NULL,
    [RESULTS] VARCHAR(2000) NOT NULL,
    [ADD_REMARKS] VARCHAR(1000) NULL,
    [STATUS] DECIMAL(38) NOT NULL,
    [REJECTION_BY] DECIMAL(38) NULL,
    [REJECTION_ON] DATETIME2(3) NULL,
    [RECOMMEND_BY] CHAR(3) NOT NULL,
    [RECOMMEND_SUBMITBY] DECIMAL(38) NULL,
    [RECOMMEND_SUBMITON] DATETIME2(3) NULL,
    [REVIEWER_SUBMITBY] DECIMAL(38) NULL,
    [REVIEWER_SUBMITON] DATETIME2(3) NULL,
    [BHR_SUBMITBY] DECIMAL(38) NULL,
    [BHR_SUBMITON] DATETIME2(3) NULL,
    [CHR_SUBMITBY] DECIMAL(38) NULL,
    [CHR_SUBMITON] DATETIME2(3) NULL,
    [REJECTION_REMARKS] VARCHAR(1000) NULL,
    [FINAL_LEVEL] DECIMAL(38) NULL,
    [FINAL_AMOUNT] DECIMAL(38) NULL,
    [INITIATIVE_LETTER] VARCHAR(2000) NULL,
    [RESULTS_LETTER] VARCHAR(2000) NULL,
    [UHR_SUBMITBY] DECIMAL(38) NULL,
    [UHR_SUBMITON] DATETIME2(3) NULL,
    [RECOMMEND_SIGNID] DECIMAL(38) NULL
);



-- Table: SAA_RECOMMENDDEL
CREATE TABLE [SAA_RECOMMENDDEL] (
    [RECOMMEND_ID] DECIMAL(38) NOT NULL,
    [YEAR_ID] DECIMAL(38) NOT NULL,
    [PERIOD_ID] DECIMAL(38) NOT NULL,
    [EMP_SYSID] DECIMAL(38) NOT NULL,
    [LEVEL_ID] DECIMAL(38) NOT NULL,
    [CTC_AMOUNT] DECIMAL(38) NOT NULL,
    [MAXIMUM_CAP] DECIMAL(38) NOT NULL,
    [ELIGIBILITY_AMOUNT] DECIMAL(38) NOT NULL,
    [RECOMMEND_AMOUNT] DECIMAL(38) NULL,
    [INITIATIVE_TAKEN] VARCHAR(2000) NOT NULL,
    [RESULTS] VARCHAR(2000) NOT NULL,
    [ADD_REMARKS] VARCHAR(1000) NULL,
    [STATUS] DECIMAL(38) NOT NULL,
    [REJECTION_BY] DECIMAL(38) NULL,
    [REJECTION_ON] DATETIME2(3) NULL,
    [RECOMMEND_BY] CHAR(3) NOT NULL,
    [RECOMMEND_SUBMITBY] DECIMAL(38) NULL,
    [RECOMMEND_SUBMITON] DATETIME2(3) NULL,
    [REVIEWER_SUBMITBY] DECIMAL(38) NULL,
    [REVIEWER_SUBMITON] DATETIME2(3) NULL,
    [BHR_SUBMITBY] DECIMAL(38) NULL,
    [BHR_SUBMITON] DATETIME2(3) NULL,
    [CHR_SUBMITBY] DECIMAL(38) NULL,
    [CHR_SUBMITON] DATETIME2(3) NULL,
    [REJECTION_REMARKS] VARCHAR(1000) NULL,
    [FINAL_LEVEL] DECIMAL(38) NULL,
    [FINAL_AMOUNT] DECIMAL(38) NULL,
    [INITIATIVE_LETTER] VARCHAR(2000) NULL,
    [RESULTS_LETTER] VARCHAR(2000) NULL,
    [UHR_SUBMITBY] DECIMAL(38) NULL,
    [UHR_SUBMITON] DATETIME2(3) NULL,
    [RECOMMEND_SIGNID] DECIMAL(38) NULL,
    [DELETE_INITIATEDBY] DECIMAL(38) NULL,
    [DELETE_ON] DATETIME2(3) NULL
);



-- Table: SAA_RECOMMENDLOG
CREATE TABLE [SAA_RECOMMENDLOG] (
    [LOG_ID] DECIMAL(38) NOT NULL  -- Log ID,
    [RECOMMEND_ID] DECIMAL(38) NOT NULL  -- Recommendation ID,
    [LEVEL_ID] DECIMAL(38) NOT NULL  -- Level,
    [CTC_AMOUNT] DECIMAL(38) NOT NULL  -- CTC Amount,
    [MAXIMUM_CAP] DECIMAL(38) NOT NULL  -- Maximum Cap,
    [ELIGIBILITY_AMOUNT] DECIMAL(38) NOT NULL  -- Eligibility Amount,
    [RECOMMEND_AMOUNT] DECIMAL(38) NULL  -- Recommended Amount,
    [INITIATIVE_TAKEN] VARCHAR(2000) NOT NULL  -- Initiative Taken,
    [RESULTS] VARCHAR(2000) NOT NULL  -- Results,
    [REMARKS] VARCHAR(1000) NULL  -- Remarks if any,
    [REJECTION_BY] DECIMAL(38) NULL  -- Rejection By,
    [REJECTION_ON] DATETIME2(3) NULL  -- Rejection On,
    [REJECTION_REMARKS] VARCHAR(1000) NULL  -- Rejection Remarks,
    [UPDATED_BY] DECIMAL(38) NOT NULL  -- Updated By,
    [UPDATED_ON] DATETIME2(3) NOT NULL  -- Updated On,
    CONSTRAINT [PK_SAA_RECOMMENDLOG] PRIMARY KEY ([LOG_ID])
);



-- Table: SAA_RECOMMENDPAY
CREATE TABLE [SAA_RECOMMENDPAY] (
    [RECOMMEND_ID] DECIMAL(38) NOT NULL,
    [YEAR_ID] DECIMAL(38) NOT NULL,
    [PERIOD_ID] DECIMAL(38) NOT NULL,
    [EMP_SYSID] DECIMAL(38) NOT NULL,
    [LEVEL_ID] DECIMAL(38) NOT NULL,
    [CTC_AMOUNT] DECIMAL(38) NOT NULL,
    [MAXIMUM_CAP] DECIMAL(38) NOT NULL,
    [ELIGIBILITY_AMOUNT] DECIMAL(38) NOT NULL,
    [RECOMMEND_AMOUNT] DECIMAL(38) NULL,
    [INITIATIVE_TAKEN] VARCHAR(2000) NOT NULL,
    [RESULTS] VARCHAR(2000) NOT NULL,
    [ADD_REMARKS] VARCHAR(1000) NULL,
    [STATUS] DECIMAL(38) NOT NULL,
    [REJECTION_BY] DECIMAL(38) NULL,
    [REJECTION_ON] DATETIME2(3) NULL,
    [RECOMMEND_BY] CHAR(3) NOT NULL,
    [RECOMMEND_SUBMITBY] DECIMAL(38) NULL,
    [RECOMMEND_SUBMITON] DATETIME2(3) NULL,
    [REVIEWER_SUBMITBY] DECIMAL(38) NULL,
    [REVIEWER_SUBMITON] DATETIME2(3) NULL,
    [BHR_SUBMITBY] DECIMAL(38) NULL,
    [BHR_SUBMITON] DATETIME2(3) NULL,
    [CHR_SUBMITBY] DECIMAL(38) NULL,
    [CHR_SUBMITON] DATETIME2(3) NULL,
    [REJECTION_REMARKS] VARCHAR(1000) NULL,
    [FINAL_LEVEL] DECIMAL(38) NULL,
    [FINAL_AMOUNT] DECIMAL(38) NULL,
    [INITIATIVE_LETTER] VARCHAR(2000) NULL,
    [RESULTS_LETTER] VARCHAR(2000) NULL,
    [UHR_SUBMITBY] DECIMAL(38) NULL,
    [UHR_SUBMITON] DATETIME2(3) NULL,
    [RECOMMEND_SIGNID] DECIMAL(38) NULL
);



-- Table: SAA_RECOMMEND_71
CREATE TABLE [SAA_RECOMMEND_71] (
    [RECOMMEND_ID] DECIMAL(38) NOT NULL,
    [YEAR_ID] DECIMAL(38) NOT NULL,
    [PERIOD_ID] DECIMAL(38) NOT NULL,
    [EMP_SYSID] DECIMAL(38) NOT NULL,
    [LEVEL_ID] DECIMAL(38) NOT NULL,
    [CTC_AMOUNT] DECIMAL(38) NOT NULL,
    [MAXIMUM_CAP] DECIMAL(38) NOT NULL,
    [ELIGIBILITY_AMOUNT] DECIMAL(38) NOT NULL,
    [RECOMMEND_AMOUNT] DECIMAL(38) NULL,
    [INITIATIVE_TAKEN] VARCHAR(2000) NOT NULL,
    [RESULTS] VARCHAR(2000) NOT NULL,
    [ADD_REMARKS] VARCHAR(1000) NULL,
    [STATUS] DECIMAL(38) NOT NULL,
    [REJECTION_BY] DECIMAL(38) NULL,
    [REJECTION_ON] DATETIME2(3) NULL,
    [RECOMMEND_BY] CHAR(3) NOT NULL,
    [RECOMMEND_SUBMITBY] DECIMAL(38) NULL,
    [RECOMMEND_SUBMITON] DATETIME2(3) NULL,
    [REVIEWER_SUBMITBY] DECIMAL(38) NULL,
    [REVIEWER_SUBMITON] DATETIME2(3) NULL,
    [BHR_SUBMITBY] DECIMAL(38) NULL,
    [BHR_SUBMITON] DATETIME2(3) NULL,
    [CHR_SUBMITBY] DECIMAL(38) NULL,
    [CHR_SUBMITON] DATETIME2(3) NULL,
    [REJECTION_REMARKS] VARCHAR(1000) NULL,
    [FINAL_LEVEL] DECIMAL(38) NULL,
    [FINAL_AMOUNT] DECIMAL(38) NULL,
    [INITIATIVE_LETTER] VARCHAR(2000) NULL,
    [RESULTS_LETTER] VARCHAR(2000) NULL,
    [UHR_SUBMITBY] DECIMAL(38) NULL,
    [UHR_SUBMITON] DATETIME2(3) NULL,
    [RECOMMEND_SIGNID] DECIMAL(38) NULL
);



-- Table: SAA_SUBMIT
CREATE TABLE [SAA_SUBMIT] (
    [SUBID] DECIMAL(38) NOT NULL,
    [PERIOD_ID] DECIMAL(38) NOT NULL,
    [BUS_ID] DECIMAL(38) NOT NULL,
    [BHR_FLAG] CHAR(1) NOT NULL,
    [CHR_FLAG] CHAR(1) NOT NULL,
    [BHR_UPDBY] DECIMAL(38) NOT NULL,
    [BHR_UPDON] DATETIME2(3) NOT NULL,
    [BHR_AMOUNT] DECIMAL(38) NULL,
    [CHR_UPDBY] DECIMAL(38) NULL,
    [CHR_UPDON] DATETIME2(3) NULL,
    [CHR_AMOUNT] DECIMAL(38) NULL,
    CONSTRAINT [PK_SAA_SUBMIT] PRIMARY KEY ([SUBID])
);



-- Table: SAA_UHR
CREATE TABLE [SAA_UHR] (
    [UNITID] DECIMAL(38) NOT NULL
);

