-- ==========================================
-- Module: UNIT MANAGEMENT
-- Database: TASKDB
-- Purpose: Unit & Equipment Management
-- Tables for managing equipment, status, budgets, mail, and access
-- ==========================================

USE [TASKDB];
GO

-- ==========================================
-- UNIT MANAGEMENT TABLES
-- ==========================================

-- Table: UM_EQUIPMENT_MASTER
-- Purpose: Master list of all equipment/assets
CREATE TABLE [UM_EQUIPMENT_MASTER] (
    [EM_EQUIPMENT_ID] INT NOT NULL,
    [EM_EQUIPMENT_NAME] VARCHAR(65) NOT NULL,
    [EM_UNIT_CODE] CHAR(3) NOT NULL,
    [EM_CATEGORY] VARCHAR(25) NOT NULL,
    [EM_START_DATE] DATETIME2(3) NOT NULL,
    [EM_CLOSE_DATE] DATETIME2(3) NULL,
    [EM_LAST_MODIFIEDBY] INT NOT NULL,
    [EM_LAST_MODIFIEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_UM_EQUIPMENT_MASTER] PRIMARY KEY ([EM_EQUIPMENT_ID])
);

-- Table: UM_CATEGORY_MASTER
-- Purpose: Equipment category master
CREATE TABLE [UM_CATEGORY_MASTER] (
    [UNIT_CODE] CHAR(3) NOT NULL,
    [CATEGORY_ID] DECIMAL(38) NOT NULL,
    [CATEGORY_NAME] VARCHAR(65) NOT NULL,
    [LAST_MODIFIEDBY] INT NULL,
    [LAST_MODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_UM_CATEGORY_MASTER] PRIMARY KEY ([UNIT_CODE])
);

-- Table: UM_EQUIP_STATUS
-- Purpose: Equipment status history and tracking
CREATE TABLE [UM_EQUIP_STATUS] (
    [ES_ID] INT NOT NULL,
    [ES_EQUIPMENT_ID] INT NOT NULL,
    [ES_STATUS_DESC] VARCHAR(65) NOT NULL,
    [ES_STATUS_ID] VARCHAR(5) NOT NULL,
    [ES_START_DATE] VARCHAR(255) NOT NULL,
    [ES_CLOSE_DATE] VARCHAR(255) NULL,
    [ES_REMARKS] VARCHAR(200) NULL,
    [ES_HOURS] BIGINT NULL,
    [ES_FILEPATH] VARCHAR(100) NULL,
    [ES_CREATED_BY] INT NULL,
    [ES_CREATED_ON] VARCHAR(255) NULL,
    [ES_LAST_MODIFIED_BY] INT NULL,
    [ES_LAST_MODIFIED_ON] DATETIME2(3) NULL,
    CONSTRAINT [PK_UM_EQUIP_STATUS] PRIMARY KEY ([ES_ID])
);

-- Table: UM_ACCESS_MASTER
-- Purpose: User access control to units
CREATE TABLE [UM_ACCESS_MASTER] (
    [UA_ID] INT NOT NULL,
    [UA_UNIT_CODE] CHAR(3) NOT NULL,
    [UA_EMP_SYSID] INT NOT NULL,
    [UA_ACCESS_TYPE] CHAR(1) NOT NULL,
    [UA_START_DATE] DATETIME2(3) NOT NULL,
    [UA_CLOSE_DATE] VARCHAR(255) NULL,
    [UA_LAST_MODIFIEDBY] INT NOT NULL,
    [UA_LAST_MODIFIEDON] DATETIME2(3) NOT NULL,
    [UA_MODULE] VARCHAR(5) NOT NULL
);

-- Table: UM_BUDGET_MASTER
-- Purpose: Equipment budget tracking
CREATE TABLE [UM_BUDGET_MASTER] (
    [BM_UNIT_CODE] CHAR(3) NOT NULL,
    [BM_EQUIPMENT_ID] DECIMAL(38) NOT NULL,
    [BM_START_DATE] DATETIME2(3) NOT NULL,
    [BM_CLOSE_DATE] DATETIME2(3) NULL,
    [BM_LAST_MODIFIEDBY] INT NULL,
    [BM_LAST_MODIFIEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_UM_BUDGET_MASTER] PRIMARY KEY ([BM_UNIT_CODE])
);

-- Table: UM_MAILID_MASTER
-- Purpose: Email contact list for unit notifications
CREATE TABLE [UM_MAILID_MASTER] (
    [MM_ID] INT NOT NULL,
    [MM_UNIT_CODE] CHAR(3) NOT NULL,
    [MM_MAIL_ID] VARCHAR(65) NOT NULL,
    [MM_DELIVERY_TYPE] VARCHAR(3) NOT NULL,
    [MM_START_DATE] VARCHAR(255) NOT NULL,
    [MM_CLOSE_DATE] VARCHAR(255) NULL,
    [MM_LAST_MODIFIEDBY] INT NOT NULL,
    [MM_LAST_MODIFIEDON] VARCHAR(30) NOT NULL,
    [MM_MODULE] VARCHAR(5) NOT NULL,
    CONSTRAINT [PK_UM_MAILID_MASTER] PRIMARY KEY ([MM_ID])
);

-- Table: UM_STATUS_CONFIRM
-- Purpose: Unit status confirmation log
CREATE TABLE [UM_STATUS_CONFIRM] (
    [STATUS_UNIT_CODE] CHAR(3) NOT NULL,
    [STATUS_DATE] DATETIME2(3) NOT NULL,
    [STATUS_CONFIRM_BY] DECIMAL(38) NOT NULL,
    [STATUS_CONFIRM_ON] DATETIME2(3) NOT NULL
);

-- ==========================================
-- END OF SCRIPT - UNIT MODULE TABLES
-- ==========================================
