## RabbitMQ Configuration
loopback_users.guest = false
management.load_definitions = /etc/rabbitmq/definitions.json

## Listeners
listeners.tcp.default = 5672

## Management
management.tcp.port = 15672

## Limits
vm_memory_high_watermark.relative = 0.7
disk_free_limit.absolute = 1GB

## Logging
log.console = true
log.console.level = info

## Heartbeat
heartbeat = 60
