FROM mcr.microsoft.com/dotnet/aspnet:10.0-preview AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0-preview AS build
WORKDIR /src
COPY EnergyService/src/EnergyService.Domain/EnergyService.Domain.csproj EnergyService/src/EnergyService.Domain/
COPY EnergyService/src/EnergyService.Application/EnergyService.Application.csproj EnergyService/src/EnergyService.Application/
COPY EnergyService/src/EnergyService.Infrastructure/EnergyService.Infrastructure.csproj EnergyService/src/EnergyService.Infrastructure/
COPY EnergyService/src/EnergyService.Functions/EnergyService.Functions.csproj EnergyService/src/EnergyService.Functions/
RUN dotnet restore EnergyService/src/EnergyService.Functions/EnergyService.Functions.csproj
COPY . .
WORKDIR /src/EnergyService/src/EnergyService.Functions
RUN dotnet publish -c Release -o /app/publish --no-restore

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENV DOTNET_ENVIRONMENT=Production
ENTRYPOINT ["dotnet", "EnergyService.Functions.dll"]
