-- ==========================================
-- Module: INVOICE PROCESSING MODULE
-- Description: Document management, invoice processing, approvals, and payment details
-- Created: March 9, 2026
-- Database: SSCDB
-- ==========================================

USE SSCDB;
GO

-- ==========================================
-- DOC_DET - Document Details (Main Invoice/Document Table)
-- ==========================================
IF OBJECT_ID('[DOC_DET]', 'U') IS NOT NULL DROP TABLE [DOC_DET];
GO
CREATE TABLE [DOC_DET] (
    [DOC_ID] BIGINT NOT NULL  -- Document Sequence ID,
    [DOC_ORGID] VARCHAR(25) NOT NULL  -- Org ID,
    [DOC_LOCID] INT NOT NULL  -- Location ID,
    [DOC_NO] VARCHAR(25) NULL  -- Document No Sequence by Org ID wise,
    [DOC_TYPE] CHAR(3) NOT NULL  -- PO Based / Non PO Based / Receipt Based/ Travel vendor,
    [DOC_MAINCAT] BIGINT NOT NULL  -- Main Category,
    [DOC_SUBCAT] BIGINT NOT NULL  -- Sub Category,
    [DOC_PONO] VARCHAR(25) NOT NULL  -- R12 PO No / Travel Batch No,
    [DOC_VNDSITEID] BIGINT NOT NULL  -- Vendor Site ID,
    [DOC_VNDID] BIGINT NOT NULL  -- Vendor ID,
    [DOC_DUEDAYS] INT NOT NULL  -- Due Days,
    [DOC_POID] BIGINT NOT NULL  -- R12 PO Sequence ID,
    [DOC_MRCREM] VARCHAR(200) NULL  -- MRC Remarks,
    [DOC_VATFLAG] CHAR(1) NOT NULL  -- VAT Status (Y/N),
    [DOC_INVOICENO] VARCHAR(100) NOT NULL  -- Vendor Invoice No,
    [DOC_INVAMT] BIGINT NOT NULL  -- Invoice Amount to be paid,
    [DOC_CURRENCY] INT NOT NULL  -- Currency,
    [DOC_INVDATE] DATETIME2(3) NOT NULL  -- Invoice Date,
    [DOC_INVRECDATE] DATETIME2(3) NOT NULL  -- Invoice Receipt Date,
    [DOC_PAGES] BIGINT NOT NULL  -- No of Pages,
    [DOC_REMARKS] VARCHAR(1000) NULL  -- Remarks to AP Processor,
    [DOC_DUEDATE] DATETIME2(3) NOT NULL  -- Payment Due Date,
    [DOC_PAYBY] INT NOT NULL  -- Pay By,
    [DOC_SIGNATORY1] BIGINT NULL  -- Signatory 1,
    [DOC_SIGNATORY2] BIGINT NULL  -- Signatory 2,
    [DOC_APPROVER] BIGINT NULL  -- Approver,
    [DOC_OWNER] BIGINT NOT NULL  -- Document Owner,
    [DOC_DOCSTATUS] CHAR(2) NOT NULL  -- Document Status,
    [DOC_INVSTATUS] CHAR(2) NULL  -- Invoice Status,
    [DOC_USERID] BIGINT NOT NULL  -- Created By,
    [DOC_CREATEDON] DATETIME2(3) NOT NULL  -- Created on,
    [DOC_SUBMITTEDON] DATETIME2(3) NOT NULL  -- Submitted on,
    [DOC_RECEIVEDBY] BIGINT NOT NULL  -- Received By,
    [DOC_RECEIVEDON] DATETIME2(3) NOT NULL  -- Received On,
    [DOC_CANCELFLAG] CHAR(1) NOT NULL  -- Cancel Status (Y/N),
    [DOC_CANCELUSER] BIGINT NOT NULL  -- Cancelled By,
    [DOC_CANCELDATE] DATETIME2(3) NOT NULL  -- Cancel Date,
    [DOC_APALLID] BIGINT NOT NULL  -- Current Allocation ID,
    [DOC_ORAINVNO] BIGINT NOT NULL  -- Oracle Voucher No,
    [DOC_PAYTYPENO] BIGINT NOT NULL  -- Payment type,
    [DOC_ACCOUNTCODE] VARCHAR(25) NOT NULL  -- Account Code,
    [DOC_SSCINVOICEPDF] VARCHAR(200) NULL  -- SSC Invoice File Name,
    [DOC_KEY] VARCHAR(25) NULL  -- Document Key,
    [DOC_USRINVOICEPDF] VARCHAR(200) NULL  -- User Invoice File Name,
    [DOC_FILEPATH] VARCHAR(200) NULL  -- Document File Path,
    [DOC_INVPROCDATE] DATETIME2(3) NULL  -- Invoice Processed Date,
    [DOC_INVPROCALLID] BIGINT NULL  -- Invoice Processed Allocation ID,
    [DOC_INVVALIDDATE] DATETIME2(3) NULL  -- Invoice Validation Date,
    [DOC_INVVALIDALLID] BIGINT NULL  -- Invoice Validation Allocation ID,
    [DOC_HOLDSTATUS] CHAR(1) NULL  -- Hold Status Y/N,
    [DOC_DEDUCTION] BIGINT NULL  -- Invoice Amount Cleared for Payment,
    [DOC_THIRDPARTYFLAG] CHAR(1) NULL  -- ThirdParty Vendor Status Y/N,
    [DOC_THIRDPARTYVENDOR] VARCHAR(50) NULL  -- Third party Vendor Site,
    [DOC_DEDUCTIONREMARKS] VARCHAR(1000) NULL  -- Deduction Remarks,
    [DOC_FILEID] BIGINT NULL  -- File id,
    [DOC_CANCELREMARKS] VARCHAR(200) NULL,
    [DOC_HOLDPAYMENTFLAG] CHAR(1) NULL,
    [DOC_HOLDPAYMENTREMARKS] VARCHAR(200) NULL,
    [DOC_HOLDRELEASEREMARKS] VARCHAR(200) NULL,
    [DOC_SCANFLAG] CHAR(1) NULL  -- L - Local S - SSC,
    [DOC_APPROVEDBY] BIGINT NULL,
    CONSTRAINT [PK_DOC_DET] PRIMARY KEY ([DOC_ID])
);
GO

-- ==========================================
-- DOC_ORACLEINVDET - Oracle Invoice Details
-- ==========================================
IF OBJECT_ID('[DOC_ORACLEINVDET]', 'U') IS NOT NULL DROP TABLE [DOC_ORACLEINVDET];
GO
CREATE TABLE [DOC_ORACLEINVDET] (
    [DOC_INVID] BIGINT NOT NULL,
    [DOC_ID] BIGINT NOT NULL,
    [DOC_VOUCHERNO] DECIMAL(38) NULL,
    [DOC_INVOICETYPE] VARCHAR(25) NULL,
    [DOC_VENDORID] BIGINT NULL,
    [DOC_VENDOR_SITEID] BIGINT NULL,
    [DOC_INVOICENUM] VARCHAR(50) NULL,
    [DOC_INVOICEDATE] DATETIME2(3) NULL,
    [DOC_INVOICEAMOUNT] DECIMAL(38) NULL,
    [DOC_INVOICEID] BIGINT NOT NULL,
    [DOC_INVOICESTATUS] VARCHAR(4000) NULL,
    [DOC_INVOICECREATEDON] DATETIME2(3) NULL,
    [DOC_INVOICECREATEDBY] DECIMAL(38) NULL,
    [DOC_PAYMENT_METHOD_CODE] VARCHAR(30) NULL,
    [DOC_ACCOUNTING_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_DOC_ORACLEINVDET] PRIMARY KEY ([DOC_INVID])
);
GO

-- ==========================================
-- DOC_ORACLEPAYDET - Oracle Payment Details
-- ==========================================
IF OBJECT_ID('[DOC_ORACLEPAYDET]', 'U') IS NOT NULL DROP TABLE [DOC_ORACLEPAYDET];
GO
CREATE TABLE [DOC_ORACLEPAYDET] (
    [DOC_PAYID] BIGINT NOT NULL,
    [DOC_ID] BIGINT NOT NULL,
    [DOC_PAYMENTNUM] BIGINT NOT NULL,
    [DOC_INVOICEID] BIGINT NOT NULL,
    [DOC_DUEDATE] DATETIME2(3) NULL,
    [DOC_GROSSAMOUNT] DECIMAL(38) NULL,
    [DOC_AMOUNTREMAINING] DECIMAL(38) NULL,
    [DOC_PAYMENT_STATUS] VARCHAR(14) NULL,
    [DOC_PAYMENT_METHOD] VARCHAR(30) NULL,
    [DOC_PREPAYMENT_APPLIED] VARCHAR(3) NULL,
    [DOC_PAYMENT_CREATEDBY] DECIMAL(38) NULL,
    [DOC_PAYMENT_CREATEDON] DATETIME2(3) NULL,
    [CHECK_ID] BIGINT NULL,
    [BNKSTATUS] CHAR(1) NULL,
    [CHECK_NUMBER] BIGINT NULL,
    [CHECK_DATE] DATETIME2(3) NULL,
    [CHECK_AMOUNT] DECIMAL(38) NULL,
    CONSTRAINT [PK_DOC_ORACLEPAYDET] PRIMARY KEY ([DOC_PAYID])
);
GO

-- ==========================================
-- DOC_ORACLEBNKDET - Oracle Bank Details
-- ==========================================
IF OBJECT_ID('[DOC_ORACLEBNKDET]', 'U') IS NOT NULL DROP TABLE [DOC_ORACLEBNKDET];
GO
CREATE TABLE [DOC_ORACLEBNKDET] (
    [DOC_BNKID] BIGINT NOT NULL,
    [DOC_ID] BIGINT NOT NULL,
    [TYPE] VARCHAR(255) NULL,
    [CHECK_ID] VARCHAR(255) NOT NULL,
    [BUSINESS] VARCHAR(255) NULL,
    [ORG_ID] VARCHAR(255) NULL,
    [VENDOR_SITE_ID] VARCHAR(255) NULL,
    [FILE_NAME] VARCHAR(255) NULL,
    [RECORD_IDETIFIER] VARCHAR(255) NULL,
    [TRANSACTION_TYPE] VARCHAR(255) NULL,
    [VENDOR_CODE] VARCHAR(255) NULL,
    [MAIL_TO] VARCHAR(255) NULL,
    [BENE_MAIL_ADDRESS] VARCHAR(255) NULL,
    [BENE_BANK_AC] VARCHAR(255) NULL,
    [PAY_TO] VARCHAR(255) NULL,
    [CHECK_DATE] VARCHAR(255) NULL,
    [AMOUNT] VARCHAR(255) NULL,
    [HUNDI] VARCHAR(255) NULL,
    [CURRENCY] VARCHAR(255) NULL,
    [PAYMENT_LOCATION] VARCHAR(255) NULL,
    [PAYMENT_NUMBER] VARCHAR(255) NULL,
    [CHECK_NUMBER] VARCHAR(255) NULL,
    [PAYMENT_DATE] VARCHAR(255) NULL,
    [RECORS_ANNEXURE] VARCHAR(255) NULL,
    [PRINT_LOCATION] VARCHAR(255) NULL,
    [BENE_IFSC] VARCHAR(255) NULL,
    [BENE_ACCOUNT_TYPE] VARCHAR(255) NULL,
    [BENE_BANK_NAME] VARCHAR(255) NULL,
    [BENE_BANK_AC22] VARCHAR(255) NULL,
    [BENE_BANK_BRANCH] VARCHAR(255) NULL,
    [BENE_BANK_LOCATION] VARCHAR(255) NULL,
    [BENE_MAIL_ID] VARCHAR(255) NULL,
    [REF_NO] VARCHAR(255) NULL,
    [UTR_NO] VARCHAR(255) NULL,
    [REJECT_REASON1] VARCHAR(255) NULL,
    [REJECT_REASON2] VARCHAR(255) NULL,
    [STATUS_LOOKUP_CODE] VARCHAR(25) NULL,
    CONSTRAINT [PK_DOC_ORACLEBNKDET] PRIMARY KEY ([DOC_BNKID])
);
GO

-- ==========================================
-- DOC_POLIST - Document PO List
-- ==========================================
IF OBJECT_ID('[DOC_POLIST]', 'U') IS NOT NULL DROP TABLE [DOC_POLIST];
GO
CREATE TABLE [DOC_POLIST] (
    [PO_SEQID] BIGINT NOT NULL,
    [PO_DOCID] BIGINT NOT NULL,
    [PO_ID] BIGINT NOT NULL,
    [PO_NO] VARCHAR(15) NOT NULL,
    [PO_LINENO] VARCHAR(15) NOT NULL,
    [PO_LINE_ID] BIGINT NULL,
    [PO_DATE] DATETIME2(3) NULL,
    [PO_TERM_ID] BIGINT NULL,
    [PO_TERM_SEQNO] BIGINT NULL,
    CONSTRAINT [PK_DOC_POLIST] PRIMARY KEY ([PO_SEQID])
);
GO

-- ==========================================
-- DOC_APPDET - Document Approval Details
-- ==========================================
IF OBJECT_ID('[DOC_APPDET]', 'U') IS NOT NULL DROP TABLE [DOC_APPDET];
GO
CREATE TABLE [DOC_APPDET] (
    [APP_SEQID] BIGINT NOT NULL,
    [APP_DOCID] BIGINT NOT NULL,
    [APP_USERID] BIGINT NOT NULL,
    [APP_STATUS] CHAR(1) NOT NULL,
    [APP_REMARKS] VARCHAR(200) NULL,
    [APP_DATE] DATETIME2(3) NOT NULL
);
GO

-- ==========================================
-- DOC_MRCLIST - Document MRC List
-- ==========================================
IF OBJECT_ID('[DOC_MRCLIST]', 'U') IS NOT NULL DROP TABLE [DOC_MRCLIST];
GO
CREATE TABLE [DOC_MRCLIST] (
    [MRC_SEQID] BIGINT NOT NULL,
    [MRC_DOCID] BIGINT NOT NULL,
    [MRC_LINEID] BIGINT NOT NULL,
    [MRC_ID] BIGINT NOT NULL,
    [MRC_NO] VARCHAR(15) NOT NULL,
    [MRC_DATE] DATETIME2(3) NULL,
    [MRC_PO_LINEID] BIGINT NULL,
    CONSTRAINT [PK_DOC_MRCLIST] PRIMARY KEY ([MRC_SEQID])
);
GO

-- ==========================================
-- DOC_CC - Document Cost Center
-- ==========================================
IF OBJECT_ID('[DOC_CC]', 'U') IS NOT NULL DROP TABLE [DOC_CC];
GO
CREATE TABLE [DOC_CC] (
    [CC_ID] BIGINT NOT NULL,
    [CC_DOCID] BIGINT NOT NULL,
    [CC_BUID] VARCHAR(25) NOT NULL,
    [CC_LOCCODE] VARCHAR(25) NOT NULL,
    [CC_ACCOUNTCODE] VARCHAR(25) NOT NULL,
    [CC_SUBACC] VARCHAR(25) NOT NULL,
    [CC_CODE] VARCHAR(25) NOT NULL,
    [CC_PRODUCT] VARCHAR(25) NOT NULL,
    [CC_PER] BIGINT NOT NULL,
    CONSTRAINT [PK_DOC_CC] PRIMARY KEY ([CC_ID])
);
GO

-- ==========================================
-- DOC_ATTACHMENT - Document Attachments
-- ==========================================
IF OBJECT_ID('[DOC_ATTACHMENT]', 'U') IS NOT NULL DROP TABLE [DOC_ATTACHMENT];
GO
CREATE TABLE [DOC_ATTACHMENT] (
    [ATTACH_ID] BIGINT NOT NULL,
    [ATTACH_DOCID] BIGINT NOT NULL,
    [ATTACH_FILEPATH] VARCHAR(25) NOT NULL,
    CONSTRAINT [PK_DOC_ATTACHMENT] PRIMARY KEY ([ATTACH_ID])
);
GO

-- ==========================================
-- DOC_SSFILELIST - Document SSC File List
-- ==========================================
IF OBJECT_ID('[DOC_SSFILELIST]', 'U') IS NOT NULL DROP TABLE [DOC_SSFILELIST];
GO
CREATE TABLE [DOC_SSFILELIST] (
    [FILE_ID] BIGINT NOT NULL,
    [FILE_DOCID] BIGINT NOT NULL,
    [FILE_PATH] VARCHAR(25) NOT NULL,
    CONSTRAINT [PK_DOC_SSFILELIST] PRIMARY KEY ([FILE_ID])
);
GO

-- ==========================================
-- DOC_APALLDET - Document AP Allocation Details
-- ==========================================
IF OBJECT_ID('[DOC_APALLDET]', 'U') IS NOT NULL DROP TABLE [DOC_APALLDET];
GO
CREATE TABLE [DOC_APALLDET] (
    [APALL_ID] BIGINT NOT NULL,
    [APALL_DOCID] BIGINT NOT NULL,
    [APALL_ACTION] CHAR(1) NOT NULL,
    [APALL_GROUPID] BIGINT NOT NULL,
    [APALL_PULLSTATUS] CHAR(1) NOT NULL,
    [APALL_PULLUSERID] BIGINT NOT NULL,
    [APALL_PRIORITY] INT NOT NULL,
    [APALL_ALLBY] BIGINT NOT NULL,
    [APALL_ALLON] DATETIME2(3) NOT NULL,
    [APALL_REMARKS] VARCHAR(200) NULL,
    [APALL_ACTIONFLAG] CHAR(1) NOT NULL,
    [APALL_ACTIONDATE] DATETIME2(3) NULL,
    [APALL_CORRID] BIGINT NULL,
    [APALL_DEFTYPE] BIGINT NULL,
    [APALL_CLOSEREMARKS] VARCHAR(200) NULL,
    [APALL_MODIFIEDBY] BIGINT NOT NULL,
    [APALL_MODIFIEDON] DATETIME2(3) NOT NULL,
    [APALL_PULLEDON] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_DOC_APALLDET] PRIMARY KEY ([APALL_ID])
);
GO

-- ==========================================
-- DOC_CORRESPOND - Document Correspondence (Holds)
-- ==========================================
IF OBJECT_ID('[DOC_CORRESPOND]', 'U') IS NOT NULL DROP TABLE [DOC_CORRESPOND];
GO
CREATE TABLE [DOC_CORRESPOND] (
    [CORR_ID] BIGINT NOT NULL,
    [CORR_DOCID] BIGINT NOT NULL,
    [CORR_ALLID] BIGINT NOT NULL,
    [CORR_HOLDCAT] BIGINT NOT NULL,
    [CORR_HOLDTYPE] BIGINT NOT NULL,
    [CORR_HOLDDATE] DATETIME2(3) NOT NULL,
    [CORR_HOLDREMARKS] VARCHAR(200) NOT NULL,
    [CORR_HOLDBY] BIGINT NOT NULL,
    [CORR_HOLDSTATUS] CHAR(1) NOT NULL,
    [CORR_RELDATE] DATETIME2(3) NULL,
    [CORR_RELREMARKS] VARCHAR(200) NULL,
    [CORR_RELBY] BIGINT NULL,
    [CORR_HOLDNATURE] DECIMAL(38) NULL,
    CONSTRAINT [PK_DOC_CORRESPOND] PRIMARY KEY ([CORR_ID])
);
GO

-- ==========================================
-- DOC_CORRESPONDATT - Document Correspondence Attachments
-- ==========================================
IF OBJECT_ID('[DOC_CORRESPONDATT]', 'U') IS NOT NULL DROP TABLE [DOC_CORRESPONDATT];
GO
CREATE TABLE [DOC_CORRESPONDATT] (
    [ATT_ID] BIGINT NOT NULL,
    [ATT_CORRID] BIGINT NOT NULL,
    [ATT_CORRSTATUS] CHAR(1) NOT NULL,
    [ATT_FILEPATH] VARCHAR(200) NOT NULL,
    CONSTRAINT [PK_DOC_CORRESPONDATT] PRIMARY KEY ([ATT_ID])
);
GO

-- ==========================================
-- DOC_DEFECTIVEATT - Document Defective Attachments
-- ==========================================
IF OBJECT_ID('[DOC_DEFECTIVEATT]', 'U') IS NOT NULL DROP TABLE [DOC_DEFECTIVEATT];
GO
CREATE TABLE [DOC_DEFECTIVEATT] (
    [DEFATT_ID] BIGINT NOT NULL,
    [DEFATT_ALLID] BIGINT NOT NULL,
    [DEFATT_FILEPATH] VARCHAR(200) NOT NULL,
    CONSTRAINT [PK_DOC_DEFECTIVEATT] PRIMARY KEY ([DEFATT_ID])
);
GO

-- ==========================================
-- DOC_STATUS - Document Status
-- ==========================================
IF OBJECT_ID('[DOC_STATUS]', 'U') IS NOT NULL DROP TABLE [DOC_STATUS];
GO
CREATE TABLE [DOC_STATUS] (
    [DOC_FLAG] CHAR(2) NOT NULL,
    [DOC_TYPE] CHAR(1) NOT NULL,
    [DOC_COMPLETEDREM] VARCHAR(100) NOT NULL,
    [DOC_PENDINGREM] VARCHAR(100) NOT NULL,
    [DOC_STAGEORDER] BIGINT NULL,
    [DOC_CATGROUP] VARCHAR(50) NULL,
    [DOC_STAGENO] BIGINT NULL,
    CONSTRAINT [PK_DOC_STATUS] PRIMARY KEY ([DOC_FLAG])
);
GO

-- ==========================================
-- DOC_RESCANDET - Document Rescan Details
-- ==========================================
IF OBJECT_ID('[DOC_RESCANDET]', 'U') IS NOT NULL DROP TABLE [DOC_RESCANDET];
GO
CREATE TABLE [DOC_RESCANDET] (
    [RESCAN_ID] BIGINT NOT NULL,
    [RESCAN_DOCID] BIGINT NOT NULL,
    [RESCAN_ALLID] BIGINT NOT NULL,
    [RESCAN_STATUS] CHAR(1) NOT NULL,
    [RESCAN_DATE] DATETIME2(3) NOT NULL,
    [RESCAN_TO] CHAR(1) NOT NULL,
    [RESCAN_REMARKS] VARCHAR(100) NOT NULL,
    [RESCAN_ON] DATETIME2(3) NULL,
    [RESCAN_BY] BIGINT NULL,
    [RESCAN_COMPLETIONREM] VARCHAR(100) NULL,
    [RESCAN_FILEPATH] VARCHAR(200) NULL,
    CONSTRAINT [PK_DOC_RESCANDET] PRIMARY KEY ([RESCAN_ID])
);
GO

-- ==========================================
-- DOC_REVOKEDET - Document Revoke Details
-- ==========================================
IF OBJECT_ID('[DOC_REVOKEDET]', 'U') IS NOT NULL DROP TABLE [DOC_REVOKEDET];
GO
CREATE TABLE [DOC_REVOKEDET] (
    [DOC_REVOKEDETID] BIGINT NOT NULL,
    [DOC_ID] BIGINT NOT NULL,
    [DOC_REVOKEREMARKS] VARCHAR(1000) NOT NULL,
    [DOC_REVOKESTATUS] CHAR(10) NOT NULL,
    [DOC_REVOKEDBY] BIGINT NOT NULL,
    [DOC_REVOKEDON] DATETIME2(3) NOT NULL
);
GO

-- ==========================================
-- DOC_APPROVER - Document Approvers
-- ==========================================
IF OBJECT_ID('[DOC_APPROVER]', 'U') IS NOT NULL DROP TABLE [DOC_APPROVER];
GO
CREATE TABLE [DOC_APPROVER] (
    [DOC_APPRID] BIGINT NOT NULL,
    [DOC_BU] VARCHAR(25) NOT NULL,
    [DOC_LOC] BIGINT NOT NULL,
    [DOC_APPRTYPE] CHAR(1) NOT NULL,
    [DOC_APPREMPID] BIGINT NOT NULL,
    [DOC_ENTBY] BIGINT NOT NULL,
    [DOC_ENTON] DATETIME2(3) NOT NULL
);
GO

-- ==========================================
-- DOC_COUNTER - Document Counter
-- ==========================================
IF OBJECT_ID('[DOC_COUNTER]', 'U') IS NOT NULL DROP TABLE [DOC_COUNTER];
GO
CREATE TABLE [DOC_COUNTER] (
    [DOC_BUID] VARCHAR(25) NOT NULL,
    [DOC_NO] BIGINT NOT NULL,
    CONSTRAINT [PK_DOC_COUNTER] PRIMARY KEY ([DOC_BUID])
);
GO

-- ==========================================
-- DOC_DUPLICATE_CHK - Duplicate Document Check
-- ==========================================
IF OBJECT_ID('[DOC_DUPLICATE_CHK]', 'U') IS NOT NULL DROP TABLE [DOC_DUPLICATE_CHK];
GO
CREATE TABLE [DOC_DUPLICATE_CHK] (
    [DOC_ID] VARCHAR(50) NULL
);
GO

-- ==========================================
-- DOC_ORACLEDUEDET - Oracle Due Details
-- ==========================================
IF OBJECT_ID('[DOC_ORACLEDUEDET]', 'U') IS NOT NULL DROP TABLE [DOC_ORACLEDUEDET];
GO
CREATE TABLE [DOC_ORACLEDUEDET] (
    [DOC_DUEID] BIGINT NOT NULL,
    [DOC_ID] BIGINT NOT NULL,
    [ORG_ID] BIGINT NULL,
    [INVOICEID] BIGINT NOT NULL,
    [VOUCHER_NO] DECIMAL(38) NULL,
    [DOCUMENT_ID] VARCHAR(150) NULL,
    [DUEDATE] DATETIME2(3) NULL,
    [PAYMENT_NUM] BIGINT NULL,
    [DUE_AMOUNT] DECIMAL(38) NULL,
    [DOC_DUECREATEDBY] DECIMAL(38) NULL,
    [DOC_DUECREATEDON] DATETIME2(3) NULL,
    CONSTRAINT [PK_DOC_ORACLEDUEDET] PRIMARY KEY ([DOC_DUEID])
);
GO

-- ==========================================
-- DOC_REPORTFIELDS - Document Report Fields
-- ==========================================
IF OBJECT_ID('[DOC_REPORTFIELDS]', 'U') IS NOT NULL DROP TABLE [DOC_REPORTFIELDS];
GO
CREATE TABLE [DOC_REPORTFIELDS] (
    [RPT_FIELDID] BIGINT NOT NULL,
    [RPT_COLFIELD] VARCHAR(2000) NULL,
    [RPT_COLDISPFIELD] VARCHAR(30) NOT NULL,
    CONSTRAINT [PK_DOC_REPORTFIELDS] PRIMARY KEY ([RPT_FIELDID])
);
GO

-- ==========================================
-- DOC_SHAREPOINT - Document SharePoint Integration
-- ==========================================
IF OBJECT_ID('[DOC_SHAREPOINT]', 'U') IS NOT NULL DROP TABLE [DOC_SHAREPOINT];
GO
CREATE TABLE [DOC_SHAREPOINT] (
    [ID] BIGINT NULL,
    [UNIT] VARCHAR(50) NULL,
    [STATUS] VARCHAR(100) NULL,
    [CATEGORY] VARCHAR(100) NULL,
    [SUBCAT] VARCHAR(100) NULL,
    [BUSINESS] VARCHAR(50) NULL,
    [VENDORNAMESITE] VARCHAR(500) NULL,
    [VENDORNAME] VARCHAR(500) NULL,
    [VENDORSITE] VARCHAR(500) NULL,
    [PONO] VARCHAR(500) NULL,
    [MRCNO] VARCHAR(500) NULL,
    [R12VOUCHER] VARCHAR(100) NULL,
    [CURRENTCY] VARCHAR(10) NULL,
    [AMOUNT] VARCHAR(100) NULL,
    [DOC_KEY] VARCHAR(100) NULL,
    [INV_NO] VARCHAR(1000) NULL,
    [INV_DATE] VARCHAR(100) NULL,
    [PAYTO] VARCHAR(1000) NULL,
    [VENDORCODE] VARCHAR(200) NULL,
    [R12BUCODE] VARCHAR(25) NULL
);
GO

PRINT 'INVOICE_PROCESSING_MODULE Schema created successfully.';
GO
