IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132436_InitialCreate'
)
BEGIN
    CREATE TABLE [MEMBER_AUDIT_LOG] (
        [AUDIT_ID] bigint NOT NULL IDENTITY,
        [MEMBER_NO] bigint NOT NULL,
        [AUDIT_ACTION] nvarchar(50) NOT NULL,
        [AUDIT_TIMESTAMP] DATETIME2(3) NOT NULL,
        [AUDIT_USER_ID] bigint NOT NULL,
        [AUDIT_OLD_VALUES] VARCHAR(MAX) NULL,
        [AUDIT_NEW_VALUES] VARCHAR(MAX) NULL,
        CONSTRAINT [PK_MEMBER_AUDIT_LOG] PRIMARY KEY ([AUDIT_ID])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132436_InitialCreate'
)
BEGIN
    CREATE TABLE [MEMBER_MASTER] (
        [MEMBER_NO] bigint NOT NULL,
        [MEMBER_TRUST_CODE] CHAR(3) NOT NULL,
        [MEMBER_FPSTRUST_CODE] CHAR(3) NOT NULL,
        [MEMBER_OPF_NO] int NOT NULL,
        [MEMBER_PENSION_NO] int NOT NULL,
        [MEMBER_NAME] nvarchar(65) NOT NULL,
        [MEMBER_FATHERNAME] nvarchar(65) NULL,
        [MEMBER_DOB] DATETIME2(3) NULL,
        [MEMBER_ENR_DATE] DATETIME2(3) NOT NULL,
        [MEMBER_DOJ] DATETIME2(3) NOT NULL,
        [MEMBER_EMPLOYEE_TYPE] CHAR(2) NOT NULL,
        [MEMBER_UNIT_CODE] CHAR(3) NOT NULL,
        [MEMBER_EMP_NUM] bigint NOT NULL,
        [MEMBER_EMP_SYSID] bigint NOT NULL,
        [MEMBER_ENROLL_USER_ID] nvarchar(25) NOT NULL,
        [MEMBER_ENROLL_SYSID] bigint NOT NULL,
        [MEMBER_ENROLL_DATE] DATETIME2(3) NOT NULL,
        [MEMBER_CLOSURE_DATE] DATETIME2(3) NULL,
        [MEMBER_LEAVE_DATE] DATETIME2(3) NULL,
        [MEMBER_LEAVE_REASON] nvarchar(200) NULL,
        [MEMBER_STATUS] CHAR(1) NOT NULL,
        [MEMBER_UPDATED_BY] bigint NULL,
        [MEMBER_UPDATED_ON] DATETIME2(3) NULL,
        CONSTRAINT [PK_MEMBER_MASTER] PRIMARY KEY ([MEMBER_NO])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132436_InitialCreate'
)
BEGIN
    CREATE TABLE [NOMINEE_GAURDIAN] (
        [GN_TRUST_CODE] CHAR(3) NOT NULL,
        [GN_NOMINEE_MEMBER_NO] bigint NOT NULL,
        [GN_NOMINEE_SERIAL_NO] bigint NOT NULL,
        [GAURDIAN_NAME] nvarchar(65) NOT NULL,
        [GN_ADDRESS_LINE1] nvarchar(200) NULL,
        [GN_ADDRESS_LINE2] nvarchar(200) NULL,
        [GN_ADDRESS_LINE3] nvarchar(200) NULL,
        [GN_ADDRESS_LINE4] nvarchar(200) NULL,
        [GN_PHONE_NO] nvarchar(20) NULL,
        [GN_EMAIL] nvarchar(100) NULL,
        [GN_EFF_DATE] DATETIME2(3) NULL,
        [GN_CLS_DATE] DATETIME2(3) NULL,
        [GAURDIAN_RELATIONSHIP] CHAR(3) NOT NULL,
        [GN_STATUS] CHAR(1) NOT NULL DEFAULT 'A',
        CONSTRAINT [PK_NOMINEE_GAURDIAN] PRIMARY KEY ([GN_TRUST_CODE], [GN_NOMINEE_MEMBER_NO], [GN_NOMINEE_SERIAL_NO])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132436_InitialCreate'
)
BEGIN
    CREATE TABLE [MEMBER_CONTACT] (
        [CONTACT_ID] bigint NOT NULL IDENTITY,
        [MEMBER_NO] bigint NOT NULL,
        [CONTACT_TYPE] CHAR(1) NOT NULL,
        [ADDRESS_LINE_1] nvarchar(200) NOT NULL,
        [ADDRESS_LINE_2] nvarchar(200) NULL,
        [ADDRESS_LINE_3] nvarchar(200) NULL,
        [CITY] nvarchar(50) NOT NULL,
        [STATE] nvarchar(50) NOT NULL,
        [PIN_CODE] nvarchar(10) NOT NULL,
        [COUNTRY] nvarchar(50) NOT NULL,
        [PHONE_NO] nvarchar(20) NULL,
        [EMAIL] nvarchar(100) NULL,
        [EFF_DATE] DATETIME2(3) NOT NULL,
        [CLS_DATE] DATETIME2(3) NULL,
        CONSTRAINT [PK_MEMBER_CONTACT] PRIMARY KEY ([CONTACT_ID]),
        CONSTRAINT [FK_MEMBER_CONTACT_MEMBER_MASTER_MEMBER_NO] FOREIGN KEY ([MEMBER_NO]) REFERENCES [MEMBER_MASTER] ([MEMBER_NO]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132436_InitialCreate'
)
BEGIN
    CREATE TABLE [MEMBER_NOMINEE] (
        [NOMINEE_MEMBER_NO] BIGINT NOT NULL,
        [NOMINEE_SERIAL_NO] int NOT NULL,
        [NOMINEE_FUND_TYPE] CHAR(3) NOT NULL,
        [NOMINEE_NAME] nvarchar(65) NOT NULL,
        [NOMINEE_RELATIONSHIP_CODE] CHAR(3) NOT NULL,
        [NOMINEE_PERCENTAGE] bigint NOT NULL,
        [NOMINEE_DOB] DATETIME2(3) NOT NULL,
        [NOMINEE_ADDRESS_LINE_1] nvarchar(200) NULL,
        [NOMINEE_ADDRESS_LINE_2] nvarchar(200) NULL,
        [NOMINEE_ADDRESS_LINE_3] nvarchar(200) NULL,
        [NOMINEE_PHONE_NO] nvarchar(20) NULL,
        [NOMINEE_EMAIL] nvarchar(100) NULL,
        [NOMINEE_EFF_DATE] DATETIME2(3) NOT NULL,
        [NOMINEE_CLS_DATE] DATETIME2(3) NULL,
        [NOMINEE_MINOR_FLAG] nvarchar(max) NOT NULL,
        [NOMINEE_TRUST_CODE] CHAR(3) NOT NULL,
        [NOMINEE_STATUS] CHAR(1) NOT NULL,
        CONSTRAINT [PK_MEMBER_NOMINEE] PRIMARY KEY ([NOMINEE_MEMBER_NO], [NOMINEE_SERIAL_NO], [NOMINEE_FUND_TYPE]),
        CONSTRAINT [FK_MEMBER_NOMINEE_MEMBER_MASTER_NOMINEE_MEMBER_NO] FOREIGN KEY ([NOMINEE_MEMBER_NO]) REFERENCES [MEMBER_MASTER] ([MEMBER_NO]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132436_InitialCreate'
)
BEGIN
    CREATE TABLE [MEMBER_PAYROLL] (
        [PAYROLL_MEMBER_NO] bigint NOT NULL,
        [PAYROLL_UNT_COD] CHAR(3) NOT NULL,
        [PAYROLL_EMP_NUM] bigint NOT NULL,
        [PAYROLL_EFF_DATE] DATETIME2(3) NOT NULL,
        [PAYROLL_CLS_DATE] DATETIME2(3) NULL,
        [PAYROLL_STATUS] CHAR(1) NOT NULL,
        CONSTRAINT [PK_MEMBER_PAYROLL] PRIMARY KEY ([PAYROLL_MEMBER_NO], [PAYROLL_UNT_COD]),
        CONSTRAINT [FK_MEMBER_PAYROLL_MEMBER_MASTER_PAYROLL_MEMBER_NO] FOREIGN KEY ([PAYROLL_MEMBER_NO]) REFERENCES [MEMBER_MASTER] ([MEMBER_NO]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132436_InitialCreate'
)
BEGIN
    CREATE INDEX [IDX_MEMBER_AUDIT_LOG_MEMBER] ON [MEMBER_AUDIT_LOG] ([MEMBER_NO], [AUDIT_TIMESTAMP]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132436_InitialCreate'
)
BEGIN
    CREATE INDEX [IDX_MEMBER_CONTACT_MEMBER] ON [MEMBER_CONTACT] ([MEMBER_NO], [CONTACT_TYPE]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132436_InitialCreate'
)
BEGIN
    CREATE INDEX [IDX_MEMBER_MASTER_EMP_SYSID] ON [MEMBER_MASTER] ([MEMBER_EMP_SYSID]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132436_InitialCreate'
)
BEGIN
    CREATE INDEX [IDX_MEMBER_MASTER_TRUST_STATUS] ON [MEMBER_MASTER] ([MEMBER_TRUST_CODE], [MEMBER_STATUS]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132436_InitialCreate'
)
BEGIN
    CREATE INDEX [IDX_MEMBER_NOMINEE_MEMBER] ON [MEMBER_NOMINEE] ([NOMINEE_MEMBER_NO], [NOMINEE_EFF_DATE], [NOMINEE_STATUS]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132436_InitialCreate'
)
BEGIN
    CREATE INDEX [IDX_MEMBER_PAYROLL_STATUS] ON [MEMBER_PAYROLL] ([PAYROLL_MEMBER_NO], [PAYROLL_STATUS]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132436_InitialCreate'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260317132436_InitialCreate', N'9.0.2');
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132452_SeedData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'MEMBER_NO', N'MEMBER_TRUST_CODE', N'MEMBER_FPSTRUST_CODE', N'MEMBER_OPF_NO', N'MEMBER_PENSION_NO', N'MEMBER_NAME', N'MEMBER_FATHERNAME', N'MEMBER_DOB', N'MEMBER_ENR_DATE', N'MEMBER_DOJ', N'MEMBER_EMPLOYEE_TYPE', N'MEMBER_UNIT_CODE', N'MEMBER_EMP_NUM', N'MEMBER_EMP_SYSID', N'MEMBER_ENROLL_USER_ID', N'MEMBER_ENROLL_SYSID', N'MEMBER_ENROLL_DATE', N'MEMBER_STATUS', N'MEMBER_CLOSURE_DATE', N'MEMBER_LEAVE_DATE', N'MEMBER_LEAVE_REASON', N'MEMBER_UPDATED_BY', N'MEMBER_UPDATED_ON') AND [object_id] = OBJECT_ID(N'[MEMBER_MASTER]'))
        SET IDENTITY_INSERT [MEMBER_MASTER] ON;
    EXEC(N'INSERT INTO [MEMBER_MASTER] ([MEMBER_NO], [MEMBER_TRUST_CODE], [MEMBER_FPSTRUST_CODE], [MEMBER_OPF_NO], [MEMBER_PENSION_NO], [MEMBER_NAME], [MEMBER_FATHERNAME], [MEMBER_DOB], [MEMBER_ENR_DATE], [MEMBER_DOJ], [MEMBER_EMPLOYEE_TYPE], [MEMBER_UNIT_CODE], [MEMBER_EMP_NUM], [MEMBER_EMP_SYSID], [MEMBER_ENROLL_USER_ID], [MEMBER_ENROLL_SYSID], [MEMBER_ENROLL_DATE], [MEMBER_STATUS], [MEMBER_CLOSURE_DATE], [MEMBER_LEAVE_DATE], [MEMBER_LEAVE_REASON], [MEMBER_UPDATED_BY], [MEMBER_UPDATED_ON])
    VALUES (CAST(1001 AS bigint), ''SRF'', ''SRF'', 1001, 1001, N''JOHN DOE'', N''JAMES DOE'', ''1985-06-10T00:00:00.000'', ''2020-01-15T00:00:00.000'', ''2020-01-15T00:00:00.000'', ''N'', ''SRF'', CAST(5001 AS bigint), CAST(1001 AS bigint), N''ADMIN'', CAST(1 AS bigint), ''2020-01-15T00:00:00.000'', ''A'', NULL, NULL, NULL, CAST(1 AS bigint), ''2020-01-15T00:00:00.000'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'MEMBER_NO', N'MEMBER_TRUST_CODE', N'MEMBER_FPSTRUST_CODE', N'MEMBER_OPF_NO', N'MEMBER_PENSION_NO', N'MEMBER_NAME', N'MEMBER_FATHERNAME', N'MEMBER_DOB', N'MEMBER_ENR_DATE', N'MEMBER_DOJ', N'MEMBER_EMPLOYEE_TYPE', N'MEMBER_UNIT_CODE', N'MEMBER_EMP_NUM', N'MEMBER_EMP_SYSID', N'MEMBER_ENROLL_USER_ID', N'MEMBER_ENROLL_SYSID', N'MEMBER_ENROLL_DATE', N'MEMBER_STATUS', N'MEMBER_CLOSURE_DATE', N'MEMBER_LEAVE_DATE', N'MEMBER_LEAVE_REASON', N'MEMBER_UPDATED_BY', N'MEMBER_UPDATED_ON') AND [object_id] = OBJECT_ID(N'[MEMBER_MASTER]'))
        SET IDENTITY_INSERT [MEMBER_MASTER] OFF;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132452_SeedData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'MEMBER_NO', N'MEMBER_TRUST_CODE', N'MEMBER_FPSTRUST_CODE', N'MEMBER_OPF_NO', N'MEMBER_PENSION_NO', N'MEMBER_NAME', N'MEMBER_FATHERNAME', N'MEMBER_DOB', N'MEMBER_ENR_DATE', N'MEMBER_DOJ', N'MEMBER_EMPLOYEE_TYPE', N'MEMBER_UNIT_CODE', N'MEMBER_EMP_NUM', N'MEMBER_EMP_SYSID', N'MEMBER_ENROLL_USER_ID', N'MEMBER_ENROLL_SYSID', N'MEMBER_ENROLL_DATE', N'MEMBER_STATUS', N'MEMBER_CLOSURE_DATE', N'MEMBER_LEAVE_DATE', N'MEMBER_LEAVE_REASON', N'MEMBER_UPDATED_BY', N'MEMBER_UPDATED_ON') AND [object_id] = OBJECT_ID(N'[MEMBER_MASTER]'))
        SET IDENTITY_INSERT [MEMBER_MASTER] ON;
    EXEC(N'INSERT INTO [MEMBER_MASTER] ([MEMBER_NO], [MEMBER_TRUST_CODE], [MEMBER_FPSTRUST_CODE], [MEMBER_OPF_NO], [MEMBER_PENSION_NO], [MEMBER_NAME], [MEMBER_FATHERNAME], [MEMBER_DOB], [MEMBER_ENR_DATE], [MEMBER_DOJ], [MEMBER_EMPLOYEE_TYPE], [MEMBER_UNIT_CODE], [MEMBER_EMP_NUM], [MEMBER_EMP_SYSID], [MEMBER_ENROLL_USER_ID], [MEMBER_ENROLL_SYSID], [MEMBER_ENROLL_DATE], [MEMBER_STATUS], [MEMBER_CLOSURE_DATE], [MEMBER_LEAVE_DATE], [MEMBER_LEAVE_REASON], [MEMBER_UPDATED_BY], [MEMBER_UPDATED_ON])
    VALUES (CAST(1002 AS bigint), ''SRF'', ''SRF'', 1002, 1002, N''PRIYA SHARMA'', N''RAJESH SHARMA'', ''1990-11-25T00:00:00.000'', ''2018-04-01T00:00:00.000'', ''2018-04-01T00:00:00.000'', ''S'', ''SRF'', CAST(5002 AS bigint), CAST(1002 AS bigint), N''ADMIN'', CAST(1 AS bigint), ''2018-04-01T00:00:00.000'', ''A'', NULL, NULL, NULL, CAST(1 AS bigint), ''2018-04-01T00:00:00.000'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'MEMBER_NO', N'MEMBER_TRUST_CODE', N'MEMBER_FPSTRUST_CODE', N'MEMBER_OPF_NO', N'MEMBER_PENSION_NO', N'MEMBER_NAME', N'MEMBER_FATHERNAME', N'MEMBER_DOB', N'MEMBER_ENR_DATE', N'MEMBER_DOJ', N'MEMBER_EMPLOYEE_TYPE', N'MEMBER_UNIT_CODE', N'MEMBER_EMP_NUM', N'MEMBER_EMP_SYSID', N'MEMBER_ENROLL_USER_ID', N'MEMBER_ENROLL_SYSID', N'MEMBER_ENROLL_DATE', N'MEMBER_STATUS', N'MEMBER_CLOSURE_DATE', N'MEMBER_LEAVE_DATE', N'MEMBER_LEAVE_REASON', N'MEMBER_UPDATED_BY', N'MEMBER_UPDATED_ON') AND [object_id] = OBJECT_ID(N'[MEMBER_MASTER]'))
        SET IDENTITY_INSERT [MEMBER_MASTER] OFF;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132452_SeedData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'MEMBER_NO', N'MEMBER_TRUST_CODE', N'MEMBER_FPSTRUST_CODE', N'MEMBER_OPF_NO', N'MEMBER_PENSION_NO', N'MEMBER_NAME', N'MEMBER_FATHERNAME', N'MEMBER_DOB', N'MEMBER_ENR_DATE', N'MEMBER_DOJ', N'MEMBER_EMPLOYEE_TYPE', N'MEMBER_UNIT_CODE', N'MEMBER_EMP_NUM', N'MEMBER_EMP_SYSID', N'MEMBER_ENROLL_USER_ID', N'MEMBER_ENROLL_SYSID', N'MEMBER_ENROLL_DATE', N'MEMBER_STATUS', N'MEMBER_CLOSURE_DATE', N'MEMBER_LEAVE_DATE', N'MEMBER_LEAVE_REASON', N'MEMBER_UPDATED_BY', N'MEMBER_UPDATED_ON') AND [object_id] = OBJECT_ID(N'[MEMBER_MASTER]'))
        SET IDENTITY_INSERT [MEMBER_MASTER] ON;
    EXEC(N'INSERT INTO [MEMBER_MASTER] ([MEMBER_NO], [MEMBER_TRUST_CODE], [MEMBER_FPSTRUST_CODE], [MEMBER_OPF_NO], [MEMBER_PENSION_NO], [MEMBER_NAME], [MEMBER_FATHERNAME], [MEMBER_DOB], [MEMBER_ENR_DATE], [MEMBER_DOJ], [MEMBER_EMPLOYEE_TYPE], [MEMBER_UNIT_CODE], [MEMBER_EMP_NUM], [MEMBER_EMP_SYSID], [MEMBER_ENROLL_USER_ID], [MEMBER_ENROLL_SYSID], [MEMBER_ENROLL_DATE], [MEMBER_STATUS], [MEMBER_CLOSURE_DATE], [MEMBER_LEAVE_DATE], [MEMBER_LEAVE_REASON], [MEMBER_UPDATED_BY], [MEMBER_UPDATED_ON])
    VALUES (CAST(1003 AS bigint), ''SRF'', ''SRF'', 1003, 1003, N''RAVI KUMAR'', N''SURESH KUMAR'', ''1978-03-14T00:00:00.000'', ''2015-06-10T00:00:00.000'', ''2015-06-10T00:00:00.000'', ''O'', ''SRF'', CAST(5003 AS bigint), CAST(1003 AS bigint), N''ADMIN'', CAST(1 AS bigint), ''2015-06-10T00:00:00.000'', ''C'', ''2024-12-31T00:00:00.000'', ''2024-12-31T00:00:00.000'', N''VOLUNTARY RETIREMENT'', CAST(1 AS bigint), ''2024-12-31T00:00:00.000'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'MEMBER_NO', N'MEMBER_TRUST_CODE', N'MEMBER_FPSTRUST_CODE', N'MEMBER_OPF_NO', N'MEMBER_PENSION_NO', N'MEMBER_NAME', N'MEMBER_FATHERNAME', N'MEMBER_DOB', N'MEMBER_ENR_DATE', N'MEMBER_DOJ', N'MEMBER_EMPLOYEE_TYPE', N'MEMBER_UNIT_CODE', N'MEMBER_EMP_NUM', N'MEMBER_EMP_SYSID', N'MEMBER_ENROLL_USER_ID', N'MEMBER_ENROLL_SYSID', N'MEMBER_ENROLL_DATE', N'MEMBER_STATUS', N'MEMBER_CLOSURE_DATE', N'MEMBER_LEAVE_DATE', N'MEMBER_LEAVE_REASON', N'MEMBER_UPDATED_BY', N'MEMBER_UPDATED_ON') AND [object_id] = OBJECT_ID(N'[MEMBER_MASTER]'))
        SET IDENTITY_INSERT [MEMBER_MASTER] OFF;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132452_SeedData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'PAYROLL_MEMBER_NO', N'PAYROLL_UNT_COD', N'PAYROLL_EMP_NUM', N'PAYROLL_EFF_DATE', N'PAYROLL_STATUS') AND [object_id] = OBJECT_ID(N'[MEMBER_PAYROLL]'))
        SET IDENTITY_INSERT [MEMBER_PAYROLL] ON;
    EXEC(N'INSERT INTO [MEMBER_PAYROLL] ([PAYROLL_MEMBER_NO], [PAYROLL_UNT_COD], [PAYROLL_EMP_NUM], [PAYROLL_EFF_DATE], [PAYROLL_STATUS])
    VALUES (CAST(1001 AS bigint), ''SRF'', CAST(5001 AS bigint), ''2020-01-15T00:00:00.000'', ''A'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'PAYROLL_MEMBER_NO', N'PAYROLL_UNT_COD', N'PAYROLL_EMP_NUM', N'PAYROLL_EFF_DATE', N'PAYROLL_STATUS') AND [object_id] = OBJECT_ID(N'[MEMBER_PAYROLL]'))
        SET IDENTITY_INSERT [MEMBER_PAYROLL] OFF;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132452_SeedData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'PAYROLL_MEMBER_NO', N'PAYROLL_UNT_COD', N'PAYROLL_EMP_NUM', N'PAYROLL_EFF_DATE', N'PAYROLL_STATUS') AND [object_id] = OBJECT_ID(N'[MEMBER_PAYROLL]'))
        SET IDENTITY_INSERT [MEMBER_PAYROLL] ON;
    EXEC(N'INSERT INTO [MEMBER_PAYROLL] ([PAYROLL_MEMBER_NO], [PAYROLL_UNT_COD], [PAYROLL_EMP_NUM], [PAYROLL_EFF_DATE], [PAYROLL_STATUS])
    VALUES (CAST(1002 AS bigint), ''SRF'', CAST(5002 AS bigint), ''2018-04-01T00:00:00.000'', ''A'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'PAYROLL_MEMBER_NO', N'PAYROLL_UNT_COD', N'PAYROLL_EMP_NUM', N'PAYROLL_EFF_DATE', N'PAYROLL_STATUS') AND [object_id] = OBJECT_ID(N'[MEMBER_PAYROLL]'))
        SET IDENTITY_INSERT [MEMBER_PAYROLL] OFF;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132452_SeedData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'PAYROLL_MEMBER_NO', N'PAYROLL_UNT_COD', N'PAYROLL_EMP_NUM', N'PAYROLL_EFF_DATE', N'PAYROLL_CLS_DATE', N'PAYROLL_STATUS') AND [object_id] = OBJECT_ID(N'[MEMBER_PAYROLL]'))
        SET IDENTITY_INSERT [MEMBER_PAYROLL] ON;
    EXEC(N'INSERT INTO [MEMBER_PAYROLL] ([PAYROLL_MEMBER_NO], [PAYROLL_UNT_COD], [PAYROLL_EMP_NUM], [PAYROLL_EFF_DATE], [PAYROLL_CLS_DATE], [PAYROLL_STATUS])
    VALUES (CAST(1003 AS bigint), ''SRF'', CAST(5003 AS bigint), ''2015-06-10T00:00:00.000'', ''2024-12-31T00:00:00.000'', ''C'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'PAYROLL_MEMBER_NO', N'PAYROLL_UNT_COD', N'PAYROLL_EMP_NUM', N'PAYROLL_EFF_DATE', N'PAYROLL_CLS_DATE', N'PAYROLL_STATUS') AND [object_id] = OBJECT_ID(N'[MEMBER_PAYROLL]'))
        SET IDENTITY_INSERT [MEMBER_PAYROLL] OFF;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132452_SeedData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'NOMINEE_MEMBER_NO', N'NOMINEE_SERIAL_NO', N'NOMINEE_FUND_TYPE', N'NOMINEE_NAME', N'NOMINEE_RELATIONSHIP_CODE', N'NOMINEE_PERCENTAGE', N'NOMINEE_DOB', N'NOMINEE_EFF_DATE', N'NOMINEE_MINOR_FLAG', N'NOMINEE_TRUST_CODE', N'NOMINEE_STATUS') AND [object_id] = OBJECT_ID(N'[MEMBER_NOMINEE]'))
        SET IDENTITY_INSERT [MEMBER_NOMINEE] ON;
    EXEC(N'INSERT INTO [MEMBER_NOMINEE] ([NOMINEE_MEMBER_NO], [NOMINEE_SERIAL_NO], [NOMINEE_FUND_TYPE], [NOMINEE_NAME], [NOMINEE_RELATIONSHIP_CODE], [NOMINEE_PERCENTAGE], [NOMINEE_DOB], [NOMINEE_EFF_DATE], [NOMINEE_MINOR_FLAG], [NOMINEE_TRUST_CODE], [NOMINEE_STATUS])
    VALUES (CAST(1001 AS BIGINT), 1, ''GPF'', N''JANE DOE'', ''SPO'', CAST(100 AS bigint), ''1988-03-22T00:00:00.000'', ''2020-01-15T00:00:00.000'', N''N'', ''SRF'', ''A'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'NOMINEE_MEMBER_NO', N'NOMINEE_SERIAL_NO', N'NOMINEE_FUND_TYPE', N'NOMINEE_NAME', N'NOMINEE_RELATIONSHIP_CODE', N'NOMINEE_PERCENTAGE', N'NOMINEE_DOB', N'NOMINEE_EFF_DATE', N'NOMINEE_MINOR_FLAG', N'NOMINEE_TRUST_CODE', N'NOMINEE_STATUS') AND [object_id] = OBJECT_ID(N'[MEMBER_NOMINEE]'))
        SET IDENTITY_INSERT [MEMBER_NOMINEE] OFF;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132452_SeedData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'NOMINEE_MEMBER_NO', N'NOMINEE_SERIAL_NO', N'NOMINEE_FUND_TYPE', N'NOMINEE_NAME', N'NOMINEE_RELATIONSHIP_CODE', N'NOMINEE_PERCENTAGE', N'NOMINEE_DOB', N'NOMINEE_EFF_DATE', N'NOMINEE_MINOR_FLAG', N'NOMINEE_TRUST_CODE', N'NOMINEE_STATUS') AND [object_id] = OBJECT_ID(N'[MEMBER_NOMINEE]'))
        SET IDENTITY_INSERT [MEMBER_NOMINEE] ON;
    EXEC(N'INSERT INTO [MEMBER_NOMINEE] ([NOMINEE_MEMBER_NO], [NOMINEE_SERIAL_NO], [NOMINEE_FUND_TYPE], [NOMINEE_NAME], [NOMINEE_RELATIONSHIP_CODE], [NOMINEE_PERCENTAGE], [NOMINEE_DOB], [NOMINEE_EFF_DATE], [NOMINEE_MINOR_FLAG], [NOMINEE_TRUST_CODE], [NOMINEE_STATUS])
    VALUES (CAST(1001 AS BIGINT), 1, ''FPS'', N''JANE DOE'', ''SPO'', CAST(100 AS bigint), ''1988-03-22T00:00:00.000'', ''2020-01-15T00:00:00.000'', N''N'', ''SRF'', ''A'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'NOMINEE_MEMBER_NO', N'NOMINEE_SERIAL_NO', N'NOMINEE_FUND_TYPE', N'NOMINEE_NAME', N'NOMINEE_RELATIONSHIP_CODE', N'NOMINEE_PERCENTAGE', N'NOMINEE_DOB', N'NOMINEE_EFF_DATE', N'NOMINEE_MINOR_FLAG', N'NOMINEE_TRUST_CODE', N'NOMINEE_STATUS') AND [object_id] = OBJECT_ID(N'[MEMBER_NOMINEE]'))
        SET IDENTITY_INSERT [MEMBER_NOMINEE] OFF;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132452_SeedData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'NOMINEE_MEMBER_NO', N'NOMINEE_SERIAL_NO', N'NOMINEE_FUND_TYPE', N'NOMINEE_NAME', N'NOMINEE_RELATIONSHIP_CODE', N'NOMINEE_PERCENTAGE', N'NOMINEE_DOB', N'NOMINEE_EFF_DATE', N'NOMINEE_MINOR_FLAG', N'NOMINEE_TRUST_CODE', N'NOMINEE_STATUS') AND [object_id] = OBJECT_ID(N'[MEMBER_NOMINEE]'))
        SET IDENTITY_INSERT [MEMBER_NOMINEE] ON;
    EXEC(N'INSERT INTO [MEMBER_NOMINEE] ([NOMINEE_MEMBER_NO], [NOMINEE_SERIAL_NO], [NOMINEE_FUND_TYPE], [NOMINEE_NAME], [NOMINEE_RELATIONSHIP_CODE], [NOMINEE_PERCENTAGE], [NOMINEE_DOB], [NOMINEE_EFF_DATE], [NOMINEE_MINOR_FLAG], [NOMINEE_TRUST_CODE], [NOMINEE_STATUS])
    VALUES (CAST(1002 AS BIGINT), 1, ''GPF'', N''ARJUN SHARMA'', ''SON'', CAST(60 AS bigint), ''2015-07-05T00:00:00.000'', ''2018-04-01T00:00:00.000'', N''Y'', ''SRF'', ''A'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'NOMINEE_MEMBER_NO', N'NOMINEE_SERIAL_NO', N'NOMINEE_FUND_TYPE', N'NOMINEE_NAME', N'NOMINEE_RELATIONSHIP_CODE', N'NOMINEE_PERCENTAGE', N'NOMINEE_DOB', N'NOMINEE_EFF_DATE', N'NOMINEE_MINOR_FLAG', N'NOMINEE_TRUST_CODE', N'NOMINEE_STATUS') AND [object_id] = OBJECT_ID(N'[MEMBER_NOMINEE]'))
        SET IDENTITY_INSERT [MEMBER_NOMINEE] OFF;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132452_SeedData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'NOMINEE_MEMBER_NO', N'NOMINEE_SERIAL_NO', N'NOMINEE_FUND_TYPE', N'NOMINEE_NAME', N'NOMINEE_RELATIONSHIP_CODE', N'NOMINEE_PERCENTAGE', N'NOMINEE_DOB', N'NOMINEE_EFF_DATE', N'NOMINEE_MINOR_FLAG', N'NOMINEE_TRUST_CODE', N'NOMINEE_STATUS') AND [object_id] = OBJECT_ID(N'[MEMBER_NOMINEE]'))
        SET IDENTITY_INSERT [MEMBER_NOMINEE] ON;
    EXEC(N'INSERT INTO [MEMBER_NOMINEE] ([NOMINEE_MEMBER_NO], [NOMINEE_SERIAL_NO], [NOMINEE_FUND_TYPE], [NOMINEE_NAME], [NOMINEE_RELATIONSHIP_CODE], [NOMINEE_PERCENTAGE], [NOMINEE_DOB], [NOMINEE_EFF_DATE], [NOMINEE_MINOR_FLAG], [NOMINEE_TRUST_CODE], [NOMINEE_STATUS])
    VALUES (CAST(1002 AS BIGINT), 2, ''GPF'', N''SUNITA SHARMA'', ''MTH'', CAST(40 AS bigint), ''1962-02-18T00:00:00.000'', ''2018-04-01T00:00:00.000'', N''N'', ''SRF'', ''A'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'NOMINEE_MEMBER_NO', N'NOMINEE_SERIAL_NO', N'NOMINEE_FUND_TYPE', N'NOMINEE_NAME', N'NOMINEE_RELATIONSHIP_CODE', N'NOMINEE_PERCENTAGE', N'NOMINEE_DOB', N'NOMINEE_EFF_DATE', N'NOMINEE_MINOR_FLAG', N'NOMINEE_TRUST_CODE', N'NOMINEE_STATUS') AND [object_id] = OBJECT_ID(N'[MEMBER_NOMINEE]'))
        SET IDENTITY_INSERT [MEMBER_NOMINEE] OFF;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132452_SeedData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'NOMINEE_MEMBER_NO', N'NOMINEE_SERIAL_NO', N'NOMINEE_FUND_TYPE', N'NOMINEE_NAME', N'NOMINEE_RELATIONSHIP_CODE', N'NOMINEE_PERCENTAGE', N'NOMINEE_DOB', N'NOMINEE_EFF_DATE', N'NOMINEE_MINOR_FLAG', N'NOMINEE_TRUST_CODE', N'NOMINEE_STATUS') AND [object_id] = OBJECT_ID(N'[MEMBER_NOMINEE]'))
        SET IDENTITY_INSERT [MEMBER_NOMINEE] ON;
    EXEC(N'INSERT INTO [MEMBER_NOMINEE] ([NOMINEE_MEMBER_NO], [NOMINEE_SERIAL_NO], [NOMINEE_FUND_TYPE], [NOMINEE_NAME], [NOMINEE_RELATIONSHIP_CODE], [NOMINEE_PERCENTAGE], [NOMINEE_DOB], [NOMINEE_EFF_DATE], [NOMINEE_MINOR_FLAG], [NOMINEE_TRUST_CODE], [NOMINEE_STATUS])
    VALUES (CAST(1002 AS BIGINT), 1, ''FPS'', N''ARJUN SHARMA'', ''SON'', CAST(100 AS bigint), ''2015-07-05T00:00:00.000'', ''2018-04-01T00:00:00.000'', N''Y'', ''SRF'', ''A'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'NOMINEE_MEMBER_NO', N'NOMINEE_SERIAL_NO', N'NOMINEE_FUND_TYPE', N'NOMINEE_NAME', N'NOMINEE_RELATIONSHIP_CODE', N'NOMINEE_PERCENTAGE', N'NOMINEE_DOB', N'NOMINEE_EFF_DATE', N'NOMINEE_MINOR_FLAG', N'NOMINEE_TRUST_CODE', N'NOMINEE_STATUS') AND [object_id] = OBJECT_ID(N'[MEMBER_NOMINEE]'))
        SET IDENTITY_INSERT [MEMBER_NOMINEE] OFF;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132452_SeedData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'NOMINEE_MEMBER_NO', N'NOMINEE_SERIAL_NO', N'NOMINEE_FUND_TYPE', N'NOMINEE_NAME', N'NOMINEE_RELATIONSHIP_CODE', N'NOMINEE_PERCENTAGE', N'NOMINEE_DOB', N'NOMINEE_EFF_DATE', N'NOMINEE_CLS_DATE', N'NOMINEE_MINOR_FLAG', N'NOMINEE_TRUST_CODE', N'NOMINEE_STATUS') AND [object_id] = OBJECT_ID(N'[MEMBER_NOMINEE]'))
        SET IDENTITY_INSERT [MEMBER_NOMINEE] ON;
    EXEC(N'INSERT INTO [MEMBER_NOMINEE] ([NOMINEE_MEMBER_NO], [NOMINEE_SERIAL_NO], [NOMINEE_FUND_TYPE], [NOMINEE_NAME], [NOMINEE_RELATIONSHIP_CODE], [NOMINEE_PERCENTAGE], [NOMINEE_DOB], [NOMINEE_EFF_DATE], [NOMINEE_CLS_DATE], [NOMINEE_MINOR_FLAG], [NOMINEE_TRUST_CODE], [NOMINEE_STATUS])
    VALUES (CAST(1003 AS BIGINT), 1, ''GPF'', N''MEENA KUMAR'', ''SPO'', CAST(100 AS bigint), ''1980-09-03T00:00:00.000'', ''2015-06-10T00:00:00.000'', ''2024-12-31T00:00:00.000'', N''N'', ''SRF'', ''I'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'NOMINEE_MEMBER_NO', N'NOMINEE_SERIAL_NO', N'NOMINEE_FUND_TYPE', N'NOMINEE_NAME', N'NOMINEE_RELATIONSHIP_CODE', N'NOMINEE_PERCENTAGE', N'NOMINEE_DOB', N'NOMINEE_EFF_DATE', N'NOMINEE_CLS_DATE', N'NOMINEE_MINOR_FLAG', N'NOMINEE_TRUST_CODE', N'NOMINEE_STATUS') AND [object_id] = OBJECT_ID(N'[MEMBER_NOMINEE]'))
        SET IDENTITY_INSERT [MEMBER_NOMINEE] OFF;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132452_SeedData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'GN_TRUST_CODE', N'GN_NOMINEE_MEMBER_NO', N'GN_NOMINEE_SERIAL_NO', N'GAURDIAN_NAME', N'GAURDIAN_RELATIONSHIP', N'GN_ADDRESS_LINE1', N'GN_ADDRESS_LINE2', N'GN_ADDRESS_LINE3', N'GN_PHONE_NO', N'GN_EMAIL', N'GN_EFF_DATE') AND [object_id] = OBJECT_ID(N'[NOMINEE_GAURDIAN]'))
        SET IDENTITY_INSERT [NOMINEE_GAURDIAN] ON;
    EXEC(N'INSERT INTO [NOMINEE_GAURDIAN] ([GN_TRUST_CODE], [GN_NOMINEE_MEMBER_NO], [GN_NOMINEE_SERIAL_NO], [GAURDIAN_NAME], [GAURDIAN_RELATIONSHIP], [GN_ADDRESS_LINE1], [GN_ADDRESS_LINE2], [GN_ADDRESS_LINE3], [GN_PHONE_NO], [GN_EMAIL], [GN_EFF_DATE])
    VALUES (''SRF'', CAST(1002 AS bigint), CAST(1 AS bigint), N''RAJESH SHARMA'', ''FAT'', N''12 GREEN PARK'', N''NEW DELHI'', N''DELHI - 110016'', N''9911002200'', N''rajesh.sharma@example.com'', ''2018-04-01T00:00:00.000'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'GN_TRUST_CODE', N'GN_NOMINEE_MEMBER_NO', N'GN_NOMINEE_SERIAL_NO', N'GAURDIAN_NAME', N'GAURDIAN_RELATIONSHIP', N'GN_ADDRESS_LINE1', N'GN_ADDRESS_LINE2', N'GN_ADDRESS_LINE3', N'GN_PHONE_NO', N'GN_EMAIL', N'GN_EFF_DATE') AND [object_id] = OBJECT_ID(N'[NOMINEE_GAURDIAN]'))
        SET IDENTITY_INSERT [NOMINEE_GAURDIAN] OFF;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132452_SeedData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'MEMBER_NO', N'CONTACT_TYPE', N'ADDRESS_LINE_1', N'ADDRESS_LINE_2', N'CITY', N'STATE', N'PIN_CODE', N'COUNTRY', N'PHONE_NO', N'EMAIL', N'EFF_DATE') AND [object_id] = OBJECT_ID(N'[MEMBER_CONTACT]'))
        SET IDENTITY_INSERT [MEMBER_CONTACT] ON;
    EXEC(N'INSERT INTO [MEMBER_CONTACT] ([MEMBER_NO], [CONTACT_TYPE], [ADDRESS_LINE_1], [ADDRESS_LINE_2], [CITY], [STATE], [PIN_CODE], [COUNTRY], [PHONE_NO], [EMAIL], [EFF_DATE])
    VALUES (CAST(1001 AS bigint), ''P'', N''45 MAPLE STREET'', N''SECTOR 12'', N''MUMBAI'', N''MAHARASHTRA'', N''400001'', N''INDIA'', N''9876543210'', N''john.doe@example.com'', ''2020-01-15T00:00:00.000'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'MEMBER_NO', N'CONTACT_TYPE', N'ADDRESS_LINE_1', N'ADDRESS_LINE_2', N'CITY', N'STATE', N'PIN_CODE', N'COUNTRY', N'PHONE_NO', N'EMAIL', N'EFF_DATE') AND [object_id] = OBJECT_ID(N'[MEMBER_CONTACT]'))
        SET IDENTITY_INSERT [MEMBER_CONTACT] OFF;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132452_SeedData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'MEMBER_NO', N'CONTACT_TYPE', N'ADDRESS_LINE_1', N'ADDRESS_LINE_2', N'CITY', N'STATE', N'PIN_CODE', N'COUNTRY', N'PHONE_NO', N'EMAIL', N'EFF_DATE') AND [object_id] = OBJECT_ID(N'[MEMBER_CONTACT]'))
        SET IDENTITY_INSERT [MEMBER_CONTACT] ON;
    EXEC(N'INSERT INTO [MEMBER_CONTACT] ([MEMBER_NO], [CONTACT_TYPE], [ADDRESS_LINE_1], [ADDRESS_LINE_2], [CITY], [STATE], [PIN_CODE], [COUNTRY], [PHONE_NO], [EMAIL], [EFF_DATE])
    VALUES (CAST(1002 AS bigint), ''P'', N''12 GREEN PARK'', N''NEW DELHI'', N''NEW DELHI'', N''DELHI'', N''110016'', N''INDIA'', N''9911223344'', N''priya.sharma@example.com'', ''2018-04-01T00:00:00.000'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'MEMBER_NO', N'CONTACT_TYPE', N'ADDRESS_LINE_1', N'ADDRESS_LINE_2', N'CITY', N'STATE', N'PIN_CODE', N'COUNTRY', N'PHONE_NO', N'EMAIL', N'EFF_DATE') AND [object_id] = OBJECT_ID(N'[MEMBER_CONTACT]'))
        SET IDENTITY_INSERT [MEMBER_CONTACT] OFF;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132452_SeedData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'MEMBER_NO', N'AUDIT_ACTION', N'AUDIT_TIMESTAMP', N'AUDIT_USER_ID', N'AUDIT_OLD_VALUES', N'AUDIT_NEW_VALUES') AND [object_id] = OBJECT_ID(N'[MEMBER_AUDIT_LOG]'))
        SET IDENTITY_INSERT [MEMBER_AUDIT_LOG] ON;
    EXEC(N'INSERT INTO [MEMBER_AUDIT_LOG] ([MEMBER_NO], [AUDIT_ACTION], [AUDIT_TIMESTAMP], [AUDIT_USER_ID], [AUDIT_OLD_VALUES], [AUDIT_NEW_VALUES])
    VALUES (CAST(1003 AS bigint), N''MEMBER_CLOSED'', ''2024-12-31T17:00:00.000'', CAST(1 AS bigint), ''{"Status":"A"}'', ''{"Status":"C","ClosureDate":"2024-12-31","LeaveReason":"VOLUNTARY RETIREMENT"}'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'MEMBER_NO', N'AUDIT_ACTION', N'AUDIT_TIMESTAMP', N'AUDIT_USER_ID', N'AUDIT_OLD_VALUES', N'AUDIT_NEW_VALUES') AND [object_id] = OBJECT_ID(N'[MEMBER_AUDIT_LOG]'))
        SET IDENTITY_INSERT [MEMBER_AUDIT_LOG] OFF;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132452_SeedData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'MEMBER_NO', N'AUDIT_ACTION', N'AUDIT_TIMESTAMP', N'AUDIT_USER_ID', N'AUDIT_OLD_VALUES', N'AUDIT_NEW_VALUES') AND [object_id] = OBJECT_ID(N'[MEMBER_AUDIT_LOG]'))
        SET IDENTITY_INSERT [MEMBER_AUDIT_LOG] ON;
    EXEC(N'INSERT INTO [MEMBER_AUDIT_LOG] ([MEMBER_NO], [AUDIT_ACTION], [AUDIT_TIMESTAMP], [AUDIT_USER_ID], [AUDIT_OLD_VALUES], [AUDIT_NEW_VALUES])
    VALUES (CAST(1003 AS bigint), N''NOMINEE_DEACTIVATED'', ''2024-12-31T17:05:00.000'', CAST(1 AS bigint), ''{"NomineeStatus":"A"}'', ''{"NomineeStatus":"I","ClosureDate":"2024-12-31"}'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'MEMBER_NO', N'AUDIT_ACTION', N'AUDIT_TIMESTAMP', N'AUDIT_USER_ID', N'AUDIT_OLD_VALUES', N'AUDIT_NEW_VALUES') AND [object_id] = OBJECT_ID(N'[MEMBER_AUDIT_LOG]'))
        SET IDENTITY_INSERT [MEMBER_AUDIT_LOG] OFF;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260317132452_SeedData'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260317132452_SeedData', N'9.0.2');
END;

COMMIT;
GO

