-- Module: DemandManagement
USE DDDB;
GO

-- Table: DEMAND_MASTER
CREATE TABLE [DEMAND_MASTER] (
    [DEMAND_ID] BIGINT IDENTITY(1,1) NOT NULL,
    [DEMAND_TYPE] VARCHAR(50) NULL,
    [DEPARTMENT_ID] BIGINT NULL,
    [DEMAND_DESCRIPTION] VARCHAR(500) NULL,
    [REQUIRED_DATE] DATE NULL,
    [PRIORITY] VARCHAR(10) NULL,
    [DEMAND_STATUS] CHAR(1) NULL,
    [CREATED_BY] BIGINT NULL,
    [CREATED_ON] DATETIME2(3) DEFAULT GETDATE(),
    [APPROVAL_REMARKS] VARCHAR(500) NULL,
    [APPROVED_BY] BIGINT NULL,
    [APPROVAL_DATE] DATETIME2(3) NULL,
    [COMPLETION_REMARKS] VARCHAR(500) NULL,
    [COMPLETED_BY] BIGINT NULL,
    [COMPLETION_DATE] DATETIME2(3) NULL,
    CONSTRAINT [PK_DEMAND_MASTER] PRIMARY KEY ([DEMAND_ID])
);
