-- ==========================================
-- Module: MASTER DATA & REFERENCE
-- Description: Master data and reference tables
-- Tables: Cities, hotels, guest houses, GL codes
-- ==========================================

USE [TRAVELDB];
GO

-- Table: GH_ROOMS - Guest house rooms
CREATE TABLE [GH_ROOMS] (
    [GH_GHS_COD] BIGINT NULL  -- Guest House Code,
    [GH_ROM_SRL] BIGINT NULL  -- Room Serial No,
    [GH_NOF_PER] BIGINT NULL  -- No of Person Allowed,
    [GH_ROM_NUM] BIGINT NULL,
    [GH_GHS_FLR] BIGINT NULL
);

-- Table: GUEST_ROOM_AVAIL_TEMP - Guest room availability
CREATE TABLE [GUEST_ROOM_AVAIL_TEMP] (
    [GHS_FLR_NUM] BIGINT NULL,
    [GHS_ROM_NUM] BIGINT NULL,
    [GHS_ROM_STS] CHAR(1) NULL,
    [GHS_FLR_VAL] VARCHAR(200) NULL
);

-- Table: TRAVEL_GUESTHOUSE - Guest house master
CREATE TABLE [TRAVEL_GUESTHOUSE] (
    [AD_ADM_COD] BIGINT NOT NULL,
    [AD_ADM_NAM] VARCHAR(50) NULL,
    [AD_ADM_TYP] VARCHAR(1) NULL,
    [AD_ADM_AMOUNT] BIGINT NULL
);

-- Table: GL_CODE_COMBINATIONS_KFV - GL code combinations
CREATE TABLE [GL_CODE_COMBINATIONS_KFV] (
    [ROW_ID] BIGINT NOT NULL,
    [CODE_COMBINATION_ID] BIGINT NOT NULL,
    [CHART_OF_ACCOUNTS_ID] BIGINT NOT NULL,
    [CONCATENATED_SEGMENTS] VARCHAR(207) NULL,
    [GL_ACCOUNT_TYPE] VARCHAR(1) NOT NULL,
    [ENABLED_FLAG] VARCHAR(1) NOT NULL,
    [SUMMARY_FLAG] VARCHAR(1) NOT NULL,
    [CONTEXT] VARCHAR(150) NULL,
    [LAST_UPDATED_BY] DECIMAL(38) NOT NULL,
    [LAST_UPDATE_DATE] DATETIME2(3) NOT NULL
);

-- Table: COUPON_TEMP - Coupon temporary data
CREATE TABLE [COUPON_TEMP] (
    [CPN_ID] BIGINT NULL,
    [AIR_LIN] VARCHAR(50) NULL,
    [TOT_CPN] BIGINT NULL,
    [USD_CPN] BIGINT NULL,
    [BAL_CPN] BIGINT NULL,
    [VLS_TIL] DATETIME2(3) NULL
);

-- Table: TAX_SLAB22 - Tax slab 22
CREATE TABLE [TAX_SLAB22] (
    [TAX_TYPE] CHAR(5) NOT NULL
);

-- Table: TAX_SLAB23 - Tax slab 23
CREATE TABLE [TAX_SLAB23] (
    [TAX_EFFDAT] DATETIME2(3) NOT NULL
);

-- Table: TAX_SLAB24 - Tax slab 24
CREATE TABLE [TAX_SLAB24] (
    [TAX_CLSDAT] DATETIME2(3) NULL
);

-- Table: TAX_SLAB25 - Tax slab 25
CREATE TABLE [TAX_SLAB25] (
    [TAX_RATE] DECIMAL(19,0) NULL
);

-- Table: TAX_SLAB26 - Tax slab 26
CREATE TABLE [TAX_SLAB26] (
    [VENDORCODE] BIGINT NOT NULL
);

-- Table: SOURCE_HIST - Source history
CREATE TABLE [SOURCE_HIST] (
    [CHANGE_DATE] DATETIME2(3) NULL,
    [NAME] VARCHAR(30) NULL,
    [TYPE] VARCHAR(12) NULL,
    [LINE] DECIMAL(38) NULL,
    [TEXT] VARCHAR(4000) NULL
);

-- Table: NEWTABLE - Utility table
CREATE TABLE [NEWTABLE] (
    [NAME] VARCHAR(255) NULL,
    [COMPENSATION] DECIMAL(38) NULL
);

-- Table: MICROSOFTDTPROPERTIES - System properties
CREATE TABLE [MICROSOFTDTPROPERTIES] (
    [ID] DECIMAL(38) NOT NULL,
    [OBJECTID] DECIMAL(38) NULL,
    [PROPERTY] VARCHAR(64) NOT NULL,
    [VALUE] VARCHAR(255) NULL,
    [LVALUE] NVARCHAR(MAX) NULL,
    [VERSION] DECIMAL(38) NOT NULL,
    CONSTRAINT [PK_MICROSOFTDTPROPERTIES] PRIMARY KEY ([ID])
);

GO
