-- ==========================================
-- Seed Data Script for APPROVAL GROUP MODULE
-- Database: SSCDB
-- Created: March 19, 2026
-- ==========================================

USE SSCDB;
GO

-- Seed APGROUP_MAST
IF NOT EXISTS (SELECT 1 FROM APGROUP_MAST WHERE GROUP_ID = 1)
BEGIN
    INSERT INTO APGROUP_MAST (GROUP_ID, GROUP_NAME, GROUP_CREATEDBY, GROUP_CREATEDON, GROUP_PRIORITYID)
    VALUES 
        (1, 'Finance Approval Group',   1, GETDATE(), 1),
        (2, 'Operations Approval Group',1, GETDATE(), 2),
        (3, 'HR Approval Group',        1, GETDATE(), 3);
END
GO

-- Seed APGROUP_MAP
IF NOT EXISTS (SELECT 1 FROM APGROUP_MAP WHERE MAP_ID = 1)
BEGIN
    INSERT INTO APGROUP_MAP (MAP_ID, MAP_GROUPID, MAP_PAYBYSPECIFIC, MAP_BUSPECIFIC, MAP_MAINCAT, MAP_SUBCAT, MAP_CURRENCY, MAP_CREATEDBY, MAP_CREATEDON)
    VALUES 
        (1, 1, 1, 0, 100, 200, 'U', 1, GETDATE()),
        (2, 2, 0, 1, 101, 201, 'U', 1, GETDATE());
END
GO

-- Seed APGROUP_USERMAP
IF NOT EXISTS (SELECT 1 FROM APGROUP_USERMAP WHERE MAP_ID = 1)
BEGIN
    INSERT INTO APGROUP_USERMAP (MAP_ID, MAP_GROUPID, MAP_USERID, MAP_EFFECTIVEDATE, MAP_CREATEDBY, MAP_CREATEDON)
    VALUES 
        (1, 1, 1001, GETDATE(), 1, GETDATE()),
        (2, 2, 1002, GETDATE(), 1, GETDATE());
END
GO

-- Seed PULLMATRIX_DET
IF NOT EXISTS (SELECT 1 FROM PULLMATRIX_DET WHERE MAT_ID = 1)
BEGIN
    INSERT INTO PULLMATRIX_DET (MAT_ID, MAT_UNITID, MAT_PAYBY, MAT_FLAG, MAT_MAINCAT, MAT_EMPSYSID, MAT_MAXNOS, MAT_CREATEDBY, MAT_CREATEDON, MAT_MODIFIEDBY, MAT_MODIFIEDON)
    VALUES 
        (1, 10, 'CC', 'A', 100, 2001, 5, 1, GETDATE(), 1, GETDATE()),
        (2, 11, 'PO', 'A', 101, 2002, 3, 1, GETDATE(), 1, GETDATE());
END
GO

PRINT 'Seed data inserted successfully.';
GO
